### ISSUE TITLE
[Dev] Document tool tasks and tools runner

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#1004]
- Create a Wiki page with the general concept of our tool tasks
- Explain how they're run
- Maybe a short mention of the tag template system to write MD files

**Comment by ljacqu** [comment]
Hi @sgdc3, could ask you to review? https://github.com/AuthMe/AuthMeReloaded/wiki/Tool-tasks

**Comment by sgdc3** [comment]
looks good! good job! ;)

**Comment by ljacqu** [comment]
Great, thank you :)
