### ISSUE TITLE
Improve performance of restricted user handling

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#1005]
**1. Make lookup of restrictions more efficient**
The code in `AsynchronousJoin` iterates over all restricted user entries and performs a regex split each time a player joins. This could be improved by storing the username in a map with its associated restrictions (-> O(1) lookup for each name and no String splits happening each time).

```java
    private boolean isNameRestricted(String name, String ip, String domain) {
        // ...
        boolean nameFound = false;
        for (String entry : service.getProperty(ALLOWED_RESTRICTED_USERS)) {
            String[] args = entry.split(";");
            String testName = args[0];
            String testIp = args[1];
            if (testName.equalsIgnoreCase(name)) {
               // ...
            }
        }
        return nameFound;
    }
```

**2. Do not fetch the host name unnecessarily**
Additional improvement is to only get the IP's host name if we know there is a restriction on that username. This is not an action we want to perform if we won't actually need it, cf. http://docs.oracle.com/javase/6/docs/api/java/net/InetAddress.html#getHostName%28%29

> If this InetAddress was created with a host name, this host name will be remembered and returned; **otherwise, a reverse name lookup will be performed** and the result will be returned based on the system configured name lookup service.

**3. Improve error handling**
If a line in the config does not have a `;` separating it into two parts, an exception is thrown, which is not understandable to the user (as seen in #1078). Avoid it from throwing an exception and log a sensible warning instead.

**Comment by ljacqu** [comment]
@sgdc3, can I ask you to check if it looks OK?

**Comment by sgdc3** [comment]
Looks good ;)
