### ISSUE TITLE
Bungee Problem

### ISSUE THREAD

**Issue by JugadorON** [Xephi/AuthMeReloaded#1007]
https://dev.bukkit.org/bukkit-plugins/authme-reloaded/

Spigot 1.10.2 Java 8

BungeeCord problem:

When I connect with the '/login' command, when I change servers, the session is initially kept open, but after a short time the password is requested again.

**Comment by sgdc3** [comment]
Please provide your build number (/authme info)

**Comment by sgdc3** [comment]
@JugadorON

**Comment by ljacqu** [comment]
No answer
