### ISSUE TITLE
Can't reconnect to Mysql

### ISSUE THREAD

**Issue by prozhong** [Xephi/AuthMeReloaded#101]
Its so weird....
(I promise..) There is no error in config.yml with the  database host/port/password etc.(Using Remote Mysql)
1st
AND everytime after I restart the remote mysql server, I can start my server smoothly without any error and Authme hooked to remote mysql successfully.Players could login in and all is okay.

HOWEVER after I stop MC server and start it again...
Error shows like
"ERROR NULL"
"ERROR Can't reconnect to MySQL database... Please check your MySQL informations ! SHUTDOWN..."
SEE HERE http://pastebin.com/xdW81KLi

I can't start my server and Authme can't connect to mysql until I restart my MYsql server again.

So the problem is Authme only works fine at the very first time after MYSQL remote server restarts.

I know every minecraft-server-start is  an Independent event,there must be something wrong with Mysql reconnects or Mysql remote server itself,but after I change the "useReloadCommandSupport: true" to false, errors disappear and my server starts successfully every time..

Any ideas? By the way I disable the caching,"caching: false".

2nd 
I set the "caching: false" cause I want to setup a website for user register/changepassword but there seems an old bug (I heard one year ago) that "the password change on web wont be set ingame immediately due to caching blahblahblah and blame caching",its that bug still here ?

Thx for any reply and sorry for my English

**Comment by sgdc3** [comment]
@prozhong I think caching is safe, it should update very quickly the cache...

**Comment by sgdc3** [comment]
@prozhong To find out what's the problem I have to study how authme reload command works ;)

**Comment by sgdc3** [comment]
@Xephi is going to check this ;)

**Comment by sgdc3** [comment]
Should have been fixed by @Xephi! Try latest dev build! (when jenkins will be online xD)

**Comment by Xephi** [comment]
Jenkins is online

**Comment by sgdc3** [comment]
@prozhong Try latest dev build at ci.xephi.fr ;)

**Comment by prozhong** [comment]
Thanks for your quick debug work :+1: 
However my server is running with "useReloadCommandSupport: false" and I may maintain it next weekend..So is there any thing bad when "useReloadCommandSupport: false" and "caching:false"?

**Comment by sgdc3** [comment]
All the issue should have been fixed but we need your help to test them ;)

**Comment by prozhong** [comment]
I checked again on my local test server , your fix works !
No error on 2nd restart :+1:

**Comment by Trojaner25** [comment]
Just for reference: may be related to #34
