### ISSUE TITLE
Laravel player account

### ISSUE THREAD

**Issue by Yub0** [Xephi/AuthMeReloaded#1012]
Hi,
I would like to know how I can link AuthMe to my website. I built him with Laravel and the cipher is AES-256-CBC with salt.

Thank you

**Comment by sgdc3** [comment]
@ljacqu you're the hash expert xD

**Comment by ljacqu** [comment]
Are you really storing passwords encrypted with AES? First time I hear this—what's the morive behind it?

In case there's some confusion and you're actually using BCrypt (as seems to be default in Laravel – https://laravel.com/docs/5.3/hashing) then you just need to set the hash setting in config.yml to `bcrypt` :)
