### ISSUE TITLE
Long attach to the server on 1.11

### ISSUE THREAD

**Issue by RikoDEV** [Xephi/AuthMeReloaded#1013]
At 1.11 I noticed that after installation AuthME (latest build) attach to the server is long and player gets a time out. 

**This only occurs on version 1.11 to 1.10 and older that was not there.**
@ljacqu @sgdc3

**Comment by sgdc3** [comment]
@RikoDEV Could you post your config and some timings report?

**Comment by RikoDEV** [comment]
Timing: https://timings.aikar.co/v2/?id=e4315405d730433dbfeb7c15a1818ef4
Config: http://pastebin.com/UEQEma3d

**Comment by sgdc3** [comment]
Please join with some accounts while recording timings, i'm trying to figure out if we have some performance issue

**Comment by RikoDEV** [comment]
https://timings.aikar.co/v2/?id=bc1b65419a2b4dac8f1ce771a5b6d950

**Comment by ljacqu** [comment]
@sgdc3 What's your interpretation on the timings report? I... Ever since the remake of the site I'm struggling to understand what I'm looking at.

**Comment by sgdc3** [comment]
@ljacqu this report is useless as it doesn't show any logged player....

**Comment by ljacqu** [comment]
In that case @RikoDEV  may we kindly ask you to do another report where you join / log in a few times?
