### ISSUE TITLE
auths.db (Authme) convert to authme.db (AuthmeReloaded)

### ISSUE THREAD

**Issue by bertek41** [Xephi/AuthMeReloaded#1017]
Hey i have bungeecord server and authmereloaded support bungeecord but authme not so how can i convert auths.db (Authme) to authme.db (AuthmeReloaded) ?
Here is my auths.db (a few lines):
`posezone:$SHA$aa1cf1c8474b0f97$2dba315915de0a153118bef494a28a668fa99b9a594fd507847cca416a2151b3:88.228.109.230:1477861743672:0.0:0.0:0.0:world:your@email.com
viesto:$SHA$cf7af5ebdb503de4$b38947638b4350950d4b85e705ff1b538c41682a5260fda65beaf4e78290d1d6:78.160.120.180:1477936099015:0.0:0.0:0.0:world:your@email.com
sebahattin38tr:$SHA$9ae276625f558812$876090b4fa671a72207de957e2f79bba6d7464ec8447e1e43a05e4b58125601f:88.229.248.178:1477937389457:0.0:0.0:0.0:world:your@email.com
01pandik01:$SHA$ee39334acd68f35b$6adc75cb40287120c47ff43355e0a3d4a75f78cbdc7bcb9215b62f637a243791:78.164.28.54:1477937889845:0.0:0.0:0.0:world:your@email.com
someras:$SHA$4601c7ff0c77914e$f1d3199151335c7cc75e457e7c2195aaa0113fc9db4a15cc15644ea3512e32d5:95.7.177.174:1477940630971:0.0:0.0:0.0:world:your@email.com`

**Comment by sgdc3** [comment]
Just put it in the plugin folder and set the backend to "flatfile" ;)

**Comment by ljacqu** [comment]
Indeed, set `backend: FLATFILE` in config.yml and keep the file as auths.db. First time you start up the server, it will create an authme.db automatically with all of the data :)

**Comment by bertek41** [comment]
So i install authmereloaded start the server then stop. Then delete authme.db and in the config set backend to FLATFILE and drag and drop the auths.db to authme folder then start server?

**Comment by ljacqu** [comment]
Yes, that sounds good. You don't need to start & stop the server first, though, but it's fine if you want to do it.

**Comment by ljacqu** [comment]
@bertek41 Please let us know if it worked, in which case we can close this issue (or you can)

**Comment by bertek41** [comment]
I will try in maintenance wait.

**Comment by ljacqu** [comment]
@bertek41 SQLite will load whatever file name you have in `DataSource.mySQLDatabase` + ".db", typically the setting is set to "authme," i.e. it wants to load "authme.db"

I'm going to assume, given the error, that you tried to rename your old file to authme.db. Please don't do that; keep the flatfile DB you want to convert from as auths.db. That file name is not configurable.

**Comment by bertek41** [comment]
I keep auths.db but this time plugin don't see this file it created new authme.db and say register...

**Comment by DNx5** [comment]
have you set `` backend: FLATFILE `` in config.yml?

**Comment by ljacqu** [comment]
We're remembering the value wrong, it needs to be `FILE` xD

@bertek41, in your config.yml please set:
```yaml
    backend: 'file'
```

on start up you should get a message "[AuthMe] Database successfully converted from FILE to SQLITE". Sorry for the confusion.

**Comment by bertek41** [comment]
I will try and how can i add aliases for a command for example "/login" to "/giris" ?

**Comment by ljacqu** [comment]
Please let us know if it worked. 
Aliases: http://wiki.bukkit.org/Bukkit.yml#aliases

**Comment by bertek41** [comment]
In plugin.yml there is a aliases for command if i put "/giris" in "/login" this work?

**Comment by ljacqu** [comment]
```yml
aliases:
    giris:
    - "login $1-"
```
