### ISSUE TITLE
Transfer authme auths.db to authme reloaded authme.db

### ISSUE THREAD

**Issue by aBo0oDGamer** [Xephi/AuthMeReloaded#1022]
i have server and i run on it authme and i want to upgrade to authme reloaded v5.2 because i have a problem on authme so i want to upgrade to authme reloaded it work very well but i want transfer the auths.db to authme.db but i can't D: how i can transfer it?
help please

**Comment by ljacqu** [comment]
Can you follow what's in #1017? I think this is the same use case

**Comment by aBo0oDGamer** [comment]
i did the same thing but wen i change the anthme reloaded config.yml backend: FLATFILE wen i start the server the config change it to SQLITE alone

**Comment by ljacqu** [comment]
that's normal, it should have migrated your users from auths.db during that. please check if they are present.

**Comment by ljacqu** [comment]
Sorry, please set your backend to `FILE`:

```yaml
    backend: 'file'
```

After that you should see a success message being output:
> [AuthMe] Database successfully converted from FILE to SQLITE

**Comment by aBo0oDGamer** [comment]
ok i change it to 'file' and i see the message '[AuthMe] Database successfully converted from FILE to SQLITE'
and in the authme file create auths.db but the plugin still using authme.db why do i have to make somthing? or give me all the steps to make the authme reloaded use auths.db please
and thanks for helping

**Comment by ljacqu** [comment]
> and in the authme file create auths.db but the plugin still using authme.db why do i have to make somthing?

What? auths.db is your old file, correct? AuthMe will transfer the entries inside auths.db to authme.db. 

All the steps would be:
1. place your auths.db in the AuthMe folder
1. set `backend` to `FILE`
1. on startup, entries will be transferred to authme.db and backend is set to `SQLITE`

**Comment by aBo0oDGamer** [comment]
OMG!!!!!
Thaaaaaaaaaaaaaaaaaaaaaaaaaaaaaanks very much 
finely this problem dissolved

**Comment by ljacqu** [comment]
Excellent—thanks for the feedback. :smile:
