### ISSUE TITLE
Email Recovery not working

### ISSUE THREAD

**Issue by hiimurfather** [Xephi/AuthMeReloaded#1024]
Apparently, I have a smtp set up. Which works perfectly for the enableEmailRegistrationSystem option.
BUT not the email recovery. When I tried using /email recovery myemail@asd.com
I got this on the console 
[21:41:49] [Server thread/WARN]: [AuthMe] Failed to send a mail to [myemail@asd.com]: [EmailException]: Sending the email to the following server failed : smtp.gmail.com:465
ofc the myemail@asd.com is a make-up one.
I have no idea how is this happening.

**Comment by ljacqu** [comment]
If you have writing to authme.log enabled, please post the full error from there. Otherwise please enable logging in config.yml and post the full error

**Comment by hiimurfather** [comment]
Yes I do.
http://pastebin.com/JehZJTdW

**Comment by hiimurfather** [comment]
Yes I do
http://pastebin.com/7rhucvM3

**Comment by ljacqu** [comment]
Is your /authme version below 5.2-b1452? ;) This looks like #999 to me

**Comment by hiimurfather** [comment]
oh welp yes.
I downloaded from the spigot page and thought it was a stable version.
I'll try and see if the lastest one fix this.

**Comment by hiimurfather** [comment]
huuhh
I cant go to Xephi's Jenkins.

**Comment by ljacqu** [comment]
Oh my, same here. For the time being there's an alternative download linked on the readme :)

**Comment by ljacqu** [comment]
Please let us know if switching to a higher build fixes your issue

**Comment by sgdc3** [comment]
@ljacqu I contacted  @Xephi about the offline jenkins, still waiting for an answer, i'll let you know.

**Comment by ljacqu** [comment]
@sgdc3 Excellent, thank you! :smile:

**Comment by hiimurfather** [comment]
Yup. It did fix it.
Sorry for the late answer btw.
