### ISSUE TITLE
Login/Register messages not apearring and timeout is not working...

### ISSUE THREAD

**Issue by 3dv1zz** [Xephi/AuthMeReloaded#1025]
####Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!

### What behaviour is observed:
What happened? Login/Register messages not working and timeout is not working (after the 30 seconds player is not being kicked). You cant move without login/register but messages not appearing... i tried reseting config, redownloading everything but still same thing...

### Steps/models to reproduce:
The actions that cause the issue. I dont know, somehow this thing appeared, and messages not showing from now ...

### Plugin list:
This can be found by running `/pl`
There is a lot of plugins.....
http://www.part.lt/perziura/f7c65189f215764bf3d326c262489a69369.png
http://www.part.lt/perziura/c1091d122a335749ad176a404a871c99757.png

### AuthMe build number:
This can be found by running `/authme version`
3.4 ... Any latest version isn't working the .jar file cannot be loaded....

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensible data)
http://pastebin.com/V3vTif0a

**Comment by sgdc3** [comment]
We don't support old versions, sorry.

>Any latest version isn't working the .jar file cannot be loaded....

What's the issue? Could you describe your server setup? (Java version, Spigot/Paper version)
