### ISSUE TITLE
Add more tags/replacement for forced commands (lazy)

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#1026]
With issue #411 we introduced the new forced commands layout. In that issue, replaceable tags were mentioned, e.g. for the player's display name such that this can be used in the commands.

Make more tags available to the user. We should fetch values for tags lazily, i.e. if IP address tag is not used anywhere don't get it each time forced commands are run. 

Possible tags: player nick, IP address, country name, country code.

**Comment by ljacqu** [comment]
@Twonox commands.yml now lists the newly available tags:
https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/resources/commands.yml

Added %nick, %ip and %country. Is this OK to close or do you think something is missing?

**Comment by Twonox** [comment]
All is good.

**Comment by ljacqu** [comment]
Thanks!
