### ISSUE TITLE
Alternative language support

### ISSUE THREAD

**Issue by Kixot14** [Xephi/AuthMeReloaded#1027]
Maybe should add the ability to change the language for messages ??

I think is a great idea, but it is difficult to implement, cause this ability shuld be global, not only for AuthMe. ...Create something like GlobalMessagesFolder, which will be store all messages file for the current server plugins.

**Comment by sgdc3** [comment]
This is already in the 5.3 TODO list ;)

**Comment by ljacqu** [comment]
@sgdc3 plugin-wide translation is planned for 5.3? ;)

**Comment by sgdc3** [comment]
Don't you remember? We talked about 5.3 as "The translation update" ;)

**Comment by sgdc3** [comment]
> I think is a great idea, but it is difficult to implement, cause this ability shuld be global, not only for AuthMe. 
Oh i missed this line, no, we plan only to allow translation of all authme messages xD
