### ISSUE TITLE
[Request] Register with password and email at the same time.

### ISSUE THREAD

**Issue by koca2000** [Xephi/AuthMeReloaded#1029]
Is it possible to edit registration command to "/register <password> <password again> <email>"? I can't see even any function to set player email in api.

**Comment by ljacqu** [comment]
Duplicate of #427

**Comment by koca2000** [comment]
Can I force players to use "/register <password> <email>" as only possible command?

**Comment by sgdc3** [comment]
in our config:

        # Allowed commands for unauthenticated players
        allowCommands: 
        - '/login'
        - '/register'
        - '/l'
        - '/reg'
        - '/email'
        - '/captcha'

**Comment by koca2000** [comment]
Sorry Github have changed my message. I wrote "/register (password) (email)".

**Comment by sgdc3** [comment]
not atm, we need to implement that

**Comment by koca2000** [comment]
Would you implement it before christmas?

**Comment by sgdc3** [comment]
I have no time for it, maybe @ljacqu @Gnat008 or @Xephi ? ;)

**Comment by ljacqu** [comment]
Yeah maybe on Friday or Saturday, I'll assign the other issue to me ;) If someone else wants to do it you can just unassign me
