### ISSUE TITLE
No field with type [LItemStack on Logout

### ISSUE THREAD

**Issue by LordDWT** [Xephi/AuthMeReloaded#1039]
### What behaviour is observed:
Error when trying to /logout

### What behaviour is expected:
Smooth /logout

### Steps/models to reproduce:
/Login then /logout

### Plugin list:
Plugins (32): CoreProtect, dynmap, WorldEdit, Essentials, Trading, LWC, Multiverse-Core, ProtocolLib, WorldGuard, NoCheatPlus, Shopkeepers, EssentialsProtect, EssentialsChat, EssentialsAntiBuild, PermissionsEx, WGCustomFlags, Multiverse-Portals, EssentialsSpawn, GriefPrevention, PvPManager, BetterAlias, PvEManager, Orebfuscator4, AntiXRay, Dynmap-Essentials, AuthMe, MobArena, Dynmap-WorldGuard, Jail, Magic, Multiverse-NetherPortals, JDynmapGriefPrevention
### Environment description
Standalone

### AuthMe build number:
>version authme
[15:32:44 INFO]: AuthMe version 5.2-SNAPSHOT-b1502
[15:32:44 INFO]: The first authentication plugin for the Bukkit API!
[15:32:44 INFO]: Website: http://dev.bukkit.org/bukkit-plugins/authme-reloaded/
[15:32:44 INFO]: Authors: Xephi, sgdc3, DNx5, timvisee, games647, ljacqu and Gnat008

### Error Log:
https://ghostbin.com/paste/kszuv

### Configuration:
https://ghostbin.com/paste/uaus8

**Comment by Eufranio** [comment]
I think ProtocolLib didn't update to 1.11 yet. Could you test disabling **protect inventory**?

**Comment by LordDWT** [comment]
ProtocolLib is updated to 1.11.
https://www.spigotmc.org/resources/protocollib.1997/
http://ci.dmulloy2.net/job/ProtocolLib/345/

I have set Protect Inventory to false.
/Logout works correctly now.  (Just shows inventory on login)

Thank you!

**Comment by Eufranio** [comment]
I think you shouldn't close this issue, since it still a problem, you just work around the issue 😄

**Comment by LordDWT** [comment]
That is true.  I have Reopen the issue.
Thanks for the work around.

**Comment by sgdc3** [comment]
@games647 Hello, any way to fix this? ;)

**Comment by games647** [comment]
They changed the protocol definitions from a array to a list :(

**Comment by ljacqu** [comment]
@games647 Thank you!
@LordDWT Please check that this fixes your issue, with build n. 1504 or above — http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by LordDWT** [comment]
@ljacqu Yes this version does fix the error.
@games647 Thank you for your help!
@Eufranio Thank you for your help!
