### ISSUE TITLE
Error on console

### ISSUE THREAD

**Issue by MithrandirCraft** [Xephi/AuthMeReloaded#1043]
Hi, I found this random error on console after a user tried to log out:
https://hastebin.com/morafofuxe.vbs

Authme 1.6.2-SNAPSHOT
Spigot: 1.11

**Comment by sgdc3** [comment]
> Authme 1.6.2-SNAPSHOT
What the... xD

**Comment by sgdc3** [comment]
Please update to latest build, this issue have been fixed by @games647
