### ISSUE TITLE
Custom delayJoinMessage

### ISSUE THREAD

**Issue by dartasen** [Xephi/AuthMeReloaded#1044]
I have opened an issue 20 days ago wich has been set resolved but the feature doesn't work for me.
I use AuthMe v5.2-SNAPSHOT (build: 1506) and EssentialsX 2.0.1 for custom message but when a player login, the default message is send : 
http://prnt.sc/dpcub7

### EssentialsX config (works without delayJoinMessage) :
# You can set a custom quit message here, set to "none" to disable.
# You may use color codes, use {USERNAME} the player's name or {PLAYER} for the player's displayname.
custom-quit-message: '&7[&4-&7] &7{USERNAME} &7a quitté la partie'

Old issue : https://github.com/Xephi/AuthMeReloaded/issues/1030

**Comment by Eufranio** [comment]
Yep, confirm that it isn't using the Essentials message.

**Comment by sgdc3** [comment]
> Just use a plugin that change the message on join, authme will save the changed message.

Essentials doesn't allow us to obtain the custom message, you need to use another plugin and keep essential's option to "none".

**Comment by ljacqu** [comment]
@sgdc3 Maybe could you suggest such a plugin?

**Comment by sgdc3** [comment]
Sure, JMP should do the trick: https://dev.bukkit.org/projects/join-message-plus

**Comment by ljacqu** [comment]
@sgdc3 Thanks :smile:

**Comment by sgdc3** [comment]
Whoops nope

**Comment by sgdc3** [comment]
It broadcasts the message :/

**Comment by sgdc3** [comment]
This should work: https://www.spigotmc.org/resources/custom-join.1364/

**Comment by dartasen** [comment]
And you couldn't add an option to integrate custom message for the delayJoinMessage directly with AuthMe rather than using an other plugin just for this little detail?

**Comment by sgdc3** [comment]
We could, but not before authme 5.3

**Comment by ljacqu** [comment]
@dartasen please verify

**Comment by dartasen** [comment]
This time, the option no longer works... We see the joined message before logging (option however enabled).

**Comment by ljacqu** [comment]
@dartasen I've created #1080 for this (we can't reopen issues of a completed milestone), maybe you can share your config.yml in the new issue
