### ISSUE TITLE
DOC MISSING: Countries Whitelist/Blacklist

### ISSUE THREAD

**Issue by Oruss7** [Xephi/AuthMeReloaded#1045]
In readme, link to dev.bukkit.

Thanks

**Comment by ljacqu** [comment]
@Oruss7 Could you elaborate please?

**Comment by Oruss7** [comment]
In the readme.md, they are "country code" for country blacklist. The link send to bukkit.dev, who send to the config example... who have no list of country...

My resquest is: Can you please list country code on github ?

**Comment by sgdc3** [comment]
Done, thank you ;)

**Comment by Oruss7** [comment]
thank to you
