### ISSUE TITLE
Command to change language

### ISSUE THREAD

**Issue by Twonox** [Xephi/AuthMeReloaded#1049]
Adding a command to change authme's language from the game will be useful.
`/authme lang <languageCode>`

**Comment by sgdc3** [comment]
why?

**Comment by Twonox** [comment]
It's not very important request, but sometimes it will simplify a bit my test with authme's language.

**Comment by Twonox** [comment]
Because we always need to go Authme's config, find language setting etc not very practical some times.

**Comment by ljacqu** [comment]
While I agree, the thing is how will this scale? Right now it seems useful to be able to change the language code, in two weeks it's useful to change the registration type... and we end up with many commands, many permission nodes, for individual use cases. I'm not sure I like this.

**Comment by Twonox** [comment]
I agree what you mean. I remind this is not an important request.

**Comment by ljacqu** [comment]
Thanks for understanding. Nevertheless, if you have a good suggestion to handle this, we're open for suggestions. Also relates to #659.
