### ISSUE TITLE
Wrong 'messageInterval'

### ISSUE THREAD

**Issue by Twonox** [Xephi/AuthMeReloaded#1050]
```
 //Send every X seconds a message to a player to
 //remind him that he has to login/register
 messageInterval: 5
```
This parameter doesn't affect the interval between remind messages, it affect the time which must expire to start remind messages after connection time of the player.

**If  _messageInterval = 5_ :**

Twonox joined the game.
`[5 seconds delay]`
Please login with....
`[2 seconds delay]`
Please login with....
`[2 seconds delay]`
Please login with....

The interval between remind messages is always 2 seconds.

**Comment by sgdc3** [comment]
I just checked the code... it doesn't make any sense.

```Java
MessageTask messageTask = new MessageTask(name, messages.retrieve(key), bukkitService, playerCache);
bukkitService.runTaskTimer(messageTask, 2 * TICKS_PER_SECOND, interval * TICKS_PER_SECOND);
```

The second parameter of runTaskTimer should be the initial delay, not the interval between the runs! Could it be a bug with latest spigot versions?

**Comment by sgdc3** [comment]
Ok, found a but in our BukkitService class....

**Comment by sgdc3** [comment]
Epic fail:

```Java
    public BukkitTask runTaskTimer(BukkitRunnable task, long delay, long period) {
        return task.runTaskTimer(authMe, period, delay);
    }
```

**Comment by sgdc3** [comment]
Fixed, thank you for the report @Twonox ;)
