### ISSUE TITLE
Disable AuthmeReloaded help

### ISSUE THREAD

**Issue by xyblues** [Xephi/AuthMeReloaded#1051]
I don't want to enable this feature, I want to be able to turn him off in the profile.
Thank you very much. Thank you for the great AuthMe Reloaded plugin.
![image](https://cloud.githubusercontent.com/assets/15712089/21636864/3b330bae-d29f-11e6-9b0a-6f11f8d3dd95.png)

**Comment by ljacqu** [comment]
In messages/help_xx.yml you can set the sections to empty texts to disable them. Is this sufficient?
If no, please explain what you expect - what needs to be added? How should it behave?

**Comment by Twonox** [comment]
#758

**Comment by xyblues** [comment]
OK, I set the empty text to disable them.
Thank you very much.

**Comment by ljacqu** [comment]
@xyblues Thanks for the feedback, glad it can be solved this way.
