### ISSUE TITLE
'SaveQuitLocation: false' doesn't work

### ISSUE THREAD

**Issue by Twonox** [Xephi/AuthMeReloaded#1057]
When `teleportUnAuthedToSpawn` is `true`, we are teleported on our logout location after login even if `SaveQuitLocation` is `false`.
I believe that SaveQuitLocation was affecting that, with older builds of authme.

**Comment by sgdc3** [comment]
@Twonox could you post your config please? ;)

**Comment by sgdc3** [comment]
/**
     * Teleports the player according to the settings after having successfully logged in.
     *
     * @param player the player
     * @param auth corresponding PlayerAuth object
     * @param limbo corresponding PlayerData object
     */
    public void teleportOnLogin(final Player player, PlayerAuth auth, LimboPlayer limbo) {
        if (settings.getProperty(RestrictionSettings.NO_TELEPORT)) {
            return;
        }

        // #856: If PlayerData comes from a persisted file, the Location might be null
        String worldName = (limbo != null && limbo.getLocation() != null)
            ? limbo.getLocation().getWorld().getName()
            : null;

        // The world in PlayerData is from where the player comes, before any teleportation by AuthMe
        if (mustForceSpawnAfterLogin(worldName)) {
            teleportToSpawn(player, true);
        } else if (settings.getProperty(TELEPORT_UNAUTHED_TO_SPAWN)) {
            if (settings.getProperty(RestrictionSettings.SAVE_QUIT_LOCATION) && auth.getQuitLocY() != 0) {
                Location location = buildLocationFromAuth(player, auth);
                teleportBackFromSpawn(player, location);
            } else if (limbo != null && limbo.getLocation() != null) {
                teleportBackFromSpawn(player, limbo.getLocation());
            }
        }
    }

**Comment by sgdc3** [comment]
```Java
            } else if (limbo != null && limbo.getLocation() != null) {
                teleportBackFromSpawn(player, limbo.getLocation());
            }
```

What's the logic behind this? @DNx5

**Comment by Twonox** [comment]
No need to my config.
The problem is with authme's playerdata. When I stop the server and I delete my authme's data, I'm not teleported to my logout location. So, `SaveQuitLocation: false` doesn't reset the stored data. and doesn't stop storing (I'm once again teleported in my logout location after reset).

**Comment by DNx5** [comment]
@sgdc3 I don't remember i write that part.

@Twonox ``SaveQuitLocation`` is only used to save the player's location into database. if you want players to be teleported to spawn on login, use ``ForceSpawnLocOnJoin``

**Comment by Twonox** [comment]
What is its utility in this case ?

**Comment by sgdc3** [comment]
@DNx5 maybe @ljacqu is thhe author of that part of code, idk

**Comment by ljacqu** [comment]
@sgdc3 @DNx5 It originally stems from me at 68d5145cd78132b1c761ce723d50ed1b8478bb50 (but this is moved code from elsewhere...)

```java
        } else if (settings.getProperty(TELEPORT_UNAUTHED_TO_SPAWN)) {
            if (settings.getProperty(RestrictionSettings.SAVE_QUIT_LOCATION) && auth.getQuitLocY() != 0) {
                Location location = buildLocationFromAuth(player, auth);
                teleportBackFromSpawn(player, location);
            } else {
                teleportBackFromSpawn(player, limbo.getLoc());
            }
        }
```

Notice if (TELEPORT_UNAUTHED_TO_SPAWN)) -> if this is enabled and the user logs in, he should be teleported back to his original location. If we save it in the DB take it from there, otherwise we take it from the LimboPlayer

**Comment by ljacqu** [comment]
https://github.com/AuthMe/AuthMeReloaded/wiki/Spawn-Handling

> settings.restrictions.SaveQuitLocation must be true for the quit location to be saved in the database. If false, players are teleported back to the location in which they would have joined without changes from AuthMe.

**Comment by sgdc3** [comment]
Then we should change the TELEPORT_UNAUTHED_TO_SPAWN description.

**Comment by sgdc3** [comment]
```
    @Comment({
        "Should not logged in players be teleported to the spawn?",
        "After the authentication they will be teleported back to",
        "their normal position."})
    public static final Property<Boolean> TELEPORT_UNAUTHED_TO_SPAWN =
        newProperty("settings.restrictions.teleportUnAuthedToSpawn", false);
```
Looks already correct.
@ljacqu does configme update comments on settings?

**Comment by ljacqu** [comment]
@sgdc3 No, ConfigMe doesn't detect that comments have changed, but next time it rewrites the config (e.g. because we notice that a property is missing) the comments will be updated.

**Comment by Twonox** [comment]
It's a good thing that `teleportUnAuthedToSpawn: true` teleport us on our logout location without set `SaveQuitLocation: true` because now this is not like #815. `teleportUnAuthedToSpawn: true` now doesn't change player direction, but `SaveQuitLocation: true` does it.

**Comment by DNx5** [comment]
@Twonox because we still doesn't save player's pitch and yaw into the database.

**Comment by Twonox** [comment]
Now, I need to set `SaveQuitLocation: true` to return on last position before logout when `teleportUnAuthedToSpawn` is `true`
Is it normal ?
A don't appreciate this... :/

**Comment by ljacqu** [comment]
This issue is obsolete. Let's discuss it elsewhere, for example in a new one. What you say is correct: `SaveQuitLocation: false` literally says not to save the quit location. It is, however, a breaking change from 5.2.

**Comment by Twonox** [comment]
Please read that: https://github.com/Xephi/AuthMeReloaded/issues/1057#issuecomment-271085214
And you will understand.
