### ISSUE TITLE
Username too short / too long

### ISSUE THREAD

**Issue by FelixLudi** [Xephi/AuthMeReloaded#1058]
####Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!

### What behaviour is observed:
What happened?
Whenever I am running AuthMe on the aternos.org 1.11.2 server people get the message
"Username too short or too long"

### What behaviour is expected:
What did you expect?
A simple enter on the server and the /register pop-up.

### Steps/models to reproduce:
The actions that cause the issue
...are on the aternos.org 1.11.2 bukkit server running the AuthMe 5.2 beta 3.

### Plugin list:
This can be found by running `/pl`
Commandspy, Worldedit, PEX, Anticheatreloaded, adminessentials

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Aternos server, idk how to describe it

### AuthMe build number:
This can be found by running `/authme version`
Not able to get onto the server, not able to do /authme unless I go for the console which I should if neccessary

### Error Log:
Pastebin/Hastebin/Gist link of the error logo or stacktrace (if any)

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)

**Comment by ljacqu** [comment]
Please share the following portions of your config.yml:
```yaml
        # Minimum allowed username length
        minNicknameLength: 3
        # Maximum allowed username length
        maxNicknameLength: 16
```
```yaml
        # Regex syntax of allowed characters in the player name.
        allowedNicknameCharacters: '[a-zA-Z0-9_]*'
```

**Comment by FelixLudi** [comment]
# Minimum allowed username length
        minNicknameLength: 4
        # Maximum allowed username length
        maxNicknameLength: 16

timeout: 30
        # Regex syntax of allowed characters in the player name.
        allowedNicknameCharacters: '[a-zA-Z0-9_]*'
        # How far can unregistered players walk?
        # Set to 0 for unlimited radius

**Comment by FelixLudi** [comment]
Appareantly it works now, but for some reason I can not use /register, even tho I am opped and have set my commands in the PEX to '*' (anything).
What could be the problem?

**Comment by FelixLudi** [comment]
And now that I have removed AuthMe so people can play on my server without getting kicked after a brief amount of time, we are all frozen. We can only jump and move in the jump but we cant move normally.
Please send help

**Comment by ljacqu** [comment]
I don't know how well `*` works, but you can find our permissions at https://github.com/AuthMe/AuthMeReloaded/blob/master/docs/permission_nodes.md
The frozen thing happens because before you log in, AuthMe "takes away" some stuff like fly speed and OP status so that it can't be abused before proper authentication. If you have Essentials you can use `/speed` to restore walk speed.

**Comment by FelixLudi** [comment]
Still cannot register even if I gave all the groups the register and login commands it still says you are not authenticated or something like that.

**Comment by ljacqu** [comment]
Please post the exact message you're getting. This sounds like you're trying to do /register even though you're already registered.

**Comment by FelixLudi** [comment]
You don't have permission to use this command!

Dark red letters.

**Comment by ljacqu** [comment]
Can we see your permissions config file?

**Comment by FelixLudi** [comment]
groups:
  Member:
    options:
      prefix: '&f[&9Member&f]'
      default: true
    permissions:
    - modifyworld.*
    - -bukkit.command.*
    - -minecraft.command.help
    - -commandspy.*
    - authme.player.changepassword
    - authme.player.login
    - authme.player.logout
    - authme.player.register
    - authme.player.unregister
  Cigan:
    options:
      prefix: '&8[&6Cigan&8]'
    permission:
    - modifyworld.*
    - -bukkit.command.*
    - -minecraft.command.help
    - -commandspy.*
    - authme.player.changepassword
    - authme.player.login
    - authme.player.logout
    - authme.player.register
    - authme.player.unregister
  Owner:
    options:
      prefix: '&f[&cOwner&f]'
    permission:
    - authme.*
schema-version: 1
users:
  7f5d76d2-7dd0-3a0c-bd6d-3de44b561ccf:
    group:
    - Owner
    options:
      name: FelixLudi

**Comment by FelixLudi** [comment]
no spaces unfortunately, but my friend managed to get in, shes default by default. so i took my owner ranks and put a -authme.* to get access to all commands
but still after /reload and /pex reload still nothing.

**Comment by ljacqu** [comment]
Probably need to rename `permission:` to `permissions:`

**Comment by FelixLudi** [comment]
Dayum, thats like motherfucking : in programming. Pisses the hell out of you, thanks for replying.

**Comment by ljacqu** [comment]
Thanks for providing all the information :P If after /reload this solves your problem, can you close this issue? Thanks

**Comment by FelixLudi** [comment]
Yea i reloaded and fixed it, damn. Imma close it afterwards, thanks for the support.
