### ISSUE TITLE
ChatGuard error.

### ISSUE THREAD

**Issue by Dimatert9** [Xephi/AuthMeReloaded#106]
http://pastebin.com/mv8DXxJK

**Comment by Maxetto** [comment]
I think this is caused because we changed the API method and ChatGuard uses the old one.

Waiting for confirmation from @Xephi

**Comment by Xephi** [comment]
Erf, yep :/ You need to contact ChatGuard author :/

**Comment by Xephi** [comment]
Can't find any source :/ i'll ask him to released them , or do the change

Xephi

**Comment by Xephi** [comment]
Fixed in our side, we'll provide our old API and our new API at the same time :/
