### ISSUE TITLE
Is there a way to don't save AuthMe playerdata?

### ISSUE THREAD

**Issue by Eufranio** [Xephi/AuthMeReloaded#1062]
Even using MySQL in my network, my lobby server is filled with useless playerdata files from AuthMe. I have a plugin to purge the normal playerdata (from Essentials and minecraft), but AuthMe creates new and new files always...

**Comment by ljacqu** [comment]
We have an issue to disable LimboPlayer storage that I can link later. You mention the ability to store limboplayers in mysql – I'd like to edit this issue to be about that.

**Comment by Eufranio** [comment]
I mean specifically disable the whole playerdata. All important data is stored in MySQL in my situation. This issue is with the lobby server, no need to have extra player data because all players are teleporter to spawn when joining, and dont have nothing to do with playerdata (minecraft and/or AuthMe)

**Comment by Twonox** [comment]
#880 
I would like too. Lobby servers doesn't need this storage.
