### ISSUE TITLE
MySql SSL needs to be fixed.

### ISSUE THREAD

**Issue by woodzykiler** [Xephi/AuthMeReloaded#1063]
####Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!
just enable MySQL
### What behaviour is observed:
What happened?
08:55:21 [WARNING] Lobby > Tue Jan 10 08:55:21 EST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You  need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
### What behaviour is expected:
What did you expect?
Not that  lol
### Steps/models to reproduce:
The actions that cause the issue
Turning on MySql on the plugin
### Plugin list:
This can be found by running `/pl`

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Bungee, Subbungee, Spigot 1.11.2, MySql
### AuthMe build number:
This can be found by running `/authme version`
1384
### Error Log:
Pastebin/Hastebin/Gist link of the error logo or stacktrace (if any)
look up
Here is what you all need to change on YOUR side. in the file for connection to the MySql
and of course change as needed 🖌 

Put the useSSL=false at the end of the name database:
   <property>
      <name>javax.jdo.option.ConnectionURL</name>
      <value>jdbc:mysql://localhost/metastore?useSSL=false</value>
      <description>metadata is stored in a MySQL server</description>
   </property>

Also, on a side note every one has the same dam IP.... and non of the previous ideas are working

**Comment by sgdc3** [comment]
> 1384

Please update to latest build

**Comment by games647** [comment]
>Also, on a side note every one has the same dam IP

I guess the localhost ip? Then activate bungeecord in the spigot config and ipforward in the bungeecord config

**Comment by woodzykiler** [comment]
the bungee IP forword is set to true in the config, side note everything runs in offline mode
[config.txt](https://github.com/Xephi/AuthMeReloaded/files/696569/config.txt)

**Comment by games647** [comment]
>the bungee IP forword is set to true in the config, side note everything runs in offline mode

You also have to activate it in spigot.

**Comment by woodzykiler** [comment]
[spigot.txt](https://github.com/Xephi/AuthMeReloaded/files/699183/spigot.txt)

im a say that i do?

**Comment by games647** [comment]
ok it's activated there

**Comment by woodzykiler** [comment]
so with them active, what am i missing? 
possable interacting plugins? 
Authme-reloaded, AuthMeBridge, SubServers
And as for the MySql issue thats on your end

**Comment by woodzykiler** [comment]
any word on the MySql change? and my everyone has the same IP issue?

**Comment by sgdc3** [comment]
whoops, misread your comment

**Comment by sgdc3** [comment]
Why did you disable ssl?

**Comment by woodzykiler** [comment]
I disabled the ssl to fix that issue and it didn't effect it what so ever. So thaws why I relive its your end with the login stuff

**Comment by sgdc3** [comment]
Our code is fine, it could be a librery issue but we didn't update any library recently... Could you please try to reinstall your mysql server?

**Comment by woodzykiler** [comment]
The mysql server is on the same machine and had ssl enabled first. Then it was disabled. I started with a bland slate of a box only 3 months the ago everything is windows based

**Comment by sgdc3** [comment]
Ok, i'll add an option to disable SSL

**Comment by woodzykiler** [comment]
Wjats if people have a remote server for that? And did look at my weblink?

**Comment by sgdc3** [comment]
>And did look at my weblink?

Yes

>Wjats if people have a remote server for that?

What do you mean? :/

**Comment by woodzykiler** [comment]
U said about having the choice for the ssl .but what if someone has remote database and needs ssl turned on?

**Comment by sgdc3** [comment]
If you need ssl just fix your setup.

**Comment by woodzykiler** [comment]
There no fix for my end... Its your end you guys need to implant the new mysql usessl code

**Comment by sgdc3** [comment]
@woodzykiler nope....

**Comment by sgdc3** [comment]
@woodzykiler I added the option to disable SSL, could you check if it fixes your issue?

**Comment by woodzykiler** [comment]
Sure thing when I get home

**Comment by woodzykiler** [comment]
Build #1530, i didnt see a SSL anywhere in the New config file.
Also no change

**Comment by sgdc3** [comment]
DataBase > mySQLUseSSL: true

**Comment by woodzykiler** [comment]
Where do i type that in?

Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by sgdc3** [comment]
Under DataBase

**Comment by woodzykiler** [comment]
So in the plugin config file? Or some kind of command in the mysql window

**Comment by sgdc3** [comment]
```YAML
DataBase:
    ...
    mySQLUseSSL: false
    ...
```

In config.yml

**Comment by woodzykiler** [comment]
[config.txt](https://github.com/Xephi/AuthMeReloaded/files/708076/config.txt)
take a look at line 9 in this file. There was no change

**Comment by ljacqu** [comment]
It should be added automatically. make sure you have the latest build and reopen confg.yml after starting AuthMe. The option will be there

**Comment by woodzykiler** [comment]
I wonder did u read the past posts? U would know the build im useing

**Comment by sgdc3** [comment]
Please double check.

**Comment by woodzykiler** [comment]
BUild#1533
[11:32:54 WARN]: [AuthMe] Aborting initialization of AuthMe: [ParserException]: expected '<document start>', but found BlockMappingStart
 in 'reader', line 47, column 2:
     ExternalBoardOptions:
     ^

**Comment by ljacqu** [comment]
Verified successfully: downloaded latest build, ran the server and saw the new option appear in config.yml. Restarted the server with the new config.yml and everything still works.

@woodzykiler You probably still had the old build, and the error in the message above is a YAML issue because you probably tried to add the entry manually. Undo your manual edits and run the proper version and it will be fine.
