### ISSUE TITLE
PermissionEX Prefixes not working....

### ISSUE THREAD

**Issue by ElementalRealm** [Xephi/AuthMeReloaded#1066]
**What behaviour is observed:**
PermissionEX prefixes are not working.

**What behaviour is expected:**
I was expeting like [Prefix][Username]

**Steps/models to reproduce:**
I don't know. I've just instaled AuthMe and it removed all the prefixes.

**Plugin list:**
41 Plugins:
CleanroomGenerator; PlayerHeads; WorldEdit; Nicknamer; AutoBroadcast; PerWorldPlugins; ClearLag; Spawner; BuycraftX; Votifier; WorldGuard; InventoriesPerWorld; OldCombatMechanics; UberEnchant; PermissionsEx; AntiCheat; Simple_KitPVP; Vault; ChestShop; Essentials; PlotMe; Jobs; FamoustLottery; Citizens; SignColors; ChestCommands; LockettePro; Quests; CommandNPC; PlotMe-DefaultGenerator;
Multiverse-Core; CustomMobs; MineResetLite; Multiverse-Portals; GriefPrevention; MyPet; MultiWorldMoney; MineResetPlus; AuthMe; uSkyBlock; HolographicDisplays.

**Environment description**
I am using 1.10 Spigot Version no MySQL.

**AuthMe build number:**
Build: 1384

**Error Log:**
None... I Guess...

**Configuration:**
[config.txt](https://github.com/Xephi/AuthMeReloaded/files/703951/config.txt)

Thanks for your attencion,
- Elemental Realm Inc.

**Comment by Twonox** [comment]
If you remove Authme, the problem is it solved ?

**Comment by sgdc3** [comment]
We don't touch chat prefixes in any way :/

**Comment by sgdc3** [comment]
>Build: 1384

Anyway, update to latest build

**Comment by Twonox** [comment]
No answer and no Authme's fault. I think you can close @sgdc3
