### ISSUE TITLE
can't download AuthMe-5.2-SNAPSHOT-legacy.jar

### ISSUE THREAD

**Issue by kriusworld** [Xephi/AuthMeReloaded#1067]
http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT-legacy.jar
the link is broke :(

**Comment by DNx5** [comment]
sorry, the build site is currently down. you could try the alternative
https://1753-39092499-gh.circle-artifacts.com/0/tmp/circle-artifacts.UmjCqDA/AuthMe-5.2-SNAPSHOT-legacy.jar

**Comment by sgdc3** [comment]
Jenkins is online now, sorry for the downtime.
