### ISSUE TITLE
Lag with timings

### ISSUE THREAD

**Issue by voodootje0** [Xephi/AuthMeReloaded#1068]
Why it's so lagging?
After just a few minutes I rebooted the lobby this are the timings.
https://timings.aikar.co/?url=23799552

**Comment by sgdc3** [comment]
Use latest dev build please. http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by voodootje0** [comment]
Thank you very much =)

**Comment by sgdc3** [comment]
@voodootje0 is it fixed with latest build?
