### ISSUE TITLE
How do i connect AuthMe with my Phpbb(3.2.0) forum

### ISSUE THREAD

**Issue by tedbie** [Xephi/AuthMeReloaded#1069]
can sombody plz explain to me how to connect the AuthMe plugin to my Phpbb3.2.0 forum?

**Comment by sgdc3** [comment]
Related to #470

**Comment by tedbie** [comment]
@ljacqu if i do that and it works do the players have to make an account on the webisite or ingame ?

**Comment by ljacqu** [comment]
Sorry for the late reply, @tedbie, our phpBB integration is such that it should work both for website as well as in-game. I guess by now you've found this out yourself though?
