### ISSUE TITLE
PlayerData file cannot be read

### ISSUE THREAD

**Issue by ProDash1998** [Xephi/AuthMeReloaded#1070]
####Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!

### What behaviour is observed:
Console writing errors.
### What behaviour is expected:
What did you expect?

### Steps/models to reproduce:
I'm join to servers. Plugins writing error to console

### Plugin list:
This can be found by running `/pl` yes

### Environment description
Standalone server/Bungeecord network, SQLite/MySql,: Paperspigot /---- no select Databases

### AuthMe build number:
This can be found by running `/authme version:new wersion

### Error Log:
Pastebin/Hastebin/Gist link of the error logo or stacktrace (if any)
http://pastebin.com/kaXN7axW

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
defaul configuration

**Comment by sgdc3** [comment]
@DNx5 looks like an issue with the JSON player cache

**Comment by sgdc3** [comment]
@DNx5

**Comment by ljacqu** [comment]
@ProDash1998 , sorry for the late reply. This is a file that just has `\0`s inside, which is quite strange. A weird server crash, or some kind of host transfer / faulty file copy is what comes to my mind... 
If this happened only once, I think the only improvement we can do here is log better which file is causing the issue.

**Comment by ljacqu** [comment]
We've reworked the entire way to handle "limbo players". As an improvement based on this issue, if a file cannot be read, the error is logged but everything else should continue.
