### ISSUE TITLE
Item frame destroyed on login

### ISSUE THREAD

**Issue by MC7568** [Xephi/AuthMeReloaded#1071]
*I'm a Korean. Using Google Translator
AuthMe 5.2 BETA 3 Bugs!
Minecraft Version : 1.9.4
Server Version : spigot-1.9.4

Login x: item frame destroyed

Citizen plugin NPC is Disappear
Plugin : https://dev.bukkit.org/projects/citizens

**Comment by Twonox** [comment]
Could you try the recent build of authme to see if these bugs are solved? I think that they are.
http://ci.xephi.fr/job/AuthMeReloaded/
Use `AuthMe-5.2-SNAPSHOT-spigot.jar`

**Comment by MC7568** [comment]
Thanks!

**Comment by Twonox** [comment]
If your problems are solved,  I invite you to close this issue :)
