### ISSUE TITLE
Add Delay to Email Recovery Command

### ISSUE THREAD

**Issue by Janunez** [Xephi/AuthMeReloaded#1073]
Please add a delay in this command "/email recovery <his@email.com>" players can spam this as much as they want. 

Like this:
https://i.gyazo.com/1457b0bea645adc5eb1e679a1c2f43ff.png

**Comment by ljacqu** [comment]
Ah, good point. Relates to #949 technically

**Comment by ljacqu** [comment]
Hi @Janunez , this is now available from build nr. 1573 or above—http://ci.xephi.fr/job/AuthMeReloaded/

May I ask you to give a quick feedback whether this corresponds to your expectations?

**Comment by Janunez** [comment]
i love it, thanks
