### ISSUE TITLE
Error at join - No message

### ISSUE THREAD

**Issue by Arkazium** [Xephi/AuthMeReloaded#1078]
I've a error when i join my server, no authme message when joining.
I use the last version of Authme 'AuthMe v5.2-SNAPSHOT-b1384', my server use spigot 1.8.8.
I tested much versions and doesn't work.
The error is:
http://pastebin.com/YSkXZ9Zg

Thanks you

**Comment by sgdc3** [comment]
Please update to latest dev build and try again.

**Comment by ljacqu** [comment]
You have an entry in config.yml under "AllowedRestrictedUser" that doesn't have two parts separated by a `;`. 

All entries need to be like "username;123.44.55.66" where the first part is the username to restrict, and the second part is the IP address access is limited to.

**Comment by Arkazium** [comment]
> You have an entry in config.yml under "AllowedRestrictedUser" that doesn't have two parts separated by a ;.

All entries need to be like "username;123.44.55.66" where the first part is the username to restrict, and the second part is the IP address access is limited to.

Thanks that resolve; )

**Comment by ljacqu** [comment]
Thanks for the feedback @Arkazium , glad it could be solved like this. As an improvement, we should handle this situation better. I've added it as a third point into #1005, so we will improve this sometime.
