### ISSUE TITLE
AuthMe SQL ERROR

### ISSUE THREAD

**Issue by Janunez** [Xephi/AuthMeReloaded#1081]
I'm having trouble with the SQL stuff
I get errors in console 
Console Errors and Config Setup -> http://pastebin.com/gTiizZQk
How can i fix this?

**Comment by sgdc3** [comment]
Check your mysql auth settings.

**Comment by Janunez** [comment]
I'm not really sure what you're talking about but i use HeidiSQL to view it and my hosts provides me the sql information https://gyazo.com/536facb42ac4bb5849a74221245b1210

**Comment by sgdc3** [comment]
What's your buildnumber? /authme about

**Comment by Janunez** [comment]
29.01 18:31:12 [Server] INFO ==========[ AuthMeReloaded ABOUT ]==========
29.01 18:31:12 [Server] INFO Version: AuthMeReloaded v5.3-SNAPSHOT (build: 1545)
29.01 18:31:12 [Server] INFO Developers:
29.01 18:31:12 [Server] INFO Alexandre Vanhecke // xephi59 (Original Author)
29.01 18:31:12 [Server] INFO Lucas J. // ljacqu (Main Developer)
29.01 18:31:12 [Server] INFO Gnat008 // gnat008 (Developer)
29.01 18:31:12 [Server] INFO DNx5 // DNx5 (Developer)
29.01 18:31:12 [Server] INFO games647 // games647 (Developer)
29.01 18:31:12 [Server] INFO Tim Visee // timvisee (Developer)
29.01 18:31:12 [Server] INFO Gabriele C. // sgdc3 (Project manager, Contributor)
29.01 18:31:12 [Server] INFO Website: http://dev.bukkit.org/bukkit-plugins/authme-reloaded/
29.01 18:31:12 [Server] INFO License: GNU GPL v3.0 (See LICENSE file)
29.01 18:31:12 [Server] INFO Copyright: Copyright (c) AuthMe-Team 2016. All rights reserved.

**Comment by sgdc3** [comment]
@ljacqu it's strange that the failed authentication message has a wrong db name :/

**Comment by Janunez** [comment]
i only have database for 'mc_2570' im not sure why its trying to get into 'db' HELP pls

**Comment by Janunez** [comment]
It still spams those error messages on my console :/

**Comment by sgdc3** [comment]
i'm trying to figure it out

**Comment by Janunez** [comment]
Turns out it's an issue from another plugin I had to remove them one by one to see which one was causing the issue. Sorry for wasting your time and thanks for trying to help. The issue is resolved now. it's Not authme that was causing it
