### ISSUE TITLE
tempban of authme on fail pass happen after 1 try instead to read the config

### ISSUE THREAD

**Issue by xion87** [Xephi/AuthMeReloaded#1082]
####Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!

### What behaviour is observed:
What happened?
Using this config 
    tempban:
        # Tempban a user's IP address if they enter the wrong password too many times
        enableTempban:true
        # How many times a user can attempt to login before their IP being tempbanned
        maxLoginTries: 5
It ban you after 1 wrong pass

### What behaviour is expected:
What did you expect?
It must ban after 5 wrong password try
Was working in old release.

### Steps/models to reproduce:
The actions that cause the issue
see up

### Plugin list: not rilevant
This can be found by running `/pl`

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Bungeecord

### AuthMe build number: 1542
This can be found by running `/authme version`

### Error Log:
Pastebin/Hastebin/Gist link of the error logo or stacktrace (if any)

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)

**Comment by Twonox** [comment]
I've tested with the value "3" and it works fine.
Make sure you change this setting in your lobby server.

**Comment by sgdc3** [comment]
@xion87

**Comment by xion87** [comment]
i changed these on lobby but not in hub, i use authme bridge, and this happened to 4-5 players, also it happened yesterday

**Comment by Twonox** [comment]
Ok I founded the problem.
@ljacq On successful login, the wrong login count isn't reset. You didn't add that ?

**Comment by ljacqu** [comment]
\* @ljacqu

It should be added and I think it's configurable. I'll check

**Comment by sgdc3** [comment]
@xion87

**Comment by xion87** [comment]
I just noticed now, but i have a doubt, if a bad guy wrong the pass on the account 4/5 times, and then the real owner  wrong the pass it will be banned? maybe is that the problem...

**Comment by Twonox** [comment]
No, only the IP of this player is banned.

**Comment by xion87** [comment]
ok i think is just a config error so, i fixed it

**Comment by ljacqu** [comment]
Thanks for the feedback. FYI the current behavior is that wrong login attempts are stored by (IP, username) pairs and the count is cleared after a configurable number of minutes. I also believe the count is cleared after a successful login, so I don't see any improvements for this, besides maybe a log statement with some useful information about the ban.
