### ISSUE TITLE
Unexpected behaviour on Login or Logout

### ISSUE THREAD

**Issue by AlphabetoPT** [Xephi/AuthMeReloaded#1084]
####Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!

### What behaviour is observed:
What happened?
Messages stop showing on register or login
and massive bug reports on console. 
I am able to register and login accounts, however the messages are not showing and there is the massive spam on console on every authme action.
Emails with passwords are working normally.
I assume this is a simple mistake.

### What behaviour is expected:
What did you expect?
the same behaviour
### Steps/models to reproduce:
The actions that cause the issue
i really dont know

### Plugin list:
This can be found by running `/pl`
Plugins (17): MultiWorld, WorldEdit, NoRain, PermissionsBukkit, Essentials, EssentialsChat, WorldBorder, Vault, EssentialsSpawn, PlayerMarkers, MassiveCore, WorldGuard, Citizens, OnTime, Quests, AuthMe, Factions

### Environment description
Standalone server/MySql with wordpress integration

### AuthMe build number:
AuthMeReloaded v5.2 (build: 1542)

### Error Log:
http://pastebin.com/ciVFSLtg

### Configuration:
http://pastebin.com/Can5hM03

**Comment by sgdc3** [comment]
What's your PermissionsBukkit version?

**Comment by AlphabetoPT** [comment]
2.3

**Comment by ljacqu** [comment]
@AlphabetoPT Can you update to a newer version? https://dev.bukkit.org/projects/permbukkit/files/911279
