### ISSUE TITLE
Improve handling of missing help messages

### ISSUE THREAD

**Issue by DmitryRendov** [Xephi/AuthMeReloaded#1085]
### What behaviour is observed:
Error in a server console

### What behaviour is expected:
What did you expect?
a right help_ru.yml file placed to messages folder

### Steps/models to reproduce:
The actions that cause the issue
Use "ru" lang and the latest stable release

### Plugin list:
This can be found by running `/pl`
WorldEdit, SkinsRestorer, Essentials, EssentialsChat, PermissionsEx, SignEditor, WorldBorder, Vault, EssentialsSpawn, WorldGuard, ProtocolLib, BungeePortals, TitleManager, AuthMe, AuthMeBridge, HolographicDisplays

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Bungeecord network + mysql

### AuthMe build number:
This can be found by running `/authme version`
v5.2-b1542

### Error Log:
Pastebin/Hastebin/Gist link of the error logo or stacktrace (if any)
`[AuthMe] Cannot copy resource 'messages/help_ru.yml' to file 'plugins/AuthMe/messages/help_ru.yml': cannot load resource`

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)

**Comment by ljacqu** [comment]
Thanks for submitting a help_ru.yml file! 

I'd like to keep this issue open & assign it to me to fix this error message from being shown.

**Comment by ljacqu** [comment]
@sgdc3, would you want to look this over? ;)

New behavior:
- if a help_xx.yml file doesn't exist in our JAR, avoid logging an error when we create it for the user
- if a message in help_xx.yml doesn't exist, no longer suggest running `/authme messages` (this only updates messages_xx.yml)
- we now have a unit test to ensure that all of our help_xx.yml files have entries for all help sections, help messages and default permissions. Basically any command-specific entry is optional (and will not log an error) but if something like `section.description` is missing, an error is logged.

**Comment by sgdc3** [comment]
@ljacqu Sorry, i didn't receive any notifications about that :/

**Comment by sgdc3** [comment]
Anyway, it looks good

**Comment by ljacqu** [comment]
@sgdc3 Thanks!
