### ISSUE TITLE
No error on java 7!

### ISSUE THREAD

**Issue by Rvcboy** [Xephi/AuthMeReloaded#1096]
### What behaviour is observed:
I installed newest version of AuthMe to my server (version 1.11.2), but plugin does not start up, no errors show up and files of plugin won't generate.

### What behaviour is expected:
I expected the plugin to start up and generate its files.

### Steps/models to reproduce:
Run newest version of AuthMe Reloaded on Spigot 1.11.2 server.

### Plugin list:
Essentials
EssentialsChat
Vault

### Environment description
Standalone server, VPS, Ubuntu 14.04 server

### AuthMe build number:
AuthMe 5.2

### Error Log:
None as nothing showed up.

### Configuration:
None as it did not generate.

**Comment by sgdc3** [comment]
Probably you downloaded a corrupted jar, could you try to redownload the file?

**Comment by Rvcboy** [comment]
Tried to redownload from Spigot's website twice, from Bukkit dev once, but issue still exists.

**Comment by sgdc3** [comment]
Please update and double check everything. You arethe first one having this issue with authme 5.2

**Comment by sgdc3** [comment]
Are you using Java8, right?

**Comment by Rvcboy** [comment]
Issue was my Java version. I trusted a default file and it installed Java 7, all the other plugins worked so I did not expect that Java is the issue.

**Comment by sgdc3** [comment]
No errors at all, are you sure? it should allert you about wrong java version :^

**Comment by Rvcboy** [comment]
No messages at all, just sat and did nothing until I updated Java.

**Comment by sgdc3** [comment]
@ljacqu

**Comment by sgdc3** [comment]
@ljacqu

**Comment by sgdc3** [comment]
@ljacqu Do you have any idea about that?

**Comment by Rvcboy** [comment]
Is there any big difference between Oracle's Java 7 and OpenJDK's Java 7? I use the last one on my server as Oracle's version is quite buggy for me.

**Comment by games647** [comment]
Why not Java 8?

**Comment by Rvcboy** [comment]
> Issue was my Java version. I trusted a default file and it installed Java 7, all the other plugins worked so I did not expect that Java is the issue.
Done, this report just changed the direction as other bug came out while figuring out the Java issue.

**Comment by games647** [comment]
yeah I noticed that, but why want you to install Java 7 instead of Java 8.

> Java 7 and OpenJDK's Java 7? I used the last one on my server as Oracle's version is quite buggy for me.

**Comment by Rvcboy** [comment]
I asked it, because I used and use till now OpenJDK versions of Java and thought maybe that is why message did not pop up in console.

**Comment by ljacqu** [comment]
No idea what this could be; good that you mention the jdk you're using, thanks.

**Comment by Rvcboy** [comment]
I will test this once on a virtual machine, maybe I did not see the AuthMe notification between other messages.

**Comment by ljacqu** [comment]
I wonder who would ever see that message; if someone using java 7 tries to use AuthMe they won't be able to load the class (per #102 and #1011) --

```
Could not load 'plugins/AuthMe-5.2-SNAPSHOT-spigot.jar' in folder 'plugins' org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: fr/xephi/authme/AuthMe : 
Unsupported major.minor version 52.0 
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133)
```

**Comment by sgdc3** [comment]
@ljacqu Yeah but @Rvcboy had issues with that
