### ISSUE TITLE
Changepass command is broken

### ISSUE THREAD

**Issue by xion87** [Xephi/AuthMeReloaded#1097]
On latest authme (5.2 release) when user try to change pass with /changepass oldpass newpass, it keep to saying that password is wrong.
Tried also with new account, same issue.
No errors, using 1.8.8 version

**Comment by ljacqu** [comment]
What's your password hash? What's your /authme version?

**Comment by xion87** [comment]
Right now i have downgraded, but got the same issue (Version: AuthMeReloaded v5.2-SNAPSHOT (build: 1384)
i am using the default one "MD5"

**Comment by Twonox** [comment]
@ljacqu The problem comes from aliases of the command /changepassword

**Comment by xion87** [comment]
It don't work for me, tried both commands...

**Comment by Twonox** [comment]
It's strange...
When I do /changepass, it doesn't work, but when I do /changepassword it works.

**Comment by ljacqu** [comment]
Can't reprodue&mdash;tried with SHA256 and MD5 on spigot 1.10.2. Works fine with /changepassword, /changepass and /cp. 
This sounds like another plugin is using these commands. We could most easily see this by changing the "wrong password" text, in your messages_en.yml file:
```yml
wrong_pwd: '&cWrong password!'
```

Could you change it to something specific like "Authme wrong password" temporarily? Then after /authme reload this is the message that you should be getting. If not, then AuthMe isn't the one answering to /changepassword anymore.

-----

Btw, you said you used MD5, just to let you know that it's not exactly our strongest way to store passwords. If I can interest you in switching, it would just be a matter of changing the config:
```yml
        # https://github.com/AuthMe/AuthMeReloaded/blob/master/docs/hash_algorithms.md
        passwordHash: 'SHA256'
        # ....
        legacyHashes:
        - 'MD5'
```

**Comment by Twonox** [comment]
<a href="https://www.noelshack.com/2017-07-1487432405-2017-02-18-163830.png"><img src="https://image.noelshack.com/minis/2017/07/1487432405-2017-02-18-163830.png" border="0" alt="1487432405-2017-02-18-163830.png - envoi d'image avec NoelShack" title="1487432405-2017-02-18-163830.png"/></a>

**Comment by ljacqu** [comment]
@Twonox This is something else, though. You mapped the command to `/authme:changepassword` internally. Please update to build n. 1558 or above. http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by xion87** [comment]
i am using old pass support also for SHA1 and two more hasces, because i converted from bungeeauth, but the issue persist.... saying "wrong passworld" when type /changepass oldpass newpass

**Comment by ljacqu** [comment]
please check as described in that command really goes to authme -> https://github.com/Xephi/AuthMeReloaded/issues/1097#issuecomment-280850025

**Comment by ljacqu** [comment]
Also, does `/authme changepass <player> <newpass>` work?

**Comment by xion87** [comment]
Yeah with that command work

**Comment by ljacqu** [comment]
What?

**Comment by xion87** [comment]
command /authme changepass <player> <newpass> work

**Comment by ljacqu** [comment]
but what about the thing with changing the text in authme?

**Comment by Twonox** [comment]
> @Twonox This is something else, though. You mapped the command to /authme:changepassword internally. Please update to build n. 1558 or above. http://ci.xephi.fr/job/AuthMeReloaded/

I don't receive "Wrongp asswor" message like xion87, I receive the message which is displayed on the screen that I sent. I used my own alias (by changing it on plugin.yml), not /authme:changepassword

I did some test, and I noticed that this error happen only when I change aliases on plugin.yml, with old and recent build of authme.

**Comment by ljacqu** [comment]
Oh, sorry. The reason is that we associate commands in the code with their labels (e.g. the code for the /changepassword command _knows_ it needs to respond to "changepassword", "changepass" and "cp"). What I mentioned was fixing the commands to know that they need to respond to authme:changepass too. 

When you say "by changing it on plugin.yml" do you mean inside of the AuthMe JAR itself? This won't work for the above reason, but you can use Spigot's commands.yml file to redirect another alias to "authme:changepassword".

**Comment by Twonox** [comment]
Yes, I mean the plugin.yml which is in the Authme.jar

> I noticed that this error happen only when I change aliases on plugin.yml, with old and recent build of authme

This is same thing for other commands.

So, my issue is different to the issue of xion.

**Comment by xion87** [comment]
i find the cause of issue, on my login server the hash was SHA256, instead on hub server (where player can change pass) was MD5... o.o
