### ISSUE TITLE
/email show throws exception if username doesn't exist

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#1100]
/email show throws an exception if the queried username doesn't exist, e.g. `/email show hocuspocus`. 

**Task**
- Fix bug
- Write unit test

**Comment by ljacqu** [comment]
I have no idea why I created this issue, given that `/email show` takes no arguments and can only be executed when the player is logged in. Nevertheless, I committed a null check and will close this...

**Comment by sgdc3** [comment]
Maybe /authme email show <playername>? Idk if we implemented such command.

**Comment by ljacqu** [comment]
Yeah /authme email exists. I think it had this bug a long time ago – I must have tested with an old version once and confused the commands
