### ISSUE TITLE
Forced commands config should be empty by default

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#1102]
The commands.yml file has a sample `msg` command that is annoying users. The file should default to having an "empty" configuration. 
This requires a new version of ConfigMe to save empty maps.

**Comment by Twonox** [comment]
Or just add this command in comment.

**Comment by ljacqu** [comment]
@Twonox This is how the commands.yml looks now:
https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/resources/commands.yml

Empty defaults with explanatory comments. OK to close?

**Comment by Twonox** [comment]
It's okay ;)

**Comment by ljacqu** [comment]
Thanks!
