### ISSUE TITLE
/changepassword's aliases are not hidden

### ISSUE THREAD

**Issue by Twonox** [Xephi/AuthMeReloaded#1104]
When we use the aliases of the command /changepassword, our password is displayed on the console even if `removePassword` is `true`

**Comment by ljacqu** [comment]
Added all missing aliases, thanks for the report. Please verify with build n. 1566 or above. http://ci.xephi.fr/job/AuthMeReloaded/ @Twonox

**Comment by Twonox** [comment]
The aliases are hidden, but the commands like `/authme:changepass` are not hidden.

**Comment by ljacqu** [comment]
Nice catch, thank you! This should be fixed now. I give you the opportunity to object again. :P

**Comment by Twonox** [comment]
I can't verify, your build has failed.

**Comment by sgdc3** [comment]
@Twonox Just started a new build ;)

**Comment by ljacqu** [comment]
I think this is OK to close now.
