### ISSUE TITLE
Sorry dev, I need guide to install system.

### ISSUE THREAD

**Issue by hnomkeng** [Xephi/AuthMeReloaded#1107]
sorry sorry. :(

**Comment by ljacqu** [comment]
Minimally, you would need to at least post a question for us to be able to provide the help you need. What are you trying to do?, and what have you tried?

If you're trying to use the AuthMe plugin on your server, grab it from http://ci.xephi.fr/job/AuthMeReloaded/ and put it in your server's plugin/ folder. Whether you need the legacy jar or not is described at https://github.com/AuthMe/AuthMeReloaded/wiki/AuthMe-Releases-(Jenkins)

If you're trying to check out the project's code and compile it, I think the only "tricky" part is making sure that you have enabled either the "spigot" Maven profile or the "bukkit" one (and not both at the same time!). I think by default "spigot" should be selected. Some more instructions for a dev setup is available at https://github.com/AuthMe/AuthMeReloaded/wiki/Development-Setup
