### ISSUE TITLE
Protect feature

### ISSUE THREAD

**Issue by friishon** [Xephi/AuthMeReloaded#1108]
Hack client can try crack the account password using bruteforce, can you make anything to block 3 times of trying? And kick the account, if then he try to login putting wron password ban the ip and player and the reason "intented of hack, we send you and email to verify if you are or not, please verify your email"
And send and email that sai "you are trying to login with this ip (ip + possible location) to kown your ip go here (url to see the ip) if you are, click this link tu unban your account, and change the password"
The link can open a web page to recover the password? You can create a web page only for this problem
I thing this option is good, please think about it and sorry for my english, i'm from spain

**Comment by sgdc3** [comment]
We already have such option, check the config before asking for new features. ;)

**Comment by sgdc3** [comment]
Whoops missed the email part, atm we can kick/ban an user after x wrong passwords

**Comment by friishon** [comment]
Can you make ban-ip also?
I will check my config sorry :(

**Comment by Twonox** [comment]
This is already banip.

**Comment by friishon** [comment]
I check the config and i found the tempban, can you change tempban for permanent ip ban? And the email option that i put?

**Comment by Twonox** [comment]
#794

**Comment by ljacqu** [comment]
Voting to close in favor of the linked issues.
