### ISSUE TITLE
Simplify password recovery process

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#1109]
Hi @sgdc3 @games647 @Twonox @Platinteufel @RoinujNosde—request for comments.

You may remember that a recovery code feature was added in #472, which, if enabled, looks like this for a player to recover his account:

> Player: /email recover [email]
Server: A recovery code was sent to your email
Player: /email recover [email] [code]
Server: Your password has been changed and sent by mail

I would like to simplify this to where, after entering the correct code, the user can simply submit his new password (kind of like a "register") instead of getting a second email:

> Player: /email recover [email]
Server: A recovery code was sent to your email
Player: /email recover [email] [code]
Server: Correct code! Use /email register [pass] [pass] in the next 2 minutes to set new password
Player: /email register test1234 test1234

Is there anything that speaks against this? Should we still support the current approach (configurable)?
A better name for this "/email register" is also welcome... :)

**Comment by RoinujNosde** [comment]
"Is there anything that speaks against this?"
Nope, this is great.

"Should we still support the current approach (configurable)?"
No, this new way is much easier.

About the command name, I'm not creative (at all) so I can't suggest anything better :/

**Comment by Platinteufel** [comment]
Since I don't use this recovery feature I don't know if you can find out the code with brute force. According to your post you'll get the account once you got the code, so maybe you shouldn't be able to try it as many times as you want?

/email register could be confusing. Unfortunately I also don't know a better name on the fly. Maybe /email changepassword?

**Comment by ljacqu** [comment]
Thanks for the feedback, guys!

> brute force. According to your post you'll get the account once you got the code, so maybe you shouldn't be able to try it as many times as you want?

That's a very good point. Currently even if someone brute forces the code all confidential stuff is done via the player's email, so an attacker won't gain anything by brute forcing the recovery code. This would change with my proposition. Hmm.

I like /email changepassword, how about /email setpassword ?

**Comment by RoinujNosde** [comment]
/email setpassword sounds nice. :)

About the brute force problem... a limiter of tries would solve it, I think.

**Comment by sgdc3** [comment]
Just let the code expire after 5 minutes ;)

**Comment by sgdc3** [comment]
Player: /email recover [email]
Server: A recovery code was sent to your email
Player: /email recover [email] [code] <============= **Is the email really required there?**
Server: Correct code! Use /email register [pass] [pass] in the next 2 minutes to set new password
Player: /email register test1234 test1234

**Comment by Twonox** [comment]
"Player: /email recover [email] [code] <============= Is the email really required there?"
I asked same thing to myself :)
An other command like "/email code [code]" will be better.

**Comment by ljacqu** [comment]
I mainly kept the email there because I didn't want to deal with a parameter that might have a different value (email / code) depending on context. @Twonox solves this elegantly by introducing a new command :)

I think a max try + expiration of the recovery code is secure—to implement this our new ExpiringSet structure would just need an additional `decrement()` method. On success we can remember the IP address and allow it to set a new password within _x_ minutes (ExpiringMap).

**Comment by Gnat008** [comment]
Uhh no idea how i closed this...

**Comment by ljacqu** [comment]
This story can be broken down into subtasks. If I describe in enough detail I feel comfortable smacking the "easy pick" label (a _difficult_ easy pick story, but still...). [Easy pick](https://github.com/Xephi/AuthMeReloaded/issues?q=is%3Aissue+is%3Aopen+label%3A"easy+pick") labels issues that are suitable for new people that want to join in on the developing fun ;) We could handle 1-2 new devs.

0\) Familiarize yourself with the current password recovery mechanism... :)
### 1) Introduce /email code
- Create a new command for `/email code` to submit the recovery code to it instead of to the `/email recovery` command. (As described by Twonox above.)
  - /email recovery will be only responsible for sending out the appropriate mail: the recovery code email or the email with the new password, depending on the config.

### 2) Add max tries for /email code
Currently the recovery code for a user is limited by time, but we also only want there to be a max number of tries for this.
  - Add a setting to configure the max number of tries
  - See `ExpiringSet` for the structure to use. You need to add a `decrement()` method similar to the existing `increment()` method. When the recovery code is used, call `decrement()`. This call may take place within the `RecoveryCodeService`.

### 3) Introduce a PasswordRecoveryService
As we spread the logic for new passwords & recovery codes among different commands, we need to talk to _one_ class that unites all of this mess :) Typically a command should only perform very crude checks that the arguments are valid and then delegate to a service class. 
This encapsulate our code and allows us, as in this case, to use the some functionalities across different entry points (incoming commands).
The new service is:
 - responsible for the email cooldown (currently in /email recovery implementation)
 - responsible for handling recovery codes (keep the core logic in RecoveryCodeService if suitable, or move into the new class)

### 4) Implement /email setpassword
Once the player has run a successful `/email code` he can choose his new password. This should be done with `/email setpassword`.
 - Create the command
 - Inform the player after correct code to use /email setpassword
 - Actual check and handling should be done within RecoveryCodeService
 - Password should be validated, see `ValidationService#validatePassword`
 - Access to this command needs to expire! Should also be restricted to the IP address that has done the successful /email code. (Use ExpiringMap)

**Comment by Twonox** [comment]
Why did you add a time information for `email_cooldown_error` ?
Is it really necessary ?

**Comment by sgdc3** [comment]
@ljacqu What's the state of this?

**Comment by ljacqu** [comment]
This has been completed by @Gnat008. I don't think there's anything left open.
I'd like to play through it once more before closing it ;)
