### ISSUE TITLE
Revise LimboPlayer code structure

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#1113]
### Background
We want to make handling of LimboPlayer more flexible. In particular, we have received requests to make the behavior more configurable, such as:
- Disable LimboCache altogether #880
- Disable fly status #1036
- Allow to store LimboPlayer in MySQL (https://github.com/Xephi/AuthMeReloaded/issues/1036#issuecomment-270005821)
- Store all LimboPlayers into one file only (as before 5.2)

### Goal
This issue is about defining various design questions and completing preparatory work so that the linked issues can be implemented. In particular:
- We should have a Wiki page about the concept of LimboPlayer and how it should be handled. I currently don't understand why we sometimes just [add data](https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/process/join/AsynchronousJoin.java#L114), [delete & add data](https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/process/join/AsynchronousJoin.java#L143), or [why we update after registration](https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/process/register/ProcessSyncPasswordRegister.java#L49) (which removes the player from cache and adds him again???)
- `LimboPlayerStorage` should not be used anywhere outside of the limbo package. We don't want to expose our storage mechanism to the outside so that we may easily replace it in the background.
  - Any outside classes should be able to use _one_ method per case to take care of whatever they need to do with the LimboPlayer. LimboCache should handle the details, and this will allow us to make "the details" configurable.
  - If more suitable, an additional class (LimboService?) can be introduced to handle the details and delegate to LimboCache. (I don't think it's a good idea)
- Tasks should be handled through `LimboPlayerTaskManager` only. We could even discuss about not connecting the tasks to the LimboPlayer anymore. What for sure needs to disappear is stuff like `limboCache.getPlayerData(player.getName()).getMessageTask().setMuted(true);` --> needs a method in LimboPlayerTaskmanager.

One possibility of doing this is to create a branch and to create _new_ Limbo classes, slowly rebuilding the current features. We might get a better code structure like this and have a deeper understanding of what exactly we're trying to do... :mountain_snow:

**Comment by ljacqu** [comment]
@DNx5, I assign this to you. I can do large parts of this task but I really need an introduction of the principles first. Why do we update LimboPlayer after registration? When do we delete a LimboPlayer .json file and when do we keep it?

**Comment by ljacqu** [comment]
Some thoughts. Comments are welcome.

Regarding #1036 "Add option to disable fly status saving" I think we'd be the most flexible by letting the user decide in config.yml what he wants to do with the individual properties we save:
```yml
# Comment explaining what "limbo" is to the user
limbo:
  flyStatus: RESTORE  # value of DISABLE, RESTORE, ENABLE
  flySpeed: RESTORE # value of RESTORE or DEFAULT or ZERO?
  walkSpeed: RESTORE # as above
```
I don't think we should make it configurable for OP status. Permission group is configurable already.
How to make Location configurable? @DNx5 says the only reason we saved the LimboPlayers to JSON files was to keep the location. Maybe we can offer the options to a) save to one large file b) save to individual files c) not save to disk.

**Comment by Gnat008** [comment]
> Maybe we can offer the options to a) save to one large file b) save to individual files c) not save to disk.

Meaning save all players in one file, or save players in individual files? If so, then I would think saving to individual files would be better performance-wise, especially for large servers.

**Comment by Eufranio** [comment]
Or saving it to SQLite/MySQL? Just reducing the file number would be quite good for large servers (aka having 45k json files).

**Comment by Gnat008** [comment]
I don't know about saving it in a relational database, since isn't the Limbo system meant to be temporary? Or is my understanding wrong? I never did understand the mess that is the Limbo cache.

**Comment by Eufranio** [comment]
I think it's just some quick settings that are saved on quit and set on join. I dont think they're temporary right now, the jsons in my folder is still increasing :P

**Comment by DNx5** [comment]
It mean to be temporary. but because we could not update player's location
on quit, we could not delete the files because we still need the location
value when player next join

**Comment by ljacqu** [comment]
```yml
# This option will save the quit location of the players.
SaveQuitLocation: false
```
^ What currently happens when `false` is that the location is taken from the limbo player. And the limbo player currently does a great job of knowing the last location, but as @DNx5 says this is at the cost of storing the limbo players.

This has two problems. We store the whole LimboPlayer object and then use restore all of the data we have in there. This is why people are losing their fly speed etc. because we're overriding their stats with _who knows how old_ data. But more importantly I don't think this is the job of LimboPlayer. If you say `SaveQuitLocation: false`, that literally mean "do not save the quit location." (see also [Spawn handling](https://github.com/AuthMe/AuthMeReloaded/wiki/Spawn-Handling))

So my suggestion here, in light of the comments, is not to save the LimboPlayer at all. We need to check how this will behave with `SaveQuitLocation: false`. I suspect this will lose the location when the player quit but this is OK.

**Comment by DNx5** [comment]
@ljacqu We still need to save the LimboPlayer. just in case the server is crashed, we don't lose the player's state.

**Comment by Gnat008** [comment]
If all you need is a location, why not just store each player's location in a file on quit?

**Comment by ljacqu** [comment]
> We still need to save the LimboPlayer. just in case the server is crashed, we not losing the player's state.

Can we make this configurable? I'm sure some people don't want this. I agree with you that it's a useful feature. We could even offer what I propose: not to save, to save in individual files or to save in one big file.
We just need to keep LimboPlayers when they are in the "unauthenticated" state, right? Once a player logs in or quits the server, LimboPlayer features are restored.
@DNx5 Do you want to do this?

> If all you need is a location, why not just store each player's location in a file on quit?

That's what the option `SaveQuitLocation` is for—to save the last quit location in MySQL.

**Comment by DNx5** [comment]
@ljacqu good idea, what should the configuration will be? and I think we should have the default values too.
> That's what the option SaveQuitLocation is for—to save the last quit location in MySQL.
could we combine it with `teleportUnAuthedToSpawn` feature? so we don't need to use limbocache to store the location.

**Comment by ljacqu** [comment]
Hi @DNx5, given the long comment thread and the complexity of adding storage, I created a new task for this at #1125. I've added some text there. I'd expect the `teleportUnAuthedToSpawn` feature to work correctly with `SaveQuitLocation: true`. If it's `false`, AuthMe is literally configured _not_ to save the quit location, so what can you expect then... :man_shrugging:

**Comment by ljacqu** [comment]
Still going to keep this open for:
- creating a Wiki page
- checking if tasks shouldn't be scheduled by LimboService directly when we create a limbo player
- configurable restoration: I will probably hijack #1036 for this
