### ISSUE TITLE
Translate | Turkish Language

### ISSUE THREAD

**Issue by smt287** [Xephi/AuthMeReloaded#1114]
Hello,
I'm translated your plugin in Turkish ( tr ).
NO ERROR!

Alternative links;
- https://hastebin.com/narapimame.bash
- http://paste.ubuntu.com/24084595/

suprise: https://github.com/Xephi/AuthMeReloaded/issues/621

**Comment by Twonox** [comment]
Degisilmesi gereken daha bayagi seyler var.
Neyse, merge yapilsin, ben halederim azar azar.
Yada simdiden daha iyi bir goz atabilirsin, motivasion varsa :p

**Comment by ljacqu** [comment]
Thank you very much! :) The new texts have been added.
