### ISSUE TITLE
You should join using username "nick", not "NiCk

### ISSUE THREAD

**Issue by Darko266** [Xephi/AuthMeReloaded#1120]
### What behaviour is observed:
So i Converted the auths.db to Authme.db using     backend: 'FILE', tryed to join with my Premium account and it says "You should join using username darkoakhd, not DarkOakHD (DarkOakHD is my premium btw.)

### Plugin list:
AuthMe v5.3-SNAPSHOT-b1580 and ProtocolLib for 1.8.8

### Environment description
SQLite, but will transfer to mysql if possible cuz 100k Accounts

### AuthMe build number:
The latest build from Jekins (4.3.2017 Today, AuthMe v5.3-SNAPSHOT-b1580)

### Error Log:
No error

**Comment by sgdc3** [comment]
@ljacqu The converter should keep the realname column empty :/

**Comment by Darko266** [comment]
Is there anyway to fix that, on my side ?

**Comment by ljacqu** [comment]
@sgdc3 You're right! You can assign to me to fix this if you don't want to do it.

@Darko266 Currently not, if we fix the importer soon we'd have to ask you to convert from the .db to sqlite again. If this is not OK (you have new changes you need to keep) we can have you edit the SQLite database.

**Comment by Darko266** [comment]
http://prntscr.com/efyjvv - I Transfered the .db to the mysql (my nick is like this only i think), how do i now use the mysql i need to register (but the .db files has my password)

**Comment by ljacqu** [comment]
Run `UPDATE authme SET realname = NULL`, assuming that `authme` is your table name. This will clear the "real name" for all entries. The first time someone joins with the name (case-insensitive), the name with that casing will be registered again.

**Comment by Darko266** [comment]
Where / how do i run that ?

**Comment by ljacqu** [comment]
you have phpmyadmin, right? Open the authme table and then at the top there's a SQL tab.

**Comment by Darko266** [comment]
Yes, i see it

**Comment by ljacqu** [comment]
Paste the following in there and hit the `Go` button and you're done ;)

```sql
UPDATE authme SET realname = NULL
```

**Comment by Darko266** [comment]
Doesent work http://prntscr.com/efynrv

**Comment by ljacqu** [comment]
Oh ffs. Sorry.

```sql
UPDATE authme SET realname = 'Player'
```

**Comment by Darko266** [comment]
Works, now how do i tell authme to use mysql and not sqllite ?

**Comment by ljacqu** [comment]
change in config.yml (including connection details) + restart server

**Comment by Darko266** [comment]
Do i need to delete this ? http://prntscr.com/efypl4

**Comment by ljacqu** [comment]
Please keep the authme.db, I'm doing a fix for the conversion of Flatfile and I'll ask you to verify that it works. I don't know what the other file is.

**Comment by Darko266** [comment]
I think it is working, i need to do it on the LIVE server thoe, where are 200K players in the .db

**Comment by ljacqu** [comment]
The fix is pushed and will be available with build n. 1581 or above — http://ci.xephi.fr/job/AuthMeReloaded/ If you could configure authme to type: 'file' again it will perform the conversion again and you could give us some feedback whether the conversion works as you expect. The bug you describe should no longer happen. Thanks

**Comment by Darko266** [comment]
All working in the build 1582 :+1:

**Comment by ljacqu** [comment]
Thanks a lot for the feedback @Darko266, glad all is good now :)

**Comment by Vuong26** [comment]
i got this problem too
