### ISSUE TITLE
Disable mutiple account message

### ISSUE THREAD

**Issue by rayriffy** [Xephi/AuthMeReloaded#1126]
I edit all configuration file at config.yml but I still got message below

You own 3 accounts:
P1,P2,P3

I want to ask that where to disable this message.

**Comment by Twonox** [comment]
Add this negative permission in groups which shouldn't see own accounts.
 - -authme.player.seeownaccounts

**Comment by ljacqu** [comment]
hi @rayriffy, please let us know if Twonox's answer solved your problem. In that case we could close this issue.

**Comment by rayriffy** [comment]
Yes, problem solved. Now I need to fix another plugin bug that appear after add this permission.
