### ISSUE TITLE
[Dev] Rename classes to conform to camel case

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#1128]
We have a lot of class names that don't conform to the typical class naming rules in Java:
- a class' name should start in uppercase
- names should be CamelCase (not ALLCAPS or HaveOneCAPSGroup)

We should rename all classes that don't conform to the naming conventions. The Google style manual has a very nice overview at https://google.github.io/styleguide/javaguide.html#s5.3-camel-case . You can find a list of offending classes in our code base at https://lima.codeclimate.com/github/AuthMe/AuthMeReloaded/issues (or install the Checkstyle plugin for IDEA).

Important:
- Renamings should be done on a branch
- Don't rename API classes or methods (such as `API` and `NewAPI`)

**Comment by Yasgur99** [comment]
I made a pull request. More info at https://github.com/Xephi/AuthMeReloaded/pull/1135

**Comment by ljacqu** [comment]
Hi, thanks for doing this. Nice that you renamed the according test classes.
The background of issue #1128 is to make our code adhere better to Java conventions, and to fix the checkstyle warnings we've configured. For this project, it's configured to allow max two consecutive uppercase letters, I would therefore propose the following renamings:
- SHA256, SHA512 -> Sha256, Sha512
  - For consistency MD5 -> Md5
- XFBcrypt -> XfBcrypt
- PHPFusion -> PhpFusion

The file names don't correspond to the Java class – for example Sha256Test was renamed to SHA256Test but it's still in Sha256Test.java. I'm surprised that our integrated build services didn't fail because of that.

Lastly, we use AuthMe/AuthMeReloaded as our development repository so this one is several commits behind. If it's not too mich trouble, I'd invite you to submit this PR to the AuthMe repository. If this is too troublesome we can keep this PR and we'll take care of merging it.

Cheers!

**Comment by Yasgur99** [comment]
yea sure ill make those changes and I'd love to push to the PR. I will make those changes and pull request to the public repo and the private repo when im invited

**Comment by sgdc3** [comment]
We don't have private repositories, AuthMe/AuthMeReloaded is our development repository, Xephi/AuthMeReloaded is our release repo ;)
