### ISSUE TITLE
(/192.168.0.206:55814): Your country is banned from this server!

### ISSUE THREAD

**Issue by comonier** [Xephi/AuthMeReloaded#1131]
And its not blocked.... he is from PT
any tip to unblock that player ?

Protection:
    # Enable some servers protection (country based login, antibot)
    enableProtection: true
    # Apply the protection also to registered usernames
    enableProtectionRegistered: true
    # Countries allowed to join the server and register. For country codes, see
    # https://dev.bukkit.org/projects/authme-reloaded/pages/countries-codes
    # PLEASE USE QUOTES!
    countries: 
    - 'BR'
    - 'PT'
    # Countries not allowed to join the server and register
    # PLEASE USE QUOTES!
    countriesBlacklist: 
    - 'A1'

**Comment by sgdc3** [comment]
@comonier does it work if you set "countriesBlacklist: []"?

**Comment by comonier** [comment]
did u ask to me remove all other coutrys from Blacklist ? cause i put all other on blacklist because constant bots atacking my server

**Comment by comonier** [comment]
Protection:
    # Enable some servers protection (country based login, antibot)
    enableProtection: true
    # Apply the protection also to registered usernames
    enableProtectionRegistered: true
    # Countries allowed to join the server and register. For country codes, see
    # https://dev.bukkit.org/projects/authme-reloaded/pages/countries-codes
    # PLEASE USE QUOTES!
    countries: 
    - 'BR'
    - 'PT'
    # Countries not allowed to join the server and register
    # PLEASE USE QUOTES!
    countriesBlacklist: 
    - 'A1'
    - 'A2'
    - 'O1'
    - 'US'
    - 'AD'
    - 'AE'
    - 'AF'
    - 'AG'
    - 'AI'
    - 'AL'
    - 'AM'
    - 'AO'
    - 'AP'
    - 'AQ'
    - 'AR'
    - 'AS'
    - 'AT'
    - 'AU'
    - 'AW'
    - 'AX'
    - 'AZ'
    - 'BA'
    - 'BB'
    - 'BD'
    - 'BE'
    - 'BF'
    - 'BG'
    - 'BH'
    - 'BI'
    - 'BJ'
    - 'BL'
    - 'BM'
    - 'BN'
    - 'BO'
    - 'BQ'
    - 'BS'
    - 'BT'
    - 'BV'
    - 'BW'
    - 'BY'
    - 'BZ'
    - 'CA'
    - 'CC'
    - 'CD'
    - 'CF'
    - 'CG'
    - 'CH'
    - 'CI'
    - 'CK'
    - 'CL'
    - 'CM'
    - 'CN'
    - 'CO'
    - 'CR'
    - 'CU'
    - 'CV'
    - 'CW'
    - 'CX'
    - 'CY'
    - 'CZ'
    - 'DE'
    - 'DJ'
    - 'DK'
    - 'DM'
    - 'DO'
    - 'DZ'
    - 'EC'
    - 'EE'
    - 'EG'
    - 'EH'
    - 'ER'
    - 'ES'
    - 'ET'
    - 'EU'
    - 'FI'
    - 'FJ'
    - 'FK'
    - 'FM'
    - 'FO'
    - 'FR'
    - 'GA'
    - 'GB'
    - 'GD'
    - 'GE'
    - 'GF'
    - 'GG'
    - 'GH'
    - 'GI'
    - 'GL'
    - 'GM'
    - 'GN'
    - 'GP'
    - 'GQ'
    - 'GR'
    - 'GS'
    - 'GT'
    - 'GU'
    - 'GW'
    - 'GY'
    - 'HK'
    - 'HM'
    - 'HN'
    - 'HR'
    - 'HT'
    - 'HU'
    - 'IE'
    - 'IL'
    - 'IM'
    - 'IN'
    - 'IO'
    - 'IQ'
    - 'IR'
    - 'IS'
    - 'IT'
    - 'JE'
    - 'JM'
    - 'JO'
    - 'JP'
    - 'KE'
    - 'KG'
    - 'KH'
    - 'KI'
    - 'KM'
    - 'KN'
    - 'KP'
    - 'KR'
    - 'KW'
    - 'KY'
    - 'KZ'
    - 'LA'
    - 'LB'
    - 'LC'
    - 'LI'
    - 'LK'
    - 'LR'
    - 'LS'
    - 'LT'
    - 'LU'
    - 'LV'
    - 'LY'
    - 'MA'
    - 'MC'
    - 'MD'
    - 'ME'
    - 'MF'
    - 'MG'
    - 'MH'
    - 'MK'
    - 'ML'
    - 'MM'
    - 'MN'
    - 'MO'
    - 'MP'
    - 'MQ'
    - 'MR'
    - 'MS'
    - 'MT'
    - 'MU'
    - 'MV'
    - 'MW'
    - 'MX'
    - 'MY'
    - 'MZ'
    - 'NA'
    - 'NC'
    - 'NE'
    - 'NF'
    - 'NG'
    - 'NI'
    - 'NL'
    - 'NP'
    - 'NR'
    - 'NU'
    - 'NZ'
    - 'OM'
    - 'PA'
    - 'PE'
    - 'PF'
    - 'PG'
    - 'PH'
    - 'PK'
    - 'PL'
    - 'PM'
    - 'PN'
    - 'PR'
    - 'PS'
    - 'PW'
    - 'PY'
    - 'QA'
    - 'RE'
    - 'RO'
    - 'RS'
    - 'RU'
    - 'RW'
    - 'SA'
    - 'SB'
    - 'SC'
    - 'SD'
    - 'SE'
    - 'SG'
    - 'SH'
    - 'SI'
    - 'SJ'
    - 'SK'
    - 'SL'
    - 'SM'
    - 'SN'
    - 'SO'
    - 'SR'
    - 'SS'
    - 'ST'
    - 'SV'
    - 'SX'
    - 'SY'
    - 'SZ'
    - 'TC'
    - 'TD'
    - 'TF'
    - 'TG'
    - 'TH'
    - 'TJ'
    - 'TK'
    - 'TL'
    - 'TM'
    - 'TN'
    - 'TO'
    - 'TR'
    - 'TT'
    - 'TV'
    - 'TW'
    - 'TZ'
    - 'UA'
    - 'UG'
    - 'UM'
    - 'UY'
    - 'UZ'
    - 'VA'
    - 'VC'
    - 'VE'
    - 'VG'
    - 'VI'
    - 'VN'
    - 'VU'
    - 'WF'
    - 'WS'
    - 'YE'
    - 'YT'
    - 'ZA'
    - 'ZM'
    - 'ZW'
    # Do we need to enable automatic antibot system?
    enableAntiBot: true
    # The interval in seconds
    antiBotInterval: 5
    # Max number of players allowed to login in the interval
    # before the AntiBot system is enabled automatically
    antiBotSensibility: 1
    # Duration in minutes of the antibot automatic system
    antiBotDuration: 1
    # Delay in seconds before the antibot activation
    antiBotDelay: 10

**Comment by ljacqu** [comment]
If the whitelist is not empty, only the whitelist will have effect. The blacklist is only considered if the whitelist is empty.

**Comment by comonier** [comment]
i will test it again with 
"countriesBlacklist: []"
just a minut....

**Comment by comonier** [comment]
shoul i just delet all lines ? 
but please i dont want to be atacked again."countriesBlacklist: []"
i need to delete all linke like that ? - 'UY'

**Comment by comonier** [comment]
ERROR:

while scanning a simple key
  in "<unicode string>", line 378, column 5:
        countriesBlacklist:[]
        ^
could not found expected ':'
  in "<unicode string>", line 379, column 5:
        # Do we need to enable automatic ... 
        ^

**Comment by comonier** [comment]
change to:
    countries: 
    - 'BR'
    - 'PT'
    # Countries not allowed to join the server and register
    # PLEASE USE QUOTES!
    countriesBlacklist:
    - []
    # Do we need to enable automatic antibot system?
    enableAntiBot: true
to accept code, but waiting to check up if the player will do login tomorrow.
hope it still blocking other coutries (...)

**Comment by sgdc3** [comment]
@ljacqu uh, didn't know that, it sounds strange to me that the player ip was a 192.168.0.x address :/

**Comment by comonier** [comment]
yes its amazing and super strange, 192.162.0 its routers, and modens default gateway... who someone from PT have this wan ip, its normally a lan gateway... but whatever its from console log. I am wanting he try to connect on the server tomorrow again... so i can check if removing all countries from blocked list will work.... you sad to me change to countriesBlacklist:[] but is doenst work so i change it to - [] on another line after countriesBlacklist:[] its good ?

**Comment by comonier** [comment]
https://www.quora.com/Why-IP-addresses-start-with-192-168
"If no. of users are more .Then you should take this Private class IPs.

Class B:- 172.16.0.0 =>172.31.255.255

No. of Host IP Addresses in this Class :-1,048,576;

Class C:-  192.168.0.0 =>192.168.255.255

No. of Host IP Addresses in this Class :-65,536;

So no. of host IP Addresses are minimum in class c and if no. of Hosts are less in your Private Network then c class IPs are provided.

                                           ---***---

Other all IP Addresses are Public IP Address.

If IANA provide public IP addresses to every Host,then no. of  IPs will short . So they declared some IPs as Private IP Addresses . These Private IPs can be assigned to any Private Network of  College,Company etc.

Like In our college all students have different Private IP Addresses.But if we want to connect other Networks then we have to use Public IP .In our college there is only one Public IP .

So, No. of Hosts in your Private  Network is  less than or equal to 65,536 and you are using Class C IP Address . Due to this, your IP Address start with 192.168.."

**Comment by sgdc3** [comment]
@ljacqu sounds strange to me, what do you think?

**Comment by ljacqu** [comment]
> uh, didn't know that

The whitelist means "don't allow anything besides in the whitelist," so it's the only think that makes semantically. ;)

> sounds strange to me, what do you think?

I totally missed the fact that this is a private IP... How can the GeoIP feature we use know that the private IP is physically located in PT? It doesn't. I think you need to add `A1` to the whitelist, @comonier. I will add some debug statements for the country protection feature and I'll write a comment again.

**Comment by ljacqu** [comment]
Once it's available, it will be available in build n. 1589 at http://ci.xephi.fr/job/AuthMeReloaded/ (don't use 1588 because I messed up the log...)

Please download that JAR, and in your config.yml set `logLevel: 'DEBUG'`. If country protection is enabled, a debug log statement will be issued for each IP connecting to the server, outputting the country code. Then we'll know what those 192.168.*.* IPs are mapped to by GeoIP.

**Comment by comonier** [comment]
09.03 15:55:08 [Server] INFO UUID of player IuputPT is a9a3f38c-c6f7-4856-8069-48c80258730d
09.03 15:55:08 [Server] INFO Disconnecting com.mojang.authlib.GameProfile@189ab029[id=a9a3f38c-c6f7-4856-8069-48c80258730d,name=IuputPT,properties={textures=[com.mojang.authlib.properties.Property@ab7ee5c]},legacy=false] (/192.168.0.206:56994): Your country is banned from this server!
09.03 15:55:08 [Disconnect] User com.mojang.authlib.GameProfile@189ab029[id=a9a3f38c-c6f7-4856-8069-48c80258730d,name=IuputPT,properties={textures=[com.mojang.authlib.properties.Property@ab7ee5c]},legacy=false] (/192.168.0.206:56994) has disconnected, reason: Your country is banned from this server!

**Comment by comonier** [comment]
Protection:
    # Enable some servers protection (country based login, antibot)
    enableProtection: true
    # Apply the protection also to registered usernames
    enableProtectionRegistered: true
    # Countries allowed to join the server and register. For country codes, see
    # https://dev.bukkit.org/projects/authme-reloaded/pages/countries-codes
    # PLEASE USE QUOTES!
    countries: 
    - 'BR'
    - 'PT'
    # Countries not allowed to join the server and register
    # PLEASE USE QUOTES!
    countriesBlacklist:
    - []
    # Do we need to enable automatic antibot system?
    enableAntiBot: true

**Comment by comonier** [comment]
each one ?

	AuthMe-5.3-SNAPSHOT-legacy.jar	5.05 MB	 exibir
	AuthMe-5.3-SNAPSHOT-noshade.jar	618.84 KB	 exibir
	AuthMe-5.3-SNAPSHOT-spigot.jar	2.64 MB	 exibir

**Comment by comonier** [comment]
[16:26:01] [User Authenticator #3/INFO]: UUID of player IuputPT is a9a3f38c-c6f7-4856-8069-48c80258730d
[16:26:02] [Server thread/INFO]: [AuthMe] [DEBUG] Country code `--` for `192.168.0.206` is allowed: false

**Comment by ljacqu** [comment]
Thanks for the logs. In that case it probably needs to be:

```yml
countries:
- 'BR'
- 'PT'
- '--'
```

**Comment by comonier** [comment]
09.03 16:49:19 [Server] INFO ==========[ AuthMeReloaded ABOUT ]==========
09.03 16:49:19 [Server] INFO Version: AuthMeReloaded v5.3-SNAPSHOT (build: 1589)
----------------------------
09.03 16:48:28 [Server] INFO UUID of player IuputPT is a9a3f38c-c6f7-4856-8069-48c80258730d
09.03 16:48:28 [Server] INFO [DEBUG] Country code `--` for `192.168.0.206` is allowed: true
09.03 16:48:29 [Connect] User IuputPT, IP 192.168.0.206
09.03 16:48:29 [Multicraft] IuputPT ran command Mensagem do Dia
----------------

Now that I've released this code '--' is not this going to free all countries to connect to my server?

**Comment by ljacqu** [comment]
We use GeoIP by Maxmind in the background to map IP addresses to countries. Whatever their database returns, we take and we check against the whitelist. So no, `--` doesn't free all countries, it will simply allow all IP addresses for which GeoIP returns `--` as country code. (That's also what we return if we couldn't download the GeoIP database.)

I think a debug command for looking up IP addresses' country code might be interesting to play around with. But here these are internal IP addresses (from the same network!)... these IP addresses are not applicable for country lookup since they're in the private range, so I guess GeoIP just returns `--`.

**Comment by comonier** [comment]
no problem, the player connect on the server and he is happy now. Ty you can close this issue.

**Comment by ljacqu** [comment]
Thanks for the feedback! Btw, with the build n. 1592 and above we now have `/authme debug cty` available to view country information and to check whether the country is blocked or not. Maybe this can be helpful in the future.

**Comment by ljacqu** [comment]
Adding to 5.3 milestone because of the improvements in debug logging / debug command
