### ISSUE TITLE
Show warning for unsalted hashes

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#1138]
Preparation for #1016, before the hashes are "removed" (mandatory migration) in 5.4, we should output a warning in 5.3. 
This allows us to inform users of the upcoming change and to allow them to provide input.

**Comment by ljacqu** [comment]
hi @sgdc3, may I ask you to check my changes?

**Comment by sgdc3** [comment]
Seems fine ;)

**Comment by ljacqu** [comment]
Cheers!
