### ISSUE TITLE
[Dev] Fix public field on PlayerListener

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#1145]
In PlayerListener:

```java
public static final Map<String, String> joinMessage = new ConcurrentHashMap<>();
```

this map is being written to and read from. Typical Java conventions dictate that this should be done via dedicated methods. Suggestion: move the field to some service and add relevant methods. See also `TODO #1145` in the code.

**Comment by sgdc3** [comment]
@ljacqu is it ok? ;)

**Comment by ljacqu** [comment]
Look good, thanks! :) Once the entry for PlayerListener is removed in ClassesConsistencyTest (see `TODO #1145`) this issue can be closed.
