### ISSUE TITLE
Name's cases bug (toLowCase())

### ISSUE THREAD

**Issue by MikroAcse** [Xephi/AuthMeReloaded#115]
Hello!
Developer, please, make an option to disable toLowCase(), when saving player's info into the database.
It's an issue, because users can register nicknames with different cases (for example: abc, aBc, abC) and create NEW configs for the same person.
If you make an option to disable toLowCase(), person can login ONLY with the name, which he registered first time. 
For instance: he registered nickname baAb. If the option enabled, he now can only login with THIS name (baAb), and if he login with name, for example, bAab, he will receive an error: "Your nickname is bAab! Write it in the right case."

It's the problem on offline-mode servers. Don't ignore us.
Thank you. Best wishes, Vitaly.

**Comment by Trojaner25** [comment]
This was already reported...

**Comment by sgdc3** [comment]
yes, we are working on it, stay tuned ;)

**Comment by MikroAcse** [comment]
Thank you!
Sorry, if it was already reported..

I have no time to review all issues

**Comment by Xephi** [comment]
I've try, if I register with Xephi,  and want to join the game with XEPHI, it will ask me to login :O

**Comment by MikroAcse** [comment]
Xephi, no, it's not the problem. The problem is that other plugins create new configs for every person with the same nickname, but different case.
So, may you make an option to disable joining with the same nickname and different case? Just kick that person with the message, which can be configured in en.yml

**Comment by Xephi** [comment]
Oh , ok, have't understand it like that ... Working on quickly, sorry for delay

**Comment by MikroAcse** [comment]
Thank you for understanding!

**Comment by Xephi** [comment]
Fixed https://github.com/Xephi/AuthMeReloaded/commit/4c2fad3643803fe2cdc74c9101f7e4644a5d686b
