### ISSUE TITLE
Timings lag caused by Authme Dev-5.0 

### ISSUE THREAD

**Issue by prozhong** [Xephi/AuthMeReloaded#119]
http://timings.aikar.co/?url=11875678

Here is my timings and I know Authme is only a small problem... in this situation

My question is : is that Authme's Performance okay? Or I set any settings wrong?

**Comment by Xephi** [comment]
Which build do you use ?

**Comment by prozhong** [comment]
one pretty old  dev version
i thought its from the old CI server, downloaded on June/3/2015

**Comment by Xephi** [comment]
oh, ok, try latest one : http://ci.xephi.fr, there are so much performance improvement

Xephi

**Comment by prozhong** [comment]
okay I will give feedback in this week..

**Comment by prozhong** [comment]
may I ask which version should I download?

	AuthMe-5.0-beta1.jar
	AuthMe-5.0-beta2.jar
	AuthMe-5.0-beta3.jar
	AuthMe-5.0-SNAPSHOT.jar

**Comment by Xephi** [comment]
beta3 or SNAPSHOT if you want the latest one

**Comment by prozhong** [comment]
I installed the #_54 snapshot version on CI server
I will do timings later this week,when player numbers meet max level...

By the way what's the new config merged?

**Comment by sgdc3** [comment]
@prozhong 
Do you mean the message in the console when server starts?

**Comment by prozhong** [comment]
@sgdc3 yep,seems no need to change that after auto-merged?

Another thing is  I found the 'SaveQuitLocation: true' does nothing in the new #_54 snapshot version 

My players found them teleported to the same location everytime after login

And In my mysql table,the "x,y,z" stay the same...seems wont be changed after one player login

**Comment by prozhong** [comment]
http://timings.aikar.co/?url=11882699

new timings.....seems worse..

**Comment by sgdc3** [comment]
@prozhong We found the problem, we will fix it very soon ;)

**Comment by prozhong** [comment]
Okay...May you keep an eye the new timings if possible

And one player lost connection after new version authme installed
"worker lost connection: Internal Exception: java.io.IOException:"
Then he logged in found his inventory empty,all his items and equip gone

Is there anything related?

**Comment by sgdc3** [comment]
@prozhong Can you open a new issue for every problems? It's hard to keep track of them if they are into one single issue report. ;)

**Comment by prozhong** [comment]
fine

**Comment by sgdc3** [comment]
@prozhong Thanks ;)

**Comment by sgdc3** [comment]
FIXED! :D Thanks to @Xephi

**Comment by sgdc3** [comment]
@prozhong Try this version ;) https://circle-artifacts.com/gh/Xephi/AuthMeReloaded/29/artifacts/0/home/ubuntu/AuthMeReloaded/target/AuthMe-5.0-SNAPSHOT.jar

**Comment by sgdc3** [comment]
it's an alternative link to latest dev build since our jenkins is offline ;)
