### ISSUE TITLE
Player's item lost - Just happened once

### ISSUE THREAD

**Issue by prozhong** [Xephi/AuthMeReloaded#124]
I don't know whether its due to Authme...............

After new version authme(#_54 DEV) installed
One player ( named 'worker' ) lost connection with " worker lost connection: Internal Exception: java.io.IOException:"  (This must not Authme's fault)
Then he logged in found his inventory empty,all his items and equip gone.
(Its confirmed cuz I used " /invsee")
But when I checked his player.dat using NBTexplorer , all his items stay there...

Is there anything related?

**Comment by sgdc3** [comment]
I think this may be related to our protectInventory feature :/ I think we should add some check in it.

**Comment by Xephi** [comment]
Is he logged before get an internal exception ?

**Comment by sgdc3** [comment]
Fixed!

**Comment by prozhong** [comment]
@Xephi yep , he logged in and played for a while until getting an internal exception

Its hard to track and give feedback on this issue...So you may close this if you think it fixed

:+1:
