### ISSUE TITLE
We need more awesome people in our team!

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#131]
We need:
- Experienced Developers (1 or 2)
- Web Developers (for the new Web Interface) (1 or 2)
- Basic Developers (2 or 3)
- Documenters (2 or 3)
- Ticket Managers (3)
- Translators

If you want to partecipate actively to the project, please, write below some informations about you, like:
- Name
- Languages
- Old Experiences and current Projects
- What do you think you could do to enhance the project?

**Comment by Trojaner25** [comment]
I'd like to be a ticket manager, since I'm an experienced java developer and already had my own modified fork of AuthMe (which allowed logins via the Woltlab Burning Board software). My current projects are all plugins at https://github.com/Static-Interface and some C# projects. 

I'm able to speak German, Turkish and ofc English

**Comment by sgdc3** [comment]
@Trojaner25 So, would you like to be a developer or a ticket manager? :)

**Comment by Trojaner25** [comment]
Ticket Manager, since I don't have enough time to be a developer

**Comment by sgdc3** [comment]
Ok, feel free also to help us with new features and bugfixes :) Atm, can you check if our German and Turkish translations are OK? Thanks :)

**Comment by Trojaner25** [comment]
Ok

For some reason the Turkish one does not have special characters. Does the config support UTF-8?

**Comment by sgdc3** [comment]
We only support UTF-8 xD (Without BOM)

**Comment by sgdc3** [comment]
Don't send PR here, senf them at the AuthMe-Team fork

**Comment by WaterXCubic** [comment]
I might be able to be the zhhk translator 

你好 xD

**Comment by sgdc3** [comment]
@WaterXCubic it's fine :)

**Comment by Bodyash** [comment]
Bohdan Shkliarenko 21y old.
English, Russian, Ukrainian
Low Java knowledge (want to learn it), have a small server (30-70 daily online)
I can help with translation and i think it`s a good Exp in Java learning. Ty

**Comment by sgdc3** [comment]
Ok ;)

**Comment by sgdc3** [comment]
@Bodyash Ok, :) can you check our current russian translation?

**Comment by sgdc3** [comment]
look at our english new translations

**Comment by sgdc3** [comment]
we changed colors and style

**Comment by sgdc3** [comment]
also @irobin591 and @WaterXCubic can you check our current translations and adapt them to the English translation file style? Thx :)

**Comment by sgdc3** [comment]
also @Maxetto puoi adattare la versione italiana? :) Basta cambiare lo stile

**Comment by sgdc3** [comment]
REMEMBER: DON'T CHANGE THE "<theCaptcha>" STRING!

**Comment by WaterXCubic** [comment]
K i gonna check it

**Comment by Bodyash** [comment]
@sgdc3 i will look into it

**Comment by sgdc3** [comment]
@irobin591 are you there? We need you to continue the DE translation. :)

**Comment by sgdc3** [comment]
@Bodyash How is going with the russian translation?

**Comment by sgdc3** [comment]
@irobin591 Thank you! Your translation will be merged into the xephi fork when the other translations will be finished :)

**Comment by Bodyash** [comment]
@sgdc3 merged

**Comment by sgdc3** [comment]
@Bodyash Thank you :)

**Comment by sgdc3** [comment]
BUMP

**Comment by DNx5** [comment]
maybe I can help. But, I never work with public project before (Still learning git). :smile: 
My main language is Indonesia.

**Comment by sgdc3** [comment]
@DNx5 Git is very simple, if you want I can help you :) We need someone expert with database connection pools but we need also someone to help the main developer to fix the bugs.

**Comment by DNx5** [comment]
@sgdc3 Okay, thank you :D
I will help for fixing the bugs. I thought the database connection pools already better with HikariCP. 
just the Inventory cache problem.

**Comment by sgdc3** [comment]
@DNx5 Ok, can you join the development chatroom? :) https://gitter.im/Xephi/AuthMeReloaded
