### ISSUE TITLE
PermissionsEx purge doesn't work

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#134]
reported on bukkit page

**Comment by Xephi** [comment]
I use VaultAPI to do this :/

**Comment by sgdc3** [comment]
probably is a UUID issue :/

**Comment by sgdc3** [comment]
We are using Vault with player names

**Comment by sgdc3** [comment]
but probably with latest versions Pex uses UUID

**Comment by sgdc3** [comment]
@Xephi

**Comment by sgdc3** [comment]
Old issue, no more informations about the issues
