### ISSUE TITLE
5.0 can not support 1.7.10?

### ISSUE THREAD

**Issue by authme** [Xephi/AuthMeReloaded#138]
I can't use it for Cauldron, get some errors.

**Comment by WaterXCubic** [comment]
It does not suppot 1.7.10 because its dev version,it only supports 1.8

**Comment by authme** [comment]
Where can I found the 3.5 Version or 3.4 Version's Code? I need it...

**Comment by sgdc3** [comment]
It should work with 1.7.10

**Comment by sgdc3** [comment]
@authme And why you pick the name "authme" ? :/

**Comment by authme** [comment]
@sgdc3 Because I only look for AuthMe on Github. But, it does not work...

**Comment by sgdc3** [comment]
I think the problem is cauldron, the plugin should work on a normal spigot 1.7.10 installation...

**Comment by sgdc3** [comment]
I will investigate..

**Comment by sgdc3** [comment]
@authme About the name, can you change it? It's very confusing xD

**Comment by Trojaner25** [comment]
@authme https://github.com/Xephi/AuthMeReloaded/tree/faabe0e31565f14ed11a7932e0e9d13d46b11c05 Here you go

**Comment by sgdc3** [comment]
3.5 is unstable

**Comment by Trojaner25** [comment]
Still stabler in some cases than 5.0

**Comment by sgdc3** [comment]
latest 5.0 build is stable, lag issue fixed, email system fixed, we have only the lowercase thing (it is also in 3.5)

**Comment by sgdc3** [comment]
CAN'T REPRODUCE! It works perfectly on both spigot 1.7.10 and kcauldron!

**Comment by sgdc3** [comment]
@Xephi Can't reproduce, you can close this
