### ISSUE TITLE
Join with big/small characters, please FIX

### ISSUE THREAD

**Issue by NickFirenzo** [Xephi/AuthMeReloaded#139]
Please fix this problem, this is very big problem. Players can join with small/big characters. Please fix
Spigot TOPIC: https://www.spigotmc.org/threads/help-me-fast-please-small-and-large-characters-the-name-when-do-join.79653/
Essentials topic: https://www.spigotmc.org/threads/essentials-problem-about-big-small-characters.80081/

**Comment by sgdc3** [comment]
We are working on it :) Stay tuned!

**Comment by Trojaner25** [comment]
duplicate

**Comment by sgdc3** [comment]
@Trojaner25 It's fine. The other issue is not very clear and suggest a wrong way to fix the problem.

**Comment by NickFirenzo** [comment]
Sorry for spam, but please hurry up.
Thanks a lot for answer :)

**Comment by Xephi** [comment]
Fixed https://github.com/Xephi/AuthMeReloaded/commit/4c2fad3643803fe2cdc74c9101f7e4644a5d686b
