### ISSUE TITLE
Need help, about AuthMeBridge please help me.

### ISSUE THREAD

**Issue by NickFirenzo** [Xephi/AuthMeReloaded#141]
I need help. I do not know how to connect with AuthMeBridge with proxy servers and bukkit. I try to connect, everything is fine. But I have an unclear. How to make do with the same account as the HUB can play without having to log on again minigames / roleplay and so on, or to other servers?
 
When I let the other servers AuthMe AuthMeBridge and then generate new folder AuthMe accounts, how to fix it can afford a player who is the Hub account can afford to play on all servers without new registration?

Video tutorial? Thanks :)

**Comment by sgdc3** [comment]
AuthMeBridge is an unofficial project, but I can help you with the configuration :)
On which server do you have authme installed?

**Comment by NickFirenzo** [comment]
On HUB, and on hub I have all registered accounts

**Comment by NickFirenzo** [comment]
And now, how can I install authme on other servers with folder of HUB?

**Comment by sgdc3** [comment]
All the servers are in the same machine?

**Comment by NickFirenzo** [comment]
You will tell me how or not?

**Comment by sgdc3** [comment]
yes :) but I need to understand how your network is structured

**Comment by NickFirenzo** [comment]
On one machine and?...

**Comment by NickFirenzo** [comment]
Is not on one machine, why?

**Comment by sgdc3** [comment]
AuthMeBridge works only on this way: Only the lobby server have authme, the other server can't be access from the internet, only by the bungeecord
