### ISSUE TITLE
Login session with BungeeCord

### ISSUE THREAD

**Issue by Ownercz** [Xephi/AuthMeReloaded#15]
Version: 3.5-Snapshot

Problem: After the player gets logged in at lobby server and moves to another server within BungeeCord network (like survival etc.) he has to login again. 
Those servers have the same AuthMe plugin and configuration as well, but session login is not working on any of them.

Config: http://pastebin.com/FMrLXc3H

**Comment by Xephi** [comment]
i think datas are not update in time, looking in
