### ISSUE TITLE
Add login/register exception permission

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#151]
like unrestrictedusers

**Comment by WaterXCubic** [comment]
Great

**Comment by Xephi** [comment]
Whut ?

**Comment by sgdc3** [comment]
@Xephi add a permission that allow the player to join without login (like unrestricted users)

**Comment by Xephi** [comment]
Huum, why ? x) Permission depend on player name/ UUID :O Unrestricted users depend on IP , it will be not safe at all to do that :O

**Comment by sgdc3** [comment]
Yeah, it's true, this would work only with auto-in
