### ISSUE TITLE
Items not stacking

### ISSUE THREAD

**Issue by jqzua** [Xephi/AuthMeReloaded#16]
Hello,
I'm using version: 3.5-Snapshot
Sometimes, items don't stack correctly and you have to use more than one slot in the inventory.
When you try to group them, you can't.
They are more users with the same problem here:
http://www.spigotmc.org/threads/authme-reloaded-item-stacking-bug.39696/
http://www.spigotmc.org/threads/items-sometimes-dont-stack.29701/

Thank you

**Comment by k3ldon** [comment]
me too!!

**Comment by animexxx** [comment]
me too

**Comment by Kongolan** [comment]
Same here and needs urgent fix!

**Comment by nhanb** [comment]
I've got this bug too. According to [this comment](http://dev.bukkit.org/bukkit-plugins/authme-reloaded/tickets/922-item-stacking-bug/?comment=2), it's because AuthMe added some `tag` field to the item. What's the priority for a fix for this? I'm more than willing to help out if someone could tell me what that `tag` is used for and where the relevant code is.

**Comment by Kongolan** [comment]
@nhanb The code is at com.comphenix.attribute. The attribute system is called by the item storage, when someone logout (i assume this). I can't find any fix for it myself, i tried already.

**Comment by nhanb** [comment]
Hmm no luck from my side either. @Kongolan: I'm sorry if this is off-topic but do you happen to know an alternative to AuthMe that works for 1.8?

**Comment by k3ldon** [comment]
try with that...
https://drive.google.com/file/d/0ByxJmcDQPwmLaDFrYlNsbW5ldUE/view?usp=sharing

**Comment by Trojaner25** [comment]
@k3ldon I decompiled it, you are using a very dirty solution. I will break all plugins which use NBT Tags...

**Comment by k3ldon** [comment]
well only if you use nbt tags... if you find a better solution post it :D

**Comment by Kongolan** [comment]
@nhanb No need for another plugin, i just wait for the update of it. Hope it's soon. It doesn't even influences gameplay this much.

**Comment by Xephi** [comment]
Fixed : https://github.com/Xephi/AuthMeReloaded/commit/514d5bfe6e7f5e7f0f2ca01b1923ec9bcfe1c0dd
