### ISSUE TITLE
Can't restore OP on connection loss

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#164]

**Comment by Xephi** [comment]
how to reproduce?

**Comment by sgdc3** [comment]
I think when connection time out it doesn't save the Op status.... I have too few informations about it...

**Comment by sgdc3** [comment]
Op state is lost after server restart!

**Comment by sgdc3** [comment]
@Xephi

**Comment by sgdc3** [comment]
Nope, this was related to the AutoIn compatibility issue!
