### ISSUE TITLE
Lowercase Bug

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#165]
From an user report:

"My real name is qaz852, if someone try to enters as QAZ852 he is kicked
but qaz852 will be unable to move or use commands!!!"

Probably we forgot a toLowerCase()

**Comment by Xephi** [comment]
qaz852 will be unable to move or use commands!!! after logged in ? >.>

**Comment by sgdc3** [comment]
no, when the server kicks the wrong username the real name will be set in limbo state

**Comment by sgdc3** [comment]
@Xephi

**Comment by Xephi** [comment]
Fixed i hope

**Comment by sgdc3** [comment]
Fixed
