### ISSUE TITLE
You are not the Owner of this account, please try another name! 

### ISSUE THREAD

**Issue by Dimatert9** [Xephi/AuthMeReloaded#168]
This is again! Its full convert to sqlite and i cant connect. Pls fix it! Nick is 100% correct!
In old DB all nicknames save with lowercase. Player name is F_I_N but in file his name kept as a  f_i_n.
And after converting his name in sqlite is f_i_n and he is can login how f_i_n. But dont can how F_I_N
Fix it. 90% of users have big letter in their names but in DB theirs nick have all lowercase letters.

Sorry for my BAD English!

**Comment by iedeso** [comment]
I have the same problem, any help?

**Comment by sgdc3** [comment]
We are working on a fix ;)

**Comment by sgdc3** [comment]
@iedeso @Dimatert9 Fixed! You have to set the backend to file, start the server, wait for database conversion and then restart. ;)

**Comment by Xephi** [comment]
Fixed in build 123 , please remove authme.db (always keep your auths.db and set backend in config.yml to file)

**Comment by sgdc3** [comment]
@iedeso @Dimatert9 read @Xephi 's instructions ;)

**Comment by Dimatert9** [comment]
Yes! It works!
Need fix #169
