### ISSUE TITLE
AuthMe create ALLOT OF THREADS!!!

### ISSUE THREAD

**Issue by Dimatert9** [Xephi/AuthMeReloaded#169]
http://i.gyazo.com/28bfd22964827c868ecba2496011ead5.png
http://i.gyazo.com/7e5bbf29f893f07ab635fdbe3d188f4a.png

**Comment by Dimatert9** [comment]
![](http://i.gyazo.com/2e01cb69c759d213568cd45f3e3c49a7.png)

**Comment by Dimatert9** [comment]
This need fix!

**Comment by Trojaner25** [comment]
Whats the problem?
CPU load and ram usage aren't that high..

**Comment by sgdc3** [comment]
The problem is we have too many threads running.

**Comment by Xephi** [comment]
Does it cause any performance issues?

**Comment by sgdc3** [comment]
@Dimatert9 how many users are playing at the same time?

**Comment by Dimatert9** [comment]
This is login server. But other servers is verry lagging. I had 5 servers where there was AuthMe. And in one server AuthMe create  1 400 000 thread in 90 min, My english is bad. But this drop performance in others servers.

**Comment by sgdc3** [comment]
@Dimatert9 Yes but how many players you have on your network?

**Comment by Dimatert9** [comment]
Not much. 75

**Comment by sgdc3** [comment]
ok, it's a problem XD

**Comment by sgdc3** [comment]
@Xephi need to fix this, very quickly

**Comment by Dimatert9** [comment]
AuthMe:
http://i.gyazo.com/859485413888786e0c4a019c5151333d.png
[14:07:57 INFO]: Plugins (6): PermissionsEx, AuthMe, CommandSync, HideStream, ProtocolLib, NoCheatPlus
Hub:
http://i.gyazo.com/0845a9cb563b7e995fcaea620f5bcdb6.png
[14:09:26 INFO]: Plugins (26): WorldEdit, JoinCommands, Essentials, SimpleBungeePortals, VoidWorld, AutoMessage, ProtocolLib, WorldGuard, NoCheatPlus, AutoSaveWorld, SuperTrails, MaxBans, TickOptimizer, TimeToDoubleJump, PermissionsEx, CommandSync, CustomJoinItems, Player_Visibility, Vault, HideStream, EssentialsSpawn, TitleManager, ShoppingCartReloaded, ChestCommands, ChatEx, BungeeTabListPlus_BukkitBridge

**Comment by Dimatert9** [comment]
http://pastebin.com/sxkP3F3x

**Comment by Trojaner25** [comment]
The last thing you posted happend outside the java VM. So its an issue with an external library which an authme library depends on (in this case: libsqlitejdbc.so).

**Comment by sgdc3** [comment]
Ok now i'm sure the problem is how we manage the connections to the database.

**Comment by Dimatert9** [comment]
I got this error when I turn off the server

**Comment by games647** [comment]
So is it fixed now?
