### ISSUE TITLE
Support for 3rd party logins (allow custom logins via API)

### ISSUE THREAD

**Issue by Trojaner25** [Xephi/AuthMeReloaded#172]
Hey,
It would be nice if there would be an API allowing other plugins to define custom login types.

For example, a player would be able to login with his forum credentials, or other plugins may add 2 factor authentifications like those from google, etc...

A simple implementation would be an event which is fired upon handling of login. It could check it with functions like event.isSuccess() and event.setSuccess(boolean value)

**Comment by Trojaner25** [comment]
push?

**Comment by sgdc3** [comment]
ATM we have too many bugs to add new features xD Just be patient! ;)

**Comment by Trojaner25** [comment]
ok :D

**Comment by Xephi** [comment]
is it a pre /login or a post  /login ?

**Comment by Trojaner25** [comment]
pre /login i think

**Comment by Xephi** [comment]
Is that one ok ? : 
https://github.com/Xephi/AuthMeReloaded/commit/e1eb22239ac934fa024770c175b39c0698a1d22d

**Comment by Trojaner25** [comment]
hmm.. i will maybe commit a PR in a few days

**Comment by Xephi** [comment]
?

**Comment by Trojaner25** [comment]
I meant more somthing like an event which is fired before login, with functions like getPlayer() and getPassword() (or getArgs()?), so plugins could use AuthMe's infrastructure to allow other login implementations

-> Login Command -> Call event with args -> Check if event was successfull (if another plugin handles the login) -> if yes, login the player directly -> if no, do an default authme login (check pw etc)

**Comment by sgdc3** [comment]
@Trojaner25 Any news about your idea? :)

**Comment by sgdc3** [comment]
Bump

**Comment by Trojaner25** [comment]
Since I'm very busy with my own Plugins (Sink-Plugins & ReallifePlugin @ Static-Interface), I currenlty don't have enough time to do this...

**Comment by sgdc3** [comment]
@Trojaner25 any news? Can you write the interface of the methods you need?

**Comment by sgdc3** [comment]
@ljacqu @games647 @DNx5 can you look at this? I can't understand what @Trojaner25 needs in addition to our API.

**Comment by Trojaner25** [comment]
Currently I stoppped developing bukkit plugins, so this can be closed.

**Comment by sgdc3** [comment]
@Trojaner25 Lol this feature may be useful to someone else ;)

**Comment by sgdc3** [comment]
Ok, i think this feature will be avariable when the plugin will be splitted into more modules ;)

**Comment by ljacqu** [comment]
Just to quickly comment—probably Trojaner would have just required a few tweaks to our PreAuthEvent if I'm not mistaken.
