### ISSUE TITLE
Username with different capitalization can join without login when the "genuine" is online

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#174]
**Description**
When a user is online, it is possible for someone else to join with the same name using different capitalization. The user will immediately join as a logged in user and be able to do whatever a logged in user can do.

**Version**
AuthMe Version: 5.0-SNAPSHOT, running on Spigot-d97e08b-5e85956 (MC: 1.8.8) (implementing API version 1.8.8-R0.1-SNAPSHOT)

**Steps to reproduce**
1. Join with a username, e.g. "bobby", and register it (/register [pw] [pw])
2. Join with same name using different capitalization, e.g. "Bobby", when the genuine "bobby" is online and has logged in
 **Result:** User does not have to log in and is regarded as a logged in player
 **Expected:** User should not be logged in and should have to use /login, or he should be rejected

Note that this does not only happen when testing from the same computer: we observed this behavior while being on two different continents, so this is a major issue.

**Technical Hint**
In offline mode, the UUID is not the same for the same usernames with different capitalizations, e.g. "bobby" and "Bobby" have completely different UUIDs.

**Comment by Xephi** [comment]
Fixed : https://github.com/Xephi/AuthMeReloaded/commit/11db85ac2692d07b8fde51e649aefda41d20d699

Build : http://ci.xephi.fr/job/AuthMeReloaded/127/

Xephi

**Comment by ljacqu** [comment]
I can confirm the fix – thank you.
