### ISSUE TITLE
Authme error, and lagg.

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#180]
http://pastebin.com/pTCZ0EtW

**Comment by sgdc3** [comment]
Fixed in latest dev build, you can get it at: http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by andris155** [comment]
Thanks

**Comment by sgdc3** [comment]
Is it fixed? :) @andris155

**Comment by andris155** [comment]
Yes

**Comment by sgdc3** [comment]
@andris155 Can you close this issue? :)
