### ISSUE TITLE
Authme java crash stop server.

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#181]
http://pastebin.com/2aSYJ7ez
http://pastebin.com/BAVj13UF

**Comment by sgdc3** [comment]
@andris155 Are you maybe using AutoIn? AutoIn is incompatible with latest version of AuthMe.

**Comment by andris155** [comment]
Not used AutoIn

**Comment by andris155** [comment]
14.08 19:21:43 [Server] INFO Plugins (51): PlugMan, ConsoleScheduler, AntiBotUltra, ChatColor, CoreProtect, AsyncWorldEditInjector, WorldEdit, FrameProtect, ClearLag, ChatControl, Chairs, ProtocolLib, NoCheatPlus, LibsDisguises, NoNBT, RedstoneClockDetector, BlocksHub, PermissionsEx, Vault, ProtocolSupport, FamoustLottery, WorldGuard, SkinsRestorer, BlocksHub-WorldGuard, monkeysLockette, RandomTeleport, MyCommand, PlayerHeads, RedstoneClockPreventer, CombatLog, Essentials, PlotMe, Jobs, Auctions, Multiverse-Core, TreasureChest, AsyncWorldEdit, EssentialsChat, CraftBook, ChestShop, MobArena, EssentialsGeoIP, EssentialsSpawn, TitleManager, iZone, AreaShop, Paintball, AuthMe, AsyncWorldEdit-TitleManager, LimitedCreative, MineMarket

**Comment by Xephi** [comment]
Ok, I see, it appears AuthMe trying to disabled at the same time to register a player quit, did you experience this when turning off server or it could appear whenever?

**Comment by andris155** [comment]
stop server + online players = crashed java.
stop server + no online players = no crashed java.

**Comment by Xephi** [comment]
What's your version of Craftbukkit/Spigot ?
Also the crash doesn't appear if you kick all players before the stop ?

**Comment by andris155** [comment]
This server is running CraftBukkit version git-Spigot-fdc1440-53fac9f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
online players + kickall, and stop server = no crashed java.

**Comment by Xephi** [comment]
oh ok, also you prefere use CraftBukkit instead of Spigot ? Can you test with Spigot and tell me if you got the same problem ?

**Comment by andris155** [comment]
"git-Spigot-fdc1440-53fac9f" = uses spigot 1.8.8

**Comment by Xephi** [comment]
oh sorry T.T ok i'll investigate a bit more, stay tuned

Xephi

**Comment by andris155** [comment]
New pastebin link: http://pastebin.com/kW6u8uwh

**Comment by sgdc3** [comment]
Which version of authme are you using?

**Comment by andris155** [comment]
Latest 5.0 Dev.

**Comment by sgdc3** [comment]
try 5.1

**Comment by sgdc3** [comment]
http://ci.xephi.fr/job/DEVBUILD-ONLY/lastSuccessfulBuild/artifact/target/AuthMe-5.1-SNAPSHOT.jar

**Comment by andris155** [comment]
Thanks

**Comment by sgdc3** [comment]
@andris155 Can you close this issue? :)
