### ISSUE TITLE
Authme bug.

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#182]
https://www.youtube.com/watch?v=d-vdZpNJYJk&feature=youtu.be
Latest dev. version.

**Comment by sgdc3** [comment]
@andris155  Thanks :) Can you try this version? http://ci.xephi.fr/job/DEVBUILD-ONLY/lastSuccessfulBuild/artifact/target/AuthMe-5.0-SNAPSHOT.jar

**Comment by andris155** [comment]
Bug fixed.
New bug Console error player join: http://pastebin.com/4qNdLbEL

**Comment by sgdc3** [comment]
@andris155 Ok, fixed, redownload the jar from the same link :)

**Comment by andris155** [comment]
Thanks. :+1:
