### ISSUE TITLE
Inventory wipe

### ISSUE THREAD

**Issue by DNx5** [Xephi/AuthMeReloaded#184]
sometimes I get this message in console.
"Error on creating an inventory cache for DNx, maybe inventory wipe in preparation..."
and my inventory wiped out :unamused: 
I hope it will be fixed

**Comment by Xephi** [comment]
Can you test with latest build please? Thx

**Comment by DNx5** [comment]
I will test it, since it's not happening too often. I think it's caused by database connection error

**Comment by Xephi** [comment]
Huum, Yep , i need to make a workaround to prevent that kind of lost data

Xephi
