### ISSUE TITLE
Authme error randomly players join.

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#187]
http://pastebin.com/CiH5Z2kc
version: Authme 5.0 DEV.

**Comment by Xephi** [comment]
With the latest dev build ?

**Comment by andris155** [comment]
Yes, I use latest build.

**Comment by Xephi** [comment]
What kind of database do u use ?

**Comment by andris155** [comment]
Use default database settings. (authme.db)

**Comment by sgdc3** [comment]
sqlite?

**Comment by andris155** [comment]
Yes, I use sqlite database.

**Comment by sgdc3** [comment]
Ok, try this version: http://ci.xephi.fr/job/DEVBUILD-ONLY/lastSuccessfulBuild/artifact/target/AuthMe-5.0-SNAPSHOT.jar
It should be more "verbose" and should print in the console more informations about the issue :)

**Comment by sgdc3** [comment]
It will print a java stack trace of the error :)

**Comment by sgdc3** [comment]
@andris155 can you test this version please? :)

**Comment by andris155** [comment]
Waiting for test. My server registered over 45 000 players. Players don't like restart, and the bugs.

**Comment by andris155** [comment]
The linked plugin installed another server, and testing. Waiting for reproduce bug.

**Comment by sgdc3** [comment]
@andris155 if you have a bungeecord network you can hot swap the plugin, right? :)

**Comment by andris155** [comment]
My servers not use bungecoord.

**Comment by andris155** [comment]
The linked plugin error: http://pastebin.com/DFzeQfk0

**Comment by sgdc3** [comment]
@Xephi wrong enchantment cache reader ;)

**Comment by sgdc3** [comment]
@Xephi should be easy to fix

**Comment by sgdc3** [comment]
@Xephi but if it works with version 1.8.3 it means that something changed with the enchantment system

**Comment by sgdc3** [comment]
@andris155 Any news?

**Comment by sgdc3** [comment]
@andris155 It's fixed now, can you close this issue?

**Comment by andris155** [comment]
Yes
