### ISSUE TITLE
Converter FlatToSQLite Error

### ISSUE THREAD

**Issue by VladStarr** [Xephi/AuthMeReloaded#188]
Hi.

When i'm trying to convert from flat-file to sqlite, plugin throws errors.

`[16:04:41 WARN]: [AuthMe] ERROR: [SQLITE_ERROR] SQL error or missing database (table authme_accounts has 12 columns but 10 values were supplied)`

I'm using sqlite database, i had converted it to mysql, using this commands:
```
/converter sqltoflat (with sqlite backend in config)
/converter flattosql (with mysql backend in config).
```
This works.

If I want to convert from mysql to sqlite, i'm using:
```
/converter sqltoflat (with mysql backend in config)
/converter flattosqlite (with sqlite backend in config)
```
As a result - the error above.
I don't use flat-file, because plugin says, that it's deprecated.

Please, fix that.
Also you can make simple converter - /converter sqlitetomysql and /converter mysqltosqlite :)

**Comment by VladStarr** [comment]
I've found a solution.
On the next server startup it converts from flat to sqlite.
But it's very slow... :(
I'll be glad to see working flattosqlite conversion in next update :)

**Comment by VladStarr** [comment]
I've found a solution.
On the next server startup it converts from flat to sqlite without errors.
But it's very slow...
I'll be glad to see working flattosqlite conversion in next update :)

**Comment by sgdc3** [comment]
@VladStarr Does it work now?
