### ISSUE TITLE
Cannot build due missing dependencies

### ISSUE THREAD

**Issue by DmitryRendov** [Xephi/AuthMeReloaded#196]
Hi guys,

trying to build the application (Java 1.8, Debian) and got this error:
http://pastebin.com/0Jh4F06a

Could you please advise on it?
Many thanks for your help in advance.

**Comment by Xephi** [comment]
If you want a latest compiled version : 
http://ci.xephi.fr/

If you do some change and want to compile by yourself : 
Try to remove the .m2 folder or force a maven update dependency
I don't have any problem, nor jenkins, to compile actually ^^"

**Comment by DmitryRendov** [comment]
Thanks for your quick response. I'm trying to integrate your plugin and Django - your application generates a pbkdf2 hash different from Django 1.7+

It seems this issue is close connected with certs (http://stackoverflow.com/questions/15691985/maven-release-peer-not-authenticated). Deleting .m2 hasn't helped. After adding -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true I've got other error - http://pastebin.com/wx46qD3V

Thanks again.

**Comment by sgdc3** [comment]
It's the same error, I think that you are having problems with your maven installation, does it work with other projects?

**Comment by DmitryRendov** [comment]
You're right. It was maven 3.0.4 SSLv3 issue "peer not authenticated" -- solved by updating to 3.3.3.
It can be closed.

Thanks guys for your help.
