### ISSUE TITLE
[Important] We need urgently another active developer!

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#197]
Don't be shy! If you are using our plugin and you're a developer, please consider to help us! We need you NOW! Thanks ;)

**Comment by InstanceOfDev** [comment]
Add me on Skype: instanceofdev and we can talk about it :)

**Comment by ljacqu** [comment]
I have a lot on my plate but I feel like I could help out in this project, too. My skype and email is my Github username at hotmail dot com if you are interested.

**Comment by sgdc3** [comment]
Well, @InstanceOfDev  @ljacqu start looking into the issue tracker and try to fix some of the issues, if you succeed to do this we can start talking about the recruiment, ok? :)
