### ISSUE TITLE
E-Mail Recovery System is not safe

### ISSUE THREAD

**Issue by xjboss** [Xephi/AuthMeReloaded#199]
Lots of Chinese player use QQ Email so many player know other player's email.
malicious recovery password.
And some thieves hacking other player's account,they can easy to change the email,than account's old owner can't recovery his account.
Best to change send new password the way,send to player a temp captcha,player can use temp captcha to change his password,then malicious recovery become Invalid.
Also change email also need to use temp captcha,then thieves can't change player's email.

**Comment by sgdc3** [comment]
I don't understand the problem, can you explain it more clearly?

**Comment by DNx5** [comment]
I think we need to send verification code when player changed the email. i dont know.

**Comment by sgdc3** [comment]
Yeah but atm we already do this...

**Comment by xjboss** [comment]
Yeah change email and recovery password use verification code.
