### ISSUE TITLE
URGENT build #144 unregister doesn't work also /changepassword doesn't work!!!

### ISSUE THREAD

**Issue by vanjavk** [Xephi/AuthMeReloaded#200]
I think it's not fixed in #149 because I dn't see anything in changes that would say so, but I need this done fast by tonight, (5 hours) please.  1 guy got his account hacked and now he can't change password. I CANNOT CHANGEPASSWORD OR UNREGISTER THEM :(

07.09 17:51:38 [Server] INFO ... 15 more
07.09 17:51:38 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
07.09 17:51:38 [Server] INFO at fr.xephi.authme.commands.ChangePasswordCommand.onCommand(ChangePasswordCommand.java:71) ~[?:?]
07.09 17:51:38 [Server] INFO at fr.xephi.authme.security.PasswordSecurity.getHash(PasswordSecurity.java:122) ~[?:?]
07.09 17:51:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
07.09 17:51:38 [Server] INFO Caused by: java.lang.IllegalStateException: PasswordEncryptionEvent cannot be triggered asynchronously from primary server thread.
07.09 17:51:38 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
07.09 17:51:38 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-fdc1440-53fac9f]
07.09 17:51:38 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-fdc1440-53fac9f]
07.09 17:51:38 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-fdc1440-53fac9f]
07.09 17:51:38 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-fdc1440-53fac9f]
07.09 17:51:38 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-fdc1440-53fac9f]
07.09 17:51:38 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40]
07.09 17:51:38 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40]
07.09 17:51:38 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-fdc1440-53fac9f]
07.09 17:51:38 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-fdc1440-53fac9f]
07.09 17:51:38 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-fdc1440-53fac9f]
07.09 17:51:38 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-fdc1440-53fac9f]
07.09 17:51:38 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-fdc1440-53fac9f]
07.09 17:51:38 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
07.09 17:51:38 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
07.09 17:51:38 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
07.09 17:51:38 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'changepassword' in plugin AuthMe v5.0-SNAPSHOT
07.09 17:51:38 [Server] ERROR null

**Comment by vanjavk** [comment]
i will update to latest build at my regular restart tonight.

**Comment by sgdc3** [comment]
@DNx5 can you check this? Thanks

**Comment by DNx5** [comment]
okay

**Comment by vanjavk** [comment]
Thanks for fast response guys and happy fixing <3

**Comment by sgdc3** [comment]
FIXED! Thanks @DNx5 ;)
Link to latest dev build: http://ci.xephi.fr/job/DEVBUILD-ONLY/
WARNING (this build contains also new untested features, if you can't use it we'll create a build with only this fix)

**Comment by sgdc3** [comment]
@vanjavk

**Comment by vanjavk** [comment]
well If I don't use new features I should be fine ?

**Comment by sgdc3** [comment]
as new features i mean performace enhancements

**Comment by sgdc3** [comment]
if you use sqlite there are no problems
we only modified how mysql connector works

**Comment by vanjavk** [comment]
Oh, well let's just hope everything goes well :) Lemme test this :D

**Comment by vanjavk** [comment]
Hmm I use MYSQL

**Comment by vanjavk** [comment]
is that different?

**Comment by vanjavk** [comment]
I see that it is by googling, not understanding whole concept of SQLs :/  anyways my server host supplies me only with MYSQL, so I'll have to stick with that, but for future, do you recommend SQlite, is it faster than Mysql?

**Comment by sgdc3** [comment]
mysql requires a mysql server to work, it should be faster (it depends by your hosting performance), sqlite a simple version of sql, it doesn't require a server.

**Comment by sgdc3** [comment]
If your mysql hosting is slow you should use SQLite, but if you have lots of registered users you must use mysql!

**Comment by vanjavk** [comment]
Ok big proglem, info coming

**Comment by vanjavk** [comment]
[19:19:20] [Server thread/WARN]: [Server thread] INFO com.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - is starting.
[19:19:20] [Server thread/WARN]: [Server thread] INFO com.zaxxer.hikari.pool.HikariPool - AuthMeMYSQLPool - is closing down.
[19:19:20] [Server thread/WARN]: [AuthMe] ERROR: Exception during pool initialization: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[19:19:20] [Server thread/WARN]: [AuthMe] ERROR: Can't connect to the MySql database! Please check your configuration!
[19:19:20] [Server thread/WARN]: [AuthMe] ERROR: If this error persists, please report it to the developer! SHUTDOWN...
[19:19:20] [Server thread/INFO]: [AuthMe] Disabling AuthMe v5.0-SNAPSHOT

**Comment by vanjavk** [comment]
Other plugins are connecting to mysql just fine

**Comment by vanjavk** [comment]
If anyone's here " if you can't use it we'll create a build with only this fix" this would help me right now

**Comment by sgdc3** [comment]
First try the development build, if you find some issues report them and we'll create a personal build for you

**Comment by vanjavk** [comment]
Uhm, not sure if comments didn't load for you but check above, I tried but it doesn't even want to connect to database

**Comment by sgdc3** [comment]
no this is a wrong mysql configuration issue

**Comment by sgdc3** [comment]
are you sure they are ok?

**Comment by vanjavk** [comment]
It seems to be problem only with latest dev build and not build before that

**Comment by sgdc3** [comment]
ok building it right now

**Comment by vanjavk** [comment]
they're 100% ok sec lemme test again with build #155 then #154

**Comment by sgdc3** [comment]
https://mega.nz/#!2A90VaDZ!aU2Lck_yLh8dPG2gZZ7B41oTkz2AflBpoAU4XYAAflQ build without unstable stuff

**Comment by vanjavk** [comment]
none doesn't seem to work for either 155 or 154, however if i load old .jar with bugged changepassword it connects succesfuly so it's not problem in database configuration

**Comment by vanjavk** [comment]
thanks I'll try that now

**Comment by vanjavk** [comment]
Anyways this was my configuration:
  mySQLColumnName: username
  mySQLTablename: authme
  mySQLUsername: MCSQL_2714
  backend: mysql
  mySQLColumnLastLogin: lastlogin
  mySQLDatabase: MCSQL_2714
  mySQLPort: 3306
  mySQLColumnIp: ip
  mySQLHost: mysql.netherbyte.com
  mySQLColumnPassword: password
  mySQLPassword: HIDDEN
  caching: true
  mySQLlastlocX: x
  mySQLlastlocY: y
  mySQLlastlocZ: z
  mySQLlastlocWorld: world
  mySQLColumnEmail: email
  mySQLColumnId: id
  mySQLColumnLogged: isLogged
  mySQLRealName: realname
I will now test mega.nz version

**Comment by vanjavk** [comment]
Hey this latest one you gave me seems to be working fine :D

**Comment by vanjavk** [comment]
07.09 21:58:12 [Multicraft] Lettawi ran command Message of the Day
07.09 21:58:12 [Server] WARN ERROR: Error while reading file for Lettawi, some wipe inventory incoming...
07.09 21:58:12 [Server] WARN ERROR: Error while reading file for Lettawi, some wipe inventory incoming...
07.09 21:58:12 [Server] WARN ERROR: Error while reading file for Lettawi, some wipe inventory incoming...
07.09 21:58:12 [Server] WARN ERROR: Error while reading file for Lettawi, some wipe inventory incoming...
07.09 21:58:12 [Server] WARN ERROR: Error while reading file for Lettawi, some wipe inventory incoming...

However doesn't seem that he lost anything in his inventory, that's the guy who I changed password for, inventory protection is false

**Comment by sgdc3** [comment]
Yeah if the option was true it will have wiped everything xD

**Comment by sgdc3** [comment]
Now with the new developers we can work on these bugs more quickly ;)

**Comment by sgdc3** [comment]
Expect a stable version soon

**Comment by vanjavk** [comment]
Awesome :)

**Comment by Xephi** [comment]
Fixed

Xephi
