### ISSUE TITLE
Suggestion: Admins register more alt accounts

### ISSUE THREAD

**Issue by vanjavk** [Xephi/AuthMeReloaded#202]
Add permission node or something for when admins want to create new account but it blocks them due to too many accounts from same IP.

So for example I am logged in as vanjavk. I exit minecraft and I start new minecraft with different name. I log into server and type /register, plugin would now:
Check if I can make account:
If not:
  Iterate over all players that logged with my IP
  Check each for permission to register more accounts
  If any of the names has permissions then (like an admin would):
    Allow creation of another account.
  If not:
    Deny creation of account like it used to.

I know that you can already do /authme register, but I'm sometimes switching minecraft names to test stuff It's annoying having to log to my main account again register account for myself, then go back to other minecraft with different name.

Not really important, but would be a very nice feature if it isn't too hard to make it work :)

**Comment by sgdc3** [comment]
:/ this isn't very secure. atm you can already forcelogin someone!

**Comment by vanjavk** [comment]
Okey np :)

**Comment by hokindo9000** [comment]
> Okey np :)

agreed
