### ISSUE TITLE
MaxAccounts Registering per IP setting not working!

### ISSUE THREAD

**Issue by BeastPsycho** [Xephi/AuthMeReloaded#205]
Users are registering accounts, up to 25 in my network!
What happended with the authmereloaded developer?
This version 5 has a lot a bugs....

**Comment by sgdc3** [comment]
Simply @Xephi is too busy atm, we are looking for more developers... Anyway, do you use bungeecord?

**Comment by vanjavk** [comment]
I'm not able to reproduce the bug, please give us more data.

**Comment by BeastPsycho** [comment]
@vanjavk Yes I know it, but i cant downdrade to v4 of AuthmeReloaded, i use a MYSQL databse.
But, the version 5, added UUID support, now:

If you register with, a new username in my network:
mc.risingbattles.com
Do you can register 2 or more accounts with your same IP address, i get notified in server lobby (OP permissions) in chat about some players have up to 25 accounts, do you can fix it?
I have in the config:
    maxLoginPerIp: 1
    maxJoinPerIp: 1

These setting are not working.

**Comment by sgdc3** [comment]
you need to set maxregperip!

**Comment by sgdc3** [comment]
maxlogin and maxjoin are an old feature, probably glitched. Today I will look into it.

**Comment by BeastPsycho** [comment]
@sgdc3 Yes in my config its so:

    maxRegPerIp: 1

This is a bug.

**Comment by NickFirenzo** [comment]
At me work fine maxRegPerIp: 3, and 3 accounds are availible for register per ip.
Use 0 for unlimited
maxregperip work fine.

**Comment by Xephi** [comment]
I can't reproduce the bug :/ Can you please provide more informations ?

**Comment by BeastPsycho** [comment]
@Xephi This was already fixed with last builds

**Comment by sgdc3** [comment]
@BeastPsycho Ok, thanks :) Can you close the issue?
