### ISSUE TITLE
Latest Authme 5.1 DEV.

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#212]
Latest Authme 5.1 DEV. after login set fly speed 2-3.

**Comment by sgdc3** [comment]
You mean it gived fly to everyone or only to already flying players?

**Comment by andris155** [comment]
Fly speed changed already flying players.

**Comment by sgdc3** [comment]
It should reset the speef to the default value, is it too fast or slow?

**Comment by sgdc3** [comment]
speed sorry

**Comment by andris155** [comment]
Default fly speed = 1. AuthMe latest 5.1 DEV. = After /logging already flying players the flying speed change to 2-3 (essentials speed command logic)

**Comment by sgdc3** [comment]
ok i used a wrong default value (2) I will fix it now ;)

**Comment by andris155** [comment]
Thanks. :+1:

**Comment by sgdc3** [comment]
Keep this open please, i will fix the issue tomorrow because git on my mobile isn't working

**Comment by VladStarr** [comment]
@sgdc3, also I`ve noticed that some of players had fly mode after login, but they did not have permission.
It had been already fixed or not yet?

**Comment by sgdc3** [comment]
Probably this isn't an authme issue, nobody else reported this issue... @VladStarr 
I will look on it anyway ;)

**Comment by sgdc3** [comment]
fixed!

**Comment by sgdc3** [comment]
@andris155 Can you close the issue please? :)
