### ISSUE TITLE
Chatcontrol pro latest + Authme 5.1 Snapshot error

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#214]
http://pastebin.com/hfw4K1Qs

**Comment by DNx5** [comment]
@sgdc3 are i am doing wrong by moving that method? because that was not the part of API.

**Comment by sgdc3** [comment]
idk why chat control uses this method -_- we need to contact the plugin's author

**Comment by andris155** [comment]
Plugin link: https://www.spigotmc.org/resources/chatcontrol-pro.10258/

**Comment by andris155** [comment]
Plugin author comment
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/10053476/88176b84-622c-11e5-8686-c0c7eb84c5d2.PNG)

**Comment by DNx5** [comment]
http://ci.xephi.fr/view/All/job/DEVBUILD-ONLY/lastSuccessfulBuild/artifact/target/AuthMe-5.1-SNAPSHOT.jar

**Comment by andris155** [comment]
Thanks!

**Comment by andris155** [comment]
Not work!
23.09 21:53:17 [Multicraft] Server shut down (running)
23.09 21:53:17 [Multicraft] Restarting crashed server in 10 seconds

**Comment by andris155** [comment]
[21:51:08] [Server thread/WARN]: [AuthMe] [AuthMe] Can't load the configuration file... Something went wrong, to avoid security issues the server will shutdown! why?

**Comment by sgdc3** [comment]
Try latest dev build ;)

**Comment by sgdc3** [comment]
@andris155 Fixed!

**Comment by sgdc3** [comment]
@andris155 Can you close this if it's fixed?

**Comment by andris155** [comment]
Thanks!
