### ISSUE TITLE
Changepassword

### ISSUE THREAD

**Issue by Xofter** [Xephi/AuthMeReloaded#218]
Authme 5.1 (newest) when you changepassword shows that the password was changed, HOWEVER it doesnt change the password.

**Comment by sgdc3** [comment]
Thanks for the report :) 
I think @Xephi is going to improve the performance and fix some of the most critical issues this night, more infos tomorrow! :)

**Comment by DNx5** [comment]
@Xofter can you try the latest dev build :smile: do a backup before.
http://ci.xephi.fr/job/DEVBUILD-ONLY/lastSuccessfulBuild/artifact/target/AuthMe-5.1-SNAPSHOT.jar

**Comment by sgdc3** [comment]
@Xofter Can you test latest build and close the issue? :) Thanks

**Comment by Xephi** [comment]
Any new ?
