### ISSUE TITLE
FakePlayers

### ISSUE THREAD

**Issue by evernife** [Xephi/AuthMeReloaded#219]
I cannot allow fake players to join the server. (Using kcauldron)

My config: 
![image](https://cloud.githubusercontent.com/assets/11357801/10063020/60a036e0-623f-11e5-84e6-ebb7b66d8354.png)

**Comment by ChezRD** [comment]
Similar issues here were closed without any response. wtf?

**Comment by DNx5** [comment]
@evernife try to enable this
```AllowRestrictedUser: true```

**Comment by evernife** [comment]
Worked!
