### ISSUE TITLE
Dev Build Bug

### ISSUE THREAD

**Issue by orkun1675** [Xephi/AuthMeReloaded#22]
When a player is killed by CombatTag before logging in, AuthMe throws errors: http://pastebin.com/ia5M7hbz

First error is shown on join (player was killed when logging out, escaping from PvP)
The second error is shown after hitting re-spawn and typing /login

**Comment by orkun1675** [comment]
While fixing the NPE's we should also note that if the player died when logging out, AuthMe should not bring him back to the death location, but leave him at spawn. This actually works as intended right now (if we don't count the errors in console).

**Comment by Xephi** [comment]
Fixed
