### ISSUE TITLE
Accounts

### ISSUE THREAD

**Issue by Xofter** [Xephi/AuthMeReloaded#229]
Sometimes people cant log in to their accounts. It says that player is already playing (even tho they dont)

**Comment by games647** [comment]
Can they log into server?

**Comment by Xofter** [comment]
Like i said no, they cannot log in with their other accounts. However with their main account (or some other) they can. It only happens with a couple of guys,as i can tell.

**Comment by Xofter** [comment]
Seems the problem is with similiar names, for example user Xofter cannot log in if Xofter2003 is logged in or Xofter2003The

**Comment by Xofter** [comment]
Gonna try the newest build see if its fixes it

**Comment by Xofter** [comment]
found out the bug, its with /authme register when u register someone,it shows as logged in. It works fine if someone register it himself ;>

**Comment by sgdc3** [comment]
Are all the users able to login after a restart?

**Comment by Xephi** [comment]
Add a way to force them to re-login after an admin registration
https://github.com/Xephi/AuthMeReloaded/commit/8e90a5f9a82aba9622bf81420394b8fbc767a976
