### ISSUE TITLE
[Feature Request] disabling accounts

### ISSUE THREAD

**Issue by ticklemynausea** [Xephi/AuthMeReloaded#230]
Hi. I'm moving my server from xAuth to AuthMe. After using xAuth for about 4 years I am forced to move out because very sadly it lacks support for java 1.8 and newer versions of Spigot/Bukkit. One of the features we grew really accustomed to was being able to disable accounts without deleting them (xAuth's db schema has an 'active' column in the accounts table).

I'm probably going to be able to pull this off on my own and eventually submit a PR, but I'm posting this here anyway so I can get people's opinion on this)

**Comment by sgdc3** [comment]
What's the difference from the ban?

**Comment by DNx5** [comment]
ban should works too. set the reason message to something about disabled account.

**Comment by ticklemynausea** [comment]
It has little difference from the point of view of a banned or disabled player. But from our managerial point of view though, the 'active' database column is, as I said, something we require. Several parts of our server, including player accounts, are managed through a custom web interface which integrates with the server plugins at the database layer. Disabling accounts through this interface is a must.

**Comment by sgdc3** [comment]
It's only a complication :/

**Comment by ticklemynausea** [comment]
I understand that this is not something everyone requires.

Thanks

**Comment by sgdc3** [comment]
You can do it in other ways :)

**Comment by sgdc3** [comment]
Without modifying your web interface I mean
