### ISSUE TITLE
Set custom stats as visible! (mcstats.org)

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#231]
We are unable to display custom graphs on mcstats.org because we don't own the ownership of the page.

**Comment by sgdc3** [comment]
@darkwarriors has the password

**Comment by sgdc3** [comment]
@Hidendra could you give us access to the page?

**Comment by ljacqu** [comment]
@sgdc3 Since we switched to bstats, ok to close this?

**Comment by sgdc3** [comment]
Sure! ;)
