### ISSUE TITLE
Help ASAP

### ISSUE THREAD

**Issue by Ac3W0lfJ3rk** [Xephi/AuthMeReloaded#233]
My staff and my players on my servers are getting kicked from the server "Your logged in from another location" and 1 member got his house griefed! PLEASE HELP ME (server with offline mode and spigot 1.8.8 authme for 1.8.8)

**Comment by sgdc3** [comment]
try latest dev build here: ci.xephi.fr
and update bungeecord if you use it.

**Comment by Ac3W0lfJ3rk** [comment]
i dont have bungeecord

**Comment by sgdc3** [comment]
ok, just update your authme version

**Comment by Ac3W0lfJ3rk** [comment]
ok, i updated, now i restarted the server see if fies the problem

**Comment by Ac3W0lfJ3rk** [comment]
STILL HAPPENS

**Comment by Ac3W0lfJ3rk** [comment]
please help

**Comment by Ac3W0lfJ3rk** [comment]
WARN]: handleDisconnection() called twice

**Comment by sgdc3** [comment]
@DNx5 @games647 @Xephi

**Comment by Xephi** [comment]
@Ac3W0lfJ3rk Also when people try to connecting to the server, if people is already connected, authme disconnect the player and allow the bad one to connect ?

**Comment by sgdc3** [comment]
@Ac3W0lfJ3rk try latest build

**Comment by sgdc3** [comment]
@Ac3W0lfJ3rk

**Comment by sgdc3** [comment]
@Ac3W0lfJ3rk BUMP, we'll close the issue if you don't answer

**Comment by Ac3W0lfJ3rk** [comment]
fixed, used a plugin that a friend of mine did. AntiUserSteal

**Comment by Xephi** [comment]
Fixed !
