### ISSUE TITLE
Help me, how to configure to teleport on QUIT location when logged in, NOT on SPAWN

### ISSUE THREAD

**Issue by NickFirenzo** [Xephi/AuthMeReloaded#234]
Hi,
I need help with authme. How can I configure in config.yml, when play go offlilne and join/rejoin on server, type his password and teleport on place when he logged out, not on SPAWN. When join on server, type PW and teleport on place when person go logged out.
Camera/screen will be on SPAWN, but when logged in teleport on quit LOC.
THANKS!
Config yml[PASTEBIN]
http://pastebin.com/UnTxRdDC

**Comment by sgdc3** [comment]
Try this:

ForceSpawnLocOnJoinEnabled: false
SaveQuitLocation: true
teleportUnAuthedToSpawn: true
noTeleport: false

**Comment by sgdc3** [comment]
@NickFirenzo

**Comment by NickFirenzo** [comment]
@sgdc3 THANKS A LOT, but I have one question..
ForceSingleSession: true/false
What IF true, what if false? Thanks.

**Comment by sgdc3** [comment]
If disabled if a player tries to login with the username of an online player the online player will be kicked. Keep it ENABLED. ;)

**Comment by sgdc3** [comment]
@NickFirenzo can you close the issue?

**Comment by NickFirenzo** [comment]
Yes, thanks
