### ISSUE TITLE
Another person LOGIN in on account, get kicked

### ISSUE THREAD

**Issue by NickFirenzo** [Xephi/AuthMeReloaded#236]
Hi,
I want to report bug with authme, when person is on server, if someone type your nick and join you will be kicked. Please fix this. Thanks
http://prntscr.com/8s1ltw
Owner of his acoount play normal, but another player make join and owner get kickced.

**Comment by Bodyash** [comment]
Same

**Comment by sgdc3** [comment]
Is forceSingleSession ensbled?

**Comment by sgdc3** [comment]
@NickFirenzo

**Comment by NickFirenzo** [comment]
ForceSingleSession: false
No, why?

**Comment by sgdc3** [comment]
IT MUST BE ENABLED! XD

**Comment by sgdc3** [comment]
Try to set it to true and close the issue ;) @NickFirenzo

**Comment by NickFirenzo** [comment]
Fixed, thanks CLOSE ticket
