### ISSUE TITLE
Authme BUG big/small characters. Fix fast, help fast.. Thanks.

### ISSUE THREAD

**Issue by NickFirenzo** [Xephi/AuthMeReloaded#237]
Hi, 
I need help please help me
How to prevent join with big/small characters?
TOPIC: https://www.spigotmc.org/threads/help-me-fast-please-small-and-large-characters-the-name-when-do-join.79653/

**Comment by NickFirenzo** [comment]
I used the latest version Authme 5.0, updated few days ago

**Comment by sgdc3** [comment]
Try this: http://ci.xephi.fr/job/AuthMeReloaded-Dev/

**Comment by NickFirenzo** [comment]
Thanks.
I fixed with this https://github.com/Shevchik/DatDuplicateRemover (Works with spigot 1.8.8)

**Comment by sgdc3** [comment]
@NickFirenzo can you try without it? It should have been fixed
