### ISSUE TITLE
Gson error

### ISSUE THREAD

**Issue by mariolars** [Xephi/AuthMeReloaded#239]
http://pastebin.com/MM4jvj4E

**Comment by sgdc3** [comment]
Server type(craftbukkit, spigot, paperspigot l, etc...)? version(1.8.8, etc..)?

**Comment by mariolars** [comment]
PaperSpigot 1.7.10

**Comment by sgdc3** [comment]
can you try with ps 1.8?

**Comment by mariolars** [comment]
No error

**Comment by sgdc3** [comment]
ok, one last test: normal spigot 1.7?

**Comment by mariolars** [comment]
Same error like on Paper

**Comment by sgdc3** [comment]
Ok thanks today i will fix it asap ;)

**Comment by sgdc3** [comment]
@mariolars Can you try latest dev build? :)

**Comment by mariolars** [comment]
same error

**Comment by games647** [comment]
Could you send us a list of your plugins? I guess one plugin includes a different gson version.

**Comment by mariolars** [comment]
http://scr.hu/0rj/mzh44

**Comment by sgdc3** [comment]
@mariolars Fixed in latest dev build

**Comment by mariolars** [comment]
Yep, plugin is now loading properly. Thank you.
