### ISSUE TITLE
Authme BUG, player is not on server, say: SAME player is playing on the server with this nickname

### ISSUE THREAD

**Issue by NickFirenzo** [Xephi/AuthMeReloaded#240]
I want to report authme bug. I want to connect on my server, when click on connect get kicked
SAME PLAYER IS PLAYING WITH NICKNAME, it's wrong. The player is not on the server.
SS: I'm offline since 20 minutes http://prntscr.com/8t3dou
Get kicked: http://prntscr.com/8t3eyx ( Translate on english: The player with this NICKNAME is on server)

**Comment by Xephi** [comment]
Can you please test with latest devbuild please? Thanks :
http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by NickFirenzo** [comment]
I'will try, thanks :)

**Comment by Xephi** [comment]
Also you closed it cause it's fixed ?

**Comment by NickFirenzo** [comment]
Again this problem, not fixed :(

**Comment by NickFirenzo** [comment]
It's not fixed :(
Please fix it, thanks

**Comment by NickFirenzo** [comment]
Refresh, please fix it

**Comment by NickFirenzo** [comment]
@Xephi

**Comment by sgdc3** [comment]
Try latest build.

**Comment by NickFirenzo** [comment]
Is it the latest version?
http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by sgdc3** [comment]
jeah :)

2015-11-01 12:09 GMT+01:00 NickFirenzo <notifications@github.com>:

**Comment by NickFirenzo** [comment]
Latest build is 900KB, build witch is on my server is 1.5MB size....

**Comment by sgdc3** [comment]
This means that you need to update xD

**Comment by NickFirenzo** [comment]
Fixed
