### ISSUE TITLE
already in game bug

### ISSUE THREAD

**Issue by Xofter** [Xephi/AuthMeReloaded#241]
i already posted one of these, but it still seems to happen. It only happens in for example Xofter_scrub is online, and you can not log in into Xofter account, you get an error "Xofter is already ingame" or something like that, it doesnt seem to happen when its Xofter340 or so. I am using latest build.

**Comment by sgdc3** [comment]
@Xofer can you try latest build?

**Comment by sgdc3** [comment]
@Xofter

**Comment by sgdc3** [comment]
@Xofter ? :)

**Comment by Xofter** [comment]
Fixed, please lock
