### ISSUE TITLE
AuthMe 5.1 Snapshot inventory bug.

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#246]
Server: Spigot 1.8.8 latest
Authme version: http://ci.xephi.fr/job/AuthMeReloaded/167/
Video: https://www.youtube.com/watch?v=qNpYGp-Kslo&feature=youtu.be

**Comment by Platinteufel** [comment]
http://dev.bukkit.org/bukkit-plugins/authme-reloaded/tickets/987-force-survival-inventory-wipes/

I'm waiting for a fix too ^^

**Comment by sgdc3** [comment]
Which multiinv plugin are you using?

**Comment by andris155** [comment]
I don't using multiinv plugin.

**Comment by Platinteufel** [comment]
But you're running a plugin to handle inventories? Sth. like Multiverse-Inventories or Per-World-Inventories?

**Comment by Platinteufel** [comment]
But I've tested it with several Inventory-Plugins. It's definitely an authme issue @sgdc3

**Comment by andris155** [comment]
Used inv edit plugin: https://onedrive.live.com/redir?resid=3860F4BFDA7C3FED%2115381

**Comment by Platinteufel** [comment]
I've reported it three month ago on BukkitDev and there's still no fix or at least a statement about this bug. That's a bit disappointing. :(

**Comment by NickFirenzo** [comment]
This is not authme bug. Wich plugin for creative use? LimitedCreative/Creative Control?

**Comment by NickFirenzo** [comment]
This is not authme bug. Wich plugin for creative you are using? LimitedCreative/CreativeControl?

**Comment by NickFirenzo** [comment]
Aham, I saw post below. Yes, Limited Creative is problem and I have this problem 3-4 months ago, but I fixed it. You need other plugin wich save inventory on players in BASE, not limited creative.
You can use MultiInv
http://dev.bukkit.org/bukkit-plugins/multiinv/
http://dev.bukkit.org/bukkit-plugins/tuxtwolib/
MultiInv + TuxTwoLib must put in your plugins folder to work. 

1. When you put 2 plugins below, you need going in config.yml at LimitedCreative and edit it.
LimitedCreative config.yml CONFIGURE!: http://pastebin.com/9X6XHvnd

2. MultiInv plugin to save inventory on all players on the server you must configure, pastebin 
Edit MultiInv: http://pastebin.com/Kj60Agf3 

DON'T REMEMBER TO CONFIGURE LimitedCreative in config.YML how on my PASTEBIN!
When you make this steps you can ENJOY :D. If you have any problem, comment on topic

**Comment by Platinteufel** [comment]
There are inventory wipes if you logout in another gamemode than it's defined by Multiverse (e.g. logout with Survival in a Creative-world). It doesn't matter which inventory-plugin you're using.

**Comment by Platinteufel** [comment]
Just tested it with the latest dev-build (487).
- No special AuthMe-Permissions (just defaults like login, register, changepassword, .. )
- default config, clean install (I've changed nothing)
- Survival-World
- Latest Multiinv, also happens with other plugins like Multiverse-Inventories or PerWorldInventory
- Doesn't happen without AuthMe installed.

https://youtu.be/MHF6BxvNlAw

-  No inventory wipes with the permission authme.bypassforcesurvival .. (!?)

**Comment by DNx5** [comment]
it fixed? @Platinteufel

**Comment by Platinteufel** [comment]
Nope, it's still not fixed in build 487.

**Comment by games647** [comment]
Do we actually need to save and restore the gamemode? I think it's useless.

**Comment by sgdc3** [comment]
@games647 I agree

**Comment by games647** [comment]
@Platinteufel Can I send you new version in order to test if the issue still exists?

I already tested my changes, but it's very likely that I forgot something.

**Comment by Platinteufel** [comment]
Seems like everything works fine now, thank you @games647 !
Just one suggestion: Maybe you could disable gamemode restoring by default and the user can enable it in config if they need to. There should be a warning like: "gamemode restoring can cause inventory swaps".

**Comment by games647** [comment]
@Platinteufel it should be already disabled by default because of this commit https://github.com/AuthMe-Team/AuthMeReloaded/commit/0beb937b8fcfef8e1e1b06f42ea65088e403ee5b. The warning hint is really good point. We might add it to the config.

**Comment by andris155** [comment]
Thanks!
