### ISSUE TITLE
Caching issue

### ISSUE THREAD

**Issue by kingpyro** [Xephi/AuthMeReloaded#249]
I run a few servers all sharing the same AuthMe table. Currently running http://ci.xephi.fr/job/AuthMeReloaded/170/ on all servers. All same Spigot version as well. Caching enabled on all. If a Player registers on ServerA then changes to ServerB he is prompted to reregister. Upon typing /register an error message appears in console. Duplicate key ect ect. Which is what would happen since he already registered on the first server. If he tried to ignore the register prompt and use /login you get a User is not registered error message. In addition to all of this, if the Player goes back to ServerA ( the server he initially registered on ) he is prompted with a register message. So it seems that though he got inserted into the mySQL table, he didn't even get put into the Cached table.

Is it possible that when a new player registers it can push the new register out to all the other cached databases including its own? Because it seems like the server will only update the cached database at server start. Caching is great, cept that the database is constantly updating with new players and such.

**Comment by sgdc3** [comment]
Ok found the cause: we need to disable hikari caching

**Comment by DNx5** [comment]
not hikari, but AuthMe itself.
we need to find a better implementation of cached database.

**Comment by sgdc3** [comment]
can you try latest -dev build? ;)
