### ISSUE TITLE
handleDisconnection() called twice

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#253]
http://pastebin.com/ERDcstrE
Why is it?

**Comment by games647** [comment]
This is a server software issue.

**Comment by andris155** [comment]
Server: PaperSpigot latest
(use-native-transport=false)

**Comment by sgdc3** [comment]
Are you sure this is caused by authme?

**Comment by andris155** [comment]
I'm not.

**Comment by sgdc3** [comment]
Lol can you try on a local server? :)

**Comment by andris155** [comment]
[12:11:49] [Server thread/INFO]: andris155[/192.168.X.XXX:XXXXX] logged in with entity id 344 at ([world]-180.45008080923856, 4.0, 285.0911035022133)
[12:12:19] [Server thread/WARN]: handleDisconnection() called twice <-- Timed out kick

**Comment by Xephi** [comment]
http://www.spigotmc.org/threads/handledisconnect-called-twice.74171/

**Comment by sgdc3** [comment]
Not an authme issue, @andris155 can you close the issue? :)

**Comment by andris155** [comment]
yes

**Comment by sgdc3** [comment]
Thanks
