### ISSUE TITLE
Kit duplication bug - Name issue

### ISSUE THREAD

**Issue by Kritex** [Xephi/AuthMeReloaded#254]
"Jack" can login with "jack" with latest authme build. However there is one single consistent build which is #151 (Sep 21, 2015). Above this build, essentials kits can be used when you changed your name (Jack to jack). To sum up, any vip can duplicate his kits amount of he wants. This is a critical bug.

**Comment by xknat** [comment]
its common cuz offline server's dont use UUID and other plugins do use UUID. i got this problem on my server as well, its hard to prevent stealing and stuff. also when players join your account with a capital. they get creative as well...

**Comment by ljacqu** [comment]
I'll check this out within the next two weeks

**Comment by sgdc3** [comment]
We fixed this on sspigot 1.8.5 and lower
Due to some strange reasons it doesn't work since 1.8.7

**Comment by Xephi** [comment]
Is it fixed ?

**Comment by sgdc3** [comment]
@Xephi Me and @DNx5 are unable to find the realname check. Where is it?

**Comment by Kritex** [comment]
I have tried, it wasn't fixed yet

**Comment by sgdc3** [comment]
@Kritex Try latest dev build ;)

**Comment by Kritex** [comment]
It doesn't work in 1.8.7 spigot my dear friend.

**Comment by ljacqu** [comment]
this is my plan for this evening

**Comment by ljacqu** [comment]
@Kritex
I just tried with the latest build with both sqlite and mysql. If I register a user and try to join with a different uppercase / lowercase combination I may not join. Are you using another database type?

It might be possible that we had a bug where we didn't properly save the names as all lowercase. If you look at your database you should see a "realname" column with the usernames in all lowercase.

**Comment by Kritex** [comment]
I've tried latest build, it still gives same problem. The thing you don't understand is that player register with "John" but later on he can join with "john". Both of them cannot join in same time. However he can change his nickname and join to server. Only build 151 provides this option.

**Comment by sgdc3** [comment]
Nope, it should work! Try build number 536

**Comment by ljacqu** [comment]
What database type are you using?
Can you look at the db?, is there anywhere a 'realname' column with all lowercase usernames (if any names are not lowercase, that's a problem).

To make sure we're on the same page – the user 'john' can then really _log in_ as 'John', right?

@sgdc3 Is there maybe a setting for this check the user may have disabled? (On phone, so difficult to check for myself)

**Comment by sgdc3** [comment]
@Kritex Can you post your config.yml file?

**Comment by Kritex** [comment]
I am using default config. You can try on my test server: 5.62.126.44:11000
Its spigot 1.8.7

**Comment by sgdc3** [comment]
Can you try with 1.8.8?

**Comment by sgdc3** [comment]
Delete the config and let the plugin regenerate it.

**Comment by Kritex** [comment]
Now its 1.8.8 server, and still gives same error.

**Comment by ljacqu** [comment]
Unassigning myself since my questions aren't being answered

**Comment by sgdc3** [comment]
He uses SQlite

**Comment by Kritex** [comment]
@ljacqu sorry i forgot to answer. Its sqlite and it saves in lowercase in database
