### ISSUE TITLE
Login command issue

### ISSUE THREAD

**Issue by VladStarr** [Xephi/AuthMeReloaded#255]
Latest dev build. Spigot 1.8.8

When trying to login with /l password, plugin tells
```
Failed to paste AuthMeReloaded command!
/login password
```
But with /login password everything's good.

Please fix :)

**Comment by Xephi** [comment]
Fixed :)

**Comment by timvisee** [comment]
Good it has been fixed!

@Xephi Can you link me the commit that fixed this issue. So I can check whether my command system has a problem in it or not ^^.

Tim Visée
