### ISSUE TITLE
"ForceSpawnOnTheseWorlds" feature Broken

### ISSUE THREAD

**Issue by MithrandirCraft** [Xephi/AuthMeReloaded#256]
I am unable to set a specific world where players should get teleported to Authme's spawn after relogging.

Relevant config details:

ForceSpawnLocOnJoinEnabled: true    #This configuration seems to be necesarily set to true for "ForceSpawnOnTheseWorlds" function to work, right?

"ForceSpawnOnTheseWorlds" configuration:
http://hastebin.com/tuficiqunu.md

spawnPriority: authme,essentials,multiverse,default

The world where I want players to be dragged to spawn when they log out is called "PVP-EVENT" The fact that this name contains a "-" makes me think it may be interpreting "PVP" as one world, and "EVENT" as another, therefore messing up the whole configuration. But this could still be a bug.

----------------------------------------------------------

Current authme version: 5.1 - SNAPSHOT (One of the latest devs)
Current Minecraft-Spigot version: 1.8.8

----------------------------------------------------------
Original Bukkit Ticket (Outdated but commented on): 
http://dev.bukkit.org/bukkit-plugins/authme-reloaded/tickets/957-forcing-spawn-on-login-in-specific-world/

**Comment by Xephi** [comment]
What if you surround your world name with single quotes?

**Comment by MithrandirCraft** [comment]
ForceSpawnOnTheseWorlds:
    - 'PVP-EVENT'

This has never worked either. But I am now trying this with a very recent dev build. (I doubt there will be any diference)

**Comment by MithrandirCraft** [comment]
Yeah, it's just reseting that config to PVP-EVENT (quoteless). So it doesn't work.

**Comment by sgdc3** [comment]
@MithrandirCraft Hello, could you test it now? ;)

**Comment by MithrandirCraft** [comment]
Oh yeah, I really hope this is fixed, I want this feature so much :D will test in 2h

**Comment by MithrandirCraft** [comment]
Hi, I noticed there was a release on bukkit, so I used that one.
Is this well configured?: 

        ForceSpawnOnTheseWorlds: 
        - 'PVP-EVENT'

Still not working aparently.
Keep in mind, PVP-EVENT is the name of the world where I want players sent to the spawn.

**Comment by MithrandirCraft** [comment]
I also tried it quoteless.
My camera angle coordinates seem to reset when I log back in... did this happen before? Not that it's a major issue...

**Comment by NoChanceSD** [comment]
They are sent to spawn on login, not on logout. I'm pretty sure it works btw, i created a world with that exact name when i tested.

**Comment by sgdc3** [comment]
@MithrandirCraft

**Comment by MithrandirCraft** [comment]
@NoChanceSD 
@sgdc3 

Sure. On login, that's when I expect players to be sent to the corresponding world spawn coordinates if they logged out on "PVP-EVENT"

But I'm not getting teleported: https://youtu.be/XzMhRyKs6ns

I'll try this out on a localhost Spigot server. I will do further testing... however I'm pretty convinced it's not going to work.

**Comment by MithrandirCraft** [comment]
@lijacqu @sgdc3

This issue is solved. A config entry was missing from my config.yml

        ForceSpawnLocOnJoin: 
            # If enabled, every player will be teleported to the world spawnpoint
            # after successful authentication.
            # The quit location of the player will be overwritten.
            # This is different from "teleportUnAuthedToSpawn" that teleport player
            # back to his quit location after the authentication.
            enabled: true
            # WorldNames where we need to force the spawn location
            # Case-sensitive!
            worlds: 
            - 'PVP-EVENT'

Enabled was not present, and therefore defaultly set to false. I appollogize for the mistake, allthough there wasn't such option in the first place.

**Comment by sgdc3** [comment]
@MithrandirCraft That setting exist only since Beta3 ;)
