### ISSUE TITLE
"ProtectInventoryBeforeLogIn" feature Broken

### ISSUE THREAD

**Issue by MithrandirCraft** [Xephi/AuthMeReloaded#257]
I disabled the "ProtectInventoryBeforeLogIn" by setting it to false some time ago, in order to avoid an issue which wiped inventories (I was told this issue was fixed, so I set it back to true to give it a chance again.)

But somehow, when I re-activated "ProtectInventoryBeforeLogIn: true", the protective inventory did not not re-appear, instead you can see my inventory normally while loged out, as with it being set to false.

Not that it matters much, because I can at least still give initial noob kits without any issues or danger with the kits being swallowed by the protective inventory. 

But I would prefer the starter kits to be recieved without any issues, while using the protective inventory which is nicer than seeing other offline player's inventories.

----------------------------------------------------------

Current authme version: 5.1 - SNAPSHOT (One of the latest devs)
Current Minecraft-Spigot version: 1.8.8

----------------------------------------------------------

**Comment by sgdc3** [comment]
You need protocollib to enable the new safe inventory protection ^_^
Check your server log, you will notice a warning when authme is loaded.

**Comment by MithrandirCraft** [comment]
@sgdc3 I'm already using ProtocolLib v3.6.4

**Comment by sgdc3** [comment]
Very strange...

**Comment by MithrandirCraft** [comment]
It seems like this issue may only be affecting certain player names, for example, my own.

It still affects my playername even if I'm not OP, so there may be other affected names.

**Comment by games647** [comment]
Do you tried to log out by command?

**Comment by MithrandirCraft** [comment]
Yes. Result with my main account is the same, my inventory is always visible.

**Comment by games647** [comment]
Could you try to rejoin?

**Comment by MithrandirCraft** [comment]
Yeah, the result is the same. (I'm assuming you mean leaving the server & or closing the client. Result is always the same.)

**Comment by DNx5** [comment]
it should be fixed now, using /logout command will hide the inventory.

**Comment by sgdc3** [comment]
@MithrandirCraft

**Comment by MithrandirCraft** [comment]
Confirmed, this is fixed.
