### ISSUE TITLE
Per World Inventory plugin compatibility (Inventories get messed up with Authme + PWI)

### ISSUE THREAD

**Issue by MithrandirCraft** [Xephi/AuthMeReloaded#258]
Here's a detailed recording explaining some inventory issues which are being caused due to Authme + PerWorldInventory plugins compatibility:

http://youtu.be/U9N3rRsMy38 (On my server, example.)

Issue conditions (For reproducing):
- Having Authme + PWI on a blank Spigot server
- Authme config: "teleportUnAuthedToSpawn: true"
- Set up two worlds with separate PWI Inventory groups. (In order to separate their inventories)
- Set Authme's login spawn on one of these two worlds.

Issue reproduction: 
1. Give yourself some items on the world where you didn't set the authme spawn where players will get teleported on login.
2. Log out from that same world.
3. Log back in: You are now on the other world (because it's where you log in due to the Authme spawn being there) (And this is when your inventory from the original world gets messed up), but once you log in you will be teleported to the world where you logged out, without your inventory. Your inventory from this world will have been transfered to the Authme spawn world (Where, if you had some other inventory, it will have been replaced).

In my case, I have three worlds: Factions, Events, and Survival. Factions and Events share the same inventory, and the Authme spawn is in Events, so when someone logs out from Survival, their inventory moves to the Factions inventory group, which is also the Events group/world where the Authme Spawn is located.
Some players can somehow abuse this issue for duplicating items.
I am still unsure exactly as to why this happens, but I can understand one of the two plugins, either PWI or Authme is attributing the wrong inventory on the wrong world, the inventory should be attributed once the player is in the right world.

This causes what I call "An inventory messup".

----------------------------------------------------------

Current authme version: 5.1 - SNAPSHOT (One of the latest devs)
Current Minecraft-Spigot version: 1.8.8

----------------------------------------------------------
Original Bukkit Ticket (Outdated but commented on): 
http://dev.bukkit.org/bukkit-plugins/authme-reloaded/tickets/970-inventory-messup/

**Comment by Platinteufel** [comment]
Could you give yourself the permission authme.bypassforcesurvival and test it again? I've also noticed an inventory issue that doesn't happen with this permission.

**Comment by MithrandirCraft** [comment]
@Platinteufel I honestly mean no disrespect, but this sounds like a wacky solution...

Are you sure you had the same issue as me? What does this permission do exactly?

**Comment by MithrandirCraft** [comment]
Tried the "authme.bypassforcesurvival" permission. It seems like it decreased the odds of this issue happening, but I still got two reports in the last three days indicating the exact same symptoms I describe on this ticket (Players got their Survival inventories overwritten to my Factions world.)

I am unable to reproduce the issue with a normal account, but other players seem to be having these issues still. I have no idea why or when they are still experiencing this horrible bug.

**Comment by MithrandirCraft** [comment]
I think this issue may be fixed. 
I'm closing the ticket.
If the issue re-emerges I will re-open it.
