### ISSUE TITLE
Make datasource operations run asynchronously.

### ISSUE THREAD

**Issue by IfarPL** [Xephi/AuthMeReloaded#26]
All current database/file operations are run in main server thread. On big servers authme make a lot of lags. Solution of this problem might be to run the datasource operation in another thread.

**Comment by Xephi** [comment]
Can you give me some examples in code ?

**Comment by IfarPL** [comment]
1. You should use AsyncPlayerPreLoginEvent instead PlayerLoginEvent
2. I think the best option is: load data to cache in PlayerJoinEvent and save to datasource in PlayerQuitEvent. All operations between these events are run on cache. Unfortunately this requires many changes in code.
Code example: http://pastebin.com/Y1yF7afG

**Comment by Xephi** [comment]
AsyncPlayerPreLoginEvent isn't called in an offline server and DataSource operations are already in an another thread :O

**Comment by IfarPL** [comment]
http://www.spigotmc.org/threads/call-asyncplayerpreloginevent-when-online-mode-false.2690/

I add a debug: System.out.println(Thread.currentThread().getName()); in MySQLThread.getAuth() method and output is: "Server thread", that mean is run in main server thread

**Comment by Xephi** [comment]
Code was based on CraftBukkit not Spigot

And i will check that, it's anormal :')
