### ISSUE TITLE
Broken Email Recovery

### ISSUE THREAD

**Issue by MithrandirCraft** [Xephi/AuthMeReloaded#260]
This system is more than often broken. Still broken on Authme 5.1 SNAPSHOT (One of the latest dev builds)

Configuration details:
http://hastebin.com/iyucuzebij.xml

In Authme 3.5. The email registration commands would always give an internal error (This was fixed in 5.0). In authme 5.0 & 5.1, the password is changed, but the e-mail is never recieved for some reason. (I've tried this my self without success, and I've also recieved reports from players.)

----------------------------------------------------------

Current authme version: 5.1 - SNAPSHOT (One of the latest devs)
Current Minecraft-Spigot version: 1.8.8

----------------------------------------------------------
Original Bukkit Ticket (Outdated but commented on): 
http://dev.bukkit.org/bukkit-plugins/authme-reloaded/tickets/973-broken-e-mail-recovery/

**Comment by kxjhwbb** [comment]
I use authme 3.5, send email success.
but use AuthMe-5.0-beta3.jar，seems lost something..
com/sun/mail/util/MailLogger，I can see this in 3.5 and 5.0-beta2，5.0-beta3 delete at all...
and only can send email in 3.5，  can't send in 5.0 beta2， show error in beta3！

**Comment by sgdc3** [comment]
Try latest dev build: http://ci.xephi.fr/job/AuthMeReloaded-Dev/

**Comment by sgdc3** [comment]
@MithrandirCraft @kxjhwbb

**Comment by Xephi** [comment]
Hi ! You can use latest build with new email system

By the way, google use a restriction to application that can access to your account
To allow external application to work, we need to set config like that into your gmail account settings:

<img width="1212" alt="screen-shot-2015-05-28-at-21 59 16" src="https://cloud.githubusercontent.com/assets/2137621/11080783/a2eefd58-8817-11e5-8433-bfe75175c583.png">

**Comment by Xephi** [comment]
i will add a way to connect via oauth2 also

**Comment by MithrandirCraft** [comment]
I'm currently recieving a generic missing permission message every time I try to use /email recover

The message still shows up even if I give myself the permission (which shouldn't be necesary, if I'm already OP.)

Therefore, I cannot test email recovery due to this impediment.

**Comment by kxjhwbb** [comment]
@sgdc3 HI, sorry i'm late,  I have test it, no error but show dont have Permission , I have gave all permission to the test player :)

**Comment by Xephi** [comment]
have you try to use authme.email.recover permission ?

**Comment by kxjhwbb** [comment]
no.. I just add *.* and set the player op last time..
I test authme.email.recover tonight , still can't work , nothing show in console but can see "an unexcepted error occurrrd" in client, something wrong been catch but not show ?
by the way , when I was testing, a maxinum number of reg print, so I change the  config "maxRegPerEmail" + "maxRegPerIp" and type /authme reload, but it does't work until i type /reload  :P

**Comment by MithrandirCraft** [comment]
@Xephi I already tried that permission. Result is the same.

**Comment by MithrandirCraft** [comment]
Hi. I tried the latest version which should fix the permission issues.

I finally managed to send a recovery email, but I never recieve it. Did anyone else try?

**Comment by sgdc3** [comment]
Retry now ;)

**Comment by MithrandirCraft** [comment]
Still not fixed.

**Comment by MithrandirCraft** [comment]
Hi!

Testing with Authme dev build 557 as requested by @Xephi: 

1. I sent an email recovery request, but I didn't recieve any email.
2. I've reset the password to how it was, after having sent the recovery email to limbo.
3. Entering my reset password doesn't even return "invalid password"
it just keeps asking me to log in. This looks like a new issue in it self, and it never happened before.

**Comment by Xephi** [comment]
Can you test with the latest devbuild ?

**Comment by MithrandirCraft** [comment]
I think I already did, with no success. I'm going to keep testing ASAP.

In any case, this new configuration is weird. I don't know if its because it's still in development, but having a message edited from an html file, and the rest of email configurations on the main config is just strange...

I could perfectly have something badly configured with all these changes. You already saw my configs, so if you didn't spot anything wrong... I'll keep testing, maybe the email I used two years ago is a bit abandoned or someting xD

**Comment by sgdc3** [comment]
Can you post your config? I'll try to clean it up ;)

**Comment by Xephi** [comment]
i can't reproduce any bug with gmail account for myself, actually it works well with port 465 ad 587 :/

**Comment by MithrandirCraft** [comment]
Thank you @sgdc3 :)

.html file: http://hastebin.com/ojagurakec.xml
Authme regular config: http://hastebin.com/uqujuxarib.vbs

**Comment by sgdc3** [comment]
email: http://hastebin.com/ayopinuqax.xml

**Comment by sgdc3** [comment]
config (enabled verygames ip check, it should have been fixed) http://hastebin.com/udemoconez.sm

**Comment by sgdc3** [comment]
check also if spawn loc works with this config

**Comment by MithrandirCraft** [comment]
I provably won't be using that feature, as I am not sure I have the correct service for the IP checks to work.

**Comment by sgdc3** [comment]
Which service are you using?

**Comment by Xephi** [comment]
@MithrandirCraft if your server don't use ipClean from Verygames, i don't think you need it :) it's useless for you ;)

For the email feature, test like that : set smtp to : smtp.gmail.com
Use your gmail address which you have enable the low security application system on google config
Set the port to 465 
Cross fingers :')

**Comment by sgdc3** [comment]
@Xephi we should rename the verygames option in the configuration

**Comment by MithrandirCraft** [comment]
I noticed my email was blocking Authme from using it, because it considers it a "Less secure application".

So I allowed less secure applications to connect to my gmail, but I still don't recieve any email for recovery.

Does anyone want to try it?: sv1.mithrandircraft.es

**Comment by Xephi** [comment]
Finally Done !

That was a problem with server blacklisted in the smtp server
to solve it, we use our own smtp server from the domain name provider ;)
