### ISSUE TITLE
Session expire always after restart

### ISSUE THREAD

**Issue by ludgart** [Xephi/AuthMeReloaded#262]
Hey,

I tested the new version of Authme and i have A problem with the session save.
My settings are: expire: 9999 (work in the old version < 5.0)
On every restart all players need to login again, i tryed the unlimted session setting, but i dont work.
Is this a bug or my fault?

**Comment by sgdc3** [comment]
Are you using mysql or sqlite?

**Comment by ludgart** [comment]
I use MySQL.

**Comment by Xephi** [comment]
Do you use Cache ?

**Comment by ludgart** [comment]
No i disabled the mysq cache system.

**Comment by Xephi** [comment]
Oh , didn't understood, our code do it like that : 
If server is reloading (not restarting, catch if player are always logged in when plugin is re-enabled), method setUnlogged are not called, but if you stop your server (players are all kicked and plugin start before player are online), we set all logged players to unlogged, it's a security check if database is not reachable too quickly before player logs in
It's not an issue here :/

**Comment by ludgart** [comment]
It would be helpful if you can add a secruity configuration option, because the old system work fine. 
I hate it to login every day.. And im not alone... 

Thanks!

**Comment by sgdc3** [comment]
It's useless with dynamic ips...

**Comment by Xephi** [comment]
Nah sorry mate, it will open a large backdoor :O Session is a strange stuff and we can't enable such a feature without checking veracity of a player :/

**Comment by ludgart** [comment]
Why are u added this feature in the old version? 
The new version of authme is complete Bugy for big server, he can't handle many connections.

**Comment by sgdc3** [comment]
You should check latest dev version from our buildserver ci.xephi.fr
