### ISSUE TITLE
Authme > chests

### ISSUE THREAD

**Issue by MrFiliper** [Xephi/AuthMeReloaded#265]
I have i problem. If player join to server, authme display this error http://pastebin.com/SZbAhGgb and all chests in cca radius 32 now empty. Please help. Full log is here: http://pastebin.com/VXpSF1Rx

**Comment by DNx5** [comment]
@MrFiliper try with current version.
http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by sgdc3** [comment]
I'm sure this was fixed by @Xephi some time ago

**Comment by Xephi** [comment]
Already Fixed
