### ISSUE TITLE
Huge Lags

### ISSUE THREAD

**Issue by mariolars** [Xephi/AuthMeReloaded#267]
http://aikar.co/timings.php?url=13228044

**Comment by mariolars** [comment]
i can't use any never build since you implemented hikari. I use java8 with PaparSpigot 1.7.10.

**Comment by sgdc3** [comment]
TODO: fix the onPlayerMove event lag issue

**Comment by mariolars** [comment]
i managed to fix moveevent by myself but onJoinEvent server is lagging as well : http://timings.aikar.co/?url=13247204

**Comment by Cazmon** [comment]
http://timings.aikar.co/?url=13258010

**Comment by mariolars** [comment]
@Cazmon you are using old version

**Comment by mariolars** [comment]
PlayerJoinEvent lags only when there is disabled "caching". When i enable server works perfectly fine but authme doesnt send message to player to log in.

**Comment by sgdc3** [comment]
So when cache is disabled the notification sistem is broken, right?

**Comment by mariolars** [comment]
Yep

**Comment by Xephi** [comment]
TODO: Fix notification for cache enable

**Comment by xknat** [comment]
yea that would help, thanks @Xephi

**Comment by sgdc3** [comment]
Can you try with cache enabled and using latest -dev build?

**Comment by mariolars** [comment]
No problem. But about any effects i will be able to post smth' around 05.00 PM GMT+1.

**Comment by sgdc3** [comment]
@mariolars Any update? ;)

**Comment by mariolars** [comment]
oh.. sorry. The first thing is that during logging mysql function "isLogged" lags so badly i edited a little bit code pasting there only return false so players could at least join to server . You shoudl really check it. Second i noticed that with cache enabled makes new  registered players are not added to database. I think it is because of not properly closed server but i can't really close it cus of authme that is stacked with strange message( i dont really remember hwo it looked, sorry)The only way to close it is kill process.. Cache disabled saves players but they cant really log if server after fresh restart saw more  than 10 ppl. I had to write my own auth plugin but ofc i can still test new builds on less populated hub.

**Comment by mariolars** [comment]
I think also that u should stop using " * " when you are selecting things in mysql and "ask" only for specific column that you are intrested but it's only my opinion and maybe i'm wrong.

**Comment by DNx5** [comment]
I'm start working on it :D performance improvement.
can you try latest dev build? don't forget to backup.

**Comment by sgdc3** [comment]
no more response

**Comment by sgdc3** [comment]
@MithrandirCraft can prove that the issue is fixed
