### ISSUE TITLE
Username case sensitive

### ISSUE THREAD

**Issue by LudnicaKiller** [Xephi/AuthMeReloaded#270]
Hi,
I have a big problem, so on my Hub server if someone register with username etc. Jason and gets banned, he can just get back on the server with username jason and he can login with old password and have old ranks on every server on my network. 
I'm using:
authme: AuthMe - 5.0-beta3
spigot: http://prntscr.com/93ku6l
config.yml: http://pastebin.com/UcNY7nqf

Thanks in advance.. :)

**Comment by sgdc3** [comment]
Try our latest dev build avariable at ci.xephi.fr ;)

**Comment by LudnicaKiller** [comment]
http://prntscr.com/93qb60 this one?

**Comment by LudnicaKiller** [comment]
I have downloaded it but now my,
TPS: http://prntscr.com/93qf5m
Timings: http://timings.aikar.co/?url=13312050
And I have turned caching to false but it still creates files and folders in cache
config.yml: http://pastebin.com/mver0kg5

**Comment by LudnicaKiller** [comment]
You're versions of AuthMe: "AuthMe - 5.0-beta3" and "AuthMeReloaded-Dev #342" are lagging so much. On 5.0-beta3 when you set caching to false it still creates folders of players. Dev #342 is not creating folders into cache folder when you set false in config but still tps goes below 8.
Now I have returned to my old AuthMe 3.4 and I have 20TPS and no lagg. Please fix all that things..

**Comment by DNx5** [comment]
@LudnicaKiller 
cache in config.yml is for database things, and the files in the cache folder is used to store player's data and will removed when players logged in.
are you still getting lag with cache set to true?

**Comment by LudnicaKiller** [comment]
I'm getting lag with cache set to true and set to false..

**Comment by sgdc3** [comment]
Can you post your configuration and try latest authmereloaded-dev build

**Comment by sgdc3** [comment]
? thanks ;)
