### ISSUE TITLE
[AuthMe] YOU'RE USING THE SQLITE DATABASE WITH 5079+ ....... How to fix?

### ISSUE THREAD

**Issue by NickFirenzo** [Xephi/AuthMeReloaded#271]
In console when start server, when load all plugins say
[AuthMe] YOU'RE USING THE SQLITE DATABASE WITH 5079+ ACCOUNTS, FOR BETTER PERFORMANCES, PLEASE UPGRADE TO MYSQL!!

How to fix it? And I want to ask. I must change to MySQL?

**Comment by Xephi** [comment]
You can just ignore it if you don't get any performance issue, sqlite database is better on SSD disk than HDD one, cause it's just a file that is getting accessed, but mySQL allow a multiple connection read/write at the same time, neither sqlite :/

**Comment by NickFirenzo** [comment]
Ok thanks :)
