### ISSUE TITLE
Verygames IPCheck breaks the config

### ISSUE THREAD

**Issue by MithrandirCraft** [Xephi/AuthMeReloaded#273]
There's something going on with the "VeryGames: enableIpCheck: true" feature.
Every time I set it to true, it makes the plugin go mad, login stops working and weird things happen.
This started happening this afternoon after the 6PM restart, I had no idea what was causing it untill I started reconfiuring and restarting the server one feature at a time.
I think this may have something to do with my hosting company

-------------------------------------
Current authme version: 5.1 - SNAPSHOT (One of the latest devs)
Current Minecraft-Spigot version: 1.8.8

**Comment by NickFirenzo** [comment]
Yes, all people who have authme and EnableIpCheck: true, all having a problem.
"VeryGames" maybe is under mainstance.. Just set to false and problem will be solved.

**Comment by MithrandirCraft** [comment]
I will comunicate this to VeryGames... every time something happens on their side authme will start doing irregularities :S

**Comment by Xephi** [comment]
This options is needed only if you use VeryGames IPclean system
