### ISSUE TITLE
"allowMovement: false" teleports players to Authme Spawn when not configured to do so

### ISSUE THREAD

**Issue by MithrandirCraft** [Xephi/AuthMeReloaded#274]
With the following config:
    allowMovement: false   

When Players are in login mode, if they move the camera or try to move, they get teleported to the authme spawn (which I use as a login area), allthough this shouldn't be happening, because "teleportUnAuthedToSpawn: false"
Some players even reported being randomly teleported to the authme spawn (Unused due to inventory bugs when "true") and also being bounced from one world to another during login, up to 6 times (Yeah, I know this sounds ridiculous but I do trust what my moderators tell me xD)

This means that if a player moves the camera too much, his inventory gets teleported to another world, because there's the PWI glitch that makes player inventories get messed up when a player gets teleported to another world during login:
https://github.com/Xephi/AuthMeReloaded/issues/258
The only way to aviod this is for the players to know that they shouldn't move the camera :S Apparently making the plugin rectify the view too much makes players get teleported to the authme spawn for some reason.

I had to set these configs in order to evade the issue:
   
    allowMovement: true
    allowedMovementRadius: 0

Sum that up to the fact that I'm already using:

    teleportUnAuthedToSpawn: false

In order to evade Inventory issues... the result is that I'm having to force players to login in some really shitty ways xD

--------------------------------
Current authme version: 5.1 - SNAPSHOT (One of the latest devs)
Current Minecraft-Spigot version: 1.8.8

**Comment by sgdc3** [comment]
Fixed
