### ISSUE TITLE
Remove Speed feature broken

### ISSUE THREAD

**Issue by MithrandirCraft** [Xephi/AuthMeReloaded#275]
The following config doesn't work:

    removeSpeed: true

Players are still capable of moving, at least if the allowMovement feature is set to true (My case), but I didn't try setting that to false. I guess the issue would still persist.

------------------------
Current authme version: 5.1 - SNAPSHOT (One of the latest devs)
Current Minecraft-Spigot version: 1.8.8

**Comment by sgdc3** [comment]
i know why, i will fix this tomorrow

**Comment by MithrandirCraft** [comment]
Great, considering I've had to configure some very special login conditions (In order to avoid some other issues), this will help a lot in avoiding players from walking around freely before login :S

**Comment by MithrandirCraft** [comment]
Still not fixed on dev #419

**Comment by sgdc3** [comment]
You misunderstood how remove speed works :) If allowMovements is set to true the removeSpeed option will be ignored.

**Comment by MithrandirCraft** [comment]
Oh yeah, sorry, I didn't pay attention xD that was stupid :)
