### ISSUE TITLE
"noTeleport" feature broken

### ISSUE THREAD

**Issue by MithrandirCraft** [Xephi/AuthMeReloaded#276]
Refering to following config:
    noTeleport: true

Is it posible that this feature is broken? According to the (first config load) description, setting this to true should stop any authme teleportation events (All teleportations related to Authme I asume?).

The fact is, that turning this feature "true" has no effect in allowing players to move freely when unlogged. So unless the unlogged teleportation events are something separate, or I just don't understand the function of this feature, I would say it's broken, because Authme still teleports people around when necesary (noTeleport: true should override and prevent all teleportations.)

---------------------------
Current authme version: 5.1 - SNAPSHOT (One of the latest devs)
Current Minecraft-Spigot version: 1.8.8

**Comment by sgdc3** [comment]
Done
