### ISSUE TITLE
PvPManager (Premium Spigot Resource) NPC's compatibility

### ISSUE THREAD

**Issue by MithrandirCraft** [Xephi/AuthMeReloaded#277]
Basically compatibility with any PvP logger plugin which spawns NPC's

PvPManager can spawn NPC's when people run away from battle, if the NPC's are killed they drop all the stuff from the coward player.

But Authme is blocking these NPC's from being killed.

----------------------------
Current authme version: 5.1 - SNAPSHOT (One of the latest devs)
Current Minecraft-Spigot version: 1.8.8

**Comment by games647** [comment]
Does this plugin add any metadata to the player in order to detect the NPC?

**Comment by sgdc3** [comment]
Apparently not @games647 :/
We probably should contact the author...

**Comment by games647** [comment]
@MithrandirCraft are the NPCs generated by Citizens or a similar plugin?

**Comment by MithrandirCraft** [comment]
No, directly generated by PVPManager

**Comment by sgdc3** [comment]
Fixed :)

**Comment by MithrandirCraft** [comment]
Confirmed.
