### ISSUE TITLE
Tick lag at Spigot 1.8

### ISSUE THREAD

**Issue by JunkyBulgaria** [Xephi/AuthMeReloaded#28]
http://i.imgur.com/Y9U3qRR.png here's the timings.
http://i.imgur.com/WTbY8f7.png

CPU increases at ~300% (CentOS) [which means all 8cores set are used at 100%]
Probably #26 is releated. (Using MySQL connections instead of SQLite)

PC Specs: 
Intel Xeon E7-8820 (8cores for the server, rest are free)
128gb DDR3-ECC 1600MHz ram (32 allocated to the server)
SSD space.

**Comment by orkun1675** [comment]
I also have this lag problem with 3.5, but not with 3.4.

**Comment by JunkyBulgaria** [comment]
@Xephi any ideas?

**Comment by JunkyBulgaria** [comment]
http://i.imgur.com/d29VtSA.png

Seems to be getting out of control at ~200online players with MySQL and 15k+ registered players.

**Comment by Xephi** [comment]
I'm checking what's the problem, AuthMe 3.4 seems to be more stable at the moment :/

**Comment by Xephi** [comment]
Have you enable cache in your config.yml ?

**Comment by JunkyBulgaria** [comment]
Yeah, it is.

**Comment by Xephi** [comment]
Ok i think it's fixed for now, can you test?

**Comment by Xephi** [comment]
http://ci.xephi.fr

**Comment by JunkyBulgaria** [comment]
Yes, it is.
