### ISSUE TITLE
[Dev] Messages: Reload upon language check doesn't take effect

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#280]
@DNx5 With the change in commit [d7ae2a9](https://github.com/AuthMe-Team/AuthMeReloaded/commit/d7ae2a9) the method `reloadMessages()` creates a new instance it adds to `singleton` but this variable is no longer referenced inside the method `retrieve`. 

Probably reloading upon language change is smart in case someone changes the config and reloads AuthMe, or do we lose reference to any Message instances then? Please advise.

Edit: Actually I believe the constructor could be made private (yes, it's used in AuthMe in `onEnable()` but `getInstance()` automatically instantiates the instance anyway) and then we could always call commands through the singleton field.

**Comment by DNx5** [comment]
should it be singleton or POJO ?
i'm trying to change it, that's why I set all classes to use ``` getMessages() ``` method in plugin instance.

**Comment by ljacqu** [comment]
Personally I think singleton:
- No use case of having two separate Messages instances
- Allows the reloading behavior upon language change

If tests are failing after changes I can help with that ;)

**Comment by DNx5** [comment]
Singleton should be final and the instance shouldn't be changed.
Also, we have getter and setter for messages field in AuthMe class.
then we can reload the languange change by using ``` plugin.setMessages(messagesObject); ```

**Comment by ljacqu** [comment]
Note: for testability `final` fields are counter-productive – they cannot be mocked. Ideally use the `Wrapper` class to retrieve the Messages instance. I'll create a general Wiki page about testing over the weekend

**Comment by ljacqu** [comment]
I will do this today and will ask DNx5 to verify my changes

**Comment by ljacqu** [comment]
Changed Messages to be able to reload upon language setting change – the only problem is that the language setting doesn't seem to change even after `/authme reload`. Not related to this story, though, so closing.
