### ISSUE TITLE
Bukkit Plugins page: wrong link to plugin.yml

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#281]
@Xephi The link to plugins.yml on http://dev.bukkit.org/bukkit-plugins/authme-reloaded/pages/permissions/ leads to a broken link. You probably want either

https://raw.githubusercontent.com/Xephi/AuthMeReloaded/master/src/main/resources/plugin.yml
or https://raw.githubusercontent.com/AuthMe-Team/AuthMeReloaded/master/src/main/resources/plugin.yml

**Comment by Xephi** [comment]
Thanks
