### ISSUE TITLE
[AuthMe] How to configure first letter of the password to be with CAPS for secure

### ISSUE THREAD

**Issue by NickFirenzo** [Xephi/AuthMeReloaded#282]
How do I set up so that the first letter of your password when you sign up to be with CAPS or a greater protection?

MUST USE FIRST LETTER WITH CAPS to register

**Comment by DNx5** [comment]
why?

**Comment by games647** [comment]
Isn't it better to require a mixed case password rather than just the first letter have to uppercase?

**Comment by sgdc3** [comment]
Yes I agree with games.

**Comment by Xephi** [comment]
Use a regexp anyway...

**Comment by Xephi** [comment]
e.g. : ^[A-Z][a-zA-Z0-9]+$

Xephi will match 
xephi will not
Xephi+ will match
Xephi@ will not
