### ISSUE TITLE
Bug with block clickable command

### ISSUE THREAD

**Issue by Toshka17** [Xephi/AuthMeReloaded#283]
I wanted to use authme 5.1-snapshot from your site jenkins. But I found it a bug, if a player is not authorized, it can use the commands through the sign. For example through the ins and telepostsigns serversigns. Please fix it. In version AuthMe - 5.0-beta3 everything works well.

**Comment by sgdc3** [comment]
Try now @Toshka17 ;)

**Comment by Toshka17** [comment]
Thanks! All works fine ;)

**Comment by sgdc3** [comment]
can you close the issue? ;) @Toshka17

**Comment by Toshka17** [comment]
hmhm .. now I have a new problem. when I try to log in, for me wrote that lacks permissions

**Comment by sgdc3** [comment]
:/ i'll fix that
In the meantime you can add permission to your default  group.

**Comment by sgdc3** [comment]
Can you create a new issje abou it? @Toshska17
