### ISSUE TITLE
Stops working permit authme.player.*

### ISSUE THREAD

**Issue by Toshka17** [Xephi/AuthMeReloaded#285]

**Comment by timvisee** [comment]
The latest AuthMe reloaded build don't offer the `authme.player.*` permission anymore. Every command has it's own permission node, except for the `...help` and `...version` command.

For example, the login command for players has the permission `authme.login`.

It's easy to find out what permission is required for a specific command. This can be done using the help command. For example, for the `/login` command, use `/login help login` to view help for this command. This help page that is popping up, shows what permission node is used for this command. It also shows whether you currently have permission for this command or not, along with some other things.
For the `/register` command, you can use `/register help register` and so on.
For the `/authme ...` commands, it's a little different. For example, if you would like to see what permission should be used for the `/authme reload` command. You can use `/authme help authme reload`, or simply `/authme help reload`. And for example, the `/authme forcelogin` permission can be shown using `/authme help forcelogin`.

I'd like to note, that you could also use a short syntax for various commands. For example, you can replace `help` with `h` or `?`. Some other command labels can be shortened too. So, `/authme ? rld` will show you the help page of the `/authme reload` command (with it's permission).
 
The documentation pages should be updated as soon as this version has been released!

Hope this helps,
Tim Visée

**Comment by sgdc3** [comment]
@timvisee we should add super nodes support anyway...

**Comment by sgdc3** [comment]
@timvisee

**Comment by ljacqu** [comment]
Implemented support for `authme.player.*` and `authme.admin.*`; it should be available in the next dev builds.

You can find the most recent list of permission nodes at https://github.com/AuthMe-Team/AuthMeReloaded/blob/master/src/tools/docs/permission_nodes.md (URL subject to change)

You can find our dev builds at http://ci.xephi.fr/job/AuthMeReloaded-Dev/ **though I would recommend waiting until the build is "blue" again.**

**Comment by ljacqu** [comment]
I'm going to assume that this has been solved. If this is not the case, kindly open another issue with a reference to this one.
