### ISSUE TITLE
Email recovery system not worked

### ISSUE THREAD

**Issue by Toshka17** [Xephi/AuthMeReloaded#286]
http://pastebin.com/ShXsLTr2

**Comment by sgdc3** [comment]
Plugin's version and build number?

**Comment by Toshka17** [comment]
AuthMeReloaded-Dev #443

**Comment by Toshka17** [comment]
Bump?

**Comment by sgdc3** [comment]
Yeah we had to fix some other bugs first ;) Now we can look at this.

**Comment by Xephi** [comment]
Is it for all email or just your smtp server didn't respond once ?

**Comment by Toshka17** [comment]
I tried to use different mailboxes (mail, yandex), the result is always the same.

Also, I tried to send the password for different mail (yandex, mail), but still the result is the same.
