### ISSUE TITLE
broken delayJoinMessage feature

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#291]
join message is shown both before and after the login

**Comment by Xephi** [comment]
On all spigot versions ?

**Comment by sgdc3** [comment]
@KingPyro is the author of the report
![265f768afc185bf8fa5e68a318a2be27bc2db45e](https://cloud.githubusercontent.com/assets/8779252/11595024/a30bbad0-9aad-11e5-9094-45b7b889cdee.png)

**Comment by Xephi** [comment]
was delayJoinLeaveMessages set as true ?

**Comment by sgdc3** [comment]
if it was false the message would not have appeared after the login.

**Comment by sgdc3** [comment]
The issue is how we remove the original message.

**Comment by Xephi** [comment]
https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/listener/AuthMePlayerListener.java#L179

**Comment by DNx5** [comment]
I've set the event priority to Lowest. 
I will see the result.

**Comment by kingpyro** [comment]
@DNx5  @sgdc3  Tested on build 185 on the dev server and now the result is that the vanilla message ( First one ) is still there but the one for after login is now not working. ( delayJoinLeaveMessage:True )
