### ISSUE TITLE
Norway country code support

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#292]
Norway's country code is "NO" so the yaml parser convert it to false

**Comment by Xephi** [comment]
use simple/double quotes to force parsing

**Comment by Xephi** [comment]
countries:
    - 'US'
    - 'NO'

**Comment by sgdc3** [comment]
yeah, i already told him but no answer atm

**Comment by sgdc3** [comment]
i'll add quotes by default

**Comment by Xephi** [comment]
http://yaml-online-parser.appspot.com/?yaml=++++countriesBlacklist%3A%0A++++-+US%0A++++-+NO%0A%0A++++countries%3A%0A++++-+US%0A++++-+%27NO%27&type=json
