### ISSUE TITLE
AuthMe 5.1 SNAPSHOT #182 + Chatcontrol Pro latest error

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#295]
http://pastebin.com/ExyDDzCi

**Comment by DNx5** [comment]
not chat control again :smile:

**Comment by sgdc3** [comment]
HE CAN'T USE OUR METHODS -_-

**Comment by sgdc3** [comment]
@DNx5 We should add a way to get it from our new API

**Comment by DNx5** [comment]
but our API class shouldn't named NewAPI

**Comment by Xephi** [comment]
Ahah I said to do not remove these methods :P

**Comment by DNx5** [comment]
@Xephi it's still there, in AuthMe class

**Comment by sgdc3** [comment]
@Xephi Which methods? :?

**Comment by Xephi** [comment]
I've send a message to ChatControl author, he will do the change quickly

Thanks for report anyway
