### ISSUE TITLE
Session login between servers is broken. #182

### ISSUE THREAD

**Issue by Done84** [Xephi/AuthMeReloaded#297]
Session login between servers is broken. It works in single server but when switching servers using the same database it doesent resume session.

**Comment by DNx5** [comment]
is bungeecord hook enabled?
```
Hooks:
  bungeecord: true
```

**Comment by Xephi** [comment]
Can you please send us your config.yml ? (remove all password (db, email))

**Comment by Done84** [comment]
Yep.   bungeecord: true

Pastebin config:
http://pastebin.com/dLHmCNgY

**Comment by Xephi** [comment]
Can you please try with mysqlwebsite set to true ? it will force database to flush all queries

And come back to tell if it worked ;)

**Comment by Done84** [comment]
Sorry for the late response. It didnt make any diference, i also updated to the latest dev version and it also doesent work. Do i need to install the AuthMeBungeeBridge for it to work?

**Comment by sgdc3** [comment]
No, you can try with authmebridge's session reset feature: https://www.spigotmc.org/resources/authmebridge-for-bungeecord.574/

**Comment by DNx5** [comment]
try latest dev build, **don't forget to backup**
http://ci.xephi.fr/job/AuthMeReloaded-Dev/

**Comment by sgdc3** [comment]
@Done84

**Comment by d1One** [comment]
Yes. Its fixed int he latest #531 dev version. Thanks.

**Comment by sgdc3** [comment]
@Done84 Can you check this out? ;)

**Comment by Done84** [comment]
Yes. Its fine, for some reason i have 2 account on github.

**Comment by sgdc3** [comment]
Lol :P
