### ISSUE TITLE
Session Steal?

### ISSUE THREAD

**Issue by Platinteufel** [Xephi/AuthMeReloaded#302]
Hey,
a random player joined my server today and wanted some of my players to join his server (IP was sth. like e.grappl.io:...). My players told me that this IP directs to my server, just the same as you would join by my server-IP. But if they do this, the "man in the middle" will get their account-control. I'm not sure if he catches the password (it's usually encrypted?) or if he just steals the session, but it's quite important to stop that for my players safety. I don't use AuthMe-Sessions and I'm running the latest 5.1-devbuild.

**Comment by games647** [comment]
Does the fake server kicks the player or can they play normal as they are on your server?

If the players types there password on the fake server, the password will be visible to the fake instance. The minecraft chat isn't encrypted.

**Comment by Platinteufel** [comment]
It doesn't kick the player. You can play on my server as same as if you joined by my server-IP. I'm not sure how to prevent this.

**Comment by games647** [comment]
Maybe check the source ip.

**Comment by Platinteufel** [comment]
It's from grappl.io - "Grappl is a tool that lets you host virtually any type of server anywhere, with no port forwarding."
But the players have a different IP if they join by fakeserver.

**Comment by sgdc3** [comment]
Players from the fake server have the same ip, right?

**Comment by Platinteufel** [comment]
I think all players from the fake server have the same IP, but I'm not sure about that.
They don't have their own IP because they will be redirected to my server.

**Comment by Platinteufel** [comment]
Looked again in my server-log. All players that join by the fake-IP have the same IP: 
The IP of the person that is running the fakeserver which redirects to my server.

**Comment by Xephi** [comment]
He can maybe listen packet send from Minecraft client before they're send to server, by the way, the only one way to handle that is to prevent people for join the game with an another server ip than you give them, 
You're server ip is still unique, and maybe you have a domain name associated to it, by the way, just tell people to do not join your server with an another ip,

Best of luck for you, but i'm sorry, we can't help you more :/

**Comment by Platinteufel** [comment]
Okay, thank you tho, I'll try to find a solution. :)
