### ISSUE TITLE
[Dev] Minor - change CommandInitializer to only use the builder

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#307]
In `CommandInitializer`, replace all initializations of `CommandDescription` to use the builder and remove the deprecated public constructor.

**Comment by Xephi** [comment]
Done

**Comment by ljacqu** [comment]
Hello @Xephi, unfortunately this cannot be closed yet. As mentioned on Gitter, part of this issue is to remove the deprecated constructor after, and it's also mentioned in the description of the issue. However, it's still in the code.
