### ISSUE TITLE
[Dev] SQL - Security: use prepared statements and validate SQL settings

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#308]
Maybe a story for @DNx5?

1) Ensure that we only use prepared statements for all SQL statements we run with parameters.

<del>2) Validate the settings for the column and table names (e.g. `mySQLColumnId`) to be also sure that they won't break the SQL statements (probably a regexp such as `[a-zA-Z0-9_-]+` or similar)</del> Skipped for this issue

3) Once this is done, we can remove the checks for SQL keywords in the password. For instance, this is done in `ChangePasswordCommand` and will no longer be necessary:

```java
if (playerPassLowerCase.contains("delete") || playerPassLowerCase.contains("where")
            || playerPassLowerCase.contains("insert") || playerPassLowerCase.contains("modify")
            || playerPassLowerCase.contains("from") || playerPassLowerCase.contains("select")
            || playerPassLowerCase.contains(";") || playerPassLowerCase.contains("null")
```

**Comment by sgdc3** [comment]
:+1:

**Comment by DNx5** [comment]
I'm only use preparedStatement if the input type is String.
we can remove that sql keywords check for mysql, but idk for other datasources. I will do it if I have time.

**Comment by sgdc3** [comment]
@ljacqu bump

**Comment by ljacqu** [comment]
> sgdc3 commented @ljacqu bump
> sgdc3 added this to the 5.2 Release milestone

I don't have time to do this personally within the release of 5.2, but if there's any taker for it, it would certainly be great to have it done in 5.2

**Comment by DNx5** [comment]
i think there is no need to validate the database configuration, because it will fail to connect if something wrong. people should put the right value there.

**Comment by ljacqu** [comment]
It's more about preventing some sort of SQL injection. I know it's a long shot since the names come from the config file, i.e. a file only an admin has access to, but it wouldn't hurt.

**Comment by DNx5** [comment]
I'm too lazy to think about that, because it is not only for MySQL :laughing:

**Comment by ljacqu** [comment]
OK :laughing: 
Is 3) possible to be done?

**Comment by DNx5** [comment]
we can remove it, if 1) is done.

**Comment by sgdc3** [comment]
5.3 beta

**Comment by ljacqu** [comment]
@Xephi "awaiting answer"?

**Comment by Xephi** [comment]
I would put please-verify :') but i've finish my check, also i think it's ok now

If you're ok by the way i've fixed 1), we can close this

**Comment by ljacqu** [comment]
1) looks good
2) was decided by DNx5 that we skip (for this issue anyway; I will create another)
3) is still open

**Comment by ljacqu** [comment]
Reopened – there are three other places annotated with `TODO #308` and there are probably more places where this check is present.

**Comment by Xephi** [comment]
Reclose - Sorry :')

**Comment by ljacqu** [comment]
Looks good – thanks! I'm very glad that these checks are no longer part of the codebase. :)
