### ISSUE TITLE
[Dev] SQL - Restructuring

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#309]
Maybe a story for @DNx5?

The MySQL.java class is too big. Too much is being done and it has too many responsibilities. I could imagine a solution as follows:

a. Provide some sort of generic way to wrap exception handling and statement calling if it makes sense (I can help to provide an analysis there if need be) so we don't have all of those `try`-`catch`es everywhere.

b. Create subclasses for various implementations / extensions. There are various places with an `if (Settings.getPasswordHash == HashAlgorithm.XENFORO)` containing 30+ lines of code that could be isolated to some sort of subclass. Here too, I can help brainstorm for possible architectures.

**Comment by DNx5** [comment]
I still don't know what should I do with subclasses thing.

**Comment by ljacqu** [comment]
I'll get back to you on Tuesday. I need some time to analyze this huge class. :P

**Comment by Xephi** [comment]
I have a dump of a Xenforo database if we need it to implement xenforo correctly

**Comment by ljacqu** [comment]
Sorry I haven't gotten back to this – I'll open a more concise issue if I come up with something specific. No sense leaving this issue dangling around in the meantime.
