### ISSUE TITLE
[Dev] Minor - Clean prose in config.yml

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#311]
Blocked by #347

With time, config.yml accumulated a lot of awkward uppercase/lowercase combinations and typos. Clean up the config file a little so "sintax" will be "syntax" and maybe the "AllowedRestrctedUser field" will finally receive that `i` it misses so dearly :)

**Comment by sgdc3** [comment]
We need to break old configuration support.

**Comment by sgdc3** [comment]
We should rework the entire configuration management and structure

**Comment by DNx5** [comment]
We already break servers with our laggy buggy plugin. so its okay to break much more :smile_cat:
