### ISSUE TITLE
[Dev] Look into having a util folder

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#313]
Maybe @sgdc3 can advise here.

As a developer I would like to create various helper scripts (e.g. to update the messages files with newly added keys automatically) and I'd like to share these in the AuthMeReloaded repository, **but** I don't want them to be included in the build. If we created a src/util folder, would it be possible for the files to be excluded from the build entirely? Or would there be a better way to have such a util folder?

**Comment by sgdc3** [comment]
src/tools would be less confusing

**Comment by ljacqu** [comment]
I love src/tools! If we add this folder without referencing it in the pom will it be ignored by the build? (i.e. not compiled and not included in the jar)

**Comment by sgdc3** [comment]
Exactly, if you want we can build the classes but exclude them from the final jar.
PS: We can also create a separate jar ;)

**Comment by ljacqu** [comment]
@sgdc3 Can you verify if I added the _tools_ folder correctly? (In case I didn't use the right structure or if it's being included by the build). If not then we can close this; thanks for all the advice!
