### ISSUE TITLE
[Dev] Permissions - refactor to encapsulate more

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#314]
The `PermissionsManager` does too much.

- [x] Detecting when (and which) permissions plugin is enabled should be done in a separate class, not together with all the permission handling logic.

- [x] Each hook for a permissions plugin should be in its own class, just as we handle only one data source per class (we have a MySql class, a SQLite class, etc.). So this would also need a common interface and then just classes for one specific permissions manager implementing it.

- [x] Minor: replace usage of `System.out.println` with our `ConsoleLogger`...

---

- [X] Issue from outside of the permissions package:
Permissions should be handled by some class in the permissions package and I shouldn't have to worry about any of the implementation or conditions. Currently the permissions check goes over a class from commands (namely `FoundCommandResult#hasPermission()` which then calls further down to `CommandPermissions#hasPermission()`).

- [X] It would be nice if the `CommandHandler` could simply receive a "PermissionsManager" and then just query it with `permissionsManager.hasPermission(CommandSender, CommandDescription)` or `permissionsManager.hasPermission(CommandSender, PermissionNode...)`.

**Comment by sgdc3** [comment]
@ljacqu Bump?

**Comment by ljacqu** [comment]
You can do it if you want ;)

**Comment by sgdc3** [comment]
Yeah but what's the "todo" list about this issue?

**Comment by ljacqu** [comment]
I've updated the description. In a nutshell, a lot of methods in `PermissionsManager` are doing this:
```java
        switch (this.permsType) {
            case PERMISSIONS_EX:
                // Permissions Ex
                PermissionUser user = PermissionsEx.getUser(player);
                return user.has(permsNode);

            case PERMISSIONS_BUKKIT:
                // Permissions Bukkit
                return player.hasPermission(permsNode);
            // etc.
```

That's a good sign that a common interface should be created and then we worry about _one_ permissions plugin per class.
I half-heartedly created the `PermissionsService` interface with barely any methods yet. This can either be extended to contain all common methods of the future child classes, or it can be deleted for a fresh start. (It's not used anywhere yet)

**Comment by timvisee** [comment]
This sounds like a good idea. 

Initially, the permissions manager was ment to be a single class/file that could be included. It has become quite bloated though. 

Generalizing everything sounds good. An abstract adapter base class, with permissions-specific adapters extending the base would do the trick. 

I do think however, that it would be good to leave all methods regarding permission checking, group checking and so on in the main permissions manager class. Those methods should route their calls to the appropriate adapter(s). This has one catch; you're still stuck with a lot of methods in the main class. 

Spreading everything in user, group and other sub-classes would require a lot of work, and the permissions interface would probably become hard to use. 

What do you think?

**Comment by ljacqu** [comment]
@timvisee The permission manager is tackling two problems:
- management of permissions systems (what permission system is active? did it disable?)
- speaking with the permissions system (using the API of whatever permission system we're hooked in)

These two things need some form of separation. I totally agree with you that from the outside, I need to be able to use one class and just be able to do my "check permission node for user", "add user to group" kind of actions without having to know _anything_ about the implementation details.

Without covering all details, I'd propose something like (with better names! ha). (This is really about the idea and not about any name/method/action specifically):

```java
// Implementations talk with one permissions system
public interface PermissionsAdapter {
  boolean hasPermission(Player player, PermissionNode permissionNode);
  void addToGroup(Player player, String group);
}

public class BukkitPermissionAdapter implements PermissionsAdapter {
  private BukkitPermission bukkitPermission;
  @Override public boolean hasPermission(Player player, PermissionNode permissionNode) {
    return bukkitPermission.hasPermission(player, permissionNode.getPath()); // whatever
  } // and so forth
}

public class PermissionsManager {
  // HERE below resides the implementation of whatever perm system is enabled
  // --> could even have a DEFAULT implementation for no perm system = max encapsulation
  private PermissionsAdapter permissionsAdapter;

  public onEnable(String pluginName) { // and onDisable(...)
    // the existing check if we need to change adapter, and so forth
    // so e.g. if we discover that BukkitPermission has enabled:
     adapter = new BukkitPermissionAdapter();
    // we can probably find a nice, generic way to instantiate these adapters, but this could
    // be done in a second iteration, so having a dirty switch here would be a-OK for now
  }

  public boolean hasPermission(Player player, PermissionNode node) {
    // need to delegate to the adapter here, which is a little sad I guess, but hey
     return adapter.hasPermission(player, node);
  }
}
```

@timvisee What do you think?

One advantage of this is that an individual adapter could be unit tested, and even the main permission manager.

**Comment by ljacqu** [comment]
NB: Following the comment thread, the PermissionsService interface needs to be deleted. It's not used anywhere yet and was added back in December half-heartedly.
