### ISSUE TITLE
Ordinary players can use the command / authme unregister player

### ISSUE THREAD

**Issue by Toshka17** [Xephi/AuthMeReloaded#316]
Ordinary players can use the command / authme unregister player

My permissions:
http://pastebin.com/bDpM5sGx

Use version authme reloaded # 182 (30.11)

**Comment by ljacqu** [comment]
Hello,
Thanks for the report and sorry for the troubles. I remember fixing this just a few days ago but it looks like my changes got lost again. I'll report back when this is fixed.

**Comment by ljacqu** [comment]
Thanks for the report. This issue is fixed starting from build 473 on the dev Jenkins:
http://ci.xephi.fr/job/AuthMeReloaded-Dev/

**Comment by Toshka17** [comment]
Thanks
