### ISSUE TITLE
preventOtherCase explanation

### ISSUE THREAD

**Issue by Kixot14** [Xephi/AuthMeReloaded#317]
How can i do nickname registration with case sensetive??

I mean, if player join and register with nickname [player], he shuld not be able to relog with another case [plaYEr, PLAYER, PLayEr, etc...]. 
And if letters [player] is registered, all another case string of this name shuld be disabled to register.
Did that real? Can you help me with that ??

**Comment by Xephi** [comment]
"And if letters [player] is registered, all another case string of this name shuld be disabled to register." it's already the case :O

"I mean, if player join and register with nickname [player], he shuld not be able to relog with another case [plaYEr, PLAYER, PLayEr, etc...]. ", they'll be called to login , also it's not really a problem , isn't it?

**Comment by Kixot14** [comment]
Yeah, i understand all of that... But problem not in it! I just want to if a player registered with one CapsLock, he not be able relog with another... For what? For many reasons! As a example: Permissions is case sensitive, many ban-system is case sensitive...
So please, add option to enable that feature!

**Comment by DNx5** [comment]
so, two players with different name case can play together in the same server?

**Comment by Kixot14** [comment]
No, but if one player join with different case, he will have other perms and punishment. And not only...

**Comment by Xephi** [comment]
Can you please try with latest dev build , and turn in
settings > preventOtherCase option ?

**Comment by Kixot14** [comment]
Of course, but at this moment latest build is build #182, right?? In this build no option PreventOtherCase

**Comment by Xephi** [comment]
Sorry, latest build is ok now, some problem during compilation (a)

**Comment by Kixot14** [comment]
Why you not update AuthMe version on curse.com ??

**Comment by sgdc3** [comment]
We should release beta4

**Comment by ElitStrikerzHD** [comment]
So how to fix it? players can join with the same name at my server ppl even lose their MCMMO AND inventory stuff.............
fix this!!

**Comment by DNx5** [comment]
@ElitStrikerzHD Thank you!!

**Comment by sgdc3** [comment]
This is more a Bukkit bug, we can avoid it, but this will require time...

**Comment by DNx5** [comment]
https://github.com/AuthMe-Team/AuthMeReloaded/commit/2fc55c5e7f55edfec19dc2055cc96b1ed5021072

**Comment by sgdc3** [comment]
Well done @DNx5  :)

**Comment by sgdc3** [comment]
@Kixot14 should work fine now, remember to enable the preventOtherCase feature in the config file ;)

**Comment by Kixot14** [comment]
Can someone explain me, what exactly do this **preventOtherCase** ??
Did that feature can prevent bug in **Offline-mod** servers, when UUID is dupped, because some player join with different case, and as a result dupped all data from plugins, which used UUID system (Essentials, for example: Money, homePoints, punishments... In short: All data, that have previous player with same nickname but another case...)

**Comment by RoinujNosde** [comment]
@Kixot14 if you set preventOtherCase to true, AuthMe will allow only one case to join your server.
E.g.:
I register RoinujNosde; if I try to join with roinujnosde, authme will kick me.

So yes, it prevent uuid bugs :)

**Comment by ljacqu** [comment]
Exactly—in offline mode, even a change in casing (roinuj vs. Roinuj) will have a different UUID. More up-to-date plugins use UUIDs to distinguish players and so will be able to profit from that.

**Comment by Kixot14** [comment]
It's very cool! Thanks!
Did i need to purge all data of players, before use this feature ??

**Comment by RoinujNosde** [comment]
Nope, you don't have to purge players' data :)
(Make a backup of your database just in case)
