### ISSUE TITLE
Strange errors on login/loguts

### ISSUE THREAD

**Issue by YouShallNevaKnow** [Xephi/AuthMeReloaded#318]
05.12 09:21:23 [Server] INFO ... 3 more
05.12 09:21:23 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
05.12 09:21:23 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
05.12 09:21:23 [Server] INFO at fr.xephi.authme.process.Management$3.run(Management.java:60)
05.12 09:21:23 [Server] INFO at fr.xephi.authme.process.logout.AsyncronousLogout.process(AsyncronousLogout.java:81)
05.12 09:21:23 [Server] INFO at fr.xephi.authme.cache.limbo.LimboCache.addLimboPlayer(LimboCache.java:76)
05.12 09:21:23 [Server] INFO at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738)
05.12 09:21:23 [Server] INFO at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getPrimaryGroup(Permission_PermissionsEx.java:264)
05.12 09:21:23 [Server] INFO at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getUser(Permission_PermissionsEx.java:243)
05.12 09:21:23 [Server] INFO Caused by: java.lang.NoSuchMethodError: ru.tehkode.permissions.PermissionManager.getUser(Ljava/util/UUID;)Lru/tehkode/permissions/PermissionUser;
05.12 09:21:23 [Server] INFO at java.lang.Thread.run(Thread.java:745)
05.12 09:21:23 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
05.12 09:21:23 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
05.12 09:21:23 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
05.12 09:21:23 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.0-SNAPSHOT generated an exception while executing task 1014911
05.12 09:21:23 [Server] WARN Exception in thread "Craft Scheduler Thread - 907" 

//no clue what or why its doing this help?

**Comment by games647** [comment]
It happens, because you have an old version of PermissionsEx.

**Comment by YouShallNevaKnow** [comment]
07.12 08:29:45 [Server] INFO ... 3 more
07.12 08:29:45 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
07.12 08:29:45 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
07.12 08:29:45 [Server] INFO at fr.xephi.authme.process.Management$5.run(Management.java:81)
07.12 08:29:45 [Server] INFO at fr.xephi.authme.process.join.AsyncronousJoin.process(AsyncronousJoin.java:127)
07.12 08:29:45 [Server] INFO at fr.xephi.authme.cache.limbo.LimboCache.updateLimboPlayer(LimboCache.java:131)
07.12 08:29:45 [Server] INFO at fr.xephi.authme.cache.limbo.LimboCache.addLimboPlayer(LimboCache.java:76)
07.12 08:29:45 [Server] INFO at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738)
07.12 08:29:45 [Server] INFO at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getPrimaryGroup(Permission_PermissionsEx.java:264)
07.12 08:29:45 [Server] INFO at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getUser(Permission_PermissionsEx.java:243)
07.12 08:29:45 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.getPermissionManager(PermissionsEx.java:405)
07.12 08:29:45 [Server] INFO Caused by: ru.tehkode.permissions.exceptions.PermissionsNotAvailable: Permissions manager is not accessable. Is the PermissionsEx plugin enabled?
07.12 08:29:45 [Server] INFO at java.lang.Thread.run(Thread.java:745)
07.12 08:29:45 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
07.12 08:29:45 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
07.12 08:29:45 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
07.12 08:29:45 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.0-SNAPSHOT generated an exception while executing task 1545290
07.12 08:29:45 [Server] WARN Exception in thread "Craft Scheduler Thread - 2387" 
07.12 08:29:45 [Multicraft] CirclePvP ran command Message of the Day
07.12 08:29:45 [Connect] User CirclePvP, IP 175.144.223.130
07.12 08:29:45 [Server] INFO UUID of player CirclePvP is fe8279eb-e6e3-3248-a7e5-fbee9febe370
07.12 08:26:21 [Server] INFO StormZ left the game.
07.12 08:26:21 [Disconnect] User StormZ has disconnected, reason: Disconnected
07.12 08:26:14 [Server] INFO StormZ joined the game.
07.12 08:26:14 [Server] INFO ... 3 more
07.12 08:26:14 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
07.12 08:26:14 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
07.12 08:26:14 [Server] INFO at fr.xephi.authme.process.Management$5.run(Management.java:81)
07.12 08:26:14 [Server] INFO at fr.xephi.authme.process.join.AsyncronousJoin.process(AsyncronousJoin.java:127)
07.12 08:26:14 [Server] INFO at fr.xephi.authme.cache.limbo.LimboCache.updateLimboPlayer(LimboCache.java:131)
07.12 08:26:14 [Server] INFO at fr.xephi.authme.cache.limbo.LimboCache.addLimboPlayer(LimboCache.java:76)
07.12 08:26:14 [Server] INFO at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738)
07.12 08:26:14 [Server] INFO at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getPrimaryGroup(Permission_PermissionsEx.java:264)
07.12 08:26:14 [Server] INFO at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getUser(Permission_PermissionsEx.java:243)
07.12 08:26:14 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.getPermissionManager(PermissionsEx.java:405)
07.12 08:26:14 [Server] INFO Caused by: ru.tehkode.permissions.exceptions.PermissionsNotAvailable: Permissions manager is not accessable. Is the PermissionsEx plugin enabled?
07.12 08:26:14 [Server] INFO at java.lang.Thread.run(Thread.java:745)
07.12 08:26:14 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
07.12 08:26:14 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
07.12 08:26:14 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
07.12 08:26:14 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.0-SNAPSHOT generated an exception while executing task 1545279
07.12 08:26:14 [Server] WARN Exception in thread "Craft Scheduler Thread - 2381" 
07.12 08:26:14 [Server] INFO Creating empty config: /plugins/Essentials/userdata/stormz.yml
07.12 08:26:14 [Multicraft] StormZ ran command Message of the Day
07.12 08:26:14 [Connect] User StormZ, IP 180.190.68.45
07.12 08:26:14 [Server] INFO UUID of player StormZ is d44a7920-55a1-3666-9f07-8b833d728bc9
07.12 08:18:19 [Server] INFO MrCooler left the game.
07.12 08:18:19 [Disconnect] User MrCooler has disconnected, reason: Disconnected
07.12 08:18:13 [Server] INFO MrCooler» Way to go way g
07.12 08:18:04 [Server] INFO MrCooler» ?
07.12 08:17:40 [Server] INFO MrCooler logged in!
07.12 08:17:34 [Server] INFO MrCooler joined the game.
07.12 08:17:34 [Server] INFO ... 3 more
07.12 08:17:34 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
07.12 08:17:34 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
07.12 08:17:34 [Server] INFO at fr.xephi.authme.process.Management$5.run(Management.java:81)
07.12 08:17:34 [Server] INFO at fr.xephi.authme.process.join.AsyncronousJoin.process(AsyncronousJoin.java:127)
07.12 08:17:34 [Server] INFO at fr.xephi.authme.cache.limbo.LimboCache.updateLimboPlayer(LimboCache.java:131)
07.12 08:17:34 [Server] INFO at fr.xephi.authme.cache.limbo.LimboCache.addLimboPlayer(LimboCache.java:76)
07.12 08:17:34 [Server] INFO at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738)
07.12 08:17:34 [Server] INFO at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getPrimaryGroup(Permission_PermissionsEx.java:264)
07.12 08:17:34 [Server] INFO at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getUser(Permission_PermissionsEx.java:243)
07.12 08:17:34 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.getPermissionManager(PermissionsEx.java:405)
07.12 08:17:34 [Server] INFO Caused by: ru.tehkode.permissions.exceptions.PermissionsNotAvailable: Permissions manager is not accessable. Is the PermissionsEx plugin enabled?
07.12 08:17:34 [Server] INFO at java.lang.Thread.run(Thread.java:745)
07.12 08:17:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
07.12 08:17:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
07.12 08:17:34 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
07.12 08:17:34 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.0-SNAPSHOT generated an exception while executing task 1545264
07.12 08:17:34 [Server] WARN Exception in thread "Craft Scheduler Thread - 2348

//I updated pex but the error still persists

**Comment by games647** [comment]
It's a different error one.  It looks like you have also an old Vault version installed.
