### ISSUE TITLE
Players can Fly (PvPManager + Authme issue)

### ISSUE THREAD

**Issue by MithrandirCraft** [Xephi/AuthMeReloaded#320]
Steps for reproducing this problem:

1. Blank Spigot server: Install AuthmeReloaded + PvPManager (Premium maybe?)
2. Start a pvp with another player, both players will enter pvp mode, in which, if they log out, they will
be punished with an npc spawing on it's place.
3. One of the two pvp-tagged players logs out, and logs back in.
4. That player isn't asked to log in, and can fly. (wtf)

I still haven't tested this myself, but some of my moderators confirmed this. I don't comprehend the security risk this implies, so I'll be doing some testing this afternoon.

-------------------------------------
Current authme version: 5.1 - SNAPSHOT (One of the latest devs)
Current Minecraft-Spigot version: 1.8.8

**Comment by MithrandirCraft** [comment]
Video showcasing this issue: https://youtu.be/sE7k2ypOqMI

**Comment by sgdc3** [comment]
Ok, as PvPManager adds the "NPC" metadata to both the player and npc, if a "combat-logged" player tries to logout, he will be considered by the authme as an NPC and will skip the entire logout process... :/

**Comment by sgdc3** [comment]
(""""" fixed.... """"") I hope xD

**Comment by MithrandirCraft** [comment]
Ok, I think this is fixed. Allthough any player can still sort of levitate before loging in (Could it be that they can only levitate, and not fly, because I have the movement radius on login set to 1?) Is this even normal?

Log in to my server and see how wacky the movement block is xD Just jump around and you will see that you can hop around inside a 1x1 block. Maybe you should consider denying players from moving from the center of a block (blocks also have coordinates on them). Could that be possible?
