### ISSUE TITLE
[Dev] Create a tool to update/verify messages file

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#321]
Now that we have a `MessageKey` enum, we can easily find out which keys exist (and don't). Create a tool in the `src/tools` folder to verify that all of the different languages we offer include all keys. If not, the tool should add the key to the file with the message in English (fail if it doesn't exist in English – in that case someone did a terrible job adding a new key ;))

**Comment by Xephi** [comment]
Just sorted messages file to help us integrate a tool like that:
https://github.com/AuthMe-Team/AuthMeReloaded/commit/c3d724ebce1e8f9187abfb74fa9677d6bf56aafe

To sort files shell script:

ls | grep -v .sort | while read file; do sort "$file" > "$file".sort; done
for file in *.sort; do mv "$file" "${file%%.sort}"; done

**Comment by ljacqu** [comment]
Wow, very nice! Could you add that script to the tools folder?

**Comment by Xephi** [comment]
Done :p

**Comment by ljacqu** [comment]
Thanks!

I'm almost done with an implementation of the messages checker

**Comment by ljacqu** [comment]
Sorting is not done — do we need it?
Nonetheless, I'd like to keep it open. I want to try if I can load it with a Yaml reader instead. This would allow comments and new lines to be handled better. My solution is not cool in that I had to replace new lines with `&n`
