### ISSUE TITLE
kick for vip ?

### ISSUE THREAD

**Issue by JHXSMatthew** [Xephi/AuthMeReloaded#323]
kick_forvip

I did not have permission plugin for vip in auth servers.
But when server is full, players join , then some player would be kicked and sending message "kick_forvip" in message file.

I cannot find relevant config to disable this.

**Comment by DNx5** [comment]
are you using ``` authme.player.* ``` permission for players?

**Comment by JHXSMatthew** [comment]
I do not have permission plugin installed on auth servers.
@DNx5

**Comment by DNx5** [comment]
http://ci.xephi.fr/job/AuthMeReloaded-Dev/492/
