### ISSUE TITLE
[Dev] Write test to ensure command description labels are lowercase

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#324]
An implicit assumption in `CommandDescription` is that all labels are lower-case. In `CommandInitializerTest`, it would be nice to have a test that checks all command labels to detect if any non-lowercase labels are added in the future.

**Comment by Xephi** [comment]
Isn't this ? : https://github.com/Xephi/AuthMeReloaded/blob/master/src/test/java/fr/xephi/authme/command/CommandInitializerTest.java#L95

**Comment by ljacqu** [comment]
You're right—thank you
