### ISSUE TITLE
UnsafeUsername option

### ISSUE THREAD

**Issue by Kixot14** [Xephi/AuthMeReloaded#325]
Hi! Can you add something like refferal system?? Maybe it's can be a code, which players must enter with special register command... 
Example: I used command /AuthRefCode, and after that AuthMe generated for me my referal code. Than i give that code to my friend, and invite him to server.
And after he registered with /refRegister [code] [pass] [confirmPass], i get +1 point to my refferal score. After X amount of this score i can take a bonus, permission or something else, specified in the config file... Or continue to collect a bonus.

**Comment by Kixot14** [comment]
And it would be good if you've can add feature to slash messages on the below line.

Example: Text text text |n Text text

What we receive: 
Text text text
Text text

**Comment by DNx5** [comment]
use ``` &n ``` to add newline

**Comment by Xephi** [comment]
Maybe as a separated plugin :/

**Comment by Kixot14** [comment]
looks like restricted name for registration dont work

**Comment by Kixot14** [comment]
Can you add option to restricted for registration some players nickname??
As a option "UnsafePassword", but for nicknames. "UnsafeNicknames".

**Comment by sgdc3** [comment]
you can add them as unrestricted users with an impossible ip like google dns's one (8.8.8.8)
