### ISSUE TITLE
No permissions Authme-5.2-B496

### ISSUE THREAD

**Issue by ZeTioZ** [Xephi/AuthMeReloaded#331]
Hello, you have tell me to put the new build dev but when the player want to login in they can't because he is telling him they don't have permissions but I've give him permissions and it don't work still

How can I fix it ?

**Comment by DNx5** [comment]
https://github.com/AuthMe-Team/AuthMeReloaded/blob/master/src/tools/docs/permission_nodes.md

**Comment by ZeTioZ** [comment]
thx :)
