### ISSUE TITLE
Authme bug cracked accounts

### ISSUE THREAD

**Issue by ElitStrikerzHD** [Xephi/AuthMeReloaded#334]
i have a few bugs
with a cracked server
1. if a player players with the name: promeiner and he earns MCMMO stats they have them ok but if a other plays joins with the name ProMeiNeR in caps. then the no caps promeiner will lose all his MCMMO stats
2.You can play on cracked names. so its possible to have jordy,Jordy,JORDY,JoRdY ...etc.
3.if a player joins on my account: ElitStrikerzHD and they join like ElitStrikErZHD they need to register BUT THEY WILL HAVE OP!
and the IP thing doesnt fix it they can still join like that so using IP accounts wont help on it

**Comment by games647** [comment]
I guess this is related to #317

**Comment by ElitStrikerzHD** [comment]
thnx man will take a look!

**Comment by ElitStrikerzHD** [comment]
Didnt find any help there lol

**Comment by sgdc3** [comment]
Yes but we don't want to have duplicate issue reports ;)

**Comment by Xephi** [comment]
Can you send us more information like : 
Spigot/CraftBukkit version
AuthMe version (if dev , also build)
AuthMe config file

**Comment by ElitStrikerzHD** [comment]
version: Spigot 1.8.8 (auto update)
Authme version: Authme-5.0-SNAPSHOT.jar

Config authme=
DataSource:
  mySQLColumnName: username
  mySQLTablename: authme
  mySQLUsername: authme
  backend: file
  mySQLColumnLastLogin: lastlogin
  mySQLDatabase: authme
  mySQLPort: '3306'
  mySQLColumnIp: ip
  mySQLHost: 127.0.0.1
  mySQLColumnPassword: password
  mySQLPassword: '12345'
  caching: true
  mySQLlastlocX: x
  mySQLlastlocY: y
  mySQLlastlocZ: z
  mySQLlastlocWorld: world
  mySQLColumnEmail: email
  mySQLColumnId: id
  mySQLColumnLogged: isLogged
GroupOptions:
  UnregisteredPlayerGroup: ''
  RegisteredPlayerGroup: ''
  Permissions:
    PermissionsOnJoin: []
settings:
  sessions:
    enabled: false
    timeout: 25
    sessionExpireOnIpChange: false
  restrictions:
    allowChat: false
    allowCommands:
    - /login
    - /register
    - /l
    - /reg
    - /passpartu
    - /email
    - /captcha
    maxRegPerIp: 3
    maxNicknameLength: 20
    ForceSingleSession: false
    ForceSpawnLocOnJoinEnabled: false
    SaveQuitLocation: true
    AllowRestrictedUser: true
    AllowedRestrictedUser:
    - ElitStrikerzHD;94.226.182.155
    - Jordy;84.198.70.155
    kickNonRegistered: false
    kickOnWrongPassword: false
    teleportUnAuthedToSpawn: true
    minNicknameLength: 3
    allowMovement: false
    timeout: 30
    allowedNicknameCharacters: '[a-zA-Z0-9_]*'
    allowedMovementRadius: 100
    enablePasswordVerifier: true
    ProtectInventoryBeforeLogIn: true
    displayOtherAccounts: true
    ForceSpawnOnTheseWorlds:
    - world
    - world_nether
    - world_the_end
    banUnsafedIP: false
    spawnPriority: authme,essentials,multiverse,default
    maxLoginPerIp: 0
    maxJoinPerIp: 0
    noTeleport: false
    allowedPasswordCharacters: '[a-zA-Z0-9_?!@+&-]*'
  GameMode:
    ForceSurvivalMode: false
    ResetInventoryIfCreative: false
    ForceOnlyAfterLogin: false
  security:
    minPasswordLength: 4
    unLoggedinGroup: unLoggedinGroup
    passwordHash: SHA256
    doubleMD5SaltLength: 8
    supportOldPasswordHash: false
    unsafePasswords: []
  registration:
    enabled: true
    messageInterval: 1
    force: true
    enableEmailRegistrationSystem: false
    doubleEmailCheck: false
    forceKickAfterRegister: false
    forceLoginAfterRegister: false
  unrestrictions:
    UnrestrictedName: []
  messagesLanguage: en
  forceCommands: []
  forceCommandsAsConsole: []
  forceRegisterCommands: []
  forceRegisterCommandsAsConsole: []
  useWelcomeMessage: true
  broadcastWelcomeMessage: false
  delayJoinMessage: false
  applyBlindEffect: false
ExternalBoardOptions:
  mySQLColumnSalt: ''
  mySQLColumnGroup: ''
  nonActivedUserGroup: -1
  mySQLOtherUsernameColumns: []
  bCryptLog2Round: 10
  phpbbTablePrefix: phpbb_
  phpbbActivatedGroupId: 2
  wordpressTablePrefix: wp_
permission:
  EnablePermissionCheck: false
BackupSystem:
  ActivateBackup: false
  OnServerStart: false
  OnServerStop: true
  MysqlWindowsPath: C:\\Program Files\\MySQL\\MySQL Server 5.1\\
Passpartu:
  enablePasspartu: false
Security:
  SQLProblem:
    stopServer: true
  ReloadCommand:
    useReloadCommandSupport: true
  console:
    noConsoleSpam: false
    removePassword: true
  captcha:
    useCaptcha: false
    maxLoginTry: 5
    captchaLength: 5
Converter:
  Rakamak:
    fileName: users.rak
    useIP: false
    ipFileName: UsersIp.rak
  CrazyLogin:
    fileName: accounts.db
Email:
  mailSMTP: smtp.gmail.com
  mailPort: 465
  mailAccount: ''
  mailPassword: ''
  mailSenderName: ''
  RecoveryPasswordLength: 8
  mailSubject: Your new AuthMe Password
  mailText: 'Dear <playername>, <br /><br /> This is your new AuthMe password for
    the server <br /><br /> <servername> : <br /><br /> <generatedpass><br /><br />Do
    not forget to change password after login! <br /> /changepassword <generatedpass>
    newPassword'
  maxRegPerEmail: 1
  recallPlayers: false
  delayRecall: 5
  emailBlacklisted:
  - 10minutemail.com
  emailWhitelisted: []
Hooks:
  multiverse: true
  chestshop: true
  bungeecord: false
  notifications: true
  disableSocialSpy: true
  useEssentialsMotd: false
  customAttributes: false
Performances: {}
Purge:
  useAutoPurge: false
  daysBeforeRemovePlayer: 60
  removePlayerDat: false
  removeEssentialsFile: false
  defaultWorld: world
  removeLimitedCreativesInventories: false
  removeAntiXRayFile: false
  removePermissions: false
Protection:
  enableProtection: false
  countries:
  - US
  - GB
  countriesBlacklist:
  - A1
  enableAntiBot: true
  antiBotSensibility: 5
  antiBotDuration: 10
VeryGames:
  enableIpCheck: true

**Comment by DNx5** [comment]
@ElitStrikerzHD you are not using latest version

**Comment by ElitStrikerzHD** [comment]
Okay thnx DNx5 :D so wich 1 i need? authme 5.0 beta3?

**Comment by sgdc3** [comment]
No, this one: http://ci.xephi.fr/job/AuthMeReloaded-Dev/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT.jar

**Comment by ElitStrikerzHD** [comment]
ok

**Comment by ElitStrikerzHD** [comment]
will this reset my player data and passwords?

**Comment by DNx5** [comment]
you should backup your server before update any plugin.

**Comment by DNx5** [comment]
https://github.com/AuthMe-Team/AuthMeReloaded/commit/2fc55c5e7f55edfec19dc2055cc96b1ed5021072

**Comment by DNx5** [comment]
@ElitStrikerzHD please redownload it if you've downloaded the plugin.

**Comment by ElitStrikerzHD** [comment]
???

**Comment by ElitStrikerzHD** [comment]
what do you mean?

**Comment by DNx5** [comment]
I just updated the plugin, 10 min ago.

**Comment by ElitStrikerzHD** [comment]
this doesnt fix anything

**Comment by ElitStrikerzHD** [comment]
now you can join with 2 accounts on the server
and if i do /mcstats on the other account the stats will apear LOL

**Comment by ElitStrikerzHD** [comment]
this one: http://ci.xephi.fr/job/AuthMeReloaded-Dev/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT.jar?

**Comment by ElitStrikerzHD** [comment]
Well now i an not join anymore with ElitStrikerzHD.........
its case sensitive XD

**Comment by ElitStrikerzHD** [comment]
Now it even has permissions...
i dont have the login permission LoL

**Comment by sgdc3** [comment]
We changed permissions nodes: https://github.com/AuthMe-Team/AuthMeReloaded/blob/master/src/tools/docs/permission_nodes.md

**Comment by sgdc3** [comment]
@ElitStrikerzHD

**Comment by ElitStrikerzHD** [comment]
well 1 problem i tried it and it doesnt work anymore
but now it says you should join with TImothy2001
the account i tried with lol but the real acccount is timothy2001
and now he cant join anymore =p

**Comment by DNx5** [comment]
@ElitStrikerzHD http://ci.xephi.fr/job/AuthMeReloaded-Dev/524/

**Comment by ElitStrikerzHD** [comment]
????

**Comment by ElitStrikerzHD** [comment]
whats that? lol

**Comment by sgdc3** [comment]
?

**Comment by ElitStrikerzHD** [comment]
whats the link @DNx5  sended?

**Comment by sgdc3** [comment]
Our devbuild server ;)

**Comment by ElitStrikerzHD** [comment]
thats a link for authme download

**Comment by DNx5** [comment]
whatever :unamused:

**Comment by ElitStrikerzHD** [comment]
everything is good but 1 problem pls help me with this

**Comment by ElitStrikerzHD** [comment]
ok 2 problems:
1. whats this?


12.12 09:23:05 [Disconnect] User com.mojang.authlib.GameProfile@4ad2046e[id=415b6d8b-671c-329e-8c95-756417d92f1b,name=MarcelAlKenany,properties={},legacy=false] (/83.162.194.15:50924) has disconnected, reason: You are not whitelisted on this server!
12.12 09:23:05 [Server] INFO Disconnecting com.mojang.authlib.GameProfile@4ad2046e[id=415b6d8b-671c-329e-8c95-756417d92f1b,name=MarcelAlKenany,properties={},legacy=false] (/83.162.194.15:50924): You are not whitelisted on this server!
12.12 09:23:05 [Server] INFO UUID of player MarcelAlKenany is 415b6d8b-671c-329e-8c95-756417d92f1b
12.12 09:23:05 [Server] INFO ... 7 more
12.12 09:23:05 [Server] INFO at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:116) ~[?:?]
12.12 09:23:05 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
12.12 09:23:05 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
12.12 09:23:05 [Server] INFO at sun.reflect.GeneratedMethodAccessor130.invoke(Unknown Source) ~[?:?]
12.12 09:23:05 [Server] INFO at fr.xephi.authme.listener.AuthMePlayerListener.onPreLogin(AuthMePlayerListener.java:228) ~[?:?]
12.12 09:23:05 [Server] INFO at fr.xephi.authme.datasource.CacheDataSource.getAuth(CacheDataSource.java:79) ~[?:?]
12.12 09:23:05 [Server] INFO at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
12.12 09:23:05 [Server] INFO at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
12.12 09:23:05 [Server] INFO at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
12.12 09:23:05 [Server] INFO at com.google.common.cache.LocalCache.get(LocalCache.java:3934) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
12.12 09:23:05 [Server] INFO at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
12.12 09:23:05 [Server] INFO at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
12.12 09:23:05 [Server] INFO at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2318) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
12.12 09:23:05 [Server] INFO at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2348) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
12.12 09:23:05 [Server] INFO Caused by: com.google.common.cache.CacheLoader$InvalidCacheLoadException: CacheLoader returned null for key marcelalkenany.
12.12 09:23:05 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
12.12 09:23:05 [Server] INFO at net.minecraft.server.v1_8_R3.LoginListener$2.run(LoginListener.java:172) [spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
12.12 09:23:05 [Server] INFO at net.minecraft.server.v1_8_R3.LoginListener$LoginHandler.fireEvents(LoginListener.java:248) [spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
12.12 09:23:05 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
12.12 09:23:05 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
12.12 09:23:05 [Server] INFO at me.incomprehendable.dev.pwp.transparentlisteners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:28) [PerWorldPlugins.jar:?]
12.12 09:23:05 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
12.12 09:23:05 [Server] INFO at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:118) ~[?:?]
12.12 09:23:05 [Server] INFO org.bukkit.event.EventException
12.12 09:23:05 [Server] INFO Could not pass event AsyncPlayerPreLoginEvent to AuthMe v5.2-SNAPSHOT-b522
12.12 09:23:05 [Server] ERROR **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****

**Comment by sgdc3** [comment]
..........
Don't use per world plugin with AuthMe!

**Comment by sgdc3** [comment]
At least allow it on the entire server!

**Comment by DNx5** [comment]
i have fix that error, download it.

**Comment by ElitStrikerzHD** [comment]
download what DNx5?

**Comment by ElitStrikerzHD** [comment]
and my last issue:
my account timothy2001 is my rela account but i tried to join with TIMothy2001
but now it sayas join with TIMothy2001 instead so i can never join witth timothy2001 again :/

**Comment by DNx5** [comment]
http://ci.xephi.fr/job/AuthMeReloaded-Dev/524/artifact/target/AuthMe-5.2-SNAPSHOT.jar

**Comment by sgdc3** [comment]
@DNx5 Yeah, we need to check how to determinate the real name

**Comment by ElitStrikerzHD** [comment]
btw i can't remove perworldplugins i need it

**Comment by DNx5** [comment]
@ElitStrikerzHD you should update your RealName column in the database

**Comment by sgdc3** [comment]
@ElitStrikerzHD can you post your "PerWorldPlugin" configuration?

**Comment by ElitStrikerzHD** [comment]
# This config controls what plugins work on certain worlds.
# Example
# limit:
#   WorldEdit:
#     - world
#     - world_nether
#   Essentials: []
# This will make it so worldedit will only work in world & world_nether, meaning in the end it is not usable.
# When there is no worlds in the list it will allow it for any worlds, in this example allowing all worlds.
# Whenever a plugin is added, this config will automatically add it!
# exempt-login-events is for excluding login events when true, this means if a plugin uses PlayerLogin it will allow it for any world. We advise this to be enabled!
# blocked-msg is the string displayed to a client when a command is blocked
exempt-login-events: true
check-for-updates: true
blocked-msg: '&c[Error] This command cannot be performed in this world.'
limit:
  CratesPlus:
  - world
  - world_nether
  - world_the_end
  BlockCommands:
  - world
  - world_nether
  - world_the_end
  KitsPreview:
  - world
  - world_nether
  - world_the_end
  SimpleAutoMessage: []
  WorldEdit:
  - world
  - world_nether
  - world_the_end
  - skyworld
  Essentials:
  - world
  - world_nether
  - world_the_end
  ClearLag: []
  PlugMan:
  - world
  - world_nether
  - world_the_end
  AlphaChest:
  - world
  - world_nether
  - world_the_end
  ColourMotd: []
  Lockette:
  - world
  - world_nether
  - world_the_end
  Votifier:
  - world
  - world_nether
  - world_the_end
  WorldGuard: []
  Multiverse-Core: []
  Multiverse-Inventories: []
  EssentialsChat: []
  PermissionsEx: []
  AntiJoinBot: []
  mcMMO:
  - world
  - world_nether
  - world_the_end
  Multiverse-Portals: []
  Vault: []
  GAListener:
  - world
  - world_nether
  - world_the_end
  EssentialsSpawn: []
  MassiveCore:
  - world
  - world_nether
  - world_the_end
  - skyworld
  uSkyBlock: []
  HolographicDisplays: []
  WhatIsIt:
  - world
  - world_nether
  - world_the_end
  CTSNC: []
  Citizens: []
  Mobcash:
  - world
  - world_nether
  - world_the_end
  CompatNoCheatPlus: []
  AuthMe: []
  floAuction:
  - world
  - world_nether
  - world_the_end
  NoCheatPlus: []
  Factions:
  - world
  - world_nether
  - world_the_end
  PlayerHeads:
  - world
  - world_nether
  - world_the_end
  CombatLog:
  - world
  - world_nether
  - world_the_end
  ScoreboardStats: []
  VoteParty: []
  SkyWarsReloaded: []
  EnderPearlCoolDown: []
  MCBans: []
  CoreProtect: []

**Comment by DNx5** [comment]
this...

**Comment by sgdc3** [comment]
:/

**Comment by ElitStrikerzHD** [comment]
xD thats perworldplugins

**Comment by ElitStrikerzHD** [comment]
each world has his own Plugs.....
SkyBlocck needs stuff to be disabled :D

**Comment by sgdc3** [comment]
AuthMe: []
AuthMe should work fine...

**Comment by ElitStrikerzHD** [comment]
i know ;-)

**Comment by DNx5** [comment]
if you don't want to have uuid issue and can login with other name case, you should set your server to
``` online-mode=false ```

**Comment by ElitStrikerzHD** [comment]
No thnx i need a cracked server

**Comment by ElitStrikerzHD** [comment]
my server = offline

**Comment by ElitStrikerzHD** [comment]
its cracked XD

**Comment by DNx5** [comment]
in offline mode server, uuid is determined by player's name (case sensitive). We can't change it instead preventing player join with another name case.

**Comment by ElitStrikerzHD** [comment]
okay!

**Comment by ElitStrikerzHD** [comment]
Players can still talk and move when they are not logged in? dafuck?



config:

DataSource:
  backend: sqlite
  caching: true
  mySQLHost: 127.0.0.1
  mySQLPort: '3306'
  mySQLUsername: authme
  mySQLPassword: '12345'
  mySQLDatabase: authme
  mySQLTablename: authme
  mySQLColumnId: id
  mySQLColumnName: username
  mySQLColumnPassword: password
  mySQLColumnEmail: email
  mySQLColumnLogged: isLogged
  mySQLColumnIp: ip
  mySQLColumnLastLogin: lastlogin
  mySQLlastlocX: x
  mySQLlastlocY: y
  mySQLlastlocZ: z
  mySQLlastlocWorld: world
  mySQLRealName: realname
  mySQLWebsite: false
  mySQLMaxConections: 25
settings:
  helpHeader: AuthMeReloaded
  sessions:
    enabled: false
    timeout: 25
    sessionExpireOnIpChange: false
  restrictions:
    allowChat: false
    allowCommands:
    - /login
    - /register
    - /l
    - /reg
    - /passpartu
    - /email
    - /captcha
    maxRegPerIp: 3
    maxNicknameLength: 20
    ForceSingleSession: false
    ForceSpawnLocOnJoinEnabled: false
    SaveQuitLocation: true
    AllowRestrictedUser: true
    AllowedRestrictedUser:
    - ElitStrikerzHD;94.226.182.155
    - Jordy;84.198.70.155
    kickNonRegistered: false
    kickOnWrongPassword: false
    teleportUnAuthedToSpawn: true
    minNicknameLength: 3
    allowMovement: false
    removeSpeed: true
    timeout: 30
    allowedNicknameCharacters: '[a-zA-Z0-9_]*'
    allowedMovementRadius: 100
    enablePasswordVerifier: true
    ProtectInventoryBeforeLogIn: false
    displayOtherAccounts: false
    ForceSpawnOnTheseWorlds:
    - world
    - world_nether
    - world_the_end
    banUnsafedIP: false
    spawnPriority: authme,essentials,multiverse,default
    maxLoginPerIp: 0
    maxJoinPerIp: 0
    noTeleport: false
    allowedPasswordCharacters: '[a-zA-Z0-9_?!@+&-]*'
  GameMode:
    ForceSurvivalMode: false
    ResetInventoryIfCreative: false
    ForceOnlyAfterLogin: false
  security:
    minPasswordLength: 4
    unLoggedinGroup: unLoggedinGroup
    passwordHash: SHA256
    doubleMD5SaltLength: 8
    supportOldPasswordHash: false
    unsafePasswords: []
  registration:
    enabled: true
    messageInterval: 1
    force: true
    enableEmailRegistrationSystem: false
    doubleEmailCheck: false
    forceKickAfterRegister: false
    forceLoginAfterRegister: false
  unrestrictions:
    UnrestrictedName: []
  messagesLanguage: en
  forceCommands: []
  forceCommandsAsConsole: []
  forceRegisterCommands: []
  forceRegisterCommandsAsConsole: []
  useWelcomeMessage: true
  broadcastWelcomeMessage: false
  delayJoinLeaveMessages: true
  applyBlindEffect: false
  preventOtherCase: false
ExternalBoardOptions:
  mySQLColumnSalt: ''
  mySQLColumnGroup: ''
  nonActivedUserGroup: -1
  mySQLOtherUsernameColumns: []
  bCryptLog2Round: 10
  phpbbTablePrefix: phpbb_
  phpbbActivatedGroupId: 2
  wordpressTablePrefix: wp_
permission:
  EnablePermissionCheck: false
BackupSystem:
  ActivateBackup: false
  OnServerStart: false
  OnServerStop: true
  MysqlWindowsPath: C:\\Program Files\\MySQL\\MySQL Server 5.1\\
Security:
  SQLProblem:
    stopServer: true
  ReloadCommand:
    useReloadCommandSupport: true
  console:
    noConsoleSpam: false
    removePassword: true
  captcha:
    useCaptcha: false
    maxLoginTry: 5
    captchaLength: 5
Converter:
  Rakamak:
    fileName: users.rak
    useIP: false
    ipFileName: UsersIp.rak
  CrazyLogin:
    fileName: accounts.db
Email:
  mailSMTP: smtp.gmail.com
  mailPort: 465
  mailAccount: ''
  mailPassword: ''
  mailSenderName: ''
  RecoveryPasswordLength: 8
  mailSubject: Your new AuthMe Password
  mailText: 'Dear <playername>, <br /><br /> This is your new AuthMe password for
    the server <br /><br /> <servername> : <br /><br /> <generatedpass><br /><image><br
    />Do not forget to change password after login! <br /> /changepassword <generatedpass>
    newPassword'
  maxRegPerEmail: 1
  recallPlayers: false
  delayRecall: 5
  emailBlacklisted:
  - 10minutemail.com
  emailWhitelisted: []
  generateImage: true
Hooks:
  multiverse: true
  bungeecord: false
  disableSocialSpy: true
  useEssentialsMotd: false
  customAttributes: false
Purge:
  useAutoPurge: false
  daysBeforeRemovePlayer: 60
  removePlayerDat: false
  removeEssentialsFile: false
  defaultWorld: world
  removeLimitedCreativesInventories: false
  removeAntiXRayFile: false
  removePermissions: false
Protection:
  enableProtection: false
  countries:
  - US
  - GB
  countriesBlacklist:
  - A1
  enableAntiBot: true
  antiBotSensibility: 5
  antiBotDuration: 10
VeryGames:
  enableIpCheck: true
GroupOptions:
  UnregisteredPlayerGroup: ''
  RegisteredPlayerGroup: ''
  Permissions:
    PermissionsOnJoin: []

**Comment by ElitStrikerzHD** [comment]
they login and it says already logged in but they can't move

**Comment by DNx5** [comment]
I hope you have restarted the server after updating AuthMe.

**Comment by ElitStrikerzHD** [comment]
i did :/.
and btw now it doesnt show ElitStrikerzHD left the game!
only ElitStrikerzHD joined the game :p help me lol

**Comment by ElitStrikerzHD** [comment]
it is really bugy
my new players they all need to
/register [password] [password]
then it registers them but they can't move i think they do can talk :p 
but when they logout and join again
the are logged in lol or they can /login then and then it works
and after that it nevers seems to be happening only with new ppl

**Comment by DNx5** [comment]
related to #339

**Comment by ElitStrikerzHD** [comment]
so ya i will need to have some help with that

**Comment by ljacqu** [comment]
@ElitStrikerzHD I believe this should not happen anymore with the latest dev builds.

**Comment by ElitStrikerzHD** [comment]
whats the latest dev build?

**Comment by ljacqu** [comment]
You can find it at http://ci.xephi.fr/job/AuthMeReloaded-Dev/

**Comment by sgdc3** [comment]
@ElitStrikerzHD so, any news?

**Comment by ElitStrikerzHD** [comment]
yeah. i need the download again haha
