### ISSUE TITLE
ERROR, when use command /AuthMe register

### ISSUE THREAD

**Issue by Kixot14** [Xephi/AuthMeReloaded#335]
error log: http://pastebin.com/gaps5eDx

i use CraftBukkit version git-Spigot-2f787bd-ea28011 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT

P.S. authMe data placed on MySQL

**Comment by DNx5** [comment]
update
http://ci.xephi.fr/job/AuthMeReloaded/
