### ISSUE TITLE
[Dev] Test that plugin.yml has up-to-date permission nodes

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#337]
CommandConsistencyTest checks that plugin.yml lists the same base commands as defined in CommandInitializer.
- Rename CommandConsistencyTest to PluginYmlConsistencyTest (or similar)
- Create a test that checks the listed permission nodes in plugin.yml against the existing ones

**Comment by ljacqu** [comment]
Blocked by #415

**Comment by ljacqu** [comment]
Depends on #516

**Comment by sgdc3** [comment]
Should check also #872

**Comment by ljacqu** [comment]
@sgdc3 Can you explain what the defaults should be? If DefaultPermission is ALLOWED is it true in the yml file?

**Comment by sgdc3** [comment]
Yeah
