### ISSUE TITLE
Some players can't move on login

### ISSUE THREAD

**Issue by MithrandirCraft** [Xephi/AuthMeReloaded#339]
I don't know exactly what causes this, but it seems that some new players that register for the first time, can't move. They can move once they relog in though.

This could be due to the speed removal effect, which is already quite buggy (And should be improved). It could be being maintained after they log in.

I can't detail much more, as I'm already using some really shittly methods for login, in order to avoid some other issues. The whole situation prevents me from studying this in detail.

-----------------------------------
Current authme version: 5.2 - SNAPSHOT (One of the latest devs)
Current Minecraft-Spigot version: 1.8.8

**Comment by DNx5** [comment]
@MithrandirCraft could you include the build number?

**Comment by MithrandirCraft** [comment]
wow sorry, I thought I had already answered this: build nº 494

**Comment by hsombini** [comment]
I can relate!

Also it happens on bungeecord using AuthMeBungeeBridge, players who changes the server cannot move!

**Comment by DNx5** [comment]
http://ci.xephi.fr/job/AuthMeReloaded-Dev/525/artifact/target/AuthMe-5.2-SNAPSHOT.jar

**Comment by MithrandirCraft** [comment]
I would call this fixed unless I find someone crying about it on my server.

I can't try it myself, because I've limited my manual registry ammount, and don't like adding random emails to the login xD (Sorry about that)

Feel free to close this ticket, I will reopen it if I find out this happening again.

**Comment by MithrandirCraft** [comment]
Ok, big NOPE.

This issue is still happening, and it's not only happening on registry, it also happens to random players on login.

It's curious, because they can't move a single inch. Maybe you should learn from whatever is happening to them in order to apply complete inmobility before login xDD

**Comment by DNx5** [comment]
so, this is not remove speed problem.

**Comment by MithrandirCraft** [comment]
@DNx5 It might be, I don't really know... :S

**Comment by DardBrinza** [comment]
The same problem : l The latest version authme 5.2, new players can not move , it helps rejoining after registration. Last spigot 1.8.8 + ProtocolSupport. AuthmeBridge not used.

**Comment by ljacqu** [comment]
I had this issue while testing my command refactor before merging the change from games647 to my branch and encountered this issue when I logged out in creative. Once I included the changes by games647 I could move again but not fly (as would be expected in creative mode).

**Comment by games647** [comment]
@ljacqu This is related to #355

**Comment by MithrandirCraft** [comment]
Calling this closed untill further report from my players.

**Comment by Lorsel** [comment]
I've encountered this problem, any help?
