### ISSUE TITLE
MySQLThread (any maybe other storage Threads) are not always synchronized with settings

### ISSUE THREAD

**Issue by Trojaner25** [Xephi/AuthMeReloaded#34]
When starting a server with the latest AuthMe Dev Build, sometimes the MySQLThread (and maybe other Threads too?) are started even before the settings were fully read, so it can't get the correct database connection info and causes at https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/datasource/MySQL.java#L106 an NumberFormatException since port equals null. This exception gets caught somewhere and the server shuts down

**Comment by Trojaner25** [comment]
Push

**Comment by Xephi** [comment]
Is it fixed ?

**Comment by Trojaner25** [comment]
Should be fixed

**Comment by sgdc3** [comment]
@Xephi, I think we can close this issue now ;)
