### ISSUE TITLE
How use a bungeecord send server after login/register?

### ISSUE THREAD

**Issue by Dimatert9** [Xephi/AuthMeReloaded#340]
https://github.com/AuthMe-Team/AuthMeReloaded/commit/d01713a2f59cf7a313eb8d8874b735164daf75f9

How use it? How configure a Lobby server?

**Comment by sgdc3** [comment]
No this isn't a "send to" feature. We can add it anyway if you want ;)

**Comment by Dimatert9** [comment]
add this please.

**Comment by DNx5** [comment]
@sgdc3 no, restructure those damn Settings before adding more feature.

**Comment by NickFirenzo** [comment]
AuthMe plugin install only on lobby(hub) server. On others spigot servers change port, set 23781 or etc

**Comment by Xephi** [comment]
Done, use latest devbuild please
