### ISSUE TITLE
Make a converter faster.

### ISSUE THREAD

**Issue by Dimatert9** [Xephi/AuthMeReloaded#341]
Its too slow. it make a 100 accounts for 2-3 sec.
![image](https://cloud.githubusercontent.com/assets/8667294/11763820/5b1e5806-a122-11e5-934c-b5db37a96587.png)

**Comment by kingpyro** [comment]
You'd only do a conversion once. Should be happy their even is a conversion...

**Comment by ljacqu** [comment]
We have eight different converters. Which one is this about?

**Comment by Dimatert9** [comment]
converter sqltoflat

**Comment by ljacqu** [comment]
For any dev reading this.
Looking at the code I would suggest a `saveAuth(Iterable<PlayerAuth> auths)` method on `FlatFile` to save multiple _PlayerAuth_ instances with the same writers. Opening buffers for each entry is grossly inefficient, especially when we're talking about thousands of entries.
Additionally, I wonder how much of an impact it would have to replace `if ((i % 100) == 0)` to `if ((i & 127) == 127)` in SqlToFlat.java. Modulo is famously slow but of course it's nicer to have round numbers.

**Comment by sgdc3** [comment]
sqltoflat converter?! WE SHOULD REMOVE IT

**Comment by sgdc3** [comment]
FlatFile support is deprecated, it should be readonly. (r/w only before a complete flat to sql convertion)!

**Comment by Dimatert9** [comment]
i need flat file to wipe accaunts.

**Comment by sgdc3** [comment]
What do you mean?

**Comment by Dimatert9** [comment]
I want remove all accaunts without pex groups.(Default group users)

**Comment by sgdc3** [comment]
Why do you need to convert the database to flatfile?

**Comment by sgdc3** [comment]
You can do it with mysql and sqlite

**Comment by Dimatert9** [comment]
How?

**Comment by sgdc3** [comment]
Can you describe how you wipe the flatfile ?

**Comment by Dimatert9** [comment]
From bukkit plugin get donators names, and with utilite remove other users from file.

**Comment by sgdc3** [comment]
You can edit any .sql file with programs like http://www.sqlabs.com/sqlitemanager.php

**Comment by Dimatert9** [comment]
Ok. How i can convert from sql to mysql? Authme.db ----> authme.sql

**Comment by sgdc3** [comment]
Authme.sb is the FlatFile database, authme.sql is the sqlite database, mysql is stored only on the mysql server!

**Comment by sgdc3** [comment]
At the moment, what's your database backend? Mysql or Sqlite?

**Comment by Dimatert9** [comment]
Sqlite

**Comment by sgdc3** [comment]
Ok

**Comment by sgdc3** [comment]
How many .sql file do you have in authme directory?

**Comment by Dimatert9** [comment]
0

**Comment by sgdc3** [comment]
Impossible

**Comment by Dimatert9** [comment]
![image](https://cloud.githubusercontent.com/assets/8667294/11766825/04905794-a1a1-11e5-9ca1-dba7eec90e93.png)

**Comment by sgdc3** [comment]
Wait, right, we save sql as authme.db xD sorry.

**Comment by sgdc3** [comment]
.sql are the export to mysql

**Comment by Dimatert9** [comment]
How i can make .sql from .db?

**Comment by sgdc3** [comment]
wait, you don't need to do it

**Comment by sgdc3** [comment]
you need to open your authme.db with a sqlite management software

**Comment by sgdc3** [comment]
wait, can you post your configuration?

**Comment by Dimatert9** [comment]
I want move authme database to mysql.

**Comment by Dimatert9** [comment]
I have donators users list. How i can wipe others accaunts with sql command?

**Comment by Xephi** [comment]
Use latest devbuild, and use /converter sqlitetosql
