### ISSUE TITLE
Can't find the email.html file

### ISSUE THREAD

**Issue by Toshka17** [Xephi/AuthMeReloaded#342]
I can not fine this file in my Authme Foilder (latest dev build)

**Comment by Xephi** [comment]
This file is use in replace of mailText variable in config.yml, the entire email.html is read and send to a player when he use /email recovery

**Comment by Toshka17** [comment]
[AuthMe] Your email.html config contains some error and cannot be send!

Where i can find this file?

**Comment by sgdc3** [comment]
Should have been fixed, try latest dev build ;) http://ci.xephi.fr/job/AuthMeReloaded-Dev/

**Comment by Toshka17** [comment]
Unfortunately, nothing changed (sorry for my English)

**Comment by Xephi** [comment]
Can you please try latest devbuild ?

**Comment by Toshka17** [comment]
the problem is solved. Error is no more, but the message still has not come to email to the player

**Comment by Toshka17** [comment]
Thanks for your work :)

**Comment by Xephi** [comment]
I'm working on all issue with email sending, wait a bit , sorry for problems
