### ISSUE TITLE
Help about Authme PURGE in config.yml

### ISSUE THREAD

**Issue by NickFirenzo** [Xephi/AuthMeReloaded#343]
Hi I need help about PURGE in config.yml at authme.
I'd like to make if player is not joined on the server last 20-30 days his account will be deleted.
Is it purge option?
IF daysBeforeRemovePlayer: 60, person who is not joined last 60 days will be deleted from the database?

Purge:
  useAutoPurge: true
  daysBeforeRemovePlayer: 60
  removePlayerDat: true
  removeEssentialsFile: true
  defaultWorld: world
  removeLimitedCreativesInventories: true
  removeAntiXRayFile: true
  removePermissions: false

**Comment by DNx5** [comment]
@NickFirenzo Yes!
