### ISSUE TITLE
Deprecate the FlatFile backend

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#344]
- remove all the X to FlatFile converter
- on first start convert the entire database to sql (kick players until the convertion is finished)

**Comment by ljacqu** [comment]
I don't understand the second point – what database type should be converted to SQL?

**Comment by sgdc3** [comment]
Atm when the backend is set to flatfile we send warning messages saying that an automated conversion have been scheduled. After a restart if the convertion is finished, the backend option is set to sqlite.

**Comment by sgdc3** [comment]
Now with the canConnect boolean value we can allow connections only after the conversion is finished.

**Comment by sgdc3** [comment]
So flatfile will be completely deprecated

**Comment by sgdc3** [comment]
We need also to add new converters, like the x to sqlite one.

**Comment by ljacqu** [comment]
Thanks. So it's "convert the database to sqlIte"

**Comment by sgdc3** [comment]
yeah and set canConnect to false until it is finished

**Comment by Xephi** [comment]
Done

**Comment by ljacqu** [comment]
I've added it to our list of [breaking changes](https://github.com/AuthMe-Team/AuthMeReloaded/wiki/Breaking-Changes)
