### ISSUE TITLE
I need help about delete accounts from DATABASE

### ISSUE THREAD

**Issue by NickFirenzo** [Xephi/AuthMeReloaded#345]
I need help about database authme which you saved all that poop is registered. I want to delete a part of the accounts and some to stay, whether they could somehow, by some accounts command as the database and the rest remain to be deleted? With Purge it can not do because I want to leave a few accounts.

**Comment by ljacqu** [comment]
What database type are you using? If it's a SQL one I would suggest running a SQL command on your DB. It would be hard to generalize the behavior you want to a command.

**Comment by NickFirenzo** [comment]
I'm using SQL on SHA256 alogrithm and I want to delete a part of account, but other part stay in database. Any command or etc?

**Comment by sgdc3** [comment]
Of all the accounts? Describe what do you want to do ;)

**Comment by ljacqu** [comment]
You only want to delete a part of the accounts? Like all of their IP addresses for example?

**Comment by NickFirenzo** [comment]
My serevr has ranks in large numbers over 100 and now not to register new I want to stay just as they normally ranks those in GroupManager and other players(who is not in users.yml, who is members) can be removed from the base, as it can afford to do? I know GroupManager AuthMe with no connection.

**Comment by ljacqu** [comment]
The problem is what you want is essentially to load data from elsewhere (permissions) and then to combine it with AuthMe to alter the data in a specific, individual way. That's a lot of effort to develop for an individual's needs that are beyond the scope of AuthMe.

Maybe we can meet halfway and teach you how to delete all users except a given list

**Comment by NickFirenzo** [comment]
And I need to delete all users except those specified as in GroupManager users.yml. If possible if you can, to enter names that can be left in the database and the rest are deleted.

**Comment by ljacqu** [comment]
You said you were using SQL. Something like the following will **delete all users** _except_ the ones in the list:
```SQL
DELETE FROM authme 
WHERE username NOT IN ('anna', 'bobby', 'christy', 'denise', 'elliot');
```
The list with anna, bobby, etc. are the users that will **not** be deleted. **Please back up your database beforehand;** it should be possible to generate a dump of it.

I'm assuming standard config values where `authme` = mySQLTablename, `username` = mySQLColumnName

**Comment by NickFirenzo** [comment]
Doesn't work, all acounts has been removed xD

**Comment by sgdc3** [comment]
Have you done a backup? D:

**Comment by sgdc3** [comment]
all the name should be lowercase

**Comment by NickFirenzo** [comment]
Yes I have a backup :D

**Comment by sgdc3** [comment]
@Xephi MySql master, we need your magic power!

**Comment by Xephi** [comment]
The only one way to do it without need to dev an individual method, is to use the system that @ljacqu as mentioned, by the way, you need to check each syntax of player names, and check the column where you do your conditions have the same case

**Comment by sgdc3** [comment]
@Xephi can you fix the query @ljacqu posted?

**Comment by Xephi** [comment]
The query is correct :O

**Comment by sgdc3** [comment]
"Doesn't work, all acounts has been removed xD"

**Comment by Xephi** [comment]
yeah , he needs to list all his users in users.yml , in the query , was an error occured when you use the command @NickFirenzo  ?

**Comment by NickFirenzo** [comment]
No need all. Tested just a few when I wrote the command was above write are erased from all accounts MySQL (Of course, this was just a test of the new database).

**Comment by Xephi** [comment]
Done, result was :

DELETE FROM authme WHERE id IN (SELECT * FROM (SELECT id FROM authme WHERE username NOT IN ('xephi', 'nickfirenzo')) as tmp);
