### ISSUE TITLE
Email.txt detected brackets

### ISSUE THREAD

**Issue by zhgt** [Xephi/AuthMeReloaded#346]
Hi. The problem that occurs to me is that when a user receives an email to retrieve your password (/ email recovery) this does not display the password, either the server name or user name (not displayed <generatedpass> for example).

The console does not appear to errors because the email is sent successfully.

**Comment by ljacqu** [comment]
Are you using newer versions where the email is defined in email.html already? (Not in config.yml)
If so, please make sure that you've adjusted your tags accordingly. It's no longer ´<playerName>´ but ´%playerName%´.
You can see the default here: https://github.com/AuthMe-Team/AuthMeReloaded/blob/master/src/main/resources/email.html

**Comment by zhgt** [comment]
That was the problem, thank you very much!
