### ISSUE TITLE
Player logout coordinates do not correspond with login coordinates

### ISSUE THREAD

**Issue by MithrandirCraft** [Xephi/AuthMeReloaded#348]
It seems that when some players log out, their position is reset to some RANDOM POSITION.

@Xephi Indicated to me that this issue could be solved by kicking all players before a restart, but that was on a time that I though that this was happening during restarts. Now I've noticed it happens whenever certain players log out.

-----------------------------------

Current authme version: 5.2-SNAPSHOT-b660
Current Minecraft-Spigot version: 1.8.8

**Comment by MithrandirCraft** [comment]
Corrected the login position where players appear: It's actually completely RANDOM some times.

**Comment by MithrandirCraft** [comment]
This issue is fixed.

If It re-emerges for some reason, I will reopen this ticket.

**Comment by MithrandirCraft** [comment]
yeah...

**Comment by sgdc3** [comment]
This happens only with old accounts. New users (registered on latest builds) are ok.

**Comment by MithrandirCraft** [comment]
Using a more actual version (updated version to 660) and executing: /authme purgelastpos *

My server crashed, nice xD
huh... but it looks like it helped, I don't know if it's going to be something permanent though...
