### ISSUE TITLE
Authme Console SPAWM Error[DRIVER]

### ISSUE THREAD

**Issue by NickFirenzo** [Xephi/AuthMeReloaded#352]
Hi, I need help about authme, I getting and error in console.

15.12 19:13:08 [Server] ERROR Connection failed.
15.12 19:13:08 [Server] ERROR Unknown SQL driver 'sql'. Please use one of these drivers: [mysql, pgsql, sqlite, h2]
15.12 19:12:08 [Server] ERROR Connection failed.
15.12 19:12:08 [Server] ERROR Unknown SQL driver 'sql'. Please use one of these drivers: [mysql, pgsql, sqlite, h2]
15.12 19:11:08 [Server] ERROR Connection failed.
15.12 19:11:08 [Server] ERROR Unknown SQL driver 'sql'. Please use one of these drivers: [mysql, pgsql, sqlite, h2]
15.12 19:10:08 [Server] ERROR Connection failed.
15.12 19:10:08 [Server] ERROR Unknown SQL driver 'sql'. Please use one of these drivers: [mysql, pgsql, sqlite, h2]
15.12 19:09:08 [Server] INFO AntiJoinBot is enabled
15.12 19:09:08 [Server] ERROR Connection failed.
15.12 19:09:08 [Server] ERROR Unknown SQL driver 'sql'. Please use one of these drivers: [mysql, pgsql, sqlite, h2]

**Comment by NickFirenzo** [comment]
And how to disable command
/email change Old New
Only
/email recovery 
/email add been availible, /email change how to disable?

**Comment by sgdc3** [comment]
Why did you close that?

**Comment by ljacqu** [comment]
Probably had a wrong config value, and the second was presumably a permissiobns issue
