### ISSUE TITLE
Email Recovery. Own domain

### ISSUE THREAD

**Issue by zhgt** [Xephi/AuthMeReloaded#353]
I think I made 3 ticket and email but hey, I want to finish. The problem is missing me fix it:

I am not allowed to send emails from your own domain (@ imperiummc.com.ar) but from a @ gmail.com if I may.

When I use an @ gmail.com I use port 25. smtp.gmail.com and works perfect.

When I use an email with own domain, in this case @ imperiummc.com.ar not work for me, I contact people who also use this domain for other games and I mentioned that the SMTP have to use the local (127.0.0.1) and that works for them perfectly. In my case it is not so. Probe also in case using SMTP domain (mail.imperiummc) and did not run. Probe in both cases also use ports 25, 465 and 587, do not succeed.

Any ideas? The strange thing is that domain via gmail but can not.

I need this because I only work properly and, of course thank you.

**Comment by sgdc3** [comment]
Have you tried to send an email from gmail to our domain? Maybe it's a dns or maillserver issue.

**Comment by zhgt** [comment]
By sending an email from agmail aimperiummc is sent correctly.

Using a mail to sendgmail works.
Using aimperiummc mail is not working.

Mails to other games that domain is used and the local SMTP 127.0.0.1 is used and it works, but not authme.

**Comment by Xephi** [comment]
Does your smtp support ssl ?

**Comment by zhgt** [comment]
Yes.

**Comment by sgdc3** [comment]
@Xephi

**Comment by Xephi** [comment]
Can you please try the latest devbuild ?

**Comment by Xephi** [comment]
Up

**Comment by sgdc3** [comment]
@zhgt Bump

**Comment by sgdc3** [comment]
@zhgt Any news?

**Comment by zhgt** [comment]
Sorry, I was on holiday.
Update the dev and remains unchanged.

**Comment by sgdc3** [comment]
@Xephi bump
