### ISSUE TITLE
Email RECOVERY password via E - MAIL

### ISSUE THREAD

**Issue by NickFirenzo** [Xephi/AuthMeReloaded#354]
Hi, I configure in config.yml to recovery password via email but getting an error, please tell me how to fix :(

Error: http://pastebin.com/wH7hQqMG
AuthMe config.yml[EMAIL]: http://pastebin.com/fntTjkTh
AuthMe config.yml: http://pastebin.com/4ansUTi3

Before 3-5 hours worked fine without problem I getting an email, but now I getting an error

**Comment by zhgt** [comment]
Change the port to 25.

**Comment by NickFirenzo** [comment]
No changes, again some error

@zhgt

**Comment by NickFirenzo** [comment]
When will be fixed email recovery?

**Comment by Xephi** [comment]
Can you please try the latest dev build ? After the reboot, authme will create a file name email.html in the config folder that can me modify as you wish

In case of gmail, you need to disable low level application security :
https://github.com/Xephi/AuthMeReloaded/issues/260#issuecomment-155617799

**Comment by NickFirenzo** [comment]
I installed latest buil but email.html file doesn't generate in AuthMe folder.
Getting WARN in console
'WARN Your email.html config contains some error and cannot be send!'
http://prntscr.com/9fa2as - Email.html doesn't exist.

**Comment by Xephi** [comment]
My bad, can you please try the latest devbuild please ?

**Comment by Xephi** [comment]
erf missclick sorry for closing

**Comment by NickFirenzo** [comment]
When type /email recovery example@example.com getting WARN
17.12 19:51:41 [Server] WARN Fail to send a mail to example@example.com cause Sending the email to the following server failed : smtp.gmail.com:465

**Comment by ljacqu** [comment]
Did it create the email.html file? If so, kindly close this and open another issue. Otherwise things will get very confusing fast

**Comment by Xephi** [comment]
Have you test what i said here :
https://github.com/Xephi/AuthMeReloaded/issues/260#issuecomment-155617799
?

**Comment by NickFirenzo** [comment]
@Xephi 
Yes, sure. I turned on this
http://prntscr.com/9fduy7
I tried to send but can't

**Comment by NickFirenzo** [comment]
I tried to generate new AuthMe folder, add email, password, join on server registered and added an email, tried to recovery and in console output same error :(

**Comment by NickFirenzo** [comment]
@Xephi ?

**Comment by NickFirenzo** [comment]
@Xephi 
@sgdc3 
@ljacqu

**Comment by sgdc3** [comment]
Working on it ;)

**Comment by NickFirenzo** [comment]
Oh, thanks for notify :)

**Comment by Xephi** [comment]
Can you please try the latest devbuild ?

**Comment by NickFirenzo** [comment]
Again same :(

 WARN Fail to send a mail to macedoniancraft05@gmail.com cause Sending the email to the following server failed : smtp.gmail.com:465

**Comment by NickFirenzo** [comment]
Again Same :(

 WARN Fail to send a mail to XXX@xx.com cause Sending the email to the following server failed : smtp.gmail.com:465

**Comment by Xephi** [comment]
ok, what's the mail provider to the player who's receive the mail ? can you try to send from a gmail.com mail to another gmail.com mail to test?

**Comment by NickFirenzo** [comment]
I'm ever trying to send on gmail.com
xxx@gmail.com send to zzz@gmail.com
Provider is gmail, again problem and i'm using in config.yml gmail provider.

**Comment by NickFirenzo** [comment]
Done, FIXED
