### ISSUE TITLE
removespeed: true = Nocheatplus fly hack. (blocked ncp move) first registered players.

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#356]
Authme 5.2 build:185 Snapshot

**Comment by sgdc3** [comment]
Can you describe an example scenario? Who is affected? Before or after the login?

**Comment by andris155** [comment]
https://youtu.be/diCVKZn6Sxk

**Comment by sgdc3** [comment]
ok fixed 50%: Now newbies will be able to walk without quitting and relogging. We still need to fix the ncp issue.

**Comment by ljacqu** [comment]
Hello @andris155, a change was made by @games647. Could you try the latest build at http://ci.xephi.fr/job/AuthMeReloaded-Dev/ and see if it fixes your issue? Thanks.

**Comment by andris155** [comment]
Latest dev build fixed bug thanks. :)
