### ISSUE TITLE
[Dev] EncryptionMethod interface shouldn't throw exception

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#358]
The `EncryptionMethod` interface has a `throws` clause that should be handled a level lower – it should not pass it up to be handled where the classes are used.

`MessageDigest.getInstance()` and similar methods may throw a `NoSuchAlgorithmException` but this should be handled within the implementation – e.g. by using a local `try`-`catch` clause and converting it into a runtime exception:
```java
try {
   MessageDigest md5 = MessageDigest.getInstance("MD5");
   // etc.
} catch (NoSuchAlgorithmException e) {
   throw new IllegalStateException("Your system does not support MD5", e);
}
```
There may be a way to handle this generically on superclass level but certain encryption implementations depend e.g. on SHA1 but then do a lot of logic wrapped around it, in which case I think it would be inappropriate to put all of this in a `try`-`catch` just because of `MessageDigest.getInstance()`. However, maybe some kind of helper method is possible, along the lines of:
```java
public abstract class EncryptionMethod {
  protected static MessageDigest getMessageDigest(String algorithm) {
    /* return MessageDigest.getInstance(algorithm); with try-catch */
  }
}
```
That's pretty nice.

**Comment by sgdc3** [comment]
@ljacqu I'll assign it to @DNx5 ;) sorry, i've assignet too many issues to you

**Comment by ljacqu** [comment]
@sgdc3 np. I generally assign myself stuff I intend to do in the near future or things that really make sense for me to do (like documenting the command handling that I refactored)

**Comment by sgdc3** [comment]
Ah ok ;) Srry

**Comment by ljacqu** [comment]
Also salt generation should be handled in each class, not in `PasswordSecurity`.

**Comment by ljacqu** [comment]
Planned changes:
1. Make `PasswordSecurity` non-static
2. `PasswordSecurity` is a real "manager" class and will worry about persisting the salt
3. However, it's the job of `EncryptionMethod` to generate a salt if none supplied
4. `EncryptionMethod` implementations do not do any datasource modifications: that's the job of `PasswordSecurity`

--> Separation of concerns, clearer layout of what happens where. This way `EncryptionMethod` implementations will be "parameters in, computation out" kind of classes without any unclear side effects (like writes to the data source).
