### ISSUE TITLE
Unregistered Players with forceRegistration on false can't hit mobs

### ISSUE THREAD

**Issue by Kongolan** [Xephi/AuthMeReloaded#36]
There is a problem in AuthMeEntityListener.java

The 	public void onDmg(EntityDamageByEntityEvent event) method needs  

if (!data.isAuthAvailable(name)) {
            if (!Settings.isForcedRegistrationEnabled) {
                return;
            }
}

be added as well at line 119!

**Comment by Xephi** [comment]
Fixed
