### ISSUE TITLE
Investigate NPC issue

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#360]
Ref: 558a124 by @sgdc3
If an NPC player has the same name tag as a player, it can be used to bypass certain checks. Investigate what may be affected by this and find an elegant solution. 

@sgdc3 If I described this issue wrong or if there's more to add, kindly edit this description

**Comment by Xephi** [comment]
NPC from which plugin ?

**Comment by sgdc3** [comment]
Lots of plugins store npc status with metadatas. The issue is when a plugin creates a npc with the name of an ingame player. In spigot metadatas are sorted by playername, not by entity uuid!

**Comment by sgdc3** [comment]
Example plugin: PvPManager Pro

**Comment by Xephi** [comment]
"Lots of plugins store npc status with metadatas. The issue is when a plugin creates a npc with the name of an ingame player. In spigot metadatas are sorted by playername, not by entity uuid!" , also it's a spigot issue, nop ? :/

**Comment by sgdc3** [comment]
Yeah

**Comment by sgdc3** [comment]
Idk how we can fix this xD

**Comment by DNx5** [comment]
Solution: 
Use NPC check API from those NPC plugins instead checking player's metadatas.

**Comment by sgdc3** [comment]
Nope, too many dependencies
