### ISSUE TITLE
Broken VeryGames IP resolver

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#362]

**Comment by games647** [comment]
Could you explain this issue.

**Comment by sgdc3** [comment]
Sorry I'll post an appropriate description by tomorrow ;)

**Comment by ljacqu** [comment]
Why is VeryGames IP resolver needed in the first place?

**Comment by sgdc3** [comment]
Because VeryGames (server hosting provider) uses an own DDOS protection (proxy) that hides the realname of connected players.

**Comment by ljacqu** [comment]
Oh, thanks for the info

**Comment by Xephi** [comment]
Fixed

**Comment by ljacqu** [comment]
705cc7ba
