### ISSUE TITLE
SQL Cache refresh/update 

### ISSUE THREAD

**Issue by JHXSMatthew** [Xephi/AuthMeReloaded#365]
I have been using an external register (web) system && AuthMe database cache .
But if players registered on the webpage, the data is not in the AuthMe cache.

Is there any way to solve this issue better than restarting server or adding a cache refresh task ?

Thanks.

**Comment by Xephi** [comment]
Can you try latestdevbuild and set
mySQLWebsite to true ?

**Comment by sgdc3** [comment]
@JHXSMatthew

**Comment by JHXSMatthew** [comment]
Sorry, I have not been active for a while, 
I will test it tomorrow (23:00 now).
Thanks for fixing !

**Comment by JHXSMatthew** [comment]
Works, cheers!
