### ISSUE TITLE
Players sent to wrong location upon login after server restart

### ISSUE THREAD

**Issue by UberNoel** [Xephi/AuthMeReloaded#366]
I've been hosting my server for 3 months now and it worked perfectly until yesterday my players started complaining to me about this , i tried to fix it but it dint work out . Yesterday all i remembered was i restarted my server once .
Let 'Place B' Be : Everyones log out point when the server restarted yesterday
Let 'Place A' Be : The Normal Log Out Place When Players Disconnect
How It Works Now :
1. Players logs out at Place A 
2. Players rejoins at spawn to login
3. After login , Players are sent to Place B ( Its soppose to teleport them back to Place A )
4. Everytime Players login it just sends them to place B
How It Should Behave : 
1. Players logs out at Place A
2. Players rejoins at spawn to login
3. After login  , Players are sopposed to be teleported back to where they logged out.

So what im trying to say is players just spawns at the area whr i restarted yesterday... May i know a solution to this ? But i dont understand how does this restart affect this ? Or maybe its not the restart . Im clueless

Config:
DataSource:
  mySQLColumnName: username
  mySQLTablename: authme
  mySQLUsername: authme
  backend: file
  mySQLColumnLastLogin: lastlogin
  mySQLDatabase: authme
  mySQLPort: '3306'
  mySQLColumnIp: ip
  mySQLHost: 127.0.0.1
  mySQLColumnPassword: password
  mySQLPassword: '12345'
  caching: true
  mySQLlastlocX: x
  mySQLlastlocY: y
  mySQLlastlocZ: z
  mySQLlastlocWorld: world
  mySQLColumnEmail: email
  mySQLColumnId: id
  mySQLColumnLogged: isLogged
GroupOptions:
  UnregisteredPlayerGroup: ''
  RegisteredPlayerGroup: ''
  Permissions:
    PermissionsOnJoin: []
settings:
  sessions:
    enabled: false
    timeout: 10
    sessionExpireOnIpChange: true
  restrictions:
    allowChat: false
    allowCommands:
    - /login
    - /register
    - /l
    - /reg
    - /passpartu
    - /email
    - /captcha
    maxRegPerIp: 3
    maxNicknameLength: 20
    ForceSingleSession: true
    ForceSpawnLocOnJoinEnabled: false
    SaveQuitLocation: true
    AllowRestrictedUser: false
    AllowedRestrictedUser:
    - playername;127.0.0.1
    kickNonRegistered: false
    kickOnWrongPassword: false
    teleportUnAuthedToSpawn: true
    minNicknameLength: 3
    allowMovement: false
    timeout: 10000
    allowedNicknameCharacters: '[a-zA-Z0-9_]*'
    allowedMovementRadius: 100
    enablePasswordVerifier: true
    ProtectInventoryBeforeLogIn: true
    displayOtherAccounts: true
    ForceSpawnOnTheseWorlds:
    - world
    - world_nether
    - world_the_end
    banUnsafedIP: false
    spawnPriority: authme,essentials,multiverse,default
    maxLoginPerIp: 0
    maxJoinPerIp: 0
    noTeleport: false
    allowedPasswordCharacters: '[\x21-\x7E]*'
  GameMode:
    ForceSurvivalMode: false
    ResetInventoryIfCreative: false
    ForceOnlyAfterLogin: false
  security:
    minPasswordLength: 4
    unLoggedinGroup: unLoggedinGroup
    passwordHash: SHA256
    doubleMD5SaltLength: 8
    supportOldPasswordHash: false
    unsafePasswords: []
  registration:
    enabled: true
    messageInterval: 5
    force: true
    enableEmailRegistrationSystem: false
    doubleEmailCheck: false
    forceKickAfterRegister: false
    forceLoginAfterRegister: false
  unrestrictions:
    UnrestrictedName: []
  messagesLanguage: en
  forceCommands: []
  forceCommandsAsConsole: []
  useWelcomeMessage: true
  broadcastWelcomeMessage: false
  delayJoinMessage: false
  applyBlindEffect: false
  forceRegisterCommands: []
  forceRegisterCommandsAsConsole: []
ExternalBoardOptions:
  mySQLColumnSalt: ''
  mySQLColumnGroup: ''
  nonActivedUserGroup: -1
  mySQLOtherUsernameColumns: []
  bCryptLog2Round: 10
  phpbbTablePrefix: phpbb_
  phpbbActivatedGroupId: 2
  wordpressTablePrefix: wp_
permission:
  EnablePermissionCheck: false
BackupSystem:
  ActivateBackup: false
  OnServerStart: false
  OnServerStop: true
  MysqlWindowsPath: C:\\Program Files\\MySQL\\MySQL Server 5.1\\
Passpartu:
  enablePasspartu: false
Security:
  SQLProblem:
    stopServer: true
  ReloadCommand:
    useReloadCommandSupport: true
  console:
    noConsoleSpam: false
    removePassword: true
  captcha:
    useCaptcha: false
    maxLoginTry: 5
    captchaLength: 5
Converter:
  Rakamak:
    fileName: users.rak
    useIP: false
    ipFileName: UsersIp.rak
  CrazyLogin:
    fileName: accounts.db
Email:
  mailSMTP: smtp.gmail.com
  mailPort: 465
  mailAccount: ''
  mailPassword: ''
  mailSenderName: ''
  RecoveryPasswordLength: 8
  mailSubject: Your new AuthMe Password
  mailText: 'Dear <playername>, <br /><br /> This is your new AuthMe password for
    the server <br /><br /> <servername> : <br /><br /> <generatedpass><br /><br />Do
    not forget to change password after login! <br /> /changepassword <generatedpass>
    newPassword'
  maxRegPerEmail: 1
  recallPlayers: false
  delayRecall: 5
  emailBlacklisted: []
  emailWhitelisted: []
  generateImage: true
Hooks:
  multiverse: true
  chestshop: true
  bungeecord: false
  disableSocialSpy: true
  useEssentialsMotd: false
  customAttributes: false
Performances: {}
Purge:
  useAutoPurge: false
  daysBeforeRemovePlayer: 60
  removePlayerDat: false
  removeEssentialsFile: false
  defaultWorld: world
  removeLimitedCreativesInventories: false
  removeAntiXRayFile: false
  removePermissions: false
Protection:
  enableProtection: false
  countries:
  - US
  - GB
  countriesBlacklist:
  - A1
  enableAntiBot: false
  antiBotSensibility: 5
  antiBotDuration: 10
VeryGames:
  enableIpCheck: false

**Comment by Xephi** [comment]
Can you please try with latest dev version ?

http://ci.xephi.fr/job/AuthMeReloaded-Dev/

**Comment by UberNoel** [comment]
I've installed it on my server and it does not let anyone join the server.
My username is ' UberNoel ' it states that im using UberNoel and i should have joined with ubernoel without caps.
Same goes with the username ' Jintai ' it says that he should have joined with jintai without caps

**Comment by sgdc3** [comment]
@UberNoel Can you open another issue for that? Thx ;)

**Comment by DNx5** [comment]
@UberNoel do you have access to mysql db? if yes, try to clear all realname column values.

**Comment by ljacqu** [comment]
Closing—two months went by without an answer
