### ISSUE TITLE
EventListeners with MONITOR priority should not modify events

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#367]
`AuthMePlayerListener#onPlayerQuit` and `AuthMePlayerListener#onPlayerKick` have priority level `EventPriority.MONITOR` but modify the events.

Check all listener methods using the `MONITOR` level and change the level if they change the event under circumstances.

http://wiki.bukkit.org/Event_API_Reference#Event_Priorities

**Comment by Xephi** [comment]
Changed, idk why that was has monitor T.T

Thanks

**Comment by ljacqu** [comment]
5c2547c
