### ISSUE TITLE
Event listeners also handling canceled events

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#368]
I noticed that some event listener methods do not have `ignoreCancelled = true` and so also perform logic when an event has been canceled. I'm not familiar enough with the event listener to change this as I don't know if it is intended.

In any case, I wrote a test class `ListenerConsistencyTest` in which the methods without `ignoreCancelled = true` are saved in `CANCELED_EXCEPTIONS`. If all is good, kindly just remove the `TODO` comment, otherwise kindly fix the offending commands and remove the exceptions from the test class altogether.

**Comment by Xephi** [comment]
Actually all event got ignoreCancelled = true has they need it, only event which cannot been cancel don't provide this annotation :)

**Comment by ljacqu** [comment]
I thought about it this morning… It wouldn't make sense to be able to cancel the event of a player leaving etc.
If all the exceptions are fine the TODO can be removed and this issue closed. I don't want to do this myself so a second pair of eyes can go over the exceptions for the canceled thing :)

**Comment by ljacqu** [comment]
Not done, the TODO is still in the code.

**Comment by Xephi** [comment]
Done ! >.<
