### ISSUE TITLE
How can I use AuthMe with AuthMe bridge[BungeeCord]

### ISSUE THREAD

**Issue by NickFirenzo** [Xephi/AuthMeReloaded#370]
Hi,
I need help about Authme + AuthME bridge on bungeecord mod.
How to install AuthMe on all spigot servers wich are on my bungeecord?
Connect with bridge, same account, password and etc will be on all servers, how to do that?
Thanks :)

**Comment by sgdc3** [comment]
You need a mysql server shared between all the authme instances.
A more simple way is to install authme only on the join server and block direct servers port with a firewall rule (keep open only the bungeecord one) ;)

**Comment by Xephi** [comment]
Nah, the better way is actually that : 

Use ONLY one instance of BungeeCord,
Install AuthMe and configure it with mySQL on EACH servers
In each authme config.yml, set to true on Hook > BungeeCord

:)

**Comment by sgdc3** [comment]
Yeah but if you don't own a dedicated server it's hard to setup a common mysql server

**Comment by NickFirenzo** [comment]
OK I know it needs to connect to MySQL database from which you read the data but my question is whether all Spigoli servers should install AuthMe and AuthMe Bridge on BungeeCord.

**Comment by Xephi** [comment]
If you use only one instance of BungeeCord, you don't need AuthMe Bridge, you just need to install latest dev build of AuthMe and set the bungeecord hook to true :)

**Comment by NickFirenzo** [comment]
Done, solved. But I have one question how to convert SQL to MySQL because when make connect and join on server on screen getting /register, but all accounts are on SQL.

**Comment by Xephi** [comment]
You mean SQLite to MySQL ?

**Comment by NickFirenzo** [comment]
Yes

**Comment by Xephi** [comment]
I think we don't have something like that T.T i'll check >.<

**Comment by NickFirenzo** [comment]
Can you add option to convert sqlite on accounts to mysql?

**Comment by Xephi** [comment]
Done : latest dev build ->
Configure your authme config.yml to work with mySQL, and use : /converter sqlitetosql

**Comment by NickFirenzo** [comment]
Already using MySQL, getting an error to configure, how to configure ?
http://prntscr.com/9gt9do
Converter:
  Rakamak:
    fileName: igraci.rak
    useIP: true
    ipFileName: ip.rak
  CrazyLogin:
    fileName: accounts.db

**Comment by Xephi** [comment]
What ? :') if you already use MySQL you don't need to convert :O :')

**Comment by Xephi** [comment]
Even if, you need to configure the database part of the config.yml to work with mysql :

DataSource:
    # What type of database do you want to use?
    # Valid values: sqlite, mysql
    backend: mysql
    # Enable database caching, should improve database performance
    caching: true
    # Database location
    mySQLHost: 127.0.0.1
    # Database Port
    mySQLPort: '3306'
    # Username about Database Connection Infos
    mySQLUsername: authme
    # Password about Database Connection Infos
    mySQLPassword: '12345'
    # Database Name, use with converters or as SQLITE database name
    mySQLDatabase: authme
    # Table of the database
    mySQLTablename: authme
    # Column of IDs to sort data
    mySQLColumnId: id
    # Column for storing or checking players nickname
    mySQLColumnName: username
    # Column for storing players passwords
    mySQLColumnPassword: password
    # Column for storing players emails
    mySQLColumnEmail: email
    # Column for Saving if a player is logged in or not
    mySQLColumnLogged: isLogged
    # Column for storing players IPs
    mySQLColumnIp: ip
    # Column for storing players lastlogins
    mySQLColumnLastLogin: lastlogin
    # Column for SaveQuitLocation - X
    mySQLlastlocX: x
    # Column for SaveQuitLocation - Y
    mySQLlastlocY: y
    # Column for SaveQuitLocation - Z
    mySQLlastlocZ: z
    # Column for SaveQuitLocation - World name
    mySQLlastlocWorld: world
    # Column for RealName
    mySQLRealName: realname

Xephi

**Comment by NickFirenzo** [comment]
Before MySQL I'm used SQLite and now I want to convert SQLite to MySQL and save on mysql driver.
I need convert of h2 to mysql

**Comment by NickFirenzo** [comment]
Fixed, thanks
