### ISSUE TITLE
2x welcome messages on first join (synchronous login called twice!!!)

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#371]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/11920953/80c1ea7c-a77c-11e5-93bc-30677aeb1184.PNG)
AuthMeReloaded-Dev b548

**Comment by sgdc3** [comment]
Critical issue, login process is called twice! This may be the cause of lot of other issues!

**Comment by sgdc3** [comment]
@ljacqu @Xephi @DNx5 @timvisee

**Comment by Xephi** [comment]
We never call synchronous login after a registration :O

**Comment by Xephi** [comment]
https://github.com/AuthMe-Team/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/process/register/AsyncRegister.java#L147 WHY ? :O @sgdc3

**Comment by Xephi** [comment]
https://github.com/AuthMe-Team/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/process/register/ProcessSyncPasswordRegister.java#L132 @DNx5 call login event in registration ? :O 

You add this to registration : 
https://github.com/AuthMe-Team/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/process/register/ProcessSyncPasswordRegister.java#L152
But i think it's called again at login cause you force it @sgdc3 :)
https://github.com/AuthMe-Team/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/process/login/ProcessSyncronousPlayerLogin.java#L204

**Comment by sgdc3** [comment]
True, sorry, but register should call login instead of doing login process itself

**Comment by Xephi** [comment]
Fixed in latest dev build
