### ISSUE TITLE
Authme removeSpeed doesn't work with non registered users.

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#372]
Join = allow moving, and later remove speed.
https://www.youtube.com/watch?v=e_gK_0OcoPU&feature=youtu.be
AuthMeReloaded-Dev b548

**Comment by Xephi** [comment]
If i understand the video correctly, on first join, speed is set to 0,
what about if you logged in ?

**Comment by andris155** [comment]
New video:
https://www.youtube.com/watch?v=vGFtsXdplRA&feature=youtu.be

**Comment by sgdc3** [comment]
Ok, understood

**Comment by sgdc3** [comment]
Fixed, try latest dev build

**Comment by andris155** [comment]
New players = Not fixed bug.

**Comment by andris155** [comment]
Registered players = Fixed bug

**Comment by games647** [comment]
So if I understand it correctly. The speed isn't removed on join as it should, correct?

**Comment by sgdc3** [comment]
yeah

**Comment by sgdc3** [comment]
@andris155 Any news?

**Comment by andris155** [comment]
Fixed.

**Comment by ljacqu** [comment]
Thanks for the feedback
