### ISSUE TITLE
verifyPassword option is broken

### ISSUE THREAD

**Issue by rErEaT** [Xephi/AuthMeReloaded#374]
I maked it true but nothing happend!

I using your latest dev build!

**Comment by ljacqu** [comment]
Why is verifyPassword even a setting? Password should always be verified

**Comment by sgdc3** [comment]
We should rename it to enableDoubleCheckPassword (/register psw *psw*)

**Comment by sgdc3** [comment]
I'm doing it right now..

**Comment by rErEaT** [comment]
And should be fixed :D

2015-12-23 11:21 GMT+01:00 Gabriele C. <notifications@github.com>:

> I'm doing it right now..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Xephi/AuthMeReloaded/issues/374#issuecomment-166856010>
> .
>



-- 
Üdvözlettel:
Foki Dániel

**Comment by sgdc3** [comment]
Yeah, working on it

**Comment by rErEaT** [comment]
I watch this dev site: http://ci.xephi.fr/job/AuthMeReloaded-Dev/

**Comment by sgdc3** [comment]
Yeah it's the right one

2015-12-23 11:31 GMT+01:00 rErEaT <notifications@github.com>:

**Comment by ljacqu** [comment]
enableDoubleCheckPassword implies that the password gets... _double-checked_ (while actually it's either checked, or not). How about something with `confirmation` in it, uhh... I'm bad at naming things. confirmPasswordOnRegister? Something like that? enablePasswordConfirm? I don't know

**Comment by sgdc3** [comment]
@ljacqu ok, @rErEaT can you post your configuration file (remember to remove the mysql passwords if you use them)

**Comment by rErEaT** [comment]
http://pastebin.com/FEhjzRbT

**Comment by sgdc3** [comment]
Ok, blindness should have been fixed ;)

**Comment by sgdc3** [comment]
@rErEaT Can you record a video of  the other issue?

**Comment by rErEaT** [comment]
ye I hope.

btw what does it?
    enablePasswordConfirmation
    enablePasswordVerifier

same thing or not?

**Comment by rErEaT** [comment]
![1](https://cloud.githubusercontent.com/assets/2604798/11975418/e1874bde-a96d-11e5-9e46-e410be012cc9.png)
![2](https://cloud.githubusercontent.com/assets/2604798/11975419/e1a5d5a4-a96d-11e5-99f3-63197d7b19d9.png)

**Comment by sgdc3** [comment]
does it work with rimeout > 0 ?

**Comment by sgdc3** [comment]
blindness i mean xD

**Comment by rErEaT** [comment]
yepp, works with 1.

**Comment by sgdc3** [comment]
Build number?

**Comment by rErEaT** [comment]
#572

**Comment by sgdc3** [comment]
ok

**Comment by sgdc3** [comment]
I'm too stupid, fixed xD

**Comment by rErEaT** [comment]
blind effect is working now with build575 :+1:

**Comment by rErEaT** [comment]
what about "enablePasswordConfirmation" ?

**Comment by ljacqu** [comment]
@rErEaT If you set `enablePasswordConfirmation` to `false` players will only have to enter the password once, e.g. `/register test` instead of `/register test test`. The message will be the same, but you can change it in the `messages_en.yml` file or whatever language you use.

I tested it and it worked as expected.

**Comment by rErEaT** [comment]
Okay, then everything works!

**Comment by ljacqu** [comment]
Great, thanks for the feedback! In that case I'll close this issue.
