### ISSUE TITLE
Error 'login' Authme 5.2

### ISSUE THREAD

**Issue by DardBrinza** [Xephi/AuthMeReloaded#376]
I use spigot latest spigot 1.8.8 and authme 5.2 #582
Error:
http://pastebin.com/CRUTpTGc

**Comment by ljacqu** [comment]
Do you have any idea what the player invoked? From the error it seems to me that he wrote `/login` (just that) but I can't reproduce it.

**Comment by ljacqu** [comment]
Thanks for the report; it should be fixed as of build nr. 585.
http://ci.xephi.fr/job/AuthMeReloaded-Dev/

**Comment by DardBrinza** [comment]
Fixed. Thanks :) Close.
