### ISSUE TITLE
Error messages authme 5.2 #585

### ISSUE THREAD

**Issue by DardBrinza** [Xephi/AuthMeReloaded#377]
New lang file and same error in console:

[AuthMe] Error getting message with key 'invalid_session'. Please verify your config file at 'messages_en.yml'

[AuthMe] Error getting message with key 'password_error_nick'. Please verify your config file at 'messages_en.yml'

**Comment by sgdc3** [comment]
TODO: clean/check all the language files for deprecated/missing messages

**Comment by ljacqu** [comment]
A quick look at the repository's messages_en.yml confirms we have those keys in messages_en.yml. 
https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/resources/messages/messages_en.yml

We have a tool task to verify our default message files and there, no keys are missing.

So maybe @DardBrinza is using an old version of messages_en.yml, or for some reason those keys were removed.

**Comment by sgdc3** [comment]
Yeah, sorry, forgot about this ;)

**Comment by sgdc3** [comment]
Wait, he said "new lang files" :p

**Comment by ljacqu** [comment]
Oh, good catch, didn't notice that :P

**Comment by Xephi** [comment]
Is is fixed with latest build?

**Comment by DardBrinza** [comment]
Yep, fix
