### ISSUE TITLE
Player can't move after register

### ISSUE THREAD

**Issue by jwtuan** [Xephi/AuthMeReloaded#378]
hi, im use AuthMe-5.2-Snapshot, Build 186. After player register, thay can't move.
Sorry for my english.

**Comment by sgdc3** [comment]
Can you try this version please? http://ci.xephi.fr/job/AuthMeReloaded-Dev/ ;)

**Comment by sgdc3** [comment]
@jwtuan

**Comment by jwtuan** [comment]
@sgdc3  yes, i'm use this version (latest build 586), with spigot 1.8.8. (just fresh spigot 1.8.8 and only 1 plugin is authme)
also MagRegPerIP dont work.
sorry again for my bad english.

**Comment by jwtuan** [comment]
@sgdc3 Thank you! it work perfect.
