### ISSUE TITLE
How to disable ForceSurvivalMode latest dev build?

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#379]
ForceSurvivalMode: false config option not work.
authme.player.bypassforcesurvival permission not work.

**Comment by andris155** [comment]
Fixed:
- mv.bypass.gamemode.*

**Comment by sgdc3** [comment]
so, not an authme issue, right? ;)

**Comment by andris155** [comment]
Not, and thank you for the new version.
I like new permission logic. :)

**Comment by sgdc3** [comment]
if you look at the newPlugin.yml file you can see how permissions will look like in version 5.2 release. What do you think about? (we need feedback ;D)

**Comment by andris155** [comment]
We like the newer version of the Permissions. We think, that it's more convenient and better than the older versions of the AuthMe.

**Comment by sgdc3** [comment]
Thanks ;) We'll try to implement it asap

**Comment by sgdc3** [comment]
email: http://hastebin.com/ayopinuqax.xml
