### ISSUE TITLE
Allow restricted users by domain instead of ip

### ISSUE THREAD

**Issue by ziutekkk** [Xephi/AuthMeReloaded#380]
Hi
I would like to suggest option to accept domain ip in restricted users section of configuration.

        # For activate Restricted user by ip u need
        # to set True this option and configure the field
        # AllowedRestrctedUser as show below
        AllowRestrictedUser: true
        # Restricted user will kick players that 
        # is listed below and they dont
        # meet the match of username;ip
        # Example playername;127.0.0.1 , if playername 
        # hasent 127.0.0.1 as ip address
        # he will not be allowed to join the server
        AllowedRestrictedUser:
        - player;player.ddns.net

I and my moderators have dynamic ip, so we are using noip.com domains to have static ip for restricted users configuration.
Unfortunately authme accepts only numerical ips.
I tested that on correctly set domain from noip.com and it doesnt allow me to connect to server.
Is it possible to do something with that?
Thanks

**Comment by Xephi** [comment]
Can you please try this build ?
http://ci.xephi.fr/job/AuthMeReloaded-Dev/599/

**Comment by ziutekkk** [comment]
Unfortunately no, still it doesn't work. 
It is not very very needed thing but it would be great if it worked well to improve security on cracked servers.

**Comment by sgdc3** [comment]
@Xephi

**Comment by DNx5** [comment]
afaik, it will never work on dynamic ip

**Comment by sgdc3** [comment]
@DNx5 why?

**Comment by sgdc3** [comment]
DDNS do the trick

**Comment by DNx5** [comment]
@sgdc3 because it was dynamic, reverse lookup not always do the trick.

**Comment by sgdc3** [comment]
why not?

**Comment by DNx5** [comment]
just try it

**Comment by sgdc3** [comment]
done xD

**Comment by sgdc3** [comment]
it should work fine with noip

**Comment by sgdc3** [comment]
anyway it's not safe as a static ip, i'll close the issue
