### ISSUE TITLE
It gets very old after the exit point /login

### ISSUE THREAD

**Issue by DardBrinza** [Xephi/AuthMeReloaded#381]
I go to the server and appears in the exit point, insert / login and throws me on a very old exit point. After entering the password I do not stay on the same spot, and flip to the other. Latest authme and spigot,

**Comment by ljacqu** [comment]
Possibly related to #348

**Comment by DardBrinza** [comment]
Returns on the coordinates of which have been for a long time when you exit . I updated the plugin to the new version , and the coordinates of the older players in the outlet were old .

**Comment by Xephi** [comment]
Is it now fixed when you had reset all last pos player ?

**Comment by DardBrinza** [comment]
Oh lol, I mixed up the topic. After cleaning the columns I corrected this problem with the exit points . But the upgrade to the latest version , removing the problem with /logout. Close Fix XD

**Comment by Xephi** [comment]
Okay, thanks for your report anyway :)
