### ISSUE TITLE
Error on console + Crash

### ISSUE THREAD

**Issue by MithrandirCraft** [Xephi/AuthMeReloaded#382]
I have this error spamming on the console:
http://hastebin.com/ofododifuh.rb

It looks like it also caused a global kick tonight.
The server also shows symptoms of low tps, allthgough the timings don't seem to indicate this is Authme's fault.

------------------------------
Current authme version: 5.2 - SNAPSHOT (build 593)
Current Minecraft-Spigot version: 1.8.8

**Comment by sgdc3** [comment]
@ljacqu

**Comment by ljacqu** [comment]
Hello,
Thank you for the report and sorry for the trouble! This should be fixed from build nr. 595 and upwards.
http://ci.xephi.fr/job/AuthMeReloaded-Dev/

**Comment by DardBrinza** [comment]
Fixed
