### ISSUE TITLE
Logout problem

### ISSUE THREAD

**Issue by DardBrinza** [Xephi/AuthMeReloaded#384]
While playing could accidentally delete the authorization. Writing a chat and you can not move, but the message asking you to enter the password is not present. If you enter / login in the chat message is displayed on successful authorization. Latest authme and spigot :)
As auto /logout

**Comment by sgdc3** [comment]
This is an issue with /reload command

**Comment by sgdc3** [comment]
Don't reload the server/plugin if not required.

**Comment by sgdc3** [comment]
If you don't run the /reload command everything should work fine.

**Comment by DardBrinza** [comment]
No, i don't use /reload. My online 180 players and /reload is very dangerous,

**Comment by sgdc3** [comment]
Is it a standalone server or a bungeecord network?

**Comment by DardBrinza** [comment]
This 1 server + bungeecord. Bunch need for anti-bot.

**Comment by sgdc3** [comment]
why bungee as antibot?

**Comment by DardBrinza** [comment]
A small room in which players get when joining a server. This room can not interact with the server. I use session:

  sessions:
    enabled: true
    timeout: 8
    sessionExpireOnIpChange: true

**Comment by sgdc3** [comment]
ah ok, so 3 servers... Bungee + Login + GameServer

**Comment by DardBrinza** [comment]
No, Bumgee +Login Game Server. Anti-bot room in plugin. No plugin creates a room and after passing it , the player gets to the primary server, and enter a password . No AuthmeBungee or more servers, 1 server.

**Comment by DardBrinza** [comment]
I clear xyz in mysql and fix problem. Close :)

**Comment by sgdc3** [comment]
? are you sure? It sounds strange...

**Comment by DardBrinza** [comment]
I'm sure. Just cleared the columns x y z.

**Comment by Xephi** [comment]
Okok, thanks for your report anyway ^^
