### ISSUE TITLE
[Dev] Release AuthMe 5.2

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#385]
This is an issue for us to store whatever needs to be taken care of for the person doing the 5.2 release of AuthMe (I presume @Xephi).
- [x] Remove `AuthMe#getVerygamesIp`: ([ref](https://github.com/AuthMe-Team/AuthMeReloaded/commit/5d21d1b))
- [x] Update the [AuthMe Bukkit dev page](http://dev.bukkit.org/bukkit-plugins/authme-reloaded/) with the [new permission nodes](https://github.com/AuthMe-Team/AuthMeReloaded/blob/master/docs/permission_nodes.md)
- [x] List all [Breaking changes](https://github.com/AuthMe-Team/AuthMeReloaded/wiki/Breaking-Changes)
- [x] Delete the branch "pre-commands-merge". (Please do not do it before 2016-01-15)

Feel free to directly edit this description if more things come to mind, or add a separate comment if you're more comfortable with that.

**Comment by sgdc3** [comment]
Why do we need to remove verygames ipresolver? @Xephi

**Comment by Xephi** [comment]
Cause VeryGames will remove the technology and will use something else that we don't need to handle to get real Player ip ;) they are finishing change their Architecture just before :)

**Comment by sgdc3** [comment]
Ah ok ;)

**Comment by Xephi** [comment]
[ ] - Write the full changelog :'(

**Comment by ljacqu** [comment]
Before releasing the final version:
- check single session
- check that email sending works

**Comment by ljacqu** [comment]
This can be closed:
- I just checked email sending & single session successfully
- I try to actively maintain the breaking changes page at https://github.com/AuthMe/AuthMeReloaded/wiki/Breaking-Changes, I think I'm only missing the fact that we deleted a lot of Bungee code
- A while back I created a changelog page https://github.com/AuthMe/AuthMeReloaded/wiki/5.2-Changelog with the most important features (hopefully).
