### ISSUE TITLE
authme 5.2 #586 join bug

### ISSUE THREAD

**Issue by ziutekkk** [Xephi/AuthMeReloaded#386]
Hello
When players try to join server on newest authme build, they are not allowed to and this error in console appears.
http://pastebin.com/tviHvRZZ
Everything was fine on authme 5.1

Im using:
newest spigot
authme #586
offline mode server

Please look at that.
Thanks

**Comment by Xephi** [comment]
Can you please try with build 617 ? http://ci.xephi.fr/job/AuthMeReloaded-Dev/617/

**Comment by ziutekkk** [comment]
It is ok now,
Thank you :)

**Comment by Xephi** [comment]
You're welcome ;)
