### ISSUE TITLE
Error cant use mysql 000webhost incorrent?

### ISSUE THREAD

**Issue by Warfacenl** [Xephi/AuthMeReloaded#387]
What am i doing wrong here? using wordpress

DataSource:
  mySQLColumnName: user_login
  mySQLTablename: wp_users
  mySQLUsername: a6995701_user
  backend: mysql
  mySQLColumnLastLogin: last_login
  mySQLDatabase: a6995701_databasename
  mySQLPort: '3306'
  mySQLColumnIp: ip
  mySQLHost: mysql**.000webhost.com
  mySQLColumnPassword: user_pass
  mySQLPassword: password
  caching: true
  mySQLlastlocX: x
  mySQLlastlocY: y
  mySQLlastlocZ: z
  mySQLlastlocWorld: world
  mySQLColumnEmail: email
  mySQLColumnId: ID
  mySQLColumnLogged: is_Logged
GroupOptions:
  UnregisteredPlayerGroup: ''
  RegisteredPlayerGroup: ''
  Permissions:
    PermissionsOnJoin: []
settings:
  sessions:
    enabled: false
    timeout: 10
    sessionExpireOnIpChange: false
  restrictions:
    allowChat: false
    allowCommands:
    - /login
    - /register
    - /l
    - /reg
    - /passpartu
    - /email
    - /captcha
    maxRegPerIp: 1
    maxNicknameLength: 20
    ForceSingleSession: true
    ForceSpawnLocOnJoinEnabled: false
    SaveQuitLocation: false
    AllowRestrictedUser: false
    AllowedRestrictedUser:
    - playername;127.0.0.1
    kickNonRegistered: false
    kickOnWrongPassword: false
    teleportUnAuthedToSpawn: false
    minNicknameLength: 3
    allowMovement: false
    timeout: 30
    allowedNicknameCharacters: '[a-zA-Z0-9_]*'
    allowedMovementRadius: 100
    enablePasswordVerifier: true
    ProtectInventoryBeforeLogIn: true
    displayOtherAccounts: true
    ForceSpawnOnTheseWorlds:
    - world
    - world_nether
    - world_the_end
    banUnsafedIP: false
    spawnPriority: authme,essentials,multiverse,default
    maxLoginPerIp: 0
    maxJoinPerIp: 0
    noTeleport: false
    allowedPasswordCharacters: '[\x21-\x7E]*'
  GameMode:
    ForceSurvivalMode: false
    ResetInventoryIfCreative: false
    ForceOnlyAfterLogin: false
  security:
    minPasswordLength: 4
    unLoggedinGroup: unLoggedinGroup
    passwordHash: WORDPRESS
    doubleMD5SaltLength: 8
    supportOldPasswordHash: false
    unsafePasswords: []
  registration:
    enabled: true
    messageInterval: 5
    force: true
    enableEmailRegistrationSystem: false
    doubleEmailCheck: false
    forceKickAfterRegister: false
    forceLoginAfterRegister: false
  unrestrictions:
    UnrestrictedName: []
  messagesLanguage: en
  forceCommands: []
  forceCommandsAsConsole: []
  forceRegisterCommands: []
  forceRegisterCommandsAsConsole: []
  useWelcomeMessage: true
  broadcastWelcomeMessage: false
  delayJoinMessage: false
  applyBlindEffect: false
ExternalBoardOptions:
  mySQLColumnSalt: ''
  mySQLColumnGroup: ''
  nonActivedUserGroup: -1
  mySQLOtherUsernameColumns: []
  bCryptLog2Round: 10
  phpbbTablePrefix: phpbb_
  phpbbActivatedGroupId: 2
  wordpressTablePrefix: wp_
permission:
  EnablePermissionCheck: false
BackupSystem:
  ActivateBackup: false
  OnServerStart: false
  OnServerStop: true
  MysqlWindowsPath: C:\\Program Files\\MySQL\\MySQL Server 5.1\\
Passpartu:
  enablePasspartu: false
Security:
  SQLProblem:
    stopServer: true
  ReloadCommand:
    useReloadCommandSupport: true
  console:
    noConsoleSpam: false
    removePassword: true
  captcha:
    useCaptcha: false
    maxLoginTry: 5
    captchaLength: 5
Converter:
  Rakamak:
    fileName: users.rak
    useIP: false
    ipFileName: UsersIp.rak
  CrazyLogin:
    fileName: accounts.db
Email:
  mailSMTP: smtp.gmail.com
  mailPort: 465
  mailAccount: ''
  mailPassword: ''
  mailSenderName: ''
  RecoveryPasswordLength: 8
  mailSubject: Your new AuthMe Password
  mailText: 'Dear <playername>, <br /><br /> This is your new AuthMe password for
    the server <br /><br /> <servername> : <br /><br /> <generatedpass><br /><br />Do
    not forget to change password after login! <br /> /changepassword <generatedpass>
    newPassword'
  maxRegPerEmail: 1
  recallPlayers: false
  delayRecall: 5
  emailBlacklisted:
  - 10minutemail.com
  emailWhitelisted: []
  generateImage: true
Hooks:
  multiverse: true
  chestshop: true
  bungeecord: false
  disableSocialSpy: true
  useEssentialsMotd: false
  customAttributes: false
Performances: {}
Purge:
  useAutoPurge: false
  daysBeforeRemovePlayer: 60
  removePlayerDat: false
  removeEssentialsFile: false
  defaultWorld: world
  removeLimitedCreativesInventories: false
  removeAntiXRayFile: false
  removePermissions: false
Protection:
  enableProtection: false
  countries:
  - US
  - GB
  countriesBlacklist:
  - A1
  enableAntiBot: false
  antiBotSensibility: 5
  antiBotDuration: 10
VeryGames:
  enableIpCheck: false

**Comment by sgdc3** [comment]
why mysql*.000host.com with the "*"?

**Comment by sgdc3** [comment]
@Warfacenl

**Comment by Warfacenl** [comment]
Ooh not all ppl from here needs that number ;) @sgdc3

**Comment by sgdc3** [comment]
i can't understand your issue

**Comment by sgdc3** [comment]
what happens in console on start?

**Comment by sgdc3** [comment]
https://www.000webhost.com/faq.php?ID=27

**Comment by sgdc3** [comment]
@Warfacenl

**Comment by Warfacenl** [comment]
I use a minecraft webhosting not in my home network?

I am trying to connect authme to my webhosting databse and im sure i have the authme config good with the 000webhosting data. 


29.12 03:40:24 [Server] INFO ConnectionPool was unavailable... Reconnected!
29.12 03:38:17 [Server] INFO Connection pool ready
29.12 03:38:17 [Server] INFO MySQL driver loaded
29.12 03:38:16 [Server] INFO Set Language: en
29.12 03:38:16 [Server] INFO Loading Configuration File...
29.12 03:38:16 [Server] INFO Enabling AuthMe v${version}
29.12 03:38:16 [Server] INFO WEPIF: Using the Bukkit Permissions API.
29.12 03:38:16 [Server] INFO Enabling WorldEdit v5.6.3
29.12 03:38:16 [Server] INFO Enabling RKMP v1.0
29.12 03:38:16 [Server] INFO Preparing start region for level 1 (Seed: -1989843230815396969)
29.12 03:38:16 [Server] INFO Preparing start region for level 0 (Seed: -1989843230815396969)
29.12 03:38:16 [Server] INFO Preparing level "world"
29.12 03:38:16 [Server] INFO Loading PlotManager v2.0
29.12 03:38:16 [Server] INFO Loading WorldGuard v6.1
29.12 03:38:16 [Server] INFO Loading AuthMe v${version}
29.12 03:38:16 [Server] INFO Loading WorldEdit v5.6.3
29.12 03:38:16 [Server] INFO Loading RKMP v1.0
29.12 03:38:16 [Server] INFO This server is running CraftBukkit version git-Bukkit-d27e6d0 (MC: 1.8.7)

**Comment by sgdc3** [comment]
Look at the link I posted.

**Comment by Warfacenl** [comment]
otherwise if that problem counts out of network to with mysql connection, than i need to look for an other webhost :)

**Comment by sgdc3** [comment]
yeah, 000webhost's free plan doesn't provide remote mysql access
