### ISSUE TITLE
Authme location bug

### ISSUE THREAD

**Issue by eero619** [Xephi/AuthMeReloaded#388]
Authme location bug. Happend when i restarted server. 1.5 version. Some users are bugged. some are not.
my config:
DataSource:
  mySQLColumnName: username
  mySQLTablename: authme
  mySQLUsername: authme
  backend: sqlite
  mySQLColumnLastLogin: lastlogin
  mySQLDatabase: authme
  mySQLPort: '3306'
  mySQLColumnIp: ip
  mySQLHost: 127.0.0.1
  mySQLColumnPassword: password
  mySQLPassword: '12345'
  caching: true
  mySQLlastlocX: x
  mySQLlastlocY: y
  mySQLlastlocZ: z
  mySQLlastlocWorld: world
  mySQLColumnEmail: email
  mySQLColumnId: id
  mySQLColumnLogged: isLogged
GroupOptions:
  UnregisteredPlayerGroup: ''
  RegisteredPlayerGroup: ''
  Permissions:
    PermissionsOnJoin: []
settings:
  sessions:
    enabled: false
    timeout: 10
    sessionExpireOnIpChange: false
  restrictions:
    allowChat: false
    allowCommands:
    - /login
    - /register
    - /l
    - /reg
    - /passpartu
    - /email
    - /captcha
    maxRegPerIp: 1
    maxNicknameLength: 20
    ForceSingleSession: false
    ForceSpawnLocOnJoinEnabled: false
    SaveQuitLocation: true
    AllowRestrictedUser: false
    AllowedRestrictedUser:
    - playername;127.0.0.1
    kickNonRegistered: false
    kickOnWrongPassword: false
    teleportUnAuthedToSpawn: false
    minNicknameLength: 3
    allowMovement: true
    timeout: 30
    allowedNicknameCharacters: '[a-zA-Z0-9_]*'
    allowedMovementRadius: 15
    enablePasswordVerifier: true
    ProtectInventoryBeforeLogIn: true
    displayOtherAccounts: true
    ForceSpawnOnTheseWorlds:
    - world
    - world_nether
    - world_the_end
    banUnsafedIP: false
    spawnPriority: authme,essentials,multiverse,default
    maxLoginPerIp: 0
    maxJoinPerIp: 0
    noTeleport: false
    allowedPasswordCharacters: '[\x21-\x7E]*'
  GameMode:
    ForceSurvivalMode: false
    ResetInventoryIfCreative: false
    ForceOnlyAfterLogin: false
  security:
    minPasswordLength: 4
    unLoggedinGroup: unLoggedinGroup
    passwordHash: SHA256
    doubleMD5SaltLength: 8
    supportOldPasswordHash: false
    unsafePasswords: []
  registration:
    enabled: true
    messageInterval: 5
    force: true
    enableEmailRegistrationSystem: false
    doubleEmailCheck: false
    forceKickAfterRegister: false
    forceLoginAfterRegister: false
  unrestrictions:
    UnrestrictedName: []
  messagesLanguage: en
  forceCommands: []
  forceCommandsAsConsole: []
  forceRegisterCommands: []
  forceRegisterCommandsAsConsole: []
  useWelcomeMessage: true
  broadcastWelcomeMessage: false
  delayJoinMessage: false
  applyBlindEffect: false
ExternalBoardOptions:
  mySQLColumnSalt: ''
  mySQLColumnGroup: ''
  nonActivedUserGroup: -1
  mySQLOtherUsernameColumns: []
  bCryptLog2Round: 10
  phpbbTablePrefix: phpbb_
  phpbbActivatedGroupId: 2
  wordpressTablePrefix: wp_
permission:
  EnablePermissionCheck: false
BackupSystem:
  ActivateBackup: false
  OnServerStart: false
  OnServerStop: true
  MysqlWindowsPath: C:\\Program Files\\MySQL\\MySQL Server 5.1\\
Passpartu:
  enablePasspartu: false
Security:
  SQLProblem:
    stopServer: true
  ReloadCommand:
    useReloadCommandSupport: true
  console:
    noConsoleSpam: false
    removePassword: true
  captcha:
    useCaptcha: false
    maxLoginTry: 5
    captchaLength: 5
Converter:
  Rakamak:
    fileName: users.rak
    useIP: false
    ipFileName: UsersIp.rak
  CrazyLogin:
    fileName: accounts.db
Email:
  mailSMTP: smtp.gmail.com
  mailPort: 465
  mailAccount: ''
  mailPassword: ''
  mailSenderName: ''
  RecoveryPasswordLength: 8
  mailSubject: Your new AuthMe Password
  mailText: 'Dear <playername>, <br /><br /> This is your new AuthMe password for
    the server <br /><br /> <servername> : <br /><br /> <generatedpass><br /><br />Do
    not forget to change password after login! <br /> /changepassword <generatedpass>
    newPassword'
  maxRegPerEmail: 1
  recallPlayers: false
  delayRecall: 5
  emailBlacklisted:
  - 10minutemail.com
  emailWhitelisted: []
  generateImage: true
Hooks:
  multiverse: true
  chestshop: true
  bungeecord: false
  disableSocialSpy: true
  useEssentialsMotd: false
  customAttributes: false
Performances: {}
Purge:
  useAutoPurge: false
  daysBeforeRemovePlayer: 60
  removePlayerDat: false
  removeEssentialsFile: false
  defaultWorld: world
  removeLimitedCreativesInventories: false
  removeAntiXRayFile: false
  removePermissions: false
Protection:
  enableProtection: false
  countries:
  - US
  - GB
  countriesBlacklist:
  - A1
  enableAntiBot: false
  antiBotSensibility: 5
  antiBotDuration: 10
VeryGames:
  enableIpCheck: false

It always sets me to location where i logged off 3-4 days ago some others aswell.
server hasnt installed mysql or sql just flat file i think.

**Comment by sgdc3** [comment]
try to purge your last location with this command: /authme resetpos yourname

**Comment by eero619** [comment]
/authme purgelastpos name worked for me ty !

**Comment by sgdc3** [comment]
if you use /authme purgelastpos * it should remove it for EVERYONE!!! (use it only if you don't mind about last pos of players)

**Comment by ljacqu** [comment]
@eero619 Am I right to assume that we can close this issue? Or is there still something pending on our side? :)

**Comment by sgdc3** [comment]
@ljacqu we need to fix this issue with last location first

**Comment by ljacqu** [comment]
Hopefully done with #408. I should have mentioned

**Comment by eero619** [comment]
There is still a problem i tried this : 
Hopefully done with #408. I should have mentioned
and it was ok until no permssions worked only * perm worked. so please fix
i am using pex

**Comment by ljacqu** [comment]
Are you using the most recent perm nodes? They've changed from 5.0 to 5.2:

https://github.com/AuthMe-Team/AuthMeReloaded/blob/master/src/tools/docs/permission_nodes.md

**Comment by sgdc3** [comment]
No answer
