### ISSUE TITLE
Latest Github compilation is totally broken

### ISSUE THREAD

**Issue by Kongolan** [Xephi/AuthMeReloaded#39]
I just compiled your new code and finally everyone can login without being asked for any password! The plugin loads without any errors or such, but it seems like the storage backend is fully broken. Also /register has an internal problem for what ever reason.

I really need a quick fix for this, people are taking over Staff accounts already....

**Comment by Trojaner25** [comment]
You should try to downgrade, also posting the error logs would be helpful...

**Comment by Kongolan** [comment]
There are no error logs at all... Which is the interesting part about it. Seems like the flat file just isn't read or loaded.

The latest dev build doesn't have the attribute fix in it and either has my 2 suggest fixes which are essential for forceRegister = false. So i actually run my patched version for over 2 years now, but i just updated my full ressource, when those fixes were made.

**Comment by Trojaner25** [comment]
Maybe its related to #34

**Comment by Xephi** [comment]
Fixed? :/

**Comment by Kongolan** [comment]
Yes already on last commits.
