### ISSUE TITLE
Block TAB auto completion for unlogged players

### ISSUE THREAD

**Issue by DardBrinza** [Xephi/AuthMeReloaded#390]
Can you add a feature to block the use of the TAB key to authorization , as is done in the plugin AntiTAB. Someone may try to login as admin , and without entering a password , press / <TAB> and get a list of plugins. Thanks :)

**Comment by Xephi** [comment]
https://www.spigotmc.org/wiki/spigot-configuration/
You can set the autocomplete as -1 to prevent it

**Comment by Xephi** [comment]
AuthMe-Team/AuthMeReloaded@edffae3

**Comment by Xephi** [comment]
Can you try the latest dev build please ?

**Comment by DardBrinza** [comment]
Great work. Thank. Closed.
