### ISSUE TITLE
[Dev] Discussion: config.yml and comments

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#393]
addressing @Xephi @sgdc3 @DNx5 @games647 @MithrandirCraft & anyone else interested. (This relates to #347 but there's so much going on in there I'd like to create a new issue for discussion.)

The current problem we have is that we save config.yml whenever we detect missing or deprecated properties. When saving to config.yml, we lose all comments. We'd like to address that.

Possibility A (what we currently do): save to config.yml when necessary and lose all comments.

Possibility B (on the 347 branch): annotate the configuration fields with the comments that should go in config.yml. When we need to save to config.yml, fetch the comments of the fields and write them along with the values.

Possibility C (my proposition): Essentials-style – never write to config.yml. 
- We have default values if a property is missing. 
- We can still move properties to a new file (like the email stuff): simply copy the values to a separate file without removing them from config.yml. 
- We can always log warnings for obsolete/missing properties. 
- We could even have an `/authme validateconfig` command that can tell a user the properties that are missing or deprecated.
- We have a breaking changes Wiki page, so we keep track of any new settings and can list them with a new release of AuthMe

Essentials uses an upgrades-done.yml file that keeps track of the upgrades it has done (e.g. moving configs to a separate file). It's a technical file, so this file can be written to and it shouldn't matter to the end user. (Ref: [Settings.java](https://github.com/essentials/Essentials/blob/d36d80933f8f672cd8bb0f210adc23aac10850ea/Essentials/src/com/earth2me/essentials/Settings.java), [EssentialsUpgrade.java](https://github.com/essentials/Essentials/blob/d36d80933f8f672cd8bb0f210adc23aac10850ea/Essentials/src/com/earth2me/essentials/EssentialsUpgrade.java))

Advantage of this? We don't implement our own YAML writer or reader (bad idea), and a user can edit his config file with personal comments without losing them.

Thoughts on this? @MithrandirCraft What is best for the typical plugin user?, what would he expect?

**Comment by DardBrinza** [comment]
Like

**Comment by games647** [comment]
In my opinion B is the best solution, but it's a lot of work to implement it. So I would rather choose C and then notify our users if there some changes made to the config. If we use possibility A, we lose all the comments which are in my opinion very helpful.

**Comment by ljacqu** [comment]
Note that with B we will always write our default comments. If you think that's OK, we can probably swing that.

**Comment by sgdc3** [comment]
Nope, i prefer to remove the merge feature

**Comment by sgdc3** [comment]
Method C will only create confusion...

**Comment by ljacqu** [comment]
@sgdc3 What merge feature do you mean? Can you elaborate on the confusion?

**Comment by Xephi** [comment]
I've already begin the B choice and i will finish it soonly, by the way i think it's the better and easier way to do this ^^'

**Comment by ljacqu** [comment]
Why do you think it would be easier? Why do you think it's better? I'm trying to gather thoughts here

**Comment by DNx5** [comment]
B is good, looks like Yamler. User should not put personal comments in config.yml , only able to edit the value.

**Comment by ljacqu** [comment]
B it is. Thanks for the comments!

**Comment by DNx5** [comment]
how about creating our own template processor for snakeyaml?

**Comment by ljacqu** [comment]
@DNx5 That's a difficult thing to do. If you would be willing to write one, then it could be an option to explore; you're a good coder. I don't think it's a good idea if someone else does it.

**Comment by DNx5** [comment]
ah :smile: nevermind, I'm not a good coder. Also, I see B is already in progress.
maybe I can help.
