### ISSUE TITLE
Recover password e-mail bug

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#394]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/12071215/fc0b2730-b09f-11e5-921a-21f4fd5091cc.PNG)

**Comment by sgdc3** [comment]
you need to use <playername /> format not the %playername% one

**Comment by ljacqu** [comment]
Also, there is still one tag in the email.html file in our repo that uses the `%` format

**Comment by sgdc3** [comment]
ok, can you fix it?

**Comment by ljacqu** [comment]
Not right now.

**Comment by andris155** [comment]
<playername /> works thanks! :)

**Comment by ljacqu** [comment]
Btw, my bad, all tags are fine in the file. I must have looked at an old diff sometime
