### ISSUE TITLE
Email command generates exception

### ISSUE THREAD

**Issue by ArcasCZ** [Xephi/AuthMeReloaded#396]
When I try to use /email recover (mail) command, I get this error:

[20:43:15 WARN]: org.apache.commons.mail.EmailException: Invalid message supplied
>       at org.apache.commons.mail.HtmlEmail.setHtmlMsg(HtmlEmail.java:151)
>       at fr.xephi.authme.SendMailSSL$1.run(SendMailSSL.java:84)
>       at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
>       at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
>       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>       at java.lang.Thread.run(Thread.java:745)
>

I'm using latest AuthMe.

**Comment by Xephi** [comment]
can you send your email.html file please?

**Comment by ArcasCZ** [comment]
It didn't create any email.html...

**Comment by Xephi** [comment]
Huum, what's your actual build please?

**Comment by ArcasCZ** [comment]
Latest.

**Comment by sgdc3** [comment]
With latest build we mean this: http://ci.xephi.fr/job/AuthMeReloaded-Dev/
NOT THIS: http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by ArcasCZ** [comment]
http://pastebin.com/dJEbVWNt

DB login information are hidden.

**Comment by sgdc3** [comment]
download build number 654

**Comment by ArcasCZ** [comment]
All works now. Please, fix that missleading link. Thanks :-)
