### ISSUE TITLE
Microlag on player join

### ISSUE THREAD

**Issue by ArcasCZ** [Xephi/AuthMeReloaded#397]
Hello there!

When player joins, whole server got microlag for 3-4 seconds. Plugins doesn't react, tile entities stop working. After 4 secs all works fine. It doesn't happens all time, but it happens.

I'm running latest version of AuthMe and KCauldron.

**Comment by DNx5** [comment]
what is your ``` /authme version ``` ?

**Comment by ArcasCZ** [comment]
AuthMeReloaded v5.2-SNAPSHOT (build: 186)

**Comment by sgdc3** [comment]
can you post your config?

**Comment by DNx5** [comment]
Well, that's not a dev build.

**Comment by DNx5** [comment]
Well, that's not dev build.

**Comment by ArcasCZ** [comment]
Meh, maybe someone have to fix that link in readme ;)

**Comment by ljacqu** [comment]
I agree with ArcasCZ, "latest build" is misleading/ambiguous for users

**Comment by DNx5** [comment]
http://ci.xephi.fr/job/AuthMeReloaded-Dev/

**Comment by ArcasCZ** [comment]
All seems working :-)
