### ISSUE TITLE
Email added whenever player joins server

### ISSUE THREAD

**Issue by ArcasCZ** [Xephi/AuthMeReloaded#399]
Hello there!

I'm (finally) using latest version of AuthMe (b654) and I have a little bit problem.

When player joins server, after login AuthMe sends to player MSG email_added, but player has no added email. Then server (correctly) sends message add_email.

What is wrong?

**Comment by sgdc3** [comment]
@Xephi

**Comment by ArcasCZ** [comment]
When it will be fixed?

**Comment by sgdc3** [comment]
@ArcasCZ what's your buildnumber?

**Comment by ArcasCZ** [comment]
IDK now. I just want to know if there is reason to update :D

**Comment by sgdc3** [comment]
...

**Comment by sgdc3** [comment]
@ArcasCZ should have been fixed

**Comment by ArcasCZ** [comment]
We are working on WIPE for server. I'll let you know after all be done and players will be moved to new server.

**Comment by ljacqu** [comment]
@ArcasCZ Thanks!

**Comment by ljacqu** [comment]
@ArcasCZ Maybe now some news? Is this solved? :)

**Comment by ArcasCZ** [comment]
Seems working. Thanks alot!
