### ISSUE TITLE
Passwords lost on restart

### ISSUE THREAD

**Issue by Qballl** [Xephi/AuthMeReloaded#40]
Ok I dont have a console log as there appears to be no errors. The problem I have is everytime I restart my server it seems the passwords are lost with the newest snapshot 5.0 whatever. Can you help?

**Comment by Trojaner25** [comment]
Does a reconnect of the player fix that problem?

**Comment by Qballl** [comment]
yes

On Tue, May 26, 2015 at 2:46 PM, Trojaner <notifications@github.com> wrote:

> Does a reconnect of the player fix that problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Xephi/AuthMeReloaded/issues/40#issuecomment-105645408>
> .
>



-- 
Qvanbooven513

**Comment by iBars** [comment]
The same! Anyone has 3.5 sources?

**Comment by Qballl** [comment]
Update Im using it still and it is now working fine but it may be just like the #43 but Ive not tested it yet

**Comment by Xephi** [comment]
Seems to be fixed : https://github.com/Xephi/AuthMeReloaded/commit/b75adf6a981e68d350ee6d5d6056f023f217c290
If you can test :)
