### ISSUE TITLE
Abnormal ammount of registred users with localhost IP

### ISSUE THREAD

**Issue by MithrandirCraft** [Xephi/AuthMeReloaded#400]
My team has recently noticed an abnormal ammount of players with IP 127.0.0.1 (default localhost IP) attributed to their names on the Authme mySQL tables.
(Yes I do have a team which notices these things huh e_e, we're professionals after all.)

The ammount of players registred with these IP's is growing every day :/

-------------------------
Spigot version: 1.8.8
Authme version: 5.2-SNAPSHOT-b596

**Comment by ljacqu** [comment]
If I recall correctly, you're on VeryGames, right? So do you have `VeryGames.enableIpCheck` set to `true` in your config.yml?

Are there still new registrations (say, since Dec 30th) that are _not_ with the IP address 127.0.0.1?

**Comment by DNx5** [comment]
default ip for PlayerAuth object is ``` 127.0.0.1 ``` :open_mouth:

**Comment by MithrandirCraft** [comment]
@ljacqu I imagined that could have something to do. I just disabled that function before the last restart (1h ago)

I'm checking right now if this volume of registred players with "127.0.0.1" may actually be the whole volume of recently registred players.

**Comment by ljacqu** [comment]
@MithrandirCraft  Thanks, that will provide us some insight as for what is causing this :)

**Comment by MithrandirCraft** [comment]
@ljacqu No, it's not everyone who registred since Dec 30. It's a bunch of random people, and the volume grows every now and then, I would say there's around 40 player names (I haven't really counted them).

If you think the verygames function may have something to do, this issue may now be prevented.

**Comment by ljacqu** [comment]
@MithrandirCraft Thanks for the info. It will be interesting to know if this no longer happens without the very games function.

From an analytical point of view, the fact that not everyone has 127.0.0.1 as IP address can mean one of two things:
- The users with 127.0.0.1 are the users who registered and never came back, or they are the ones who registered and logged back in later—i.e., our registration process or something else is bugged, but not both. I checked registration process and it should be working properly. I'll look at other places where the IP address is updated.
- The VeryGames API sometimes returns this IP as default (service overloaded? do we talk to the API in a wrong way, e.g. with characters in the username it doesn't expect?)

**Comment by MithrandirCraft** [comment]
@ljacqu Understood. My webmaster has this IP, and he's pretty active (It's definetly not his real IP xD)

**Comment by DNx5** [comment]
@ljacqu If your webmaster registered by ``` /authme register ``` he will have that IP.

**Comment by DNx5** [comment]
^ I just realized I tagged the wrong person :laughing: 
that shoul go for @MithrandirCraft

**Comment by MithrandirCraft** [comment]
@DNx5 I still saw it though :P

In any case, I don't think I registred my webmaster through that command.

Looks like the ammount of accounts with 127.0.0.1 attributed to them is being reduced since I disactivated the verygames function.
I would call this verygames's fault, and close this ticket untill the likelyhood of any further issues re-emerging.
