### ISSUE TITLE
Add API Actions on Register

### ISSUE THREAD

**Issue by GabrielTK** [Xephi/AuthMeReloaded#405]
For Example, i would like to use this: https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#Add-Single-Recipient-POST

**Comment by sgdc3** [comment]
? what do you mean?

**Comment by ljacqu** [comment]
That's a REST API over HTTP. That would be a whole other module. We do have a NewAPI.java class for other plugins to talk with us, though.

**Comment by DNx5** [comment]
Looks like email sending service.
@GeARCraft1 you could create a plugin and listen at AuthMe register event.

**Comment by GeARCraft1** [comment]
But how i do this?? (Sorry, i`m very noob, but at least i know the plugin structure, so i just need to know how to listen for the event and get the player name and e-mail)

**Comment by ljacqu** [comment]
Idea for this: create a small 2 class plugin in the samples folder that listens to AuthMe events and for example, messages all occurring events to a configured player. And rejects the login of all caps players, or something along those lines. Just simple demo stuff

**Comment by ljacqu** [comment]
@GabrielTK If this is still relevant, I've actually created a small demo plugin that hooks into AuthMe. https://github.com/ljacqu/AuthMe_integration_demo
