### ISSUE TITLE
/authme unregister name sometimes not work.

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#406]

**Comment by sgdc3** [comment]
Can you provide more infos?

**Comment by andris155** [comment]
https://www.youtube.com/watch?v=2o-U1BjsbeA&feature=youtu.be

**Comment by sgdc3** [comment]
Are you using latest dev build?

**Comment by andris155** [comment]
AuthMeReloaded v5.2-SNAPSHOT (build: 659)

**Comment by sgdc3** [comment]
@DNx5 can you look at this?

**Comment by DNx5** [comment]
Not now, too lazy to open the IDE on my slow pc. :penguin:

**Comment by sgdc3** [comment]
lol

**Comment by sgdc3** [comment]
@DNx5 now? xD

**Comment by DNx5** [comment]
is this problem still happen on build 825+ ?

**Comment by sgdc3** [comment]
@andris155

**Comment by andris155** [comment]
I don't use latest dev AuthMe version.
https://github.com/Xephi/AuthMeReloaded/issues/557

**Comment by sgdc3** [comment]
Why?

**Comment by andris155** [comment]
AuthMe latest dev. build not support AuthMeBridge in my Bungeecord server.

**Comment by andris155** [comment]
I started testing latest dev build. Bug fixed.

**Comment by sgdc3** [comment]
Thank you ;)
