### ISSUE TITLE
Players are able to bypass server user limit

### ISSUE THREAD

**Issue by Eisenbahn** [Xephi/AuthMeReloaded#407]
For some reason, it started happening after i got 5.2 snapshop (b185)

It stats fine. A player tries to login when its full, and it says its full and stuff. But for some reason, the plugin start ignoring this and anyone can join after this. :c 

Java 7
Linux
Cauldron
Mine 1.7.10

[]'s !

**Comment by Eisenbahn** [comment]
I've noticed after a restart, works until i do /authme reload. I gotta confirm this.

**Comment by sgdc3** [comment]
Only after an authme reload, right?

**Comment by Eisenbahn** [comment]
Ok. Not confirmed. Havent perform a reload and there are common players bypassing.
(Vips got essentials bypass permission). 
Maybe permission issue?

**Comment by Eisenbahn** [comment]
This very weird. It blocks, then suddenly, it doesnt. Maybe a new player joining triggers it?

**Comment by sgdc3** [comment]
I still can't understand you issue

**Comment by Eisenbahn** [comment]
Well. Server's player limit is 70. (But Vips has a permission, from essentials plugin, that allows them to bypass this limit. But ONLY VIPS)
For some reason, after i updated to 5.2 b185, ANY player can bypass this limit.
For some reason, when it reachs 70/70 and another player tries to join, it returns 'server full bla bla bla'.
But after some time, it doesnt return anything and any player can bypass this limit.
I had 86/70 players yesterday :(

[]'s

**Comment by sgdc3** [comment]
Ok, understood

**Comment by Eisenbahn** [comment]
Oh, god. I guess i cant use the 3.5 Snapshot again :'(
When i enter a command it just returns the same the command.

**Comment by Eisenbahn** [comment]
http://pastebin.com/8ABnsHLM

**Comment by ljacqu** [comment]
What command?

**Comment by Eisenbahn** [comment]
Any command. /login, /logout /changepassword. The log is on the ling above.
[]'s

**Comment by Eisenbahn** [comment]
Any way i could tempfix this? Or a way i could use the old version? (5.0)

**Comment by ljacqu** [comment]
By the way, looks like that was 3.5:
> Error occurred while enabling AuthMe v3.5-SNAPSHOT

I haven't worked on the code back in 3.5 so I have no idea what changed. But from the error I would guess that the database structure may have changed, which would not be easy to tempfix.

**Comment by Eisenbahn** [comment]
Oh. You are 100% right :c . My mistake. But again i tried 5.0:
http://pastebin.com/pBgKRvf2

**Comment by Eisenbahn** [comment]
Thank you guys for answering so quickly. :)

**Comment by DNx5** [comment]
by the way, 5.0 contains a lot of bugs and performance problem. like inventory wipe, mysql lag, etc.
I recommend you to stick at last dev build

**Comment by Eisenbahn** [comment]
I'll anyway. But im getting like 100 players in a modded server and its lagging the crap of it :C hahaha

Any way to force the limit? A plugin maybe?

**Comment by DNx5** [comment]
are your players have ``` authme.player.vip ``` ?

**Comment by Eisenbahn** [comment]
They probably has authme.player.* . But had in the 5.0. Is it new in 5.2?
I'll check it. But im almost sure i tried it.

**Comment by DNx5** [comment]
see this,
https://github.com/AuthMe-Team/AuthMeReloaded/blob/master/src/tools/docs/permission_nodes.md

**Comment by Eisenbahn** [comment]
Mhm. So. ive added a "-authme.player.vip" and still happening. :(

**Comment by Eisenbahn** [comment]
As i explained above. Sometimes it works just fine, but 90% of the time, it just ignores the limit =/

**Comment by DNx5** [comment]
yeah, its happen because player has vip permissions :laughing:

**Comment by Eisenbahn** [comment]
Hm.. only vip has. And any player is joining :(
It were alright before 5.2. So i guess is a small glitch

**Comment by DNx5** [comment]
if you give players ``` authme.player.* ``` permission. that mean you give them ``` authme.player.vip ``` too.

**Comment by Eisenbahn** [comment]
Okay. I'll try removing this node. I tought adding a - before a node, it added an exception.

**Comment by DNx5** [comment]
well, authme seems broken with ``` * ``` node. What do you think @ljacqu ?
@Eisenbahn 
could you try this build?
http://ci.xephi.fr/job/AuthMeReloaded/661/

**Comment by Eisenbahn** [comment]
Will do.

**Comment by Eisenbahn** [comment]
Ok. Removing the authme.player.*, adding authme.player.login, logout and authme.player.register. now returns the vanilla 'full' message ("Server is Full !").

I'll keep my eyes on it, But seems to be fine again. (Still using the 5.2 b185)

**Comment by Eisenbahn** [comment]
I'll let ya know if still bypassing. Thank you for all your patiece, guys. Keep the good work :)

**Comment by DNx5** [comment]
You can close this if there is no problem left.

**Comment by Eisenbahn** [comment]
Okay. Closing. []'s

**Comment by ljacqu** [comment]
@DNx5 Great analysis! How is the `*` node broken? Currently player.vip falls under player.* so it will be granted. Once we use the reworked perms by @sgdc3 this will no longer be the case

**Comment by ljacqu** [comment]
I had a look at the commits again, and I guess that player.* is still allowing player.vip (as it should currently)? From what I can tell (reading on a phone) the changes look good

**Comment by DNx5** [comment]
I mean, the exclude thing.
something like,
```
authme.player.*
-authme.player.vip
```

**Comment by ljacqu** [comment]
Once we use @sgdc3's newPlugin setup we won't have this problem anymore :)
