### ISSUE TITLE
Player's logout positon freeze after plugin update

### ISSUE THREAD

**Issue by prozhong** [Xephi/AuthMeReloaded#408]
I updated my authme from 5.0 to 5.2#657.
http://ci.xephi.fr/job/AuthMeReloaded/657/

Now wherever you logout and disconnect, you will be teleported to one fixed location (saved in mysql before update)

seems the 5.2 update caused mySQLlastloc wont be saved ?

Here is some config related:

  backend: mysql
  caching: true
  mySQLColumnId: id
  mySQLColumnName: username
  mySQLColumnPassword: password
  mySQLColumnEmail: email
  mySQLColumnLogged: isLogged
  mySQLColumnIp: ip
  mySQLColumnLastLogin: lastlogin
  mySQLlastlocX: x
  mySQLlastlocY: y
  mySQLlastlocZ: z
  mySQLlastlocWorld: world
  mySQLRealName: realname
  mySQLWebsite: false
  mySQLMaxConections: 25

    ForceSingleSession: true
    ForceSpawnLocOnJoinEnabled: false
    SaveQuitLocation: true
    AllowRestrictedUser: false
    AllowedRestrictedUser:
    - playername;127.0.0.1
    kickNonRegistered: false
    kickOnWrongPassword: true
    teleportUnAuthedToSpawn: true

**Comment by ljacqu** [comment]
I think I've found the issue—please try with the latest dev build (nr. 660 or upwards)
http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by prozhong** [comment]
fixed confirmed
