### ISSUE TITLE
AuthMe v5 allow use commands

### ISSUE THREAD

**Issue by k3ldon** [Xephi/AuthMeReloaded#41]
the latest authme allow any commands before /register or /login

=/

**Comment by Trojaner25** [comment]
Can't confirm this on the latest dev build...

**Comment by Xephi** [comment]
Have tested and i can't :o

**Comment by k3ldon** [comment]
mmm maybe is only with bungeecord...
i can use /server skyblock without login

**Comment by Xephi** [comment]
Cause Bungeecord command don't depand of bukkit api , it seems to be catch before the call of the event

Xephi
