### ISSUE TITLE
A fix for #348 by deleting all last player locations

### ISSUE THREAD

**Issue by MithrandirCraft** [Xephi/AuthMeReloaded#410]
In reference to:
https://github.com/Xephi/AuthMeReloaded/issues/348

@sgdc3 Gave me a command: /purgelastloc *
He said it might help with purging the logout location of all players, and therefore might fix #348

The problem is that purgelastloc isn't an existing command. 
A valid command is: /purgelastpos
Yet * doesn't automatically work for all players, instead, the command tries to find the player called '*'

------------------------
Spigot version: 1.8.8
Authme version: 5.2-SNAPSHOT-b596

**Comment by ljacqu** [comment]
Are you using an older version? For me it works fine; using the latest dev build.

```
/authme purgelastpos *
[21:12:27 INFO]: All players last position locations are now reset
```

**Comment by MithrandirCraft** [comment]
I'm using b596

This link is down, so I can't get anything more recent:
http://ci.xephi.fr/job/AuthMeReloaded-Dev/596/

My case:
/authme purgelastpos *
[21:47:07 INFO]: El usuario no se encuentra en la base de datos

(user doesn't exist.)

**Comment by ljacqu** [comment]
Please use http://ci.xephi.fr/job/AuthMeReloaded/ — sgdc3 recently renamed the dev build to "AuthMeReloaded". I think if you use a more recent build version it should be included.
We can see that build nr. 586 was on Dec 25th, and Xephi added the `*` option on [Dec 28th](https://github.com/AuthMe-Team/AuthMeReloaded/commit/c94b622). So it's possible that it was _after_ build nr. 596.

Sorry for the confusion!

**Comment by MithrandirCraft** [comment]
No problem, lets hope that's the case :)

I'll be doing this asap and reporting back.

**Comment by MithrandirCraft** [comment]
reported on #348

**Comment by ljacqu** [comment]
What is still open for this issue?
