### ISSUE TITLE
WARN after server stop

### ISSUE THREAD

**Issue by prozhong** [Xephi/AuthMeReloaded#413]
http://pastebin.com/c6piN8tD
"org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled"

Using #660
http://ci.xephi.fr/job/AuthMeReloaded/660/
My config same as #408

**Comment by Xephi** [comment]
Can you please try latest build ?

**Comment by sgdc3** [comment]
@prozhong

**Comment by prozhong** [comment]
Fixed
