### ISSUE TITLE
[Dev] Clean wildcard permissions

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#414]
- Verify whether it is sufficient to define wildcard permission nodes in plugin.yml
- If so, remove the logic for wildcard nodes in the permissions manager and the permission enums

**Comment by DNx5** [comment]
It's optional to put wildcard permission in plugin.yml, but registering the permissions is required.

**Comment by DNx5** [comment]
plugin.getServer().getPluginManager().addPermission(new Permission(...));
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/permissions/Permission.html

**Comment by ljacqu** [comment]
Where do we do this in AuthMe? I'm really confused now.

**Comment by ljacqu** [comment]
https://bukkit.org/threads/permissions-faq.25080/, although dated, says:

> **Do I have to register my permissions in plugin.yml?**
No. It's entirely optional to register permissions at all. However, I recommend that you do so that you may provide a description of each permissions and set a default. Also, you can set "shortcut" permissions in plugin.yml to let people easily pick groups of similar permissions using a single node.

**Comment by DNx5** [comment]
We only check player's permission, and permissions section in plugin.yml isn't fully updated.

**Comment by DNx5** [comment]
Probably we aren't register permissions properly
http://wiki.ess3.net/wiki/Group_Manager#Permissions_Nodes
> **Summary Nodes**
Group Manager supports summary nodes, that is using a wildcard to enable all registered sub-permissions.
`essentials.*` : Allows access to every essentials command
`essentials.kits.*` : Allows access to use every kit
You can also give the '*' wildcard by itself, without specifying a plugin. This causes the specified group to have access to every command from every plugin. Note: Conflicting commands will become unstable unless negated by a negative node. Use at your own risk. Not all plugins properly register their permissions as well.

**Comment by ljacqu** [comment]
Thanks for the commit! I think we can close this.
