### ISSUE TITLE
[Dev] Rework permission nodes (newplugin.yml)

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#415]
- Review that the setup in the newplugin.yml file is satisfactory
- Replace the current plugin.yml file with it
- Add the breaking changes to the wiki page (e.g. /converter --> /authme converter)
- Update the permission enums accordingly 
- Update the command initializer accordingly
- Move the ExecutableCommand implementation(s?) to the authme package
- Run the tools tasks to create the list of permission nodes and the list of commands

Contact: @sgdc3

**Comment by ljacqu** [comment]
Adding it to the 5.2 release. If we can still fit this + the config rework into 5.2 then we'll have a nice setup and hopefully very little breaking changes in the future :)

**Comment by sgdc3** [comment]
newPlugin can be ommited if @DNx5 's one is better ;)

**Comment by ljacqu** [comment]
I think we've seen in #414 that I have no idea how permissions are defined... :P So I'll describe it on a higher level: giving `authme.player.vip` when a player has `authme.player.*` is obviously a bad idea since a plugin admin won't suspect the consequences of that, but at the same time I find it very ugly to have `authme.player.*` NOT include all `authme.player` permissions.

@sgdc3, your change solves both of these problems by renaming `authme.player.vip` to `authme.vip`. I personally think that all four permission nodes you've taken out of the `authme.player` branch make a lot of sense. What do you think, @DNx5?

Those are very little breaking changes if we just move those four. I personally also really liked your explanation for moving `/converter` to `/authme converter` but those are things you two, @sgdc3 and @DNx5, can decide on if you want to do it or not. Does this sound good? And of course I can take care of the tool tasks, and if any unit tests fail (for no good reason) you can just leave them for me to fix.

**Comment by DNx5** [comment]
http://wiki.ess3.net/wiki/Group_Manager#Permissions_Nodes
>Summary Nodes
Group Manager supports summary nodes, that is using a wildcard to enable all registered sub-permissions.

essentials.* : Allows access to every essentials command
essentials.kits.* : Allows access to use every kit
You can also give the '*' wildcard by itself, without specifying a plugin. This causes the specified group to have access to every command from every plugin. Note: Conflicting commands will become unstable unless negated by a negative node. Use at your own risk. Not all plugins properly register their permissions as well.

**Comment by DNx5** [comment]
I agree with you :smile: I don't like `authme.vip`

**Comment by ljacqu** [comment]
I like it better than `authme.player.vip` though :/ This way it isn't included in `authme.player.*`

**Comment by Done84** [comment]
authme.player.* Gives everyone the perm to see alternate accounts, i don't think this permission should be under authme.player, its more of a staff perm than a players perm.

**Comment by ljacqu** [comment]
I can't find that node explicitly but what @Done84 mentions (authme.player.* gives more than it should) would be fixed by sgdc3's newPlugin.yml

I will assign this issue to me and make the necessary changes on a branch, then I'll assign this to DNx5 or sgdc3 for verification and changing whatever you don't like ^^

Once we rework the perm nodes we need to make sure that we all like it so that we stick with it

**Comment by ljacqu** [comment]
I merged some of the changes of newPlugin.yml on a branch; please review and make any changes you're not happy with (e.g. if you have a better name for `PlayerStatePermission`).

List of what the new permission nodes would be can be seen [on the branch](https://github.com/AuthMe-Team/AuthMeReloaded/blob/415-perm-nodes-rework/src/tools/docs/permission_nodes.md).
I didn't move `/converter` to `/authme converter` because I haven't heard much about this anymore, so not sure if the team would be happy with that breaking change.

I didn't add any of the newPlugin.yml's `permission` constraints for the base commands as it didn't seem to me that it was necessary. But as I said, the plugin.yml format is a little alien to me ;)

Renamed permission nodes:
```
authme.player.allow2accounts	  -> authme.allowmultipleaccounts
authme.player.bypassantibot		  -> authme.bypassantibot
authme.player.bypassforcesurvival -> authme.bypassforcesurvival
authme.player.seeotheraccounts	  -> authme.admin.seeotheraccounts
authme.player.vip				  -> authme.vip
```

@DNx5 @sgdc3 Once you like the setup, you can merge it to master. I will then add an entry to the breaking changes Wiki page.

**Comment by ljacqu** [comment]
bumperoni

**Comment by sgdc3** [comment]
it should be fine, and yes we agree to move the /converter comand ;)

**Comment by ljacqu** [comment]
Thanks! I'll merge master into the branch since it's gotten quite old and then you can move `/authme converter` to `/converter` if you want. :)

**Comment by ljacqu** [comment]
19 commits behind and not a single conflict. Nice. :smile:

**Comment by ljacqu** [comment]
Permission change done + added to breaking changes. Still open is moving /converter to /authme converter
