### ISSUE TITLE
Bug with /email add - Please fix

### ISSUE THREAD

**Issue by NickFirenzo** [Xephi/AuthMeReloaded#416]
Hi,
I want to report a bug with /email add.
If someone have acounts who is the maximum of limit, example in config yml have maxregperip: 3 and someone have 3 accounts when type /email add hisemail@example.com getting a text:
You have reached the maximum number of accounts when type /email add.

**Comment by DNx5** [comment]
http://ci.xephi.fr/job/AuthMeReloaded/664/

**Comment by NickFirenzo** [comment]
Done, fixed. But have another bug.
When you add an email adress
example:
/email add email@example.com email@example.com and you added sucsess.
You can add again with /email add email@example.com email@example.com, again getting sucsess added. Please fix it with /email add, when added 1 time, no more. To change use /email change, thanks

**Comment by NickFirenzo** [comment]
fixed, thanks
