### ISSUE TITLE
Player can't join bug due to 'USERNAME_ALREADY_ONLINE_ERROR'

### ISSUE THREAD

**Issue by prozhong** [Xephi/AuthMeReloaded#417]
Using #660
http://ci.xephi.fr/job/AuthMeReloaded/660/
My config same as #408

When a player named 'oneplayer' is playing ,the new player named 'oneplaye' can't join and will kicked with ''USERNAME_ALREADY_ONLINE_ERROR''

**Comment by prozhong** [comment]
so player EASON's online will block player 'EASO' or 'EAS' joining
but player EASO's online wont block player 'EASON' joining

**Comment by DNx5** [comment]
You could test this build,
http://ci.xephi.fr/job/AuthMeReloaded/666/

**Comment by prozhong** [comment]
fixed
