### ISSUE TITLE
Strict Mode

### ISSUE THREAD

**Issue by me1ga** [Xephi/AuthMeReloaded#418]
Please add the ability to disable mysql strict modes for AuthMe session.
When strict modes enabled:
[10:39:29] [pool-3-thread-1/WARN]: [AuthMe] Field 'buddy_list' doesn't have a default value
and in-game message:
An unexpected error occured, please contact an Administrator!

**Comment by DNx5** [comment]
you should do it yourself. AuthMe shouldn't handle MySQL system configuration.
Also, where is field 'buddy_list' come from? could you set default value for it?

**Comment by me1ga** [comment]
in my system MySQL configuration sql-mode=""
I am using simple machines forum base for storage player data, there is a field, such as 'buddy_list' TEXT NOT NULL, and TEXT NOT NULL field can't have a default value.
Old version AuthMe (on 1.7.2 craftbukkit server) register new users without errors.
