### ISSUE TITLE
Falling through the world

### ISSUE THREAD

**Issue by kristiantomov** [Xephi/AuthMeReloaded#420]
There is some weird issue that when player leave in The End then log back in sometimes he fall though the world. I dont know why but before he log in it just spawns him at x.y.z = 0, and after he log in it spawns him where he left.

**Comment by DNx5** [comment]
What is your `/authme version` ?

**Comment by kristiantomov** [comment]
The server is using 5.2-Snapshot (i dont even know how did they got it...)

**Comment by DNx5** [comment]
build number please?

**Comment by kristiantomov** [comment]
186

**Comment by DNx5** [comment]
Could you update?
http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by kristiantomov** [comment]
the admins said that its fixed.. we'll see

**Comment by sgdc3** [comment]
Closing due to no answer
