### ISSUE TITLE
[Dev] Document AuthMe events and the API

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#421]
Not very important but a nice improvement.

- Create a Wiki page listing the custom events of AuthMe that can be listened to by third party developers (e.g. a short description + link to javadoc)
- Include a note to use NewAPI.java and not Api.java, link to NewAPI javadoc
- Ensure that NewAPI has useful javadoc, i.e. a short description of what the method does + a description of the parameters – *not* the type of the parameter

**Comment by GeARCraft1** [comment]
+1

**Comment by ljacqu** [comment]
@GeARCraft1 I'm glad for the +1, your issue #405 inspired this one ;)

**Comment by Done84** [comment]
+ An API would be very nice

**Comment by sgdc3** [comment]
@Done84 The API already exist...

**Comment by GeARCraft1** [comment]
I don`t now if a JavaDoc is already available, but it would be a nice idea.

**Comment by games647** [comment]
Yes there is a online JavaDoc available. http://www.xephi.fr/AuthMeReloaded/fr/xephi/authme/api/NewAPI.html

But it looks like this version is very old.

**Comment by sgdc3** [comment]
new javadocs are hosted on our jenkins

**Comment by sgdc3** [comment]
the issue is that i don't remember the link

**Comment by sgdc3** [comment]
Ok, found it: http://ci.xephi.fr/job/AuthMeReloaded/javadoc

**Comment by ljacqu** [comment]
https://github.com/AuthMe-Team/AuthMeReloaded/wiki/Hooking-into-AuthMe
