### ISSUE TITLE
Fix own accounts message

### ISSUE THREAD

**Issue by MithrandirCraft** [Xephi/AuthMeReloaded#423]
I don't know how you guys will find this, but there's currently an option for viewing related accounts when someone logs in, as long as you have the "authme.player.seeotheraccounts" permission.

I would like to suggest a permission for viewing one's own account names when logging in, or a command for such checking purpose.

This would be usefull for players who want to unregister some accounts because they have exceded the limit :) But it may have some negative downsides.

---------------------------------
Spigot version: 1.8.8
Authme version: 5.2-SNAPSHOT-b596

**Comment by ljacqu** [comment]
That sounds like a nice idea! Since we can associate it with a permission node, a plugin admin can then decide if he wants to allow it or not. So no downsides per se ^^

**Comment by Xephi** [comment]
Check if it works

**Comment by MithrandirCraft** [comment]
Permission node or New config?

**Comment by Xephi** [comment]
Permission node
authme.player.showotheraccounts

**Comment by MithrandirCraft** [comment]
authme.player.seeownaccounts

**Comment by MithrandirCraft** [comment]
Not working.

**Comment by sgdc3** [comment]
@Xephi

**Comment by ljacqu** [comment]
@MithrandirCraft Is this still an open issue?

**Comment by MithrandirCraft** [comment]
@ljacqu This isn't an issue, it's a suggestion :)
Anyway, I still havent got the change to test if the latest builds already apply this. I am quite stable at the moment, and I'm waiting for a full release on bukkit.

**Comment by MithrandirCraft** [comment]
Ok. I can confirm this is still not working.

**Comment by ljacqu** [comment]
@sgdc3 What is still open for this?

**Comment by sgdc3** [comment]
@MithrandirCraft i don't remember what was missing :/

**Comment by MithrandirCraft** [comment]
It basically just doesn't work.
Setting up the permission: authme.player.seeownaccounts
doesn't  show one's own accounts on entering the server.

Authme version:
![screenshot_2](https://cloud.githubusercontent.com/assets/6623704/15985050/41855a54-2fe1-11e6-950c-848752276005.png)

**Comment by sgdc3** [comment]
894 is old xD

**Comment by MithrandirCraft** [comment]
@sgdc3 This was implemented + suposedly fixed before 894. So If you didn't do any changes related to this issue since then, I'd say the issue will still persist.

+ Updating Authme to a new dev build is something risky and rerrifying xD

**Comment by sgdc3** [comment]
It only shows the own accounts if you have more than 1 registered account per IP

**Comment by ljacqu** [comment]
@MithrandirCraft Could we ask you to verify this again please? I've tested on 1.8.8 with PermissionsBukkit and it behaves as expected.
@sgdc3 The green names for online players is really nice... :)

**Comment by sgdc3** [comment]
Works as intended

**Comment by sgdc3** [comment]
@MithrandirCraft

**Comment by MithrandirCraft** [comment]
I'm on it.

**Comment by MithrandirCraft** [comment]
Fixed. Just one thing, where can I change the "You own X accounts" message?

It hasn't shown up yet on the locale. Can I add it myself? If so, how would the format be?

**Comment by sgdc3** [comment]
just look at the English locale, it should include the key

**Comment by sgdc3** [comment]
@ljacqu  we need to run the tools again

**Comment by ljacqu** [comment]
@sgdc3 You know how, right? :) Good practice. We need someone else who knows the tools

**Comment by MithrandirCraft** [comment]
I really can't find the You own X accounts message anywhere. Can you give me the line?

**Comment by MithrandirCraft** [comment]
Maybe the server needs another restart.

**Comment by ljacqu** [comment]
@MithrandirCraft At the bottom of https://github.com/AuthMe-Team/AuthMeReloaded/blob/master/src/main/resources/messages/messages_en.yml

Opened #768 for creating a command that will automatically "pull" new messages into a user's messages file.

**Comment by ljacqu** [comment]
@sgdc3 Can you run the task for the messages please?

**Comment by sgdc3** [comment]
Yeah, just give me 2 hours, i'm not at pc now.

**Comment by sgdc3** [comment]
I'll also replace the release jar

**Comment by ljacqu** [comment]
@sgdc3 Thanks! The reason I ask you to do it is to make sure you know how, and that it works on your end ;)

**Comment by sgdc3** [comment]
@ljacqu yeah it works but how to add the missing messages to the language files? xD

**Comment by ljacqu** [comment]
Run `verifyMessages` and pay attention to the options (I think it doesn't write the missing ones by default, need to enter `y`)
