### ISSUE TITLE
Permission authme.admin.accounts doesn't work (showing up to all the multiaccounts)

### ISSUE THREAD

**Issue by TonyMontero** [Xephi/AuthMeReloaded#425]
Since i update to the AuthMe Reloaded v5.2 (build 662) all my players can see the multi accounts of other people, no way i negate the authme.admin.accounts node to all (including OP and Admins).

Using Spigot 1.8.8 r0.1 Snapshot (fdc1440-53fac9f)

**Comment by DNx5** [comment]
see
https://github.com/AuthMe-Team/AuthMeReloaded/blob/master/src/tools/docs/permission_nodes.md
