### ISSUE TITLE
usernames are lowercase

### ISSUE THREAD

**Issue by sNuuFix** [Xephi/AuthMeReloaded#426]
all registered usernames saved in mysql database are lowercase, no matter what config uption they are created with (mySQLColumnName and mySQLOtherUsernameColumns (tested as array and string)), no matter what field type. I have tested all possible combinations and nothing works. This compleatly breaks all web integration feature and renders weeks of work useless for our project. I've implemented functionality for web to connect to mojang API and fetch the real username from there with correct case, but it only partly solves our problem, because we are forced to disable mojang auth and only some of players are so called "premiums".

Edit: The database is MariaDB, fully compatible with MySQL interfaces, so that shouldn't be the issue.

**Comment by sNuuFix** [comment]
Resloved this by cloning and compiling latest snapshot and regenerating configuration.

P.S. Thank you for such plugin with so many good features, I was impressed by bcrypt support. :)

**Comment by ljacqu** [comment]
Weird, if this happens again please reopen or create a new issue. Note that the "username" column _is_ lower-case by definition, but "realname" has the actual casing of the user.

**Comment by sNuuFix** [comment]
There was no realname column option in 5.0 version from dev.bukkit.com stable download. Only possibility to use mySQLOtherUsernameColumns that by documentation was supposed to be all-case. But it's old version anyway so doesn't need fixing.

**Comment by sgdc3** [comment]
Yeah, the version on dev bukkit is very outdated...
