### ISSUE TITLE
Players are not recognized correctly

### ISSUE THREAD

**Issue by Trojaner25** [Xephi/AuthMeReloaded#43]
When a player who is registered joins, the plugin still sends the "register using /register password password" message. The player won't be able to log in (-> nickname not registered or something). 

When the player relogs, he will be able to login normally until the next server restart.

**Comment by Xephi** [comment]
Huuum maybe some corruption in database during transition, checking it!

**Comment by Trojaner25** [comment]
This is maybe a duplicate of #40 
But there were not enough details provided on that issuse

**Comment by Xephi** [comment]
Fixed
