### ISSUE TITLE
[Dev] Improve PlayerAuth builder

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#430]
The PlayerAuth builder is excellent and has rendered the code a lot clearer. The following are some improvements:

- Automatically set `name` from `realName`, since `name` should always be `realName.toLowerCase()`. This is a field we shouldn't have to set explicitly. This reduces redundancy & the potential for mistakes.

- The builder speaks of `name`, whereas the PlayerAuth class has the field `nickname`. Unify the names. I'd also suggest moving the `realName` field closer to `nickname`.

- Remove all uses of the constructors in favor of the builder. In the end, there should only be a private constructor which is called by the builder's `build()` method.

**Comment by Xephi** [comment]
The problem with automatically set name from realName is for old datas, since RealName column was not automatically fill in the past, we cannot read from database and found the username from it

**Comment by ljacqu** [comment]
Thanks for the heads up @Xephi. Referencing this issue I made a commit to remove all PlayerAuth constructors. I decided not to change any of the nickname / name fields or the builder's behavior since so far it's been working well and we're used to it.
