### ISSUE TITLE
Registration not working with Vault and/or PermissionsEx plugins enabled

### ISSUE THREAD

**Issue by sNuuFix** [Xephi/AuthMeReloaded#435]
While using Vault or PermissionsEx (bukkit stable releases), users that are not in ops list cannot join the server, they are shown a message to register even if they are already registered and any command they write, including /register and /login gets error "You don't have permission to use this command!". unLoggedinGroup is ignored, even giving all permissions (even including admin commands like /stop) to all users and all groups don't do anything. setting unLoggedinGroup to default or nonexistant group doesn't have any effect too. EnablePermissionCheck also doesn't do anything. If upgrading PermissionsEx to latest snapshot, AuthMe fails to start compleatly with class not found exception for 'PermissionsEx' class. Tested with all plugins individually removed or enabled again, this issue only occurs with Vault and/or PermissionsEx installed with both latest Spigot releases, with custom or stock config for PermissionsEx. Default AuthMe config also doesn't work. I've tried to find a solution for this all day and I'm out of options, so it seems to be a bug. This is critical issue, because only admins can join the server.

**Comment by sNuuFix** [comment]
This is very serious issue to our development team, that has stopped everything for 2 days now. We are willing to help in any way we can, even donate to resolve this.

**Comment by games647** [comment]
Which build do you use?

**Comment by sNuuFix** [comment]
I compiled latest snapshot from github at master branch.

**Comment by games647** [comment]
From the AuthMe-Team repo?

**Comment by sNuuFix** [comment]
No, this one, git@github.com:Xephi/AuthMeReloaded.git
Is that version better or more stable in any way?

**Comment by games647** [comment]
>Is that version better or more stable in any way?

That's a very good question. Personally I don't know, but there are the newest changes.

**Comment by games647** [comment]
So I tried the build from there and added the permission "authme.player.register" and it worked for me.

**Comment by sNuuFix** [comment]
Thank you for suggestion, testing this right now.

**Comment by sNuuFix** [comment]
It's the same bug, even introduces new ones. The players who are not logged in or registered get kicked for flying by anticheat.

**Comment by games647** [comment]
Do you also tried to install both Vault and PermissionsEx? I tried it under these conditions and it worked without problems.

**Comment by sNuuFix** [comment]
Ofcourse. Latest stable versions and snapshots. Also, the issue seems not to be connected with ops list, because PermissionEx admin group also have no problems connecting. Everybody else is forced to register but have no permission, even with already registered accounts.

**Comment by sNuuFix** [comment]
This bug misteriously dissapeared after again testing with specific register permission on unregistered and default group with latest snapshot. I don't know if it's worth closing, let me test this a few days.

**Comment by sgdc3** [comment]
@sNuuFix which programming languages do you know? ;)

**Comment by sgdc3** [comment]
Off topic, i know, but i was curious xD

**Comment by sNuuFix** [comment]
@sgdc3 no problem. I'm professional web developer with 7 years of expirience in the field, mainly as a backend developer. I've been involved in various interesting projects, for example accounting managment systems, post office logistics system, various CMS'es and frameworks. I've managed teams of developers, also have tried to create two businesses on my own, but not successfully. At this point I'm a bit retired from all the struggle with that stuff, it created alot of stress in my personal life, but I will continue to work in the field, mainly in managment positions.

About the languages I'm good at: PHP is my thing, I've even been involved in its core development. Ofcourse that comes with all other web related languages: JavaScript, HTML, CSS. All except Flash, because it's dying and irrelevant. Other things I know a bit include C, C++, C#, Objective-C, Cocoa, Swift, Java, even some things about Assembler, but I can't say that I'm good at these, because I have not much expirience working with them. I'm also good at Linux stuff, been managing clusters of servers with load balancers and complicated caching mechanisms for high availability and performance.

The minecraft server I'm developing right now is my personal project with my firends because we like Minecraft and we are very dissapointed with the poor server quality our country offers, so we decided to make a good one for a change. It's by no means any project that aims to get huge income, bet we certainly want to scale up when time comes. At this point covering hosting expenses is our only priority. Everything else goes into quality and good gameplay, so we could play and enjoy it ourselves.

**Comment by Mabus13** [comment]
Plugins (30): AsyncWorldEditInjector, craftinomicon, WorldEdit, Essentials, PacketListenerApi, ClearLag, AnimatedFrames, ReversCraft, ConsolesCore, ProtocolLib, NoCheatPlus, GravityGun, SkinsRestorer, AsyncWorldEdit, MyCraft, EssentialsChat, PermissionsEx, RandomTPItem, SkullTurret, GTADeath, Vault, GriefPrevention, EssentialsSpawn, TitleManager, AuthMe, ConsolesComputers, ResourcePackDownloader, HolographicDisplays, RPGHealthPlus, GPRealEstate

Have like same problem. But also oped char cant login. Trying  /L pass command with message no permission.

**Comment by Giulio1708** [comment]
@sNuuFix news about it? I have the same problem, but for me it's still not solved.

**Comment by sgdc3** [comment]
Blocked by our permissions structure update

**Comment by sNuuFix** [comment]
Sorry for the delayed response. I still haven't found the exact solution, but what I know from setting permission plugin to debug, was that it requires authme.player.register and authme.player.login permissions exactly and it seems to fail with authme.player.* wildcard setting.

**Comment by Mabus13** [comment]
- authme.player.register
        - authme.player.login
Only after add it for my oped char admin group i can login

    permissions:
    - permissions.* 
That option not enough. >_< and it option not work for can use login command.

**Comment by Mabus13** [comment]
Also i try all it after update from ver 3.5 maybe "old" config wrongly updatet and it issue for that bug. idnk

**Comment by sgdc3** [comment]
Now the permissions docs are updated, closing.
