### ISSUE TITLE
Authme bad permissions managing

### ISSUE THREAD

**Issue by netbiosxx** [Xephi/AuthMeReloaded#439]
Hi! On my server,when a player join,sometimes it remain on non-logged group.
So i replaced the non logged-group with the user group.
But now the staffers remain users,and i have to reset them every time.
Now the prefix is bugged,and the default one on the group don't work,it remains user,so i need to set that.
I use PermissionsEX ,essentials and authme,and i have spigot 1.8.8

**Comment by games647** [comment]
Do you have Vault installed?

**Comment by sgdc3** [comment]
@netbiosxx

**Comment by netbiosxx** [comment]
yes si

**Comment by netbiosxx** [comment]
I have vault installed,i followed the adviceof sgdc3,putting a fake group unLogged InGroup, result?
They join on that fake group,written by authme on permissionsEX.
It would be better that the unLoggedInGroup Group was already integrated on AuthMe,with a pre-login permissions management system,and then jumps to permissionsEX after login,So he only read on permissionsEX,preventing bugs.

**Comment by sgdc3** [comment]
Ok i've found the issue. @ljacqu we need to check if the target group exist before changing the player one. ;)

**Comment by netbiosxx** [comment]
Ciao 
Il problema che continuo a porti è che io stesso non trovo soluzione ed il seguente è sempre il solito:
A prescidere cosa io ci scriva nel config di AuthMe in unLoggedinGroup:, che in questo momento forzatamente ho messo utente, il plugin authme non si ricorda il gruppo di origine a cui apparteneva un determinato utente.
Un esempio:
l'utente xxx in permissionex è settato helper,  ebbene, quando slogga xxx per poi rientrare in un deteminato momento si ritrova settato  come utente e non più helper.
Se solo mi azzardo a settare unLoggedinGroup: nel gruppo nonloggati, che hanno i permessi dritti dritti per loggarsi, mi ritrovo staff ed utenti tutti assegnati sempre in permissionex nel gruppo dei nonloggati non potendo piu interaggire col normale svolgimento del game.

**Comment by sgdc3** [comment]
@ljacqu @DNx5 @games647 Can you give a quick look at this? (read my last comment to understand what's the possible cause of this issue) Thanks ;)

**Comment by sgdc3** [comment]
@ljacqu can you check this? The fix should be very quickly!

> Ok i found the issue. @ljacqu we need to check if the target group exist before changing the player one. ;)

**Comment by sgdc3** [comment]
Pex creates a new group if it doesn't exist!

**Comment by ljacqu** [comment]
@sgdc3 I'm afraid I'm not familiar with our handling of permissions that much. Maybe this is more suitable for you to look at? I have no idea how to get about this.

**Comment by sgdc3** [comment]
lol me too maybe @games647 or @DNx5 can help us ;)
