### ISSUE TITLE
Case sensitive usernames

### ISSUE THREAD

**Issue by Platinteufel** [Xephi/AuthMeReloaded#441]
Hello,

I got a question: Is it possible to deny "nAmE" to join if there's a registered user called "Name"? He shouldn't be able to connect and should get a message like this:

![case sen](https://cloud.githubusercontent.com/assets/13700636/12314788/2e951840-ba74-11e5-94f1-d89bce4f0b3e.png)

atm AuthMe only denies "nAmE" to join if "Name" is currently online, but it doesn't check if "Name" is already registered.
I will translate messages into German if needed. Thank you! :+1:

**Comment by sgdc3** [comment]
Enable preventOtherCases in the config.

**Comment by ljacqu** [comment]
@Platinteufel We'll probably do a round of translatable messages sometime soon. Could we contact you for German translations at that point? :)

**Comment by Platinteufel** [comment]
Thank you for the fast support. :)

Sure @ljacqu ;)

**Comment by RoinujNosde** [comment]
> Enable preventOtherCases in the config.

Can't find this option.

I'm using AuthMe Reloaded 5.0-beta3

**Comment by games647** [comment]
This option is only implemented in the dev builds.

**Comment by RoinujNosde** [comment]
Thanks ;)

**Comment by Platinteufel** [comment]
@ljacqu Do you still need German translations for 5.2 release?

**Comment by sgdc3** [comment]
@Platinteufel Yes please ;) Just open a new issue with a link to your message_xx file.
