### ISSUE TITLE
The setting maxRegPerEmail won't work.

### ISSUE THREAD

**Issue by smartmadio** [Xephi/AuthMeReloaded#442]
My fault,it's translation error.

**Comment by ljacqu** [comment]
Is one of our translation files wrong?

**Comment by smartmadio** [comment]
Yes,the translation of 'max_reg' in messages_zhcn.yml,messages_zhhk.yml,messages_zhtw.yml is not exactly enough.

The translation's meaning is 'You have exceeded the maximum number of registrations for your IP!'

But When the player reaches the limit of maxRegPerEmail ,it also display this message.

Emm...maybe the English version is also not suitable.

Maybe adding a 'max_reg_email' could be better:)

**Comment by smartmadio** [comment]
Maybe it's not just a translation error.Seems maxRegPerEmail really can't work correctly,today I tested again on it,the players coult register unlimited amount of accounts using the same e-mail while 'maxRegPerEmail' is setted to '1'.

**Comment by RoinujNosde** [comment]
Still happens on:
Build 813
CraftBukkit version git-Spigot-db6de12-3f3c65f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by RoinujNosde** [comment]
Update:
I set maxRegPerEmail to 2.
Registered SirCadogan and killer010 with blabla@email.com.
When I tried to register RoinujNosde with the same email, it displays me max_reg msg.
So it just does not work with maxRegPerEmail: 1.

Here is another bug I found:
Both killer and sircadogan were registered, so the limit was reached, but i was able to register RoinujNosde using blabla@email.COM.
Should I open another ticket for this bug?

**Comment by ljacqu** [comment]
If I understand correctly, the issues are:
1. email check does not work when maxRegPerEmail is set to 1
2. Email check is case-sensitive

If it's just that, we're OK with one ticket :) Both should be easy fixes. Thanks a lot for your analysis!

**Comment by RoinujNosde** [comment]
That's it :)

**Comment by RoinujNosde** [comment]
> I set maxRegPerEmail to 2.
 Registered SirCadogan and killer010 with blabla@email.com.
 When I tried to register RoinujNosde with the same email, it displays me max_reg msg.
 So it just does not work with maxRegPerEmail: 1.

Ignore this.
Just tested again and maxRegPerEmail: 1 is working.

**Comment by RoinujNosde** [comment]
P.S.: This is still a bug:
> 2. Email check is case-sensitive

**Comment by ljacqu** [comment]
Thanks as always, @RoinujNosde; I hope you stick around! You're providing us with a lot of helpful analyzes and insight. The issue at hand should be fixed with build nr. 816 or upwards :)

Full disclosure, haven't tested on MySQL before pushing but will do that now...

**Comment by RoinujNosde** [comment]
Man, as long as I am a server owner, I am gonna use AuthMe and help reporting bugs :)

**Comment by sgdc3** [comment]
@RoinujNosde can you try latest build and report back? :)

**Comment by RoinujNosde** [comment]
@sgdc3 Just downloaded 817, opened its plugin.yml:
> version: 5.2-SNAPSHOT-b813

**Comment by RoinujNosde** [comment]
Fixed.

**Comment by sgdc3** [comment]
Thank you ;)
