### ISSUE TITLE
Wrong message when player logs in successfully.

### ISSUE THREAD

**Issue by smartmadio** [Xephi/AuthMeReloaded#443]
I used this setting a long time ago.
```
    enableEmailRegistrationSystem: false
    recallPlayers: false
```
Today I changed the setting to
```
    enableEmailRegistrationSystem: true
    recallPlayers: true
```
And when a player who havn't added an email to his account logs in successfully,it always displays: `Email address successfully added to your account!` rather than  `Please add your email to your account with the command "/email add <yourEmail> <confirmEmail>"`

**Comment by smartmadio** [comment]
Something wrong with my words ,I've corrected it.

**Comment by ljacqu** [comment]
Should be fixed, thanks for the report :)

**Comment by sgdc3** [comment]
@smartmadio

**Comment by smartmadio** [comment]
Got it, I‘ll have a look on it :-)

**Comment by smartmadio** [comment]
@sgdc3 Yes,it could have the right message now.
