### ISSUE TITLE
Ignore IP from OP ?

### ISSUE THREAD

**Issue by agronaque512** [Xephi/AuthMeReloaded#445]
Is this possible to configure AuthMe to make him ignore all admins account IP ? Like they need to use /login too but they don't have IP join/login/reg restriction ?

**Comment by ljacqu** [comment]
Sounds like you want to allow certain people multiple accounts, which we have a permission for :) Please see
https://github.com/AuthMe-Team/AuthMeReloaded/blob/master/src/tools/docs/permission_nodes.md
