### ISSUE TITLE
Im not sure if its an issue but look it over

### ISSUE THREAD

**Issue by eero619** [Xephi/AuthMeReloaded#446]
DataSource:
  backend: sqlite
  caching: true
  mySQLHost: 127.0.0.1
  mySQLPort: '3306'
  mySQLUsername: authme
  mySQLPassword: '12345'
  mySQLDatabase: authme
  mySQLTablename: authme
  mySQLColumnId: id
  mySQLColumnName: username
  mySQLColumnPassword: password
  mySQLColumnEmail: email
  mySQLColumnLogged: isLogged
  mySQLColumnIp: ip
  mySQLColumnLastLogin: lastlogin
  mySQLlastlocX: x
  mySQLlastlocY: y
  mySQLlastlocZ: z
  mySQLlastlocWorld: world
  mySQLRealName: realname
  mySQLWebsite: false
  mySQLMaxConections: 25
settings:
  helpHeader: AuthMeReloaded
  sessions:
    enabled: false
    timeout: 10
    sessionExpireOnIpChange: false
  restrictions:
    allowChat: false
    allowCommands:
    - /login
    - /register
    - /l
    - /reg
    - /passpartu
    - /email
    - /captcha
    maxRegPerIp: 1
    maxNicknameLength: 20
    ForceSingleSession: false
    ForceSpawnLocOnJoinEnabled: false
    SaveQuitLocation: true
    AllowRestrictedUser: false
    AllowedRestrictedUser:
    - playername;127.0.0.1
    kickNonRegistered: false
    kickOnWrongPassword: false
    teleportUnAuthedToSpawn: false
    minNicknameLength: 3
    allowMovement: true
    removeSpeed: true
    timeout: 30
    allowedNicknameCharacters: '[a-zA-Z0-9_]*'
    allowedMovementRadius: 15
    enablePasswordConfirmation: true
    ProtectInventoryBeforeLogIn: false
    displayOtherAccounts: true
    ForceSpawnOnTheseWorlds:
    - world
    - world_nether
    - world_the_end
    banUnsafedIP: false
    spawnPriority: authme,essentials,multiverse,default
    maxLoginPerIp: 0
    maxJoinPerIp: 0
    noTeleport: false
    allowedPasswordCharacters: '[\x21-\x7E]*'
  GameMode:
    ForceSurvivalMode: false
    ResetInventoryIfCreative: false
    ForceOnlyAfterLogin: false
  security:
    minPasswordLength: 4
    unLoggedinGroup: unLoggedinGroup
    passwordHash: SHA256
    doubleMD5SaltLength: 8
    supportOldPasswordHash: false
    unsafePasswords: []
  registration:
    enabled: true
    messageInterval: 5
    force: true
    enableEmailRegistrationSystem: false
    doubleEmailCheck: false
    forceKickAfterRegister: false
    forceLoginAfterRegister: false
  unrestrictions:
    UnrestrictedName: []
  messagesLanguage: en
  forceCommands: []
  forceCommandsAsConsole: []
  forceRegisterCommands: []
  forceRegisterCommandsAsConsole: []
  useWelcomeMessage: true
  broadcastWelcomeMessage: false
  delayJoinLeaveMessages: true
  applyBlindEffect: false
  preventOtherCase: false
ExternalBoardOptions:
  mySQLColumnSalt: ''
  mySQLColumnGroup: ''
  nonActivedUserGroup: -1
  mySQLOtherUsernameColumns: []
  bCryptLog2Round: 10
  phpbbTablePrefix: phpbb_
  phpbbActivatedGroupId: 2
  wordpressTablePrefix: wp_
permission:
  EnablePermissionCheck: false
BackupSystem:
  ActivateBackup: false
  OnServerStart: false
  OnServerStop: true
  MysqlWindowsPath: C:\\Program Files\\MySQL\\MySQL Server 5.1\\
Security:
  SQLProblem:
    stopServer: true
  ReloadCommand:
    useReloadCommandSupport: true
  console:
    noConsoleSpam: false
    removePassword: true
  captcha:
    useCaptcha: true
    maxLoginTry: 2
    captchaLength: 5
  stop:
    kickPlayersBeforeStopping: true
Converter:
  Rakamak:
    fileName: users.rak
    useIP: false
    ipFileName: UsersIp.rak
  CrazyLogin:
    fileName: accounts.db
Email:
  mailSMTP: smtp.gmail.com
  mailPort: 465
  mailAccount: ''
  mailPassword: ''
  mailSenderName: ''
  RecoveryPasswordLength: 8
  mailSubject: Your new AuthMe Password
  mailText: 'Dear <playername>, <br /><br /> This is your new AuthMe password for
    the server <br /><br /> <servername> : <br /><br /> <generatedpass><br /><image><br
    />Do not forget to change password after login! <br /> /changepassword <generatedpass>
    newPassword'
  maxRegPerEmail: 1
  recallPlayers: false
  delayRecall: 5
  emailBlacklisted:
  - 10minutemail.com
  emailWhitelisted: []
  generateImage: true
  emailOauth2Token: ''
Hooks:
  multiverse: true
  bungeecord: false
  sendPlayerTo: ''
  disableSocialSpy: true
  useEssentialsMotd: false
  customAttributes: false
Purge:
  useAutoPurge: false
  daysBeforeRemovePlayer: 60
  removePlayerDat: false
  removeEssentialsFile: false
  defaultWorld: world
  removeLimitedCreativesInventories: false
  removeAntiXRayFile: false
  removePermissions: false
Protection:
  enableProtection: true
  countries: []
  countriesBlacklist: []
  enableAntiBot: true
  antiBotSensibility: 5
  antiBotDuration: 10
VeryGames:
  enableIpCheck: false
GroupOptions:
  UnregisteredPlayerGroup: ''
  RegisteredPlayerGroup: ''
  Permissions:
    PermissionsOnJoin: []

My config i want something that more than 4 accounts couldnt join per ip since its kinda like botting the server today somebody with similair bot spammer joined after evry abit of second bot joined they all had the same ip i want to disable this pls help if can if cant il just keep banning them via ip

**Comment by sgdc3** [comment]
sure you can! ;)
maxJoinPerIp: 4

**Comment by ljacqu** [comment]
Closing—no feedback from issue reporter
