### ISSUE TITLE
the player loses the inventory when not logged this caused by auto-kick

### ISSUE THREAD

**Issue by yzz17** [Xephi/AuthMeReloaded#447]
the time out cose this 
1 login 
2 take items
3 log out
4 enter the server
5 wait for auto kick 
6 enter the server
7 login
8 the items "pufff" ={

**Comment by DNx5** [comment]
what is your `/authme version` ?

**Comment by sgdc3** [comment]
What's your inventory management plugin (Es: mv-inv, multiinv, perworldinventory... )

**Comment by Platinteufel** [comment]
I'm running the latest snapshot + MultiInv b70 since two days and can't confirm this bug.

**Comment by yzz17** [comment]
mv-inv , beta-3

**Comment by sgdc3** [comment]
Can you try with perworldinventory?

**Comment by yajiedesign** [comment]
I am this bug too


AuthMe-5.0-beta3.jar
AutoSaveWorld.jar
DeathMessages-1.7.10.jar
Essentials.jar
EssentialsAntiBuild.jar
EssentialsChat.jar
EssentialsGroupManager.jar
EssentialsProtect.jar
EssentialsSpawn.jar
KillerMoney.jar
NeverLag1.3.0.jar
ProtocolLib.jar
pTweaks.jar
Residence.jar
Vault-1.4.1.jar
worldedit-bukkit-6.1.jar

**Comment by games647** [comment]
@sgdc3 It's the old version from BukkitDev

@yajiedesign @yzz17 Please try to update to a dev build

**Comment by DNx5** [comment]
someone should remove 5.0 from BukkitDev. It has critical bug.

**Comment by sgdc3** [comment]
@Xephi

**Comment by yzz17** [comment]
thx to all
