### ISSUE TITLE
MOD

### ISSUE THREAD

**Issue by evernife** [Xephi/AuthMeReloaded#45]
Aren't there a way to convert this plugin in a Forge MOd? It is too difficult ?

**Comment by Trojaner25** [comment]
Why?

**Comment by evernife** [comment]
Because there isn't exits an effective mod that do this....
For exemple, we have the FE module, but, that module can easy dupe itens...

**Comment by Xephi** [comment]
if someone want to do it, i have no free time to do something like that :/ sorry, but , for real, if someone want to code it, just send me a mail :)

Sorry :/

Xephi
