### ISSUE TITLE
[Dev] Configuration: Port rewrite checks to NewSetting class

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#450]
We are temporarily using `Settings` and `NewSetting`. The goal is to eventually use only `NewSetting`.

- [x] **Before** this can be done, we need to be able to write proper YAML in NewSetting. This should be done as much as possible by the methods SnakeYAML offers. Integration test should still work and could be enhanced a little more (e.g. have a value with a backslash, have a value with an apostrophe, have a string list with a multi-line value... Just values that might potentially break)

- [x] Right now we check in `Settings` whether we need to rewrite the config.yml file, if for example a setting is missing or an old setting is present. The task of this issue is to move this logic to the NewSetting class and to have that class decide when we need to rewrite to config.yml.
It should be possible to do it a little more generically with the `PropertyMap`, e.g. to check if a property is missing.

- [x] Test before merging (welcome message, email message, rewrite, handling of missing config file, handling of missing email file, isEmailCorrect, force migration flat -> sqlite, force migration of PLAINTEXT hash algorithm)

**Comment by sgdc3** [comment]
Why we can't just rename NewSettings to Settings?

**Comment by ljacqu** [comment]
We can once Settings is deleted. I don't think it would make sense to gradually change the code in Settings.

**Comment by ljacqu** [comment]
TODO:
- [ ] ReloadCommand needs to be changed to speak with NewSettings
- [ ] AuthMe main class uses Settings#set at one point... 
- [ ] AuthMe main class + ForceFlatToSqlite uses Settings#setValue. Both need to be ported
- [ ] Need to relocate Settings#getRestrictedIp, Settings#isEmailCorrect
- [ ] Do equivalent of Settings#loadEmailText and #getWelcomeMessage
- [ ] Need to port check from Settings#checkLang
