### ISSUE TITLE
[Enhancement] Login in the air

### ISSUE THREAD

**Issue by Platinteufel** [Xephi/AuthMeReloaded#452]
Hey,
I just noticed that if you logout in the air or in water and relog with AuthMe installed, you're bugging in the air, can't login (because you can't open the chat) and sometimes get kicked for "flying is not enabled". 
I don't know if there's an easy fix for it, but maybe it's possible to create a virtual block below the player or enable fly-mode till the player is logged in. :)

**Comment by sgdc3** [comment]
@Platinteufel what's your plugin version?

**Comment by Platinteufel** [comment]
build 683

**Comment by sgdc3** [comment]
Ok, we'll fix asap. ;)

**Comment by Platinteufel** [comment]
Maybe you could add a point like "SafeLogin" in config that you can enable/disable.

**Comment by Platinteufel** [comment]
Do you have any idea how to fix this? Is it possible to enable Essentials Flymode till the player is logged in? It's quite annoying that players can't login in the air and have to try it 5-10 times. ;)

**Comment by DardBrinza** [comment]
Add a feature that will put the player on the ground before authorization (was in the air, puts it on the ground, he enters the password and sends it back into the air)

**Comment by sgdc3** [comment]
@DNx5 @ljacqu @games647 what do you think about?

**Comment by DardBrinza** [comment]
UP. Important problem.

**Comment by Platinteufel** [comment]
Don't think that's very difficult to fix, would be awesome seeing it in 5.2 release. No ideas? :/

**Comment by sgdc3** [comment]
@ljacqu We should set the player's fly state to true before login, and then back to the original one (like in authme 3.4 with the limbocache)

**Comment by ljacqu** [comment]
I'm unfamiliar with that part of AuthMe so it will be good to learn ^^

**Comment by Platinteufel** [comment]
Thank you! :)
I'm just wondering why all Build Processors are down at jenkins server. Is this intended? ^^

**Comment by games647** [comment]
>I'm just wondering why all Build Processors are down at jenkins server. Is this intended? ^^

```java.io.IOException: No space left on device
	at java.io.FileOutputStream.writeBytes(Native Method)```

:disappointed:

**Comment by Platinteufel** [comment]
Oh, okay :persevere:

**Comment by Platinteufel** [comment]
Any progress here? :/

**Comment by ljacqu** [comment]
Nothing so far, sorry. Will check this after another issue.

**Comment by sgdc3** [comment]
Just a reminder @ljacqu ;)

**Comment by sgdc3** [comment]
@ljacqu Just a reminder ;)

**Comment by ljacqu** [comment]
OK, finally tested this: quitting in the air, in water, or in lava (which hopefully no one does) behaves as it should—the player drops, or sinks, to the ground.
