### ISSUE TITLE
[Dev] Protect AuthMe master branch

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#454]
@games647 recently suggested that we protect the _master_ branch of our dev repository at AuthMe-Team/AuthMeReloaded.

This can be done under Settings > Branches: Protected branches. This helps us prevent accidental force pushes in the future.

I think only @sgdc3 can set this, or @Xephi

https://help.github.com/enterprise/11.10.340/admin/articles/blocking-force-pushes-to-a-repository/

**Comment by sgdc3** [comment]
Sometimes we use the force feature to reset huge errors in the commit log

**Comment by sgdc3** [comment]
we have tons of backup anyway.

**Comment by sgdc3** [comment]
just think about all the forks

**Comment by games647** [comment]
>Sometimes we use the force feature to reset huge errors in the commit log

Then you could do revert commit, don't you think so?

>we have tons of backup anyway. Just think about our forks ;)

But most of them are not up to date.

**Comment by sgdc3** [comment]
Nope, mine is updated

**Comment by sgdc3** [comment]
Anyway if you want we can enable the protection and disable it only when required

**Comment by sgdc3** [comment]
done

**Comment by games647** [comment]
Thank you

**Comment by sgdc3** [comment]
You're welcome ;)

**Comment by ljacqu** [comment]
Thanks, yeah, force push is never a good idea
