### ISSUE TITLE
How to disable /server command before login or register?

### ISSUE THREAD

**Issue by NickFirenzo** [Xephi/AuthMeReloaded#455]
Hi,
I need help about disable /server command before players logging in. Authme isn't block it :(

**Comment by prozhong** [comment]
Do you use bungeecord(BC)?
/server is one BC command

/server [server] 
Permission Node: bungeecord.command.server

**Comment by sgdc3** [comment]
This should be done by authmebungee. The issue is that we first need to fix it. xD

**Comment by NickFirenzo** [comment]
I'm using plugin for /server, not bungeecord permission
@sgdc3 AuthMeBridge install on bungeecord ?

**Comment by games647** [comment]
@NickFirenzo Yes you need to install it on the BungeeCord instance.

**Comment by NickFirenzo** [comment]
fixed
