### ISSUE TITLE
[Question] How do I disable the /login command

### ISSUE THREAD

**Issue by Dooleylabs** [Xephi/AuthMeReloaded#456]
I want to use AuthMeReloaded as a forum sign-up tool, rather than a game login tool. I want to disable /login and allow players to play as they would if the plugin were not installed. Is this possible? I though I did it before, but after I reinstalled the plugin, I couldn't disable the feature. Is there a way I can do this?

All help is greatly appreciated.
Thanks.

**Comment by Platinteufel** [comment]
Hm, there's a point in config that let you disable registrations:

    registration:
        # enable registration on the server?
        enabled: true

But I'm not sure if this will solve your issue.

**Comment by sgdc3** [comment]
yeah you're right ;)

**Comment by Dooleylabs** [comment]
I only want to get rid of /login. I want to use /register to sign up on our forum so we don't get spam bots and users that aren't part of the game.

**Comment by RoinujNosde** [comment]
I think AutoIn would help you.

**Comment by sgdc3** [comment]
I'll send you a configuration ;)

**Comment by Dooleylabs** [comment]
How's the configuration coming? I'm excited. Once this works properly, I'm launching our forum, which hooks into our teamspeak - which should, in theory, make our server s secure as possible.

**Comment by sgdc3** [comment]
[config.txt](https://github.com/Xephi/AuthMeReloaded/files/107212/config.txt)

**Comment by sgdc3** [comment]
@Dooleylabs It should work fine, check it and set your customization settings.

**Comment by Dooleylabs** [comment]
I tested it, it still says the /login prompt when I try any conmand. Is there a way to whitelist all possible commands without needing to login, or am I missing something? I tried it with 5.0 beta 3 and build 700, but neither worked, claiming that some nodes in the config were updated each time. With both instances, I used a fresh copy of the modified config you sent.

**Comment by Dooleylabs** [comment]
*bump*

**Comment by sgdc3** [comment]
@DNx5 @games647@ljacqu we need to add an allowCommands option.

**Comment by Dooleylabs** [comment]
**It works!!** The last thing I need now is an option to hide the /login message and something to disable the unlogged group. Thank you for all of your help @sgdc3

**Comment by sgdc3** [comment]
Message: just incrase the delay value to something like 300, the message will still be shown but it will remember players that they should register ;)

**Comment by sgdc3** [comment]
Group issue: It's a current bug, we are working on it!

**Comment by Dooleylabs** [comment]
So I set the timeout on that reminder to broadcast once a year (31536000 - my fav number ;D) and I set the login reminder to " ". As for the group, is it possible to set it to a blank space or [ ]? I can safely set it to default, but it messes up prefixes, so I've set it as unLogged until it can be disabled. I do not want a pex listing for every player on the server as I've seen it create lag in the past.

**Comment by sgdc3** [comment]
@Dooleylabs I sent a commit that allows you to set the reminder interval to a value < 0 (disables the message), can you try it? ;)

**Comment by Dooleylabs** [comment]
I'll try it within 30-45 mins. I'm out at the moment.

**Comment by sgdc3** [comment]
Ok, thanks ;)

**Comment by Dooleylabs** [comment]
@sgdc3 once again, **It works!!** Now to figure out the unLogged permission and we'll be forever set!! **<3**

**Comment by Dooleylabs** [comment]
Found a cavet._. When you aren't logged in, you can't break or place blocks at all...

**Comment by sgdc3** [comment]
right... we need to add an option to disable all the checks @ljacqu @games647 @DNx5

**Comment by games647** [comment]
or mark the player as logged in?

**Comment by sgdc3** [comment]
Yeah but this will create issues with web interfaces.

**Comment by Dooleylabs** [comment]
Any progress?

**Comment by sgdc3** [comment]
Assigned to @games647 
We need to create a method shouldDenyEvent method and use it into all the listener

**Comment by sgdc3** [comment]
Why did i close this? O_o thanks @ljacqu

**Comment by ljacqu** [comment]
@sgdc3 It's not your fault—when someone commits something along the lines of "Fix #456" or "Close #456" it automatically closes the issue. This only happens for commits on Xephi/master, which happened with the pull request you merged (and thanks for that! It was time). :)

**Comment by sgdc3** [comment]
@DNx5 @ljacqu @games647 Who want to fix this? ;)

**Comment by DNx5** [comment]
this should be, "No Need to Authenticate Players" feature.
@sgdc3 How about the newconfig.yml? is it good enough?

**Comment by sgdc3** [comment]
we can't switch to newsettings atm, the NewSettings class is still a WIP and settings often are taken from the old Settings class.. If we need to add an option we had to insert it in the old file.

**Comment by sgdc3** [comment]
@DNx5 @ljacqu @games647 Anyone wants to work on this?

**Comment by Dooleylabs** [comment]
Any progress updates?

**Comment by Dooleylabs** [comment]
@sgdc3 Any updates?

**Comment by sgdc3** [comment]
No, sorry :/

**Comment by Dooleylabs** [comment]
bump

**Comment by Dooleylabs** [comment]
Anyone mind pointing me to a plugin that solely allows forums registration or a way to make a plugin for it?

**Comment by Dooleylabs** [comment]
Any luck disabling all checks in the config? As of build 1082, I'm still added to the unLoggedIn group and denied access to commands. Maybe I'm doing something wrong?

**Comment by Dooleylabs** [comment]
Maybe something like this to allow all commands:

        # Commands allowed when a player is not authenticated
        allowCommands:
        - '*'

And I've set the `unLoggedinGroup` to inherit the perms of the default group, so I'm thinking there's not much else I can do before this feature is added. How's progress on the `Disable All Checks` feature coming? I'd like to be able to disable the unLoggedinGroup thing, but at this point, I'm thinking maybe someone could make a second plugin that is a stripped-down version of AuthMe which only allows forum registration. There's nothing else out there like it, and AuthMe has all the feature and code for it already, so I figure a slimmer version may work without doubling every line of code to disable almost everything.

Unless AuthMe is aiming for 100% configurability xD, which in that case, I'm more than happy to get this feature implemented in the plugin.

**Comment by ljacqu** [comment]
We had a discussion about this a week ago and came to the conclusion that we cannot satisfy this use case with our plugin. In the end, AuthMe is an _authentication_ plugin; supporting this would require to disable large parts of the very core of AuthMe.
I don't know the Minecraft plugin landscape well enough anymore but if forum spam is the major issue here a mechanism that messages, say, a code to an online player or so would better suit this problem.

**Comment by Dooleylabs** [comment]
We thought of that, but no plugin exists. Thanks for looking into this. We'll see if a friend can provide a tool to do this.
