### ISSUE TITLE
Authme similar nicks bug

### ISSUE THREAD

**Issue by Nightick** [Xephi/AuthMeReloaded#461]
Hi all! I face a problem. If, for example player "Player" is on the server and he is logged in if the second user try to log in with nick "plAyEr", the first user would be unlogged, and the second one is allowed to join the server

**Comment by games647** [comment]
Which version do you use?

**Comment by Nightick** [comment]
The latest Authme version. And 1.8.8-R0.1-SNAPSHOT spigot version.

**Comment by games647** [comment]
From BukkitDev or Jenkins?

**Comment by Nightick** [comment]
The second one

**Comment by Nightick** [comment]
Plugin version. whops. From Bukkit

**Comment by sgdc3** [comment]
@Nightick Please use this version: http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT.jar
and enable the preventOtherCase option in the configuration. ;)

**Comment by Nightick** [comment]
Thank your so much :+1:

**Comment by sgdc3** [comment]
You're welcome ;)

**Comment by Nightick** [comment]
Sry, one more quest, after login command server broadcast "@playername joined the game", i can't find any settings in config for this case and, also, hide stream doesn't help

**Comment by Nightick** [comment]
Oh, i understand, it's okey

**Comment by Nightick** [comment]
Oh, and what permissions should i give player to let them log in, they are complainging that, they don't have perms for login
