### ISSUE TITLE
AuthMe and EssentialsSpawn

### ISSUE THREAD

**Issue by Kixot14** [Xephi/AuthMeReloaded#463]
Essentials spawn have feature to set 2 spawn points: 1 normal, and 1 for newbie players.
But this newbie spawn don't actual, because AuthMe always teleport all players on general spawn. Even if i disable ''teleportUnAuthedToSpawn", then newbies spawn on newbies point, but after move authme teleport them to general spawn.

I wanna to teleport unauthed users to spawn, but newbies(who first time join on server) to newbie spawn-point, and all others to general.

Can you fix that??

**Comment by Kixot14** [comment]
if set essentials first on 'spawnPriority' it's don't help to!

**Comment by Kixot14** [comment]
And little bug: AuthMe don't remember your eye point (pitch and yaw) after relog. Always turn you to 0. and 0.

**Comment by DNx5** [comment]
yeah, because we only store x,y,z into the database.

**Comment by Kixot14** [comment]
So can you store Facing position into database to ??

**Comment by ljacqu** [comment]
@Kixot14, is the main question here solved? I think the wisest way to solve this is to use only Essentials spawn or AuthMe's spawn. The difference between Essentials' newbie spawn and AuthMe's firstspawn is that a player will go to AuthMe's firstspawn for as long as he isn't registered.
