### ISSUE TITLE
Default message "player join the game"

### ISSUE THREAD

**Issue by DardBrinza** [Xephi/AuthMeReloaded#464]
After installing the latest build # 696, after authorization players in the chat default message appears "player join the game". In his plugin, I turned off the message, but after installing the latest build it began to appear after a successful login.

**Comment by DNx5** [comment]
So, you have a plugin that prevent/edit the join message?

**Comment by DardBrinza** [comment]
Yes, I use a plugin to hide this message and authme #682 and this is no problem.

**Comment by sgdc3** [comment]
We need to listen to the join message at lowest priority... @DNx5

**Comment by DNx5** [comment]
i already do that. maybe the code has changed.

**Comment by DNx5** [comment]
Try this, and see if it works.
http://ci.xephi.fr/job/AuthMeReloaded/699/artifact/target/AuthMe-5.2-SNAPSHOT.jar

**Comment by DNx5** [comment]
@DardBrinza are you using essentials to remove join message?

**Comment by DardBrinza** [comment]
@DNx5 No, I use not public plugin

**Comment by sgdc3** [comment]
@DardBrinza have you tried the file @DNx5 posted?

**Comment by DardBrinza** [comment]
Fixed. Thanks
