### ISSUE TITLE
Adding full localization file.

### ISSUE THREAD

**Issue by DardBrinza** [Xephi/AuthMeReloaded#465]
Can you add a file that you can locate all of  authme (/authme; /authme help; /authme about; /authme "all command")? Thanks :)

**Comment by DNx5** [comment]
This file?
https://github.com/AuthMe-Team/AuthMeReloaded/blob/master/src/tools/docs/commands.md

**Comment by DardBrinza** [comment]
Yes

**Comment by DNx5** [comment]
What do you mean?

**Comment by DardBrinza** [comment]
Translate this
http://joxi.ru/vAWYJVdTkBzPZm.jpg
http://joxi.ru/LmG3L7bTRgjPem.jpg
http://joxi.ru/V2VeNGWu08OPam.jpg
http://joxi.ru/KAgMxENIgN0Wnm.jpg

**Comment by DNx5** [comment]
related to #293
