### ISSUE TITLE
Random /logout

### ISSUE THREAD

**Issue by DardBrinza** [Xephi/AuthMeReloaded#466]
My players randomly receive removal authorization during the game on the server. The chat messages are not displayed with the requirement to enter a password. A player blocks all commands, motion and more, and if you enter /login "password" it will display a message about the successful authorization and the game continues. It happens randomly, you can play 10 minutes or 8 hours, this is impossible to predict.

**Comment by sgdc3** [comment]
@DNx5 we need to log into the console the cause of the logout. (Command, Api, etc...)

**Comment by DNx5** [comment]
duplicate? #419

**Comment by DardBrinza** [comment]
Yes, but I did not get the message about the end of the session or a message to enter the password .

**Comment by DNx5** [comment]
Same issue
https://github.com/Xephi/AuthMeReloaded/issues/419#issuecomment-169858260

**Comment by DardBrinza** [comment]
My plugins:
Plugins (51): SmokeTrail, RemoteToolkitPlugin, PlugMan, DynPad, MaxBans, stAnalytics, RandomPort, CoreProtect, WorldEdit, RainbowArmour, OpenInv, Essentials, SunCraftCases (My case plugin), ClearLag, AutoMessage, SuperDupe, Chairs, WorldBorder, Multiverse-Core, dtlCore, Fixer (My small fix with mobs), MCDonate, PermissionsEx, FeatherBoard, MineResetLite, CustomJoinItems, Vault, UralClans, ProtocolSupport, MobArena, BankRobbery, Scavenger, KillerMoney, Marriage, WorldGuard, ChestCommands, EssentialsSpawn, TitleManager, CraftArrows, MyPet, AnimatedNames, CrackShot, LimitedWorldEdit, ProtocolLib, LibsDisguises, NoCheatPlus, Citizens, AntiTab, AuthMe, All-U-Want_fix, dtlTraders

**Comment by ljacqu** [comment]
Thanks for the report – this bug will be handled with the linked issue, so please watch it to receive notifications if interested.
