### ISSUE TITLE
Players Play Without Loggin In

### ISSUE THREAD

**Issue by UberNoel** [Xephi/AuthMeReloaded#468]
I've been hosting a cracked server for 6 months now , using Authme , no problems until recently 4 hours ago , my admin told me that everyone can play without logging in . I quickly stopped my server before members starts logging in into my staffs account or mine . I've tried reinstalling the plugin and did everything i could for few hours. May i know how to solve this ?

**Comment by games647** [comment]
Which version do you use? Do you have any errors in the log?

**Comment by sgdc3** [comment]
@UberNoel

**Comment by sgdc3** [comment]
No answer
