### ISSUE TITLE
caching nickname case error.

### ISSUE THREAD

**Issue by Asmprog** [Xephi/AuthMeReloaded#47]
It seems to me that there is an error:
https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/datasource/CacheDataSource.java#L27

put in cache not lowercase, but cache.containsKey lowercase.

https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/datasource/CacheDataSource.java#L37
https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/datasource/CacheDataSource.java#L44

If caching is true, and user name in database contains uppercase character, isAuthAvailable always return false.

**Comment by Worldbeater** [comment]
+1

**Comment by Trojaner25** [comment]
+1

**Comment by Xephi** [comment]
Fixed https://github.com/Xephi/AuthMeReloaded/commit/b75adf6a981e68d350ee6d5d6056f023f217c290
Sorry u.U
