### ISSUE TITLE
API: ForceRegister doesn't work

### ISSUE THREAD

**Issue by games647** [Xephi/AuthMeReloaded#473]
Testcase:

If the player joins the server invoke the command after a delay of 3 seconds:

Output:
[16:57:16 INFO]: games647[/127.0.0.1:58689] logged in with entity id 7291 at [...]
[16:57:26 WARN]: [AuthMe] null

**Comment by games647** [comment]
BTW: logConsole property is missing from the config.

**Comment by sgdc3** [comment]
@ljacqu

**Comment by ljacqu** [comment]
Good catch on the "logConsole" property—I'll make sure to add it on the branch for #450, which should be merged within this week.
