### ISSUE TITLE
PhpBB 3.1

### ISSUE THREAD

**Issue by Giulio1708** [Xephi/AuthMeReloaded#474]
Hi there,
I know that the PhpBB integration is actually work in progress, but I'm here to ask a question.
I configured AuthMe and Phpbb trying to login with my password and the server says that my account isn't verified and that I have to check my email inbox to validate it.

**Comment by Giulio1708** [comment]
Well, solved reinstalling the plugin.

**Comment by ljacqu** [comment]
Happy to hear it! Thanks for the update.
