### ISSUE TITLE
IPB

### ISSUE THREAD

**Issue by White6983** [Xephi/AuthMeReloaded#475]
AuthMeReloaded have support for IPB 3.4.8/9 ?

**Comment by Giulio1708** [comment]
Yes

**Comment by White6983** [comment]
Maybe you have a configuration file?

**Comment by Giulio1708** [comment]
I haven't, but if you post your config and a screen of the user table I'll try to help you out.

**Comment by White6983** [comment]
Working... wrong column name with salt:D
