### ISSUE TITLE
Authme's mysql table uses bigint instead of timestamp

### ISSUE THREAD

**Issue by ravkr** [Xephi/AuthMeReloaded#477]
mysql table created by AuthMe is using `bigint(20)` on `lastlogin` column but `timestamp` would be better. almost all programs made for managing mysql shows date and time when column is using `timestamp` type.
now we have eg. `1454151480984` but after changing type it would show eg. `2016-01-30 10:58:00`

**Comment by sgdc3** [comment]
@Xephi @DNx5 @ljacqu @games647

**Comment by ljacqu** [comment]
I'll bite; I assigned another sql issue to myself so I can also do this while I'm there

**Comment by sgdc3** [comment]
Thanks ;)

**Comment by ljacqu** [comment]
I thought this was going to be easy >.< I spent about four hours on this so far.

**Comment by sgdc3** [comment]
Wtf? @ljacqu xD

**Comment by ravkr** [comment]
good job @ljacqu XD

**Comment by ljacqu** [comment]
Thanks—it's still on a branch currently :P I will have it done within this week sometime (Wednesday?, Thursday?). Still having some weird bugs where the timestamp is saved as 0000-00-00...

**Comment by sgdc3** [comment]
Why do we need to save 00-00-0000 ? xD

**Comment by ljacqu** [comment]
@sgdc3 Heh no, for some reason it kept writing that timestamp into the DB. Looks like I just missed a method that was still talking to the DB with the `long` format, instead of the new `timestamp`

@ravkr I think this (_finally_) concludes our story. Please close it if so, or let us know what is still open :)

**Comment by ljacqu** [comment]
As discussed in #542, lastlogin had to be reverted from timestamp back to bigint. The suggestion to use the `timestamp` was very good but unfortunately had some undesirable consequences.
