### ISSUE TITLE
AuthmeBridge not working

### ISSUE THREAD

**Issue by k3ldon** [Xephi/AuthMeReloaded#478]
Hi, I recently upgraded to the latest version and no longer works authme + authmebridge...
any idea what things changed?
=/

AuthMe v5.2-SNAPSHOT-b702
and
AuthmeBridge:
https://www.spigotmc.org/resources/authmebridge-for-bungeecord.574/

**Comment by sgdc3** [comment]
AuthMeBridge is not an official authme addon and it seems to be abbandoned... We are working on an official replacement ;)
