### ISSUE TITLE
delayJoinMessage option not working

### ISSUE THREAD

**Issue by Trojaner25** [Xephi/AuthMeReloaded#479]
> delayJoinMessage: false

But still join messages are delayed and only shown on login

**Comment by sgdc3** [comment]
@DNx5 @games647 Can you check this please? Thanks ;)

**Comment by Trojaner25** [comment]
push

**Comment by sgdc3** [comment]
try with delayJoinLeaveMessages: false

**Comment by ljacqu** [comment]
@Trojaner25 Guessing this is OK to be closed?

**Comment by sgdc3** [comment]
I'm sure it works now ;)
