### ISSUE TITLE
Bug reg_only

### ISSUE THREAD

**Issue by Kedarin** [Xephi/AuthMeReloaded#48]
When players are trying to connect message is displayed them I do not understand: 
Registered players only! Please visit http://example.com to register

**Comment by Xephi** [comment]
kickUnregistered on true

Or :

registration->enabled on false

Xephi

**Comment by Kedarin** [comment]
kickUnregistered on true ---> don't have

registration->enabled on false ---> After her: Registration is disabled

**Comment by Kedarin** [comment]
i Think it's ok

**Comment by Kedarin** [comment]
Still the same problem, I put MaxRegIp = 0 suddenly they can have infinite account ..

**Comment by Xephi** [comment]
Expected ^^"

2015-06-04 16:47 GMT+02:00 Kedarin <notifications@github.com>:

**Comment by Kedarin** [comment]
So how fixed? ^^

**Comment by Xephi** [comment]
All of your player can't join cause they're not registered ? , what's your authme version please?
