### ISSUE TITLE
Output from the server in the air.

### ISSUE THREAD

**Issue by DardBrinza** [Xephi/AuthMeReloaded#480]
Hi. Faced with the problem of the players output from the server through the air, and then they can not enter the password (closes chat and kicked from server with the reason: You can not fly). There is a suggestion: Add a feature that will put the player on the ground before authorization (was in the air, puts it on the ground, he enters the password and sends it back into the air)

**Comment by Platinteufel** [comment]
#452

**Comment by DardBrinza** [comment]
Sorry :D
