### ISSUE TITLE
Server Lagging So Much When A player joins

### ISSUE THREAD

**Issue by UberNoel** [Xephi/AuthMeReloaded#481]

**Comment by UberNoel** [comment]
http://pastebin.com/qzqfj7Rx
This error keeps spamming in my console over and over the lag wont stop when a player joins

**Comment by ljacqu** [comment]
If we look at the last few lines of the error:

> 31.01 15:46:09 [Server] WARN at **com.xmasterproxhd.stopbot**.Main.onPlayerJoin(Main.java:224)
31.01 15:46:09 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
31.01 15:46:09 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
31.01 15:46:09 [Server] WARN java.io.IOException: **Server returned HTTP response code: 502 for URL: http\://www.projecthoneypot.org/ip_175.136.186.181**

Seems like you have another plugin, something called stopbot or similar? "com.xmasterproxhd.stopbot" is not us. From the error we can see that it wants to connect to projecthoneypot.org, but it returned a response code of 502: _Bad Gateway_. And indeed, if you visit projecthoneyport.org, currently it is down and shows exactly that message.

i.e. it's an error on the website's side. Might still be useful to alert the author about these errors as maybe he can do some better error handling.

**Comment by UberNoel** [comment]
ok thanks for ur reply ill try removing the plugin

**Comment by ljacqu** [comment]
Good luck!
