### ISSUE TITLE
AuthMe with IPB4

### ISSUE THREAD

**Issue by Feerko** [Xephi/AuthMeReloaded#483]
Hello, 

Connection to the database is correct. The problem is with a password. Typed password does not match.

Authme Version: v5.2
Config: http://pastebin.com/raw/zy193eyL

I hope for a quick response. Thanks! :)

**Comment by ljacqu** [comment]
Looks like IPB4 does password hashing differently from IPB3. Do you know anything more about what's done? Failing so, could you maybe share a hash or two for us to test against?

**Comment by Feerko** [comment]
Ok :)

pass: password
hash: $2a$13$hTUJkHi6NNjgFUhcKqodqOJEkaasnksrD1a3phmjhB9OXF7TtKLWO
salt: OPYU52RvYD2mPReSvIYafn

pass: StrongPassword!
hash: $2a$13$n0GJE9D1aPCWMmPk07VnfuyiV/N/Wsj.vkUtJq5wYzdG.7lInZMEC
salt: n0GJE9D1aPCWMmPk07Vnf8

**Comment by ljacqu** [comment]
Oh, cool, you rock!
I wonder what the salt does—seems like the hash is enough to validate the password. In your config, could you please try:
```
    passwordHash: BCRYPT
```

maybe you also need to set
```
  bCryptLog2Round: 13
```
so that the hashes generated by AuthMe also follow the `$2a$13$` format, but I would assume that it works with any number.
It's possible that players who register with AuthMe won't be able to log into the forum since the `BCRYPT` hash won't store this additional salt column. However, I have no idea how it comes into play.

**Comment by Feerko** [comment]
BCRYPT 13

pass: StrongPassword!
hash: $2a$13$QpurEu2SgqbS7n.nR26bbu8Oa.IoqCl4aXApvUXXc2UoG0PrdhyPS

Unfortunately, a different result.

**Comment by ljacqu** [comment]
Thanks for the info. In that case we'll need to take a closer look at it. Note that it generating a different hash doesn't necessarily mean it's wrong, but of course since the forum doesn't accept it, something is wrong.

**Comment by Feerko** [comment]
Thank you @sgdc3 ! When can I expect some small updates? Few hours ago I bought IPB and I'm very excited, but I can not move forward because AuthMe does not support IPB4.

Players are waiting and I can not do anything.

Greetings.

**Comment by sgdc3** [comment]
@Feerko Why me? @ljacqu is the one you need to thanks ;)

**Comment by Feerko** [comment]
You right :)

**Comment by ljacqu** [comment]
I'm afraid I already have a lot of things in AuthMe to take care of so I won't have time to look at this in greater detail. Maybe someone else from the dev team can.

**Comment by Feerko** [comment]
Hello there. 
Are there any progress with this? I must admit that I really really care about.

**Comment by Feerko** [comment]
Please?

**Comment by Maddeningmorel** [comment]
Hi, I have the same problem. Is anyone working on fixing this?

**Comment by sgdc3** [comment]
@Feerko @Maddeningmorel We are all volunteers in the team, please be patient...

**Comment by ljacqu** [comment]
I'm not taking on any issues before I finish the ones I assigned myself to (besides any unstarted [Dev]). 
What you lads could kindly do to speed up the process is if you have any php knowledge – if so, you could find out what IPB needs in the db for the login to work (like why there is this salt column).
Alternatively, we could look into having a Skype session sometime to have a look together. I'm a native speaker of German and French, in case that would coincidentally match someone's mother tongue... ;)

**Comment by Feerko** [comment]
It's hard to be patient when you spend on licensed almost 200 dollars and there's nothing you can do.

Okay, I'm in despair. I really want this.
Someone will do it for payment on paypal?

**Comment by sgdc3** [comment]
@DNx5 @games647 @ljacqu I can only bump this report..

**Comment by ljacqu** [comment]
@Feerko Money is not an incentive for me, but if you have the possibility to have a Skype session together sometime, we could kick some butt ;3
I speak German and French natively in case that would luckily coincide with your mother tongue

**Comment by Feerko** [comment]
Moj angielski jest zbyt kiepski, żeby rozmawiać a ojczysty język to Polski.
Może przyda Wam się moja tabela z użytkownikami ipb4? Mogę dodać pare rekordów.

http://pastebin.com/raw/7PnpPZFf

test:test123
ljacqu:ljacqu123
sgdc3:sgdc3123
someother:3vbQ(y7Pw$K2j'?;

Please write if I could somehow help.

**Comment by ljacqu** [comment]
Thanks, that's already a great help. The real question is what this `members_pass_salt` column does. Do you know php? We need to find out where it's used in IPB.

**Comment by Feerko** [comment]
I understand PHP syntax but do not encode. Ok, I'll try to find it. Give me a moment.

**Comment by Feerko** [comment]
It's been almost a week. :C

**Comment by sgdc3** [comment]
@Xephi can you help us? ;)

**Comment by Feerko** [comment]
Please? :)

**Comment by sgdc3** [comment]
@Xephi @Xephi @Xephi @Xephi @Xephi @Xephi @Xephi @Xephi @Xephi @Xephi @Xephi @Xephi @Xephi @Xephi @Xephi @Xephi @Xephi @Xephi @Xephi @Xephi @Xephi @Xephi @Xephi @Xephi 
-----
Sorry for the spam xD

**Comment by Feerko** [comment]
@games647 I see that you take care of 2fa You can also look at it?

**Comment by sgdc3** [comment]
Bump, any volunteer?
@Xephi @ljacqu @games647 @DNx5

**Comment by games647** [comment]
@sgdc3 Me!

It looks like IPB4 uses bcrypt but with a higher cost value.

**Comment by sgdc3** [comment]
@games647 Thanks ;)

**Comment by games647** [comment]
@Feerko Do you use AuthMe for registrations or logins?

**Comment by Feerko** [comment]
After using the new version also works. Yey!
But now I have a problem with the Maven http://pastebin.com/raw/sFCbq5mv

I have to recompile, beacuse...
https://github.com/AuthMe-Team/AuthMeReloaded/blob/9cf7405f63b2e5bddf48c1e9487ce9f96d638088/src/main/java/fr/xephi/authme/listener/AuthMePlayerListener.java

@EventHandler(ignoreCancelled = true, priority = EventPriority.HIGHEST)
It spoils my script on anti-bot. I created a "captcha" in inventory before registration.

**Comment by Feerko** [comment]
I was wrong. it doesn't work. In a database column of salt it is null.

**Comment by Feerko** [comment]
I know what the problem is. 
Registrations have on the server. 
Forum is used to login, password recall and change the password.

When you register on the server does not fill the field with salt.
Salt is not necessary to login on the server.
To login on to the forum is needed.

**Comment by games647** [comment]
>To login on to the forum is needed.

That's weird, because the salt is included in the bcrypt hash. It's the first 22 characters after the $.

**Comment by Feerko** [comment]
Really. 
Hmm... If the salt is not needed, then there wouldn't be salt column. 
I don't know what IPB invented.

**Comment by games647** [comment]
@Feerko Does it work if you copy the salt into the salt column?

**Comment by Feerko** [comment]
It worked when I changed the password to other in admin panel and automatically created the salt.

**Comment by ljacqu** [comment]
@Feerko: random guess, what if you add a "salt" (random text of same length as the others) into the column? 
It wouldn't make sense to persist it but maybe IPB uses a second salt for some other purposes, like creating a safer cookie to signal to the server that the user is logged in (just putting the password hash has security implications, so it's a possibility they went that way)

**Comment by ljacqu** [comment]
If so, the implementation is easy: use BCrypt (with 13 as number of rounds?) + add behavior to persist a random string of fixed length to the column

**Comment by Feerko** [comment]
I did it in a rather unusual way. In authme did execute commands at registration. In the script I cut the string, so that came out of the salt. It works.

set {_salt} to index 0 of objects in column "members_pass_hash" from result of query "SELECT members_pass_hash FROM core_members WHERE member_id=%{id.%arg-player%}%;"
set {_salt} to the first (index of "" in {_salt} + 28) characters of {_salt}
replace all "$2a$13$" with "" in {_salt}
update "UPDATE core_members SET members_pass_salt = '%{_salt}%' WHERE member_id=%{id.%arg-player%}%;"

**Comment by games647** [comment]
@ljacqu So maybe we should save the salt in the salt column although it's not needed.

**Comment by DNx5** [comment]
This looks like xenforo
```
/Users/feerko/Downloads/ips_d6298/system/Member/Member.php:
 2057  	{
 2058  		/* New password style introduced in IPS4 using Blowfish */
 2059: 		if ( mb_strlen( $this->members_pass_salt ) === 22 )
 2060  		{
 2061: 			return crypt( $password, '$2a$13$' . $this->members_pass_salt );
 2062  		}
 2063  		/* Old encryption style using md5 */
 2064  		else
 2065  		{
 2066: 			return md5( md5( $this->members_pass_salt ) . md5( \IPS\Request::legacyEscape( $password ) ) );
 2067  		}
 2068  	}
```

**Comment by ljacqu** [comment]
@Feerko IPB4 support has been implemented by @DNx5 and should work by setting `passwordHash: IPB4` and `mySQLColumnSalt: 'members_pass_hash'` in your config. Could you please try it out with a recent [development build](http://ci.xephi.fr/job/AuthMeReloaded/)? :) [build 755 or any blue build above]

**Comment by ljacqu** [comment]
Sad that we never got feedback from @Feerko, but I'm assuming that this can be closed.

**Comment by Krokit** [comment]
Hi, script is working with ipb 4, but there is one problem, script doesn't add default group and user can't log in forum.  :) Default group is 3, collum is member_group_id

**Comment by ljacqu** [comment]
Hi @Krokit, if you'd like to discuss about this could I ask you to create a new issue?
