### ISSUE TITLE
Enchantment - Allow to disable help for the plugin

### ISSUE THREAD

**Issue by ghost** [Xephi/AuthMeReloaded#484]
Hello,

I've found an enchantment possibility for your plugin. It'd be nice when we could translate help options in AuthMe, so you could add those options to "message_xx.yml". 

Also, you could add an options to disable help for the plugin.

Thank you.

**Comment by Naxter** [comment]
Also, you could add an option to disable help for the plugin.

**Comment by ljacqu** [comment]
Related to #293

**Comment by ljacqu** [comment]
Unfortunately the OP is now a ghost. Help can be disabled if the translation for all sections is set to empty text in messages/help_xx.yml. This means a player is still able to do /authme help but it will return no answer, not even the help header.
