### ISSUE TITLE
People able to login with any letter case.

### ISSUE THREAD

**Issue by vst8800** [Xephi/AuthMeReloaded#489]
Hi, can you make an option that restricts the players so that they can login only with the exact letter case they have registered only. Now they can change upper case to lower case or lower to upper in their nicks and this way they can cheat things from other plugins.

Thanks a lot in advance,

**Comment by sgdc3** [comment]
Are you using latest version? If yes just enable the "preventOtherCase" setting in the plugin's configur ation. ;)

**Comment by vst8800** [comment]
Hi actually missed that option. Now I see it and it is not enabled. I will try it and if it does what we need I will close the issue. Thanks a lot.

**Comment by vst8800** [comment]
Tried the option. It didn't seemed to work. However our issue was else where. Closing the issue.

**Comment by sgdc3** [comment]
@vst8800 What do you mean? What was the cause? ;) Just to know!

**Comment by vst8800** [comment]
Hi when Donation Points is used the players were able to do dp transfer while not logged in and when logged with different case letters. The solution was to disable the command in the dp config.

**Comment by sgdc3** [comment]
@vst8800 Yeah, but authme should never allow users with different case to join if the preventOtherCase feature is enable. :/

**Comment by vst8800** [comment]
I agree. But in the latest dev builds the server stop letting people joining in after like 10 minutes after the server has loaded and when you stop it is stuck on disabling AuthMe and cannot stop until you hit ctrl + c in the console :/
