### ISSUE TITLE
Suggestion: Kick user if is using the same name but with other case

### ISSUE THREAD

**Issue by i-rme** [Xephi/AuthMeReloaded#49]
In the current version, a user called Notch can login with the username "NotCH", use the same password (/login) to login and he can play.

The problem is that some plugins expect that Notch is a different user than NotCH causing some issues (Users can dupe /money if they do certain trick with different name cases).

Some months ago a plugin kicked the user if he logged in with different case that the first one that he used the first time (it was maybe factions, worldguard or other) but now that feature got removed.

I hope that you could implement that feature into AuthMeReloaded as this plugin works with offline mode servers that are the ones with this problem.

Possible fix:
Store in the "username" row the username as entered by the user (Notch), for all the checks you can convert it to lowercase when needed.
Then, if a user logs into the server with a name that is already in the database but with other case kick him and tell the exact name that he has to input. (Error, your name should be spelled as "Notch").
That way Notch cannot login as NotCH or notch so other plugins dont have to handle this issue.

Thanks for reading and thanks for the plugin

**Comment by orkun1675** [comment]
Merge with #76
