### ISSUE TITLE
Async task %%%%% on stop

### ISSUE THREAD

**Issue by 7h3ev1l** [Xephi/AuthMeReloaded#490]
Every time when server is stopping and i have 100 players i get

**[AuthMe] Progress: 1 / 106
[00:06:43 INFO]: [AuthMe] Async task %%%%% times out after to many tries
and i need to wait like 10 minutes...**

How to skip this???

**Comment by games647** [comment]
Is it just one task or are there more?

**Comment by 7h3ev1l** [comment]
Its more like 
[AuthMe] Progress: 1 / 106
[AuthMe] Progress: 2 / 106
[AuthMe] Progress: 3 / 106
[AuthMe] Progress: 4 / 106

to 106...

**Comment by nathampa0909** [comment]
The players dont be kicked and shouldn't be delay more time!

**Comment by games647** [comment]
@7h3ev1l Are there any more tasks which times out?

**Comment by 7h3ev1l** [comment]
hm, i will check next time

**Comment by sgdc3** [comment]
@7h3ev1l Any update?

**Comment by nathampa0909** [comment]
This is my log when AuthMe disable: http://pastebin.com/nbJMm4EW

When authme try turn off delay more time (In above paste I think 30 minutes!)

**Comment by sgdc3** [comment]
memory leak issue

**Comment by sgdc3** [comment]
@games647

**Comment by nathampa0909** [comment]
Can you do to remove 10 in 10 to remove more fast?

**Comment by games647** [comment]
Thanks a lot that help me to fix it. I'll do that today.

**Comment by DNx5** [comment]
It's broken

**Comment by games647** [comment]
That's why I'm working on it. -.-

**Comment by DNx5** [comment]
Anyway, its no longer necessary. Also, that spamming a lot.

**Comment by nathampa0909** [comment]
Thanks @games I will test the latest version.

**Comment by games647** [comment]
@DNx5 sql save query still runs async...

**Comment by DNx5** [comment]
@games647 that's the point of CachedDataSource

**Comment by nathampa0909** [comment]
@games647 AuthMe build 719 dont turn off, dont have errors and nothing only says that authme is disabling and server bug and dont turn off.

**Comment by games647** [comment]
@DNx5 Could you look into it? You made the changes.

**Comment by nathampa0909** [comment]
I think I found error, see my code:

`
        System.out.println("0");
        // Save player data
        Collection<? extends Player> players = Utils.getOnlinePlayers();
        for (Player player : players) {
            savePlayer(player);
        }
        System.out.println("1");
        // Do backup on stop if enabled
        new PerformBackup(plugin).doBackup(PerformBackup.BackupCause.STOP);
        System.out.println("2");

        // Unload modules
        if (moduleManager != null) {
            moduleManager.unloadModules();
        }
        System.out.println("3");

        // Close the database
        if (database != null) {
            database.close();
        }
        System.out.println("4");

        // Disabled correctly
        ConsoleLogger.info("AuthMe " + this.getDescription().getVersion() + " disabled!");
`

In console:

`
[16:30:30 INFO]: Stopping the server
[16:30:30 INFO]: Stopping server
[16:30:30 INFO]: [AuthMe] Disabling AuthMe v5.2-SNAPSHOT-bUnknown
[16:30:30 INFO]: 0
[16:30:30 INFO]: 1
[16:30:30 INFO]: 2
[16:30:30 INFO]: 3
`

And 7 minutes ago the server don't turned off.

**Comment by sgdc3** [comment]
Database can't be closed, probably due to unfinished tasks.

**Comment by nathampa0909** [comment]
Why @sgdc3 any updates before did not have this problem.

**Comment by sgdc3** [comment]
Because we changed how database queries are managed on server stop.

**Comment by DNx5** [comment]
Try latest code, 
i dont think `database.close();` could block it.

**Comment by nathampa0909** [comment]
Plugin don't stop. Today 10:30 server restart and now I see the console 18:28 the server dont turned off. Build 10:30:29 INFO]: [AuthMe] Disabling AuthMe v5.2-SNAPSHOT-b759

**Comment by DNx5** [comment]
should've been fixed on latest build

**Comment by sgdc3** [comment]
@21218128297289129821389

**Comment by nathampa0909** [comment]
@sgdc3 Well, shows fine. In this: https://github.com/Xephi/AuthMeReloaded/issues/508 someone make the test and it's functional, I cant test in this week.

**Comment by sgdc3** [comment]
@nathampa0909 Thank you ;)
