### ISSUE TITLE
Dependencies of project

### ISSUE THREAD

**Issue by nathampa0909** [Xephi/AuthMeReloaded#491]
Hello, I'm trying to compile AuthMe but I can't, I have this error on try to compile:

Failed to execute goal on project authme: Could not resolve dependencies for project fr.xephi:authme:jar:5.2-SNAPSHOT: Failed to collect dependencies for [com.zaxxer:HikariCP:jar:2.4.3 (compile?), org.slf4j:slf4j-jdk14:jar:1.7.14 (compile?), org.apache.logging.log4j:log4j-core:jar:2.0-beta9 (provided?), org.apache.commons:commons-email:jar:1.4 (compile?), com.google.code.gson:gson:jar:2.5 (compile?), com.maxmind.geoip:geoip-api:jar:1.3.0 (compile?), org.mcstats.bukkit:metrics:jar:R8-SNAPSHOT (compile?), org.bukkit:bukkit:jar:1.8.8-R0.1-SNAPSHOT (provided?), com.comphenix.protocol:ProtocolLib:jar:3.6.5-SNAPSHOT (provided?), ru.tehkode:PermissionsEx:jar:1.23.1 (provided), org.anjocaido:groupmanagerx:jar:2.2-SNAPSHOT (provided), de.bananaco:bPermissions:jar:2.12-DEV (provided), org.tyrannyofheaven.bukkit:zPermissions:jar:1.3-SNAPSHOT (provided), net.milkbowl.vault:VaultAPI:jar:1.5 (provided?), com.onarandombox.multiversecore:Multiverse-Core:jar:2.5 (provided?), net.ess3:EssentialsX:jar:2.0.1-SNAPSHOT (provided?), net.minelink:CombatTagPlus:jar:1.2.1-SNAPSHOT (provided?), de.luricos.bukkit:xAuth:jar:2.6 (provided?), junit:junit:jar:4.12 (test?), org.hamcrest:java-hamcrest:jar:2.0.0.0 (test?), org.mockito:mockito-core:jar:2.0.5-beta (test?), net.ricecode:string-similarity:jar:1.0.0 (compile?)]: Failed to read artifact descriptor for org.bukkit:bukkit:jar:1.8.8-R0.1-SNAPSHOT: Could not transfer artifact org.bukkit:bukkit:pom:1.8.8-R0.1-SNAPSHOT from/to spigot-repo (http://hub.spigotmc.org/nexus/content/groups/public): Failed to transfer file: http://hub.spigotmc.org/nexus/content/groups/public/org/bukkit/bukkit/1.8.8-R0.1-SNAPSHOT/bukkit-1.8.8-R0.1-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Temporarily Unavailable. -> [Help 1]

The owner of project can fix the dependencies plz?

Thanks!

**Comment by sgdc3** [comment]
All the dependencies are working well. Try to run mvn clean before mvn install or delete your .m2 folder

**Comment by nathampa0909** [comment]
Im using Netbeans, how do i run these commands?

**Comment by ljacqu** [comment]
It can't even find Gson or JUnit – this is a problem on your machine.

**Comment by ljacqu** [comment]
`cd` to the project folder (where your pom.xml is) in console and run `mvn clean install`

**Comment by games647** [comment]
Netbeans, IntelliJ and Eclipse can detect Maven projects.
1. Click the open project symbol.
2. Select the folder
3. Netbeans should detect the project folder as maven project.
    (if you have the maven plugin installed, which is default)
4. Then you could click the 'Clean and Build' option
    * or use the custom goal button after you right clicked the project.

**Comment by nathampa0909** [comment]
@games647 I tried what you says but Im having this error: http://pastebin.com/wNimChp8

**Comment by sgdc3** [comment]
Can't reproduce...

**Comment by games647** [comment]
@nathampa0909 Looks like the service was down. Could you try it again? Maybe additional with the the option -U (You could use the yellow button in the output section) added in order to force a repository update.

**Comment by nathampa0909** [comment]
I will test.

**Comment by nathampa0909** [comment]
I downloaded the maven and tried to compile AuthMe but failed.

I used the option -U but have same errors.

[http://pastebin.com/MM3uyprG](url)

**Comment by games647** [comment]
Which repo did you downloaded?

**Comment by nathampa0909** [comment]
This doesn't exists: https://hub.spigotmc.org/nexus/content/groups/public/org/bukkit/bukkit/1.8.8-R0.1-SNAPSHOT/bukkit-1.8.8-R0.1-SNAPSHOT.pom

I tried to use this: https://hub.spigotmc.org/nexus/content/groups/public/org/bukkit/bukkit/1.8.8-R0.1-SNAPSHOT/bukkit-1.8.8-R0.1-20150727.122515-1.pom

**Comment by games647** [comment]
Do you downloaded the AuthMe-Team repo or this repo?

**Comment by nathampa0909** [comment]
AuthMe-Team.

See my pom: http://pastebin.com/ffCGu4EH

**Comment by games647** [comment]
Found it. Add change the repository url of the spigot from http to https.

**Comment by nathampa0909** [comment]
It worked! But I have this errors: http://pastebin.com/v6jBB0jc

**Comment by games647** [comment]
@ljacqu Could you look into it. It's about a unit test from the new settings, which is failing.

**Comment by games647** [comment]
@nathampa0909 What does your config.yml in src/main/resources folder and your config-sample-values.yml in src/test/resources look like?

**Comment by nathampa0909** [comment]
@games647 src/main/resources/config.yml is http://pastebin.com/ARZPDH3B and src/test/resources/config-sample-values.yml is http://pastebin.com/YSEAUEDK

**Comment by games647** [comment]
@nathampa0909 Sorry I don't know why the tests are failing for you, but you could skip tests until we found the cause for it. 

Tools->Options->Java->Maven->Skip Tests
or for command line: -DskipTests=true

**Comment by nathampa0909** [comment]
@games647 Build sucess! Thanks for support! I will contribute with the project.

I use Windows 7 Ultimate 64-bits (I think that helps you to find the problem).
