### ISSUE TITLE
[Dev] Minor - create ConsoleLogger method for exceptions

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#495]
We often do something like 

```java
ConsoleLogger.showError("Could not do the thing: "
    + StringUtils.formatException(ex));
ConsoleLogger.writeStackTrace(ex);
```

This could be summarized as one method on ConsoleLogger with `String message, Throwable th` as arguments

**Comment by Xephi** [comment]
Huuum done i think ;)

**Comment by ljacqu** [comment]
Thanks — assigning to me to make a small change this evening
