### ISSUE TITLE
Already Join Playername can join with ABC like abc to join

### ISSUE THREAD

**Issue by mckite** [Xephi/AuthMeReloaded#496]
We have a problem on a minecraft server,with the plugin AuthMe.
Our server is non-premium so people can join with whatever nickname they want.
Players join on donator nicknames with small letters.Example if the nickname is Milojka and has a donator rank,someone can join with MiLOjKA and he will have the same permissions and perks as the donator rank.When they join it doesn't require login,but register,so they give all the kits because the delay resets and throw all the items.Can someone please tell me how to fix this?We are having trouble with this very long time.
Thanks.. :

**Comment by mckite** [comment]
We have a problem on a minecraft server,with the plugin AuthMe.
Our server is non-premium so people can join with whatever nickname they want.
Players join on donator nicknames with small letters.Example if the nickname is Milojka and has a donator rank,someone can join with MiLOjKA and he will have the same permissions and perks as the donator rank.When they join it doesn't require login,but register,so they give all the kits because the delay resets and throw all the items.Can someone please tell me how to fix this?We are having trouble with this very long time.
Thanks.. :

**Comment by sgdc3** [comment]
What's the plugin version? ;)

**Comment by Platinteufel** [comment]
That's definitely implemented in the dev builds ..
