### ISSUE TITLE
Commands bungeecord before authorization.

### ISSUE THREAD

**Issue by DardBrinza** [Xephi/AuthMeReloaded#497]
There is a problem: if you do not enter a password and write commands bungeecord, they will work. It is very important that command "/alert" and anyone can enter this command to login. How can I fix it?

**Comment by sgdc3** [comment]
We are working on a bungeecord-side plugin to prevent this. Stay tuned! ;)

**Comment by Xephi** [comment]
Can you please test with this ?
http://ci.xephi.fr/job/AuthMeBungee/

**Comment by sgdc3** [comment]
@Xephi It doesn't work....

**Comment by ljacqu** [comment]
@sgdc3 Is this still in progress? 5.2, or 5.3 Beta?

**Comment by sgdc3** [comment]
AuthmeBungee is discontinued, now AuthMeBridge is the official addon.
