### ISSUE TITLE
 3 authme servers use one sqlite db

### ISSUE THREAD

**Issue by Dimatert9** [Xephi/AuthMeReloaded#498]
like this:
![default](https://cloud.githubusercontent.com/assets/8667294/12866211/3a5e5944-cccf-11e5-8082-77e07880a01b.png)

Can you make this? Because i have about 200k+ accaunts and its very difficult to move this db to mysql.

**Comment by sgdc3** [comment]
Impossible, our sqlite structure disallow us to share the same data between servers... You really should convert your db to mysql, Keep in mind that sqlite is slower than mysql, and it may cause sync issues between authme instances!

**Comment by ljacqu** [comment]
> very difficult to move this db to mysql

Why is that? For the reasons mentioned by sgdc3, such a setup really requires MySQL.

**Comment by Dimatert9** [comment]
in authme.db i has lot of duplicates. And when i import a authme.sql using phpmyadmin i has errors.

**Comment by ljacqu** [comment]
Strange. Both datasources (SQLite and MySQL) should have the same restrictions.

**Comment by Dimatert9** [comment]
![image](https://cloud.githubusercontent.com/assets/8667294/12866681/4956d89e-ccdf-11e5-94e0-8197594d2abe.png)

**Comment by sgdc3** [comment]
@ljacqu There is still this issue with duplicates! :/

**Comment by ljacqu** [comment]
@sgdc3 But that's being handled in another issue, right? Do you mean #469?

**Comment by sgdc3** [comment]
Yeah i know, sorry i was lazy xD @ljacqu

**Comment by ljacqu** [comment]
I will "revert" this to the original question and close it since we have another issue dedicated to the duplication issue.
