### ISSUE TITLE
delayJoinLeaveMessages uses default Minecraft join message.

### ISSUE THREAD

**Issue by ImPat** [Xephi/AuthMeReloaded#503]
When enabeling delayJoinLeaveMessages in the config it always outputs the default join message.
If you change the join message in Essentials it still uses the default message.
Could you please change it so we can change the joinmessage in the config? It doesnt need to link in with essentials or any other Plugin. 
Thanks,
ImPat

**Comment by sgdc3** [comment]
@ImPat What's your Authme version? (/authme version)

**Comment by ImPat** [comment]
5.2 Snapshot Build 708

**Comment by ImPat** [comment]
Please also do so with the leave message!

**Comment by sgdc3** [comment]
Join message fixed, working on the leave msg

**Comment by ImPat** [comment]
Thanks, is it in the latest dev build? Do i need to regenerate my config?

**Comment by sgdc3** [comment]
No, the config is the same ;)

**Comment by ImPat** [comment]
ok :+1:

**Comment by Platinteufel** [comment]
Unfortunately I've got the same issue with AuthMe 5.2 beta 1 and the latest EssentialsX dev build.

**Comment by sgdc3** [comment]
Listener priority issue. (Essentials listens at an higher priority)

**Comment by sgdc3** [comment]
@ImPat @Platinteufel Should have been fixed in latest dev build ;)

**Comment by Platinteufel** [comment]
@sgdc3 Tested it with the latest dev build. As soon as I change the JoinLeaveMessages in Essentials to some custom stuff, AuthMe won't delay them anymore. The delay only works if you use the default JoinLeaveMessages. :/

**Comment by sgdc3** [comment]
..... damn essentials

**Comment by Platinteufel** [comment]
So I think it's essentials fault, hm?

**Comment by sgdc3** [comment]
yeah: https://github.com/essentials/Essentials/blob/d36d80933f8f672cd8bb0f210adc23aac10850ea/Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java They listen to the join event and remove the message completely. In order to fix this we need to provide a new setting that allows to set the new join message.

**Comment by Platinteufel** [comment]
Still in progress? :/

**Comment by ljacqu** [comment]
@sgdc3

**Comment by sgdc3** [comment]
Can't fix...

**Comment by sgdc3** [comment]
@ljacqu we should add our custom join/leave messages setting.

**Comment by Platinteufel** [comment]
So this won't be fixed?

**Comment by ImPat** [comment]
@sgdc3 Bump...

**Comment by sgdc3** [comment]
Sorry guys, I'll work on this asap ;)

**Comment by ljacqu** [comment]
Removing "in progress," because, you know... ;)

**Comment by sgdc3** [comment]
Wontfix, you need to use other plugins to change the messages...
