### ISSUE TITLE
When the server restarts reset the password.

### ISSUE THREAD

**Issue by Lthwoibe** [Xephi/AuthMeReloaded#504]
Hello. AuthMe bound to the database. Cms - DLE. Until the server restart all is well come, but after restarting the server, when entering the password, writes that he is wrong. In the log run\disable there are no mistakes. Maybe something with config?

**Comment by sgdc3** [comment]
What's your version? Can you post your config? ;)

**Comment by sgdc3** [comment]
Bump!
