### ISSUE TITLE
Cauldron compatibility issue (same nick online)

### ISSUE THREAD

**Issue by Eisenbahn** [Xephi/AuthMeReloaded#505]
Its becoming too frequent the "a player with this username is already online" and he is not.
(Not sure how is the message in english, but you get the idea.)

Ive tried to disable sessions, force single session and still getting this issue.
AuthMe-5.2-SNAPSHOT

Using cauldron, java7

**Comment by games647** [comment]
Which build do you have?

**Comment by Eisenbahn** [comment]
b185

**Comment by games647** [comment]
That's very old. Could you try it with a newer build?

**Comment by Eisenbahn** [comment]
Can do. But ive tested a new build after generating files with this one, and the commands didnt worked. But i'll try anyway. Which one do you recommend?

**Comment by games647** [comment]
>Which one do you recommend?

The newest.

**Comment by Eisenbahn** [comment]
http://ci.xephi.fr/job/AuthMeReloaded/749/ will be then. 
I'll let you know.

**Comment by Eisenbahn** [comment]
Yep. No command work. 
Eg:
I join and it doenst ask for login or register.
I do like /login mypass it returns in chat
"login password"  in white.

**Comment by games647** [comment]
Do you have any errors in the log?

**Comment by Eisenbahn** [comment]
Yep:
http://pastebin.com/F2VsBA1x

**Comment by sgdc3** [comment]
We need to drop guava usage...

**Comment by sgdc3** [comment]
Or wait, i have an idea! :D

**Comment by Eisenbahn** [comment]
Am i screwed D:?

**Comment by sgdc3** [comment]
@Eisenbahn Can you try this jar? http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT-legacy.jar

**Comment by Eisenbahn** [comment]
Will do.

**Comment by sgdc3** [comment]
Thanks ;)

**Comment by Eisenbahn** [comment]
Loaded fine as i can see. Ill checked logs too. Its fine. 

BUT i havent tested the primary issue i had. I'm still worried.. Files is from 185, now its 740+. Do you think i will have problems if i upload it in the main server and i had to rollback versions?

**Comment by sgdc3** [comment]
Just do a backup before the update ;)

**Comment by Eisenbahn** [comment]
I'm currently using this last version. But still not sure if the primary problem is fixed, cause i havent reached the max players yet. The server is crashing/restarting sometimes tho.

This is the only crash log i got in the first crash:

http://pastebin.com/ixvDQDBs

[]'s

**Comment by Eisenbahn** [comment]
Yep. Another timeout.

**Comment by DNx5** [comment]
looks like not AuthMe fault

**Comment by Eisenbahn** [comment]
Thats possible.
I'm using the old version now. I'll let know if i get timeout or crashes.

[]'s !

**Comment by Eisenbahn** [comment]
Server still fine.. Is there a way i could make sure is/isnt the Plugin? Any way to depure it?

[]'s

**Comment by DNx5** [comment]
i dont know why. but in your crashlog, it show me that your virtual pack plugin is the cause.

**Comment by Eisenbahn** [comment]
Ye, i noticed this crash happened few times before. But again, still giving timeouts. The timeouts/no response happened cause authme somehow. Ive switch back to old version and server still up and fine. :c

**Comment by Eisenbahn** [comment]
Should i start a new possible issue about the timeout then?

**Comment by sgdc3** [comment]
What do you mean?

**Comment by Eisenbahn** [comment]
The new versions works with cauldron and everything, but im getting these timeouts.. Like, server connection getting slower and slower until the console stops.
No timeouts when i put the old version back. 
(I havent tested the nickname online issue yet, cause the server doesnt get full cause of that timeout thing)

My question is if i should make another post here about the possible timeout thing.

[]'s

**Comment by sgdc3** [comment]
Ok if you prefer to open another issue you should ;)
