### ISSUE TITLE
countriesBlacklist is not working

### ISSUE THREAD

**Issue by WindofFreedom** [Xephi/AuthMeReloaded#507]
In all 5.x versions countriesBlacklist is not working on my server. My config file is in attachment
[config.txt](https://github.com/Xephi/AuthMeReloaded/files/124485/config.txt)

**Comment by sgdc3** [comment]
You need to set "enableProtection: true" ;)

**Comment by WindofFreedom** [comment]
If I set "enableProtection: true" it will be enable countriesWihitelist. How do I enable only the blacklist? 
От the [Bukkit site](http://dev.bukkit.org/bukkit-plugins/authme-reloaded/pages/configure-auth-me/) says: 
"Countries blacklisted automatically ( without any needed to enable protection )"

**Comment by sgdc3** [comment]
Ah sorry, i forgot about this ;) Let me check...

**Comment by WindofFreedom** [comment]
)) 
Can I enable only blacklist?

**Comment by sgdc3** [comment]
Yeah with enableProtection: false the blacklist is enabled.

**Comment by sgdc3** [comment]
Maybe players uses proxyes to join the server...

**Comment by WindofFreedom** [comment]
No, player join from countries that have been added to the blacklist

**Comment by Platinteufel** [comment]
IPs from Russia are able to join my server, even I didn't add Russian IPs to the whitelist, just a few countries from EU. :/

![unbenannt](https://cloud.githubusercontent.com/assets/13700636/13035371/cc7f974a-d34e-11e5-87e0-5592f6fa67b7.png)

**Comment by WindofFreedom** [comment]
Russian hackers forever)) But you are right, it's а bug

**Comment by Platinteufel** [comment]
Sorry, deleted my comment. Just a question: My GeoIP.dat is from 2014. Should I delete and regenerate it?

**Comment by sgdc3** [comment]
@Platinteufel :/ Idk if it can be the cause of the issue, but try! ;)

**Comment by WindofFreedom** [comment]
My Geoip is from 2014 too. I have already updated it, hope will help. Thank you!
