### ISSUE TITLE
Timeouts in 750 + ?

### ISSUE THREAD

**Issue by Eisenbahn** [Xephi/AuthMeReloaded#508]
The new versions works with cauldron and everything, but im getting these timeouts.. Like, server connection getting slower and slower until the console stops.
Timeouts are gone when i put the old version back (currently using b185). (I knooow, old)

Java 7, Cauldron.
Happens with all players.

[]'s!

**Comment by DNx5** [comment]
it would help us if you put crash-log or console error here, :smile:

**Comment by Eisenbahn** [comment]
I would, but i got nothing to show :c
It literally just gets harder and harder to join the server until everyone timeouts. (750)

**Comment by DNx5** [comment]
could you do.. timings paste?

**Comment by Eisenbahn** [comment]
Sure. But ill come back with the timings in few days. I'm moving at the moment.

[]'s

**Comment by xyblues** [comment]
I have the same problem

**Comment by sgdc3** [comment]
@xyblues Already reported in issue #490

**Comment by Eisenbahn** [comment]
Ello. Still need timings? If so, how long should i run it?

**Comment by DNx5** [comment]
5mins is okay. or until you get that timeout.

**Comment by Eisenbahn** [comment]
http://timings.aikar.co/?url=15183993



This is NOT my crowded server. That one was around 15 players while was timing.

Im using the last versin right now (821) and got no timeout or any other issues yet.

**Comment by Eisenbahn** [comment]
OK. Server is at 4 players now. I cant even join myself. And apparently noone can :(

**Comment by sgdc3** [comment]
damn :( The timings are ok, nothing suspicious... @DNx5 @games647 any idea?

**Comment by sgdc3** [comment]
@Eisenbahn Can you try latest build? http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT-spigot.jar

**Comment by Eisenbahn** [comment]
Sure. But im using cauldron. Should i get the legacy build? Or that one?

**Comment by DNx5** [comment]
get the legacy build on http://ci.xephi.fr/job/AuthMeReloaded

**Comment by Eisenbahn** [comment]
Got it and been running fine for 30 min.

**Comment by Eisenbahn** [comment]
No timeouts and such. Ill put in my crowded server to test it out.

**Comment by DNx5** [comment]
good to hear that.

**Comment by Eisenbahn** [comment]
What was it changed?

**Comment by DNx5** [comment]
There is no breaking changes, just changed internal code.
you could see the commits if you understand.

**Comment by Eisenbahn** [comment]
Been fine :)
