### ISSUE TITLE
Password security issues

### ISSUE THREAD

**Issue by Maxetto** [Xephi/AuthMeReloaded#51]
So, I've setup some unsafe passwords and, besides that it's telling "The passwords doesn't match" while it could be telling some specific messages like "This password is not safe, choose another", there's an high security issue with /changepassword.

In fact, while it's blocking unsafe passwords and too short passwords during register, with /changepassword neither of these 2 are checked. Results is that people can register with a password and lately change it to 123 (too short password), password (unsafe password), etc.

Also, i would suggest to block with "%p" passwords that matches the username and, if uppercase, also the relative lowercase match.

(I also remind you of this bug that i posted on the bukkit page)
"This may be fixed on new versions, but I want to report it anyway: Basically, if you have "ForceSpawnLocOnJoin: true" and the configured worlds on "ForceSpawnOnTheseWorlds:" and "Session: true", players in one of the Forced Spawn worlds that logged in with session won't get Teleported to Spawn. Using AuthMe 3.4, since I heard 3.5 is pretty Bugged. If you could make a quick fix for 3.4 of this bug, or maybe just post the relative code and I'll build it myself."

Thank you for keeping this plugin up-to-date.

**Comment by Xephi** [comment]
Added here : https://github.com/Xephi/AuthMeReloaded/commit/de2961b75418634c08ccb9f8749e4f31498a8c2c
You can find builds here : http://ci.xephi.fr

**Comment by Maxetto** [comment]
Reopening that, missing the lenght and unsafe password checks.
(From the registration class:)
        if (password.length() < Settings.getPasswordMinLen || password.length() > Settings.passwordMaxLength) {
            m.send(player, "pass_len");
            return;
        }
        if (!Settings.unsafePasswords.isEmpty()) {
            if (Settings.unsafePasswords.contains(password.toLowerCase())) {
                m.send(player, "password_error");
                return;
            }
        }

Plus, I hope you've taken in charge the "%p" placeholder to block the username of the player as password. It's really a must have, many people use the username as password.
