### ISSUE TITLE
Add blocking movement in the Y coordinate.

### ISSUE THREAD

**Issue by DardBrinza** [Xephi/AuthMeReloaded#510]
Hello. Whether motion lock is possible in all the coordinates? This will help me with the players go out of the game. Their pulls down authme and returns them back, so they can not open a chat and to enter their passwords. Thx :)

**Comment by DardBrinza** [comment]
@sgdc3

**Comment by sgdc3** [comment]
@DardBrinza Keep calm xD We are now focused on bugfixes, stay tuned... ;)

**Comment by Platinteufel** [comment]
#452

**Comment by sgdc3** [comment]
i'll close this because the other issue is more clear.
