### ISSUE TITLE
Remove players from tablist, and make they invisible when Hooks.bungeecord: true

### ISSUE THREAD

**Issue by Dimatert9** [Xephi/AuthMeReloaded#512]
Can you add this? And please add fuction to hide join and leave messages.

**Comment by DardBrinza** [comment]
In bungeecord config "tab_list: GLOBAL_PING" change to "tab_list: SERVER"

**Comment by Dimatert9** [comment]
Remove players from tablist and make they invisible with protocollib:
```
        ProtocolLibrary.getProtocolManager().addPacketListener((PacketListener)new PacketAdapter(this, new PacketType[] { PacketType.Play.Server.PLAYER_INFO }) {
            public void onPacketSending(final PacketEvent e) {
                e.setCancelled(true);
            }
```
remove messages: 
```
e.setQuitMessage((String)null);
e.setJoinMessage((String)null);

```
can you add this to this plugin. And add config functions for this?

Thanks

**Comment by sgdc3** [comment]
@Dimatert9 Done ;)

**Comment by ljacqu** [comment]
@sgdc3 
Why is there a `catch (FieldAccessException e)`? I don't see anything that would throw that.

**Comment by sgdc3** [comment]
I don't know, i think it's required with old protocol version :/

**Comment by Dimatert9** [comment]
@sgdc3 What version i need to download? Authme-legacy or -spigot?

**Comment by sgdc3** [comment]
legacy is for 1.7.10 and cauldron. spigot is for 1.8.x

**Comment by ljacqu** [comment]
@sgdc3 I've added this info to the Wiki https://github.com/AuthMe-Team/AuthMeReloaded/wiki/AuthMe-Releases-%28Jenkins%29 Please update or complete it if something is not good. You understand this better than I do

**Comment by Dimatert9** [comment]
http://pastebin.com/9y1W3ZBw

**Comment by sgdc3** [comment]
@games647 What do you think about this error?

**Comment by Dimatert9** [comment]
http://pastebin.com/mCqyXK9r

in this plugin code is work.

**Comment by ljacqu** [comment]
The messages suggests we have to override the `onPacketSending()` as well, see the [code and javadoc](https://github.com/aadnk/ProtocolLib/blob/master/ProtocolLib/src/main/java/com/comphenix/protocol/events/PacketAdapter.java), as well as [this](http://dev.bukkit.org/bukkit-plugins/protocollib/forum/50417-cant-use-time-update-event/)

**Comment by Dimatert9** [comment]
Thanks. Fix is work.

**Comment by ljacqu** [comment]
Thanks for the feedback :)
