### ISSUE TITLE
[Dev] Link tool task execution to Maven lifecycle

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#513]
Find a way to link the tool tasks that make sense to our maven life cycle. The docs only make sense to have on the repository and it would be nice if all files corresponded to the ones in the repository, so this might be a little tricky

**Comment by ljacqu** [comment]
@sgdc3 One question about this, what are we trying to achieve?

If we run some sort of java class _during the build_, it will generate files we'll never see on the repo (so they will be generated on Jenkins, or wherever). Or is the idea to run a maven command locally and to then commit the changes?

**Comment by sgdc3** [comment]
When you compile the project on your ide the changes are commited by git ;)

**Comment by sgdc3** [comment]
The only issue is that those file will update everytime you compile the project (due to the header of the file that tells the date of generation of the docs)

**Comment by sgdc3** [comment]
But the main issue with this system is that your tool class loader fails to load classes, idk why. :(

**Comment by ljacqu** [comment]
@sgdc3 I managed to fix it, thanks for the feedback. You're right about the gen files, maybe we can execute it only when a certain profile is enabled? e.g. we already have the "jenkins" profile. This way when we run the build on Jenkins/CircleCI and friends they won't execute any useless tasks.

**Comment by sgdc3** [comment]
Yeah but we don't want to make jenkins commits changes to github. Anyway, we need to avoid docs update if nothing has changed (= don't change the generation date and time if nothing has changed)

**Comment by ljacqu** [comment]
Yes, maybe we can make another profile and have it run only then.

**Comment by sgdc3** [comment]
It should be linked to the install lifecycle, in my opinion we shoudl't update the latest doc update timestamp if nothing has changed.

**Comment by ljacqu** [comment]
install is a great idea. Then we can still do verify without updating docs

I partially agree about the timestamp—if nothing changes for three months it might be good to update the date anyway, as not to appear outdated. However, this definitely doesn't need to be done on a frequent basis.
One concern I still have is that the docs might be committed (accidentally or not) with other, irrelevant things. I don't want a commit like "fix email registration" to update the docs as well if it has nothing to do with it at all

**Comment by ljacqu** [comment]
@sgdc3 Where do we remain with this?

**Comment by sgdc3** [comment]
idk xD probably the current solution is the best one.

**Comment by ljacqu** [comment]
Then I would suggest we remove the execution from the pom -> one less plugin / execution we depend on. Whoever notices that docs are getting old can run the updateDocs task; there's one that should run all of the tasks ^^ What do you think, @sgdc3?

**Comment by sgdc3** [comment]
Just keep the plugin but remove the task.

**Comment by ljacqu** [comment]
Assuming that this can be closed after 7229a8b02b850e38a51dd2d8963938c994cc16bf

**Comment by ljacqu** [comment]
I closed too hastily; one improvement I can still do is making sure it runs the correct list of tasks
