### ISSUE TITLE
Welcome Message

### ISSUE THREAD

**Issue by solidern** [Xephi/AuthMeReloaded#517]
Hi, welcome message not working. When setting useWelcomeMessage: true or BroadcastWelcomeMessage: true, so are not working. In older versions working properly

**Comment by ljacqu** [comment]
What `/authme version` are you using? I did a test with the most recent and it worked. The welcome message only appears when a user _registers_, not logs in.

We recently moved the welcome message from config.yml to a separate welcome.txt. If you don't have a welcome.txt in the same folder as config.yml, then something is wrong and we need to investigate. It should create it automatically.

**Comment by RoinujNosde** [comment]
# Enable to display the welcome message (welcome.txt) after a registration or a login
    # You can use colors in this welcome.txt + some replaced strings:
    # {PLAYER}: player name, {ONLINE}: display number of online players, {MAXPLAYERS}: display server slots,
    # {IP}: player ip, {LOGINS}: number of players logged, {WORLD}: player current world, {SERVER}: server name
    # {VERSION}: get current bukkit version, {COUNTRY}: player country
    useWelcomeMessage: true

> after a registration or a login

**Comment by sgdc3** [comment]
@solidern Yeah maybe you misread how the welcome message works, look at @RoinujNosde 's comment ;)

**Comment by RoinujNosde** [comment]
Nope, he did not misread.
The welcome message should be displayed on register or login, but it's only displayed on register.

**Comment by sgdc3** [comment]
ah ok ;) let me check...

**Comment by RoinujNosde** [comment]
![authme](https://cloud.githubusercontent.com/assets/6441328/13142289/4ec0dc1a-d623-11e5-82e2-673c0059a651.PNG)
Build 797.

**Comment by ljacqu** [comment]
The question is now whether we should show the welcome message for register _and_ login, or if we should adjust the description.

**Comment by ljacqu** [comment]
My personal opinion is the first because the config clearly says register **and** login, and that's probably more useful for a server owner. @sgdc3 Thoughts?

**Comment by sgdc3** [comment]
@ljacqu yeah, you're right, maybe we'll split this feature into two options in the future ;)

**Comment by ljacqu** [comment]
So for now I'll do it for both and I'll call it a day

**Comment by sgdc3** [comment]
ok

**Comment by ljacqu** [comment]
Please verify. (@solidern or @RoinujNosde)

Welcome message upon login was changed to be shown only on email registration...? https://github.com/AuthMe-Team/AuthMeReloaded/commit/48b845b That wasn't even so long ago but I don't remember the context, so I undid that check.

**Comment by RoinujNosde** [comment]
Build 807:
Fixed.

**Comment by ljacqu** [comment]
Thanks for verifying!
