### ISSUE TITLE
Website integration code sample prone to SQL injection

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#518]
The php code at http://dev.bukkit.org/server-mods/authme-reloaded/pages/web-site-integration/ uses the deprecated mysql_ function family and does not use a prepared statement for inserting the name into the query

**Comment by ljacqu** [comment]
@Xephi Not asking you replace the code in the link with mine, but the SQL injection needs to be fixed. I'd also be satisfied with a mention on that page or something.

**Comment by sgdc3** [comment]
I can edit the bukkit page now. What do you need?

**Comment by ljacqu** [comment]
Oh, neat! I'll create a fix to the code on the page (so it's still relatively small, as opposed to the code I've committed) and I'll report back.

**Comment by ljacqu** [comment]
@sgdc3 I have a fix for the code on the page, which uses mysqli instead of mysql and makes use of prepared statements. It's shorter than my previous commit, but not by much (because of some additional error handling / dealing because of the prepared statement).

I could imagine the page to look something like below. What do you think? :)

<hr />

## Website Integration

**Web integration**  [<-- please fix the current "Wweb"]
**Function to check SHA256 passwords**
```php
// Returns true if the username and password combination is valid
function authme_check_password($username, $password) {
    $hash = get_hash($username);
    if ($hash) {
        $parts = explode('$', $hash);
        return count($parts) === 4 
            && $parts[3] === hash('sha256', hash('sha256', $password) . $parts[2]);
    }
    return false;
}

// Gets the user's hash from the database
function get_hash($username) {
    // IMPORTANT: Adjust the database host, user, password and database name here!
    $link = mysqli_connect('HOST', 'USER', 'PASSWORD', 'NAME');
    $authme_table = 'authme';

    if ($link) {
        $stmt = mysqli_prepare($link, "SELECT password FROM $authme_table WHERE username = ?");
        mysqli_stmt_bind_param($stmt, 's', $username);
        mysqli_stmt_execute($stmt);
        mysqli_stmt_bind_result($stmt, $hash);
        var_dump($username, $stmt);
        if (mysqli_stmt_fetch($stmt)) {
            return $hash;
        }
    } else {
        printf('Unable to connect to database, errno: %d, error: "%s"',
            mysqli_connect_errno(), mysqli_connect_error());
    }
    return null;
}
```

You can find it integrated into a demo form at the dev repo's [/samples/website-integration](https://github.com/AuthMe-Team/AuthMeReloaded/tree/master/samples/website_integration).

**Comment by sgdc3** [comment]
@ljacqu Thanks, can you take a look at the oldest issues in the issuetracker please? ;)

**Comment by sgdc3** [comment]
Done!

**Comment by ljacqu** [comment]
Beautiful, thanks! Could we maybe link to [/samples/website-integration](https://github.com/AuthMe-Team/AuthMeReloaded/tree/master/samples/website_integration) on the page? It has a sample form to quickly test that it works, and integration.php is a little different (but compatible)

**Comment by sgdc3** [comment]
I missed that xD

**Comment by ljacqu** [comment]
If you don't like it we can skip it :P

**Comment by sgdc3** [comment]
Done, sorry!

**Comment by ljacqu** [comment]
Thank you very much :blush:

**Comment by sgdc3** [comment]
@ljacqu can you login into gitter? ;)
