### ISSUE TITLE
PlayerMovementEvent Problem with forceRegistration = false

### ISSUE THREAD

**Issue by Kongolan** [Xephi/AuthMeReloaded#52]
Line 356 needs to check for 

  if (!data.isAuthAvailable(name)) {
            if (!Settings.isForcedRegistrationEnabled) {
                return;
            }
 }

**Comment by Xephi** [comment]
Thanks ! Fixed : https://github.com/Xephi/AuthMeReloaded/commit/aa957cc7c983a4b48cc4dbb07b9971a53dace27b
