### ISSUE TITLE
GeoIp data auto update

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#523]
Old geoip data may cause bugs like #507

**Comment by DNx5** [comment]
https://github.com/AuthMe-Team/AuthMeReloaded/pull/106

**Comment by ljacqu** [comment]
It would be interesting to know if the legacy GeoIp is at least still updated somewhat. Otherwise the data will become too inaccurate soon

**Comment by sgdc3** [comment]
It seems to be updated: http://dev.maxmind.com/geoip/legacy/downloadable/
