### ISSUE TITLE
[Question] Would this work?

### ISSUE THREAD

**Issue by RoinujNosde** [Xephi/AuthMeReloaded#525]
https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/process/join/AsynchronousJoin.java#L72
player.kickPlayer(MessageKey.NOT_OWNER);

https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/output/MessageKey.java
NOT_OWNER("not_owner"),

https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/resources/messages/messages_en.yml
not_owner: You are not the Owner of this account, please try another name!'

**Comment by ljacqu** [comment]
Should be done :) Pretty cool that you figured out the places to add the things :D

**Comment by RoinujNosde** [comment]
I started learning Java :)
Pehaps this week I make a pull request to make other things translatable

**Comment by ljacqu** [comment]
That's awesome :) Any message that is public (i.e. not admin-only specific stuff) is very welcome to be translated. A few people opened issues for this, actually, so that would definitely help us out!
