### ISSUE TITLE
user email is not getting saved

### ISSUE THREAD

**Issue by RoinujNosde** [Xephi/AuthMeReloaded#527]
AuthMe version: 5.2-SNAPSHOT-b790
When player issues /email add someemail someemail, he gets the "Email added" message.
But if I run /authme getemail player, it shows me "your@email.com".
PS.: I'm using sqlite.

**Comment by RoinujNosde** [comment]
Update: Just tested with MySQL, same thing happened.

**Comment by ljacqu** [comment]
Thanks for the detailed analysis :)

**Comment by RoinujNosde** [comment]
https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/datasource/MySQL.java#L332
 I think "pst.setString(x, auth.getEmail());" is missing.

**Comment by sgdc3** [comment]
@ljacqu

**Comment by RoinujNosde** [comment]
@ljacqu

**Comment by sgdc3** [comment]
@ljacqu @DNx5 @games647 @Xephi

**Comment by DNx5** [comment]
@sgdc3 that source code is from Xephi's repo. that's old and already fixed
https://github.com/AuthMe-Team/AuthMeReloaded/commit/7eeabd68e788474378fdaa44c1827552c5bb6ef8

**Comment by DNx5** [comment]
Just found the problem, should works fine now.

**Comment by ljacqu** [comment]
Thanks, @DNx5; excellent work as always!

**Comment by RoinujNosde** [comment]
Build 802:
It's not fixed.

**Comment by RoinujNosde** [comment]
Update:
If I use /email add fakeemail fakeemail and then /email change fakeemail realemail.
It works.

**Comment by ljacqu** [comment]
Thanks for the update. Hopefully it's fixed now. (Build nr. 803 or upwards)

**Comment by RoinujNosde** [comment]
Fixed! xD
