### ISSUE TITLE
NickName issue.

### ISSUE THREAD

**Issue by Dimatert9** [Xephi/AuthMeReloaded#53]
allowedNicknameCharacters: '[a-zA-Z0-9_]*'
but see picture.    http://i.gyazo.com/ca068023103fd02b1b3b060b07711798.png
there is russian symbols

**Comment by Dimatert9** [comment]
http://i.gyazo.com/b031dc473c51c0d9afb447c1eb108e91.png

**Comment by Dimatert9** [comment]
please
fix it. i dont can ban his player. /gamemode 1. in his nickname he has space.
FIX IT

**Comment by prozhong** [comment]
I met a player named 'xiao xing'....As you can see...one space in his name....weird and I can't add permission to him

**Comment by Dimatert9** [comment]
@Xephi Fix it please. ASAP

**Comment by Xephi** [comment]
Fixed
