### ISSUE TITLE
Why "not the owner of this account"?

### ISSUE THREAD

**Issue by FabioZumbi12** [Xephi/AuthMeReloaded#534]
Why i having this message on my lobby server: You are not the owner of this account. Please try another name!

Running in offline mode!

Theres no options to disable this? All of my players is having this and cant connect to my server!

Using the bukkit version:
**AuthMe 5.2-SNAPSHOT for 1.8.1 Feb 11, 2016**

**Comment by RoinujNosde** [comment]
Is AllowRestrictedUser true in config.yml?

**Comment by sgdc3** [comment]
`preventOtherCase: false`

**Comment by FabioZumbi12** [comment]
Still not allowing: http://prntscr.com/a5e2xd

**Comment by ljacqu** [comment]
@sgdc3 The error comes from AsynchronousJoin
```        
if (Settings.isAllowRestrictedIp && !isNameRestricted(name, ip, player.getAddress().getHostName())) {
```

I don't have time to troubleshoot which setting this is but hopefully that points in the right direction

**Comment by FabioZumbi12** [comment]
Reproducing the problem, using "AllowRestrictedUser: false" that Works, but i need to allow one nick to player test and have a preview on my server. Then i need to have this option enabled. This is my config:

```
AllowRestrictedUser: false
        # The restricted user feature will kick players listed below
        # if they don't match the defined IP address.
        # Example:
        #     AllowedRestrictedUser:
        #     - playername;127.0.0.1
        AllowedRestrictedUser: 
        - 'TesteDemo;127.0.0.1'

...
preventOtherCase: false
```

**Comment by RoinujNosde** [comment]
Why 127.0.0.1?

Você é brasileiro?

**Comment by FabioZumbi12** [comment]
Sim, sou kkkk
E é um bot do site que uso pra conectar no server!

**Comment by RoinujNosde** [comment]
Tente trocar esse IP pelo IP externo da máquina.

**Comment by FabioZumbi12** [comment]
Mas não acontece com esse nick, acontece com todos que tentam se logar!
"But this happens not only for this nick, its with all player Nicks that tryng to join!"

**Comment by RoinujNosde** [comment]
Tente mesmo assim :)

**Comment by FabioZumbi12** [comment]
Mesmo com o IP do meu host que uso pra conectar não funciona!

**Comment by DNx5** [comment]
try to enable bungeecord hook.
```
Hooks:
    # Do we need to hook with BungeeCord ?
    bungeecord: true
```
if this didn't work, probably we have problem getting player's real IP.

**Comment by ljacqu** [comment]
Please check with build nr. 805 or upwards

**Comment by FabioZumbi12** [comment]
Hook with bungee already true. I will try the new build ;)

**Comment by FabioZumbi12** [comment]
Yay, seems working fine now! My TesteDemo can login only from that ip (tested with my ip) and other player can connect too ^^

I only received this message: 
```
[AuthMe] Error getting message with key 'not_owner_error'. Please verify your config file at 'messages_br.yml'
[09:03:51 INFO]: TesteDemo lost connection: Error retrieving message 'not_owner_error'
```
I already added on my messages_br.yml but only for information ;)

**Comment by ljacqu** [comment]
@FabioZumbi12 Thanks for the verification, and for the report—it should be fixed now.

```
[12:06:55 WARN]: [AuthMe] Error getting message with key 'not_owner_error'. Please verify your config file at 'messages_en.yml'
[12:06:55 INFO]: myname lost connection: You are not the owner of this account. Please try another name!
```

If you think this concludes this issue, kindly close it, otherwise please let me know what's still open. :) 

Finally, if you have any [messages_br](https://github.com/AuthMe-Team/AuthMeReloaded/blob/master/src/main/resources/messages/messages_br.yml) texts we don't have that you'd like to share, we'd gladly add them to the repo.

**Comment by FabioZumbi12** [comment]
I wait before close i theres some bug but now is working fine ;)
And on AuthMe-5.2-SNAPSHOT-spigot.jar/messages already have messages_br.yml, or you mean the message for 'not_owner_error' message?

**Comment by RoinujNosde** [comment]
> Translation: Voce nao e o dono(a) desta conta. Por favor use outro nome!

Voce nao e o(a) dono(a) desta conta. Por favor, use outro nome!
:)

**Comment by ljacqu** [comment]
Thanks. Message has been added via pull request of @RoinujNosde
