### ISSUE TITLE
com.mojang.authlib.GameProfile

### ISSUE THREAD

**Issue by rErEaT** [Xephi/AuthMeReloaded#537]
Hello!

I think its problem cause of Authme:
Player com.mojang.authlib.GameProfile@1fa6d0e1[id=b874c95b-0b54-3744-9c27-fe0527956db3,name=foxi69,properties={},legacy=false] (/193.6.61.20:1666) disconnected (Disconnected)

But if not, please help me how can I fix this?

**Comment by sgdc3** [comment]
Not enough infos, please send us a portion of your log and your configuration. ;)

**Comment by rErEaT** [comment]
http://pastebin.com/7Y3JWrFh

What is the most stable and bugfree version of AuthMe?

**Comment by sgdc3** [comment]
I'm sorry but this is not enough! Please provide a full log file ;)

**Comment by rErEaT** [comment]
And when I stop the server its crash cause of authme cant be disabled.

http://pastebin.com/jyWbjB54

**Comment by StelArian** [comment]
Same here. And after I restart the server, player can connect again for an hr or so.

**Comment by sgdc3** [comment]
@rErEaT @Done84 @StelArian It should have been fixed in latest build: http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT-spigot.jar

**Comment by rErEaT** [comment]
yes fixed!

**Comment by rErEaT** [comment]
yes fixed!

**Comment by Programmetajs** [comment]
> @rErEaT @Done84 @StelArian It should have been fixed in latest build: http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT-spigot.jar

i cant download

**Comment by emanuelD12** [comment]
> Olá!
> 
> Acho que é a causa do problema de Authme:
> Player com.mojang.authlib.GameProfile@1fa6d0e1 [id = b874c95b-0b54-3744-9c27-fe0527956db3, name = foxi69, properties = {}, legacy = false](/193.6.61.20:1666) desconectado (desconectado)
> 
> Mas se não, por favor me ajude como posso consertar isso?

have you tried to disable online-mode?

**Comment by Gugacarioca2012** [comment]
I having the same problem, this is a part of the log of my friend to connect: 





com.mojang.authlib.GameProfile@1f7eff43[id=f5352226-ba89-46b2-ba6e-f477addc8f44,name=Jhonyzgg,properties={textures=[com.mojang.authlib.properties.Property@7559c9cc]},legacy=false] (/191.34.137.214:62478) lost connection: Disconnected
453

<br class="Apple-interchange-newline">

I'm using aternos.org to use this server

**Comment by giani-reyess** [comment]
> > Olá!
> > Acho que é a causa do problema de Authme:
> > Player com.mojang.authlib.GameProfile@1fa6d0e1 [id = b874c95b-0b54-3744-9c27-fe0527956db3, name = foxi69, properties = {}, legacy = false](/193.6.61.20:1666) desconectado (desconectado)
> > Mas se não, por favor me ajude como posso consertar isso?
> 
> have you tried to disable online-mode?

This worked to me!!!

**Comment by xFixMeme** [comment]
guys anyone have a code to hide this [12:34:56 INFO]: Disconnecting com.mojang.authlib.GameProfile@20198aa9[id=55418218-dc95-3035-9a27-0bc7f87a1afe,name=FHKSpWsgjtkuWxLh,properties={},legacy=false] (/176.9.160.118:56517): §8┃ §cAegis §8» §7You must to add ping or refresh the server list

**Comment by xFixMeme** [comment]
guys anyone have a code to hide this [12:34:56 INFO]: Disconnecting com.mojang.authlib.GameProfile@20198aa9[id=55418218-dc95-3035-9a27-0bc7f87a1afe,name=FHKSpWsgjtkuWxLh,properties={},legacy=false] (/176.9.160.118:56517): §8┃ §cAegis §8» §7You must to add ping or refresh the server list

**Comment by Gugacarioca2012** [comment]
Guys, Install RandomPatches to resolve this, for me work

**Comment by Srivathsav-max** [comment]
> Guys, Install RandomPatches to resolve this, for me work

which patch did you install for resolving this issue
