### ISSUE TITLE
Error while getting country code.

### ISSUE THREAD

**Issue by smartmadio** [Xephi/AuthMeReloaded#539]
```
[Netty Server IO #0/WARN]: [AuthMe] Error while getting country code [AddressNotFoundException]: The address 127.0.0.1 is not in the database.
```
Spigot 1.8.8 / AuthMeReloaded v5.2-SNAPSHOT (build: 793)

**Comment by ljacqu** [comment]
For devs, an interesting read:
https://github.com/maxmind/GeoIP2-java/issues/28

(And indeed, a simple `null` would be simpler for unknown IP's...)

**Comment by DNx5** [comment]
@ljacqu or we could go back with old GeoIP.
GeoIP2 depends on jackson library.

**Comment by sgdc3** [comment]
Ok, i missed that requirement... Let's move back to legacy geoip. P.S: I think that @ljacqu is right, we should use null as default address ;)

**Comment by DNx5** [comment]
I already set default value for unkown ips, that was just logging problem.

**Comment by ljacqu** [comment]
@sgdc3 The linked issue is from the GeoIp2 repo :P I was just happy to see other people complain about the exception being thrown. It's expensive, and imho inuintive.

**Comment by sgdc3** [comment]
@ljacqu Yeah i know but i've misunderstood your P.S ;)

**Comment by ljacqu** [comment]
No answer to "please verify", assuming solved.
