### ISSUE TITLE
Some Error with TaskID canceling

### ISSUE THREAD

**Issue by Kongolan** [Xephi/AuthMeReloaded#54]
http://www.spigotmc.org/threads/auto-in.19040/page-51#post-775310

Self explaining :)

**Comment by Xephi** [comment]
Looking in..

**Comment by Kongolan** [comment]
AuthmePlayerListener line 834:
 limbo.getTimeoutTaskId().cancel();

Seems like the Task isn't properly set sometimes for my players. It is normally set in line 738

The numbers can differ for like 2-3 lines, because i added the PlayerMovementFix already, which i reported below.

**Comment by Kongolan** [comment]
So far i can see is that most of the problem happen, when using /ai iamnowpremium with Auto-In. Because it does access the API and bypass the normal PlayerLoginEvent, which does fill the Limbo.setTimeoutTask

**Comment by Kongolan** [comment]
Last edit, did put a try / catch around the 3 cancel() NPE and seems to work so far.

**Comment by Xephi** [comment]
Fixed ? https://github.com/Xephi/AuthMeReloaded/commit/a1c09aecfcb384387010812c0a6848f1739fe3d9

**Comment by Kongolan** [comment]
It also fires on PlayerQuitEvent and somewhere else in PlayerListener, what i forgot.

**Comment by Xephi** [comment]
Added
