### ISSUE TITLE
AuthMe v5.2-SNAPSHOT-b763 removePassword: true not work

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#541]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/13183762/b37c91f6-d738-11e5-940a-d3c57d698da7.PNG)

**Comment by FabioZumbi12** [comment]
Yes, this a critical bug! No snapshots on jenkings solving this? Thanks!

**Comment by ljacqu** [comment]
Cannot reproduce. I have in config.yml
```yml
        removePassword: true
```

Otherwise maybe some other plugin interfering or something? I checked on Spigot with barely any other plugins. CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by FabioZumbi12** [comment]
My lobby server has only this plug-ins: 
Plugins (11): AdvancedPortals, AuthMe, UltimateHub, WorldEdit, 
Legendchat, MaxBans, SkinsModule, PictureLogin, BetterAlias, PacketListenerApi, ProtocolSupport

**Comment by andris155** [comment]
Used plugins:
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/13199476/8c10f4d8-d826-11e5-951e-bcbdbc5d8eb2.PNG)

**Comment by sgdc3** [comment]
Ok, not a compatibility issue :(

**Comment by RoinujNosde** [comment]
Both of you are using MultiCraft?

**Comment by FabioZumbi12** [comment]
I am not! I using direct with SSH and not PaperSpigot.

**Comment by RoinujNosde** [comment]
Can you try to run your server locally?

**Comment by andris155** [comment]
I tested Windows bat, and Multicraft.

**Comment by andris155** [comment]
http://ci.xephi.fr/job/AuthMeReloaded/813/ = work removePassword: true Thanks!

**Comment by ljacqu** [comment]
Thank you for the update. I have no idea what changed in the meantime :P
@FabioZumbi12 Does a new build also solve it for you?

**Comment by FabioZumbi12** [comment]
Yess, solved the /register nd /login problens ^^
http://prntscr.com/a6aiwq

**Comment by sgdc3** [comment]
Fine ;)
