### ISSUE TITLE
Timstamp issue. Re-Register - Spigot version

### ISSUE THREAD

**Issue by Done84** [Xephi/AuthMeReloaded#542]
Hi. i just tried version #799 Spigot.
First i was getting this error:

[12:58:22] [Craft Scheduler Thread - 131/WARN]: [AuthMe] Could not get timestamp from resultSet. Defaulting to current time [SQLException]: Cannot convert value '0000-00-00 00:00:00' from column 5 to TIMESTAMP.
[12:58:22] [Craft Scheduler Thread - 132/INFO]: [AuthMe] Player itzgamefreak_ has logged in from one of your server!

Full log here: http://pastebin.com/nF1XvZAW

I used the new version on One server only, i always do it this way to test first. After i wile i switched server that has a older build and everythign was fine, some time later it asked to me register. I reboot everything and updated all server to the spigot build and now it asks everyone to register.

**Comment by Done84** [comment]
More errors: http://pastebin.com/BdDZgEyj

**Comment by Done84** [comment]
Also i reverted back to a previous version that worked fine mostly, and the problem persists.

**Comment by Done84** [comment]
For for the monolog, but im getting a bit desperate here.
Tryed the lates build that just came out #802

The behavior is not consistent. Some people are asked to register even thought they already are. Some are not.

**Comment by ljacqu** [comment]
A question while I fix the timestamp issue -- are there many users in the database with 00:00:00 as timestamp? If so, do you know the "origin" of any of those? Like, where they registered by an admin maybe? (Or anything like that that would make them stand out from other players)

**Comment by Done84** [comment]
Not sure if this is the propper way to search as i am not good with mysql, but heres my try:
http://prntscr.com/a5g891

Also, i dont get the timestamp error anymore, i just get a few players asked to register when they are already in the database and nothing stops them from doing so.

**Comment by Done84** [comment]
Maybe this comparison can help
Bugged player in my backup database: http://prntscr.com/a5gnsz
Bugged player in my curreent database: http://prntscr.com/a5goht

**Comment by ljacqu** [comment]
I'm thinking about this, and I'm at a complete loss where this 00:00:00 stuff comes from. Did you recently update AuthMe version? We did a change to the timestamp recently and automatically migrated that column; I wonder a) whether the migration is faulty and/or b) whether it causes trouble together with the database caching.

Your two most recent screenshots—are both records in the same database? I believe that wouldn't be possible. But if the second screenshot is an updated version, I find it very odd that the ID of the player has changed. Do you maybe have a backup of your database from a few days ago?

**Comment by Done84** [comment]
the first screen shot is from i backup i made before updating to the new -spigot builds of authme, the second is how the database became ofter the fact for a player that had the Re-Register issue.

**Comment by ljacqu** [comment]
It seems quite the same, besides the last position. I just realized, though, that it might be because your database got purged. We haven't updated to the new format so it might be that we just match way too much and delete too many accounts. I'll report back.

**Comment by Done84** [comment]
Things seeamed stable for a while then booom.. all hell breaks lose and people get asked to re-register.

rror during SQL operation: [MySQLIntegrityConstraintViolationException]: Duplicate entry 'vengadordelolpvp' for key 'username'

full log: http://pastebin.com/DcUD7bNB

**Comment by Done84** [comment]
Ok so... The BungeeCord hook somehow set itself to "true" and changed it back to false and now things seem stable. I report back once again to confirm... jesus

**Comment by Done84** [comment]
Same issue as #537

**Comment by ljacqu** [comment]
@sgdc3 @DNx5 @games647
I would like to suggest reverting the lastlogin column from `timestamp` back to `bigint`. For one, we're only doing it for MySQL (because SQLite doesn't have such a type) and MySQL does not like the timestamp `0000-00-00 00:00:00`. Checking for this value before retrieving it is annoying and requires two reads for one value. Therefore, I will create a pull request shortly and you can see whether you agree with this.

**Comment by sgdc3** [comment]
yeah, you're right ;)

**Comment by Done84** [comment]
I dont know if its relevant... but. With the latest builds i wasn't getting the error in console anymore. Just the timeouts.

**Comment by ljacqu** [comment]
@sgdc3 Are you doing it? I'm confused by the "in progress" label

**Comment by sgdc3** [comment]
@Done84 can you try latest build? ;)

**Comment by Done84** [comment]
@sgdc3 To be honest, I'm scared to death to that ... Dealing with a big database restoring things is such a pain...
I'll do it later tomorrow and report back.

**Comment by sgdc3** [comment]
It's hard to do a mysql dump? :/ If you are using a webpanel like phpmyadmin it should be very easy.

**Comment by Done84** [comment]
It's easy, it just takes some time to dump, shut down the whole network, replace jars in all servers, start everything again, wait 30 mins to check if the problem still occurs, then to everything again.

Anyway.. The problem still persists.. After 15 to 30 mins no one can switch servers, everyone just times out.

**Comment by Done84** [comment]
@sgdc3 
Ok.. So. I found out that BungeeBridge was causing even more problems, so i took it off to debug.
After that instead of time outs now the server does not ask for /login, if you still run the command it works thoght.

 This error shows up in the console:
Caused by: java.lang.IllegalArgumentException: Name cannot be null

Full logs from 2 servers:
http://pastebin.com/08bid9Br
http://pastebin.com/arpNeP6B

**Comment by sgdc3** [comment]
.... AuthMeBridge? NEVER USE IT. It's not official and it's outdated.

**Comment by sgdc3** [comment]
Remove also the AuthMeBridgeBukkit jar from your servers

**Comment by sgdc3** [comment]
@Done84 So... any news?

**Comment by Done84** [comment]
@sgdc3 Everything looks to be stable on the latest build.
Only issue i have now is MOTD ramdonly spamming when using:
<    useEssentialsMotd: false>
I think the welcome.txt might be sent to all players everytime another player connects, but i cant really be 100% sure since i have login messages hidden in my servers.

**Comment by Done84** [comment]
Ohh.. i Just noticed sometimes I am also randomly asked to type my password again, this happens rarely but it happens.

**Comment by sgdc3** [comment]
@ljacqu Any ideas? :/

**Comment by ljacqu** [comment]
Hmm, nothing I can come up with off the top of my head :/ Given the long comment thread of this issue I'd like to suggest to close this issue and to open new ones for the bugs mentioned. I'll create one for the MOTD issue, and if @Done84 finds that he has to retype his password randomly again he's also invited to open an issue for that :)
