### ISSUE TITLE
[Maven] New pom style: yaml

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#543]
https://gist.github.com/sgdc3/6144626a390b9428ad76
Would you like a pom like that? ;)

**Comment by ljacqu** [comment]
I had no idea that was a thing—trying to stay open-minded :P

**Comment by sgdc3** [comment]
We shouldn't use this: services like versioneye will break!

**Comment by ljacqu** [comment]
Thanks for the update. The pom looks really nice in YAML but not at the cost of relying on unstable services / deviating from the standard. You made the right call, so great work :)

**Comment by sgdc3** [comment]
"great work" xD Only xml-hate :+1:
