### ISSUE TITLE
removeSpeed stops player from moving after switching server.

### ISSUE THREAD

**Issue by smartmadio** [Xephi/AuthMeReloaded#544]
There're two servers (server A and server B) under the same bungeecord.They all have authme installed.
I've turned 'bungeecord' hook and 'removeSpeed' to 'true' in the config.yml.But when player logged in in server A and then switched to server B ,player can't move in server B (But he could jump in server B,authme also suggested that he had already logged in successfully.).
Need help on it.Is there any wrong on my setting or it's a bug?

**Comment by sgdc3** [comment]
Issue with bungeecord messaging

**Comment by dankand** [comment]
I have the same problem as you

**Comment by sgdc3** [comment]
@DNx5 @games647 @ljacqu Who wants to take care of this? :)

**Comment by Xephi** [comment]
Do you use the bridge ?
http://ci.xephi.fr/job/AuthMeBungee/

**Comment by smartmadio** [comment]
@Xephi No,I've removed this bridge recently.

**Comment by smartmadio** [comment]
Seems this problem still not solved yet.

**Comment by sgdc3** [comment]
@smartmadio Using latest build?

**Comment by smartmadio** [comment]
Last version on bukkitdev

**Comment by sgdc3** [comment]
Could you try latest build from jenkins?

**Comment by smartmadio** [comment]
I'll have a try immediately.

**Comment by smartmadio** [comment]
Problem solved:)
Works fine with version #1366.

**Comment by smartmadio** [comment]
Solved.

**Comment by ljacqu** [comment]
Thanks for the feedback!
