### ISSUE TITLE
Early 1.9 Support

### ISSUE THREAD

**Issue by Platinteufel** [Xephi/AuthMeReloaded#545]
Hey AuthMe-Team. :)
According to this thread in spigot forums
https://www.spigotmc.org/threads/minecraft-1-9-more-info.124273/ 
Spigot/Bukkit 1.9 will be released at Feb 26th. The 1.9 API should be already available on git. Is it possible to support early 1.9 builds in time? That would be awesome. :)

**Comment by sgdc3** [comment]
Yeah yesterday i checked the api changes. We need only to fix missing event listeners ;)

**Comment by sgdc3** [comment]
No errors! AuthMe is already compatible with the new API ;)

**Comment by Platinteufel** [comment]
Wow, nice to hear. :)
