### ISSUE TITLE
[Dev] Revise (a)sync task architecture

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#547]
Introduce a service to easily pass our usual service instances to the (a)sync processes and to avoid static injections.

**Comment by DNx5** [comment]
Is this can be used to wait uncomplete scheduled async bukkit task before closing MySQL datasource?
#542
http://hastebin.com/wukesebuhu.avrasm

**Comment by ljacqu** [comment]
That should be one level above, ProcessService is passed to the processes themselves for some common tasks like sending a message to players (has advantages of adding a layer between the real services and the action in case we ever switch, and no need to get services statically)

If you want to implement a waiting mechanism that should probably be on `Management` level, but I wouldn't be sure how to go about that.

**Comment by ljacqu** [comment]
This is essentially done. Still keeping open for unit testing + adding some javadoc
