### ISSUE TITLE
Lowercase user name related

### ISSUE THREAD

**Issue by prozhong** [Xephi/AuthMeReloaded#55]
hi~ I use the 3/6/2015 snapshot build from CI server
And I met this:

Let's say my username is 'user' and I have an alt named 'User',
when my alt first join , it doesn't let me register,I can use the password set by 'user';
I see account 'user' and 'User' share the same password.

Its that intended?

Here is another problem but caused by essentials: 'user' and 'User' share the balance number and their essentials user data (in plugins\Essentials\userdata ; like user's location & kits info etc.) will be a total mess.

What I mean here is ,could you add some function like refusing player named 'User' join(I mean join) server because there is already a player named 'user' in our cache?

I know its maybe a dirty solution to lowercase problem...

You can find bug report here:
https://hub.spigotmc.org/jira/browse/PLUG-34
https://hub.spigotmc.org/jira/browse/PLUG-50

**Comment by orkun1675** [comment]
Please merge this with #76
