### ISSUE TITLE
Welcome message shown twice upon registration

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#550]
Looks like a recent fix by me now makes the welcome message be displayed twice. Reason is after registration we call the login event so it goes through it twice.

**Comment by Platinteufel** [comment]
I can confirm it, but it's only shown twice after registration, not after login.

**Comment by ljacqu** [comment]
Thanks for the input

**Comment by Platinteufel** [comment]
@ljacq @sgdc3 This commit causes the issue:
https://github.com/AuthMe-Team/AuthMeReloaded/commit/fd8991507159968bcbff884e2bc1f9cf19916776
You've changed "display welcome message if we use email registration" to "display welcome message" .. maybe this was just for a special case (email registration)?

**Comment by ljacqu** [comment]
It was missing in some cases and now it's shown twice in some others ^^ I need to play through each scenario to determine how to solve it

**Comment by Platinteufel** [comment]
Okay, but before this commit it was fine, and you've only changed one file there. ^^

**Comment by ljacqu** [comment]
@sgdc3 Could I ask you to verify the changes and see if you agree with them? Finally I did remove the welcome message from the registration: the user will get the welcome message when he is logged on anyway, or if he has to /login explicitly we would expect this to happen quite fast.

+ also moved the execution of force commands before the registration check so that they are always run.

**Comment by sgdc3** [comment]
It seems fine! Thank you! :D

**Comment by ljacqu** [comment]
Thanks for verifying! Always glad to have a second pair of eyes on my code :)

**Comment by ljacqu** [comment]
Hmm, still getting it twice. Reopening >.<
