### ISSUE TITLE
Email registration does not work when no email is set

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#551]
RegisterCommand checks if email registration is enabled but only performs email registration if the mail account setting is populated with a value. Otherwise, even though the user did `/register mail@example.com mail@example.com`, the registration process will continue and interpret the email as the password... 

```java
if (Settings.emailRegistration && !Settings.getmailAccount.isEmpty()) {
```

If no mail account is set it means the user's password cannot be sent by mail, so I would expect the registration to fail, logging an error and sending a message to the user.

**Comment by sgdc3** [comment]
Bump (just to keep it in the top of the issue list)

**Comment by ljacqu** [comment]
@sgdc3 In the meantime, what would you suggest to do if we have email registration but no email account?
Failing seems unfriendly, but if we can't send the password the registration is pointless.

**Comment by sgdc3** [comment]
What we can do? I think nothing...

**Comment by sgdc3** [comment]
@ljacqu

**Comment by ljacqu** [comment]
In that case we should add some error. Looks like the best option

**Comment by sgdc3** [comment]
Yeah but no stacktraces, we shouldn't spam the console xD

**Comment by ljacqu** [comment]
Stacktrace would not make sense in this scenario anyway

**Comment by sgdc3** [comment]
@ljacqu Yeah xD

**Comment by sgdc3** [comment]
Thank you ;)
