### ISSUE TITLE
Loading/creating spawn.yml

### ISSUE THREAD

**Issue by RoinujNosde** [Xephi/AuthMeReloaded#554]
Build 821:
There is some kind of bug on loading/creating spawn.yml:
> at fr.xephi.authme.settings.Spawn.reload(Spawn.java:30) ~[?:?]
at fr.xephi.authme.settings.Spawn.<init>(Spawn.java:26) ~[?:?]
at fr.xephi.authme.settings.Spawn.getInstance(Spawn.java:42) ~[?:?]

How to reproduce:
1. Delete your spawn.yml file
2. Start your server
Or:
1. Start your server
2. Use /authme reload
Or:
1. Start your server
2. Join server

**Comment by sgdc3** [comment]
@RoinujNosde It should have been fixed by @DNx5 ;)

**Comment by RoinujNosde** [comment]
Fixed :)

**Comment by sgdc3** [comment]
Thanks you ;)
