### ISSUE TITLE
NullPointer when TabComplete false and TabListHide false

### ISSUE THREAD

**Issue by Kongolan** [Xephi/AuthMeReloaded#558]
AuthMe.java throws NullPointer when tabComplete and tablistHider not initialized

Line 667+

        if (newSettings.getProperty(RestrictionSettings.DENY_TABCOMPLETE_BEFORE_LOGIN) && tabComplete == null) {
            tabComplete = new AuthMeTabCompletePacketAdapter(this);
            tabComplete.register();
        } else if (inventoryProtector != null && tabComplete != null) {
            tabComplete.unregister();
            tabComplete = null;
        }
        if (newSettings.getProperty(RestrictionSettings.HIDE_TABLIST_BEFORE_LOGIN) && tablistHider == null) {
            tablistHider = new AuthMeTablistPacketAdapter(this);
            tablistHider.register();
        } else if (inventoryProtector != null && tablistHider != null) {
            tablistHider.unregister();
            tablistHider = null;
        }

**Comment by DNx5** [comment]
Thanks
