### ISSUE TITLE
I need a new version!!!

### ISSUE THREAD

**Issue by markob007** [Xephi/AuthMeReloaded#560]
Players can enter the admin account by mistake with case sensitive... for example
markob007 and MarkoB007 
He can enter and register and he will have OP 
or when I am in game he can join without registration

**Comment by sgdc3** [comment]
@markob007 What's your authme version?

**Comment by RoinujNosde** [comment]
@markob007 Try the last build: http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT-legacy.jar

**Comment by markob007** [comment]
I will try this V.  
sgdc3 I am using 4.0

**Comment by markob007** [comment]
BUG with new snapshot... After 10min nobody can enter server

**Comment by ljacqu** [comment]
We have multiple issues about that
