### ISSUE TITLE
PlayerJoinEvent

### ISSUE THREAD

**Issue by RoinujNosde** [Xephi/AuthMeReloaded#561]
Hi,
I'm making a plugin that uses PlayerJoinEvent to teleport some players to a location x.
The thing is ForceSpawnLocOnJoinEnabled is true, so ALL players go to the spawn location.
```
@EventHandler(priority = EventPriority.HIGHEST)
	public void OnPlayerJoin(PlayerJoinEvent event) {
		Player player = event.getPlayer();
		if (somelogical){
			player.teleport(new Location(world, spawn.getX(), spawn.getY()+1, spawn.getZ()));
		}
	}
```
How can i give my plugin a higher priority than authme's?

**Comment by RoinujNosde** [comment]
Or...
AuthMe has an event when a player logs in successfully?

**Comment by DNx5** [comment]
try to set your event to LOW and see if it works.

**Comment by RoinujNosde** [comment]
Did not work.

**Comment by games647** [comment]
>AuthMe has an event when a player logs in successfully?

Yes the LoginEvent, but I think SpawnTeleportEvent is more useful for you.

**Comment by RoinujNosde** [comment]
@games647 
LoginEvent works nicely xD
