### ISSUE TITLE
No permissions

### ISSUE THREAD

**Issue by tteeee** [Xephi/AuthMeReloaded#562]
`/authme forcelogin NICKNAME`
Ezy Hacking a servers. :(

**Comment by sgdc3** [comment]
What do you mean?

**Comment by RoinujNosde** [comment]
@sgdc3 I think he is saying that /authme forcelogin don't require a permission, so everyone can use it.

**Comment by DNx5** [comment]
Couldn't reproduce it. Probably he is using the broken one.

**Comment by sgdc3** [comment]
Yeah, it works fine.

**Comment by sgdc3** [comment]
@tteeee Please use the latest dev build: http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT-spigot.jar
