### ISSUE TITLE
Improve projectile launch event handling

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#568]
Two TODO's about the projectile launch event in AuthMeEntityListener:
```java
    // TODO: Need to check this, player can't throw snowball but the item is taken.
    @EventHandler(ignoreCancelled = true, priority = EventPriority.LOWEST)
    public void onProjectileLaunch(ProjectileLaunchEvent event) {
// -snip- //
            // TODO ljacqu 20151220: Invoking getShooter() with null but method isn't static
            try {
                if (getShooter == null) {
                    getShooter = Projectile.class.getMethod("getShooter");
                }
                Object obj = getShooter.invoke(null);
```

**Comment by FabioZumbi12** [comment]
If you mean improvement to not use methods, i think we can check the shooter based on event projectile, and on variables assigned on load class:

`
// TODO: Need to check this, player can't throw snowball but the item is taken.
    @EventHandler(ignoreCancelled = true, priority = EventPriority.LOWEST)
    public void onProjectileLaunch(ProjectileLaunchEvent event) {
        if (event.getEntity() == null) {
            return;
        }

        Player player = null;
        Projectile projectile = event.getEntity();
        //Already checked if projectile is null, only check if is ProjectileSorce
        if (projectile.getShooter() instanceof ProjectileSource) {
            ProjectileSource shooter = projectile.getShooter();
            if (shooter == null || !(shooter instanceof Player)) {
                return;
            }
            player = (Player) shooter;
        }
        
        //We dont need to asign object to player becau already is null if the shooter isnt a player

        if (ListenerService.shouldCancelEvent(player)) {
            event.setCancelled(true);
        }
    }
`

**Comment by ljacqu** [comment]
I think there's a misunderstanding here as to what the code is doing. Unfortunately the piece of code using reflections is not commented, but I found this similar one—https://github.com/fromgate/ReActions/blame/master/src/me/fromgate/reactions/util/BukkitCompatibilityFix.java

```java
	/* 
	 * In latest version of Bukkit API getShooter() method returns Projectile source 
	 * that not available in previous version of Bukkit API. 
	 * This method is returns LivingEntity instead of ProjectileSource   
	 */
	public static LivingEntity getShooter (Projectile projectile){
		if (projectile==null) return null;
		try {
			Method getShooter = projectile.getClass().getDeclaredMethod("getShooter");
			Object shooterObject = getShooter.invoke(projectile);
			if (shooterObject == null) return null; 
			if (shooterObject instanceof LivingEntity) return (LivingEntity) shooterObject;
		} catch (Exception e) {
			ReActions.util.logOnce("getShooter", "Looks like this version of BukkitAPI totally incompatible with API 1.7.x. Method \"getShooter\" is not declared in Projectile class");
		}
		return null;
	}
```

**Comment by sgdc3** [comment]
What about this?
     // TODO: Need to check this, player can't throw snowball but the item is taken.
    @EventHandler(ignoreCancelled = true, priority = EventPriority.LOWEST)
    public void onProjectileLaunch(ProjectileLaunchEvent event) {
        Projectile projectile = event.getEntity();
        if (projectile == null) {
            return;
        }

        Object shooter = projectile.getShooter();
        Player player = null;

        try {
            player = (Player)shooter;
        } catch(Exception e) {
            ConsoleLogger.logException("EntityListener: onProjectileLauch, can't cast the shooter to player!", e);
        }

        if (ListenerService.shouldCancelEvent(player)) {
            event.setCancelled(true);
        }
    }

**Comment by sgdc3** [comment]
@ljacqu

**Comment by ljacqu** [comment]
@games647 recently said that for Bukkit.getPlayers(), which returns `Player[]` or `Collection<? extends Player>` depending on the version, we still need to go over reflections because the return type of the version we compile against will be in the bytecode, so it will fail for the other return type even if our code would allow it. Maybe he knows if doing `Object shooter = projectile.getShooter()` and then `if (shooter instanceof Player)` is OK to do bytecode-wise.

If so, that would indeed be very elegant. I'd just suggest a slight change, namely to check the type before casting:
```java
if (shooter instanceof Player) {
    player = (Player) shooter;
} else {
   ConsoleLogger.showError("EntityListener: onProjectileLauch, can't cast the shooter to player!");
}
```

**Comment by sgdc3** [comment]
Ok, final version atm
`JAVA    // TODO: Need to check this, player can't throw snowball but the item is taken.
    // -sgdc3: can't reproduce...
    @EventHandler(ignoreCancelled = true, priority = EventPriority.LOWEST)
    public void onProjectileLaunch(ProjectileLaunchEvent event) {
        Projectile projectile = event.getEntity();
        if (projectile == null) {
            return;
        }
        Object shooter = projectile.getShooter();
        if (shooter == null) {
            return;
        }

        Player player = null;
        if (shooter instanceof Player) {
            player = (Player) shooter;
            if (ListenerService.shouldCancelEvent(player)) {
                event.setCancelled(true);
            }
        }
    }`

**Comment by ljacqu** [comment]
More suggestions

```java
    // TODO: Need to check this, player can't throw snowball but the item is taken.
    // -sgdc3: can't reproduce...
    @EventHandler(ignoreCancelled = true, priority = EventPriority.LOWEST)
    public void onProjectileLaunch(ProjectileLaunchEvent event) {
        Projectile projectile = event.getEntity();
        if (projectile == null) {
            return;
        }

        Object shooter = projectile.getShooter();
        if (shooter instanceof Player) {
            Player player = (Player) shooter;
            if (ListenerService.shouldCancelEvent(player)) {
                event.setCancelled(true);
            }
        }
    }
```

Removed the check for `shooter == null` because [null instanceof X always returns false](http://stackoverflow.com/questions/2950319/is-null-check-needed-before-calling-instanceof), but if you prefer `if (shooter != null && shooter instanceof Player)` that would also be quite nice IMHO and it would remind devs in the future that `shooter` could be null.

**Comment by sgdc3** [comment]
@ljacqu Yeah, you're right! Thanks ;)

**Comment by sgdc3** [comment]
Ok, created a new branch ;)

**Comment by ljacqu** [comment]
Thanks!

I did some digging and I'd like to share some background. Bukkit has the following hierarchy:
```
ProjectileSource
├─ LivingEntity
│   └─ Player
└─ BlockProjectileSource
```

What changed somewhere around 1.5 is the return type of `Projectile.getShooter()`—from LivingEntity to ProjectileSource (probably that's when those arrow blocks were introduced).

Maybe @games647 knows if doing `Object shooter = projectile.getShooter();` is OK to do (bytecode) for a method whose return type might vary.

**Comment by FabioZumbi12** [comment]
Use object is the best way but one question: Both ProjectileSource and LivingEntity will cast to player right?

**Comment by sgdc3** [comment]
Maybe instead of Object we should use ProjectileSource. :/

**Comment by games647** [comment]
@ljacqu is right

>                  linenumber      84
              10: aload_2         /* projectile */
              11: invokeinterface org/bukkit/entity/Projectile.getShooter:()Lorg/bukkit/projectiles/ProjectileSource;
              16: astore_3        /* shooter */
                  linenumber      85

We have to use reflection, because ProjectileSource isn't available in old versions. :(

**Comment by sgdc3** [comment]
@ljacqu Could you give it a quick look?

**Comment by ljacqu** [comment]
@sgdc3 Yep, this issue requires the following points to be done:

1. `Object obj = getShooter.invoke(null);` should be replaced with 
`Object obj = getShooter.invoke(projectile);` 
  * (but please do take a moment to check that it makes sense)

2. Replace the `catch (Exception e)` clause with something a little more specific
  * as elsewhere we have combined catches, e.g. `catch (IllegalInvocationException | IllegalAccessException e)`

3. Log the exception in the `catch` clause 
  * e.g. `ConsoleLogger.logException("Error getting shooter", e);`

4. Test that it works

A note explaining [why we need reflection](#issuecomment-192750899) would be nice too

**Comment by sgdc3** [comment]
@ljacqu Thank you ;)

**Comment by ljacqu** [comment]
@sgdc3 Thanks for taking this over :) We'll have one less debt in our code.
