### ISSUE TITLE
New messages_de.yml :)

### ISSUE THREAD

**Issue by Platinteufel** [Xephi/AuthMeReloaded#569]
Hey,

here's an updated _messages_de.yml_ for you. Awesome work guys, hope we'll see a 5.2 release soon. :)

[messages_de.zip](https://github.com/Xephi/AuthMeReloaded/files/149580/messages_de.zip)

**Comment by ljacqu** [comment]
Aren't you just awesome :) Thanks a lot for providing the translations.

**Comment by sgdc3** [comment]
@ljacqu Why please-verify?

**Comment by ljacqu** [comment]
Felt weird to close the issue like two minutes after he opened it. Wanted to give a chance to Platinteufel to provide feedback or close it himself

**Comment by sgdc3** [comment]
@ljacqu Lol, sorry but i hate to have more than 50/60 open issues xD
