### ISSUE TITLE
Fix build server uptime

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#57]
ci.xephi.fr

**Comment by prozhong** [comment]
sometimes offline

its normal

**Comment by Xephi** [comment]
Re-up, i hope :'(

**Comment by sgdc3** [comment]
It works! ;)

**Comment by sgdc3** [comment]
Still OFFLINE.....

**Comment by Trojaner25** [comment]
It's offline for me too

**Comment by Xephi** [comment]
Online for now ... Hosting service is pretty useless, i think i will change for an another one T.T

**Comment by sgdc3** [comment]
Renamed issue

**Comment by sgdc3** [comment]
Ovh is a really good hosting service, probably there is an incorrect/incomplete configuration.

**Comment by Xephi** [comment]
Build server is temporary offline ...

**Comment by sgdc3** [comment]
done!
