### ISSUE TITLE
Marker for max_reg message

### ISSUE THREAD

**Issue by Kixot14** [Xephi/AuthMeReloaded#570]
Can you add marker  **%**ALREADY REGISTERED ACC**%**  for message **max_reg**, when player reached max reg per IP ??

This marker will be replaced by nickname of already registered accounts of this player.

**Comment by Xephi** [comment]
Can you test please ? tag is : %acc_nb

Xephi

**Comment by sgdc3** [comment]
@Kixot14 Does it work now?

**Comment by ljacqu** [comment]
To be fair it's not what he requested :P

**Comment by sgdc3** [comment]
Lol sorry, we misread the request, i'll fix it asap.

**Comment by ljacqu** [comment]
seeing the two commits to this issue, am I completely understanding the wrong wish here??

> This marker will be replaced by nickname of already registered accounts of this player.

**Comment by sgdc3** [comment]
LOOOL @Xephi our mind is blown xD

**Comment by sgdc3** [comment]
I'll add it tomorrow xD

**Comment by sgdc3** [comment]
Now we have 3 placeholder, fine! :D
