### ISSUE TITLE
[Dev] Fix the tablist hider

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#574]
- [x] Check if we handle this correctly

Edit: Ok we can reenable it, sorry but i wasn't sure we were filtering the right packet. ;)

**Comment by ljacqu** [comment]
Please provide a description of what currently doesn't work.

**Comment by sgdc3** [comment]
Just double check what we are doing, are we sure PLAYER_INFO is only used by the tablist?

**Comment by sgdc3** [comment]
2° How the data is sent? Every X Ticks? If so we can ignore this point.

**Comment by ljacqu** [comment]
Please provide a description of what currently doesn't work and how this manifests itself.

**Comment by sgdc3** [comment]
...

**Comment by sgdc3** [comment]
Ok, nevermind
