### ISSUE TITLE
Spigot 1.9 - Empty Tablist and invisible players

### ISSUE THREAD

**Issue by Platinteufel** [Xephi/AuthMeReloaded#576]
Hey,

I've recently tested Spigot 1.9 with the latest AuthMe dev build, but my tablist is empty and some players are invisible for me. It works fine without AuthMe installed.

**Comment by sgdc3** [comment]
I knew it xD @Xephi I think 1.9 uses the PLAYER_INFO for other scopes

**Comment by sgdc3** [comment]
whoops i mean @ljacqu @games647

**Comment by sgdc3** [comment]
@Platinteufel What happens if you turn off the hideTablistBeforeLogin option?

**Comment by Dimatert9** [comment]
If set to false this fuctions this will remove from config and need add this to config myself

**Comment by Platinteufel** [comment]
I know that they dropped support for read: getOnlinePlayers() array (as md5 mentioned in the release thread), but I don't know if that could be the point. 
I will test it without hideTablist.

**Comment by Platinteufel** [comment]
After I set hideTablistBeforeLogin = false it seems to work fine. @sgdc3

**Comment by sgdc3** [comment]
@Dimatert9 What do you mean?

**Comment by Platinteufel** [comment]
Uhm okay, it's a Minecraft issue, so maybe you have to remove or change the hideTablistBeforeLogin feature?

**Comment by sgdc3** [comment]
Yeah, I know. :/

**Comment by Xephi** [comment]
Huum have you update ProtocolLib too ? Cause we remove the tablist with a protocol lib adapter

**Comment by Platinteufel** [comment]
Yeah sure, I'm running the latest ProtocolLib dev build. But nevertheless there shouldn't be such critical bugs if there's a missing dependency. ^^

**Comment by sgdc3** [comment]
> Spawn Player
> [...]This packet must be sent after the Player List Item (Play, 0x38, clientbound) packet that adds the player data for the client to use when spawning a player. If the tab list entry for the UUID included in this packet is not present when this packet arrives, the entity will not be spawned. The tab includes skin/cape data. [...]

**Comment by sgdc3** [comment]
More details: https://github.com/dmulloy2/ProtocolLib/issues/157

**Comment by games647** [comment]
Maybe it's better to hide the player completely?

**Comment by sgdc3** [comment]
@games647 Nope, we are unable to respawn them client-side after the login...

**Comment by games647** [comment]
With Bukkit's hidePlayer?

**Comment by Dimatert9** [comment]
How about move this fuction to Hooks.bungeecord?
If bungeecord is enabled && sendto enabled = hide players.

**Comment by games647** [comment]
@Dimatert9 Should players be hidden completely or should the name just be removed from the tablist?

**Comment by sgdc3** [comment]
@games647 maybe we should create two different adapters. What do you think about?

**Comment by games647** [comment]
Currently we only hide the tablist for new players. I thought with Bukkit's hidePlayer we could make it compatible with other plugins.

**Comment by ljacqu** [comment]
@games647 Following #810, is this issue now obsolete?

**Comment by games647** [comment]
Yes

**Comment by itsLaserr** [comment]
> After I set hideTablistBeforeLogin = false it seems to work fine. @sgdc3

hey i have a qestion does anyone know how to hide players from tab befor login cuz i don't have  "hideTablistBeforeLogin" in my config
