### ISSUE TITLE
Question Compatibility of Authme 3.4 to newer Versions and Backwards Compat of new Versions

### ISSUE THREAD

**Issue by Phreag** [Xephi/AuthMeReloaded#577]
We have some Modpack Servers runing on  1.6.4, 1.7.10 and a VanillaServer which is about to be updated to 1.9.

Currently we are using Authme 3.4 on all of those servers.
But with 1.9 it is Broken.

So My Question is: Can We use newer Authme on all of those MC Versions or can Authme 3.4 run on the same Databse then the newest Builds.

Because by now we have on big Database for all login Data and we want too keep it like that.

**Comment by sgdc3** [comment]
:/ This is an hard question... I think it would produce a large amount of issues. Why didn't you update every server to authme 5.2?

**Comment by ljacqu** [comment]
If it's not flatfile probably we can help you migrate if something doesnt work :) Just make sure to back up everything first before experimenting

**Comment by Phreag** [comment]
That would be the question 2: Will Authme 5.2 work on Cauldron 1.6.4?

**Comment by sgdc3** [comment]
It should but we never tested it

**Comment by sgdc3** [comment]
Our code support 1.5 - 1.8

**Comment by Phreag** [comment]
Hm, okay but i just got the best option for me. 
I Updated Authme 3.4 to work with Spigot 1.9 and all newest Dependencys.
Just did some testing on 1.9 Spigot and it works well.
I you want to continue support on 3.4 i can also give it to you.

**Comment by HappyHarm** [comment]
Authme 3.4 for 1.9 would be nice. I heard that there were still many bugs in 5.x and that it wasn't working properly with Auto-In

**Comment by Phreag** [comment]
Here is a link to the updated jar.
Its a big bigger because i did not compress it because older MC Versions have troubles with it.
[https://mega.nz/#!mUElSRKS!weWGlDchI-6Jo4L-sv8bV4U6ePzpCXxrT93x2EK_3ow](url)

**Comment by HappyHarm** [comment]
It says github page not found? Maybe something wrong with the link?

**Comment by sgdc3** [comment]
@Phreag Please don't post jars without an attached source

**Comment by Phreag** [comment]
The source is included in the jar. it contains .class and .java code.

**Comment by sgdc3** [comment]
Ok, sorry ;)

**Comment by HappyHarm** [comment]
It's removed now xD?

**Comment by sgdc3** [comment]
@Phreag @HappyHarm yeah, sorry i lost the original link, can you repost it please? :)

**Comment by Phreag** [comment]
Okay. xD
Here is naother file, now a rar file. inside is the complete source directory and a compiled jar.
[https://mega.nz/#!iV9TWLrL!iC1fgLwuhAzqu3ZEjrPkYpa8NDOdS7Upiv6Rlx_gVGE](url)

**Comment by ljacqu** [comment]
Closing this—if there's a concrete issue, kindly open another issue.
