### ISSUE TITLE
/authme register name password  -> case-sensitivity

### ISSUE THREAD

**Issue by Platinteufel** [Xephi/AuthMeReloaded#578]
Hey,

if I register an account with /authme register name password the registered name is not case-sensitiv. 
I've just tried to register an account with **/authme register Platinteufel password** and now AuthMe tells me that I should join with _platinteufel_ and not with _Platinteufel_.

**Comment by ljacqu** [comment]
Thanks for the report, and thanks for the fix @DNx5

**Comment by Platinteufel** [comment]
Sorry but I don't find the build. :D

**Comment by games647** [comment]
From the ReadMe:

>Alternative Dev Build download link (via CircleCi): [Download](https://circleci-tkn.rhcloud.com/api/v1/project/AuthMe-Team/AuthMeReloaded/tree/master/latest/artifacts/AuthMe.jar)

**Comment by Platinteufel** [comment]
Thank you!
