### ISSUE TITLE
Authme problem command permission

### ISSUE THREAD

**Issue by ireeskenz** [Xephi/AuthMeReloaded#581]
First, thank's for our update 1.9 Devs. But i have a other problem now, i can't login me and i'm op. On game, it say me "You don't have permission to use this command!"

**Comment by ljacqu** [comment]
@ireeskenz Any news since you first posted? I would reckon there's some permission issue on your side. Sharing your permission config + what plugin you're using would be useful here

**Comment by ireeskenz** [comment]
It works :D sorry !
