### ISSUE TITLE
BungeeCord: save real IP of player

### ISSUE THREAD

**Issue by robimoli** [Xephi/AuthMeReloaded#582]
Hi, i like register in the DB the real ip of the players, i am using bungeecord and i havn´t got installed spigot, because it do very problems with the plugins.

I like take the real ip of a player and not the proxy-server ip.

Thanks, regards.

**Comment by ljacqu** [comment]
It should already be the real IP, could you check with a more recent dev build maybe? http://ci.xephi.fr/job/AuthMeReloaded/
