### ISSUE TITLE
Hide leave message for unlogged users

### ISSUE THREAD

**Issue by rErEaT** [Xephi/AuthMeReloaded#583]
I am using DeluxeJoin, how I can make a delay?
I added the kick when the player misstype the password then its spam the chat with join/leave messages.

So can I make a delay?

**Comment by sgdc3** [comment]
delayJoinMessage: true in your config should do the trick

**Comment by rErEaT** [comment]
not really :D

**Comment by rErEaT** [comment]
working with essentials but bug with other plugins what change the join event

**Comment by sgdc3** [comment]
Can you tell us the name of a plugin that isn't working?

**Comment by rErEaT** [comment]
DeluxeJoin, but i think anyother plugin wont work

**Comment by sgdc3** [comment]
You need to try, deluxejoin ovverrides any

**Comment by sgdc3** [comment]
join message changes

**Comment by rErEaT** [comment]
CTSNC+ working.
hmm

**Comment by rErEaT** [comment]
+ question, with -1 i disable the max reg with ip? 
and maxjoin etc, all ip limit to -1 will disable that?

**Comment by sgdc3** [comment]
use 0, but in theory -1 should work too.

**Comment by rErEaT** [comment]
thanks :)

**Comment by rErEaT** [comment]
okay thanks for everything!
but if the player leave before enter the correct password or register, the leave message is shows up.
can it disabled?

**Comment by rErEaT** [comment]
The join message delay is working but the leave messages still there :)

**Comment by sgdc3** [comment]
I know! xD We are focusing on the main bugs before working to enhancements ;)

**Comment by rErEaT** [comment]
okay

**Comment by sgdc3** [comment]
Wait, i remember i've added a removeLeaveMessage setting, have you enabled it? If yes, are you sure it doesn't work?

**Comment by rErEaT** [comment]
its sure remove that, but its remove the whole message :)

I mean the leave message is should removed before that player is login

**Comment by sgdc3** [comment]
Impossible with api, the only way is to add a "custom leave message" option.

**Comment by rErEaT** [comment]
ChatControl is makes this possible so everythings good :D

**Comment by sgdc3** [comment]
We can't know the quit message before the player disconnects due to api limitations, sorry. We need to add a new option ;)

**Comment by rErEaT** [comment]
okay, its good :)

**Comment by sgdc3** [comment]
See #833
