### ISSUE TITLE
Per world noTeleport

### ISSUE THREAD

**Issue by Gardiac** [Xephi/AuthMeReloaded#586]
<githubroot>Hey can you add "noTeleport" for certain world http://prntscr.com/abjz6o !
<br />Because like when player disconnect while felling in void he die when he reconnect thats all good so noTeleport will be allowed only in "world_the_end" 
<br />But like when he disconnect in his base in "world" world I dont wanna noTeleport because someone can go on his nickname and press f3 and he can see his base coords</githubroot>

**Comment by sgdc3** [comment]
noTeleport: false
teleportUnauthedToSpawn = true;
saveQuitLocation = true;

(Remember to set the spawnpoint with /authme setspawn)

**Comment by Gardiac** [comment]
When they disconnect they were teleport to spawn and they can disconnect whenever they fell but they wont die...

**Comment by sgdc3** [comment]
@Gardiac Can't understand your example :/ Can you post a video about it?

**Comment by Gardiac** [comment]
Gonna try to explain it again.
You went to world_the_end and you fell into void and you disconnect - you log-in back and you will be teleported to spawn and you wont die[BUG]
If I change noTeleport to true when you fell and you disconnect - you log-in back you will die , but also because I got Faction server people have bases , so he can type their's name in cracked launcher and if they disconnect in base he can easily press F3 and see the coords of base.
Thats why I want noTeleport to be allowed only in world_the_end!
Hope you got it now!

**Comment by sgdc3** [comment]
Yeah but as i said, 
teleportUnauthedToSpawn = true;
saveQuitLocation = true;
should fix your issue!

**Comment by Gardiac** [comment]
Its not fixed , you got skype so you can join server and see

**Comment by RoinujNosde** [comment]
@Gardiac if you set teleportUnauthedToSpawn true, the player will be temporarily teleported to authme spawn (/authme setspawn), when they successfully logs in, they go back to their last position.

**Comment by Gardiac** [comment]
Nope , I can't explain if you could add me on skype and I will give you an IP to server and you will see...
skype "benjamin.dzelle69"

**Comment by Gardiac** [comment]
https://www.youtube.com/watch?v=Uaocd_bTkGQ&feature=youtu.be --> video

**Comment by Gardiac** [comment]
FIXED !
ForceSpawnOnJoin: false
I should put that to false and not true!
