### ISSUE TITLE
Update Inventory Hider to 1.9

### ISSUE THREAD

**Issue by games647** [Xephi/AuthMeReloaded#587]
With the additionally off hand inventory slot, the inventory hider sets the block to a incorrect position.

**Comment by ireeskenz** [comment]
No news?

**Comment by games647** [comment]
I updated it to 1.9, but I don't know if it's backwards compatible. So it's not in the master branch for now.

**Comment by ljacqu** [comment]
Note that it's on master. :P But I think it's fine—there's no direct reference to anything that might be unavailable in previous versions. Looks great.

**Comment by games647** [comment]
@ljacqu I made the comment before I pushed the changes. I tested it now and it should work.

**Comment by ljacqu** [comment]
@games647 Oh, I understood it to mean that it's on another branch.
