### ISSUE TITLE
Non-Essentials MOTD spams the server

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#588]
From @Done84 in #542:
 Only issue i have now is MOTD ramdonly spamming when using:
< useEssentialsMotd: false>
I think the welcome.txt might be sent to all players everytime another player connects, but i cant really be 100% sure since i have login messages hidden in my servers.

**Comment by sgdc3** [comment]
Not a but. He needs to set broadcastWelcomeMessage to false! @Done84
