### ISSUE TITLE
The Plugins don't start

### ISSUE THREAD

**Issue by wendaf** [Xephi/AuthMeReloaded#59]
I have put the plugin in my folder plugins but the plugins dont load 
why?
help me please.

**Comment by sgdc3** [comment]
Can you post your console log please?

**Comment by wendaf** [comment]
I have change the plugin : http://dev.bukkit.org/bukkit-plugins/authme-reloaded/
it work
this plugin : http://www.spigotmc.org/resources/authme-reloaded.6269/
don't work

**Comment by sgdc3** [comment]
Are you using latest spigot version? (1.8.7)

**Comment by sgdc3** [comment]
I think this issue should be closed.
