### ISSUE TITLE
Authme-Spigot version + SkinsRestorer

### ISSUE THREAD

**Issue by Done84** [Xephi/AuthMeReloaded#590]
Hi.
Hi I hope this is isn't a duplicate, I tried but didn't find any other issue.. so..
So when using Authme-Spigot and SkinsRestorer players with no skin set are invisible in game, i am not sure if this is a bug in authme or skinsrestorer I just know they're not compatible with each other.

The older versions of authme work just fine.

**Comment by Platinteufel** [comment]
Just disable hideTablistBeforeLogin ...

**Comment by Platinteufel** [comment]
#576
