### ISSUE TITLE
Please fix use one email for multiple accounts!

### ISSUE THREAD

**Issue by vanthoi** [Xephi/AuthMeReloaded#591]
My server was too much spam. I've enabled register by email. But this plug accidentally allowed to register using an email multiple accounts. So continue to be spam server. So you can fix this error.
Thank you!

**Comment by ljacqu** [comment]
How does it not work? There's a maxRegPerEmail setting.

**Comment by sgdc3** [comment]
We still need to check the maximum number of registration per ip. Max reg per email should be an additional protection.

**Comment by vanthoi** [comment]
How to set max reg per IP if server use Bungee cord ?
Yes I like max reg per Email !

**Comment by sgdc3** [comment]
@vanthoi Just enable the ip_forward setting bungee side and the bungeecord feature in your spigot.yml file (server side)

**Comment by sgdc3** [comment]
@ljacqu Idk if two users can use the same email to register :/ I think it should be unique....

**Comment by ljacqu** [comment]
We have a setting to allow multiple emails—if set to 1 the email is unique. This allows people to choose.

I'm personally not a big fan of restrictive email settings; for example Gmail will allow tons of different looking addresses, test@gmail, te.st@gmail, test+auth@gmail will all end up at the same address. So if you want to have 1 acc per person it needs to be done otherwise

**Comment by sgdc3** [comment]
We need a getallauthsbyemail method to fix the registration messages

**Comment by ljacqu** [comment]
http://ci.xephi.fr/job/AuthMeReloaded/javadoc/fr/xephi/authme/datasource/DataSource.html#countAuthsByEmail-java.lang.String- ;)

**Comment by sgdc3** [comment]
Lol!

**Comment by metroyanno** [comment]
@vanthoi you can create site and host on them any script to register, I'm do them. And this my example: slycraft.ru (not add). Without connecting to MySql server AuthMe and script

**Comment by sgdc3** [comment]
Should have been fixed ;)

**Comment by sgdc3** [comment]
@vanthoi

**Comment by ljacqu** [comment]
Closing—assuming fixed.
