### ISSUE TITLE
SHA256 SHIFRATE IN AUTHME

### ISSUE THREAD

**Issue by metroyanno** [Xephi/AuthMeReloaded#593]
Hi everybody, and sorry for caps. I'm from Russia, and I so bad in English :(. Can ypu help me with my project? Okay. I would have to learn how to encrypt passwords plug AuthMe, or rather his actions , who can , I beg you to write some code encryption in PHP, all that I need for my project , as I wrote earlier. The forums already searched , found nothing
***Translated by TRANSLAE.GOOGLE.RU :P***

**Comment by ljacqu** [comment]
PHP sample integration for AuthMe—https://github.com/AuthMe-Team/AuthMeReloaded/tree/master/samples/website_integration

**Comment by metroyanno** [comment]
Thanks! :)
