### ISSUE TITLE
AuthMe date and session

### ISSUE THREAD

**Issue by metroyanno** [Xephi/AuthMeReloaded#594]
Do not tell , I have a line in MySql "lastlogin", as I understand it , it is the time , and here is how to use it? In general, where the session is stored in AuthMe ?
***Translated by TRANSLATE.GOOGLE.RU***

**Comment by metroyanno** [comment]
UPD: please, write code to calculate time in PHP :3

**Comment by sgdc3** [comment]
@Xephi @games647 @ljacqu

**Comment by ljacqu** [comment]
lastlogin is a Unix timestamp.

1. fetch column from db
2. format number with [date()](http://php.net/manual/en/function.date.php) for human-readable output

**Comment by metroyanno** [comment]
@ljacqu sorry, but I can't decode format of date in the my DB

**Comment by metroyanno** [comment]
@ljacqu and my data from the DB: 1457440773568 can you decrypt them?

**Comment by metroyanno** [comment]
@ljacqu thanks for format to fuction, I'm get them:
$unixdate = date("Uni");
echo $unixdate;
and all good!
