### ISSUE TITLE
[Suggestion] allow unlimited login/register/join from defined ip.

### ISSUE THREAD

**Issue by rErEaT** [Xephi/AuthMeReloaded#595]
I think its should be a good idea :D

**Comment by sgdc3** [comment]
you can already use the console to bypass that :/

**Comment by sgdc3** [comment]
Yeah, this would only create security issues...

**Comment by rErEaT** [comment]
oh

**Comment by sgdc3** [comment]
Ps: an allow multiple accounts perm node already exist

**Comment by rErEaT** [comment]
what is that? :D

**Comment by sgdc3** [comment]
?

**Comment by rErEaT** [comment]
"Ps: an allow multiple accounts perm node already exist"

**Comment by rErEaT** [comment]
thanks
