### ISSUE TITLE
Error occurred while enabling AuthMe

### ISSUE THREAD

**Issue by TheKillHDmc** [Xephi/AuthMeReloaded#598]
Hey,

I have a problem when I update Authme 3.4 to 3.5 : 

http://pastebin.com/NXn0gYuu

**Comment by sgdc3** [comment]
You need to use this jar (the -legacy edition): http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT-legacy.jar

**Comment by TheKillHDmc** [comment]
thx!
