### ISSUE TITLE
[Dev] ConsoleLogger improvements

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#605]
- [ ] Log the level into authme.log as well -> as a user it's interesting to just quickly check for WARN entries
- [ ] Can we use the log4j style `{}` argument placeholders with some restructuring?
- [ ] Can we fine-tune the config of log4j (not a new setting on our side) to log different levels? It would allow us to use a FINE or DEBUG level for development without spamming anyone else

**Comment by sgdc3** [comment]
No, i think we can use only INFO, WARNING and SEVERE due to Craftbukkit/Spigot limitations.

**Comment by ljacqu** [comment]
Part of this story is to check that

**Comment by ljacqu** [comment]
Some sort of debug level would be quite useful and make it easier for plugin users & for us to troubleshoot problems, e.g. for the random logouts, or for database integrations to make sure the salt can be retrieved, etc.

**Comment by sgdc3** [comment]
+1

**Comment by sgdc3** [comment]
@ljacqu 100% done?

**Comment by ljacqu** [comment]
2nd point isn't done (formatted string with separately passed arguments), for reasons discussed in https://github.com/AuthMe/AuthMeReloaded/pull/148
If you think something else is missing, please let me know
