### ISSUE TITLE
RollBack position

### ISSUE THREAD

**Issue by Blamo27** [Xephi/AuthMeReloaded#608]
The position of players sometimes rollback upon reconnection
Positions are saved into a MySQL databse.

This bug occurs with the latest build (AuthMe ver 5.2 b-870).

**Comment by ljacqu** [comment]
Is this still an issue you're experiencing? How does it rollback? Back to 0, 0, 0 or some old position of the player?

**Comment by Blamo27** [comment]
Not to 0,0,0
=> Rollback to a previous position (1 min / 2 mins before)

**Comment by ljacqu** [comment]
Thanks for the feedback. You say this happens _sometimes_—is there any pattern you can think of?

**Comment by Blamo27** [comment]
@ljacqu Sorry I don't saw your message, I think it's fixed
