### ISSUE TITLE
How to fix command server use bungee cord Spigot

### ISSUE THREAD

**Issue by vanthoi** [Xephi/AuthMeReloaded#609]
I use server on Bungee cord Spigot.
I create server private have login with Authme Reload. And new sub server. 
If Player login server Private, after porward sub server /server subserver.
Ok good.
But player not login will go to comand /server subserver worked!
How to fix it!

Thanks!

**Comment by sgdc3** [comment]
You need to use latest AuthMeBridge release ;)

**Comment by vanthoi** [comment]
Ok good but not move consoler warning: player moved too quickly!
I config removeSpeed: false But will not world.
i set speed 1 then move!

**Comment by sgdc3** [comment]
I think this is not an issue caused by authme.

**Comment by vanthoi** [comment]
But if I remove authme bridge. Logged normal, no matter what happens. As I look out at the time of the warning consoler. Then the speed is 0! So I think it is the speed of authme remove when not logged into the server

**Comment by sgdc3** [comment]
@ljacqu maybe an issue with the new settings manager :/

**Comment by ljacqu** [comment]
@sgdc3 I haven't followed this thread, but I would guess if the value returned by the settings manager for some config isn't the same in both circumstances, there is indeed a problem. Otherwise it's probably some logic error elsewhere (_how_ the setting is being used/checked).

**Comment by vanthoi** [comment]
To fix on me was trembling command after logging in or signing up. run set speed = 1. You can also try to set speed = 0 then move on to see the warning consoler.

**Comment by vanthoi** [comment]
I leave this problem is due authme bridge. Because it has blocked all command if not logged in. So when players connect to authme reload connected before and identity are not logged in and set speed = 0. But then authme bridge caught the new login token notify authme reload this person has logged authme bridge But this time not access to run up. Authme reload contest made by one set speed by the time the command is so fast authme bridge not meet the grant run for this player. From there arises a problem on.

**Comment by sgdc3** [comment]
You need to update to latest authmebridge and authmebridgebukkit version. If this doesn't dix the issue disable the autoLogin feature in authmebridge (bungee side) config.

**Comment by vanthoi** [comment]
OK. The last version of the spigot build today had fixed on. Thank you!
