### ISSUE TITLE
[Question] How Essentials + Permissions autopurge works?

### ISSUE THREAD

**Issue by RoinujNosde** [Xephi/AuthMeReloaded#613]
Hi,
How autopurge deletes Essentials files?
By username? By UUID? By both?

Also, "removePermissions" supports all permissions plugins? Does it removes a player from their group or only their permissions?

**Comment by ljacqu** [comment]
Hi @RoinujNosde :)

Essentials files are indeed deleted by UUID. If for some reason the UUID file doesn't exist, we will try with the player name as file name (as Essentials did in previous versions).

Not sure what you mean with remove permissions? Is that a command or also something within the purge process?

**Comment by RoinujNosde** [comment]
@ljacqu I'm talking about this new option in config.yml: "removePermissions: false".

**Comment by sgdc3** [comment]
It removes permissions and groups when a player is purged. Just found an error in the code: we need to use an OfflinePlayer not an online one. @ljacqu

**Comment by RoinujNosde** [comment]
@sgdc3 does it supports all permission plugins?

**Comment by sgdc3** [comment]
vault, pex, groupmanager, bPermissions, zPermissions

**Comment by sgdc3** [comment]
If you have vault it should support every vault-compatible perm manager.

**Comment by RoinujNosde** [comment]
Thank you :)
