### ISSUE TITLE
AuthMe blocking SkinsRestorer on 1.9

### ISSUE THREAD

**Issue by TenzoNakami** [Xephi/AuthMeReloaded#615]
After updating from AuthMe 5.0 to AuthMe 5.2, the SkinsRestorer can't set Player's skin on log in and players will be invisible.

**Comment by TenzoNakami** [comment]
More details: Using AuthMe 5.2 #890 under Spigot 1.9-R0.1-SNAPSHOT

**Comment by games647** [comment]
Could you disable hideTablist in the AuthMe config?

**Comment by sgdc3** [comment]
@TenzoNakami

**Comment by TenzoNakami** [comment]
@games647 @sgdc3
Sorry for the late reply guys, and thanks for the help! It actually worked!
Thank you guys for helping :)
