### ISSUE TITLE
Movement block until login or register

### ISSUE THREAD

**Issue by PabloMA98** [Xephi/AuthMeReloaded#618]
Before login or register, the movement is blocked, but if the player jumps and try to walk, he can move of her initial position. Also, the camera block doesn't work.

I use Spigot 1.9 and AuthMe 5.2 Beta 1.

**Comment by sgdc3** [comment]
@PabloMA98 The camera isn't locked on purpose.

**Comment by rErEaT** [comment]
authme just set the player walk speed to 0. nothing else

**Comment by sgdc3** [comment]
so, what's the purpose of this report?

**Comment by rErEaT** [comment]
i dont know

**Comment by ljacqu** [comment]
> but if the player jumps and try to walk, he can move of her initial position

@PabloMA98 Is there anything more you can say about this portion of your text?

**Comment by rErEaT** [comment]
in 1.9 the players can jostle others, so its may be the problem then

**Comment by sgdc3** [comment]
have you enabled the disableCollisions option in your authme config?

**Comment by rErEaT** [comment]
no i dont :D

**Comment by sgdc3** [comment]
@rErEaT does it work for you now?

**Comment by rErEaT** [comment]
@sgdc3 where can I disable that?

I am using this version: AuthMe-v5.2-SNAPSHOT-b930

**Comment by ljacqu** [comment]
@rErEaT In config.yml, it would be:

```yml
        keepCollisionsDisabled: true
```

**Comment by rErEaT** [comment]
oh, sorry. now its true :)

**Comment by rErEaT** [comment]
I think its working, they can jump a little bit but it maybe just 1 cm :D

**Comment by sgdc3** [comment]
> camera is not blocked, but no need to block that :)
It was useless: hacks can easily bypass it ;)

**Comment by sgdc3** [comment]
My latest commit should fix some of the movement issues ;)

**Comment by rErEaT** [comment]
sure, now fully block the moves :D
