### ISSUE TITLE
Authme new language ( Turkish )

### ISSUE THREAD

**Issue by smt287** [Xephi/AuthMeReloaded#621]
Hello,
I'm translated your plugin in Turkish ( tr ).
NO ERROR!

Alternative links;
- http://hastebin.com/eyesofedim.xml
- http://paste.ubuntu.com/15467737/

**Comment by sgdc3** [comment]
Thank you, i'll add it asap ;)

**Comment by ljacqu** [comment]
@sgdc3 boop :)

**Comment by sgdc3** [comment]
Whoops, done ;)
