### ISSUE TITLE
[Question] AuthMeMYSQLPool

### ISSUE THREAD

**Issue by RoinujNosde** [Xephi/AuthMeReloaded#622]
build: 894
I just got this warning:
```
WARN INFO fr.xephi.authme.libs.hikari.pool.PoolBase - AuthMeMYSQLPool - Driver does not support get/set network timeout for connections. (com.mysql.jdbc.JDBC4Connection.getNetworkTimeout()I)
```
Should I be worried about it? Will it affect server performance? What can I do?

**Comment by sgdc3** [comment]
It should work fine, but I'm curious :/ @Xephi what do you think?

**Comment by sgdc3** [comment]
Just found this: https://github.com/brettwooldridge/HikariCP/issues/593
It should be fine, but are you sure you're using latest version?

**Comment by sgdc3** [comment]
Ok it's the latest build, sorry ;)

**Comment by sgdc3** [comment]
Just ignore it atm. Nothing dangerous. ;)

**Comment by RoinujNosde** [comment]
OK, thanks :)
