### ISSUE TITLE
Can't move after login

### ISSUE THREAD

**Issue by Chinimala** [Xephi/AuthMeReloaded#624]
The player can't move after login, on "AuthMe-5.2-SNAPSHOT-spigot". The server is on "craftbukkit 1.9-R0.1-SNAPSHOT". I got those errors : http://pastebin.com/Ricen5FE . I tried with my old files and without any "AuthMe" folder at start.

EDIT : I found that walkspeed is set to 0, because when I type "/walkspeed 1", I can move. Still troublesome for my players.

**Comment by RoinujNosde** [comment]
Try to use the last build http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT-legacy.jar

**Comment by Chinimala** [comment]
Thank you for the link, but I still can't move after login and there is still the error message.

**Comment by RoinujNosde** [comment]
In your config:
If removeSpeed is true, set to false.

**Comment by Chinimala** [comment]
That's it, thank you very much, we can move.
There is still the error message, although it doesn't bother me.

**Comment by RoinujNosde** [comment]
Yeah, i think you should create a new ticket.
A quick question: Do you have protocollib?

Also, I would not close this issue since it's not completely solved. (Players should be able to move after login even with removeSpeed true)

**Comment by Chinimala** [comment]
Yes I have it, and as you asked the question, I tried to remove it and update it, and in both cases the error message disappeared :)
Leaving the ticket for the removeSpeed issue only then.

**Comment by RoinujNosde** [comment]
@Chinimala You're welcome.
About the removeSpeed, let's wait the developers :)

**Comment by sgdc3** [comment]
@games647 It seems an issue with protocollib :/

**Comment by games647** [comment]
@sgdc3 Not anymore
> I tried to remove it and update it, and in both cases the error message disappeared

**Comment by sgdc3** [comment]
ok, so, what's the issue now?

**Comment by RoinujNosde** [comment]
@sgdc3
Players can't move after they successfully login. (This only happens if removeSpeed is true)

**Comment by sgdc3** [comment]
Really strange..

**Comment by Platinteufel** [comment]
ProtocolLib Version?

**Comment by Platinteufel** [comment]
Upgrade to the latest ProtocolLib and try to fix your huge lags
[22:35:35] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 6942ms behind, skipping 138 tick(s)

**Comment by games647** [comment]
Could you send us a Timings report? "/timings report"

**Comment by Chinimala** [comment]
When I type "/timings report" (after having set settings : plugin-profiling to true in my bukkit.yml), it only proposes "Usage : /timings <reset|merged|separate>". I don't know what these commands do so I don't test them until you tell me what to do.
Platinteufel > Are you looking at the error message ? Because this problem is fixed. I use ProtocolLib 3.7.0-BETA.

**Comment by Platinteufel** [comment]
Is there any reason why you are running cb instead of spigot? Nevertheless, I'd recommend updating to cb/spigot 1.9.2. Maybe you are running a very early 1.9 version.
/timings merged is the command we need.

**Comment by Chinimala** [comment]
I use the 1.9 version of my host, verygames. I actually just finished downloading craftbukkit 1.9.2 on my computer, I will try going on openmod to set my own minecraft jar, as verygames doesn't offers craftbukkit 1.9.2.
I don't have any particular reason to run cb instead of spigot, I used cb for 4 years.
Here is my timings.txt : http://pastebin.com/CzLhTvMZ. Do you need that I upload it while "removeSpeed" is on true ?

**Comment by Platinteufel** [comment]
Indeed, this is an issue of the latest dev-builds. Could you tell me which version of AuthMe you are running exactly? b870?

**Comment by Chinimala** [comment]
Yes

**Comment by Platinteufel** [comment]
Please give me a minute to test sth.

**Comment by Platinteufel** [comment]
Is it possible for you to provide the latest.log from serverstart?

**Comment by Chinimala** [comment]
I cut the end, here it is : http://pastebin.com/fvSXYFFe

**Comment by Platinteufel** [comment]
Okay, please try it with the latest craftbukkit, this version is REALLY old.

**Comment by Chinimala** [comment]
Fixed with craftbukkit 1.9.2

**Comment by sgdc3** [comment]
ok thanks ;)
