### ISSUE TITLE
Kick player from bungeecord instead of moving him to the default server

### ISSUE THREAD

**Issue by MrTheBank** [Xephi/AuthMeReloaded#625]
>     bungeecord: true
    # Send player to this BungeeCord server after register/login
    sendPlayerTo: 'lobby'

When i don't login and when it's timeout it's gone to another server in config is lobby

**Comment by sgdc3** [comment]
@ljacqu @games647 @DNx5

**Comment by CryLegend** [comment]
` force_default_server: true`

**Comment by sgdc3** [comment]
@MrTheBank could you try @CryLegend 's fix? ;)

**Comment by MrTheBank** [comment]
OK It's kick now closed this

**Comment by sgdc3** [comment]
Wait i don't think this is fixed :/

**Comment by CryLegend** [comment]
This may happen to MoveMeNow users, but I don't think it's AuthMe fault

**Comment by sgdc3** [comment]
@CryLegend Yeah, but i think we should send a kick player message via messaging to the bungeecord if configured in the config. Would it solve the issue? ;)

**Comment by CryLegend** [comment]
It depends on how "move on kick" plugins are made, but it may work.

**Comment by sgdc3** [comment]
People can already do that by looking at the authme kick message bungee-side.
