### ISSUE TITLE
AutoPurge

### ISSUE THREAD

**Issue by rErEaT** [Xephi/AuthMeReloaded#627]
[01:03:46 INFO]: [AuthMe] AutoPurging the Database: 722 accounts removed!
[01:08:40 INFO]: [AuthMe] AutoPurgeDatabase: Removed 722 EssentialsFiles
[01:12:34 INFO]: [AuthMe] AutoPurgeDatabase: Removed 242 .dat Files
[01:15:56 INFO]: [AuthMe] AutoPurgeDatabase: Removed 0 LimitedCreative Survival, Creative and Adventure files
[01:19:52 INFO]: [AuthMe] AutoPurgeDatabase: Removed 0 AntiXRayData Files
[01:19:52 INFO]: [AuthMe] AutoPurgeDatabase: Removed 0permissions

Its too slow, and did not remove anything

**Comment by RoinujNosde** [comment]
>> and did not remove anything

What do you mean?

**Comment by rErEaT** [comment]
this feature may remove the files or not?

**Comment by RoinujNosde** [comment]
It does remove.

**Comment by rErEaT** [comment]
then too slow, and this number is never reset :D

**Comment by RoinujNosde** [comment]
I think the speed depends on how many files are getting removed.
Uh, never reset?

**Comment by rErEaT** [comment]
the number is all tim bigger and the start slower and slower

**Comment by RoinujNosde** [comment]
What?

**Comment by rErEaT** [comment]
The number is increasing every time. so never reset.

And it makes the startup time becomes slower and slower

**Comment by RoinujNosde** [comment]
How many days you set to purge an account?

**Comment by rErEaT** [comment]
30

but I restart my server everynight

**Comment by RoinujNosde** [comment]
mysql/sqlite or flatfile?

**Comment by rErEaT** [comment]
flatfile

**Comment by RoinujNosde** [comment]
Maybe that's the problem, try to use sqlite.
Also, what version of AuthMe you have?

**Comment by rErEaT** [comment]
I cant use that.

The latest dev version #894

**Comment by k3ldon** [comment]
in mysql is slow too but only 5 to 10min

**Comment by RoinujNosde** [comment]
@rErEaT Just set backend to sqlite.

**Comment by rErEaT** [comment]
DataSource: 
    # What type of database do you want to use?
    # Valid values: sqlite, mysql
    backend: 'SQLITE'
    # Enable database caching, should improve database performance
    caching: true
    # Database host address
    mySQLHost: '127.0.0.1'
    # Database port
    mySQLPort: '3306'
    # Username about Database Connection Infos
    mySQLUsername: 'authme'
    # Password about Database Connection Infos
    mySQLPassword: '12345'
    # Database Name, use with converters or as SQLITE database name
    mySQLDatabase: 'authme'
    # Table of the database
    mySQLTablename: 'authme'
    # Column of IDs to sort data
    mySQLColumnId: 'id'
    # Column for storing or checking players nickname
    mySQLColumnName: 'username'
    # Column for storing or checking players RealName 
    mySQLRealName: 'realname'
    # Column for storing players passwords
    mySQLColumnPassword: 'password'
    # Column for storing players emails
    mySQLColumnEmail: 'email'
    # Column for storing if a player is logged in or not
    mySQLColumnLogged: 'isLogged'
    # Column for storing players ips
    mySQLColumnIp: 'ip'
    # Column for storing players lastlogins
    mySQLColumnLastLogin: 'lastlogin'
    # Column for storing player LastLocation - X
    mySQLlastlocX: 'x'
    # Column for storing player LastLocation - Y
    mySQLlastlocY: 'y'
    # Column for storing player LastLocation - Z
    mySQLlastlocZ: 'z'
    # Column for storing player LastLocation - World Name
    mySQLlastlocWorld: 'world'
    # Enable this when you allow registration through a website
    mySQLWebsite: false

ExternalBoardOptions: 
    # Column for storing players passwords salts
    mySQLColumnSalt: ''
    # Column for storing players groups
    mySQLColumnGroup: ''
    # -1 means disabled. If you want that only activated players
    # can log into your server, you can set here the group number
    # of unactivated users, needed for some forum/CMS support
    nonActivedUserGroup: -1
    # Other MySQL columns where we need to put the username (case-sensitive)
    mySQLOtherUsernameColumns: []
    # How much log2 rounds needed in BCrypt (do not change if you do not know what it does)
    bCryptLog2Round: 10
    # phpBB table prefix defined during the phpBB installation process
    phpbbTablePrefix: 'phpbb_'
    # phpBB activated group ID; 2 is the default registered group defined by phpBB
    phpbbActivatedGroupId: 2
    # Wordpress prefix defined during WordPress installation
    wordpressTablePrefix: 'wp_'

its the default, i did not change

**Comment by RoinujNosde** [comment]
You said flatfile ¬¬

You sure the files are not been removed?

**Comment by rErEaT** [comment]
authme.db

I dont know about that, but the startup is slower and slower :S

**Comment by k3ldon** [comment]
10min

![image](https://cloud.githubusercontent.com/assets/8853186/14075533/53ab3c1a-f4b0-11e5-8109-0e3c155814ea.png)

**Comment by RoinujNosde** [comment]
@sgdc3

**Comment by DNx5** [comment]
Latest dev build should fix the problem :smile: 
but do backup first.

**Comment by rErEaT** [comment]
checking...

**Comment by rErEaT** [comment]
[17:21:26 WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.2-SNAPSHOT-b905 generated an exception while executing task 20
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:201)
        at ru.tehkode.permissions.bukkit.PermissionsEx.getUser(PermissionsEx.java:416)
        at fr.xephi.authme.permission.PermissionsManager.getGroups(PermissionsManager.java:449)
        at fr.xephi.authme.permission.PermissionsManager.removeAllGroups(PermissionsManager.java:845)
        at fr.xephi.authme.DataManager.purgePermissions(DataManager.java:147)
        at fr.xephi.authme.AuthMe$4.run(AuthMe.java:740)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by rErEaT** [comment]
The AutoPurge is seems to be works fine!

**Comment by DNx5** [comment]
Good, you could try to disable `Purge.removePermissions` option if you want to get rid with that error.

**Comment by rErEaT** [comment]
okay thanks!
