### ISSUE TITLE
Wrong password - Grave Issue, please help

### ISSUE THREAD

**Issue by MithrandirCraft** [Xephi/AuthMeReloaded#628]
Tonight I attempted to re-establish inventory protections before login, which had somehow gotten disabled (Provably due to outdated ProtocolLib). 

However, this action resulted in a MAJOR disaster. Somehow (And seemingly unrelatedly), many player's passwords & or access, including mine got corrupt/denied. Now a lot of players get wrong password messages when attempting to login.

I can't revert this by reseting inventory protection to false... I didn't touch anything else from Authme, or it's ProtocolLib dependency.
Worst part is that I can't even get through this by changing my password, as I always get access denied because my password is incorrect, even though I changed it two seconds ago.
I don't even know if the passwords are actually corrupt, as they are well encrypted on the database, but It does seem to be a deep problem with password imputing, as I cannot reset my pw even when logged in. The password will always be incorrect.

This is a true disaster for my server. Most players can't log in.

I'm already using the latest dev build, and I don't know how to fix this. The only thing that comes to mind is a total password reset (At very least) which wouldn't guarantee a true solution.

--------------------
Spigot version: 1.9
Authme version: 5.2 b894

**Comment by MithrandirCraft** [comment]
I rolled back my server to a backup from 24h ago, so that's it.

I'm definetly not touching anything from Authme untill at least a month. lol

**Comment by sgdc3** [comment]
Thank you, we'll investigate. ;)

**Comment by MithrandirCraft** [comment]
Hm... allthough I made a backup, there are still some players that can't log in u_u

**Comment by MithrandirCraft** [comment]
Something is well broken.
Players can't use email recovery either u_u

**Comment by MithrandirCraft** [comment]
Ok, this is absolutely crazy, but I think something is making players sent text to change.

For example, when someone writes a 1, a 2 comes out. That could potentially be making player's passwords to fail. I'll be investigating this.

**Comment by sgdc3** [comment]
wtf have you installed some plugins recently?

**Comment by MithrandirCraft** [comment]
Ok man, I slowly started to realize that this isn't Authme's fault.

Another plugin I use, called ChatGuard, was changing written ones (1) into two's (2).

Consequently, players couldn't write the number one. Therefore, all passwords including a one could not be written propperly, as all ones where turned into two's, resulting in invalid password (lol)

I appollogize for this. Anyway, it's a real releaf.

**Comment by MithrandirCraft** [comment]
Also, inventory protection works perfect :P I tested it again.
