### ISSUE TITLE
avoid player collisions for unlogged users in 1.9

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#630]
In 1.9 players are unable to stay on the same block, this breaks the allowMovement: false behaviour and cause lag as the server tries to teleport the player to the spawn block continuously.

**Comment by ljacqu** [comment]
Can you add a description? ;)

**Comment by sgdc3** [comment]
Sorry ;)

**Comment by ljacqu** [comment]
Thanks :+1: :3

**Comment by DNx5** [comment]
How???

**Comment by Platinteufel** [comment]
You can also check out my issue on spigots jira.
https://hub.spigotmc.org/jira/browse/SPIGOT-2102

________
Off-topic: What the hell is BountifulAPI (sgdc3-noupdater) and why it rebuilds every minute? @sgdc3 
http://ci.xephi.fr/job/BountifulAPI%20%28sgdc3-noupdater%29/ 
I'm just curious, sorry. xD

**Comment by sgdc3** [comment]
wtf every minute xD

**Comment by sgdc3** [comment]
Thank you, you saved our jenkins xD

**Comment by sgdc3** [comment]
@DNx5 https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/LivingEntity.html#setCollidable(boolean)

**Comment by Platinteufel** [comment]
Fixed: https://hub.spigotmc.org/jira/browse/SPIGOT-2102
