### ISSUE TITLE
Could not pass event PlayerLoginEvent to AuthMe v5.2-SNAPSHOT-b896

### ISSUE THREAD

**Issue by tuanjr** [Xephi/AuthMeReloaded#632]
Here are errors:
http://paste.ubuntu.com/15566035/
And, please fix issues with minecraft 1.9, when player can push another players, on authme setting ForceSpawnLocOnJoinEnabled: true, so it's spam console with warning "Player moved too quickly! "

**Comment by DNx5** [comment]
the error should've fixed now.
for workaround, you could set 
```
allowMovement: true
allowedMovementRadius: 5 #Higher is better if you have many player joining
```
Hope that's work while we are fixing the problem.

**Comment by jwtuan** [comment]
thank, i will try :)

**Comment by tuanjr** [comment]
Could not pass event PlayerLoginEvent are fixed, 
but about issues "pushing player"
```
allowMovement: true
allowedMovementRadius: 5 #Higher is better if you have many player joining
```
Won't work! both unregisted player and registed player still cant walk around 5 radius, still apear  moved too quickly!

**Comment by DNx5** [comment]
yeah, that's different issue. should be on #630
