### ISSUE TITLE
Error to recovery password via EMAIL

### ISSUE THREAD

**Issue by NickFirenzo** [Xephi/AuthMeReloaded#633]
Hi,
I want to report error when use the command for recovery. Before 24h works fine, succsess sent an email to email. But now when try to recovery, when use /email recovery email@hotmail.com, in console getting: 

02.04 18:51:27 [Server] WARN Failed to send a mail to [email@hotmail.com]: Sending the email to the following server failed : smtp.gmail.com:465

How can I fix it? Thanks :)

**Comment by RoinujNosde** [comment]
May I see your config.yml? Is your server localhost? Are you using last version of authme?

**Comment by NickFirenzo** [comment]
Config.yml: http://pastebin.com/wdxzZTvc
Using latest build.

**Comment by RoinujNosde** [comment]
Config seems to be all right.
Again, is your server hosted?

**Comment by NickFirenzo** [comment]
My server is still on my dedicated

**Comment by sgdc3** [comment]
Have you enabled the 'allow unsafe application' feature in your gmail account?

**Comment by NickFirenzo** [comment]
It seems the problem is to GMAIL by blocking the IP address of the server dedicated think that dedi try to hack the gmail account.

**Comment by sgdc3** [comment]
Yeah, check out this feature: http://www.google.com/settings/security/lesssecureapps

**Comment by sgdc3** [comment]
Switch it to enabled and it should work fine ;)

**Comment by NickFirenzo** [comment]
Already enabled, 
here is the problem http://prntscr.com/anjdx4

**Comment by sgdc3** [comment]
Try with port 587 :/

**Comment by NickFirenzo** [comment]
Same error

**Comment by sgdc3** [comment]
@Xephi do you remember the failsafe gmail recovery setup?

**Comment by NickFirenzo** [comment]
The problem is not AUTHME. Problem is gmail, I fixed the problem. 
Create new gmail account and problem solved

**Comment by sgdc3** [comment]
Lol, fine
