### ISSUE TITLE
LOGIN MOVEMENT SPEED BUG

### ISSUE THREAD

**Issue by RAZERMC** [Xephi/AuthMeReloaded#645]
USING SPIGOT 1.8.8
AUTHME BUILD #924 
JAVA VERSION 8

NO CONSOLE ERROR

authme Config Settings 
allowMovement: true
movementRadius: 6
removeSpeed: false #BUG 

when you enter server and is not login yet you can only jump to move normal walking or running is impossible 

extra information: movement being detected as glide cheat

**Comment by RAZERMC** [comment]
Just found out after logging in the speed does not come back, stuck with jumping to move 
Change setting removespeed to true and allowMovement to false and i can move again after loggin

**Comment by sgdc3** [comment]
Try to update your spigot ;) I think it's related to a bug in old spigot 1.9 builds.

**Comment by RAZERMC** [comment]
i am using spigot 1.8.8
authme version 3.5 does not have this bug

**Comment by RAZERMC** [comment]
please check the code for removeSpeed and restoring speed after login 
i dont have plans yet to migrate to spigot 1.9 as most of my plugins is still 1.8.8 dependent

**Comment by sgdc3** [comment]
Whoops misread your version ;)

**Comment by RAZERMC** [comment]
verified on spigot 1.8.8 with only essentials plugin + group manager installed

**Comment by sgdc3** [comment]
Closed as it should have been fixed, please reopen this issue if the problem persist @RAZERMC

**Comment by RAZERMC** [comment]
ok downloading the latest dev testing it thanks
