### ISSUE TITLE
Register bug (with wordpress) #2

### ISSUE THREAD

**Issue by hakumanatatu** [Xephi/AuthMeReloaded#646]
Hi,
I found another bug with "wordpress hash".
https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/datasource/MySQL.java
bug with wordpress prefix in the table usermeta
```
row 481 pst2.setString(2, "wp_capabilities"); 
==>
wordpressPrefix + "capabilities"

row 486  pst2.setString(2, "wp_user_level");
==>
wordpressPrefix + "user_level"
```
thanks for fix

**Comment by sgdc3** [comment]
Thank you ;)
