### ISSUE TITLE
Hungarian language

### ISSUE THREAD

**Issue by rErEaT** [Xephi/AuthMeReloaded#647]
I updated the Hungarian messages :)
found some mistakes!
[messages_hu.zip](https://github.com/Xephi/AuthMeReloaded/files/220871/messages_hu.zip)

**Comment by sgdc3** [comment]
Thank you ;)

**Comment by rErEaT** [comment]
no problem :D

**Comment by rErEaT** [comment]
@sgdc3 can you add? :)

**Comment by rErEaT** [comment]
oh sh*t reuploaded. Did again a mistake, now correct :)

**Comment by ljacqu** [comment]
I passed it through our validation test:
```md
- Message with key 'max_reg' missing tags: %max_acc, %reg_count, %reg_names
- Message with key 'usage_captcha' missing tag: <theCaptcha>
- Missing message for key 'email_already_used'
- Message with key 'two_factor_create' missing tag: %url
- Missing message for key 'not_owner_error'
```

Especially `usage_captcha` and `two_factor_create` would be nice if they could be corrected :)

**Comment by rErEaT** [comment]
Okay I will add it from eng lang file

köszök? :)
do you mean thanks?

**Comment by ljacqu** [comment]
Thanks :) That's what I meant, yes. I learned what difference one S can make today :P

![koss](https://cloud.githubusercontent.com/assets/8417009/14560957/58ac979c-0313-11e6-9999-15ad1034295b.png)

**Comment by rErEaT** [comment]
"You can scan it from here %url"

what does it mean?
can you make me an example?

however added every missing things :)
[messages_hu.zip](https://github.com/Xephi/AuthMeReloaded/files/220913/messages_hu.zip)

**Comment by rErEaT** [comment]
@ljacqu Thanks  in hungarian is Köszönöm :)

google translate is sh*t :DDD

**Comment by rErEaT** [comment]
[](https://p1.picsto.re/NA7Dx.png)

**Comment by ljacqu** [comment]
Thanks, @rErEaT 
The message is for Two Factor Authentication. Typically you scan a QR code with your phone for it, or you can follow the URL at `%url` (it will be replaced) for phones without cameras or some other issue.

Funny, my old printer used to print a test page to make sure that everything was alright, and the page was _Thanks_ in many languages. I distinctly remember "kösszök" being on there.

**Comment by rErEaT** [comment]
[messages_hu.zip](https://github.com/Xephi/AuthMeReloaded/files/220920/messages_hu.zip)

everything added and corrected :)
check please and add then :P

**Comment by rErEaT** [comment]
Okay, wait a bit to complete the translate :D

**Comment by rErEaT** [comment]
done!

[messages_hu.zip](https://github.com/Xephi/AuthMeReloaded/files/220957/messages_hu.zip)

**Comment by ljacqu** [comment]
Fully valid file :) Thank you very much! It's on the repository now.
