### ISSUE TITLE
ProtocolLib and Authme

### ISSUE THREAD

**Issue by dustin1525** [Xephi/AuthMeReloaded#649]
According to the ProtocolLib developers when Authme and ProtocolLib are in the same server, some things break and don't work. And sadly NO console errors are given.

Example:

Jimmy joins the server,
Bob joins the server,
Richard joins the server,

Jimmy can see Bob, but Bob can't see Jimmy.
Richard can see no one, but Bob AND Jimmy can see Richard.

**Comment by games647** [comment]
Which build do you use? Can you try it with hideTablist on false? Which other plugins do you use?

**Comment by ljacqu** [comment]
The corresponding issue on the ProtocolLib repo—https://github.com/dmulloy2/ProtocolLib/issues/181

**Comment by games647** [comment]
It could be fixed with the changes I made.

**Comment by sgdc3** [comment]
@dustin1525 Could you try our latest dev build please? ;)
http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by dustin1525** [comment]
Okay I'll try it and respond back with answers.. Thank you for you timely assistance!

**Comment by RAZERMC** [comment]
happens to our server to fixed mine with creating a spawn world then when player enter main world they can see each other again
