### ISSUE TITLE
[Dev] Un-/restricted names: improve documentation

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#652]
- Create a page about how unrestricted and restricted users are handled
- Improve the description of the according properties in the config file, as I don't think they are very clear

**Comment by ljacqu** [comment]
Hi @Gnat008, could I ask you to take a quick look? In the end there wasn't much more to add besides a minor update to the config comments and elaborating on those comments a little.
https://github.com/AuthMe/AuthMeReloaded/wiki/Name-Restrictions

**Comment by Gnat008** [comment]
Er I never got any email or notification for this. Thanks GitHub...?

**Comment by Gnat008** [comment]
If it helps, it all looks good!
