### ISSUE TITLE
Empty chat message on player join

### ISSUE THREAD

**Issue by ravkr** [Xephi/AuthMeReloaded#654]
If we set `valid_session: ""` in messages_xx.yml then AuthMe is sending empty message to player.
![zrzut ekranu z 2016-04-13 22 38 44](https://cloud.githubusercontent.com/assets/3875202/14508685/fbd407c6-01c8-11e6-88d1-c554290a6cf8.png)

It would be nice if AuthMe wouldn't send it if it is empty.
This is probably the case also with other strings in AuthMe but I haven't checked it.

**Comment by ljacqu** [comment]
This is a nice suggestion.

From a technical point of view it's not difficult to check if messages are empty, but this will clutter the entire code. We sometimes use the `Messages` class to retrieve and send a message; there a check can easily be implemented. However, sometimes we retrieve texts via `Messages` and then use it externally (applying replacements, sending them line by line to the user).

If we want to allow empty messages to be skippable we need to use (and create) methods in `Messages` as much as possible. Checking for empty messages outside of `Messages` is not a long-term option.

**Comment by sgdc3** [comment]
i think we only need to return null from the config

**Comment by ljacqu** [comment]
That's not possible because `null` is when the file does not have the message key, in which case we fall back to the JAR's messages_en.yml.

**Comment by sgdc3** [comment]
No, i mean, if we use sendMessage(null) no string is printed. We only need to return null from the message class if the string is empty.

**Comment by ljacqu** [comment]
Oh, now I understand! :smile:

**Comment by sgdc3** [comment]
@ravkr Could you try with latest build? ;)

**Comment by ravkr** [comment]
@sgdc3 everything is fine now :D 
![zrzut ekranu z 2016-04-16 12 59 10](https://cloud.githubusercontent.com/assets/3875202/14580614/0c58882c-03d3-11e6-9ca2-3c46ed0263fd.png)
