### ISSUE TITLE
Quit location not saved

### ISSUE THREAD

**Issue by astr1al** [Xephi/AuthMeReloaded#657]
For the last few versions of AuthMe I've tested, I am unable to get it to save players quit locations. I am even on build #935
Here are a few of my config settings. I also use Multiverse-Core and Essentials
        ForceSpawnLocOnJoinEnabled: false
        SaveQuitLocation: true
        teleportUnAuthedToSpawn: true
        spawnPriority: authme,essentials,multiverse,default

**Comment by sgdc3** [comment]
what happens if you set noTeleport to true? just to find out if it's authme's fault ;)

**Comment by sgdc3** [comment]
@astr1al

**Comment by astr1al** [comment]
@sgdc3 set noTeleport to true and the player spawns in their proper quit location.

**Comment by ljacqu** [comment]
@astr1al, may I ask you to check with build n. 1120 or above? Cannot (or maybe: can no longer) reproduce. 
(cc #750)

**Comment by ljacqu** [comment]
Closing as #750 was tested & verified.
