### ISSUE TITLE
Update permission nodes on Bukkit page

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#671]
http://dev.bukkit.org/bukkit-plugins/authme-reloaded/pages/permissions/ lists old permission nodes (reported via #611)

Please update with up-to-date nodes. https://github.com/AuthMe-Team/AuthMeReloaded/blob/master/docs/permission_nodes.md

**Comment by rErEaT** [comment]
Passpartu Command is not working :/

**Comment by ljacqu** [comment]
It's been removed many months ago.

**Comment by rErEaT** [comment]
oh, and is there anyway to login with any accounts?

**Comment by sgdc3** [comment]
Done!

**Comment by sgdc3** [comment]
You can use the forcelogin feature to archive what you want ;)

**Comment by ljacqu** [comment]
Excellent, thank you @sgdc3!
