### ISSUE TITLE
Kicked all players

### ISSUE THREAD

**Issue by FunnyCraft** [Xephi/AuthMeReloaded#673]
http://pastebin.com/F6HX8X94

**Comment by FunnyCraft** [comment]
[15:16:49] [Netty Server IO #2/WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.nio.channels.ClosedChannelException

**Comment by ljacqu** [comment]
Can't reproduce. Try to update to the latest build maybe: http://ci.xephi.fr/job/AuthMeReloaded/

If it still persists, kindly provide a description of when it happens, what server you're running on, etc.

**Comment by FunnyCraft** [comment]
Even when I set up an authorization server, and removed Authme with server-based, some players betrayed
 23.04 02:15:58 [Server] WARN BreakingAS moved too quickly! 2439.9753933211946,19.0, -966.0875048841941
23.04 02:15:58 [Server] WARN BreakingAS moved too quickly! 2439.9753933211946,19.0, -966.0875048841941
23.04 02:15:58 [Server] WARN BreakingAS moved too quickly! 2439.9753933211946,19.0, -966.0875048841941

**Comment by sgdc3** [comment]
in your config you need to enable the disableCollisions feature

**Comment by sgdc3** [comment]
whoops, this setting doesn't exist, my bad memory xD

**Comment by sgdc3** [comment]
You really need to update to latest dev build

**Comment by sgdc3** [comment]
If this doesn't fix the issue try to update your spigot version

**Comment by FunnyCraft** [comment]
latest dev build 957?

**Comment by sgdc3** [comment]
yeah

**Comment by FunnyCraft** [comment]
Made a separate authorization server, logged in and can not go, help.

**Comment by sgdc3** [comment]
could you posy your config please?

**Comment by FunnyCraft** [comment]
With Authme all right without it can not move from your account.
And writes moved too quickly ...

**Comment by sgdc3** [comment]
could you post your config?

**Comment by sgdc3** [comment]
and your plugin list please

**Comment by FunnyCraft** [comment]
http://rghost.ru/private/6TzJvW4Vr/0643f63cff901fea915f542c0cb0e1d7

**Comment by FunnyCraft** [comment]
.04 12:38:46 [Server] INFO Plugins (62): JoinCommands, FunnyCasino, ChatGame, EliteWeapons, CheatItemWatchDog, DynPad, FunnyCr, TickOptimizer, RandomPlacer, FunnyCase, NoteBlockAPI, PotionFix, RedstonePower, FunnyCraft, HideStream, UralChat, WorldEdit, HealthBar, SimpleElevator, Essentials, ClearLag, SwornGuns, AutoMessage, Chairs, WorldBorder, SunCraftHeads, Multiverse-Core, FunnyContracts, MRPvPMoney, PermissionsEx, SuperSpleef, Funnydone, MineResetLite, CustomJoinItems, TopStatistics, Vault, UralClans, ProtocolSupport, DrugMeUp, DrinksCMD, Scavenger, Marriage, WorldGuard, ChestCommands, McMusic, EssentialsSpawn, ChatManager, ShopGUIPlus, TitleManager, BowSpleef, mwParkour2, Jobs, LimitedWorldEdit, ProtocolLib, NoCheatPlus, PayDay, ColoredTags, WGLW, AuthMe, Passport, ScoreboardStats, ShoppingCartReloaded

**Comment by sgdc3** [comment]
could you try without protocolsupport? just to exclude a cause

**Comment by FunnyCraft** [comment]
The result is the same.

**Comment by ljacqu** [comment]
@FunnyCraft This is hard without any of us being able to reproduce it. You have a big list of plugins. Maybe in the days that have gone by you have a hunch which plugin is incompatible?

**Comment by ljacqu** [comment]
@FunnyCraft Any news about this from your side?
