### ISSUE TITLE
On kick caused by wrong password the logout position is overwritten

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#677]
http://dev.bukkit.org/bukkit-plugins/authme-reloaded/#c6599

**Comment by ljacqu** [comment]
> hi so i found a bug when i have teleportUnAuthedToSpawn: true and i found for ex a mine and i wanna be there when i come back and i get my password wrong and it kicks me when i come back and use the correct password it will save were i left (i mean in the spawn) can you fix that please?

**Comment by sgdc3** [comment]
Thank you, i was outside when i i've opened the issue ;)

**Comment by ljacqu** [comment]
Verified that this is fixed, so closing.
