### ISSUE TITLE
An official bungeecord module.

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#68]

**Comment by Xephi** [comment]
In developpement :) 
https://github.com/Xephi/AuthMeBridge

**Comment by sgdc3** [comment]
@Xephi Read my issue in the new project

**Comment by sgdc3** [comment]
Bump

**Comment by sgdc3** [comment]
Bump!!!!

**Comment by Xephi** [comment]
Done
https://github.com/Xephi/AuthMeBungeeBridge/commit/f5f5d5b88f166b34f55bdf5d79e5c9fcc609f18b
