### ISSUE TITLE
Warn if ProtocolLib is outdated

### ISSUE THREAD

**Issue by ArcasCZ** [Xephi/AuthMeReloaded#680]
Using KCauldron #201, ProtocolLib 3.4.1, AuthMe latest build.

http://pastebin.com/Kk0VMgcH

**Comment by games647** [comment]
Disable hideTablist for now.

**Comment by games647** [comment]
It says you have an outdated ProtocolLib version.

**Comment by ArcasCZ** [comment]
I know. So is possible to add some kind of check, which will warn and disable this function? Or better - find some workaround?

**Comment by games647** [comment]
I will add a warning

**Comment by ArcasCZ** [comment]
Is possible to make it work at lower version of PL?

**Comment by games647** [comment]
Why don't you want to update. Protocollib works also for older minecraft versions

**Comment by ArcasCZ** [comment]
One word - KCauldron :-)

**Comment by games647** [comment]
>One word - KCauldron :-)

As I already said: 
>Protocollib works also for older minecraft versions

So also for Cauldron.

**Comment by ArcasCZ** [comment]
http://pastebin.com/deFfpVSS

ProtocolLib version: 3.7.0-BETA

**Comment by games647** [comment]
Why don't you use the latest build...

**Comment by games647** [comment]
That's a real error we can work with. The protocol changed.

**Comment by ArcasCZ** [comment]
'cause it's incompatibile with KCauldron. Believe or not, KCauldron brokes lot of things.

**Comment by games647** [comment]
Now it's not a protocollib error. The implementation of the tablist hider is just not compatible with minecraft versions below 1.8. I'll add a warning until I find a way to fix it.

**Comment by games647** [comment]
They changed really a lot, so I just added a warning and disable the feature then.
