### ISSUE TITLE
How to hide coordinates when player is login?

### ISSUE THREAD

**Issue by CrazyPHP** [Xephi/AuthMeReloaded#682]
Hello.
The option "teleportUnAuthedToSpawn" is not work good, honestly it is absolutely useless!

When player (griefer) try to login (using name of other players) he can see the coordinates of the victim for 1-2 seconds before he teleported to spawn. 

How to fully hide coordinates from griefers?

**Comment by sgdc3** [comment]
The only way is to spawn the player directly in the login spawn instead of teleporting him, we need to recode the entire spawn mechanics.

**Comment by CrazyPHP** [comment]
i resolve this issues with this code:

`
@EventHandler
    public void onSpawn(PlayerSpawnLocationEvent event) {
		SpawnStorage spawnStoreage = new SpawnStorage((IEssentials)Bukkit.getServer().getPluginManager().getPlugin("Essentials"));
        event.setSpawnLocation(spawnStoreage.getSpawn(null));
    }
`

**Comment by Xephi** [comment]
https://github.com/AuthMe-Team/AuthMeReloaded/commit/121dd7e6fb1a662a479147e31f57f00d460e8ed7

Can you please confirm it's fixed ?

**Comment by ljacqu** [comment]
Changes in above commit have been undone—2edcb703c11ecd5fd9a31aba15f507322d76a456

So this needs to be looked at again.

**Comment by ljacqu** [comment]
Hi @CrazyPHP, we got a similar report at #855, which has been verified successfully by the reporter. Could we ask you to check as well? http://ci.xephi.fr/job/AuthMeReloaded/ Build nr. 1263 or above. Thanks

**Comment by ljacqu** [comment]
The last comment in this thread from five years(!) ago answers that question. If you're having problems kindly create a new issue
