### ISSUE TITLE
Fix PBKDF2

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#685]
The CryptPBKDF2 hash has an issue and doesn't work. Fix it and unignore the test class. 

Check if we have a test for each hash algorithm

**Comment by ljacqu** [comment]
**Would anyone use this?** Please comment here if you are interested in this hash algorithm. 

Otherwise we should just delete it instead of fixing an unused feature.

**Comment by sgdc3** [comment]
We should disable this until 5.3

**Comment by ljacqu** [comment]
Just realized this is the standard PBKDF2 algorithm (the naming "CryptPBKDF2" threw me off).
This needs to be fixed—not removed.
