### ISSUE TITLE
Player randomly has to /login again

### ISSUE THREAD

**Issue by astr1al** [Xephi/AuthMeReloaded#688]
There is no console output, no errors, but every 15 - 30 minutes players have to /login again. It does't say "Sucessfuly logged out!" before or anything. I'm running build #971, but this has been an issue the last few versions. Can't recall exactly which version it picked up on. 

I use MySQL, and have been using the same settings for a few years, this has only become a recent issue.

**Comment by ljacqu** [comment]
Duplicate, but we'd be thankful for any insight you have on the issue.

How does this "has to /login again" manifest itself? You said there's no message. Does it just suddenly go back to "deny everything from unlogged player," i.e. 1) teleport back to spawn, 2) deny movement, 3) deny chat, 4) deny non-Authme commands, and 5) deny block edits? (Depending on your settings)

**Comment by sgdc3** [comment]
#692 @ljacqu look at this duplicate: it happens on tp sometimes.

**Comment by astr1al** [comment]
Closing this ticket. Following duplicate issue on #419
