### ISSUE TITLE
Password security issues (continued)

### ISSUE THREAD

**Issue by Maxetto** [Xephi/AuthMeReloaded#69]
Reopening #51 , missing the lenght and unsafe password checks.

(From the registration class:)
if (password.length() < Settings.getPasswordMinLen || password.length() > Settings.passwordMaxLength) {
m.send(player, "pass_len");
return;
}
if (!Settings.unsafePasswords.isEmpty()) {
if (Settings.unsafePasswords.contains(password.toLowerCase())) {
m.send(player, "password_error");
return;
}
}

Plus, I hope you've taken in charge the "%p" placeholder to block the username of the player as password. It's really a must have, many people use the username as password.

**Comment by Xephi** [comment]
Ficed

**Comment by Maxetto** [comment]
Very much thanks. This is a great security improvement for both users and server admins! :D

However, I think it still missing the lenght check. I will check tomorrow.
