### ISSUE TITLE
Quit location not saved

### ISSUE THREAD

**Issue by ZeTioZ** [Xephi/AuthMeReloaded#690]
Since the build #965 (I've tested all of the version even the build #973) the players don't return where he had disconnected
ForceSpawnLocOnJoinEnabled: false
SaveQuitLocation: true
teleportUnAuthedToSpawn: true
spawnPriority: authme,essentials,multiverse,default

**Comment by ljacqu** [comment]
@ZeTioZ This should be fixed with recent development builds. :)

**Comment by ZeTioZ** [comment]
Yeah it's fixed thanks a lot ! :D

**Comment by ljacqu** [comment]
Thanks for the feedback!
