### ISSUE TITLE
Tp or Afk and Login

### ISSUE THREAD

**Issue by TheIntelloBox** [Xephi/AuthMeReloaded#692]
Hello,

Sometimes, my players must be login whereas they're playing and they were loginned ? 
The same issue when do a tp sometimes.

**Comment by sgdc3** [comment]
Duplicate of #688

**Comment by TheIntelloBox** [comment]
On 10 minutes, I must login 6 times !!!

**Comment by sgdc3** [comment]
Should have been fixed in the latest build, you can download it from our buildserver
