### ISSUE TITLE
Crash on purge

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#696]
http://dev.bukkit.org/bukkit-plugins/authme-reloaded/?comment=6620

**Comment by ljacqu** [comment]
> http://pastebin.com/Un3pbEtm b-988

**Comment by games647** [comment]
According to the crash it's hanging while loading all CraftOfflinePlayers through the Bukkit API. This operation. It doesn't look like this part of the API is thread-safe. So my idea is to split the purge into portions and running it sync, for example one account every tick.

**Comment by sgdc3** [comment]
@games647 yeah you're right ;)
