### ISSUE TITLE
Strange architecture

### ISSUE THREAD

**Issue by Zeluboba** [Xephi/AuthMeReloaded#70]
Hello, I'm a new user of authme (used it like 3 years ago last time), was looking source code for modifying my forum table to use it with authme and I wonder about few things, maybe you'll explain me why are they made this way:

[url=https://github.com/Xephi/AuthMeReloaded/blob/e8f342010ca02fb31c995c9b0eb9731ee6f724d9/src/main/java/fr/xephi/authme/datasource/MySQLThread.java#L121] MySQLThread.java:121 [/url]:
Why lastlogin can't be null? If I'm using it with my forum user can never login. Ok, after this, why world can be null if lastlogin can't? 

Best regards

**Comment by Xephi** [comment]
lastlogin is set to a default value, it's due to some problem with Session, but it do not interfers with any forum cause lastlogin use a timestamp in milliseconds, world can be null cause main world isn't called world as default

**Comment by Zeluboba** [comment]
Okay, thank you for explanation.
Can I use forum user id column or should I create separate one for authme?

**Comment by Xephi** [comment]
nop you can use forum id column, as it's an auto incremantation field

**Comment by Zeluboba** [comment]
Ok, thought so, but maybe you do some weird stuff with auto increment fields :) thank you for your answers!

**Comment by Xephi** [comment]
You're welcome ;)
