### ISSUE TITLE
2 login/register messages on join

### ISSUE THREAD

**Issue by TheIntelloBox** [Xephi/AuthMeReloaded#700]
Hello,

When I'm not op and when I go on server, I have 2 times : "Please login, /login password".

**Comment by sgdc3** [comment]
What's your buildnumber?

**Comment by TheIntelloBox** [comment]
998.

**Comment by sgdc3** [comment]
@ljacqu any idea?  I remember you worked on a similar issue some time ago.

**Comment by ljacqu** [comment]
@sgdc3 we have a task that messages the player "please /login" in a given interval. Maybe we also send this message to the player when he joins outside of this task

**Comment by TheIntelloBox** [comment]
I have the same issue with the /register.

**Comment by sgdc3** [comment]
@ljacqu Just checked, no message outside the task.

**Comment by sgdc3** [comment]
@TheIntelloBox Maybe your server is trying to make 
your players run a command on join. When someone tries to do something denied by our config we resend the login/register message.

**Comment by TheIntelloBox** [comment]
I use the auto login, so I think, this is the problem ?

**Comment by sgdc3** [comment]
What type of autologin? Sessions or a plugin such fastlogin or autoin?

**Comment by TheIntelloBox** [comment]
Sessions. ;)

**Comment by ljacqu** [comment]
I can confirm this bug, noticed it myself today while testing other things. Not using sessions.

**Comment by sgdc3** [comment]
Very strange, maybe we should delay the first message...

**Comment by sgdc3** [comment]
Does it work now? @TheIntelloBox @Xephi

**Comment by TheIntelloBox** [comment]
No. I tested it and had 2 messages 3 hours after.

**Comment by HollishKid** [comment]
Hello, 
I can confirm this bug.
Using sessions.
Moreover I get kicked sometimes, claiming my login delay has expired (whilst I session logged in).

It even sometimes asks me to relog, eventhough I have been playing for a while.

**Comment by TheIntelloBox** [comment]
Yes Hollish, I have the same bug.

**Comment by HollishKid** [comment]
Maybe for extra info:

**Comment by ljacqu** [comment]
Dang, thanks for the timing. Looks like our ProcessSyncPlayerLogin task is incredibly slow... I'm at a total loss as to why, though (teleportation? emitting an event?)

**Comment by games647** [comment]
@ljacqu 

Maybe the packets, the call player.saveData() or bungee message sending

**Comment by HollishKid** [comment]
What does this mean, is there anything I can / should do to prevent this ProcessSyncPlayerLogin from lagging?
It does not imply any teleportations, but does launch one or two events from another plugin (BetonQuest) which seems to have no problem handling them though ...

An what about the double messages?

**Comment by DNx5** [comment]
@HollishKid you take the timings sample too long. you could do 5-10 minutes timings for better result, as you could see another plugins you have seems "to weigh very heavily on server performances" like you said.

**Comment by sgdc3** [comment]
Seems fixed, i'll reopen if you are having still issues.

**Comment by ljacqu** [comment]
Just to note, if an unregistered player is OP, after registration he loses OP status. 
For me this is almost more a feature than a bug. I don't care enough about it to create an issue—if someone else does, however, then please feel free.

**Comment by DNx5** [comment]
@ljacqu It's a feature, just to avoid security problem.
