### ISSUE TITLE
When a player connects, he has got another name.

### ISSUE THREAD

**Issue by TheIntelloBox** [Xephi/AuthMeReloaded#701]
Hello,

When my friend logins, when we see his accounts, he has got my name...
Look at this.

http://zupimages.net/up/16/19/osw5.jpg

**Comment by ljacqu** [comment]
Does he have the permission `authme.admin.seeotheraccounts`? Note that a player with `authme.admin.*` gets it as well.

**Comment by TheIntelloBox** [comment]
He doesn't have this permission.

**Comment by WindofFreedom** [comment]
I can confirm that. If player have the permission "authme.admin.seeotheraccounts", he sees other accounts but with own nick, not the player who joined.

**Comment by TheIntelloBox** [comment]
Yes, you've right.

**Comment by ljacqu** [comment]
@TheIntelloBox @WindofFreedom Should be fixed; sorry for the long wait. If one of you could kindly verify that the bug is positively fixed we can close this issue.

**Comment by WindofFreedom** [comment]
@ljacqu thank you, i'm verify, bug is fixed! Please fix a bug with spawn location after relogged...
