### ISSUE TITLE
php registration sha256

### ISSUE THREAD

**Issue by tommyraudy** [Xephi/AuthMeReloaded#702]
hi im going to make a registration page on my website, can you share how to encrypt password in SHA256 (authme default) with php? im using this code but didnt work to login, its mean my encrypted password are not configured properly with authme SHA256

```
function Uniwur_string($size){
        $text = md5(uniqid(rand(), TRUE));
        RETURN substr($text, 0, $size);
    }
$pwd = somethingcalledfrommypasswordfield;
$salt = Uniwur_string(8);
$crypt = hash('SHA256', $pwd);
$result = '$SHA$'.$salt.'$'.$crypt.$salt;
```

i refer to this documentation in authme page but this is not php code

> The custom SHA256 hash is created like this(pseudo code):
> String salt = randomString(length:16);
> String encryptedPassword = "$SHA$" + salt + "$" + sha256(sha256(password) + salt);

**Comment by ljacqu** [comment]
Hi, you can find a functional php integration example at https://github.com/AuthMe-Team/AuthMeReloaded/tree/master/samples/website_integration

**Comment by tommyraudy** [comment]
thanks but the code you show to me is for check login and login (for already registered users)...right now i want to create a web registration, i mean people have to register ther ign and password thru my website...not by /register command in game

**Comment by ljacqu** [comment]
integration.php, check_hash() at the bottom shows how to hash the password. You correctly say that our sha256 does s`ha256(sha256(pass) . salt)` yet you do `sha256(pass)` in your php code

**Comment by tommyraudy** [comment]
oh okay, i try this first :+1:

**Comment by tommyraudy** [comment]
wait...ive correct the hash that you mention but, what method to create salt? ive tried generate random alphanumeric 16 character but when i try to login, it failed "wrong password"

**Comment by ljacqu** [comment]
16 random characters in the range 0-9a-f

**Comment by ljacqu** [comment]
You know, let's reopen this and I will provide a working example (for both login and registration), as we already have for bcrypt

As I'm not at home the next few days I have to ask you to be patient :)

**Comment by ljacqu** [comment]
I will do this tomorrow

**Comment by ljacqu** [comment]
Done, please see Sha256.php in samples/, especially the `hash($password)` function.

**Comment by tommyraudy** [comment]
thanks, your hash working perfectly

**Comment by ljacqu** [comment]
@tommyraudy, thanks for the feedback! Good luck with your webpage.
