### ISSUE TITLE
Fix 1.9.X support

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#703]

**Comment by games647** [comment]
Could you explain it more?

**Comment by sgdc3** [comment]
Sorry i sent the issue from mobile and it hasn't saved my comment edit.

**Comment by sgdc3** [comment]
Here we are: http://dev.bukkit.org/bukkit-plugins/authme-reloaded/?comment=6632

**Comment by sgdc3** [comment]
@games647

**Comment by games647** [comment]
The client is using 3.4

**Comment by sgdc3** [comment]
Sorry xD I missed it!
