### ISSUE TITLE
Implement better /authme reload support

### ISSUE THREAD

**Issue by tuanjr** [Xephi/AuthMeReloaded#704]
after change config and run /authme reload, plugin won't change.
try many times! 
AuthMe-5.2-SNAPSHOT-legacy-973.jar
Paperclip-1.9.2

**Comment by ljacqu** [comment]
Which configuration?

**Comment by tuanjr** [comment]
all configs, i mean  /authme reload wont effected directly to plugin, i must restart server when i change config file to take effected.

**Comment by ljacqu** [comment]
Yes, not all work currently; in the future there will be some improvements. But again, which config do you mean specifically? I can give you a more precise answer then

**Comment by ljacqu** [comment]
@tuanjr I'm hijacking your bug as a development story ;)

**Comment by tuanjr** [comment]
what is your mean?
btw, thank for support and fix bug, Authme reload team are the best!

**Comment by ljacqu** [comment]
@tuanjr It means I kind of changed your bug report into an improvement task... ;)

Build n. 1003 and upwards should be a lot better with reload support
http://ci.xephi.fr/job/AuthMeReloaded/

If any setting is still not working on reload, please let us know. I'm sure there are some things missing but now it's easy to add support for reload everywhere

**Comment by ljacqu** [comment]
Note to myself—Reloadable on EncryptionMethod doesn't make sense -> I will have to remove it once I'm back home
