### ISSUE TITLE
Problem with task

### ISSUE THREAD

**Issue by ArcasCZ** [Xephi/AuthMeReloaded#705]
http://pastebin.com/q0b6aK48

Using build 957 of AuthMe, KCauldron #200.

**Comment by ArcasCZ** [comment]
Updatet to latest build - http://pastebin.com/8b7sLQ1t

**Comment by sgdc3** [comment]
@ArcasCZ Should have been fixed ;)

**Comment by ljacqu** [comment]
Thanks for the updated stack trace :) Makes our life easier
@sgdc3 Regarding your commit text -> the player is not null, the NullPointerException is being thrown by some method by Bukkit. If player were null an AuthMe class would be on top of the stack ^^

**Comment by ArcasCZ** [comment]
I found where was problem. Plugin GUIRules wasn't able to detect if player is logged in (problem with events from AuthMe I think). So GUIRules opened Inventory and AuthMe ('cause player wasn't logged in) closed it. Then it fired InventoryCloseEvent and GUIRules reopened it - again. Fix was to check if player is logged by NewAPI.

**Comment by sgdc3** [comment]
Ok, reverted ;)
sorry @ljacqu @ArcasCZ
