### ISSUE TITLE
API improvement

### ISSUE THREAD

**Issue by ArcasCZ** [Xephi/AuthMeReloaded#706]
Why is there too hard way to check if player is logged? Can you add support for simple function isLogged(String name)?

**Comment by games647** [comment]
There is already NewApi.isAuthenticated(Player)

https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/api/NewAPI.java#L89

**Comment by ArcasCZ** [comment]
@games647 Thanks, I'll try :-)

**Comment by ArcasCZ** [comment]
Seems wokring.
