### ISSUE TITLE
Custom Messages

### ISSUE THREAD

**Issue by TheIntelloBox** [Xephi/AuthMeReloaded#709]
Hi,

Could you add custom messages for "The Server is running AuthmeReloaded Snapshot", or "Use the command /authme help to view help"...
I want to custom all the messages of Authme.

Thanks.

**Comment by Xephi** [comment]
Hi guy, we are not intented to let these messages fully customizable, they're actually only exist in part of inform players about authme commands

**Comment by TheIntelloBox** [comment]
Hi, why ?

**Comment by Xephi** [comment]
They'll be leave in english and hard coded as part of some "Copyright" and information for non-current language users :)

**Comment by TheIntelloBox** [comment]
Oh ok. :( And nothing for "Use the command /authme help to view help"... This isn't a copyright.
