### ISSUE TITLE
Speed Up Compilation

### ISSUE THREAD

**Issue by Xephi** [Xephi/AuthMeReloaded#71]
Idk why, but with that new pom, compilation took so much time to re-download each metadata from all repo \*_\*

**Comment by sgdc3** [comment]
Travis or Jenkins compilation?

**Comment by sgdc3** [comment]
It freezes at: Downloading: http://dev.escapecraft.com/maven/org/bukkit/bukkit/1.8-R0.1-SNAPSHOT/maven-metadata.xml

**Comment by sgdc3** [comment]
It tries to find bukkit on every repository.

**Comment by sgdc3** [comment]
Ok I find the problem, I will create a pull request soon.

**Comment by Xephi** [comment]
thanks for the pr ^^

**Comment by sgdc3** [comment]
Fixed? ;)

**Comment by sgdc3** [comment]
Still 6 minutes on travis. The problem is Travis doesn't have a storage as cache for maven files. I think the only way to speed up the compilation is to remove useless maven downloads from all the repositories.

**Comment by sgdc3** [comment]
In my latest pr I enabled travis cache ;)

**Comment by sgdc3** [comment]
Check PR n° #75
