### ISSUE TITLE
This is feature or bug? (Country blacklist)

### ISSUE THREAD

**Issue by tuanjr** [Xephi/AuthMeReloaded#711]
My english not good, so i will explain by example:
1. Player A from USA play longtime in server
2. Nextime, i block USA in blacklist country
3. Player A still can access
4. Player B from USA first time join server, and him can't access. (country block)
so, player A still can access is a bug or feature?

**Comment by ljacqu** [comment]
It's a feature, though likely one we should make configurable. What do you think, @sgdc3?

**Comment by Xephi** [comment]
Blacklist and Whitelist are intended to handle Bot attack problem
By the way, only player whose already register can join bypassing this system

If you want him to cannot connect on the server, simply ban him :p

**Comment by tuanjr** [comment]
OK. Thanks :D
