### ISSUE TITLE
Mistake in French translation of the 'Messages_fr.yml' file

### ISSUE THREAD

**Issue by Jeje2201** [Xephi/AuthMeReloaded#712]
There is 2 time the word "connection" in the file, but in French it's "connexion" :)

**Comment by Xephi** [comment]
Mouais les deux sont valides :( :')

**Comment by Jeje2201** [comment]
C'est ce que je me disais aussi :p Pourtant selon le wiki :+1:
"Graphie fautive de connexion, influencée par le verbe connecter et l’anglais connection."

**Comment by Xephi** [comment]
Okok, bah y a moyen de changer, c'est pas très important :p

**Comment by Jeje2201** [comment]
Oui, je l'ai fais, mais c'était au cas où pour qu'il soit changé de base quand pour les prochains administrateurs de serveur fr :p 
( je suis le gars qui t'as envoyé un mail il y a peu pour te féliciter du plugin :p )

**Comment by ljacqu** [comment]
@Jeje2201 @Xephi J'avais justement quelques changements pour les messages français, "connection" -> "connexion" étant parmi eux :) J'utilise donc l'opportunité pour télécharger mes changements et je serais content si vous pourriez y jeter un coup d'oeil ^^

**Comment by Jeje2201** [comment]
Tes corrections sont impeccables ! Je crois que je ne peux pas modifier ton fichier de traductions alors j'ajoute les idées là mais généralement en France on met un espace entre le dernier mot d'une phrase et le '!' ou '?' pour par exemple 'connecté!' -> 'connecté !'. Un autre ajout mineur met qui donne un peu plus de cense : '&a' au lieu de '&c' pour des messages de réussite, généralement le vert clair prête plus à une réussite et le rouge à un échec. Exemple de 2 changements : 
valid_session: '&cVous êtes authentifié' -> valid_session: '&aVous êtes authentifié'
login: '&cConnexion effectuée!' -> login: '&aConnexion effectuée !'

**Comment by ljacqu** [comment]
@Jeje2201 Génial, merci beaucoup. Comme ça on a toujours un espace avant les point d'exclamations :) Et super pour avoir fait ça par le site, avec ça j'ai juste dû entrer le lien, merci bien :)

**Comment by Twonox** [comment]
WTF @ljacqu & @Xephi sont français ?!

**Comment by sgdc3** [comment]
@ljacqu only speaks french, @Xephi is french ;)

**Comment by Twonox** [comment]
Wow I didn't expect that xD
So, can I do my reports in french to better explain the problems ?

**Comment by sgdc3** [comment]
@Twonox no pls xD Only if really needed

**Comment by Twonox** [comment]
x) okay okay, np

**Comment by Twonox** [comment]
But it's not very easy to write in english for me :/ x)

**Comment by sgdc3** [comment]
same for me :)

**Comment by Twonox** [comment]
Hmm not more that me, I think :p
What is your Country ?

**Comment by sgdc3** [comment]
Italy ;)

**Comment by ljacqu** [comment]
@Twonox I'm Swiss btw ;)

**Comment by Twonox** [comment]
Mais donc tu sais assez bien écrire/comprendre le français ?

**Comment by ljacqu** [comment]
Oui, j'ai grandi et j'habite en Suisse alémanique mais ma famille vient de la partie francophone ;)

**Comment by Twonox** [comment]
Bon, comme ça au moins je saurais faire un rapport en français si jamais ça devient trop compliqué de le faire en anglais xD

**Comment by Jeje2201** [comment]
Je pense que vous pouvez aller débatre en privé, ca spam mes mails votre tchat x)

English translation : I think you 2 can speak in private chat, it spam my mail x)

**Comment by Twonox** [comment]
Désolé ^^' mais on en a fini donc tkt pas xD
