### ISSUE TITLE
[Dev discussion] Save UUID for mixed or online mode servers

### ISSUE THREAD

**Issue by games647** [Xephi/AuthMeReloaded#713]
Since 1.8 owners of paid minecraft accounts can change their name. In offline mode the uuid is based on the case sensitive username. So if the users change their username they will lose their inventory, permissions and their AuthMe account. This might be irrelevant for servers which run completely in offline mode.

But what about mixed online mode and complete online mode? With plugins like AutoIn and FastLogin it's possible that owners of paid minecraft accounts will receive their mojang UUID (mixed online mode). It's also known that AuthMe is used on online mode servers too. This means those player who changed their username have to create a new account. Shouldn't the same users use the same account?

If we save the UUID, we could check for the UUID instead of the playername.

An alternative would be to keep it as-is. So those users have to create a new account although they get the same inventory, permissions, .... This means we have duplicate database entries for the same player.

**Comment by sgdc3** [comment]
-1 UUIDs are a mess, and useless in Offline mode servers.

**Comment by sgdc3** [comment]
It would complicate the project without any relevant advantage

**Comment by ljacqu** [comment]
We don't save much data with accounts (pretty much: password, email, last seen date/IP and last location). I'm not really sure how much someone will benefit from being able to keep their last location, considering that name changes ought not to happen too often. But maybe you had something in mind besides that?

**Comment by games647** [comment]
I thought that premium users should have the same account even after they changed their username.
->Same password (So they don't need to reregister every time on name change)
->Same forum account
->Same lastlogin location
->No duplicates

I agree with these arguments. They are the big cons of this change.
>complicate the project
>We save much data with accounts
>name changes ought not to happen too often.

**Comment by sgdc3** [comment]
@Xephi has to decide

**Comment by sgdc3** [comment]
In my opinion we should release a stable uuid free version of the plugin and then start working on a 1.9 only version in order to clean the project from complex compatibility hooks

**Comment by games647** [comment]
>start working on a 1.9 only version in order to clean the project from complex compatibility hooks

We would lose a lot of users then.

**Comment by sgdc3** [comment]
No i mean we should keep 2 branches, one pre 1.9 with only bugfixes and another 1.9+ with new cool features

**Comment by ljacqu** [comment]
If we refactor a little the "legacy" stuff won't be in the way too much
