### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Melowelei** [Xephi/AuthMeReloaded#715]
I have this error : 
ERROR 	[15:35:51] [Server thread/ERROR]: Cannot load plugins/AuthMe/config.yml
Caused by 	Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
ERROR 	[15:35:51] [Server thread/ERROR]: Error occurred while enabling AuthMe v3.4 (Is it up to date?)

I have AuthmeBridge AuthMeBridge for BungeeCord 1.5 and AuthMe v3.4

And in my BungeeCord i don't have error.
I need ur help .. can't play....

**Comment by sgdc3** [comment]
We are not supporting AuthMe 3.4 anymore, but the error seems to be caused by a malformed config file.
