### ISSUE TITLE
AuthMe 5.0 for 1.7.10

### ISSUE THREAD

**Issue by madtomic** [Xephi/AuthMeReloaded#72]
Hi,

Will there be a 1.7.10 release for the v5.0 build?

madtomic

**Comment by sgdc3** [comment]
It should also work on 1.7.10 servers. (SHOULD) ;)

**Comment by Xephi** [comment]
Fixed just now to support old version of bukkit

**Comment by Xephi** [comment]
https://github.com/Xephi/AuthMeReloaded/commit/4e75fb76d0cc8b971922c3ce206469df7a7d2567
