### ISSUE TITLE
Updated hungarian lang

### ISSUE THREAD

**Issue by rErEaT** [Xephi/AuthMeReloaded#720]
Add denied chat message #719

@foxi69/rErEaT

[messages_hu.zip](https://github.com/Xephi/AuthMeReloaded/files/278352/messages_hu.zip)

**Comment by sgdc3** [comment]
Done, thank you ;)

**Comment by rErEaT** [comment]
Oh sorry I found a little error in the lang :D

its my personal lang file for my server.
add this file please :)
[messages_hu.zip](https://github.com/Xephi/AuthMeReloaded/files/279682/messages_hu.zip)

sorry for this mistake :(

**Comment by sgdc3** [comment]
@rErEaT Done ;)

**Comment by rErEaT** [comment]
thanks :)

**Comment by rErEaT** [comment]
http://www119.zippyshare.com/v/qtjCW5Ll/file.html

I updated again the Hungarian lang file with the following strings: denied_command, same_ip_online :)

**Comment by rErEaT** [comment]
well, thanks for update:)

**Comment by sgdc3** [comment]
done ;)

**Comment by rErEaT** [comment]
[messages_hu.zip](https://github.com/Xephi/AuthMeReloaded/files/298573/messages_hu.zip)

Updated with "password_error_chars" string :)

**Comment by rErEaT** [comment]
[messages_hu.zip](https://github.com/Xephi/AuthMeReloaded/files/310947/messages_hu.zip)

updated with tempban_max_logins string :D

**Comment by ljacqu** [comment]
@rErEaT You're fast :)

**Comment by rErEaT** [comment]
thanks :D

**Comment by ljacqu** [comment]
I copied over all of the changes, looks like you did some spelling fixes to older messages as well. Thanks :)

**Comment by rErEaT** [comment]
yes I did :)

Thanks for update it :)
