### ISSUE TITLE
Players can write to the chat, no need to login!

### ISSUE THREAD

**Issue by rErEaT** [Xephi/AuthMeReloaded#722]
https://p1.picsto.re/z4D7i.png

everyone can see it!

latest build 1045

**Comment by sgdc3** [comment]
@rErEaT Should have been fixed ;)

**Comment by rErEaT** [comment]
Okay I check it :D

**Comment by rErEaT** [comment]
verified!

its fixed!
https://p1.picsto.re/px3iJ.pngq
