### ISSUE TITLE
Wrong name of Update

### ISSUE THREAD

**Issue by Jeje2201** [Xephi/AuthMeReloaded#726]
Mistake in the name of the update "CHanges 5.3 BETA 2" -> "Changes 5.2 BETA 2"
Screenshot : 
![erreur text](https://cloud.githubusercontent.com/assets/19387127/15538046/fe7e3682-2279-11e6-8660-e95238cde7ba.jpg)

**Comment by sgdc3** [comment]
Thank you ;)
