### ISSUE TITLE
Error Message in Console when players log on

### ISSUE THREAD

**Issue by Jeje2201** [Xephi/AuthMeReloaded#730]
I'm not sure it's because of your plugin because there is no 'authme' in the error, but there is no name of any plugin and your plugin trigger when players log on, so I share you the error ( the error happen randomly when players log on, not all time ) : 
```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_72]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_72]
	at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:46) [spigot-1.9.4.jar:git-Spigot-8a048fe-042911f]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot-1.9.4.jar:git-Spigot-8a048fe-042911f]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-8a048fe-042911f]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-8a048fe-042911f]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-8a048fe-042911f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:436) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-042911f]
	at net.minecraft.server.v1_9_R2.PacketPlayInTeleportAccept.a(SourceFile:31) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-042911f]
	at net.minecraft.server.v1_9_R2.PacketPlayInTeleportAccept.a(SourceFile:8) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-042911f]
	at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-042911f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_72]
	at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-042911f]
	... 5 more
```

**Comment by ljacqu** [comment]
Is there anything that suggest that this relates to AuthMe? As you say the stacktrace doesn't suggest that. Maybe you have more information about this now, or you've noticed a certain pattern when this occurs.

**Comment by Jeje2201** [comment]
Because it's when players logon, and your plugin is only for players who log on, but can be any other plugin yes. No I don't have more info about I waited your answer to know if you knew it was a bug of authme or no. I will try to move the plugin, log on many time with different account and check if it still happen without the plugin, I update this comment in 4h to answer

**Comment by ljacqu** [comment]
Thanks @Jeje2201, this is the first report we're getting so not sure if AuthMe is causing it. The server itself (and indeed, the stacktrace has a lot of `net.minecraft.server` going on) has to deal with an incoming connection; I wonder if some server implementation has some bug causing this, rather than a plugin.
In any case, looking forward to your update

**Comment by Jeje2201** [comment]
Hum... I really don't know, I changed many configs in authe / chat control / essentials / at the same time and look like the issue do not happen again, so I think you can change the labels of this issue as you want to, but the error is gone ( for now ) and if it's happen again, I don't think it will happen because of your plugin, Thanks ;)

**Comment by ljacqu** [comment]
Thanks for the update, @Jeje2201; I suggest we close it for now and if there are suspicions again that AuthMe is the cause please let us know and we'll have a closer look :)

**Comment by Jeje2201** [comment]
Hi, suspiscions again.. hehe.. Nothing happened with my real account and a crack version, I tried to login more than 10 time with the 2 account in different way with your plugin enable, no error, this morning I checked the console, it happened with other players, [here](http://prntscr.com/ba2ypq)

**Comment by ljacqu** [comment]
Interesting, thanks for the log. Not sure what we can do, but reopening for the moment.

**Comment by rErEaT** [comment]
I think you are using the SkinsRestorer.

Thats the source of problem but ignore this error if its really happen only with skinsrestorer

**Comment by ljacqu** [comment]
@games647 Do you know of any issue like this?

**Comment by games647** [comment]
@ljacqu 
It could be an async kick or teleport. I think it's an async teleport.

**Comment by Jeje2201** [comment]
Yes @rErEaT , I use SkinRestorer. It can be the cause of the problem right cause some players use skin and it show, for some other I set it, etc.. I can ask on the gituhb of skinrestorer if it because of his plugin.
@games647 I don't kick player to get this issue, only happen when they log in. How can I check if it's async ? Is this async teleport on your plugin too ? Or on other plugins ?

**Comment by games647** [comment]
@Jeje2201 Yes I think that's the cause. Try to remove that plugin and tell us if the problem still exists.

Dev explanation:
In Minecraft 1.9 teleport network packets contain a teleport id which the client can accept. This id has 0 as initial value and will increased on every teleport through the Bukkit API. 

--> First teleport, 1 - Second teleport 2....

SkinRestorer sends raw teleport packets without accessing the bukkit api. It uses always the teleport api 0. If it doesn't correspond with the server teleport id, it will be just ignored. But if it's the first teleport it won't be ignored because it's equal with the initial value of the teleport id. The server now wants to access the latest teleport data, but there was no teleport.

**Comment by Jeje2201** [comment]
You are all Gods ! :') Thanks @rErEaT for finding first the plugin who caused this error. Thanks @ljacq to bring here @games647 here and thanks @games647 for giving me an really extremly complait explenation ! You are all awesome, I will move this error to the other github of skinrestorer, thanks you all <3 I removed the plugin, no more error, with 20 different player with 20 different account, real, crack, etc.. No error message. Thanks !

**Comment by rErEaT** [comment]
wont fixed this error in skinsrestorer btw

https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/issues/24

**Comment by Jeje2201** [comment]
Wow, this is exactly what I was looking for, we can close this issue, I wil move on the new one you sent me, thanks @rErEaT, @ljacq  and @games647

**Comment by Jeje2201** [comment]
Issue here close. Thanks all.

**Comment by sgdc3** [comment]
Thank you ;)
