### ISSUE TITLE
Problems with sessions when use authme on multiple Lobbys (hubs)

### ISSUE THREAD

**Issue by tuanjr** [Xephi/AuthMeReloaded#731]
What steps will reproduce the problem?
1. Network has a lobby, with Authme installed, session enable: false. Everything work fine
2.  copy this lobby to new, so network has 2 lobby to get rondom player to lobbys
3. Now i enter network, bungeecord send me in to random lobby, i'm login /login, and enter server to player.
4. After play, i'm quit minecraft, go to bed
5. Some one enter network with my name, so authme won't ask (require) /login

Today, ~10 players in my network be hacked account by this way. So how to fix this issues? or this issues by Authme?

**Comment by sgdc3** [comment]
Could you post your authme config + your spigot.yml + your bungeecord config(remove any ip, just keep the options section) please? ;)

**Comment by sgdc3** [comment]
P.S: what's your authme build/version?

**Comment by tuanjr** [comment]
This is bungeecord config: http://paste.ubuntu.com/16816331/
This is spigot.yml http://paste.ubuntu.com/16816384/
This ir Authme config:  http://paste.ubuntu.com/16816480/
Authme versions: same issues on "AuthMe-5.2-SNAPSHOT-legacy-build1004.jar" and "AuthMe-5.2-SNAPSHOT-legacy-1053.jar"

**Comment by sgdc3** [comment]
@tuanjr Everything seems ok, let me check the code again...

**Comment by tuanjr** [comment]
I'm just test again, so i will explain more:
example network
|
|- hub 1 (authme installed)
|-hub 2 (authme installed)
|-factions 1
|-factions 2

1. player join network, bungee send player to hub 1 (or hub 2), player /login
2. player quit network
3. player join again, if bungeecord send player to hub 1 (or hub 2), so player must /login again, but if bungeecord send player to hub 2 (or hub 1), /authme wont work, won't ask player /login, and more thing, player can walk, just jump  to move (space)

**Comment by sgdc3** [comment]
@tuanjr "should" have been fixed

**Comment by sgdc3** [comment]
@ljacqu we have too may login/logout paths (via session, via command, by quit event, etc....) we need to have a common join/login/logout/quit/session process

**Comment by sgdc3** [comment]
@DNx5 @games647 @gnat008 @timvisee @Xephi

**Comment by timvisee** [comment]
Wow, the hacks should are falling quickly too! 

@sgdc3 I might take a look into this, if someone hasn't before when I'm starting. I'm talking about the common authentication interface by the way.

**Comment by sgdc3** [comment]
Yeah that should allow us to fix tons of issues

**Comment by tuanjr** [comment]
@sgdc3 i will try new build and report.

**Comment by sgdc3** [comment]
Probably this doesn't fix the issue

**Comment by ben1122a** [comment]
Can you please fix this? My server has been rampaged because your plugin is not working correctly. We have had hackers shut down 3 of our servers and have had to spend many hours fixing all the damage while your plugin still has NOT fixed this issue in the latest build.....
