### ISSUE TITLE
Server crash!

### ISSUE THREAD

**Issue by rErEaT** [Xephi/AuthMeReloaded#732]
I found authme in the crash report. I dont know what does it mean.
I just hope you can help me to resolve this error!

http://pastebin.com/GfKwA7nA

http://pastebin.com/svVREN9C

I dont know what caused this crash, someone said authme so I report it here.

Plugins list:
Plugins (44): WorldEdit, SimpleTrading, TitleMotd, PlaceholderAPI, AnimatedNames, ChatControl, ActionHealth, ProtocolLib, NoCheatPlus, LibsDisguises, SkinsRestorer, getID, React, PermissionsEx, TreeAssist, Tab, Lottery, FAQ, Vault, LightAPI, ShopGUIPlus, Orebfuscator4, Essentials, SexyMotd, BattlePets, Jobs, PlotSquared, Multiverse-Core, DeluxeChat, TreasureChest, HeavySpleef, AncientGates, CraftBook, ServerSigns, EssentialsSpawn, GriefPrevention, CreativeControlByKubqoA, AuthMe, Paintball, MobArena, Holograms, ProtectionLib, FurnitureLib, DiceFurniture

I am using the 1057 build from Authme, tell me what u need more!

**Comment by sgdc3** [comment]
It seems to be caused by other plugins..

**Comment by sgdc3** [comment]
@ljacqu what do you think about this?

**Comment by rErEaT** [comment]
do you know what is that plugin?

**Comment by games647** [comment]
It's a sqlite driver issue

# Java VM: OpenJDK 64-Bit Server VM (25.91-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [sqlite-3.7.2-libsqlitejdbc.so+0x38c29]  sqlite3_reset+0x13

**Comment by sgdc3** [comment]
Lol GG markdown!

**Comment by rErEaT** [comment]
host error or server?

**Comment by sgdc3** [comment]
@rErEaT What's yout spigot version?

**Comment by rErEaT** [comment]
29.05 17:50:24 [Server] INFO This server is running CraftBukkit version git-Spigot-e000104-4cb3258 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)

**Comment by sgdc3** [comment]
@games647 Could it be caused by our "damn synchronous, go away!" commits? xD

**Comment by games647** [comment]
@sgdc3 SQLite claims a file lock. So SQLite should be thread-safe. I'd rather think that there is a bug in the driver.

**Comment by sgdc3** [comment]
@rErEaT Not our fault, sorry, try to update your server version.

**Comment by rErEaT** [comment]
so the error is maybe in the spigot version?

**Comment by sgdc3** [comment]
Yeah

**Comment by cyberpwnn** [comment]
# JRE version: **OpenJDK** Runtime Environment (8.0_91-b14) (build 1.8.0_91-b14)

**Comment by sgdc3** [comment]
@rErEaT

**Comment by rErEaT** [comment]
okay, I will ask my host.

@sgdc3 can we speak at skype? :D

**Comment by sgdc3** [comment]
I'm a little busy atm, i'll bee available this weekend ;) @rErEaT

**Comment by rErEaT** [comment]
Okay thanks a lot, hope we can speak a bit there :D
