### ISSUE TITLE
Unlogged player can't throw snowballs but loses the item

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#733]
In the entity listener there is a method that is supposed to deny the throwing of snowballs (and similar). If a player who is not logged in tries to throw a snowball it will not be thrown, but the item will be taken from his inventory anyway.

This is a continuation of #568 (created a new issue because part of it was solved + there was a long comment thread)

**Comment by Platinteufel** [comment]
Can't confirm at all. Seems like you're loosing them if you interact with a block, but you will get them back after login or throwing in the air.
Proof: https://youtu.be/wA6iEW4Rec4

**Comment by ljacqu** [comment]
I can reproduce this on Spigot 1.8.8. Snowballs disappear. Logging in, restarting the server, etc. does not restore the missing snowballs. They are gone.

Reopening and assigning to me to check if it can be reproduced on a more recent version, too.

**Comment by Xephi** [comment]
Idk why, but the InteractEvent should be thrown before the ProjectileLaunchEvent, by the way, if we cancel the InteractEvent just before, this event hasn't to be fired, something is wrong in the event handling also ? :O

**Comment by Twonox** [comment]
I don't have this problem in my 1.7.10 server.
So, if `protectInventoryBeforeLogin` is set to `true`, no need to worry about this :p
