### ISSUE TITLE
AsyncPreLoginEvent fired even for wrong credentials

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#734]
The AuthMeAsyncPreLoginEvent is fired even when a user does a `/login` with invalid password, but the Javadoc claims that we only emit the event when correct credentials have been supplied.

Either the event needs to be fixed that it is only emitted upon receiving correct credentials (better), or the Javadocs need to be adapted (less good).

**Comment by sgdc3** [comment]
I think it should run before the auth check, this is the right purpose of the event and of it's canLogin attribute

**Comment by sgdc3** [comment]
@ljacqu

**Comment by ljacqu** [comment]
The thing is it's a little odd if I can listen to the event and set  `canLogin(true)`  and then the user still cannot log in (because wrong password). But you're right, it's a `PreLoginEvent`, so for me this is fine. After all, t's been like this for ages and no one has brought it up.
Thanks for fixing the Javadoc!
