### ISSUE TITLE
Inventory loss 

### ISSUE THREAD

**Issue by Xogren17** [Xephi/AuthMeReloaded#735]
Hello such,
I have a server and e tinido several faults with normal people plugin mind automatically deletes them plugin anyone knows how to find the fault? my sv is 1. 9 and have the plugin to the 1. 8 is not whether that influence it in something
In spanish:
Hola que tal,
tengo un servidor y e tinido varios fallos con el plugin normal mente a las personas les borra automáticamente el plugin alguien sabe como dar con el fallo? mi sv es de la 1.9 y tengo el plugin para la 1.8 no si se eso influirla en algo

**Comment by DNx5** [comment]
what is your Authme version?

**Comment by Xogren17** [comment]
5.0-beta3

**Comment by DNx5** [comment]
update it,
http://ci.xephi.fr/job/AuthMeReloaded/1069/artifact/target/AuthMe-5.2-SNAPSHOT-spigot.jar

**Comment by Xogren17** [comment]
Thank you and if you keep going the mistake you could do in that case?

**Comment by DNx5** [comment]
people should stop using 5.0
@sgdc3

**Comment by sgdc3** [comment]
@DNx5 They download it from the spigot page, only @Xephi owns it.
