### ISSUE TITLE
Javadocs generation down

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#737]
http://ci.xephi.fr/job/AuthMeReloaded/javadoc/ doesn't seem to work. @sgdc3 Could I ask you to look into it? I haven't found any probable cause

**Comment by ljacqu** [comment]
It's something with the main page; all the subpages it displays in frames are fine, e.g. http://ci.xephi.fr/job/AuthMeReloaded/javadoc/fr/xephi/authme/api/NewAPI.html

**Comment by DNx5** [comment]
looks like the frame is blocked by Chrome.

**Comment by sgdc3** [comment]
wtf? D:

**Comment by sgdc3** [comment]
Just security policies https://wiki.jenkins-ci.org/display/JENKINS/Configuring+Content+Security+Policy

**Comment by sgdc3** [comment]
Ok, doing some jenkins maintenance ;)

**Comment by sgdc3** [comment]
Here we are: http://ci.xephi.fr/job/AuthMeReloaded/javadoc/

**Comment by ljacqu** [comment]
problem remains, both on firefox and chrome

**Comment by sgdc3** [comment]
Just press ctrl + f5 xD

**Comment by ljacqu** [comment]
Is it working on your end? It's really not working on mine.
Just tried on mobile, same. And I never opened the page there before.

**Comment by sgdc3** [comment]
yeah, someone restarted jenkins and the change was reverted

**Comment by sgdc3** [comment]
we need to add a parameter to jenkins's starting arguments

**Comment by sgdc3** [comment]
Just sent an email to @Xephi ;)

**Comment by ljacqu** [comment]
Thanks @sgdc3! :smiley_cat:
