### ISSUE TITLE
i'm getting this error

### ISSUE THREAD

**Issue by SliderKP** [Xephi/AuthMeReloaded#738]
``` 
[Server] INFO Could not pass event ProjectileLaunchEvent to AuthMe v5.2-SNAPSHOT-b1074
01.06 07:15:27 [Server] INFO org.bukkit.event.EventException
01.06 07:15:27 [Server] INFO at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[?:?]
01.06 07:15:27 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [PerWorldPlugins.jar:?]
01.06 07:15:27 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callProjectileLaunchEvent(CraftEventFactory.java:754) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at net.minecraft.server.v1_8_R3.World.addEntity(World.java:1020) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at net.minecraft.server.v1_8_R3.World.addEntity(World.java:987) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at net.minecraft.server.v1_8_R3.EntityBlaze$PathfinderGoalBlazeFireball.e(SourceFile:236) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at net.minecraft.server.v1_8_R3.PathfinderGoalSelector.a(PathfinderGoalSelector.java:91) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at net.minecraft.server.v1_8_R3.EntityInsentient.doTick(EntityInsentient.java:473) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.m(EntityLiving.java:1626) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at net.minecraft.server.v1_8_R3.EntityInsentient.m(EntityInsentient.java:338) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at net.minecraft.server.v1_8_R3.EntityMonster.m(EntityMonster.java:20) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at net.minecraft.server.v1_8_R3.EntityBlaze.m(SourceFile:98) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1487) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at net.minecraft.server.v1_8_R3.EntityInsentient.t_(EntityInsentient.java:193) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at net.minecraft.server.v1_8_R3.EntityMonster.t_(EntityMonster.java:24) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [overcraft.jar:git-Spigot-db6de12-3f3c65f]
01.06 07:15:27 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
01.06 07:15:27 [Server] INFO Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R3.entity.CraftBlaze cannot be cast to org.bukkit.entity.Player
01.06 07:15:27 [Server] INFO at fr.xephi.authme.listener.AuthMeEntityListener.onProjectileLaunch(AuthMeEntityListener.java:116) ~[?:?]
01.06 07:15:27 [Server] INFO at sun.reflect.GeneratedMethodAccessor446.invoke(Unknown Source) ~[?:?]
01.06 07:15:27 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
01.06 07:15:27 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
01.06 07:15:27 [Server] INFO at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120) ~[?:?]
01.06 07:15:27 [Server] INFO ... 26 more
```

**Comment by ljacqu** [comment]
@SliderKP Thanks for the error report, this should be fixed from build nr. 1075 and upwards. http://ci.xephi.fr/job/AuthMeReloaded/ I look forward to your feedback.

@games647 Can I ask you to review the code change? I'm not entirely sure if this is OK with the bytecode, but I would assume so. Related to #568

**Comment by SliderKP** [comment]
another problem? i using build 1075

`01.06 08:50:02 [Server] INFO [AuthMe] Database has been purged correctly
01.06 08:50:02 [Server] INFO [AuthMe] AutoPurge Finished!
01.06 08:50:02 [Server] WARN java.net.ConnectException: Connection refused
01.06 08:50:02 [Server] WARN at java.net.PlainSocketImpl.socketConnect(Native Method)
01.06 08:50:02 [Server] WARN at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
01.06 08:50:02 [Server] WARN at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
01.06 08:50:02 [Server] WARN at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
01.06 08:50:02 [Server] WARN at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
01.06 08:50:02 [Server] WARN at java.net.Socket.connect(Socket.java:589)
01.06 08:50:02 [Server] WARN at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
01.06 08:50:02 [Server] WARN at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
01.06 08:50:02 [Server] WARN at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
01.06 08:50:02 [Server] WARN at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
01.06 08:50:02 [Server] WARN at sun.net.www.http.HttpClient.New(HttpClient.java:308)
01.06 08:50:02 [Server] WARN at sun.net.www.http.HttpClient.New(HttpClient.java:326)
01.06 08:50:02 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
01.06 08:50:02 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
01.06 08:50:02 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
01.06 08:50:02 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
01.06 08:50:02 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
01.06 08:50:02 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
01.06 08:50:02 [Server] WARN at a.q.run(q.java:1857)
01.06 08:50:02 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
01.06 08:50:02 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
01.06 08:50:02 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
01.06 08:50:02 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
01.06 08:50:02 [Server] WARN at java.lang.Thread.run(Thread.java:745)
01.06 08:50:02 [Server] WARN handleDisconnection() called twice`

thanks for reponse too quickly

**Comment by ljacqu** [comment]
Is this the full error? Did it happen once or does it keep happening? I think it's unrelated to this issue, and maybe even unrelated to AuthMe (hard to tell without a description)

**Comment by SliderKP** [comment]
when the server is opening maybe is not authme error, the old error is fixed, thanks

**Comment by games647** [comment]
It doesn't look like AuthMe:

>01.06 08:50:02 [Server] WARN at a.q.run(q.java:1857)

**Comment by ljacqu** [comment]
@games647 So bytecode is fine?

**Comment by games647** [comment]
Yes

**Comment by ljacqu** [comment]
Thanks
