### ISSUE TITLE
PermissionsManager clean up (various collection)

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#739]
Some points of improvement in the PermissionsManager:

- `onPluginEnable(PluginEnableEvent event)` and `onPluginDisable(PluginDisableEvent event)` really only make use of the plugin name -> could be changed to receiving a `String pluginName` instead. (Clearer to the reader that this really only depends on the name.) We already extract the name in the listener anyway that invokes those commands

- The `hasPermission` methods are a little confusing because there are many of them. Similarly to the previous point I would suggest to scrape the `hasPermission(CommandSender sender, CommandDescription command)` one and to pass only the permission node to it. This means `hasPermission(CommandSender sender, PermissionNode permissionNode)` needs to be null aware.

   * Unit tests before the refactoring would be useful here. I can write some.

- Is the `PermissionsManager.permsType` field necessary? Every `PermissionHandler` has the `getPermissionType` method which does the same thing.

- Method `reload` always returns `true` -> could be converted into void, since it has no meaning

- `setup()` is a huge method and of course needs some work, but this is really worth an issue of its own. Still might be possible to already gather ideas how this could be refactored. It's pretty cool that the permission system's service or API is passed to it by constructor (unit testing!), but at the same time it's a little unfortunate that the PermissionsManager has to know about all of those things.

- Whatever else gets your attention... :) 

@Gnat008 (sadly can't assign you)

**Comment by Gnat008** [comment]
If you could write the unit tests, that would be awesome, since I don't know how to do them yet.

**Comment by ljacqu** [comment]
I'm working on them, and you will have quite some work for the `hasPermission` point :) I had to `@Ignore` most of them
