### ISSUE TITLE
What's the difference

### ISSUE THREAD

**Issue by Kixot14** [Xephi/AuthMeReloaded#740]
What's the difference in this 3 type of builds ?? 
http://image.prntscr.com/image/0f313b2f335c4e60b2df4894b5298d74.png

**Comment by Kixot14** [comment]
If i have spigot, i need spigot, yeah ?

**Comment by Kixot14** [comment]
What mean that WARN ?? http://pastebin.com/LBVVk0Dr
i had it, when try to stop the server

AuthMe: build 1082 (snapshot-Spigot)
Spigot: build 847

**Comment by Kixot14** [comment]
With **AuthMe 5.2-BETA2-b969** no that warning

**Comment by DNx5** [comment]
https://github.com/AuthMe-Team/AuthMeReloaded/wiki/AuthMe-Releases-(Jenkins)

**Comment by DNx5** [comment]
about that warn, latest build fixed that.
