### ISSUE TITLE
Little issue with wrong message

### ISSUE THREAD

**Issue by Kixot14** [Xephi/AuthMeReloaded#743]
If you try to register, and wrote 2 same(matching) password with unsupported characters (Cyrillic, for example), it take the same messege as when passwords don't match. (From 'password_error' line)

But must be something like "password_character_unsupported: You try to use unsupported characters, please enter something another..." line.

AuthMe #1087

**Comment by ljacqu** [comment]
Ended up being a little more painful than anticipated :P But now done and available in build nr. 1091 and upwards :) http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by Kixot14** [comment]
works fine in build 1093. Thank!

**Comment by ljacqu** [comment]
Thanks for the feedback!
