### ISSUE TITLE
IP limit trouble

### ISSUE THREAD

**Issue by Kixot14** [Xephi/AuthMeReloaded#744]
Looks like **maxRegPerIp** (like a login limit) don't work on **AuthMe build #1087**. I set all this values to **1**, and easy registered and logged in 1-st, 2-nd, and 3-rd accounts (without OP and with only one **authme.player.*** permission).

_Spigot build #847_

**Comment by Kixot14** [comment]
**AuthMe 5.2-BETA2 [build #969]** contain the same trouble.

**Comment by Kixot14** [comment]
Lol, maybe it don't work, because i test this on local server ?? :/

**Comment by sgdc3** [comment]
Yeah localhost is the reason, it should work with normal IPs ;)

**Comment by ljacqu** [comment]
To elaborate, when you run the server on localhost and join the server on the same computer the IP address will be 127.0.0.1. We specifically exclude checks like IP limit for IP address 127.0.0.1.

**Comment by Kixot14** [comment]
Confirm. In AuthMe build 1093 all ok with Max reg/login per IP.

Only one little little inconvenience: placeholder **%reg_names** in message **max_reg** show player nicknames without Caps Lock.

**Comment by sgdc3** [comment]
That because authme is case insensitive, we can try to gwt the realname from the database, but i think this is enough.
