### ISSUE TITLE
login message when need solve captcha

### ISSUE THREAD

**Issue by Kixot14** [Xephi/AuthMeReloaded#745]
Can you remove spam from login msg at the time, when need enter the captcha ??

**Comment by ljacqu** [comment]
you mean the message "please /login" that is shown every x seconds? Unfortunately no

**Comment by sgdc3** [comment]
Yea we can ;)

**Comment by sgdc3** [comment]
We can add a method setMuted(boolean) in the task

**Comment by ljacqu** [comment]
Fine, but is it worth the trouble? It's kind of ugly to couple the captcha handling with the reminder task

**Comment by sgdc3** [comment]
In my opinion we should

**Comment by ljacqu** [comment]
I will see your commit... :)

**Comment by Twonox** [comment]
Good idea

**Comment by sgdc3** [comment]
lol fogot about this

**Comment by Kixot14** [comment]
Little offtop:
Guys, tell me please, why you work on this (AuthMe) project? and did you have any other projects, that you develope ?
You get paid for this ??

**Comment by sgdc3** [comment]
No we do this for free in our free time. ;)

**Comment by sgdc3** [comment]
Seems to work ;)
