### ISSUE TITLE
Banned users can join

### ISSUE THREAD

**Issue by SliderKP** [Xephi/AuthMeReloaded#753]
my banned users can change a letter to your name and enter again, I'm not sure it's a problem of Authme , but I found it more logical since they use the same password

for example
If the user is banned Carlos , if he join With the name "CarLOS" can login (with the password of the account "Carlos") and can play

please change the name of the publication I did not know what to put .

**Comment by Platinteufel** [comment]
cofig -> preventOtherCase: true

**Comment by sgdc3** [comment]
@Platinteufel Thank you ;)
