### ISSUE TITLE
is possible to make password like this?: ******

### ISSUE THREAD

**Issue by tuanjr** [Xephi/AuthMeReloaded#757]
Is possible or any solution to make password when player input  show like this?: ******
because many players in my country player in Coffe internet!

**Comment by sgdc3** [comment]
Impossible, the only way is a client side mod!

**Comment by tuanjr** [comment]
Thank T_T

**Comment by sgdc3** [comment]
wait, you mean  while typing or in the chat log?

**Comment by tuanjr** [comment]
yes, when player type /login xxxxxx to login

**Comment by sgdc3** [comment]
but in the chat box (where you can type with the keyboard) or in the chat log (where the chat is shown)?

**Comment by tuanjr** [comment]
i mean chatbox!
when you said chat log, you mean chat log in console?

**Comment by sgdc3** [comment]
no in the client

**Comment by sgdc3** [comment]
![cattura](https://cloud.githubusercontent.com/assets/8779252/15986537/43778368-300a-11e6-815d-9e3ac2d49057.PNG)

**Comment by tuanjr** [comment]
"or this?_"

**Comment by sgdc3** [comment]
I'm sorry but it's impossible :/
