### ISSUE TITLE
Important issue, user can login without password (AuthMe - 5.0-Dev)

### ISSUE THREAD

**Issue by i-rme** [Xephi/AuthMeReloaded#76]
I am using this version in a test server: http://dev.bukkit.org/bukkit-plugins/authme-reloaded/files/72-auth-me-5-0-dev/

The bug:
-Setup a offline-mode server with AuthMe - 5.0-Dev
-Log in with the player Test11 register the account with a password.
-While logged in with Test11 try to login with the name TEST11.
-The account TEST11 can sucesfull login without any password.

Test11 and TEST11 accounts are logged at the same time, TEST11 loged in without password.

FIX:
Kick any player with the same name that is already online (As in AuthMe stable does)
Kick any player that is the same as one registered but different case (mayus).

**Comment by sgdc3** [comment]
are you using mysql or sqlite?

**Comment by i-rme** [comment]
Sqlite

I just test it with a clean install.

Spigot on Windows

2015-06-24 21:03 GMT+02:00 Gabriele C. <notifications@github.com>:

**Comment by sgdc3** [comment]
We should try to build the project excluding latest commit...

**Comment by sgdc3** [comment]
Wait, where did you download the dev build? have you compiled it yourself?

**Comment by i-rme** [comment]
http://dev.bukkit.org/bukkit-plugins/authme-reloaded/files/72-auth-me-5-0-dev/


Can you replicate the issue?



2015-06-24 21:09 GMT+02:00 Gabriele C. <notifications@github.com>:

**Comment by Dimatert9** [comment]
And what? Thay cant hack your server. Because player test11 and TEST11 have different UUID.

**Comment by i-rme** [comment]
Yes, they can, some plugins asume that Notch and NoTCH are the same user.

2015-06-26 5:42 GMT+02:00 Dimatert9 <notifications@github.com>:

**Comment by sgdc3** [comment]
Try this version (latest dev build): http://xephi.fr:8080/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.0-SNAPSHOT.jar

**Comment by i-rme** [comment]
I tried that version and it still happens.

Can you reproduce the bug?

Its simple, start a spigot server (1.8.7, latest builds) on windows (offline mode, without any other plugin), login with Sgdc3 username for example, /register password password and then login with SGDC3 to the server.

The SGDC3 user can enter the server and chat without password,

**Comment by sgdc3** [comment]
@Xephi

**Comment by Xephi** [comment]
Due to change from PlayerLoginEvent to AsyncPlayerPreLoginEvent, will check it

**Comment by Xephi** [comment]
i have re-change it to PlayerLoginEvent for temporary time, while i'm checking why
http://ci.xephi.fr

**Comment by orkun1675** [comment]
Please keep using the AsyncPlayerPreLoginEvent, as the PlayerLoginEvent causes lag and freezes up the server during bot attacks.

To fix this player name case issue i am using this custom plugin that removes dublicat DAT files and forces a single case for usernames: https://github.com/Shevchik/DatDuplicateRemover
AuthMe can include the exact same code from this plugin to prevent case issues, the owner would be okay with it as I paid for it's development.

**Comment by Xephi** [comment]
Idk why, but when i set Result Event to KICK_OTHER on AsyncPlayerPreLoginEvent, the player login anyway

**Comment by prozhong** [comment]
maybe look at this https://github.com/Shevchik/DatDuplicateRemover

**Comment by i-rme** [comment]
Thanks, with **DatDuplicateRemover** this issue gets fixed and also the user is only allowed to login with one username case.

This sould be merged into AuthMe because it should be in every single offline-mode server.
This also helps the banning system, users used to change username case to evade the ban system based on uuid.

Thanks, :thumbsup::thumbsup::thumbsup::thumbsup:

**Comment by Xephi** [comment]
Iterate all .dat file at each login of players ... \#DecreasePerformancePlease

**Comment by prozhong** [comment]
didn't it create a cache ? I thought it only lag when loading that plugin

anyway its a solution?

**Comment by orkun1675** [comment]
yeah it caches it, no performance decrease

**Comment by iaxedu** [comment]
Authme really needs something that blocks any other case in a name after the first join yes. I'm using 6 lobby's and have to create a custom plugin unless Authme adds somethings. So the question is are you planning on adding something to fix this issue?

**Comment by Xephi** [comment]
sure, i will ^^

**Comment by Xephi** [comment]
Fixed https://github.com/Xephi/AuthMeReloaded/commit/4c2fad3643803fe2cdc74c9101f7e4644a5d686b
