### ISSUE TITLE
Encapsulate sessions

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#762]
Public field in AuthMe needs to be changed to something more appropriate (separate class?).

```
public final ConcurrentHashMap<String, BukkitTask> sessions = new ConcurrentHashMap<>();
```

See other "encapsulate" issues for longer description

**Comment by ljacqu** [comment]
Todo:
- sessions should be stored with expiry timestamp
- when reload disables session, they need to be cleared

**Comment by ljacqu** [comment]
@Gnat008 you created the SessionManager, can I ask you to take a quick look at my commits?

**Comment by Gnat008** [comment]
All looks good so far. Has any of this been tested in-game yet?

**Comment by ljacqu** [comment]
Yes, in particular I tested the session timeout and that /logout invalidates the session. That's about all there is to it, so if you don't have any remarks about the code it's fine to close :)
