### ISSUE TITLE
Remove PLAINTEXT encryption

### ISSUE THREAD

**Issue by xion87** [Xephi/AuthMeReloaded#767]
I see many founder of server that stole easy passworld of other players by using PLAINTEXT, please remove it, many use the same pass on all server and it only favourite griefers/thief.

**Comment by games647** [comment]
:+1:

**Comment by ljacqu** [comment]
Excellent point. We've removed support for plaintext "hash" 6 months ago (within AuthMe 5.2). 0688a86
Plaintext hashes wilö be automatically converted to our SHA256 hash.

**Comment by xion87** [comment]
oh i see, i didn't checked the beta version and was removed, nice :)

**Comment by ljacqu** [comment]
There for labeling as "question" and closing :) Thanks all the same
