### ISSUE TITLE
Update todo comments in messages file

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#772]
- run verify messages tool task
- commit result

-> If unclear how, I need to create a Wiki page

**Comment by sgdc3** [comment]
just remember me the task name xD

**Comment by ljacqu** [comment]
Oh sorry, sure thing, it's `verifyMessages`. When you start the tools all tasks are listed

**Comment by sgdc3** [comment]
Sorry, forgot about this :(
