### ISSUE TITLE
[Suggestion] ForceTeleportToServerSpawn

### ISSUE THREAD

**Issue by rErEaT** [Xephi/AuthMeReloaded#773]
I wanna teleport my players always to the server spawn when they join.
Would it be possible?

**Comment by sgdc3** [comment]
Sure! savequitlocation: false spawnLocOnJoin: true

**Comment by rErEaT** [comment]
but that works only the listed worlds right?

**Comment by ljacqu** [comment]
Not spawnLocOnJoin :) that's a global setting :)

**Comment by rErEaT** [comment]
ForceSpawnLocOnJoin: 
            # If enabled, every player will be teleported to the world spawnpoint
            # after successful authentication.
            # The quit location of the player will be overwritten.
            # This is different from "teleportUnAuthedToSpawn" that teleport player
            # back to his quit location after the authentication.
            enabled: true
            # WorldNames where we need to force the spawn location
            # Case-sensitive!
            worlds: 

do you mean this opinion?

**Comment by sgdc3** [comment]
Yeah

**Comment by rErEaT** [comment]
thanks :)

**Comment by sgdc3** [comment]
saveQuitLocation: save the player location into the database
teleportUnloggedToSpawn: when a player is unlogged it is teleported to the spawn, when he gets logged he is teleported to the location saved in the database, if the location is not set the player remains in the spawn.
spawnLocOnJoin: teleport the players at the spawn when he joins, the location in the database is ignored.

**Comment by rErEaT** [comment]
thanks a lot I hope I configured correctly :D

will investigate this :D
