### ISSUE TITLE
forceLogin via api seems broken

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#774]
AuthMeBridge's autoLogin feature isn't working, it relies on the forceLogin method.

**Comment by sgdc3** [comment]
AutoIn is broken too, now we are sure this is our fault.

**Comment by GotoFinal** [comment]
@ljacqu I provided more information on that dev thread and in PM to @sgdc3 on bukkit too, I wanted to help, but I was ignored after all, I provided everything that I found, and was waiting for any question but got only information that "tomorrow we'll investigate", so I'm waiting...
So please, don't lie ;)

http://dev.bukkit.org/bukkit-plugins/authme-reloaded/tickets/1005-problems-with-auto-in-last-player-location-problem/?
```
import org.bukkit.Bukkit;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.plugin.java.JavaPlugin;

import fr.xephi.authme.api.NewAPI;

@SuppressWarnings("ClassInitializerMayBeStatic")
public class Main extends JavaPlugin
{
    @Override
    public void onEnable()
    {
        Bukkit.getPluginManager().registerEvents(new Listener()
        {
            @EventHandler(priority = EventPriority.LOWEST, ignoreCancelled = true)
            public void onJoin(final PlayerJoinEvent evt)
            {
                System.out.println("PlayerJoinEvent event!");
                NewAPI.getInstance().forceLogin(evt.getPlayer());
            }
        }, this);
    }
}
```

**Comment by sgdc3** [comment]
@GotoFinal Sorry, we dropped the support on the bukkit issuetracker months ago

**Comment by sgdc3** [comment]
Maybe some bump? :/

**Comment by sgdc3** [comment]
API seems to work as intended now.
