### ISSUE TITLE
Message after /register (HideTabList 1.7.10 bug)

### ISSUE THREAD

**Issue by Twonox** [Xephi/AuthMeReloaded#775]
After registering, the success register message is not sent to the chat.

**Comment by sgdc3** [comment]
Sounds strange :/

**Comment by Platinteufel** [comment]
Invalid. Tested with Beta 3 and it works without any problems. Update AuthMe.

**Comment by Twonox** [comment]
Oh, I resolved the problem xD
I was supposed to set HideTablistBeforeLogin to false to debug the message. (because I use spigot 1.7.10)
You should indicate this by comment (the required version to use HideTablistBeforeLogin)

**Comment by sgdc3** [comment]
It should be automatically disabled in 1.7.10 :/

**Comment by sgdc3** [comment]
@games647

**Comment by games647** [comment]
@sgdc3 You don't need to send a extra message. You also receive a notification email once a member is assigned.

**Comment by sgdc3** [comment]
@games647 It depends by your notification settings i think, sorry anyway, i don't want to spam your inbox ;)

**Comment by games647** [comment]
@sgdc3 There is no need to say sorry.

**Comment by games647** [comment]
The hidetablist feature is automatically disabled for me. I tested it using Cauldron:
>[11:02:02 INFO]: [AuthMe] The hideTablist feature is not compatible with your minecraft version
[11:02:02 INFO]: [AuthMe] It requires 1.8+. Disabling the hideTablist feature...

**Comment by Twonox** [comment]
The problem is HideTabList feature... with FR messages, not with EN messages.
It's disabled but .... (http://hastebin.com/eputinikib.css)

When I register:
http://hastebin.com/sowoferaxu.avrasm
And I don't receive the registered message.

When I login:
http://hastebin.com/utojosasix.avrasm

**Comment by games647** [comment]
Okay source found.

**Comment by Twonox** [comment]
It's ok !
I receive the success message after registering and there is no error log :)
