### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Alibabaand40voleur** [Xephi/AuthMeReloaded#779]
Hi,

I setup an BDD for my BungeeServer, because he only need register.

But i have no table in my BDD, nothing created by Authme.*
Why ?

**Comment by Alibabaand40voleur** [comment]
Hi,

Database in english

Cordialy

**Comment by sgdc3** [comment]
Could you post your authme config please? ;)

**Comment by Alibabaand40voleur** [comment]
Hi,

How can i send it in PM ?

Cordialy

**Comment by sgdc3** [comment]
Just remove the passwords and the ips

**Comment by Alibabaand40voleur** [comment]
ips ?

**Comment by sgdc3** [comment]
IP addresses

**Comment by Alibabaand40voleur** [comment]
DataSource:
  mySQLColumnName: username
  mySQLTablename: authme
  mySQLUsername: 32***60*10***1334
  backend: file
  mySQLColumnLastLogin: lastlogin
  mySQLDatabase: a3*****6031*00**4102****33**
  mySQLPort: 3306
  mySQLColumnIp: ip
  mySQLHost: ************
  mySQLColumnPassword: password
  mySQLPassword: **********
  caching: true
  mySQLlastlocX: x
  mySQLlastlocY: y
  mySQLlastlocZ: z
  mySQLlastlocWorld: world
  mySQLColumnEmail: email
  mySQLColumnId: id
  mySQLColumnLogged: isLogged

**Comment by sgdc3** [comment]
backend: MYSQL
You are using an old unsupported version of the plugin, please consider to update.

**Comment by Alibabaand40voleur** [comment]
I updated for the last, but when i log in my server, i can't move can't use command, i can jump for moov.. soo, Why ?

**Comment by sgdc3** [comment]
http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT-spigot.jar Try this

**Comment by Alibabaand40voleur** [comment]
Is an 1.8.8 ?

**Comment by sgdc3** [comment]
It's the plugin for spigot 1.8+

**Comment by Alibabaand40voleur** [comment]
It work

**Comment by sgdc3** [comment]
Fine ;)
