### ISSUE TITLE
Make Threads works correctly

### ISSUE THREAD

**Issue by Xephi** [Xephi/AuthMeReloaded#78]
I need to rework custom Thread, it appears they actually stop and all request are executed in Main Thread, but overload the CPU is a pretty bad idea è_é

**Comment by Xephi** [comment]
I hope ! https://github.com/Xephi/AuthMeReloaded/commit/030e9b599e86b38073a2cdf73f58507df876ed7b

**Comment by Trojaner25** [comment]
Related to #34 ?

**Comment by Xephi** [comment]
Yes but not only :) I will make some other changes

**Comment by Xephi** [comment]
Fixed also
