### ISSUE TITLE
Please fix allowedNicknameCharacters: '[a-z0-9_]*' not worked for dev 18/6

### ISSUE THREAD

**Issue by vanthoi** [Xephi/AuthMeReloaded#780]
Please fix allowedNicknameCharacters: '[a-z0-9_]*' not worked for dev 18/6

I user config: only allow names without uppercase characters

I have use hello go to login ok!
But use hellOShe go to login still accept!

**Comment by sgdc3** [comment]
Fixed, but not still applied to latest build due to some other fixes that needs testing ;)

**Comment by vanthoi** [comment]
i runing Spigot 1.10 build 1h30m 19/6!
Thanks. I will update latest build !

**Comment by sgdc3** [comment]
@vanthoi Read, please, this isn't applied to latest builds! xD

**Comment by ljacqu** [comment]
FYI you're missing a "not" @sgdc3
> Fixed, but applied to latest build

**Comment by ljacqu** [comment]
@vanthoi The fix by sgdc3 is now present in build n. 1143 or above http://ci.xephi.fr/job/AuthMeReloaded/1143/

**Comment by vanthoi** [comment]
@ljacqu OK Good. It is fixed!
Thanks!

**Comment by ljacqu** [comment]
Thanks for the feedback, @vanthoi :)
