### ISSUE TITLE
Messages translated to FR

### ISSUE THREAD

**Issue by Twonox** [Xephi/AuthMeReloaded#781]
I've translated the remaining messages to French.

max_reg: '&cVous ne pouvez pas enregistrer plus de %max_acc compte(s). &o(Compte(s): %reg_names)'
tempban_max_logins: '&cVous êtes temporairement banni suite à plusieurs échecs de connexions !'
accounts_owned_self: '&fVous avez %count comptes:'
accounts_owned_other: '&fLe joueur %name a %count comptes:'

**Comment by sgdc3** [comment]
@Xephi could you check this? Thanks ;)

**Comment by Twonox** [comment]
Then?

**Comment by sgdc3** [comment]
@Twonox Doing it right now

**Comment by sgdc3** [comment]
# TODO denied_command: '&cIn order to use this command you must be authenticated!' is still missing

**Comment by Twonox** [comment]
denied_command: '&cVous devez être connecté pour pouvoir utiliser cette commande.'

**Comment by ljacqu** [comment]
Thank you for submitting these translations, @Twonox  :)
