### ISSUE TITLE
LimboCache issue on logout

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#782]
https://www.spigotmc.org/threads/authme-reloaded.62079/page-21#post-1667939

**Comment by ljacqu** [comment]
@sgdc3 Can you please paste the actual comment when you do this? For example now it leads me to the bottom of the page so no idea which comment is meant

**Comment by sgdc3** [comment]
Sorry, yeah, that's it! ;)

**Comment by sgdc3** [comment]
Was caused by the remove speed issue.
