### ISSUE TITLE
RemoveSpeed feature issue

### ISSUE THREAD

**Issue by Twonox** [Xephi/AuthMeReloaded#783]
This feature remove completly the speed of players when is set true. To can walk, it's necessary to do /speed 1 (with essentials) while RemoveSpeed is true.

**Comment by Platinteufel** [comment]
Weird. Are you running Beta 3? I'm able to walk again as soon as I'm logged in.

**Comment by Platinteufel** [comment]
#645

**Comment by sgdc3** [comment]
Fixed?

**Comment by sgdc3** [comment]
@Twonox

**Comment by Twonox** [comment]
Yes, it's ok ! :)
