### ISSUE TITLE
forceRegisterCommands won't work?

### ISSUE THREAD

**Issue by tuanjr** [Xephi/AuthMeReloaded#785]
So i want, after player /register, they run command /server. I'm config like this:

>     forceRegisterCommands: server

it won't work

>     forceRegisterCommands:
>     - server

still won't work
>     forceRegisterCommands: 
>     - 'server'

won't work

what is correct way to make player  run command after /register

**Comment by ljacqu** [comment]
```
    forceRegisterCommands:
    - 'msg %p Thanks for joining!'
```
Works fine for me. What's your /authme version?

**Comment by tuanjr** [comment]
AuthMe-5.2-SNAPSHOT-legacy-1130.jar
But i mean, i want force player run command, not system (console)

**Comment by ljacqu** [comment]
The above example does that :) You get the message twice because you're messaging yourself. I see how it's misleading.

**Comment by tuanjr** [comment]
Sorry, my fault, i'm fixed.
it can run direct command from chest command, not short alias. so instead of

> forceRegisterCommands: 
> - 'server'

now it work with:

> forceRegisterCommands: 
> - 'chestcommand open servermenu'

**Comment by ljacqu** [comment]
Thanks for the feedback, that's interesting. Is it an alias you set yourself in commands.yml?

**Comment by tuanjr** [comment]
yes, it is alias in command.yml

**Comment by ljacqu** [comment]
Thanks! Good for us to know it doesn't work.
