### ISSUE TITLE
Internal error on login

### ISSUE THREAD

**Issue by baaconmunncher** [Xephi/AuthMeReloaded#786]
When i write any AuthMe command i get "An internal error occurred while attempting to perform this command"

[LOG FROM CONSOLE]
http://pastebin.com/XHd6kESB

**Comment by ljacqu** [comment]
What permission system do you use? (If any at all)

**Comment by Twonox** [comment]
Do you have edited plugins.yml ?

**Comment by sgdc3** [comment]
caused by commands sent by fake players

**Comment by ljacqu** [comment]
@baaconmunncher Can you confirm @sgdc3's suspicion? Commands sent by fake players?

**Comment by sgdc3** [comment]
no if you look at the stacktrace you see that every command is handled by pwp (PerWorldPlugins). Could you paste your pwp config? @baaconmunncher

**Comment by baaconmunncher** [comment]
I found solution for this. In groupmanager group for vanilla world  I make a silly mistake. I didn't set default group soo everything mess up. Anyway thanks !
