### ISSUE TITLE
Duplicated max_reg message

### ISSUE THREAD

**Issue by Twonox** [Xephi/AuthMeReloaded#788]
max_reg: '&fLimite d''enregistrement atteinte pour ce compte' (OLD; line 15) 
max_reg: '&cVous ne pouvez pas enregistrer plus de %max_acc compte(s). &o(Compte(s): %reg_names)' (NEW; line 68)

**Comment by Twonox** [comment]
It's FR messages

**Comment by ljacqu** [comment]
Thanks for the hint! @Twonox
