### ISSUE TITLE
AutoIn not work

### ISSUE THREAD

**Issue by mat41997** [Xephi/AuthMeReloaded#789]

**Comment by sgdc3** [comment]
Invalid report, please provide more informations like your server verion, authme buildnumber (/authme version), autoin version, your configuration (posted on services like pastebin) and any error you get in console.

**Comment by mat41997** [comment]
timings
https://timings.aikar.co/v2/?id=d5a131f5daeb4dbb81e8b853c69c1f81&section=plugins#AuthMe

**Comment by sgdc3** [comment]
me.incomprehendable.dev.pwp -> you are using perworldplugins
could you paste it's config?

**Comment by mat41997** [comment]
i don't have a plugin on name "perworldplugins"

this is
https://timings.aikar.co/v2/?id=5bb32d780b1f4690af56488a50489ee6&section=plugins#AuthMe
all my plugins list

**Comment by sgdc3** [comment]
Whoops wrong issue xD

**Comment by sgdc3** [comment]
@mat41997 slimefun is killing your cpu and the server is unable to start in time

**Comment by mat41997** [comment]
ok. a moment

**Comment by mat41997** [comment]
new timings
https://timings.aikar.co/v2/?id=5990b6402c324132babff1e4bc1161bb

**Comment by mat41997** [comment]
my test pack
[server.zip](https://github.com/Xephi/AuthMeReloaded/files/333132/server.zip)

and
https://ci.destroystokyo.com/job/PaperSpigot/798/

**Comment by sgdc3** [comment]
It seems like an AutoIn side issue, we are not the AutoIn developers, please contact @GotoFinal

**Comment by mat41997** [comment]
i contact to @GotoFinal

and
"Zjebali api"

**Comment by ljacqu** [comment]
> "Zjebali api"
> _they fucked up the API_

I don't know to whom this is directed to, but sgdc3 contacted GotoFinal multiple times in case he wanted help or to coordinate with our API.

https://github.com/GotoFinal/AutoIn/issues/56
https://github.com/GotoFinal/AutoIn/issues/45

Next time you or @GotoFinal have something to say, you can say it in a constructive way and in a language we understand. Thanks.

**Comment by mat41997** [comment]
and
@GotoFinal: "ich oficjalne dajen i zabiera losowo opy i gamemody."

**Comment by sgdc3** [comment]
> they fucked up the API
The API is well structured, if you are having issues please open an issue @GotoFinal

**Comment by mat41997** [comment]
i don;t know : P
thx for the all support

Regards

**Comment by sgdc3** [comment]
If you are having issues with autoin maybe you should switch to FastLogin ;)

**Comment by sgdc3** [comment]
@mat41997

**Comment by mat41997** [comment]
XD

FastLogin not work on my serwer, i create the isuses on github, and author (FastLogin) not want to help my problem.

anyway, thanks for the all help to me

**Comment by sgdc3** [comment]
@mat41997 FastLogin is our official addon, i contacted @games647 and he will help you. ;)

**Comment by GotoFinal** [comment]
@mat41997 first of all, don't paste private messages on public.
@ljacqu @sgdc3
 "you can say it in a constructive way" that was from private message, it should never be posted here ;)

About this bug, I wrote to him that this bug isn't caused by authme, the other one is... 
http://dev.bukkit.org/bukkit-plugins/authme-reloaded/tickets/1005-problems-with-auto-in-last-player-location-problem/#c10
Autoin use official authme API, I even posted long time ago a code that use authme api and cause all the bugs that autoin have with login stuff.
```
import org.bukkit.Bukkit;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.plugin.java.JavaPlugin;

import fr.xephi.authme.api.NewAPI;

@SuppressWarnings("ClassInitializerMayBeStatic")
public class Main extends JavaPlugin
{
    @Override
    public void onEnable()
    {
        Bukkit.getPluginManager().registerEvents(new Listener()
        {
            @EventHandler(priority = EventPriority.LOWEST, ignoreCancelled = true)
            public void onJoin(final PlayerJoinEvent evt)
            {
                System.out.println("PlayerJoinEvent event!");
                NewAPI.getInstance().forceLogin(evt.getPlayer());
            }
        }, this);
    }
}
```
This cause randomly removal of gamemode, ops etc... So yeach, perfect API. Waiting near year to fix that...

**Comment by sgdc3** [comment]
Yeah the forceLogin is broken

**Comment by sgdc3** [comment]
#774

**Comment by ljacqu** [comment]
@GotoFinal you can create an issue about this or supply more information to the one sgdc3 linked if you want to act like an adult. Right now it's just complaining and doing nothing, so let's put an end to that fast.
