### ISSUE TITLE
/changepassword should check if Alpha-Numeric

### ISSUE THREAD

**Issue by orkun1675** [Xephi/AuthMeReloaded#79]
I have been long waiting for this feature so if you could add it real quick it would be nice.

Player are typing /changepassword myOldPassword newPasswordWithWierdCharsöç
and because AuthMe doesnt check if the new password is alpha numeric (a-z, A-Z, 0-9, _?.*); they cant log back in to the game. MySQL doesn't support such wierd chars and so shouldn't authme.

**Comment by Xephi** [comment]
https://github.ciom/Xephi/AuthMeReloaded/commit/2aab1d67bb93c72005d6fbba8418271653d28367

I'm really sorry for that delay ...  i was really busy, but it seems ok now :$

**Comment by Xephi** [comment]
Added in /register too

**Comment by Xephi** [comment]
Ok, was already ok >.< but i've the specific rules : password must be different from username
