### ISSUE TITLE
How to set essentials join message

### ISSUE THREAD

**Issue by Oruss7** [Xephi/AuthMeReloaded#790]
Hello amazing developers, 
I want to set essentials join message but if `delayJoinMessage` options is actived, **default** message is display.

That's my essentials config:
````
# You can set a custom join message here, set to "none" to disable.
# You may use color codes, use {USERNAME} the player's name or {PLAYER} for the player's displayname.
custom-join-message: "&7[&2+&7] &f{PLAYER}"

# You can set a custom quit message here, set to "none" to disable.
# You may use color codes, use {USERNAME} the player's name or {PLAYER} for the player's displayname.
custom-quit-message: "&7[&c-&7] &f{PLAYER}"
````

Cheers,
Oruss7

**Comment by Gnat008** [comment]
Hello,

To be clear, if the configuration option `delayJoinMessage` is set to `true`, the server's default join message is displayed anyway?

**Comment by Oruss7** [comment]
yes default message in english but not my custom essentials

**Comment by Gnat008** [comment]
Is the correct join message sent later when it is supposed to?

Also, what is the delayed join message option in the Essentials config set to?

**Comment by Oruss7** [comment]
Essentials have a delayed message option ? I just set config posted on the first post for essentials.

**Comment by sgdc3** [comment]
Essentials handles the join message in a strange way, you need to change the join message with another plugin.
