### ISSUE TITLE
Please fix conflicts with Citizen 2 ver 2.0.19

### ISSUE THREAD

**Issue by vanthoi** [Xephi/AuthMeReloaded#791]
Hello. After I update to ver dev build 1150. Then all my NPC it does not show!
Go back to the old version, it is still working normally.
Thanks!

**Comment by sgdc3** [comment]
@games647

**Comment by games647** [comment]
Could you try it again with disabling hideTablist

**Comment by fullwall** [comment]
Hello, as this is a common problem with Citizens is there any chance that https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/listener/AuthMeTablistPacketAdapter.java could be changed to work with NPCs?

**Comment by games647** [comment]
@fullwall Please see my previous comment. It would help me a lot to find the source.

**Comment by mcmonkey4eva** [comment]
@games647 a random IRC user in the Citizens channel said that works.

**Comment by games647** [comment]
@mcmonkey4eva You mean when hideTablist is disabled?

**Comment by mcmonkey4eva** [comment]
Yup.
They said it all works reasonably after that setting is changed.

**Comment by games647** [comment]
Thanks. It should be fixed now.

**Comment by sgdc3** [comment]
@vanthoi

**Comment by vanthoi** [comment]
Ok Thank! disabling hideTablist it is worked :)

**Comment by sgdc3** [comment]
@vanthoi ehm no, it should work also with the hideTablist feature enabled.

**Comment by vanthoi** [comment]
Ok Good . Thank :)

**Comment by sgdc3** [comment]
@vanthoi Does it work with latest version and hideTablist: true?

**Comment by vanthoi** [comment]
Yes. I Download at 02h14m in 29/06

**Comment by vanthoi** [comment]
oh no no. bug login session bungee cord ! 
If the player has previously logged on to the server.
Then join the server again, no need to log in again
Whether I authme bridge configuration: auto login false
I had to go back to ver 1143 dev :(

**Comment by sgdc3** [comment]
@games647 :/ 

@vanthoi how many servers with authme do you have?

**Comment by sgdc3** [comment]
whops let's create another issue
