### ISSUE TITLE
Create Wiki page about dev setup

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#793]
For people who want to fork the project or join the team, would be nice to have a Wiki page set up about certain IDE configurations etc.

In particular:
- how to not show `@Inject` fields as unused
- how to make issue references clickable
- if I remember how, how to be able to run the plugin in debug inside of intelliJ
- how to properly maintain a fork (keep master synced, add custom changes to other branches only)

**Comment by ljacqu** [comment]
https://github.com/AuthMe-Team/AuthMeReloaded/wiki/Development-Setup

@Gnat008 Could I ask you to review the page? Maybe there is more I could add, or something you disagree with.

**Comment by DardBrinza** [comment]
Thanks, add new config :dash:

**Comment by Gnat008** [comment]
Oh, I never got a notification for that mention. Woo! Sorry about that.

**Comment by Gnat008** [comment]
Looks good to me!
