### ISSUE TITLE
Kick message after registering by an admin

### ISSUE THREAD

**Issue by Twonox** [Xephi/AuthMeReloaded#797]
Could you make this message translatable please?

> http://image.noelshack.com/fichiers/2016/25/1466871477-2016-06-25-18-11-45.png

**Comment by Twonox** [comment]
Could you add quickly this message ?

**Comment by ljacqu** [comment]
Also in RecoverEmailCommand, a meaningful error should be shown if the mail API is not available. Currently defaults to the general error.

```java
        if (plugin.getMail() == null) {
            ConsoleLogger.showError("Mail API is not set");
            commandService.send(player, MessageKey.ERROR); // <-- This
            return;
        }
```

**Comment by Twonox** [comment]
I don't understand xD

**Comment by ljacqu** [comment]
I noticed my above comment while doing something else, so I also "added" it to this issue so I don't forget about it... ;) I'll probably do this in a few hours.

**Comment by ljacqu** [comment]
@Twonox please verify

**Comment by Twonox** [comment]
It works, thanks.

FR translation:
> kicked_admin_registered: 'Un Admin vient de vous enregistrer, veuillez vous reconnecter.'
> incomplete_email_settings: '&cErreur: Tout les paramètres requis ne sont pas présent pour l''envoit de mail, veuillez contacter un Admin.'

**Comment by ljacqu** [comment]
Thanks!
