### ISSUE TITLE
Regex Syntax allowedNicknameCharacters: '[a-zA-Z0-9_]*'

### ISSUE THREAD

**Issue by prozhong** [Xephi/AuthMeReloaded#80]
How does '[a-zA-Z0-9_]*' work when check player's name?
Seems one can register a username with space , like 'a name'?

This may cause huge amount issues...like I cant ban a player named 'a name'

**Comment by Dimatert9** [comment]
Its was fixed. Try update your authme.

**Comment by Xephi** [comment]
Fixed :O
