### ISSUE TITLE
Merge JSONCache and LimboCache, switch to an in-memory cache

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#800]
ERROR 404: DESCRIPTION NOT AVAILABLE :P

**Comment by DNx5** [comment]
the title should be, Fix JSON Cache. because we need it.

**Comment by sgdc3** [comment]
Why? We don't need to store inventories anymore.

**Comment by sgdc3** [comment]
An in memory cache is fine

**Comment by games647** [comment]
What actually do we need to save in-memory?

**Comment by sgdc3** [comment]
The same of limbocache xD

**Comment by sgdc3** [comment]
so i think we should merge them

**Comment by games647** [comment]
Isn't a normal concurrenthashmap enough?

**Comment by sgdc3** [comment]
yeah, we don't need to store tons of data

**Comment by ljacqu** [comment]
but please keep LimboCache and just change it to your needs. Then you can simply call it and LimboCache will worry about the specifics.

**Comment by DNx5** [comment]
limbocache only save in memory, so it could lost on server restart.
that's why we need json cache.
we need to store player status (fly, op, gamemode), but currently we are not save it to disk.

**Comment by sgdc3** [comment]
We don't need to store player status

**Comment by DNx5** [comment]
@sgdc3 not all players have default speed to 0.2, fly mode disabled, default group, not op, etc. we need to store the value that we change before player login to something persistent on server restart.

**Comment by ljacqu** [comment]
@DNx5, this can be closed in my opinion; we have some open points about PlayerData as other issues (bugs). Please re-open if I'm mistaken.
