### ISSUE TITLE
Discussion: global task(s)

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#806]
I'm on mobile so bear with me ;)
For the session timeout we schedule a task for each entry to make sure it expires after the configured time. I think it would be much easier to just store the timestamp when it will expire (like in the tempBanManager). 

One problem is we'll keep all old entries, maybe we could schedule ONE global task that cleans up entries every x minutes. This prevents us from having so many small tasks that do one thing and hang around for a long time. 

Thanks to the injector we can create an interface, get all known singletons that implement that interface and run that method on them -> e.g. As we do with Reloadable :)

I think this needs to be discussed but may help us get rid of some ugly tasks in the codebase

**Comment by DNx5** [comment]
+1  to use timestamp for session, currently the sessions is lost on server restart.

**Comment by sgdc3** [comment]
how to handle sessions with multiple instance under one or multiple bungee proxy?

**Comment by DNx5** [comment]
@sgdc3 save the timestamp inside database

**Comment by sgdc3** [comment]
@DNx5 we already do this, right? ;)

**Comment by ljacqu** [comment]
Now a task is run every 5 minutes and calls `performCleanup()` on all implementors of `HasCleanup`. If the interval should be longer please adjust it. 
If persistent sessions are still desired, please create another issue.
