### ISSUE TITLE
EMAIL RECOVERY ERROR

### ISSUE THREAD

**Issue by RAZERMC** [Xephi/AuthMeReloaded#808]
I set up the email details account and password but when i try to recover my password via 

/email recovery <password> 

console says 

mail api is not set

**Comment by sgdc3** [comment]
Please provide more informations like the plugin version, config, etc...

**Comment by RAZERMC** [comment]
reload command did not work i restarted the server and it worked thanks again

**Comment by ljacqu** [comment]
What was the setting you changed? Enabled email registration? :)

**Comment by sgdc3** [comment]
@RAZERMC

**Comment by RAZERMC** [comment]
no i changed only the smtp account information so players can register with password and add email then recover their account via email

**Comment by ljacqu** [comment]
Thanks for the feedback
