### ISSUE TITLE
sessionExpireOnIpChange bug

### ISSUE THREAD

**Issue by DardBrinza** [Xephi/AuthMeReloaded#809]
Apparently it does not check the whole IP, and only part of it. If I have the IP 192.168.1.1 and the other person will go to the IP 192.168.2.2 his miss with a successful session.

Latest build authme.

**Comment by ljacqu** [comment]
@sgdc3 Could you look at this please? :) A quick look at the code reveals nothing suspicious about this.

**Comment by sgdc3** [comment]
@DardBrinza Are you still having such issue?

**Comment by DardBrinza** [comment]
Excuse me, but I have already fully developed and use my auth plugin on redis + bungeecord + 5 auth servers :(

**Comment by ljacqu** [comment]
Ok, I will check this :wink:

**Comment by ljacqu** [comment]
Checked the code again, it checks the IP. It would be better if I had a means to try to reproduce this in the game, but this is a little difficult. Since the code looks OK and no one else reported this, we close.
