### ISSUE TITLE
Suggest new feature: /authme lock/unlock ip

### ISSUE THREAD

**Issue by tuanjr** [Xephi/AuthMeReloaded#812]
/authme lock/unlock ip
example:
-  /authme lock 1.2.3.4 won't allowed this ip register new accounts
- /authme unlock 1.2.3.4 unlock locked ip

**Comment by sgdc3** [comment]
I'm not sure that it would be an useful feature :/

**Comment by Twonox** [comment]
And the /banip ? x)
But if we can set an interval of IP, why not, it can be useful to block dynamic IP.

**Comment by sgdc3** [comment]
This would be a nice feature for an addon but not in authme.
