### ISSUE TITLE
/logout should invalidate a player's session

### ISSUE THREAD

**Issue by Twonox** [Xephi/AuthMeReloaded#816]
When we do /logout during the session, the session don't expire. We can do /logout, disconnect then connect to the server without entering our pass.

**Comment by sgdc3** [comment]
@ljacqu This is related to the Bungeecord messaging refactor (we need to create an iasue for it) and the session refactor

**Comment by Gnat008** [comment]
Id say this is the same issue as #824, and thus related to #582 =.

**Comment by Twonox** [comment]
I don't use bungeecord

**Comment by sgdc3** [comment]
@Twonox Done ;)

**Comment by sgdc3** [comment]
Whoops found that we already do this

**Comment by ljacqu** [comment]
Reverted -> code was uglier (let SessionManager worry about session settings, why check if player is authenticated inside the logout process?) and did not fix the issue. You didn't test this.

**Comment by sgdc3** [comment]
:( you're evil

**Comment by sgdc3** [comment]
// Session logic
            if (service.getProperty(PluginSettings.SESSIONS_ENABLED) && (sessionManager.hasSession(name) || database.isLogged(name))) {
                sessionManager.cancelSession(name);

                PlayerAuth auth = database.getAuth(name);
                database.setUnlogged(name);
                playerCache.removePlayer(name);
                if (auth != null && auth.getIp().equals(ip)) {
                    service.send(player, MessageKey.SESSION_RECONNECTION);
                    plugin.getManagement().performLogin(player, "dontneed", true);
                    return;
                } else if (service.getProperty(PluginSettings.SESSIONS_EXPIRE_ON_IP_CHANGE)) {
                    service.send(player, MessageKey.SESSION_EXPIRED);
                }
            }
        }

**Comment by sgdc3** [comment]
L 137 AsyncJoin

**Comment by ljacqu** [comment]
Ooh bad, good catch on that, and sorry. I expected more logic to be inside SessionManager; I guess the encapsulation story is still open.
Abd next time I implement some feature I will ask you to verify @sgdc3 so you can exercise revenge ;) :smile:

**Comment by sgdc3** [comment]
:smiling_imp:

**Comment by ljacqu** [comment]
Thank you for reporting this @Twonox. Please verify with build nr. 1219 or above. http://ci.xephi.fr/job/AuthMeReloaded/1219/

**Comment by Twonox** [comment]
That works thanks :)

**Comment by ljacqu** [comment]
Thanks for testing!
