### ISSUE TITLE
Purging essentials files wrong description

### ISSUE THREAD

**Issue by Twonox** [Xephi/AuthMeReloaded#822]
> Description => Do we need to remove the Essentials/users/player.yml file during purge process?
> removeEssentialsFile: false

The correct location is Essentials/userdata/player.yml; I don't know if it's just wrong description or if it's really wrong location. (I didn't test)

**Comment by ljacqu** [comment]
It works, I tested it once. In fact it's .../userdata/uuid.dat now

But if @sgdc3 can test again that's always good :smile:

**Comment by sgdc3** [comment]
We firstly try to remove non uuid file (playername) and later the file with the player uuid, in order to keep conpatibility with old versions
