### ISSUE TITLE
Minimum allowed nick length

### ISSUE THREAD

**Issue by Twonox** [Xephi/AuthMeReloaded#823]
In config file, the default value `minNicknameLength` is `4` but for Mjang the minimum allowed is 3.
You should set `minNicknameLength` default value to `3`.

**Comment by games647** [comment]
Isn't it two?

**Comment by Twonox** [comment]
It's 3, I'm sure because I've tested xD

**Comment by games647** [comment]
I'm wondering, because the username 'bb' exists and is a migrated account:

https://api.mojang.com/users/profiles/minecraft/bb

**Comment by games647** [comment]
or 'ab'

http://mcuuid.net/?q=ab

How do you tested it?

**Comment by Twonox** [comment]
https://account.mojang.com/me/renameProfile

**Comment by Twonox** [comment]
> Please choose a name that is longer than 2 characters.

**Comment by Twonox** [comment]
The nicknames with two characters may be old

**Comment by games647** [comment]
It's a migrated account.

Nevertheless If I would be a server owner I won't let people in that have less than 4 characters in their username.

**Comment by Twonox** [comment]
Another thing:
There is 39 lines between `maxNicknameLength` and `minNicknameLength`
You should put `minNicknameLength` side of `maxNicknameLength`

> Nevertheless If I would be a server owner I won't let people in that have less than 4 characters in their username.
It's your opinion but if the minimum length is 3, it can have premium which can't connect to the server.

**Comment by Twonox** [comment]
You set 3 to default value and if there is Admin with your same opinion, they set it to 4.
