### ISSUE TITLE
Logging in without passsword

### ISSUE THREAD

**Issue by Pijanista** [Xephi/AuthMeReloaded#824]
There is some big problem, players are logging in without password with this catch:

Real player left the server
Fake player comes on  server
Fake player get kick for login timeout or wrong password
Fake player get KICKED on HUB
Fake player is logged in on HUB and can freely do whatever he wants...

How it looks like in log:

He's trying on server when real player left

[19:10:52] [Server thread/INFO]: [CONSOLE->Player] Hey there, Player!
[19:10:52] [Server thread/INFO]: [CONSOLE->Player] Welcome to SERVER - Towny
 [19:11:22] [Server thread/INFO]: Player lost connection: user was kicked.
 [19:11:22] [Server thread/INFO]: Player lost connection: §4Login timeout exceeded, you have been kicked from the server, please try again!

He has logged in on HUB without anything of authme, there isn't even authme message.
[19:11:22] [Server thread/INFO]: [CONSOLE->Player] Hey there, Player!
[19:11:22] [Server thread/INFO]: [CONSOLE->Player] Welcome to SERVER - HUB

And when he changes server only this log:
[Craft Scheduler Thread - 651/INFO]: [AuthMe] Player Playerhas logged in from one of your server!

IDK how this works, but i can't reproduce this problem always, sometimes it works, sometimes it doesn't...

Using lastest authme dev and authme bungee. Authme session is offline while authme bunge autologin is on TRUE. I'll turn off autologin on authme bungee and somehow see does this still works...

EDIT: disabling Autologin in Bridge solves the problem, they have to login. And there is bug if autologin is TRUE, you do /logout and then /server server, you're logged in without password. So i think the problem is somewhere there.

**Comment by Platinteufel** [comment]
AuthMe version?
#807

**Comment by Pijanista** [comment]
Same problem.

**Comment by sgdc3** [comment]
@CryLegend

**Comment by Pijanista** [comment]
Well they have ruined my server...

Fix - turn off Bungeecord hooking in authme config...

Even though there is NO session or whatever, sometimes it happens that authme says message he has logged in from another server and he can do whatever he wants on server.

**Comment by sgdc3** [comment]
@ljacqu @games647 @DNx5 we need to fix the sync between instances via the bungeecord messaging channel,

**Comment by Gnat008** [comment]
I have a theory on this. It could be because the session thinks the fake player is the real player, as Bungee is essentially just a proxy. Therefore, Bungee might be replacing the player's IP with its own, so when the session is checked during join, it sees the IP is the same, and BLAMO, logged in.

**Comment by Gnat008** [comment]
@Pijanista In your BungeeCord config, is `ip_forward` set to `true`? And in your spigot.yml on your servers, is `bungeecord` set to `true`?

**Comment by MichelDeStar** [comment]
This problem still occurs in build 1205, disabled the Bungeecord hook and removed the sessions. Not really user friendly.

With only the bungeecord hook or the sessions disabled the problem still occurs...

**Comment by sgdc3** [comment]
Ok, @Gnat008 not an issue with session, the problem is the sync messages between instances.
