### ISSUE TITLE
AntiBot: Add configurable interval for the time

### ISSUE THREAD

**Issue by Twonox** [Xephi/AuthMeReloaded#826]
> Description => Max number of player allowed to login in 5 secs before enable AntiBot system automatically
> `antiBotSensibility: 3`

Could you add a configurable interval for the time ? (`5 secs`)

**Comment by sgdc3** [comment]
Why? @DNx5 @ljacqu @Gnat008 it seems useless to me

**Comment by ljacqu** [comment]
@Twonox what is your intention with this?

**Comment by Twonox** [comment]
The players can join my server one per one every 3 seconds (it's normal), then authme antibot can't work properly. If I can change this interval, I would like set 10 seconds, and sensibility 3.
