### ISSUE TITLE
Language change is not working in DEV versions

### ISSUE THREAD

**Issue by WaterXCubic** [Xephi/AuthMeReloaded#83]
I am using the last Authme Reloaded versions and that is the forth in jenkins

I changed the language setting in the config file and i reloaded the server and used the command
/authme reload

After i reloaded,it says it changed to that language,and after i joined the game,its still showing english.
I manually dragged the language file from the jar file to the folder of authme.

It just delete everything in the language file

HELP!!!!!!!!!!!!!!!!

**Comment by Xephi** [comment]
For what language did you change ?

**Comment by Xephi** [comment]
AuthMe set English to default if , and only if, the defined language file cannot be loaded, it's maybe due to some accents, etc... converted in incorrectly format : ANSI for Windows and UTF-8 for Linux

Xephi

**Comment by WaterXCubic** [comment]
I set it to Zhhk and its not working,i am trying to convert to ANSI now

**Comment by WaterXCubic** [comment]
For some reason,i converted it to ANSI,its still not working,its says this in the console,
13:19:28 [INFO] [AuthMe] Set Language: zhhk
13:19:28 [SEVERE] messages_zhhk.yml is no valid configuration file
13:19:28 org.bukkit.configuration.InvalidConfigurationException: unacceptable character '?' (0xD84F) special characters are not allowed
13:19:28 in "'string'", position 301
13:19:28 Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
13:19:28 	... 14 more
13:19:28 [INFO] Error with Translation files, please contact the admin for verify or update translation

**Comment by WaterXCubic** [comment]
I have tried to convert the zhhk lang file in the jar file to ANSI,i set to ZHHK and i reloaded it automatically drag it to authme file,and theres nothing in the file.

I have also manually drag it to the authme file,it also delete everything in it even they are converted to ANSI

**Comment by sgdc3** [comment]
It's probably a syntax problem.

**Comment by WaterXCubic** [comment]
XEPHI!!!!!!!!!!!!!!!IT WORKED!!!!!!!!!!!!TYYYYYYYYYYYYY IT WORKED I SUCESSFULLY CHANGED IT TO ZHHK YAAAAYYYYYYYYYYYYYYYYYYYYYYYAAAAAAAAAYY

TY

**Comment by Xephi** [comment]
If you know how to pull request,  you can paste your translation for all of peoples :)  
I hope it will let you use AuthMe normally :) 
If you experience some other bugs, please report them :) 

Xephi

**Comment by WaterXCubic** [comment]
:D
