### ISSUE TITLE
Leave message

### ISSUE THREAD

**Issue by NewBestX** [Xephi/AuthMeReloaded#833]
Hi!
If you set `delayJoinMessage: true` in the config, when a player joins the server you won't get the join message until he logs in. However, if he doesn't log in and disconnects, you will still get the leave message.
Can't believe nobody reported this yet :))

Tested with AuthMe Build #1181 and 5.2 BETA 3.

**Comment by rErEaT** [comment]
https://github.com/Xephi/AuthMeReloaded/issues/583

**Comment by sgdc3** [comment]
```YAML
    # Should we remove the leave messages of unlogged users?
    removeUnloggedLeaveMessage: false```

**Comment by sgdc3** [comment]
@NewBestX @rErEaT

**Comment by Twonox** [comment]
`removeUnloggedLeaveMessage: true` works

**Comment by rErEaT** [comment]
oh sorry :D forget to check it
