### ISSUE TITLE
AuthMe can not support Sponge?

### ISSUE THREAD

**Issue by sourcepowered** [Xephi/AuthMeReloaded#837]
As the title said, we can not support Sponge?...

**Comment by sgdc3** [comment]
@Gnat008 could you explain why we don't want to spend time working on a sponge version? xD

**Comment by sgdc3** [comment]
We dislike the Sponge API and we think that the Sponge project will not replace Bukkit/Spigot

**Comment by AuthGood** [comment]
@sgdc3 Yes, I think so. And I think Cauldron 1.7.10 and any fork of it will kill 1.8+ mod server any time. Sponge is Sponge, you know what I mean. ;)

**Comment by sgdc3** [comment]
@AuthGood yeah sure xD

**Comment by SlimaKCoder** [comment]
Wow, so I'm not only one who really don't like "super new engine" called Sponge ;)

**Comment by SirFaizdat** [comment]
https://forums.spongepowered.org/t/authme-reloaded-official-thread/1825

**Comment by ljacqu** [comment]
For anyone: if you want to make Sponge happen, what we need is development capacity. If someone is willing to _lead_ the implementation of Sponge support for AuthMe, join our Gitter and we'll get the ball rolling... :)

**Comment by evernife** [comment]
What about now?

Sponge is getting bigger, modded comunity is getting bigger.
It would be really greate to have Authme ported for sponge.

For now i need to make a lobby just as workround to still use the Authme.
So, it would be a good thing to have it officially!

**Comment by sgdc3** [comment]
I don't think sponge will replace spigot, it isn't suitable for large networks.

**Comment by evernife** [comment]
Quite sure it wont... but just from the ones that i know, these three servers have a lot of players (Modded modpacks)

![image](https://user-images.githubusercontent.com/11357801/29986986-58014890-8f3c-11e7-9c86-17e91372190a.png)

But if you say "great networks" who have more than 500 players i think it is difficult because of the forge performace (moddeds servers cause lagg...)

**Comment by Eufranio** [comment]
Sponge DID replace spigot when talking about modded, and IS suitable for large networks, people just dont frequently request a AuthMe port because only a small percentage of those networks run modded servers on offline mode.

**Comment by sgdc3** [comment]
Sponge support would require a complete rewrite of the plugin, atm we are too busy to do that.

**Comment by Eufranio** [comment]
A rewrite that would be quicker now than when AuthMe has more and more features: turns out that later it will take more work than it would take currently.

**Comment by ljacqu** [comment]
As said, hook us up with a dev and we can make it happen
