### ISSUE TITLE
please fix bug for 1.10.2 dev 1188

### ISSUE THREAD

**Issue by vanthoi** [Xephi/AuthMeReloaded#840]
Please fix bug dev 1188. If player kicked server! Then login ok but not command add chat!
Console error: http://pastebin.com/GtH6bCFh

**Comment by sgdc3** [comment]
@DNx5 any idea about this? it seems related to your LimboCache update.

**Comment by ljacqu** [comment]
Hi @vanthoi, the log is no longer available on pastebin and the title doesn't give us any details into the issue. Could you please help us?

**Comment by vanthoi** [comment]
Ok it fixed after update new version.  Thank.
