### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Eufranio** [Xephi/AuthMeReloaded#841]
http://prntscr.com/bqv8p9
Is it normal? It appears every time that someone log in.

**Comment by sgdc3** [comment]
@Eufranio What's your permission management plugin?

**Comment by Eufranio** [comment]
PermissionsEX

**Comment by sgdc3** [comment]
@Eufranio Latest build remove the message ;)

**Comment by Eufranio** [comment]
=D
