### ISSUE TITLE
Server ping issue

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#842]
http://dev.bukkit.org/bukkit-plugins/authme-reloaded/?comment=6729
https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/listener/AuthMeServerListener.java#L42

**Comment by ljacqu** [comment]
> but i can confirm when the plugin is enabled it is really hard the server shows in multiplayer servers list... it always shows "Can't connect to server" in red.. i have to click "Refresh" button about 20-30 times to server appear in the list, then we can connect and play

> i test it disabling AuthMe for a while and server shows instantly in list even pressing Refresh many times .... is this a bug, a misconfiguration or am i doing something wrong?

**Comment by ljacqu** [comment]
@atesin Is it better if you disable the protection setting?

Probably caused by AuthMeServerListener: 
```java
    @EventHandler(priority = EventPriority.HIGHEST)
    public void onServerPing(ServerListPingEvent event) {
        if (settings.getProperty(ProtectionSettings.ENABLE_PROTECTION)) {
            String playerIp = event.getAddress().getHostAddress();
            if (!validationService.isCountryAdmitted(playerIp)) {
                event.setMotd(messages.retrieveSingle(MessageKey.COUNTRY_BANNED_ERROR));
            }
        }
    }
```

**Comment by atesin** [comment]
do you know how can i compile a single class file (for later replace (compress) into jar (zip) file) to debug what are you saying?

**Comment by sgdc3** [comment]
Probably validationService.isCountryAdmitted(playerIp) is too slow... @ljacqu

**Comment by atesin** [comment]
even when i had disabled?

**Comment by sgdc3** [comment]
I asked to the reporter to disable the protection setting, no answer atm.

**Comment by sgdc3** [comment]
Oh wait, it's you xD

**Comment by sgdc3** [comment]
Ok, really strange.

**Comment by atesin** [comment]
http://dev.bukkit.org/bukkit-plugins/authme-reloaded/?comment=6735

-    with no authme = server always appears in list instantly
-    with authme 5.2-SNAPSHOT-b870 = 20-30 refreshes until server appear in list
-    with authme 5.2 beta3 = "can't connect to server" more than 30 times and i got tired.. i decided to downgrade 

spec: centos 6.7 final x64, java 7.0_101, xeon 12 cores, 12gb ram ... never heard that "protection setting".... oh i see, enableProtection: false, enableAntiBot: false

**Comment by atesin** [comment]
i wish help you with debugging, though i am not so experienced in java .. but i can use eclipse basic

**Comment by atesin** [comment]
i discovered ... it seems this issue occurs when i am connected in my home .. i am away now and it seems to refresh and server shows fine ... strange because i revceive complaints about this from some players before   ... my subnet is 192.168.218.0/24 ...

my server is at minecraft.netgamer.cl .. i disabled registration because i implemented (log time ago) an invitation based system

**Comment by atesin** [comment]
strange anyway because my server is behind a firewall (a tp-link router with openwrt) ... so the server still should believe outcoming connections are comming from my network

**Comment by sgdc3** [comment]
so strange, with the protection disabled authme does nothing related to the server list ping :(

**Comment by atesin** [comment]
well ...  at least i conform my players outside appear to see the server ok ... maybe is an issue with the network configuration of my house .. if i discover something i will tell you ... thanks for your time and sorry for make you lose it

i still believe AuthMe is the ultimate and most essential plugin

i had a little worry about how this case affects my related and new plugin EnderMail (take a look, is so cool :D http://dev.bukkit.org/bukkit-plugins/endermail/ )

**Comment by ljacqu** [comment]
Thanks for the kind words, @atesin; if this should occur again please leave a comment & reopen, or create a new issue. :) :tangerine:
