### ISSUE TITLE
error on register

### ISSUE THREAD

**Issue by Dimatert9** [Xephi/AuthMeReloaded#843]
lastest authme dev build
http://pastebin.com/VfyUabWr

**Comment by ljacqu** [comment]
Thanks for the report—this is an easy fix I will do tomorrow. 
Does this only happen for some players? Did you recently delete a world?

**Comment by NewBestX** [comment]
Having the same issue, no worlds deleted, happens every time on /register with build #1196

**Comment by ljacqu** [comment]
The cause of this bug is not what I thought it was, and it's a lot worse...

**Comment by ljacqu** [comment]
@Dimatert9 @NewBestX May I ask you to verify? Build n. 1198 or above, http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by ljacqu** [comment]
Side note, this is something we might be able to find in the future, after #771 ;)

**Comment by Dimatert9** [comment]
No error in latest build

**Comment by sgdc3** [comment]
@Dimatert9 Thank you ;)
