### ISSUE TITLE
AutoPurge bug

### ISSUE THREAD

**Issue by rErEaT** [Xephi/AuthMeReloaded#844]
AutoPurge doesn't remove any player data in default world!

AutoPurging the Database: 3 accounts removed!
AutoPurge: Removed 3 EssentialsFiles
AutoPurge: Removed 0 .dat Files

My world/playerdata mappa is contains 5,5k items :O

Or should I remove everything from that? what happen after that?

**Comment by sgdc3** [comment]
@ljacqu

**Comment by sgdc3** [comment]
duplicate, right?

**Comment by ljacqu** [comment]
Can you link the other issue?

**Comment by rErEaT** [comment]
https://github.com/Xephi/AuthMeReloaded/issues/627

**Comment by ljacqu** [comment]
@rErEaT Does `Purge.defaultWorld` match your default world?

**Comment by rErEaT** [comment]
yepp, it says "world"

**Comment by ljacqu** [comment]
We'll find out why ;) When AuthMe was added to your server shouldn't influence the purge process. I wonder, have you ever switched from online mode to offline, or vice versa?
It might be that some old files are lying around with the other uuid type.

**Comment by rErEaT** [comment]
no I didnt.

**Comment by DardBrinza** [comment]
I have " infinite" remove accounts when a lot of them ( in my DB 160K+ accounts)

**Comment by ljacqu** [comment]
@rErEaT @DardBrinza Purging should be fixed with build nr. 1229 or above. http://ci.xephi.fr/job/AuthMeReloaded/
The issue was that the task was only run for the first round, meaning that 5 accounts were being handled and then the task stopped.

**Comment by rErEaT** [comment]
I dont know how to test it :D

because I think my authme database is up to date but the essentials userfiles and the playerdata is not.
So I think the authme is look into the database and if that player expire, remove from everything.

**Comment by ljacqu** [comment]
You're right—the database was cleared properly but data files (Essentials, player .dat) were only cleared for the first five.

**Comment by ljacqu** [comment]
Verified by @FabioZumbi12 
Thank you! :stars:
