### ISSUE TITLE
Player data not updated if player data has been persisted

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#845]
In LimboCache, updatePlayerData() is defined as follows:

``` java
    public void updatePlayerData(Player player) {
        checkNotNull(player);
        removeFromCache(player);
        addPlayerData(player);
    }
```

The only issue is that addPlayerData() checks if there is a file for the player on the disk, and then just reads from the disk. In other words, once data has been persisted to the disk, the data will never be updated anymore.

Also, data is being taken from the user even if it will then be read from the disk. 

``` java
        float walkSpeed = player.getWalkSpeed();
        float flySpeed = player.getFlySpeed();
        // ...

        if (playerDataStorage.hasData(player)) {
            PlayerData cache = playerDataStorage.readData(player);
            if (cache != null) {
                // ...
                walkSpeed = cache.getWalkSpeed();
                flySpeed = cache.getFlySpeed();
            }
        } else {
            playerDataStorage.saveData(player);
        }
```

It should be possible to call `playerDataStorage.readData()` first (saves a call to `playerDataStorage.hasData()`, which has to interact with the file system, too) and then if the result is `null` either read from the player or continue with the read data.

**Comment by DNx5** [comment]
Its not get updated to make last location work, because bukkit doesn't allow us to teleport player to the last location on player quit event (pre 1.10.2). The data will removed when player logs in. the problem is if another plugin change the player's state that has been stored into the file while player is not authenticated, it will still same on player next login.
for example, if console OP me while i'm offline, I will not get OP on login.

**Comment by ljacqu** [comment]
I need to look at this into more detail to fully analyze – what I could imagine is that we have two or three strategies for dealing with these things and could let the user decide what he wants, assuming we have a data synchronization issue (player object vs. stored PlayerData) we can solve in different equally correct ways.

**Comment by ljacqu** [comment]
this has become obsolete with the new limbo branch -> closing
