### ISSUE TITLE
[IllegalArgumentException]: Invalid salt version

### ISSUE THREAD

**Issue by bob7l** [Xephi/AuthMeReloaded#848]
**Errors:** 
Bcrypt checkpw() returned [IllegalArgumentException]: Invalid salt version
XfBCrypt checkpw() returned [IllegalArgumentException]: Invalid salt version

**Tested Versions:**
AuthMe 5.2 BETA 3, Build #1214

**Logs:**
http://pastebin.com/Uby0YFBq

**How to Reproduce:** 
Login to the server and use /login <password>. It appears if the password is incorrect, the exception is thrown. 

**Enviroment Info:**
MySQL 5.6 ~ CentOS 7 ~ Spigot 1.9

The database is approximately 4 years old. It started out originally as an XAuth database, and then we merged with another server who used AuthMe. The database contains both XAuth hashed passwords, and SHA256 passwords.

**Comment by ljacqu** [comment]
Thanks for the report. This is nothing critical but I guess should be handled more appropriately. You have the `supportOldPasswords` setting enabled, which means AuthMe will try all available hash methods. 
The hashes in your database don't match the format of Bcrypt & friends and so they output an exception. Nothing is affected by this negatively, except for the pesky log message.

**Comment by bob7l** [comment]
ljacqu, couldn't you guys simply add "supportedHashes: XAUTH, IPB3, ECT" below supportoldPasswordHash? It seems a little silly to iterate over 20 or so hash generators to find whether any are compatible with the inputted hash.

**Comment by sgdc3** [comment]
@bob7l great idea

**Comment by ljacqu** [comment]
Agree 100%

**Comment by ljacqu** [comment]
This has been fixed for a while in the dev builds; should there be an issue please feel free to comment/open again.
