### ISSUE TITLE
[IllegalArgumentException]: com.google.common.io.BaseEncoding$DecodingException: 

### ISSUE THREAD

**Issue by bob7l** [Xephi/AuthMeReloaded#849]
**Errors:** 
java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: 0

**Tested Versions:**
AuthMe 5.2 BETA 3, Build #1214

**Logs:**
http://pastebin.com/pXntP0Cw

**How to Reproduce:** 
Login to the server and use /login <numeral password>. Authme will throw an exception and the login will fail if the password is incorrect. 

**Enviroment Info:**
MySQL 5.6 ~ CentOS 7 ~ Spigot 1.9

The database is approximately 4 years old. It started out originally as an XAuth database, and then we merged with another server who used AuthMe. The database contains both XAuth hashed passwords, and SHA256 passwords.

**Comment by ljacqu** [comment]
See #848 for explanation of cause. 
This is an error that we do not handle, though = bug that must be fixed within 5.2. This will be fixed within the next five days and this issue will be updated. 
Thanks for reporting

**Comment by ljacqu** [comment]
@bob7l Build n. 1217 and above now properly catch this exception and log a message. Please verify that the bug is fixed to your satisfaction, or feel free to just close this, since it's a minor change.

**Comment by bob7l** [comment]
Fixed
