### ISSUE TITLE
Direct showing users password??

### ISSUE THREAD

**Issue by WaterXCubic** [Xephi/AuthMeReloaded#85]
So i am requesting this feature cuz admins can easily check players record without the help of the owner 

I really wanted it and maybe it can be done by like executing a command /authme getpw <username>
like that

It would be nice if u can add it to Authme ! Ty

**Comment by sgdc3** [comment]
-1! The plugin MUST provide to all the users the ability to have a private password due to privacy. I think it's more ethical to provide an administrator command to bypass the login of a specified player, like /authmebypass playername administratorpassword

**Comment by sgdc3** [comment]
@Xephi What do you think about this request?

**Comment by Xephi** [comment]
Password is hashed and cannot be revert, the password comparaison work like that : On /login, we get the password entered, hash it, and compare with the stored one

Xephi

**Comment by sgdc3** [comment]
@Xephi Yes i know, but a bypass command sometimes is required to allow an adequate moderation.
Also, please force the option removePassword to true if the password are set to be encrypted!

**Comment by WaterXCubic** [comment]
Yea i agree with the bypass command,its not needed for direct password maybe,its more better for using the bypass command

**Comment by WaterXCubic** [comment]
Also Xephi can u watch my another issue,its about the language bugg

**Comment by sgdc3** [comment]
@WaterXCubic This is still an in-development version of the plugin, languages support will be fixed when authme will be stable ;)

**Comment by Maxetto** [comment]
I want to remind everyone that AuthMe has a passpartu function, where you can get a passpartu token (valid for 60 seconds) from the console and login to someone account with /passpartu "token"

Also, make someone's password clear, above all the good uses, makes everyone password unsafe. This means, if I search your account on a forum, steam, or even Minecraft (if you're premium), i could use your login details which I got from AuthMe to hack into your account. This method is also commonly used to grief other people servers'.

**Comment by sgdc3** [comment]
I know passpartu feature had security problems in the past, I didn't check if now it's fixed.

**Comment by Xephi** [comment]
Before adding new enhancement, i need to fix existing ones :)

**Comment by WaterXCubic** [comment]
@sgdc3 Thx for telling me that the language bug :D

**Comment by Maxetto** [comment]
I know that passpartu had a bug, but i think i remember it got fixed a couple of releases later...

In any case, I think passpartu is a feature to activate only when you have to check someone's account and keep it deactivated for everything else

**Comment by Xephi** [comment]
rework passpartu + add /authme forcelogin : done

Xephi

**Comment by Maxetto** [comment]
Any form of protection? Like, if i hack into someone's account who is OP and i want to forcelogin my friend with the founder's name.
Maybe a permission to be excluded by forcelogin command (default to OPs)

**Comment by sgdc3** [comment]
@Xephi What about the RemovePassword option I mentioned above?

**Comment by sgdc3** [comment]
@Maxetto we can avoid this allowing this command only from console by default.

**Comment by Xephi** [comment]
Changed from op to console only :)
And i will force the removePassword, but i need to change something in the actual PlainText format

**Comment by sgdc3** [comment]
@Xephi Thank you ;)

**Comment by WaterXCubic** [comment]
OMFG Xephi u did 11 updates in just a few hours . . . its amazing

**Comment by WaterXCubic** [comment]
Also TY for force login command,thats amazing :DDDDDDDDDDDDDDDDDDDDDDDDDDDD

**Comment by WaterXCubic** [comment]
Also maybe u can make a option in the config file to make owners select that they can deny ops to use the forcelogin cmd,it would be great :D

P.S. suggested option: deny_op_force:true/false :P

**Comment by sgdc3** [comment]
@Maxetto I agree with you, Xephi is awesome! :D

**Comment by Maxetto** [comment]
@WaterXCubic There's no need for that, we have 2 permissions, one for allowing the commando and one for deny some people to be force logged in

**Comment by sgdc3** [comment]
@Xephi I think it's also importat to provide an option which disables OP permission for AuthMe like WorldGuard and WorldEdit (OpPermission: true/false)
