### ISSUE TITLE
Allow to specify support for multiple hashes

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#850]
As described in #848, it would make sense to set an option to allow to check against multiple password hashes (to still support one, two old ones)

--> I would suggest to keep the hash property as it is and to drop "supportOldHashes" setting in favor of a new list property where old hashes can be defined. 
This keeps it clear to the user which hash is used for new passwords and allows us to migrate settings more easily

**Comment by sgdc3** [comment]
+1

**Comment by ljacqu** [comment]
Hi @bob7l if this is still relevant for you could I ask you to verify that it behaves as you'd expect? There's a new setting `legacyHashes` that can take whichever old hashes you want to still support:

```yaml
legacyHashes:
- 'SHA256'
- 'MD5'
```

This available with build n. 1453 and above – http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by ljacqu** [comment]
Reopened—when Authme saves the config.yml (for some other property) the config.yml cannot be read anymore...
