### ISSUE TITLE
found problem in AuthMe 5.2 BETA 3

### ISSUE THREAD

**Issue by jomjonejame** [Xephi/AuthMeReloaded#851]
Help me please !!

First time joined to server. npc has missing [ NPC of citizen ]

<a href='https://postimg.org/image/r1agqazlz/' target='_blank'><img src='https://s31.postimg.org/5rmufgjbf/2559_07_13_20_06_59.png' border='0' alt='2559-07-13_20.06.59'/><br /><a target='_blank' href='https://postimage.org/'></a>

But when teleport to player and return to same. NPC back to the same

<a href='https://postimg.org/image/vq25u41kh/' target='_blank'><img src='https://s32.postimg.org/ub0l5e0hh/2559_07_13_20_07_13.png' border='0' alt='2559-07-13_20.07.13'/><br /><a target='_blank' href='https://postimage.org/'></a>

**Comment by sgdc3** [comment]
fixed in latest dev build, you can fix it without updating by disabling the hiteTablistBeforeLogin setting

**Comment by jomjonejame** [comment]
hiteTablistBeforeLogin

it's not work. npc recovered intact

**Comment by ljacqu** [comment]
What's your /authme version? Did you try the latest dev build?

**Comment by jomjonejame** [comment]
AuthMe 5.2 BETA 3 ( build: 1134 )

**Comment by sgdc3** [comment]
http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT-spigot.jar try this version

**Comment by jomjonejame** [comment]
Thank you for link.

**Comment by sgdc3** [comment]
@jomjonejame Does it work?

**Comment by jomjonejame** [comment]
@sgdc3  It's work, Thank you vary much. to tell if has problem

**Comment by jomjonejame** [comment]
@sgdc3  I'm found problem in AuthMe-5.2-SNAPSHOT-spigot for you.

1.System login has problem : same times joined to server But can't login
   1.1 When comes to servers, it can't walk and can not use /login or /l.

But NPC its work for first joined

Sorry for my english is not good

**Comment by sgdc3** [comment]
@ljacqu do we have breaking issues open like these? O_o

**Comment by sgdc3** [comment]
Anyway the reported issue is fixed, please open another report for the other ones ;)

**Comment by ljacqu** [comment]
@sgdc3 What do you mean with breaking issue?

**Comment by sgdc3** [comment]
>1.System login has problem : same times joined to server But can't login
1.1 When comes to servers, it can't walk and can not use /login or /l.

**Comment by ljacqu** [comment]
We don't have anything open like this. I don't understand item 1 but it's likely we have 1.1 currently with certain conditions
