### ISSUE TITLE
Deop on join?

### ISSUE THREAD

**Issue by Dimatert9** [Xephi/AuthMeReloaded#852]
Why when i join to server authme deop me, and after login authme op me again?
When i can disable this?

**Comment by sgdc3** [comment]
@Dimatert9 What's your plugin version atm?

**Comment by Dimatert9** [comment]
latest build

**Comment by ljacqu** [comment]
That's the expected behavior, though—before logging in, you are not op. This prevents imposters and unauthorized access.

**Comment by sgdc3** [comment]
lol misread the message
