### ISSUE TITLE
ask: What different between "legacy" and "noshade" and "spigot" version?

### ISSUE THREAD

**Issue by tuanjr** [Xephi/AuthMeReloaded#854]
may i ask stupid question, but what What different between "legacy" and "noshade" and "spigot" version?
and what is better (stable) for use?

**Comment by ljacqu** [comment]
We have a small Wiki page about this at https://github.com/AuthMe/AuthMeReloaded/wiki/AuthMe-Releases-(Jenkins)

Essentially it depends on your server. Legacy for older versions, otherwise spigot.
