### ISSUE TITLE
Late teleport

### ISSUE THREAD

**Issue by Mormaii** [Xephi/AuthMeReloaded#855]
When using the latest dev build and using

`ForceSpawnLocOnJoin: true`

There's a late teleport bug in which it takes 1-2 secs to teleport you after joining the server.

**Comment by Mormaii** [comment]
Could you guys check this out please? :)

**Comment by sgdc3** [comment]
@ljacqu any idea? @DNx5 managed to fix this once, right?

**Comment by Mormaii** [comment]
If you could please check this out guys I'd really appreciate it since It's bugging my players :/

**Comment by sgdc3** [comment]
@ljacqu @DNx5  Could you take a look at this?

**Comment by Mormaii** [comment]
This is still a bug

**Comment by ljacqu** [comment]
@Mormaii Could you try with the latest build please? @sgdc3 Changed the priority of some event listeners. I'm testing on localhost so obviously I don't experience any lag like "in the wild" but the bug doesn't seem to happen at all.

**Comment by Mormaii** [comment]
Which one? All of the latest ones are giving errors on jenkins

**Comment by ljacqu** [comment]
Build n. 1263 is fine to use :) It's yellow because one test failed, and it only failed because the build was slower than usual. It doesn't affect the plugin code itself

**Comment by Mormaii** [comment]
It works now! It doesn't fully load and it teleports to the spawn correctly and in a fast way.

**Comment by sgdc3** [comment]
;)

**Comment by sgdc3** [comment]
@ljacqu We need a new tag policy xD
