### ISSUE TITLE
How to translate tempban IP login fail!

### ISSUE THREAD

**Issue by vanthoi** [Xephi/AuthMeReloaded#858]
I enabled tempban. But not translate message!
You have been temporarily banned for failing to log in too many times.

**Comment by Twonox** [comment]
You must use the latest dev build, if it's already the latest add this to your messages.yml:
`tempban_max_logins: ''`
Or reset your message.yml to get the news messages.

**Comment by vanthoi** [comment]
Thank!
I still test! :)
