### ISSUE TITLE
Kick if not registered - Cracked

### ISSUE THREAD

**Issue by Pijanista** [Xephi/AuthMeReloaded#859]
Hello, 

Is there possibilty to add support for like semi-cracked server. So for example if user has premium and has joined server he can freely register, but if cracked user joined and he's not registered he's kicked from the server. After mod/admin register him with command cracked user can join freely.

**Comment by sgdc3** [comment]
Sure, you need to use FastLogin, our official addon made by @games647 ;) https://github.com/games647/FastLogin

**Comment by Pijanista** [comment]
Yeah that's it but not all. I need that premium player will be registered(if he's not) and cracked player kicked until they're manual registered.

So alittle bit integration of authme "kickNonRegistered" and fastlogin for auto register and login of premium.

FastLogin just gives me option to auto register/login premium player.

**Comment by sgdc3** [comment]
That's something FastLogin should do, not authme. @games647
