### ISSUE TITLE
invisible npc. when joined first times

### ISSUE THREAD

**Issue by jomjonejame** [Xephi/AuthMeReloaded#861]
AuthMe 5.2 BETA 3
MC 1.8

when players joined first time to server. They are invisible npc

<img src="https://camo.githubusercontent.com/9eb6a17f7428e7e1af5f47351bdabe7b288804d3/68747470733a2f2f7333312e706f7374696d672e6f72672f35726d7566676a62662f323535395f30375f31335f32305f30365f35392e706e67" border="0" alt="2559-07-13_20.06.59" data-canonical-src="https://s31.postimg.org/5rmufgjbf/2559_07_13_20_06_59.png" style="max-width:100%;">

and teleport to another is can see npc

<img src="https://camo.githubusercontent.com/7ce7df72341f2313cc87c0d65421178b612eaf7e/68747470733a2f2f7333322e706f7374696d672e6f72672f7562306c35653068682f323535395f30375f31335f32305f30375f31332e706e67" border="0" alt="2559-07-13_20.07.13" data-canonical-src="https://s32.postimg.org/ub0l5e0hh/2559_07_13_20_07_13.png" style="max-width:100%;">

**Comment by sgdc3** [comment]
??? this is a duplicated issue

**Comment by sgdc3** [comment]
we aready fixed this

**Comment by Twonox** [comment]
Use the latest Dev Build
