### ISSUE TITLE
Error on /login

### ISSUE THREAD

**Issue by Sitmobedaf** [Xephi/AuthMeReloaded#862]
Periodically on players join http://pastebin.com/ymg42JQy

**Comment by Sitmobedaf** [comment]
Spigot 1.10.2

**Comment by ljacqu** [comment]
I will fix this tomorrow, sorry for taking so much time on such a blocking bug. I want to properly analyze _why_ this is happening

**Comment by ljacqu** [comment]
@Sitmobedaf , @jomjonejame Please verify with build n. 1227 or above. http://ci.xephi.fr/job/AuthMeReloaded/
This is kind of a dirty fix; we need to find the _cause_ of this. Do you notice this happening only with certain players? Is there anything special you think might cause this?

**Comment by Sitmobedaf** [comment]
Here is now Google notify me for IP block (37.187.168.181), my DS have IP: 87.98.181.80

Google security: "Someone recently tried to log into your account with this device. You indicated that this attempt and changed the password."

But before everything worked! Why do these connections become blocked?

http://img10.lostpic.net/2016/07/20/5a86452c60c096608edd68f83439cc1b.jpg

**Comment by ljacqu** [comment]
Wrong issue.

**Comment by jomjonejame** [comment]
@ljacqu the issue has been resolved. But probably not all in lasted build


**sometimes is problem in login**
if has message "Unable to locate sign at x,x,x" in game. i can't use command login

<a href='https://postimg.org/image/vgdejob35/' target='_blank'><img src='https://s32.postimg.org/kgs782ko5/2559_07_21_08_08_49.png' border='0' alt='2559-07-21_08.08.49'/></a>

<a href='https://postimg.org/image/ccne6a5l3/' target='_blank'><img src='https://s31.postimg.org/7dzvrr1sb/Untitled_3_copy.jpg' border='0' alt='Untitled-3 copy'/></a>

<a href='https://postimg.org/image/dky8klfuf/' target='_blank'><img src='https://s31.postimg.org/reml9n8fv/Untitled_5_copy.jpg' border='0' alt='Untitled-5 copy'/></a>

**Comment by ljacqu** [comment]
Thanks for the answer @jomjonejame , the rest of your post seems like an unrelated issue. Not sure if it's still open; if it is, please create another issue for it so we can easily keep track of issues.
