### ISSUE TITLE
latest Dev Build is not work for login

### ISSUE THREAD

**Issue by jomjonejame** [Xephi/AuthMeReloaded#863]
Sometimes can not login.

I'm found problem in latest Dev Build for you.

1.System login has problem : same times joined to server But can't login. When comes to servers, it can't walk and can not use /login or /l.

Sorry for my english is not good

**Comment by ljacqu** [comment]
Can't login -> what happens? Error in log? Error message to user?
Which /authme version?

**Comment by sgdc3** [comment]
@ljacqu latest builds

**Comment by jomjonejame** [comment]
@ljacqu Yes lastest builds

and not have error in log and error message

**Comment by ljacqu** [comment]
So just nothing happens?

**Comment by Twonox** [comment]
What message you receive when Authme load ?

**Comment by jomjonejame** [comment]
I found error in console
URL : http://pastebin.com/QEFeeL3e

**Comment by Twonox** [comment]
#862 Same error

**Comment by ljacqu** [comment]
Thank you for the analysis, @Twonox. Thanks for reporting it, @jomjonejame. Since we already have an issue for it, closing this one. Please subscribe to #862 to stay notified about this bug.
