### ISSUE TITLE
E-Mail Recovery

### ISSUE THREAD

**Issue by Sitmobedaf** [Xephi/AuthMeReloaded#864]
Ceased E-Mail recovery system. All parameters configured correctly. I constantly update AuthMe, and problem beginning recently.

And fix double message: add_email: '&3Please add your email to your account with the command "/email add <yourEmail> <confirmEmail>"'

**Comment by Sitmobedaf** [comment]
*Double message on registration.

**Comment by ljacqu** [comment]
Please specify:
- When does it happen? (What command? Which event?)
- What happens? (Exception in log? Error message to user?)

**Comment by Sitmobedaf** [comment]
http://pastebin.com/dpjuAMte

Admin issued server command: /email recovery MyEMail@mail.ru

**Comment by ljacqu** [comment]
This is some issue with your email configuration, the server you're sending from or to is not accepting it. I'm fairly sure that this is a configuration problem and not some bug that snuck in with a recent build.

**Comment by Sitmobedaf** [comment]
With GMail same:
[18:26:57] [Craft Scheduler Thread - 1146/WARN]: [AuthMe] Failed to send a mail to [Sitmobedaf@mail.ru]: [EmailException]: Sending the email to the following server failed : smtp.gmail.com:465

**Comment by sgdc3** [comment]
With gmail you need to enable the Allow Unsafe Clients feature (google side)

**Comment by Sitmobedaf** [comment]
I allow untrusted connections. The problem is relevant. I will continue tomorrow. Please, add MySQL to SQLite converter.

**Comment by sgdc3** [comment]
It already exist if i remember well :/

**Comment by sgdc3** [comment]
Yrah it's missing :/ we'll add it asap

**Comment by ljacqu** [comment]
@Sitmobedaf is right, I just downloaded 5.2-BETA3-b1134 and email works fine. Switching to latest dev build brings an issue with the certificate:
http://hastebin.com/esogexomup.avrasm
(Replaced my mail host with "xxxxx")

**Comment by Sitmobedaf** [comment]
I not found 5.2-BETA3-b1134 in http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by sgdc3** [comment]
http://ci.xephi.fr/job/AuthMeReloaded/1134/

**Comment by sgdc3** [comment]
It's the beta3 jar available also from spigot and bukkit

**Comment by Sitmobedaf** [comment]
With 1134 recovery post successfully send.

**Comment by ljacqu** [comment]
I just checked a few build numbers and could never get this error anymore. Now even the latest few builds work fine for me and I can send an email. I'm really confused... @Sitmobedaf Can you download the latest build number and check again please? I don't know what to say.

**Comment by ljacqu** [comment]
Hello @Sitmobedaf, after investigating further I do not think there is an issue with our email system. I cannot send emails when I run a Minecraft server in IntelliJ itself (used for debugging). If I run a server from command line, sending emails is fine. The build number is not relevant. I get the same issue with BETA3, and I can send emails just fine with the latest builds.
Is it possible that you've changed how you run the server, or that you've also tested similarly to what I've described? I can send emails just fine with the latest builds in a "normal" environment.

**Comment by Sitmobedaf** [comment]
Yes, with 1230 problem not found. Issue is solved.

**Comment by ljacqu** [comment]
Thanks for the feedback.
