### ISSUE TITLE
Latest build don't work

### ISSUE THREAD

**Issue by Twonox** [Xephi/AuthMeReloaded#866]
When server starts console receive this:
http://hastebin.com/viwulolejo.profile

When I use Authme commands:
http://hastebin.com/juketewayo.vbs

**Comment by ljacqu** [comment]
What server (incl. version) do you use? Which authme JAR?

**Comment by ljacqu** [comment]
@sgdc3 Isn't there some story with older Spigot(?) versions not having Gson or something? I remember something with Guava, but maybe also something changed with Gson?

**Comment by Gnat008** [comment]
That would be my guess. GSON wasn't bundled with Bukkit until sometime in early 1.8.x I think.

**Comment by ljacqu** [comment]
My guess, @Twonox is running 1.7 or older and used the shaded.jar and mistakenly used the regular jar this time. Is this possible, @Twonox? ;)

**Comment by Twonox** [comment]
I use Authme-spigot.jar and my server is PaperSpigot 1.7.10

**Comment by ljacqu** [comment]
Please use the legacy JAR. A description of our JAR's is available at https://github.com/AuthMe/AuthMeReloaded/wiki/AuthMe-Releases-(Jenkins)

**Comment by Twonox** [comment]
Thank, it works ;)
I have alwas used spigot.jar and it was works fine wtf xD

**Comment by ljacqu** [comment]
I think @sgdc3 added the Gson exclusion one week ago (3616c3187ebcdeb212c8b19833c7d1e5941e0f67), but still weird that no errors related to Guava showed up. Thanks for the feedback anyway, glad this could be solved :)

**Comment by Twonox** [comment]
I use the spigot.jar in my principal server, if I use legacy.jar the database stil works ?

**Comment by ljacqu** [comment]
Yes, absolutely!
We use some libraries that Spigot also uses. To make the JAR size smaller we don't include those libraries. But older Spigot versions and Cauldron don't have the same libraries, so we include them into the JAR. It's all the same apart from that, so database stays the same, etc. :)
