### ISSUE TITLE
[Feature Request] Two-Factor Authentication

### ISSUE THREAD

**Issue by Maxetto** [Xephi/AuthMeReloaded#87]
As it's stated in the title, some kind of Two-Factor Authentication to let, people who activated it, to use "/login Token" to login into their account instead of using their password (password needs to be completely blocked if TFA is activated).
It needs to be compatible with common Authentication apps (Google Authenticator, Microsoft Authenticator, etc) and it could be forced after register/login to certain people (if they have the permission "authme.tfa").

Linking support must be provided both with the secret key and the QR Code (QR Code can be scanned for people who use phone apps, to not let them copy the long secret key)

**Comment by WaterXCubic** [comment]
I agree with that,but Xephi said that he/she will need to fix those problems before adding new enhancements ;D

**Comment by Xephi** [comment]
@WaterXCubic  "He" :) 

And yep, i will fix actual problems before adding new features :)

**Comment by Maxetto** [comment]
I have no hurry. Keep that as a reminder for something useful in the future ;)

**Comment by WaterXCubic** [comment]
Guys i wanna ask that is there a way to set never time out a player??IDK how do i set it ;o

**Comment by Maxetto** [comment]
I think putting timout to 0 or -1

**Comment by Xephi** [comment]
Yep, set timeout to 0 ^^

**Comment by WaterXCubic** [comment]
:D ty

**Comment by games647** [comment]
I know this kind of late, but do you want this feature as an alternative to the current password method or really as "Two-Factor" (an additional security check besides the current ones)-Authentication. 

Furthermore how should the barcode be scanned, with a browser link or a map?
An example:
![Minecraft qr map](http://i.imgur.com/9YuekuK.png)
![Google Authenticator APP](http://i.imgur.com/HWNR8SK.png)

**Comment by ljacqu** [comment]
Open points (via https://github.com/AuthMe/AuthMeReloaded/commit/6a75184ad993de2e87e95523d77d69f072e6ee47)
- what happens when an admin does /authme changepassword with 2FA? 
- can a user get the barcode again later, or regenerate it? (Say, he switches cellphones)
- should 2FA be optional (i.e. default is password, but can optionally choose to use 2FA)

> What would you think about the introduction of a new column in the DB, containing the hash algorithm? I've already thought that this would be useful for migrations, and now with 2FA this would be even more useful to let the user choose between the standard hash and 2FA.

**Comment by games647** [comment]
>what happens when an admin does /authme changepassword with 2FA?

I think about setting a new master key, but it would be much better to send an email with a random one.

>can a user get the barcode again later, or regenerate it? (Say, he switches cellphones)

No the master key should be backed up. 

>should 2FA be optional (i.e. default is password, but can optionally choose to use 2FA)

I guess so, because that's what the ticket says.

>What would you think about the introduction of a new column in the DB, containing the hash algorithm? I've already thought that this would be useful for migrations, and now with 2FA this would be even more useful to let the user choose between the standard hash and 2FA.

Yes I agree with you.

**Comment by Maxetto** [comment]
> what happens when an admin does /authme changepassword with 2FA?
I think this should be useful when switching phone. Like changing password, but actually changing the phone.

> should 2FA be optional (i.e. default is password, but can optionally choose to use 2FA)
I stated to be optional because I don't see it being smart and efficient to force it on every user (let's say someone don't have a phone or don't want to install an Authenticator).

**Comment by sgdc3** [comment]
@ljacqu @games647 Hello, what about this? Should we change the milestone to 5.4?

**Comment by ljacqu** [comment]
Hi @sgdc3, I'd like to create two follow-up issues for 5.4 indeed and put this back to 5.2 & close it

**Comment by sgdc3** [comment]
ok

**Comment by ljacqu** [comment]
With this issue, @games647 implemented the 2FA feature. For now, it forces everyone to use it if configured, and the questions above are unanswered. In 5.4, we'll handle these questions with the issues linked just above this comment, and we'll then have a fully functional (and optional) two-factor auth implementation.
