### ISSUE TITLE
Critical security issue

### ISSUE THREAD

**Issue by lapin-b** [Xephi/AuthMeReloaded#870]
Hello,
Since this is a critical security issue, I won't describe it (how to reproduce, how it affect the accounts and what you can do with) here.
Instead, you can email me via my public email address or on Twitter @l4p1n (PM).

Best regards, 
lapin-b
(PS: If you wanted me to email you directly, I didn't know who to contact...)
**Edit**: After serveral testing, the issue is more critical than I first thought

**Comment by Twonox** [comment]
With the latest dev build ?

**Comment by ljacqu** [comment]
Email sent to your public email just now from an email address that somewhat resembles my Github name (ends in "lk"). Thanks

**Comment by sgdc3** [comment]
@lapin-b

**Comment by ljacqu** [comment]
The bug affects AuthMe 5.0 and relates to usernames with different casing (think `lapin` vs. `Lapin`). Upgrading to 5.2 fixes it so this can be closed.
