### ISSUE TITLE
plugin.yml default permissions are ignored

### ISSUE THREAD

**Issue by Sitmobedaf** [Xephi/AuthMeReloaded#872]
authme.player.login:
        description: Command permission to login.
        default: true
    authme.player.logout:
        description: Command permission to logout.
        default: true
    authme.player.register:
        description: Command permission to register.
        default: true

Is not working. Players can't register login, etc. commands.

**Comment by sgdc3** [comment]
You mean the default value?

**Comment by Sitmobedaf** [comment]
Yes, above players have this permissions. AuthMe must listen "default: true". It was not until version 3.5, maybe later.

**Comment by sgdc3** [comment]
@timvisee Can you help us with this?

**Comment by ljacqu** [comment]
If someone could kindly review the changes to plugin.yml, that would be swell. I'm not sure what I'm doing :P
@sgdc3 @Sitmobedaf

**Comment by Sitmobedaf** [comment]
Checked with b-1263, problem si not solved :(

**Comment by sgdc3** [comment]
@ljacqu It seems that the default: value is ignored

**Comment by ljacqu** [comment]
@Sitmobedaf So you're not using any permission manager?

**Comment by Sitmobedaf** [comment]
It does not matter. Plugin must listen permissions data in plugin.yml. So it must be, as well, you know what I mean? Why a whole team of developers can not produce a plugin order for the week? Maybe you already will take up the matter? I'm tired of the same batter.

**Comment by ljacqu** [comment]
You know what, since you're always so unpleasant, from now on you can send pull requests to fix issues. Don't bother creating issues without a PR. It's unfortunate that you've learned _nothing_ from being banned from Gitter.

**Comment by sgdc3** [comment]
Still an issue

**Comment by sgdc3** [comment]
#903

**Comment by ljacqu** [comment]
As tested by @Platinteufel this issue is solved when `Player#hasPermission` is used instead of the `PermissionHandler#hasPermission`. I'm not sure if this is true for each permission plugin, though I would assume this is how Bukkit intended things to work.

**Comment by sgdc3** [comment]
@ljacqu Yeah, i can confirm this

**Comment by ljacqu** [comment]
Thanks, @sgdc3 , I'll submit a PR for review & discussion.

**Comment by sgdc3** [comment]
Merged
