### ISSUE TITLE
PvP before /login

### ISSUE THREAD

**Issue by Twonox** [Xephi/AuthMeReloaded#877]
PvP is enabled when we are not loged

**Comment by ljacqu** [comment]
Any pvp plugin in particular, or literally just inflicibtg damage to a player on "vanilla?"

**Comment by Twonox** [comment]
On vanilla

**Comment by sgdc3** [comment]
O_o @ljacqu we use the listeners to cancel pvp and pve events, it can't be a conflict!

**Comment by ljacqu** [comment]
That's why I asked, I could have imagined that some plugin would interfere. Strange that this occurs on "vanilla"

**Comment by Twonox** [comment]
I forgot a detail sorry.
A loged in player can't kill the player who does not loged in but he can got kill by this not loged in player.

**Comment by ljacqu** [comment]
Aha, nice catch :)

**Comment by sgdc3** [comment]
@Twonox Should have been fixed ;)

**Comment by Twonox** [comment]
Fixed, thank :)
