### ISSUE TITLE
/l not work.

### ISSUE THREAD

**Issue by molor** [Xephi/AuthMeReloaded#878]
In latest dev build №1239, /l command doesn't working before player logged in.
It always says "In order to use this command you must be authenticated!". Working only /login command.

Spigot 1.9.4, Config: http://pastebin.com/KVHz0yES

**Comment by tuanjr** [comment]
i Use build 1238 on 1.9.2, /l work fine :)

**Comment by DNx5** [comment]
looks like another plugin overriding /l command

**Comment by molor** [comment]
hmm. My plugins: AutoSaveWorld, dynmap, PermissionsEx, goBrush, ProtocolLib, SkinsRestorer, SkinsRestorer, WorldBorder, WorldEdit, WorldGuard. And this problem appeared suddenly, by itself..

> looks like another plugin overriding /l command

But I get an error message from AuthMe, not from any other plugin.
And, as I already wrote, after login with command /login, /l works fine.

**Comment by molor** [comment]
I understand the reason. Yes, it was indeed another plugin. Blame the plugin WorldEdit.

If in its configuration file change the "no-double-slash" to "false", /l command stops working. This is strange..

**Comment by sgdc3** [comment]
Idk if this is caused by our command handler or by the we one :/ This needs omvestigation....

**Comment by Twonox** [comment]
We can use /l through command.yml to bypass WE command handling.

If we put:

> l:
> - authme:login $1-

But /authme: commands don't works.

**Comment by ljacqu** [comment]
Just using `login` should work; unless there's a conflict with that command too of course, but unlikely to happen
