### ISSUE TITLE
Task 75 Loop

### ISSUE THREAD

**Issue by Eisenbahn** [Xephi/AuthMeReloaded#882]
http://pastebin.com/7TVj18ZF

Log files has 200Mb
It just loops this #75

Cauldron
Java7

**Comment by Eisenbahn** [comment]
Using the Last Build 1239

**Comment by sgdc3** [comment]
Are you using the legacy jar?

**Comment by Eisenbahn** [comment]
Yesh, i am. Should i use another? Im using cauldron (1.7.10)

**Comment by sgdc3** [comment]
@Eisenbahn Should have been fixed ;)

**Comment by Eisenbahn** [comment]
1240+ ?

**Comment by sgdc3** [comment]
1242 ;)

**Comment by Eisenbahn** [comment]
Ye, been using for few min and seems alright :)

**Comment by sgdc3** [comment]
Fine ;) Thank you for the report!
