### ISSUE TITLE
You logged in from another location ??

### ISSUE THREAD

**Issue by jomjonejame** [Xephi/AuthMeReloaded#883]
# Help me please !!

MC 1.8 ( spigot )
Authme last version

### Some players can't joined in server.

<a href='https://postimg.org/image/s9js908cn/' target='_blank'><img src='https://s31.postimg.org/ddl91ewy3/aaa.jpg' border='0' alt='aaa'/></a>

### When a player is trying to game

<a href='https://postimg.org/image/qwhez0wwn/' target='_blank'><img src='https://s31.postimg.org/cq1o3sm1n/Untitled_1.jpg' border='0' alt='Untitled-1'/></a>
The view from the player within the game.

**Comment by molor** [comment]
Can confirm on my 1.8.8 spigot server.

**Comment by ljacqu** [comment]
So this is when a player is online, and then someone else joins with the same name? Or does "you logged in from another location" happen at the beginning when someone wants to join?

**Comment by molor** [comment]
> So this is when a player is online, and then someone else joins with the same name?

Yes.

**Comment by ljacqu** [comment]
Then this has been fixed with build 1250 or above (see #851). We'd be interested in hearing back if it's been fixed for you :)

**Comment by sgdc3** [comment]
@molor @jomjonejame

**Comment by sgdc3** [comment]
Closing as this is the same issue

**Comment by ljacqu** [comment]
Since this is quite a big one, would be nice to give the reporters the opportunity to give feedback. But ok.

**Comment by sgdc3** [comment]
@ljacqu reporter should also check if there is already a report for the issue before posting xD
