### ISSUE TITLE
Add a pom profile to compile against Bukkit

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#884]
We currently have Spigot as server dependency and I'd like to add a profile in the pom to use CraftBukkit instead. 
This allows us to run unit tests against CraftBukkit e.g. before a release and to make sure we didn't unknowingly use a Spigot-only type.

**Comment by sgdc3** [comment]
Ok ;)

**Comment by ljacqu** [comment]
Excellent, thank you very much! This is a great addition.
