### ISSUE TITLE
Purge: handle entries with lastlogin = 0

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#886]
We might have entries in the DB where the lastlogin timestampis set to 0. This is an issue with purging as 0 essentially means we don't have any lastlogin info. 

I could imagine the following solution:
- When a user does /authme purge, ask for confirmation whether entries with 0 as lastlogin should be included (should we query the DB whether there are such entries?)
- Automatic purge simply ignores those entries

**Comment by ljacqu** [comment]
Brought to our attention by @FabioZumbi12

**Comment by ljacqu** [comment]
@sgdc3 You know, if we ever decide to extract the command handling stuff, what would be really cool here is some sort of state so when someone does /purge 15, they get asked "include entries with 0?" and they just do like /purge yes or /purge no. Overkill for this one here, but in the big picture maybe worth the additional dev time

**Comment by sgdc3** [comment]
How to handle autopurge then?

**Comment by ljacqu** [comment]
I'd suggest to make auto purge ignore entries with 0. As we know, there should actually never be any entries with lastlogin = 0, so if someone has some (because of our previous bugs) and wants to get rid of them, he would need to run purge manually once and it should remove all entries with lastlogin = 0.

**Comment by ljacqu** [comment]
@sgdc3 @games647 How do we best ask the player if lastlogin=0 entries should be included or not? I can think of two ways:

*Additional param*: Player can do `/authme purge 40` or, I don't know, some kind of second argument, like `/authme purge 40 all` to include 0 entries? (I don't know)

*Subsequent question*: Player does `/authme purge 40` and is then asked whether such entries should be included. Player can answer with `/authme purge yes` or `/authme purge no` (open for other suggestions)

**Comment by games647** [comment]
I'm a friend of additional parm option. It's easier to implement and can be used directly.

**Comment by ljacqu** [comment]
Thanks @games647, I did it with an additional param. Either `/authme purge 40` or `/authme purge 40 all`. If player does anything else like `/authme purge 40 test` the command returns an error and stops.
If you or @FabioZumbi12 have any suggestions or remarks, please let me know.
