### ISSUE TITLE
unlogged user using commands

### ISSUE THREAD

**Issue by ReaperAngels** [Xephi/AuthMeReloaded#888]
As per chat. Guy came on, said we have a security hole. Then proceeded to come online as my alt (OP) and wandering through the servers as he pleases. Even going as far as using /msg, /server, and /g (global.
all the info is in the pastebin
http://pastebin.com/RKijyS34

This scared me ever so slightly. He should not be able to do all that. At all. As per Gabriele's instructions, I will use the latest one as of now. 
Spigot 1.10 and bungee of course
Plugins:
AuthMe, BungeeTabListPlus, ChatControl, ChestShop, ClearLag, CoreProtect, EnjinMinecraftPlugin, Essentials, EssentialsProtect, EssentialsSpawn, FancyPortals, HideAndCustomPlugins, HolographicDisplays, Multiverse-Core, OnTime, OwnerChat, PermissionsEx, PlugMan, ProtocolLib, SkinsRestorer, Vault, WhatIsIt, WorldEdit, WorldGuard

**Comment by ljacqu** [comment]
> As per Gabriele's instructions, I will use the latest one as of now. 

Does this still happen with the latest dev build? I tested with your config file and didn't have the described issue (but my local test setup has way less plugins, of course...). 

One thing about the allowCommands option, I'm pretty sure it needs to have a starting */* for each command:
```yml
        # Allowed commands for unauthenticated players
        allowCommands: 
        - '/login'
        - '/register'
        - '/l'
        - '/reg'
        - '/email'
        - '/captcha'
```
I mean if it works on your side that's fine. I had to adjust it to be able to register/login.

**Comment by Pijanista** [comment]
What was his IP?
127.0.0.1?

Make sure you have "IPwhitelist" plugin and put in config only bungee IP so they can join from bungee IP.

**Comment by ReaperAngels** [comment]
Thank you for all the comments. I'm curious. I really hope you trying to take the piss out of me, I really do. Because if you are not, then there is not much hope. Bungee is the only server open to the internet. The servers run on localhost. So there is no possible way that anybody can not join through bungee. The config. Generated by your plugin, edited by me. If it doesn't have a "/" infront, I did not remove it. The dev build. I restarted the lobby server so I was certain it loaded the new one. Notice in my config that sessions are off. Yet I could log in without needing to authenticate, in other words, enter my password. So session login with no sessions. You say you could not reproduce it. I could, my co-owner could. But it must be the plugins. Why must it always be so difficult to report a problem? Why do you feel the need to first insult me, then when I get mad, and climb into you, then I am taken seriously? This is a trend I have seen with plugin developers. 

Now. 
![2016-08-07_14 41 07](https://cloud.githubusercontent.com/assets/17657843/17462430/2a9d896c-5cad-11e6-9a1b-8ec29697c90f.png)

That was with the latest dev build. If you take the time you will see I am not logged in. And then I changed servers.
![2016-08-07_14 41 07](https://cloud.githubusercontent.com/assets/17657843/17462442/7b90426a-5cad-11e6-9081-e3d12dee362b.png)
![2016-08-07_14 41 17](https://cloud.githubusercontent.com/assets/17657843/17462444/85a28920-5cad-11e6-873b-6525284e0989.png)
Still not logged in.

There is your proof that it can be done. Even on the latest dev build.

**Comment by ljacqu** [comment]
Please tell us how we insulted you.

**Comment by ReaperAngels** [comment]
Pijanista commented an hour ago 
What was his IP?
127.0.0.1?

Make sure you have "IPwhitelist" plugin and put in config only bungee IP so they can join from bungee IP.
Implying that this is all my fault. And you. basically saying that it's the plugins. 

And it starts. Again.

**Comment by ljacqu** [comment]
But... I literally couldn't reproduce it. I didn't say it's your fault. It's interesting for me to post my finding because it means that this is a bug that either happens in conjunction with other plugins, or it's a version-sensitive occurrence.

That's the first step in bug fixing: determining _why_ this is happening so we know _where_ we can fix it. Sometimes it's not obvious, not even for us. If you take offense in that I think you're imagining the bug fixing process to be a little more straightforward than it is most of the time.

I'm sorry you've had bad experiences with plugin developers—maybe if you escalate things a little less fast you might have better exchanges with them. For example now we're spending time talking about this instead of gathering more information about the bug.

**Comment by ReaperAngels** [comment]
I could say something to that.... I formally invite you to join my server. mc.tiganetworks.co.za Let the debug start.

**Comment by ljacqu** [comment]
I joined as sflotzdru

**Comment by ljacqu** [comment]
@ReaperAngels kindly showed me around and we had a look at the issue. Nothing in the permissions config allows `/msg` for non-logged in players. This basically narrows it down only to Bungeecord, which I can't do... (hi @sgdc3 and @Gnat008 :wink:)
Maybe also to specify (this was unclear to me before going on the server), unregistered users can't chat or perform commands but once you're registered and not logged in, you can do /msg just fine.

**Comment by ReaperAngels** [comment]
Bungee config as requested
[bungee.txt](https://github.com/Xephi/AuthMeReloaded/files/405552/bungee.txt)

**Comment by sgdc3** [comment]
Ok, the issue is really simple. AuthMe can't block bungee commands and can't remove bungee permissions

**Comment by sgdc3** [comment]
@ljacqu

**Comment by Twonox** [comment]
You can use AuthmeBridge to block the bungeecord commands during login/register.

**Comment by ReaperAngels** [comment]
Hi Guys! You can close this, using authme bridge sorted the problem. Thanks for all the help! I do have another issue now, but it's forge (sponge) related. I'd appreciate an email please?
