### ISSUE TITLE
Auth Me Cracker

### ISSUE THREAD

**Issue by callthenerdy** [Xephi/AuthMeReloaded#892]
Hi, I've recently started having problems with hackers. They use a hack which cracks the Auth Me passwords and gives them access to the admin accounts. This is the client they use to do it: https://www.wurst-client.tk/wiki/Mods/Force_OP_(AuthMeCracker)/

I hope you work out something and give us a release that can block this client. Thank you.

**Comment by Twonox** [comment]
The hackers hacked you ?
It works ?

**Comment by sgdc3** [comment]
@callthenerdy Please enable the captcha and kickOnWrongPassword features and use stronger passwords...

**Comment by ljacqu** [comment]
See also #401 :)
