### ISSUE TITLE
delayJoinMessage

### ISSUE THREAD

**Issue by Twonox** [Xephi/AuthMeReloaded#894]
`delayJoinMessage: true` doesn't work
But `removeUnloggedLeaveMessage: true` works

**Comment by sgdc3** [comment]
Please explain the issue :/

**Comment by Twonox** [comment]
When a player join the server there is directly join message and no after /login, but `delayJoinMessage` is set `true`

**Comment by sgdc3** [comment]
@Twonox Could you post your Essentials config please?

**Comment by Twonox** [comment]
`allow-silent-join-quit: true`
It's the config that interest you ?

**Comment by sgdc3** [comment]
nope join and leave messages

**Comment by Twonox** [comment]
> You can set a custom join message here, set to "none" to disable.
> You may use color codes, use {USERNAME} the player's name or {PLAYER} for the player's displayname.

`custom-join-message: "&7[&a+&7] &2{USERNAME}"`

> You can set a custom quit message here, set to "none" to disable.
> You may use color codes, use {USERNAME} the player's name or {PLAYER} for the player's displayname.

`custom-quit-message: "&7[&c-&7] &4{USERNAME}"`

**Comment by sgdc3** [comment]
That's the issue, essentials is bossy and don't allow us to remove the join message, you need to use another plugin to change the join and leave messages. Now put "none" to both messages

**Comment by Twonox** [comment]
;(
