### ISSUE TITLE
Kick player if cannot connect to bungee server

### ISSUE THREAD

**Issue by orkun1675** [Xephi/AuthMeReloaded#895]
There is an option to send a player to a bungee server after login in the config. It would be nice if we could kick the player with a message if this server is offline. Not a priority but would be a nice enhancement.

New Config Options
`Hooks.kickIfCannotSend = true`
New Messages YML
`cannot_connect_to_server: 'The main server is currently down right now. Try again later.'`

The server could be pinged (using a socket and sending this packet http://wiki.vg/Protocol#Legacy_Server_List_Ping) to understand if it is online or not. If it is online we issue the Plugin Message to Connect to player to the server, otherwise we kick the player.

Idk if it would be optimal to ping the server every time a player logins, but the only other option I can think about is to check if the player is still online after login and kick them if they are (cause they were not able to connect to the other server).

I am willing to open an pull request if you think this is the way to go.

**Comment by Twonox** [comment]
Mhmm, it seems be good idea.

**Comment by sgdc3** [comment]
Too complex, if you want, you can write your own plugin that move the player after the authentication using our API.
