### ISSUE TITLE
AntiBot configuration cannot be changed with /authme reload

### ISSUE THREAD

**Issue by Twonox** [Xephi/AuthMeReloaded#896]
When we change value of `enableAntiBot` then reload authme, the value isn't applied. We must reboot the server (or reload?).

`antiBotSensibility` does not work, we can't change sensibility.

**Comment by ljacqu** [comment]
@Twonox implemented by sgdc3 in 88ce493438247b9aaa68673c1fffc8d021f63bf1, please verify

**Comment by Twonox** [comment]
It's hard to explain in English, I will explain it in French, sorry Sgdc.

J'ai effectué des test et ça ne fonctionne pas très bien. J'ai rencontré plusieurs bug, et je ne peux pas tous les citer un-par-un. Tout ce que je peux te dire, c'est qu'au début de mes test ça avait l'air de fonctionner sauf pour `antiBotSensibility` qui déconnait lorsque je changeais sa valeur, et à l'instant où j'écris ce message l'antibot ne fonctionne plus du tout. J'ai beau faire `/authme reload`, `/authme (switch/toggle)antibot on`, ou même redémarrer le serveur, il ne s'active pas alors que j'ai `enableAntiBot: true`.

J'en ai profité pour réfléchir à un système de configuration un peu plus différent qui pourrai remplacer celui actuel si jamais vous n'arrivez pas à résoudre les soucis.
Je m'explique:
Vous remplacez `enableAntiBot` par `antiBotMod` qui prendra la valeur ON, OFF ou AUTO. Cette valeur sera modifiable depuis le serveur avec la commande` /authme antibot ON/OFF/AUTO`, en enlevant les autres commandes.
Comme les noms l'indiquent, ON sera pour garder constamment l'antibot actif, OFF pour qu'il soit constamment désactivé, et AUTO qui prendra en compte la configuration `antiBotSensibility` et `antiBotDuration`.

**Comment by sgdc3** [comment]
@Twonox Could you try again?

**Comment by ljacqu** [comment]
Quick translation of @Twonox's message is that Antibot doesn't seem to work well upon reloading.

It's important to know that Antibot takes 90 seconds before it actually starts; you can check this with `/authme antibot` (it shows DISABLED first and after that LISTENING). This should probably be configurable.

@sgdc3 fixed another bug with the commit just above, so if we could ask you to verify again @Twonox with that in mind. I create an issue for configuring the waiting period on startup in the meantime.

**Comment by Twonox** [comment]
Okay I will do some test tomorrow.
The enabling delay is probably the cause of the negatives result, know I understand why the antibot doesn't work always.

**Comment by Twonox** [comment]
It works perfectly, thanks ! :)
