### ISSUE TITLE
format code: &n won't work in message_en.yml

### ISSUE THREAD

**Issue by tuanjr** [Xephi/AuthMeReloaded#898]
when use &n code in message_en.yml, it make message to new line and reset message color and format to default. But §n work fine.

**Comment by ljacqu** [comment]
That's correct, we replace `&n` in the code to a new line. We should remove it.

**Comment by Twonox** [comment]
Change it to \n

**Comment by sgdc3** [comment]
The actual Message class doesn't make sense! We have many methods doing the same thing in different ways

**Comment by sgdc3** [comment]
Ok we need to use something like %nl%

**Comment by Twonox** [comment]
%nl% and &n works ty

**Comment by tuanjr** [comment]
@sgdc3 current, i use \n to enter new line in messages_en.yml, but if you use \n, you must use "", not ''
example:   "this is line 1 \n this is line 2"

**Comment by sgdc3** [comment]
\n is not the right way, please use %nl%
