### ISSUE TITLE
(Seemingly) deadlock with AuthMe 5.2-BETA3-b1134

### ISSUE THREAD

**Issue by TigerHix** [Xephi/AuthMeReloaded#901]
Log: http://pastebin.com/QF4rgtDr

Quite lot of players (not spambots, 2-3 players/second) joined the server before the server crashed.

**Comment by sgdc3** [comment]
@TigerHix Beta3 is outdated, please update to latest dev build and tell us if it happens again.

**Comment by ljacqu** [comment]
You can find the latest dev builds at http://ci.xephi.fr/job/AuthMeReloaded/
