### ISSUE TITLE
Permissions problem?

### ISSUE THREAD

**Issue by MarkusCZ** [Xephi/AuthMeReloaded#903]
Okay so i'm a admin on a server... default rank for players that join is 'Starter' but when i de-op and change my pex to starter i cannot do /register,/login, anything... it gives me You dont have permissions for this!. but when i look to my PeX file in permissions.ylm i have authme.player.register in it idk why it doesnt work

**Comment by Twonox** [comment]
What is your Authme version ?

**Comment by MarkusCZ** [comment]
5.2-BETA3-b1134

**Comment by Twonox** [comment]
Could you test latest build please? Normally it's fixed.
http://ci.xephi.fr/job/AuthMeReloaded/

If you have 1.7 server use AuthMe-5.2-SNAPSHOT-legacy.jar, otherwise AuthMe-5.2-SNAPSHOT-spigot.jar

If you have problem to walk, please see #890 https://github.com/Xephi/AuthMeReloaded/issues/890#issuecomment-239596517

**Comment by MarkusCZ** [comment]
Yea but i dont have a problem with a version i have a problem with permission as a admin i can /register login.... but as a starting player i cannot do /register it gives me You dont have permission for that.... even when the authme.* permission is in my PEX file

**Comment by Twonox** [comment]
Permissions problem is fixed in latest dev build. If you use it your problem will be fixed.

**Comment by MarkusCZ** [comment]
Okay i donwloaded the latest build switched to starter (/pex user MarkusCZLP group set Starter) and i tried to register what i get is You dont have permission for that!... again.. (authme.register is in PEX folder)

**Comment by sgdc3** [comment]
whoops

**Comment by Twonox** [comment]
#872

**Comment by sgdc3** [comment]
@MarkusCZ this is #872

**Comment by MarkusCZ** [comment]
Where do i find plugin.yml :o

**Comment by Twonox** [comment]
There is no problem with GroupManager.

**Comment by ljacqu** [comment]
@MarkusCZ, `authme.register` is an old permission node, it has been moved to `authme.player.register`. You can find an up-to-date list of permissions at https://github.com/AuthMe/AuthMeReloaded/blob/master/docs/permission_nodes.md

**Comment by MarkusCZ** [comment]
I  think i gonna make a short video showing my problem :)

**Comment by MarkusCZ** [comment]
@ljacq  Hello, Thank you so much i found out that my permissions was only authme.(permission)... i fixed it now i gonna try it :)

**Comment by ljacqu** [comment]
Excellent, thanks for the update, @MarkusCZ! Please let us know if this issue can be closed.

**Comment by MarkusCZ** [comment]
FIXED! Thank you guys soo much... you can now close this issue i hope it will help somebody else. :)

**Comment by ljacqu** [comment]
Thanks for the feedback :) Glad it could be solved like this.

**Comment by Registellia** [comment]
I have CB 1.5.2 R1.0, and a Dev gave me the plugin.. But I used these permission nodes up there and it doesn't work :(
