### ISSUE TITLE
Antibot message

### ISSUE THREAD

**Issue by rErEaT** [Xephi/AuthMeReloaded#904]
Can you add a permission to view the antibot's messages?
I dont want to show it for everyone

**Comment by Twonox** [comment]
All players can see ?? :O

**Comment by rErEaT** [comment]
yes

**Comment by Twonox** [comment]
So it's good idea

**Comment by rErEaT** [comment]
And btw the other accounts should be messaged only to the staff i think :) or a command to see the players' other accounts

**Comment by Twonox** [comment]
@sgdc3 When can you do this please ?

**Comment by TheIntelloBox** [comment]
Please ?
