### ISSUE TITLE
Account stealing...

### ISSUE THREAD

**Issue by SliderKP** [Xephi/AuthMeReloaded#906]
a user of Russian origin, is constantly entering my server , accessing my account and destroying my servers , I did not find errors and as it does, but it makes sense to be using the Authme and entering with my own ...

need an urgent solution ...

versions:
Spigot : 1.8.8
Authme : 5.2 build 1287
AuthmeBungee : 1.6.2

**Comment by ljacqu** [comment]
And how is he getting into your account? Do you have a log you could share? Is he guessing your password...?

**Comment by SliderKP** [comment]
that its impossible i'm from argentina, and the stupid user It is possibly a Russian, i change my password and continues joining in, i add a plugin to prevent op users, and he join to my account to destroy my servers, 

How is this possible?

my logs are really very large , if you want I can give you anything but is a needle in a haystack

**Comment by SliderKP** [comment]
also as it is a 5 servers connected by bungee , nose if maybe some bug AuthmeBungee advantage that autologin on a server and change the password to my account and then you can navigate freely.

**Comment by SliderKP** [comment]
first the " hacker" needs to be a op has to steal it , but can not do anything , one of the servers that before he was destroying , remove all op , and could not destroy it.

**Comment by ljacqu** [comment]
OK well the more information you can provide to us the better we can analyze what you've experienced. Surely it would possible to find log excerpts where that Russian joins in your name. What's also unclear to me is if this only happened on one of those connected servers.

**Comment by Twonox** [comment]
@SliderKP Do you have Autme in all servers ? If he have the IP of one of your server without authme he can join with your account without /login.

**Comment by SliderKP** [comment]
yes i use authme with authmebungee in all my servers, and yes i use CoreProtect in one server.

**Comment by Twonox** [comment]
It's possible to see password trough CoreProtect.
You can disable this in config.yml. I wouldn't say how see exactly here. I can give my skype for more info.

**Comment by SliderKP** [comment]
ok u can add me to skype?  >>    OverSliderKP

**Comment by ljacqu** [comment]
@SliderKP @Twonox, has this been solved or is there something open on our side that we can do?

**Comment by Twonox** [comment]
I've tried to help him but he have closed his server :/

**Comment by SliderKP** [comment]
Sorry for the delay , I closed my server temporarily , I found the problem , it was not authme or bungee authme , I prefer not to share the bug anyway , greetings and thanks for your attention !

**Comment by sgdc3** [comment]
@SliderKP Thank you ;)
