### ISSUE TITLE
[Grave] Fake players not working with AuthMe

### ISSUE THREAD

**Issue by Eufranio** [Xephi/AuthMeReloaded#908]
My Server fake players stop working since i added AuthMe. Everything works fine, except the fake players. I run a modded server, fake players are a essential part of mods, we can't run without them. Could you take a look in what is happening?
I'm running a Thermos server, with forge 1614 and that AuthMe Reloaded: https://www.spigotmc.org/resources/authme-reloaded.6269/update?update=98336

**Comment by sgdc3** [comment]
do you know the name of the fake players?

**Comment by Eufranio** [comment]
I saw this: https://github.com/Xephi/AuthMeReloaded/issues/219 and fixed.
But would be cool a option to debug the server fake players
