### ISSUE TITLE
Can't convert from SQLite to MySQL

### ISSUE THREAD

**Issue by Eufranio** [Xephi/AuthMeReloaded#909]
I've configured the MySQL in the config, and when i type `/authme convert sqlitetosql` i get that message:
```
[23:39:08 INFO]: [AuthMe] Successfully converted from sqlitetosql
[23:39:08 INFO]: Please configure your mySQL connection and re-run this command
```
I really don't know what do, i've already configured MySQL...

**Comment by sgdc3** [comment]
You need to change the backend to MYSQL

**Comment by Eufranio** [comment]
I changed!
`    backend: 'mysql'`

**Comment by ljacqu** [comment]
Did you restart after changing the config? `/authme reload` doesn't work to change the database type.

**Comment by Eufranio** [comment]
Yeah, restarted and is working now, thank you! :smile:
