### ISSUE TITLE
Web Integration

### ISSUE THREAD

**Issue by Eufranio** [Xephi/AuthMeReloaded#911]
Just a quick asking, is there a web system/integration ready for use? Like plug-and-play? I am thinking in switch authentication for web, but i dont have any knowledge.

**Comment by ljacqu** [comment]
Do you mean like a web interface to talk with the AuthMe database? We don't have an out of the box product but https://github.com/AuthMe/AuthMeReloaded/tree/master/samples/website_integration might offer a basic foundation to go about it :wink:

**Comment by Eufranio** [comment]
I mean a ready website for login/registeration, download and install, but thank you by the help xD
