### ISSUE TITLE
AuthMe purge system

### ISSUE THREAD

**Issue by Kixot14** [Xephi/AuthMeReloaded#912]
I very need normal purging system on my server. Did someone testing the purge from AuthMe in latestest builds? It works correctly ??
Particular for **PermissionsEx** (_plugins/PermissionsEx/permissions.yml_) 
and for new **EssentialsX** (_plugins/Essentials/userdata/UUID.yml_)
And for _world/playerdata/UUID.dat_ ??

And tell me please, this **daysBeforeRemovePlayer** timer counted by date ?
Date, when data  will be removed, is [Last login date + daysBeforeRemovePlayer] ??
Or this timer will stopped, if server non active ??

**Comment by sgdc3** [comment]
if a player is inactive for more than X days the playerdata is removed

**Comment by sgdc3** [comment]
If you don't use latest 1.10.2 paper build the purge will fail due to a bug that exist since spigot 1.7.5.

**Comment by Kixot14** [comment]
All purge will fail? Even that purge which responsible for AuthMe accounts ??

**Comment by sgdc3** [comment]
every uuid related purge, so pex and ess would fail

**Comment by sgdc3** [comment]
Authme is using names so it would purge the internal database correctly

**Comment by Kixot14** [comment]
Are you going to fix it ??

**Comment by sgdc3** [comment]
It's a spigot bug, but i can use a workaround.

**Comment by sgdc3** [comment]
Uh i forgot a thing: the bug occurs only if you have bungeecord enabled in the spigot config.

**Comment by sgdc3** [comment]
so let me open anotger issue

**Comment by ljacqu** [comment]
other issue being #914, 
don't mind me, just writing a comment to link the issues
