### ISSUE TITLE
OfflineMode UUID with Bungee workaround

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#914]
I recently found a spigot bug that existed since 1.7.5 that makes the server impossible to calculate offfline uuids when a player is not in game and the bungeecord option is enabled in the spigot configuration. That makes us unable to purge data from other plugins like pex and ess. I sent a PR (already merged) to the papermc project to fix this issue by adding a config option, but every spigot server since 1.7.5 is still affected by this issue. The only way to fix this is to calculate the uuid from this string: "OfflinePlayer:%playername%"

**Comment by sgdc3** [comment]
One issue: the uuid calculation is case sensitive, so we need to use the RealName,  not the lowercase one

**Comment by sgdc3** [comment]
this is difficult as we use offlineplayers instead of uuids

**Comment by sgdc3** [comment]
We need to drop the usage of offlineplayer

**Comment by Kixot14** [comment]
"We need to drop the usage of offlineplayer"

what do you mean? U wanna implement UUID feature to AuthMe ??

**Comment by sgdc3** [comment]
We already use uuids for example with the purge process

**Comment by ljacqu** [comment]
@sgdc3 What's the outlook on this?

**Comment by sgdc3** [comment]
IDK, i created a paper 1.8.8 fork with the offline uuid fix, 1.10 already includes the fix, i think we can close this.
