### ISSUE TITLE
keepCollisionsDisabled feature

### ISSUE THREAD

**Issue by Kixot14** [Xephi/AuthMeReloaded#915]
This **keepCollisionsDisabled** feature prevent player from pushing another player when he logged and unlogged ??
Maybe you can extend this feature to prevent players from collision with boat entity for fix this bug with elytra launcher ??  https://www.youtube.com/watch?v=o56VCNISYI8

**Comment by sgdc3** [comment]
We can't disable collisions server side due to a Minecraft bug, the only solution is to use plugins like noCollisions and set an allowMovement radius on authme

**Comment by sgdc3** [comment]
(NoCheatPlus should block elytra launchers)

**Comment by Kixot14** [comment]
In NCP build 985 not! Players be possible to use this bug and fly sometime, and then NPC kick players and it was impossible to relog due to have huge speed.

**Comment by sgdc3** [comment]
Always use latest build for 1.10: http://ci.md-5.net/job/NoCheatPlus/
