### ISSUE TITLE
AuthMe permission check

### ISSUE THREAD

**Issue by Kixot14** [Xephi/AuthMeReloaded#917]
For what need '**permission: EnablePermissionCheck**' ?? Even if this set to false, AuthMe still check for permission. (With Vault, or without Vault... Anyway)

P.S: Message '&4**You don't have permission to use this command!**' is missed in local file

**Comment by ljacqu** [comment]
In theory AuthMe allows associating a permission group with a player based on his status (unregistered, not logged in, logged in); this is the setting that enables this feature. Only this is a feature that has multiple issues; it's applied inconsistently and the group names aren't configurable. #761 is the task that addresses these issues.
