### ISSUE TITLE
Enhance the AntiBot service

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#92]
@Maxetto Se vuoi potresti migliorarlo te, ho visto che hai esperienza a riguardo xD

**Comment by Xephi** [comment]
But idk what can I add or change :')

**Comment by Maxetto** [comment]
@sgdc3 I told you, it's almost impossible. AntiJoinBot and AuthMe use 2 completely different ways to block Bots (1st with Proxy API Check, 2nd with Whitelist).
The only thing I can (try to) do is an API.
Right now, if they're using both plugins, it's fine, as Proxied Bots will be blocked by AJB and not counted to the AntiBot of AuthMe and Unproxied Bots will be counted and blocked by Authme's AntiBot.

It works perfecly on my server.

**Comment by Xephi** [comment]
I will check to add something like other AntiBot does to detect and attack

**Comment by sgdc3** [comment]
Useless
