### ISSUE TITLE
Remove help message

### ISSUE THREAD

**Issue by Kixot14** [Xephi/AuthMeReloaded#920]
Can you add option to config, or permissions (like **- -AuthMe.player.action.help**) for be possible to remove this messages http://prnt.sc/cb9kyl

p.s. this msgs, for **/email**, **/login**, **/changepassword**, **/unregister** and **/captcha** syntax is missed in messages.yml,
but not for **/register** and **/unregister**.  They are related with **usage_reg** and **usage_unreg** msg.

**Comment by ljacqu** [comment]
PS part is #293, as for the permissions, what are you trying to achieve? Hide certain help sections from _certain_ players, or hide some help sections from everyone?

**Comment by Kixot14** [comment]
I just try to hide help messages from everyone, but looks like now it's impossible
(sheduled in 5.3?  © #293)

**Comment by ljacqu** [comment]
Indeed, @Kixot14, this is currently not possible.
