### ISSUE TITLE
Email recovery system

### ISSUE THREAD

**Issue by Kixot14** [Xephi/AuthMeReloaded#921]
I dont know what i do wrong, but i can't set up the email recovery system. I set data of my actual email, and  jonin the server from another minecraft account, then add another actual mail and try to recover pass, but after 5 sec had this error:
_[10:17:16 WARN]: [AuthMe] Failed to send a mail to [qwerty@gmail.com]: [Email Exception]: Sending the email to the following server failed : smtp.gmail.com:465_
P.S. Password of player is changing after recovery try, but cant find out him, cause mail sanding failed.

Maybe problem on the Google side? Maybe need to enable this 'smtp' feature in option of the gmail account or what??

**AuthMe build 1292**

P.S. Add command for players, that be possible to look at their added email (/email myemail)

**Comment by ljacqu** [comment]
Did you allow "access for less secure apps" in Gmail? http://stackoverflow.com/a/27815241

**Comment by sgdc3** [comment]
@Kixot14

**Comment by Kixot14** [comment]
w8 a bit

**Comment by Kixot14** [comment]
Looks like disable due to i have two-steps verification =)

Now switch off and try again...

**Comment by Kixot14** [comment]
Yes, all works fine!
That is cool feature, thank! =)

**Comment by ljacqu** [comment]
Glad it could be sorted! Thanks for the feedback

**Comment by DNx5** [comment]
wait, the password has changed without confirmation?

**Comment by Kixot14** [comment]
"_wait, the password has changed without confirmation?_"

Yes, i type /email recovery <e-mail>,
then after 5-10 sec get this WARN, about failed to send e-mail.
But my old pwd becomes unactual after this.

**Comment by sgdc3** [comment]
@DNx5 damn :/

**Comment by sgdc3** [comment]
Reopening this until we decide if we should open another issue

**Comment by ljacqu** [comment]
I think this is OK to close as we have #472, which will tackle this problem. What do you think, @sgdc3?

**Comment by ljacqu** [comment]
Oh, I misread, I see, email can't be sent but password is still changed of course. I still think it will be solved with #472.
