### ISSUE TITLE
Cmd for players be able to link their IP with nickname

### ISSUE THREAD

**Issue by Kixot14** [Xephi/AuthMeReloaded#924]
I know, AuthMe have this feature in config, but maybe better will be if players can do this for himself? ...By using toggle command /linkIP [-r] on|off  -- this command linked _current_ IP of player to his nickname. With -r -- linked IP of registration.

But first:
Player must add his E-mail, and...

With linkIP feature **necessarily** need add reverse command:
**/email recoveryIP** -- this sent list with secret code to player e-mail.
and /**confirmDelink <secretCode>** -- unlogged player must type this command to switch off linkIP feature.

**Comment by sgdc3** [comment]
@ljacqu Am i wrong or you already opened an issue for that in the past? :/

**Comment by ljacqu** [comment]
@sgdc3 Good call—this is #659 :)
