### ISSUE TITLE
UA msg.yml

### ISSUE THREAD

**Issue by Kixot14** [Xephi/AuthMeReloaded#925]
Hi! I translated all messages for AuthMe into Ukrainian.
It would be great, if you add this file to your messages collection =))
http://pastebin.com/HVf8Y8xZ

It is 99% correct,
i checked him many times!

**Comment by Kixot14** [comment]
Lol. U have labels for everything ?)

**Comment by sgdc3** [comment]
@Kixot14 Yep xD

**Comment by ljacqu** [comment]
Reopened: Ukrainian already exists as messages_uk.yml. That is the correct abbreviation for the language so I'd suggest to rename the _ua.yml to _uk.yml.

**Comment by sgdc3** [comment]
Whoops xD

**Comment by ljacqu** [comment]
Cheers :)

**Comment by Kixot14** [comment]
No, you are not right. Ukrainian country code is UA, not UK!
proof http://prnt.sc/cby5h1
UK is just a abbreviation of United Kingdom.

It's first. And 2-nd, my translation slightly fresher and more correct. But it's up to you =)

**Comment by Kixot14** [comment]
Another proof from EN Wiki http://prnt.sc/cbyab8

**Comment by ljacqu** [comment]
We took your translation, thank you for that. 

Since the file is about the Ukrainian language, we take the abbreviation of the language, which is in fact `uk` – https://en.wikipedia.org/wiki/ISO_639-1

**Comment by Kixot14** [comment]
false

**Comment by Kixot14** [comment]
ISO 639-1:**2002**

This codes not up to date.

**Comment by ljacqu** [comment]
We use language codes. You keep on talking about _country_ codes but we're dealing with languages here. Similar to your "[proof from the EN Wiki](https://github.com/Xephi/AuthMeReloaded/issues/925#issuecomment-243333759)," why don't you go visit the page for the Ukrainian language and see what code is listed there?
https://en.wikipedia.org/wiki/Ukrainian_language

**Comment by ljacqu** [comment]
While visiting the Ukrainian Wiki page about the Ukrainian language to see if it lists `uk` as abbreviation (it does), I noticed the URL:  [https://**uk**.wikipedia.org/wiki/Українська_мова](https://uk.wikipedia.org/wiki/%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%B0_%D0%BC%D0%BE%D0%B2%D0%B0) :wink: Are we done now?

**Comment by Kixot14** [comment]
Perhaps... Perhaps.

But if someone man from Ukraine download AuthMe and will choose ukrainian language, i think he can't find it, if it will be called as _uk_ . Because _ua_ is more familiar.
