### ISSUE TITLE
[Question] What exactly BungeeCord hook does?

### ISSUE THREAD

**Issue by Eufranio** [Xephi/AuthMeReloaded#926]

**Comment by sgdc3** [comment]
It should sync all the authme instances and reduce the amount of queries to the db, atm it causaes some issues so i'll suggest you to keep it disabled

**Comment by Eufranio** [comment]
Hmmm, okay. These issues happens with AuthMeBridge too? If not i'll use it

**Comment by sgdc3** [comment]
This AuthMeBridge version should work fine: http://ci.xephi.fr/job/AuthMeBridge/

**Comment by Eufranio** [comment]
Thank you! :smile:
