### ISSUE TITLE
Drop flatfile database support.

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#93]
I think we should use SQLite as default.

**Comment by Xephi** [comment]
Need to convert all flat file to sqlite :/ But I agree, flat file is really buggy and performance drop with it :/

**Comment by sgdc3** [comment]
atm we can partially avoid the problem setting the beckend option to sqllite as default, right?

**Comment by Xephi** [comment]
Yep! Nice idea
