### ISSUE TITLE
MySQL to SQLite converter

### ISSUE THREAD

**Issue by Sitmobedaf** [Xephi/AuthMeReloaded#933]
Add MySQL to SQLite convert, please.

**Comment by sgdc3** [comment]
Atm you can usa external tools ;) We'll add this anyway if requested..

**Comment by ljacqu** [comment]
Available in build nr. 1322 and above, <http://ci.xephi.fr/job/AuthMeReloaded/>, as `/authme convert mysqlToSqlite`. Please close if it's OK, otherwise let us know what is open.
