### ISSUE TITLE
Don't send login message instantly.

### ISSUE THREAD

**Issue by molor** [Xephi/AuthMeReloaded#935]
Hello.

Can you add the option to the config file that sends messages "login_msg" and "reg_msg" to player after the number of seconds specified in the "settings.registration.messageInterval", but not immediately after he join the server?

**Comment by ljacqu** [comment]
@molor Out of curiosity, why do you want this?

Whoever implements this - it's important to keep in mind that we re-schedule the message task when someone unregistered runs the /login command. In such a case I'm sure we wouldn't want that delay to take effect.

But what is open is if this delay should also take effect when someone does /unregister? For consistency reasons I would assume so.

Refactoring: `registerMessageTask()` in PlayerDataTaskManager takes a boolean parameter to define whether to show the "please /register" or the "please /login" message. This is not readable code; change it to two separate methods with an obvious name.

**Comment by molor** [comment]
@ljacqu, why do I need it: when joining the server, player is received a few messages that should be read one after the other (motd). But there are times when message from AuthMe sent at the same time as these few messages. It turns out something like this:

> Hello!
> Welcome to this server,
> this is bla bla bla server with
Please, login with the command "/login <password>"
> awesome features!
> Good luck in the game.
> [empty line]

But it would be better if message from AuthMe was sent after [new line].

**Comment by ljacqu** [comment]
Thanks for the explanation @molor! In that case you only want the delay on join, but not on logout/unregister

**Comment by molor** [comment]
@ljacqu, yes, that's what.

**Comment by Twonox** [comment]
It seems that is solved. Login's message is sent 2 seconds after the connection.

**Comment by sgdc3** [comment]
@molor

**Comment by molor** [comment]
> It seems that is solved. Login's message is sent 2 seconds after the connection.

Yes, thanks!
