### ISSUE TITLE
Allow AuthMe to run in sync or async (configurable)

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#937]
Via Gitter with @sgdc3—
Add a configuration that will make AuthMe run synchronously instead of asynchronously.

- See changes in the sync branch for what is affected
- Async scheduling usually runs through the BukkitService -> I would expect we only need a few modifications in there (checking an additional setting)
- Note that _some_ things will still have to be in async (e.g. converters), so we need to create another method in BukkitService for always being in async

**Comment by ljacqu** [comment]
@Sitmobedaf, one open question about this, did you expect code to run in another _sync thread_ or just run the code immediately? Right now we do the latter and it's unclear to me what is better.

**Comment by Sitmobedaf** [comment]
I use 3.1.1 with fixed getOnlinePlayers and single session. I do not care what you do now, sorry.

**Comment by sgdc3** [comment]
@Sitmobedaf Fine, bye.

**Comment by Sitmobedaf** [comment]
Yes, it works synchronously and the load on the server attacks is almost there, it loads the server is less than SkinsRestorer, PermissionsEx, he BukkitServer. Authorization plugin does not have to be a monster - this is the direction in which you move, and you piatetes subdue him (asynchronous mode). In addition, you can not operate some of the functions of such a purge. But maybe I will come back to you. With you it was nice to talk to, good luck!
