### ISSUE TITLE
AntiBot: find better implementation for users in time span

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#938]
The AntiBot class checks that in the last 5 seconds not more than x players have joined. This is being solved with threads, so a task with a wait time is scheduled to decrease the counter again. Find a better way of doing this without scheduling threads.

**Comment by Platinteufel** [comment]
With the current implementation AntiBot can also enable after a server restart, when all players try to rejoin again. Maybe there should be an option that AntiBot only triggers on unregistered players? I think you don't have to check regular players.
If I get a botattack the probabilty that it's not a unknown player is very low.

**Comment by ljacqu** [comment]
@Platinteufel this is the intended behavior of AntiBot (only fire if X *unregistered* players are observed). Please open another issue if this is not the case
