### ISSUE TITLE
Need help with API.

### ISSUE THREAD

**Issue by Dimatert9** [Xephi/AuthMeReloaded#942]
Hello! How i can get ALL registered users?

**Comment by sgdc3** [comment]
https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/datasource/MySQL.java#L769

**Comment by sgdc3** [comment]
Auths:
https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/datasource/MySQL.java#L799

**Comment by Dimatert9** [comment]
And how i can get "getAllAuths()" from api?
This method is not static, and i cant find this metod in NewApi or in API

**Comment by sgdc3** [comment]
@ljacqu Now with dependency injection is impossible to access non-api methods, this is an issue :/

**Comment by ljacqu** [comment]
True, but at the same time it's the API's job to offer the necessary functions to interact with AuthMe. We don't want to expose the other classes to the outside.

In other words, @Dimatert9, we'll add it to the API class. :)

**Comment by sgdc3** [comment]
>We don't want to expose the other classes to the outside.
Yeah but 99% of the stuff was done using non api methods xD

**Comment by ljacqu** [comment]
Correct, but I would like it to be easily recognizable what is part of the API and what not. And most services shouldn't be part of that so we can move and modify them as AuthMe evolves. 
The API on the other hand is a _contract_ with the outside world we need to keep. So I'd suggest to add to the API as requests come in. We just need to add stuff to the API carefully. 

If we want to pass some services out I would suggest maybe a marker interface? A class that implements this interface can be retrieved from some `<T extends PublicService> T getService(Class<T>)` method on a best effort basis. But that's opening a dangerous door :smile:

**Comment by ljacqu** [comment]
Essentials has a nice way – they have interfaces in an api package and their regular classes implement those. If a plugin developer only programs against the interface his plugin remains stable even if we shove things around internally.

**Comment by sgdc3** [comment]
@ljacqu The issue is that authme was built without an api xD

**Comment by sgdc3** [comment]
@Dimatert9 now the api has 2 new methods ;)

**Comment by Dimatert9** [comment]
Thanks.
Can you add method "unregister(String name)"?

**Comment by sgdc3** [comment]
@Dimatert9 Could you open a new ticket please? :)
