### ISSUE TITLE
Add stuff to the public API

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#943]
Since we use injection developers are unable to hook into out code except the API, we need to provide some new methods like getRegisteredPlayers()

**Comment by sgdc3** [comment]
Still needs unit test, working on it

**Comment by sgdc3** [comment]
@ljacqu This still need unit test, could you take a quick look when you're back? :)

**Comment by ljacqu** [comment]
@sgdc3 Done—thanks for the hint :wink:

**Comment by sgdc3** [comment]
Ok, forgot to close this ;)
