### ISSUE TITLE
Difference about "Realname" and "Username"

### ISSUE THREAD

**Issue by G-monitor** [Xephi/AuthMeReloaded#945]
What's difference of realname and username? (in mysql column)
Is username = lower case of username? (and username = the original case of player name?)
I want register from a custom website (made by my self).

**Comment by ljacqu** [comment]
You're right, username is all lowercase and realname is the name in proper casing. We could specify this a bit better in the config comments.

**Comment by G-monitor** [comment]
Ok,thanks!
