### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Eisenbahn** [Xephi/AuthMeReloaded#946]
Keep Java 7 :D

Some users can't update to 8 due to (Specially) certain Mods or plugins!

[]'s !

**Comment by sgdc3** [comment]
Impoesible, Java 8 support any Java 7 plugin or mod

**Comment by Eisenbahn** [comment]
This is weird. I had issues with some plugins/mods earliear. But ok, ill try it anyway.

[]'s

**Comment by ljacqu** [comment]
I'd guess a plugin compiled in Java 8 won't work on a Java 7 server, same goes for plugin developers. Part of why we upgraded was because two of our dependencies kicked Java 7 out of their picture.
