### ISSUE TITLE
Add new method to api

### ISSUE THREAD

**Issue by Dimatert9** [Xephi/AuthMeReloaded#950]
unregister(String name(any case));

**Comment by ljacqu** [comment]
@Dimatert9 Done—please verify.

First I thought that you could just do:
```java
Player player = Bukkit.getPlayer("userToUnregister");
api.forceUnregister(player);
```

but then I realized we might have some players in the DB that have never been on the server. So it makes sense to have `NewAPI#forceUnregister(String)` :)

**Comment by sgdc3** [comment]
@ljacqu I think he needs a way to unregister someone not ingame.

**Comment by ljacqu** [comment]
@sgdc3 That's what the method does.

**Comment by Dimatert9** [comment]
```NewAPI#forceUnregister(String)```
This will work if player is offline?

I want to make plugin that remove all users, who dont have donate.
What i want:
1) Get all users from authme.
``` 
    for (final String pl : NewAPI.getInstance().getRegisteredNames()) {
  list.add(pl.toLowerCase());
}
```
2) 
Get all users from PEX:
```
        for (final PermissionUser user : PermissionsEx.getPermissionManager().getUsers()) {
                    final String name = user.getName();
                    if (list.contains(name.toLowerCase())) {
                        list.remove(name.toLowerCase());
     }
}
```
3) Unregister all players in "list"

**Comment by ljacqu** [comment]
@Dimatert9 Yes, that would work. You don't have to lowercase `pl` btw because `getRegisteredNames` will return everything lowercase, as opposed to `getRegisteredRealNames` :)

After that you just need to call NewAPI's `forceUnregister(name)` for each `name` you want.

**Comment by Dimatert9** [comment]
thanks. it work.

**Comment by ljacqu** [comment]
Thanks for the feedback
