### ISSUE TITLE
Firstspawn issue

### ISSUE THREAD

**Issue by afronights** [Xephi/AuthMeReloaded#951]
I'm running AuthMeReloaded v5.2-BETA3 (build: 1134) and the **setfirstspawn** command doesn't work for me.

When I log for the first time authme don't teleport the player to the authme firstspawn 
My configuration is http://pastebin.com/Q1GQpuCB

I tried several configuration like:
ForceSpawnLocOnJoin true
teleportUnAuthedToSpawn: false
and 
ForceSpawnLocOnJoin false
teleportUnAuthedToSpawn: true
or
ForceSpawnLocOnJoin true
teleportUnAuthedToSpawn: true
or 
ForceSpawnLocOnJoin false
teleportUnAuthedToSpawn: false
 but authme will spawn the player at the main spawn world point ! every time

My plugin are:
AuthMe-5.2-BETA3-spigot
Multiverse-Core-2.5
PermissionsEx-1.23.3
Vault
VoidGenerator

I'm running in local with Standalone server with Bukkitgui and version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by ljacqu** [comment]
```yml
        # AuthMe will NEVER teleport players if set to true!
        noTeleport: true
```

Please change that to `false` and let us know if it solves your issue.

**Comment by afronights** [comment]
Thank you ljacqu, now work !!!!!!

**Comment by sgdc3** [comment]
@afronights Thank you for the feedback ;)
