### ISSUE TITLE
Spawn unlogged location and spawn logged location

### ISSUE THREAD

**Issue by afronights** [Xephi/AuthMeReloaded#953]
I'm running AuthMeReloaded v5.2-BETA3 (build: 1134) and i would like to have a little room for receive unlogged player for logging/registering operation and teleports automatically it to another world (in a another spawn location).

I could not do it. 
I do it partially only with ForceSpawnLocOnJoin: false and teleportUnAuthedToSpawn: true but after the teleport the position is always the last disconnected of the player and not the spawn wanted !!!

My plugin are:
AuthMe-5.2-BETA3-spigot
Multiverse-Core-2.5
PermissionsEx-1.23.3
Vault
VoidGenerator
CustomJoinItems
Essentials-2.x
EssentialsChat-2.x
EssentialsGeoIP-2.x
FancyPortals
FeatherBoard
HolographicDisplays_2.2
hub
LibsDisguises_867
NoCheatPlus
Parkour
ProtocolLib_41
SkinsRestorer-v12.6.1
SpawnJoin_5.1.6v
UltraCosmetics-2.3.9-RELEASE
worldguard-6.1
worldedit-bukkit-6.1

I'm running in local with Standalone server with Bukkitgui and version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by sgdc3** [comment]
Please undate to latest dev build and try again.

**Comment by afronights** [comment]
Sorry my build was 1378 and no 1134.

Now with the 1384 i have the same behaviour.

**Comment by afronights** [comment]
what the different from AuthSetSpawn and AuthFirstSpawn ?

**Comment by afronights** [comment]
Ok problem solved ! Now the teleport works correctly.

Thank you for the support !!!!

**Comment by sgdc3** [comment]
Ok, fine, sorry if i haven't answer you but i've been very busy. Thank you ;)
