### ISSUE TITLE
Managing multiacconts (Any advice? Or possible enhancement?)

### ISSUE THREAD

**Issue by MithrandirCraft** [Xephi/AuthMeReloaded#954]
A true dilema for Factions servers:

Users register more than one account in order to get more faction power.

The administrators notice this and try to solve the issue by blocking more than one IP from logging in.
This "kinda stops" multiaccounts.

However, now player groups cannot play on the server if they are using the same internet connection.

So IP restrictions are not the perfect solution. Any advice on how to manage this situation?
Could a more advanced management of account registry per IP availability be implemented?
Players should also not be capable of bypassing this by reseting their IP. Once a player is detected having logged in to the server more than one single account, he/she should be blocked or maybe unregistred.

An Idea (Which is not be perfect), in case there is no propper way of managing this currently already: Server login and max registration tiers, with corresponding permission nodes. Example:

(Existing) Max registrations per IP: 1
(New config) Max different accounts having been logged from same IP (Not simultaneously): 1
(New config) Registry slots specific permission:
Slots: 3
Permission: registerlimitthree
(New config) Login different accounts slots specific permission:
Slots: 3
Permission: loginlimitthree

Permission node -> 3 registry slots: authme.registerlimitthree
Permission node -> 3 different logins: authme.loginlimitthree

This suggestion would allow giving players more registration/access allowances for performing certain tasks. But I'm not entirely convinced by it.

I may have taken it too far with my suggestion xD (I've seen custom permission nodes on some other plugins) but some kind of control with muliaccounts would be VERY usefull.

**Comment by Eufranio** [comment]
The best would be a ready web register application, like Prism does, and limit 2 register per IP/use cookies to prevent 2 registers in the same machine.

**Comment by MithrandirCraft** [comment]
@Eufranio Thanks for the suggestion, I will consider this 👍

**Comment by Twonox** [comment]
Or allow 1 account per MAC address, but idk if it's possible

**Comment by Eufranio** [comment]
Not via web/minecraft, only using a program :/

**Comment by sgdc3** [comment]
>Or allow 1 account per MAC address, but idk if it's possible 

Your MAC is not exposed to external networks like internet

**Comment by sgdc3** [comment]
@MithrandirCraft It's impossible to archieve that, even with web registration i can use multiple browser or reset the cookies

**Comment by Eufranio** [comment]
But it's more secure. A normal banned player world search for "how to join a server being banned" and the majority or all tutorials would be use a VPN/restart the router. Using cookies and IP registration would add one more security layer.

**Comment by DNx5** [comment]
set your server to online mode.

**Comment by MithrandirCraft** [comment]
@DNx5 We all know players don't want to spend money on more than one account, but even that isn't safe :P

**Comment by sgdc3** [comment]
I'm sorry but we can't do anything about that :(

**Comment by MithrandirCraft** [comment]
Understandable.
