### ISSUE TITLE
Request : Messages

### ISSUE THREAD

**Issue by TheIntelloBox** [Xephi/AuthMeReloaded#955]
Hello,

I have a little suggestion.
Could you add an option to disable the messages on the console ?
I speak about these messages : 
http://zupimages.net/up/16/38/a7et.jpg

Thanks ! :D
TheIntelloBox.

**Comment by rErEaT** [comment]
turn off the mysql

**Comment by sgdc3** [comment]
We can't control such messages, i'm sorry.
