### ISSUE TITLE
Server stop with authme 5.2-DEV-September

### ISSUE THREAD

**Issue by Cri16228** [Xephi/AuthMeReloaded#958]
What happened?
When I start my local server (for setting plugin only)  it crashes
Only this no plugins, no log. Default config.yml
After installing authme 5.2-DEV-September and starting server it stop automatically
If you want a log file http://hastebin.com/lagivimere.md

**Comment by ljacqu** [comment]
Please share your authme.log output - it should contain more detailed information about the error

**Comment by Cri16228** [comment]
Solved with [this](https://dev.bukkit.org/bukkit-plugins/authme-reloaded/files/79-auth-me-5-2-beta-3/)
[AuthMe.log](http://hastebin.com/ziticihori.pas)

**Comment by ljacqu** [comment]
```
Caused by: java.lang.NoClassDefFoundError: Lcom/google/gson/Gson
```
I think you downloaded the wrong JAR for your server version; it looks like you need the legacy one. https://github.com/AuthMe/AuthMeReloaded/wiki/AuthMe-Releases-(Jenkins)
Should this not solve the problem, please reopen / add a comment.
