### ISSUE TITLE
I can not move after login AuthMe

### ISSUE THREAD

**Issue by GDXX** [Xephi/AuthMeReloaded#962]
Hey,
I am unable to move after login  I use 
cauldron-1.7.10-2.1403.1.54

AuthMe-5.2-SNAPSHOT-legacy

**Comment by ljacqu** [comment]
Please upgrade to a more recent version http://ci.xephi.fr/job/AuthMeReloaded/
Assuming you're using anything below 5.2-b1300 (`/authme version`)

**Comment by GDXX** [comment]
I tested with build in 1391 I still have the bug after login I can not move

**Comment by ljacqu** [comment]
Does the workaround in https://github.com/Xephi/AuthMeReloaded/issues/890#issuecomment-239596517 work for you? Otherwise please post your config file to [hastebin.com](http://hastebin.com), removing any sensitive data.

**Comment by GDXX** [comment]
I use the default config

**Comment by DNx5** [comment]
I couldn't reproduce it, using Cauldron-1.7.10-2.1403.1.54 with only latest AuthMe build.

**Comment by sgdc3** [comment]
@DNx5 could you verify that if the player speed is 0 it is reverted back to default one?

**Comment by DNx5** [comment]
@sgdc3 it does restore the player speed

**Comment by GDXX** [comment]
It's good for me it works thanks guys 

AuthMe-5.2-SNAPSHOT-legacy build 1416

**Comment by DNx5** [comment]
😄 closing this
