### ISSUE TITLE
Create tool task to generate plugin.yml

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#963]
When we add new permissions we need to keep the plugin.yml file in sync - create a tool task that will update the permissions data in there.

**Comment by ljacqu** [comment]
Hi @sgdc3, if it looks OK to you please close the issue or let me know if there's something I can improve. I tested the plugin in game and all commands worked well; didn't test permissions though because the diff is minimal and permission consistency test passed.

**Comment by sgdc3** [comment]
@ljacqu Whoops, i forgot to feedback, yeah it looks very good, thank you ;)
