### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by jugtej** [Xephi/AuthMeReloaded#965]
well ijacqu the login issue is back. I cant post in the old post so i had to make a new one 
this is my console http://pastebin.com/sx1t10vy
i have not been able to find anything that would not let me login. the only chat plugins i have is essnetials chat and simple prefix

**Comment by sgdc3** [comment]
You are using many old plugins, you should remove EssentialsXampp and switch to EssentialsX

**Comment by sgdc3** [comment]
Install that plugins:
https://ci.drtshock.net/job/essentialsx/lastSuccessfulBuild/artifact/Essentials/target/EssentialsX-2.0.1.jar
https://ci.drtshock.net/job/essentialsx/lastSuccessfulBuild/artifact/EssentialsChat/target/EssentialsXChat-2.0.1.jar
https://dev.bukkit.org/bukkit-plugins/simple-prefix/
http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT-spigot.jar

**Comment by ljacqu** [comment]
Duplicate of #961 (don't mind this comment, just linking the issues)
