### ISSUE TITLE
WARN

### ISSUE THREAD

**Issue by Kixot14** [Xephi/AuthMeReloaded#966]
Why this WARN happen ??

_[00:49:15 WARN]: [Server thread] INFO fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Started._

It's happen, when server started and when server closed.

**AuthMe build 1292
Spigot build 965**

**Comment by Kixot14** [comment]
Looks like it's just notify about AuthMe MySQL connection. But why WARN ???

**Comment by sgdc3** [comment]
Caused by our connection pool, we can't change that.

**Comment by Kixot14** [comment]
@sgdc3, so nothing serious? I can just skip this and dont warry about this warn ??

**Comment by sgdc3** [comment]
Yeah, it's fine
