### ISSUE TITLE
stesso problema sgdc3 o maxetto aiuto !!

### ISSUE THREAD

**Issue by MCG-server** [Xephi/AuthMeReloaded#969]
perche lo stesso problema perchè l email recovery non mi ricordo piu come si faceva (non basta mettere l email e la password dell accaunt ma mi riocrdo che bisognava smanettare anche sul account della email ) quest ultima parte non mi ricordo più @Maxetto  @sgdc3  
versione di spigot : 1.8.4
versione plugin authme: ultima versione (last version)           ma va bene l ultima versione di authme con 1.8.4 di spigot?? ( a me da quello che vedo funziona tutto)

english 
because the same problem because the email recovery I do not remember most as it was (not just put the email and password of accaunt but riocrdo me that it was also necessary to tweak on the email account) this last part I do not remember 
translated with google translator

**Comment by sgdc3** [comment]
Se usi gmail devi consentire le app non sicure: https://support.google.com/accounts/answer/6010255?hl=it
