### ISSUE TITLE
Email recovery system

### ISSUE THREAD

**Issue by WaterXCubic** [Xephi/AuthMeReloaded#97]
The email recovery system is dangerous,i dont know if its only my setting,when i just complete the setting of the system in the config system,i tried to use /email recovery xxx in game and the server just stop and crashed

**Comment by sgdc3** [comment]
Can you post the server log?

**Comment by WaterXCubic** [comment]
How do i get it??:[

**Comment by WaterXCubic** [comment]
Do u mean the error logs?

**Comment by WaterXCubic** [comment]
I am using the bukkit gui 1.8.0.541

**Comment by sgdc3** [comment]
1) start the server
2) execute email command
3) *crash*
4) copy the content of /logs/latest.log
5) paste the content on pastebin
6) copy the link from pastebin and paste it on the issue

**Comment by WaterXCubic** [comment]
http://pastebin.com/vk9n1P2S

**Comment by Trojaner25** [comment]
Mails should be send Async... Never do networking on main thread...

**Comment by Xephi** [comment]
Can you please test with latest dev build ?

**Comment by sgdc3** [comment]
Atm this link works! http://xephi.fr:8080

**Comment by sgdc3** [comment]
@WaterXCubic now jenkins is online! Pick up latest build at ci.xephi.fr

**Comment by Xephi** [comment]
Fixed
