### ISSUE TITLE
Make startup time of Antibot configurable

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#970]
Antibot waits 90 seconds before actually going into LISTENING mode upon start / reload of the plugin; this should probably be configurable. Also has the advantage that the user knows about this behavior when he sees the configurable value in the config.

(via #896)

**Comment by ljacqu** [comment]
@sgdc3 Sorry it took so long to fix the tests; I had trouble to make the new one pass.

If there's nothing open on your side this is fine too close; I tested this extensively in-game.

**Comment by sgdc3** [comment]
Fine, thank you ;)
