### ISSUE TITLE
ho un paio di domande poi basta (almeno che non trovo qualche bug)

### ISSUE THREAD

**Issue by MCG-server** [Xephi/AuthMeReloaded#971]
@sgdc3   se uso yahoo cosa devo fare ??  
poi qualche host (che non sia turbosmpt ) per queste cose di smpt (possibilmente gratuito)
quante email giornaliere posso inviare con gmail , e con yahoo? 

a proposito di bug è vero quella cosa che ti mette su 0 la velocità di movi mento e di fly (credo che succede solo per il primo che si logga o solo ai founder )

**Comment by sgdc3** [comment]
>a proposito di bug è vero quella cosa che ti mette su 0 la velocità di movi mento e di fly (credo che succede solo per il primo che si logga o solo ai founder )

Ok

>se uso yahoo cosa devo fare ??

Sinceramente non lo so perché non uso yahoo, non potresti creare un account gmail apposito per il server?

>poi qualche host (che non sia turbosmpt ) per queste cose di smpt (possibilmente gratuito)
quante email giornaliere posso inviare con gmail , e con yahoo?

Mi spiace ma non conosco servizi simili

Se hai ulteriori domande ti prego di scrivere sempre in questa segnalazione, anche se chiusa.

**Comment by MCG-server** [comment]
quante email (smpt ) posso inviare con gmail?? (al giorno)

**Comment by MCG-server** [comment]
quante e-mail posso inviare al giorno con questo smpt ?? 

e poi la cosa piu importante come creo un server mysql sul mio computer ?? @sgdc3

**Comment by sgdc3** [comment]
>quante email (smpt ) posso inviare con gmail?? (al giorno)
500

**Comment by sgdc3** [comment]
> e poi la cosa piu importante come creo un server mysql sul mio computer ?? 
Esiste google :P

**Comment by MCG-server** [comment]
ok apro un altro post perche ho trovato un errore

**Comment by MCG-server** [comment]
si lo so che esiste google ma i tutorial sono tutti vecchi

**Comment by MCG-server** [comment]
credi che non ho cercato 
?? ho visto dei video ma certi sono vecchi e certi non spiegano bene ....uno che magari hai visto te ??

**Comment by sgdc3** [comment]
@MCG-server Non siamo un servizio assistenza....
