### ISSUE TITLE
Failed to send email (Gmail SMTP Connection)

### ISSUE THREAD

**Issue by MCG-server** [Xephi/AuthMeReloaded#972]
error:  http://hastebin.com/getafacabo.sql
spigot version : 1.8.4
authme version: latest

**Comment by sgdc3** [comment]
@ljacqu any idea? The connection parameters looks correct.

**Comment by ljacqu** [comment]
This is the typical error I get when I try to run from inside IntelliJ. If someone else can successfully send emails from Gmail we're sure it's a problem on the machine. 
@Mcg-server is this error locally or on some server?

**Comment by MCG-server** [comment]
@ljacqu locally

**Comment by MCG-server** [comment]
@ljacqu you are getting the error?

**Comment by MCG-server** [comment]
ei? @sgdc3  @ljacqu

**Comment by ljacqu** [comment]
do you need to run a server that sends email locally? this is an error with your machine, not from authme -> labels adjusted accordingly

**Comment by MCG-server** [comment]
What do you mean by problmei machine? @ljacqu

**Comment by MCG-server** [comment]
I wanted to see if everything worked @ljacqu

**Comment by ljacqu** [comment]
This is an issue with the environment in which the server is run; it's missing some stuff to support SSL certificates. I don't know the details. If you don't really _need_ to send emails locally (I expect this will happen on a server in a real situation) I'd like to suggest to close this.

**Comment by MCG-server** [comment]
before closing I would like to make a couple of questions
1) the latest version of Authme also works for version 1.8.4 ??
2) Who can I ask you a favor (that I would serve a good one that helps me fix errors in the console @ljacqu

**Comment by ljacqu** [comment]
Latest AuthMe version works with 1.8.4.

If you're encountering any other problems please create a Github issue. Just don't create more than one issue per problem please and provide a description we can understand.
