### ISSUE TITLE
Create doc page listing translations

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#976]
Auto-generated page with all available languages and translation percentage (e.g. "95% translated"). English on top, rest alphabetically

**Comment by ljacqu** [comment]
https://github.com/AuthMe/AuthMeReloaded/blob/master/docs/translations.md

**Comment by sgdc3** [comment]
Amazing, thank you :)

**Comment by ljacqu** [comment]
Haha, cheers :wink:
