### ISSUE TITLE
Thread starvation or clock leap detected

### ISSUE THREAD

**Issue by astr1al** [Xephi/AuthMeReloaded#977]
### What happened?

TPS drops to nearly 0 and the console gets spammed with a message about thread starvation.
### What did you expect?

A silky smooth auth system like this plugin has been for years ;)
### The actions that cause the issue.

Just seems to happen randomly. Most recent was yesterday morning with nobody online.
### Plugin list:

Heheh, I have a lot.... Haven't started having this issue until about a month ago. http://pastebin.com/RGCAWkT1
### Environment description

Windows 7 64 Bit, Java 8 64 bit. 8-core 3.8 Ghz AMD 8150, 32 Gb system memory 8 Gb allocated to main server, 512 Mb allocated to redirect server. Standalone Server utilizing MySQL database. There is a bungee server running but is simply acting as a redirect from our old server IP.
### AuthMe build number:

[build: 1046](http://ci.xephi.fr/job/AuthMeReloaded/1406/)
### Error Log:

http://pastebin.com/nddG92ur
### Configuration:

http://pastebin.com/RArcEqW4

**Comment by sgdc3** [comment]
This seems a deadlock detected by our dbcp, let me check if a new version of the lib is available...

**Comment by sgdc3** [comment]
Nope,  @ljacqu we haven't changed anything related to the dbcp or mysql recently, it sounds very strange. Should we trybto downgrade hikaricp version?

**Comment by ljacqu** [comment]
@astr1al has the log you sent been shortened or did this really just happen when the server was super calm? Do you regularly restart your server or could it be that it was online for like a week or so?

**Comment by astr1al** [comment]
@ljacqu that's the complete snipet from the log. It was early morning so it was pretty dead. The server is on a 24 hour reload schedule.

**Comment by DNx5** [comment]
@astr1al If you didn't see any problem, like cpu usage increased, then its fine.

**Comment by astr1al** [comment]
But what about server dropping to less than a few TPS?

**Comment by DNx5** [comment]
yes, that maybe the cause, you should find the plugin that cause the lag.

**Comment by sgdc3** [comment]
@astr1al any update?

**Comment by astr1al** [comment]
No, had another instance of AuthMe MySQL thread starvation yesterday. The issue is too elusive to replicate as it only seems to pop up every other week. 

I do use Prism which is basically a build/break logger and that has a massive mysql db. Could that have an effect?

**Comment by astr1al** [comment]
@DNx5 I've used AutmMe Reloaded for years and have been though many instances where a plugin would bring TPS to a crawl and AuthMe never had issues from it before.

**Comment by DNx5** [comment]
@astr1al the message is from our database connection pool. it will pop up if they find a big difference between current timestamp with last stored timestamp. this usually happen if your server is overloaded or the system time has changed.
you could do timings while that problem happens.

**Comment by ljacqu** [comment]
hi @astr1al, without timings this issue is stuck. Any update?
