### ISSUE TITLE
Cannot use "help" as password

### ISSUE THREAD

**Issue by Maxetto** [Xephi/AuthMeReloaded#987]
As discussed in PR #[172](https://github.com/AuthMe/AuthMeReloaded/pull/172), you cannot use "help" as password because it would trigger the help page.

We could fix it by hard disabling the password "help" (the easy way) or we could check if "help" is the password before triggering the help page (the best way).

Now, since by default password need to be longer than 5 characters, I'd rather go with the easy way.

Note: This is an issue mostly when changing password, as if you try to register (/register help help) it would trigger the register's help page.

**Comment by ljacqu** [comment]
probably the simplest solution is to add "help" as an unsafe password in the default config. This way we don't need to implement & maintain this additional check in the code.

**Comment by Maxetto** [comment]
Yeah, can do. Maybe add a comment to it reporting that it isn't an unsafe password but may break the plugin
