### ISSUE TITLE
Replace link to config.yml on Bukkit page

### ISSUE THREAD

**Issue by ljacqu** [Xephi/AuthMeReloaded#989]
plugin.yml is now auto-generated and no longer part of the project's source code, but https://dev.bukkit.org/bukkit-plugins/authme-reloaded/ still has a link to config.yml on Github which now returns a 404.
- Create a tool task that creates an up-to-date config.yml file like other doc pages we have
- Replace the link on the Bukkit page with the new docs page

**Comment by sgdc3** [comment]
We should create a new doc page with a pregenerated config

**Comment by ljacqu** [comment]
Good idea! Description updated accordingly; I can create a docs page probably still today.

**Comment by ljacqu** [comment]
@sgdc3 https://github.com/AuthMe/AuthMeReloaded/blob/master/docs/config.md – what do you think?

One improvement I want to do is limit the comment length so we don't have a horizontal scrollbar. Probably a max of ~90 characters per comment line.

**Comment by sgdc3** [comment]
Looks good! Already linked to devbukkit ;)

**Comment by ljacqu** [comment]
Cheers! :smile:
