### ISSUE TITLE
Line break not working in messages

### ISSUE THREAD

**Issue by YellowZaki** [Xephi/AuthMeReloaded#993]
### What behaviour is observed:
I had installed on my server an old build. In my messages.yml, I could use line breaks using &n.
Now I updated to the latest build, and it doesn't work.

### Environment description
Spigot

### AuthMe build number:
Build 1443

**Comment by ljacqu** [comment]
Correct, please replace any uses of `&n` for a new line to `%nl%`. This was changed a few months ago.
https://github.com/AuthMe/AuthMeReloaded/wiki/Breaking-Changes
