### ISSUE TITLE
Authme login prompt

### ISSUE THREAD

**Issue by yyeerai** [Xephi/AuthMeReloaded#996]
Player for a long time after landing, authme just login prompt, this time is about 5-10 s.

I think and asynchronous processing, authme slowly to read data

**Comment by sgdc3** [comment]
Could you post your timings with the "useAsyncTasks" option set to true and then to false?

**Comment by yyeerai** [comment]
Landing useAsyncTasks is set to true, the player will be stuck in landing interface for a long time.

**Comment by sgdc3** [comment]
Could you post some timings reports please? ('/timings on', wait 5 mins while trying to login more times, '/timings paste', copy and paste the link)

**Comment by sgdc3** [comment]
@yyeerai

**Comment by yyeerai** [comment]
https://timings.aikar.co/v2/?id=5edaedaa3e7e4ffb952e34d796168d9e&raw=1

**Comment by sNuuFix** [comment]
Having the same problem on perfectly idle server with 20TPS. Appending config option useAsyncTasks: false seems to solve this problem. As I'm using MySQL database with indexes in ram, I don't mind to put some load on it.

Will useAsyncTasks: false cause other problems? Why isn't it in default config?

**Comment by sNuuFix** [comment]
My bad. This seems like an issue with other outdated plugins, as I was removing optional stuff and redownloading it, AuthMe started to work flawlessly and showed up instantly.

**Comment by ljacqu** [comment]
Thanks for the update, @sNuuFix, that's good to know :)

**Comment by ljacqu** [comment]
@sgdc3 Could you have a look at the posted timings, please? What's your interpretation?

**Comment by sgdc3** [comment]
Maybe a slow MYSQL DB? What's your DB backend @yyeerai ?

**Comment by Twonox** [comment]
Maybe related to #1050 ?

**Comment by sgdc3** [comment]
Yes, now it's fixed, @Twonox thank you ;)
