### ISSUE TITLE
Option to deny registration for same usernames with different capital letters

### ISSUE THREAD

**Issue by YellowZaki** [Xephi/AuthMeReloaded#997]
I have a big problem using Essentials and it can be solved with authme.
Steps to reproduce problem:
1 Let's say the player "Test" get registered.
2 He play and he wins 100$
3 He quits, and he join the server with the name "TeSt" and he registers.
4 The player "TeSt" has 100$ too, and he pay those 100$ to player "X"
5 Now he join with the initial username "Test" and he keeps having 100$, and he pay 100$ to player "X"
6 Conclusion: he has duplicated his balance

What I would like: an option on authme to kick players who join with the same username but with different capital letters. Like: Kicked by: "Your username TeSt is already being used by Test"

I hope you understand this issue, thanks.

**Comment by ljacqu** [comment]
Counter question, wouldn't this be solved by setting the following in the config?

```yml
    # Do we need to prevent people to login with another case?
    # If Xephi is registered, then Xephi can login, but not XEPHI/xephi/XePhI
    preventOtherCase: true
```

**Comment by sgdc3** [comment]
Uh yes, i misread the request xD

**Comment by sgdc3** [comment]
This feature have been tested for months, it works well.
